### DISCUSSION TITLE
less restrictive "passed" semantics for fan-in on a microservices monorepository

### DISCUSSION THREAD

**Discussion by tkellen** [concourse/concourse#4949] [General]
## What challenge are you facing?
I want to visually show that a task depends on a successful build of numerous discrete jobs that will never share the same commit.

I have a monorepository that deploys ~20 odd microservices. Our `master` pipeline has one build/deploy job per project. Each project build/deploy job pair has its own resource watching the master branch for changes in its project folder only. I would like to "fan in" off of all the project deploys builds to run e2e testing.

Current "passed" semantics assume there will be one shared commit for all "passing" builds. In my context, this commit will never occur without making a spurious dummy commit affecting all projects. Each project is self-contained even though it appears on the same pipeline.

## What would make this better?
If it was possible to indicate that passing only required a current/successful build of the dependent tasks.

## Are you interested in implementing this yourself?
Yes! I just need feedback on the approach. I see two possible solutions:
```
plan:
- get: a
  anyPassed: [a-unit, integration]
- get: b
  anyPassed: [b-unit, integration]
- get: x
  anyPassed: [integration]
```
...or
```
plan:
- get: a
  passed:
  - name: a-unit
    group: null (my semantics, we don't care about the same commits between these) 
  - name: integration
    group: null (my semantics, we don't care about the same commits between these)
- get: b
  passed:
  - name: b-unit
    group: pass-group (existing semantics but allowed to group different sets of passing)
  - name: integration
    group: pass-group (existing semantics but allowed to group different sets of passing)
- get: x
  passed: ['integration'] (existing semantics)
```

**Comment by vito** [comment]
Hey, I think I have a vague notion of the problem you're talking about but it's so far off in my memory that I'm having a hard time piecing it together from the example given so far. Would you be able to provide a working example to demonstrate the use case? This stuff's tricky to convey with words. :sweat_smile: Thanks in advance!

Here's my attempt, but I found myself with more questions than answers (embedded as comments):

```yaml
---
resources:
- name: a
  type: git
  source:
    uri: ...
    paths: [a/]

- name: b
  type: git
  source:
    uri: ...
    paths: [b/]

- name: x
  # does this relate to a or b or is it just here for example?
  # type:
  # source:

jobs:
- name: a-unit
  plan:
  - get: a

- name: b-unit
  plan:
  - get: b

- name: integration
  plan:
  - get: a
    passed: [a-unit]
  - get: b
    passed: [b-unit]
  - get: x
    # does this relate to a-unit or b-unit?

  # actually, i guess if you're integrating everything, is 'x' actually the
  # monorepo itself?

- name: ship
  plan:
  - get: a
    # why not just depend on [integration] here?
    passed: [a-unit, integration]
  - get: b
    passed: [b-unit, integration]
  - get: x
    passed: [integration]
```

**Comment by tkellen** [comment]
PS: as somewhat of an aside, the fact that concourse can tolerate successfully having its pipelines rewrite themselves and that the UI just updates automatically and everything works is flipping amazing. Ya'll have made an amazing tool and I love using it.

**Comment by tkellen** [comment]
Well. That took a bit. Here's a shell script that reproduces the issue. To run it you must:
1. Change `REPO` a git repo URI you can push to from your local machine.
2. Change `CONCOURSE_TARGET` to point to a concourse in your `~/.flyrc` (that can also clone the repo located at `REPO`).
3. Not have a folder `test-folder` in the directory where you execute the script (at least, not the very first time).

When you run the script, it will:
1. Make a repo and push some initial commits to master.
2. Make a feature branch based on the time.
3. Create a pipeline that watches the branch.
4. Pause execution with instructions that describe the issue.
5. Push another commit to make the issue visible after you allow it to.

It should be possible to run this as many times as you need and it will replace the pipeline with a new one pointing to a new branch each time.
```sh
#!/usr/bin/env bash
REPO="https://github.com/tkellen/concourse-passed-issue.git"
CONCOURSE_TARGET="dev"
REPO_FOLDER="test-repo"
BRANCH="feature-$(date '+%H%M')"

# create repo
if [[ ! -d ${REPO_FOLDER} ]]; then
(
  mkdir ${REPO_FOLDER}
  cd ${REPO_FOLDER}
  git init
  git remote add origin ${REPO}

  # create mock app source and deployment config
  mkdir -p projects/service/deployments/dev
  echo "hello world" > projects/service/main
  echo "APP_DB_NAME=hello-world" > projects/service/deployments/dev/config
  git add -A
  git commit -m "add app"

  # create mock shared deploy script
  mkdir -p bin
  printf "#!/bin/sh\necho deploying\ncat -" > bin/deploy-script
  chmod +x bin/deploy-script
  git add -A
  git commit -m "create shared deploy script"

  # create end to end testing script
  mkdir -p projects/shared/e2e
  printf "#!/bin/sh\necho testing" > projects/shared/e2e/main
  chmod +x projects/shared/e2e/main
  git add -A
  git commit -m "create end to end testing script"

  # push to origin
  git add -A
  git push -u origin master -f
)
fi

# create a feature branch for this test
(
  cd ${REPO_FOLDER}
  git checkout master # for repeat runs of this script
  git checkout -b ${BRANCH}
  git push origin ${BRANCH} -f
)

# build pipeline
fly -t dev dp -p test -n
fly -t dev sp -p test -n -c <(cat <<EOF
jobs:
- name: build-service
  serial: true
  plan:
  - get: service-source
    trigger: true
  - task: build
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: service-source
      platform: linux
      run:
        path: /bin/true
- name: deploy-service
  plan:
  - in_parallel:
      steps:
      - get: service-source # used to trigger a deploy after a
        passed:             # build. without this we would only
        - build-service     # deploy on config changes.
        trigger: true
      - get: service-config # used to trigger a deploy when
        trigger: true       # files affecting config change
      - get: e2e            # only here so we can use passed
  - task: run-deploy-script
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: service-config
      platform: linux
      run:
        path: sh
        args:
        - -c
        - service-config/bin/deploy-script < service-config/projects/service/deployments/dev/config
- name: e2e
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: e2e
        passed:
        - deploy-service
        trigger: true
      - get: every-minute
        trigger: true
  - task: run-tests
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: e2e
      platform: linux
      params:
        APPS: "service"
      run:
        path: e2e/projects/shared/e2e/main
resources:
- name: service-source
  type: git
  icon: git
  source:
    branch: ${BRANCH}
    paths:
    - projects/service/*
    uri: ${REPO}
- name: service-config
  type: git
  icon: git
  source:
    branch: ${BRANCH}
    paths:
    - projects/service/deployments/dev*
    - bin/deploy-script
    uri: ${REPO}
- name: e2e
  type: git
  source:
    branch: ${BRANCH}
    uri: ${REPO}
    paths:
    - projects/shared/e2e/*
- name: every-minute
  type: time
  source:
    interval: 1m
EOF
)
fly -t ${CONCOURSE_TARGET} up -p test

cat <<EOF
Please follow these steps.
1. view pipeline
2. build will succeed (runs /bin/true)
3. deploy triggers after build (runs deploy script on project config)
4. e2e will trigger on deploy pass and every minute after
5. once this cycle completes, hit enter and the e2e suite will be modified
   but it will not trigger because it has not "passed" through the deploy
   and every 10 minutes it will run with the "wrong" commit.
EOF
read

# modify e2e test script
(
  cd ${REPO_FOLDER}
  printf "#!/bin/sh\necho testing new" > projects/shared/e2e/main
  git add -A
  git commit -m "modify end to end testing script"
  git push origin ${BRANCH} -f
)
```
This boils the problem down to shortest / easiest possible representation I could muster. Before you say to switch the `passed` declaration to `service-source` instead of e2e remember that more complex versions of this pipeline have N completely distinct "service-sources" (one for each project).

God, I hope this make some sense. Thanks in advance once more for looking at this.

**Comment by tkellen** [comment]
Gentle nudge @vito. Just to say it, I'm not looking for you to resolve this issue, I'm more than happy to contribute the feature if we can identify an approach that makes sense.

**Comment by vito** [comment]
Woops sorry forgot to check back on this! I'll save a bookmark and remember for tomorrow. :stuck_out_tongue: 

...but if I keep forgetting keep poking me, I do want to get to the bottom of this!

**Comment by tkellen** [comment]
No worries, I know this issue represents a corner case without a ton of impact given all you're trying to accomplish right now. Thanks for taking a look! I'll be happy to keep pinging now that I know I'm not bothering you :smile:

**Comment by vito** [comment]
@tkellen Thanks for working on a repro, I was able to verify it myself and it really helped me see the problem!

To test my understanding, I'm going to put myself in your shoes and try to express what you're trying to do:

* I want my pipeline to run against a single monorepo, which would most intuitively be represented as a single resource, as I plan to "fan in" on it later in the pipeline.
* For any versions (commits) which affect files under `projects/service/deployments/dev*`, run the `build-service` and `deploy-service` jobs.
  * For any versions which *don't* affect files under this path, treat them as if they had `passed` the jobs implicitly.
  * If these jobs fail, downstream `passed` constraints should not be able to progress past the failed version.
* Repeat above point for any other sub-paths.
* At the very end of the pipeline, I would like to fan in on the monorepo resource across all upstream `deploy-*` jobs and run tests in an `e2e` job.
  * This will naturally pick up changes to only the `e2e` suite or any other files in the repo, as all commits will have implicitly passed all upstream jobs.

Does this sound accurate?

(Assuming it is, ...)

The most challenging aspect to me is the 'implicit' behavior of propagating versions which don't affect the required paths.

Say the following sequence happens:

1. User pushes a commit which changes the affected paths; jobs run and go green. Versions flow along to downstream `passed` constraints.
1. User pushes a commit which does *not* change the affected paths; versions implicitly flow along to downstream `passed` constraints.
1. User pushes another commit which changes the affected paths; jobs run and *fail*.
1. User pushes a commit which does *not* change the affected paths.

In this case, we have to be sure *not* to implicitly flow these newly pushed commits along, as the most recent build has failed. Tricky, huh?

Sidebar: I have no idea how we would make this implicit propagation clear in the UI. It's kind of interesting to reason about and mentally visualize, and it strikes me as something that may be represented in a better way than with `passed` constraints, but I'm not sure how. :thinking:

**Comment by tkellen** [comment]
@vito thank you for taking the time to look at this. I'm so glad the reproduction made sense, it was pretty hard to make this behavior easily understandable and repeatable :relieved:.

Your description of my workflow is almost correct but I don't think it's worth trying to describe the subtle places where it is wrong because the sequence you outlined as being intractable has made me realize we need to be thinking about this concept in an entirely different way.

I can see now that what I'm actually reaching for is a way to express dependencies between jobs without referencing resources at all. **In my context, the resources / versions are not related.** My workaround for the problem being described in this issue is to not use `passed` at all. Today, I just have an e2e box floating on its own running all the time, many times when it shouldn't.

In effect, the only reason I ever used  `passed` was to trick the concourse UI into showing what I visually want to see. It seems the config I actually need looks something like this:
```yaml
- name: e2e
  serial: true
  depends_on:
  - task: deploy-service-bar
    state: passing
  - task: deploy-service-foo
    state: passing
  plan:
  - in_parallel:
      steps:
      - get: e2e
        trigger: true
      - get: every-minute
        trigger: true
  - task: run-tests
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: e2e
      platform: linux
      params:
        APPS: "service"
      run:
        path: e2e/projects/shared/e2e/main
```

Here is a visual (not shown is that the e2e box should have an e2e resource that isn't connected to either deploy):
![image](https://user-images.githubusercontent.com/1004324/72996947-91ad5c80-3dc9-11ea-9aa7-e1c825009716.png)

...it's not lost on me that this is effectively introducing branching logic into jobs. I don't have a clear picture of the impacts this could have but I imagine they are pretty vast.

What do you think?

**Comment by tkellen** [comment]
To take this idea a bit further, this config:
```yaml
- name: e2e
  serial: true
  depends_on:
  - task: deploy-service-bar
    state: passing
  - task: deploy-service-foo
    state: failing
```

....could be shown like this:
<img width="757" alt="245b78dd-a9d2-4eff-b52c-72a25341f36a" src="https://user-images.githubusercontent.com/1004324/72999522-78a6aa80-3dcd-11ea-91ab-17d7654587ff.png">

**Comment by tkellen** [comment]
@vito, still super curious to hear your thoughts on this if/when you have time to share them.

**Comment by tkellen** [comment]
@vito Any chance you might share some thoughts on this? If conditional branching is a hard no I will dig into your cited concerns and try to come up with a solution. I just realized a variation of this problem is manifesting in another area of our pipelines in a very subtle/confusing way.

**Comment by vito** [comment]
Hey, sorry haven't had much bandwidth to think about this since we're close to getting 6.0 out the door and I'm on vacation until Wednesday. Once 6.0 is out I can spend more time on it!

**Comment by tkellen** [comment]
> @vito Any chance you might share some thoughts on this? If conditional branching is a hard no I will dig into your cited concerns and try to come up with a solution. I just realized a variation of this problem is manifesting in another area of our pipelines in a very subtle/confusing way.

Any chance you can share your thoughts on this now @vito?

**Comment by vito** [comment]
@tkellen Would a summary of what you want to do be "I want to run end-to-end tests every minute as long as the most recent deploys of all services that go to it have succeeded"? i.e. you just don't want to run them when a deploy has failed?

Just as a gut reaction, statements like this scare me:

> I can see now that what I'm actually reaching for is a way to express dependencies between jobs without referencing resources at all.

...because that's precisely the definition of what jobs are and how they relate to one another. It's totally valid to point out; to me it's a sign that we need to think about this a little more fundamentally. I don't think you're suggesting we literally make that change.

This feels like you're trying to interact with something that isn't a *resource* - in that it has a history of versions which are all valid and can be fetched - but rather is a *deployment*, or set of deployments, which only ever have a "current state". I'd be interested in fleshing out that idea!

Rather than working backwards from jobs, resources, and the current pipeline UI, I wonder how would you actually want to interact with deployments and their associated end-to-end tests (or maybe even smoke tests / monitoring), given a blank canvas? At some point it's also worth asking whether Concourse is really the best tool for this, or if it's just being a hammer that makes everything look like nails.

(P.S. converting this to a Discussion! See the [recent post announcing Discussions](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/) if you're curious.)

**Reply by tkellen** [reply]
Hey @vito, I missed the announcement about discussions--I'm game to give them a whirl!

Your summary is close, but I don't think it's fundamental enough, here it is in a slightly more general fashion that could serve use-cases other than mine:

> I want to be able to define "work" that always grabs the latest version of every resource it depends on, as seen at the time it was triggered. I further want it to be possible to hold this "work" in a pending state until some constraint is met.

Given a blank canvas, I want developers to see a unified UI where a build/test/deploy job for one or a number of services are clearly in a good or bad state. I want that UI to also visually show a fan in of every app under development to another job which itself shows if the combination of those apps are healthy based on the execution of a test that runs once (I say this to differentiate it from monitoring which definitively belongs in a separate system). I want developers to be able to change any individual application or the test suite as a whole and have the UI automatically update to reflect the latest reality.

Concourse provides everything I just described beautifully with the sole exception that the semantics around how versions are passed between jobs prevents the system from doing the following:
1. Always running the latest e2e tests.
2. Stopping tests from running when there is no chance of success.

I'll concede Concourse may be the wrong tool for number 2 but I think it should support number 1 and I'd go through considerable effort to add it if I knew Concourse would incorporate the addition. What do you think?

**Reply by vito** [reply]
Thanks for the details!

I think I need to unpack this statement a bit more:

> I want to be able to define "work" that always grabs the latest version of every resource it depends on, as seen at the time it was triggered.

Isn't this just a job without `passed` constraints?

> 2\. Stopping tests from running when there is no chance of success.

Going back to my hypothesis about representing things that only exist in one "state", I'm kind of thinking about this as a job that depends on, say, five successful deployments. If the deploy jobs run, try to perform a deploy, and then deploy fails you can think of this as a "successful deployment" being replaced with a "failing deployment".

Instead of resources, which represent a history of versions, these would only ever have one instance, and the instance's attributes could change as the state of the deployment changes.

So, if I had an `e2e` job which runs against deployments with `state: ok`, it would no longer be able to run because one of its required inputs would be unavailable.

Here's some made-up syntax that hasn't had nearly enough thought put into it, but I hope gets my point across:

```yml
resources:
- name: e2e
- name: 10m
- name: a
- name: b

deployments:
- name: a-deployment
  type: k8s
  source: # ...

jobs:
- name: deploy-a
  plan:
  - get: a
  - put_deployment: a-deployment

- name: deploy-b
  plan:
  - get: b
  - put_deployment: b-deployment

- name: e2e
  plan:
  - get: e2e
  - get: 10m
  - get_deployment: a-deployment
    matching: {state: ok}
  - get_deployment: b-deployment
    matching: {state: ok}
  - task: e2e
    # ...
```

Because these `get_deployment` steps require the deployments to have `state: ok`, once that field goes to `failing` or something the `e2e` job would no longer be able to run.

This feels more elegant to me than requiring it to be based on job status, because it would be more precise: if the `deploy-a` or `deploy-b` jobs fail before a deploy is even attempted (perhaps a flaky test or network), in principle the `e2e` tests should still be able to run.

It may also be interesting to think of cases where you'd want a job to trigger on `state: failing`. 🤔

This all could probably be modeled as a [prototype](https://github.com/concourse/rfcs/pull/37), I just don't know what I'd call it. 😅 "Deployment" is probably too specific.
