### DISCUSSION TITLE
Is there a way to pass input name as a variable?

### DISCUSSION THREAD

**Discussion by abhipsnl** [concourse/concourse#5393] [General]
Is there a way to pass input name as a variable

platform: linux
image_resource:
  type: docker-image
  source:
    repository: <repo>
    tag: latest
    username: name
    password: pass
inputs:
  - name: ${NAME} // ((NAME))
outputs:
  - name: ${NAME} // ((NAME))
run:
  path: path

## What challenge are you facing?

NA

## What would make this better?

NA

## Are you interested in implementing this yourself?

NA

**Comment by vito** [comment]
I wouldn't recommend templating input names as it'll just make it harder for the script to know what filesystem to expect. You should probably use [`input_mapping`](https://concourse-ci.org/jobs.html#schema.step.task-step.input_mapping) instead.

If you need to, though, the `task` step supports [`vars:`](https://concourse-ci.org/jobs.html#schema.step.task-step.vars).

**Reply by abhipsnl** [reply]
So using input_mapping ,there is a way I can read input name from variables?

Inputs:
  - name: ((myvar))

**Reply by vito** [reply]
With `input_mapping` you wouldn't *need* to read the input name from a variable, you would map the name to a static input name defined in the task config:

```yaml
plan:
- get: diego-release
- get: cf-release
- get: ci-scripts
- task: audit-diego-release
  file: ci-scripts/audit-release.yml
  input_mapping: {release-repo: diego-release}
- task: audit-cf-release
  file: ci-scripts/audit-release.yml
  input_mapping: {release-repo: cf-release}
```
