### DISCUSSION TITLE
using var_sources (vault) with global credentials manager enabled (k8s)

### DISCUSSION THREAD

**Discussion by allandegnan** [concourse/concourse#5408] [General]
Hi,

I think this could be a bug, but I figured it's too obvious so I must be doing something silly.

I have the following pipeline:-

```
var_sources:
- name: dumb
  type: dummy
  config:
    vars:
      simple: hello!
      user:
        username: big
        password: sekrit

jobs:
- name: do bad thing
  plan:
    - task: expose secret
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: debian
            tag: latest
        params:
          FOO: yoyo
        run:
          path: /bin/sh
          args:
            - -c
            - |
                echo  ((dumb:user.username))
                env
```

I'm deploying with the helm chart 6.0 (tried with 5.8 too) and with kubernetes secrets management enabled globally, it fails to find the secret, appearing to be stuck checking for k8s secrets rather than checking the var_sources, despite (I think) this being explicitly defined.

I assume I'm doing something dumb, but the reason for wanting both available is we're generating client_tokens for vault and dropping them into a teams kubernetes namespace, so the hope would be a rotating secret for vault for the var_source.

```
concourse.web.kubernetes.enabled=true
---
failed to interpolate task config: var lookup 'dumb:user.username': unable to split kubernetes secret path into [namespace]:[secret]: concourse-main:test.dumb:user
```

```
concourse.web.kubernetes.enabled=false
---
big
USER=root
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FOO=yoyo
PWD=/tmp/build/3d301f53
```

Am I doing something wrong here?  Should this work?
