### DISCUSSION TITLE
Overriding/default ((vars))

### DISCUSSION THREAD

**Discussion by allandegnan** [concourse/concourse#5446] [General]
To save time, only really the ((vars)) matter in the below example, specifically the ((template_branch)), but I've added the rest for context.

So I'm creating a template repo for pipelines, which would look a bit like this:

pipeline-template/example/redacted.yml
```
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  check_every: 1m
  source:
    repository: ((source_repo))

- name: pipeline-template
  type: git
  source:
    uri: https://github.com/my-pipeline-template
    branch: ((template_branch))

jobs:
- name: set-pipeline
  plan:
    - get: pull-request
      trigger: true
      version: every
    - get: pipeline-template
    - set_pipeline: ((pipeline_name))
      file: pipeline-template/example/redacted.yml
      var_files:
        - pull-request/ci/config.yml
```

Then I'm trying to consume this via another repo that has this file in it.

pull-request/ci/config.yml
```
---
pipeline_name: test
source_repo: allandegnan/allan-test
template_branch: ad/addingTerraformTemplate
```

The wider idea is I'm trying to make buildpacks but it's likely that the list of variables is going to grow pretty quickly, i.e. from having 

* switchable tasks (i.e. I could have var to pick ECS, EKS, or Fargate for your docker deployment)
* the ability to turn steps on/off
* some vars for template development (I'm only including template_branch above so I can test patterns before I merge them into master, realistically users of the pattern shouldn't need that var).

Thus the question is, can I set a var that would be overwritten via var_files sections?  Is there a hierarchy here?  I feel like I've read this in the docs somewhere before but now I can't find it.
