### DISCUSSION TITLE
Version: `every` only running for latest version

### DISCUSSION THREAD

**Discussion by schmurfy** [concourse/concourse#5574] [General]
I am not sure if this is a bug of if I made a mistake, I am trying to run a task for every opened pull requests:

```yaml
---
  resource_types: 
    - 
      name: "pull-request"
      source: 
        repository: "teliaoss/github-pr-resource"
      type: "registry-image"
  resources: 
    - 
      name: "project-pr"
      source: 
        access_token: "((access_token))"
        repository: "((repository_short))"
      type: "pull-request"

  jobs: 
    - 
      name: "filter-pr"
      plan: 
        - 
          get: "project-pr"
          trigger: true
          version: "every"
        - 
          config: 
            image_resource: 
              source: 
                repository: "alpine"
              type: "registry-image"
            inputs: 
              - 
                name: "project-pr"
            platform: "linux"
            run: 
              args: 
                - "-ec"
                - "export"
              path: "sh"
          task: "Filter Pull requests"
```

If I run this pipeline with 2 open pull requests and look at concourse gui I only see the task being executed for the latest version.

I also checked with a custom resource to test the behavior and with the check returning 3 versions only the latest go through the pipeline...

Edit: I am running v6.0.0 using the docker images
