### DISCUSSION TITLE
Interpolating local var source in `vars` property of a `task` step

### DISCUSSION THREAD

**Discussion by multimac** [concourse/concourse#5607] [General]
With the new local var source, is there any way to pass local vars into a task defined in a file?

My attempts to do so end up with the uninterpolated value being sent to the task, ie. `((.:image))` instead of the value of `image` from the local var source.

eg.
Pipeline
```
- name: do-something-with-image-digest
  serial: true
  plan:
  - get: image-name
  - load_var: image
    file: image-name/digest
  - task: write-image-digest-somewhere
    file: task.yml
    vars:
      image: ((.:image))
```

Task
```
...

run:
  path: echo
  args:
  - "The image is:"
  - ((image))
```

Expected
```The image is: sha256:780cdc...```

Actual
```The image is: ((.:image))```
