### DISCUSSION TITLE
Unable to lookup the vault credentials via lookuptemplates

### DISCUSSION THREAD

**Discussion by gowrisankar22** [concourse/concourse#5738] [General]
Hi @alexandergurney 
something weird happening.  When I used fixed prefixpath `/concourse` everything worked but when I switched to lookup templates to custom path login is successful but lookup to the password is not happening. Not sure what I am missing over here.

Let me elaborate my configurations,

1. my lookup template and prefix path is like below

```
namespace: system/concourse
pathPrefix: /prod-system
lookupTemplates: ["/{{.Team}}/concourse/{{.Pipeline}}/{{.Secret}}", "/{{.Team}}/concourse/{{.Secret}"]

```
2. enabled kv engine using below command . 
`vault secrets enable -version=1 -path=prod-system kv`

3. my Policy looks like below,

```
path "prod-system/*" {
  policy = "read"
}
vault policy write prod-system ./concourse-policy.hcl
```

4. I am connecting via `approle`. Below are the steps i did to enable the same.
```
vault auth enable approle
vault write auth/approle/role/prod-system policies=prod-system period=1h
```
5. I generated roleid and secredid via below commands,
```
vault read auth/approle/role/concourse/prod-system
vault write -f auth/approle/role/concourse/prod-system
``` 
6. With the above configuration, I connected vault with concourse successfully. I can see the logs in the Webnode.
```
{"timestamp":"2020-06-10T13:31:59.300987060Z","level":"info","source":"atc","message":"atc.credential-manager.configured credentials manager","data":{"name":"vault","session":"6"}}
{"timestamp":"2020-06-10T13:31:59.653922075Z","level":"info","source":"atc","message":"atc.credential-manager.login.succeeded","data":{"lease-duration":3600,"name":"vault","policies":["prod-system","default"],"session":"6.1","token-accessor":"rKmQVlagyqLnfbE4TOWSWs8V.GNy9I"}}
```
7. I have created secrets to test using 
`vault kv put prod-system/main/concourse test=DM password=abcd1234` and 
`vault kv put prod-system/main/concourse/mypipeline test=DM password=abcd1234`

8. when i tried testing via pipeline it is unable to interpolate the secret`failed to interpolate task config: undefined vars: password`. my pipeline looks like below,
```
jobs:
- name: test-vault
  plan:
  - task: vault
    params:
      pwd: ((password))
      test: ((test))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
          tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          echo "$pwd $test"
```

Could you please help, to identify the problem. ?

**Comment by vito** [comment]
`((password))` means that you need a path that ends with `/password`, not a key that contains a `password=` field.

Instead, your `vault kv put` commands should look like this:

```
vault kv put prod-system/main/concourse/test value=DM
vault kv put prod-system/main/concourse/password value=abcd1234
vault kv put prod-system/main/concourse/mypipeline/test value=DM
vault kv put prod-system/main/concourse/mypipeline/password value=abcd1234
```

Or if you'd like to store them in the same key, you would do this:

```
vault kv put prod-system/main/concourse/mypipeline/foo test=DM password=abcd1234
```

And access them like `((foo.test))` and `((foo.password))`.

**Comment by gowrisankar22** [comment]
@vito @alexandergurney 

I have tried but it is not working. it was unable to interpolate the variable still. Also, I found that another issue opened by someone. May be is this related due to broken approle ?

https://github.com/concourse/concourse-chart/issues/113

{"timestamp":"2020-06-10T22:18:23.296098384Z","level":"info","source":"atc","message":"atc.tracker.track.errored","data":{"build":18537,"error":"failed to interpolate task config: undefined vars: foo","job":"test-vault","pipeline":"test_demo","session":"23.41"}}

**Reply by jamieklassen** [reply]
you said everything worked before you added lookup templates, though, right? Or did you change to approle auth at the same time?

**Reply by jamieklassen** [reply]
if you still want help with this, I think you should describe what changes you made to your secret placement and your pipeline when you say "I have tried", since @vito suggested multiple possible approaches

**Reply by gowrisankar22** [reply]
@jamieklassen I used approle earlier as well. After updating to 6.2 we adopted just only the lookup template.

To give you some more details, I have modified values.yml for vault-like below,
```
...
vault:
   enabled: true
   namespace: system/concourse
   pathPrefix: /prod-system
   lookupTemplates: ["/{{.Team}}/concourse/{{.Pipeline}}/{{.Secret}}", "/{{.Team}}/concourse/{{.Secret}"]
   authBackend: approle
   insecureSkipVerify: false

 vaultAuthParam: "role_id:x,secret_id:x"
...
```

After this, we re-deployed concourse to reflect the change and it is successful.
```
{"timestamp":"2020-06-10T13:31:59.300987060Z","level":"info","source":"atc","message":"atc.credential-manager.configured credentials manager","data":{"name":"vault","session":"6"}}
{"timestamp":"2020-06-10T13:31:59.653922075Z","level":"info","source":"atc","message":"atc.credential-manager.login.succeeded","data":{"lease-duration":3600,"name":"vault","policies":["prod-system","default"],"session":"6.1","token-accessor":"rKmQVlagyqLnfbE4TOWSWs8V.GNy9I"}}
```

Then I have done the steps described below, to store and retrieve the credentials but it dint work.
https://github.com/concourse/concourse/discussions/5738#discussion-6226 

I maintained the secrets as per @vito 's suggestion. Then I consumed via pipeline but I was unable to get the secrets.

**Reply by jamieklassen** [reply]
what does "maintained the secrets" mean? did you create a new secret called `foo`, or did you put `test` and `password` at separate paths?

**Reply by gowrisankar22** [reply]
@jamieklassen 
I have tried with all of them from https://github.com/concourse/concourse/discussions/5738#discussioncomment-24547

Used below commands to write the secret in vault.
```
vault kv put prod-system/main/concourse/test value=DM
vault kv put prod-system/main/concourse/password value=abcd1234
vault kv put prod-system/main/concourse/mypipeline/test value=DM
vault kv put prod-system/main/concourse/mypipeline/password value=abcd1234
vault kv put prod-system/main/concourse/mypipeline/foo test=DM password=abcd1234
```
I have tried testing via pipeline. Example pipeline is shown below,

```
jobs:
- name: test-vault
  plan:
  - task: vault
    params:
      pwd: ((test))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
          tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          echo "$pwd"
```

it fails with unable to interpolate the var `pwd`.
