### DISCUSSION TITLE
Reg OPA Integration

### DISCUSSION THREAD

**Discussion by gowrisankar22** [concourse/concourse#5794] [Help & Support] [answered]
Hello @evanchaoli , 

I have been following, OPA since the beginning and finally it got merged.  I got a few queries w.r.t OPA integration. 

1. You mentioned that you are running OPA as a sidecar [1] alongside concourse Webnode? 
2. If yes, you take the image example from the docker hub [2]?
3. How did you configure opa sidecar in the concourse-helm chart [3]? It would great if you can share the code snippet?
```
sidecarContainers:
   - name: opa
     image: openpolicyagent/opa:0.21.0
```
4. How to disable all the teams within concourse running the privileged containers? How should my payload/policy look like? 

[1]  https://github.com/concourse/concourse/pull/5034#issuecomment-634326427
[2] https://hub.docker.com/layers/openpolicyagent/opa/0.21.0/images/sha256-c180dd6610fd79e93d956df3864dae4a981c4f8bcfc4e0ce9060d9d1348249be?context=explore
[3] https://github.com/concourse/concourse-chart/blob/master/values.yaml#L1520

The above details might help others as well to configure opa. Of course, I know that this feature will be available only with`v6.4` but I am very curious to know the details. 

Thanks in advance.

**Comment by gowrisankar22** [comment]
@vito @evanchaoli Could you please help ?

**Comment by evanchaoli** [comment, marked as answer]
@gowrisankar22 Sorry for late response. For your questions:

1. It's suggested by OPA to run as sidecar container, refer to https://www.openpolicyagent.org/docs/latest/integration/. For us, our plan is to run OPA as sidecar containers, and all OPA instances load policy files from a center place via bundle, refer to https://www.openpolicyagent.org/docs/latest/management/#bundles

2 & 3. I'm not an expert of helm chart. Somebody else from my team is working on that part. So I don't have helm code to share with you. In my test, I just run a "opa" binary on my laptop. 

4. To block all privileged containers, I built a simple sample for you. When you start `concouse web`, add the following flags:

```
      export CONCOURSE_OPA_URL=http://<opa-url>:8181/v1/data/concourse/allow
      export CONCOURSE_POLICY_CHECK_FILTER_ACTION=UseImage
```

Then create a policy:

```
package concourse

default allow = true
allow = false {
    input.action == "UseImage"
    input.data.privileged == true
}
```

Then I create a pipeline with a privileged task, run the pipeline, from the OPA log, we can see that:

OPA received this request:

```
{"client_addr":"192.168.1.15:60803","level":"info","msg":"Received request.","req_body":"{\"input\":{\"service\":\"concourse\",\"cluster_name\":\"dev\",\"cluster_version\":\"0.0.0-dev\",\"action\":\"UseImage\",\"team\":\"main\",\"pipeline\":\"simple\",\"data\":{\"image_source\":{\"repository\":\"busybox\",\"tag\":\"latest\"},\"image_type\":\"registry-image\",\"privileged\":true}}}","req_id":38,"req_method":"POST","req_params":{},"req_path":"/v1/data/concourse/allow","time":"2020-06-30T09:41:45+08:00"}
```
and responded a false result:
```
{"client_addr":"192.168.1.15:60803","level":"info","msg":"Sent response.","req_id":38,"req_method":"POST","req_path":"/v1/data/concourse/allow","resp_body":"{\"result\":false}","resp_bytes":16,"resp_duration":0.801948,"resp_status":200,"time":"2020-06-30T09:41:45+08:00"}
```

At last, from concourse ui, we can see the task failed with an error of "policy check rejected":

![task-rejected-by-opa](https://user-images.githubusercontent.com/18585861/86075250-296e4f80-baba-11ea-8009-7e814db10340.png)

**Comment by gowrisankar22** [comment]
@evanchaoli Thanks a lot and every detailed answer. This is exactly the thing we were looking for.

I was able to run as a sidecar successfully with the below configuration and so that I can work with `localhost` .

```
sidecarContainers:
    - name: opa
      image: openpolicyagent/opa:0.21.0
      args:
        - "run"
        - "--server"
```

```
    opa:
      ## Open Policy Agent policy check endpoint.
      ##
      ## Example: https://opa.example.com:8181/v1/data/concourse/allow
      ##
      url: http://localhost:8181/v1/data/concourse/allow

      ## Open Policy Agent API request timeout, in Go duration format.
      ##
      ## Example: 5s for 5 seconds
      ##
      timeout: 15s

    policyCheck:
      ## Array of HTTP methods to filter through policy checking.
      ##
      ## Example: ["PUT", "POST"]
      ##
      filterHttpMethods:

      ## Array of ATC API actions to filter through policy checking.
      ##
      ## Example: ["SaveConfig", "UseImage"]
      ##
      filterActions: UseImage

      ## Array of ATC API actions to skip policy checking.
      ##
      ## Example: ["PausePipeline", "UnpausePipeline"]
      ##
      skipActions:

```

I not sure in the help chart where should I update the  ` input.data.privileged == true`  ? and `filterHttpMethods`

@vito Could you please help ?

**Reply by evanchaoli** [reply]
If you just want to check privileged containers, then you don't need to configure `filterHttpMethods`.

`input.data.privileged == true` should be defined in a `rego` file, and the file should be specified to opa. For example, you can save the policy content I put in my answer in a file and put it a HTTP accessible place, say, `http://your-host/test.rego`, then you `opa` configure is like:

```
sidecarContainers:
    - name: opa
      image: openpolicyagent/opa:0.21.0
      args:
        - "run"
        - "--server"
        - http://your-host/test.rego
```

**Reply by gowrisankar22** [reply]
@evanchaoli @vito Can we specify the GitHub link? [I checked it didn't work]
https://raw.githubusercontent.com/gowrisankar22/opa/master/test.rego

Is there any other way in the helm chart specifying this `rego` file? 

or does below command 

`test.rego`

```
package concourse

default allow = true
allow = false {
    input.action == "UseImage"
    input.data.privileged == true
}
```

If I make a post-call, it successfully has written the policy to opa but the problem is if the container is restarted data is lost. Can you help, how can I make this policy is persisted?

```
curl -X POST http://localhost:8181/v1/policies/test --data-binary @test.rego
```

```
{
   "result":{
      "id":"test",
      "raw":"package concourse\n\ndefault allow = true\nallow = false {\n    input.action == \"UseImage\"\n    input.data.privileged == true\n}\n",
      "ast":{
         "package":{
            "path":[
               {
                  "type":"var",
                  "value":"data"
               },
               {
                  "type":"string",
                  "value":"concourse"
               }
            ]
         },
         "rules":[
            {
               "default":true,
               "head":{
                  "name":"allow",
                  "value":{
                     "type":"boolean",
                     "value":true
                  }
               },
               "body":[
                  {
                     "index":0,
                     "terms":{
                        "type":"boolean",
                        "value":true
                     }
                  }
               ]
            },
            {
               "head":{
                  "name":"allow",
                  "value":{
                     "type":"boolean",
                     "value":false
                  }
               },
               "body":[
                  {
                     "index":0,
                     "terms":[
                        {
                           "type":"ref",
                           "value":[
                              {
                                 "type":"var",
                                 "value":"eq"
                              }
                           ]
                        },
                        {
                           "type":"ref",
                           "value":[
                              {
                                 "type":"var",
                                 "value":"input"
                              },
                              {
                                 "type":"string",
                                 "value":"action"
                              }
                           ]
                        },
                        {
                           "type":"string",
                           "value":"UseImage"
                        }
                     ]
                  },
                  {
                     "index":1,
                     "terms":[
                        {
                           "type":"ref",
                           "value":[
                              {
                                 "type":"var",
                                 "value":"eq"
                              }
                           ]
                        },
                        {
                           "type":"ref",
                           "value":[
                              {
                                 "type":"var",
                                 "value":"input"
                              },
                              {
                                 "type":"string",
                                 "value":"data"
                              },
                              {
                                 "type":"string",
                                 "value":"privileged"
                              }
                           ]
                        },
                        {
                           "type":"boolean",
                           "value":true
                        }
                     ]
                  }
               ]
            }
         ]
      }
   }
}
```

**Reply by jamieklassen** [reply]
@gowrisankar22 your question is really broadly about how to configure OPA, and specifically about how to put persistent data in a container, which has only indirectly to do with the helm chart. I wouldn't expect @evanchaoli to provide support for a question like this, he just happens to have implemented the concourse OPA integration feature -- he doesn't support OPA itself. Furthermore there are many ways of managing persistent data in kubernetes (and containers generally) so you may have to do some research to figure it out for yourself. You _could_ build your own image based on the official OPA one with the config baked in. Or you could mount a persistent volume in your sidecar container. Maybe the `additionalVolumes` and `additionalVolumeMounts` properties could help:

https://github.com/concourse/concourse-chart/blob/c556ecc4c60ca8d49b192b9c1664c6c394d52393/values.yaml#L1595-L1618

Depending on how you want to store your OPA config (who will maintain it, if it is shared with other teams, etc) you could maybe add a configmap to the namespace that you web nodes are deployed in. In really simple proof-of-concept cases I have used an init container to create simple config files and populate volumes.

I would encourage you to think through the implementation/maintenance concerns and stakeholders of your use case and maybe you could come up with some recommendations based on what you find, and share them here for others with questions like yours.

**Reply by gowrisankar22** [reply]
@jamieklassen Thanks :). I had the same thought. anyways I got the way for the same. I will add the details below.

**Comment by gowrisankar22** [comment]
@evanchaoli any update on this ?

**Comment by gowrisankar22** [comment]
@evanchaoli @jamieklassen Thanks for your inputs. Finally, prepared the things before `v6.4` for opa to disable running as the privileged container for the job. Let me know should I add these examples in the 
https://github.com/concourse/concourse-chart/blob/master/values.yaml ?

1. Create a policy. example `test.rego`
```
package concourse

default allow = true
allow = false {
    input.action == "UseImage"
    input.data.privileged == true
}
```

2. create a config map
`kubectl create configmap test-policy --from-file test.rego` 

3. add sidecar and add as a  volume mount

```
sidecarContainers:
    - name: opa
       image: openpolicyagent/opa:0.21.0
       args:
       - "run"
       - "--server"
       - "/policies"
       volumeMounts:
       - readOnly: true
         mountPath: /policies
         name: test-policy-opa
 
additionalVolumes:
- name: test-policy-opa
   configMap:
   name:  test-policy

```
