### DISCUSSION TITLE
Enabling New Relic on v5.8.0 causing 'panic: runtime error: invalid memory address or nil pointer dereference'

### DISCUSSION THREAD

**Discussion by skreddy6673** [concourse/concourse#5801] [Help & Support] [answered]
Web nodes failed to start with following error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x191a9d1]

goroutine 12 [running]:
github.com/concourse/concourse/atc/metric/emitter.(*NewRelicEmitter).Emit(0xc0006cad20, 0x37277e0, 0xc00113a540, 0x2d50cf0, 0xe, 0x2953d60, 0x49ec6a0, 0x2d3d0ff, 0x2, 0xc000717650, ...)
        /tmp/build/1c3187db/concourse/atc/metric/emitter/newrelic.go:109 +0x891
github.com/concourse/concourse/atc/metric.emitLoop()
        /tmp/build/1c3187db/concourse/atc/metric/emit.go:148 +0x133
created by github.com/concourse/concourse/atc/metric.Initialize
        /tmp/build/1c3187db/concourse/atc/metric/emit.go:108 +0x3c8
```

Any work around or recommendations?

**Comment by skreddy6673** [comment]
I tried with v6.0.0 and got the same error
```
$ kubectl logs concourse-dev-web-6cb4d7545b-dp866 -n concourse-test
{"timestamp":"2020-06-22T21:31:58.559867203Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2020-06-22T21:31:58.559983958Z","level":"debug","source":"atc","message":"atc.metrics.metric-initialize","data":{"attributes":{},"buffer-size":1000,"host":"concourse-dev-web-6cb4d7545b-dp866","session":"2"}}
{"timestamp":"2020-06-22T21:31:58.772364724Z","level":"info","source":"atc","message":"atc.credential-manager.configured credentials manager","data":{"name":"kubernetes","session":"6"}}
{"timestamp":"2020-06-22T21:31:58.922276411Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":64966,"session":"1"}}
{"timestamp":"2020-06-22T21:31:58.922643866Z","level":"info","source":"atc","message":"atc.lidar.start","data":{"session":"17"}}
{"timestamp":"2020-06-22T21:31:58.922700070Z","level":"info","source":"tsa","message":"tsa.listening","data":{}}
{"timestamp":"2020-06-22T21:31:58.922689374Z","level":"info","source":"atc","message":"atc.lidar.start","data":{"session":"17"}}
{"timestamp":"2020-06-22T21:31:58.922713568Z","level":"info","source":"atc","message":"atc.scheduler-interval-runner.start","data":{"interval":"10s","session":"20"}}
{"timestamp":"2020-06-22T21:31:58.922897753Z","level":"info","source":"atc","message":"atc.listening","data":{"debug":"127.0.0.1:8079","http":"0.0.0.0:8080"}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x199091c]

goroutine 11 [running]:
github.com/concourse/concourse/atc/metric/emitter.(*NewRelicEmitter).Emit(0xc000baf2c0, 0x39eed80, 0xc001198960, 0x2dcd5d8, 0xe, 0x0, 0xc0006ec450, 0xc000d29200, 0x22, 0xbfb466b63701625b, ...)
        /tmp/build/8cf986d9/concourse/atc/metric/emitter/newrelic.go:108 +0x81c
github.com/concourse/concourse/atc/metric.emitLoop()
        /tmp/build/8cf986d9/concourse/atc/metric/emit.go:138 +0x170
created by github.com/concourse/concourse/atc/metric.Initialize
        /tmp/build/8cf986d9/concourse/atc/metric/emit.go:98 +0x3c8
```

**Reply by taylorsilva** [reply]
Can you share your values.yaml, at least the new relic settings? I don't have access to a new relic account, but even with dummy creds I can't reproduce this error using the latest chart and Concourse 6.0.0 (or 6.3.0)

**Reply by skreddy6673** [reply]
Here is my values file
https://github.com/skreddy6673/concourse-chart/blob/master/v6.0.0.yaml

Chart version: v10.0.7

And my new relic settings:
```
newrelic:
      enabled: false

      ## New Relic Account ID
      ##
      accountId: "ACC_ID"

      ## New Relic Insights API Key
      ##
      apiKey:

      ## An optional prefix for emitted New Relic events
      ##
      servicePrefix: concourse_dev_

      ## Number of events to batch together before emitting
      ##
      batchSize:

      ## Length of time to wait between emitting until all currently batched events are emitted
      ## Example: 60s
      ##
      batchDuration:

      ## Disables compression of the batch before sending it
      ##
      disableCompression:
```

**Reply by taylorsilva** [reply]
I tried using your values.yaml but it had various small errors. Instead I modified my `newrelic` field looks like this:

```yaml
    newrelic:
      enabled: true
      accountId: "ACC_ID"
      apiKey: "fakeapikey"
      servicePrefix: concourse_dev_
```

I was able to install Concourse on my GKE cluster without error:

```
$ k get pods -n new-relic
NAME                             READY   STATUS    RESTARTS   AGE
new-relic-postgresql-0           1/1     Running   0          44s
new-relic-web-78c7c577bf-wsxpz   1/1     Running   0          44s
new-relic-worker-0               1/1     Running   0          44s
new-relic-worker-1               1/1     Running   0          44s
```

If you do a `kubectl describe pod` and look in the `Containers.Environment` section do you see anything unexpected or malformed? Specifically the `CONCOURSE_NEWRELIC_` flags? Mine looked like this (literally, I don't have an account or API key to use 😅 ):

```
      CONCOURSE_NEWRELIC_ACCOUNT_ID:                      ACC_ID
      CONCOURSE_NEWRELIC_API_KEY:                         fakeapikey
      CONCOURSE_NEWRELIC_SERVICE_PREFIX:                  concourse_dev_
```
