### DISCUSSION TITLE
only Intercepting/hijack is giving 403 forbidden

### DISCUSSION THREAD

**Discussion by gowrisankar22** [concourse/concourse#5806] [Help & Support] [answered]
Hello,

We are getting 403 forbidden only for the Intercepting/hijacking operations for concourse containers.
Not really sure what’s going wrong, whereas other commands like set-pipeline, watch ...etc are working fine.

Also, I have a garden configuration like below,

```
env:
  - name: CONCOURSE_GARDEN_NETWORK_POOL
    value: "10.254.0.0/16"
  - name: CONCOURSE_GARDEN_MAX_CONTAINERS
    value: "500"
  - name: CONCOURSE_GARDEN_DENY_NETWORK
    value: "169.254.169.254/32"
```

```
$ fly6 --verbose -t validation intercept -j test/prepare-2

2020/06/22 15:38:02 GET /api/v1/info HTTP/1.1
Host: xxx
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2020/06/22 15:38:02 HTTP/1.1 200 OK
Content-Length: 141
Alt-Svc: clear
Content-Type: application/json
Date: Mon, 22 Jun 2020 12:38:02 GMT
Vary: Accept-Encoding
Via: 1.1 google
X-Concourse-Version: 6.0.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

{"version":"6.0.0","worker_version":"2.2","external_url":xxxxx","cluster_name":"Concourse"}

2020/06/22 15:38:02 GET /api/v1/teams/Teama/containers?job_name=prepare-2&pipeline_name=test HTTP/1.1
Host: xxxx
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2020/06/22 15:38:02 HTTP/1.1 403 Forbidden
Alt-Svc: clear
Date: Mon, 22 Jun 2020 12:38:02 GMT
Vary: Accept-Encoding
Via: 1.1 google
X-Concourse-Version: 6.0.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
Content-Length: 0

error: forbidden

```

Can somebody help, what might have been the problem ?
