### DISCUSSION TITLE
unable to add multiple whitelisted GitHub users and teams

### DISCUSSION THREAD

**Discussion by gowrisankar22** [concourse/concourse#5819] [Help & Support] [answered]
Hello Experts,

I am running into an issue where, if I try to add multiple whitelists/roles for the main team. Currently, my concourse is using GitHub based authentication. if I just add one GitHub team to whitelists and role it works fine. When I try to add multiple whitelists(GitHub teams and users) that's where I see the issue.

I expect below configuration to work as per the document described but with the below configuration, I am unable to view any pipeline.

```
  config: |
       roles:
       - name: owner
          local:
             users: [ "test" ]
          github:
             teams: [ "org1:team1" ]
          github:
             users: [ "githubuser" ]
           github:
              teams: [ "org1:team2" ]
```

```
## Authentication (Main Team) (GitHub)
        ##
        github:
          ## List of whitelisted GitHub users
          ##
          user: githubuser

          ## List of whitelisted GitHub orgs
          ##
          ##org: org1

          ## List of whitelisted GitHub teams
          ##
          team: org1:team1,org1:team12

Also, I tried  with `team: team1,team12` after enabling `org: org1`

```

PS: I am using helm flavor of concourse setup. 

Could someone help what I am missing here?

BRs, Gowrisankar

**Comment by jamieklassen** [comment, marked as answer]
I haven't taken the time to reproduce, but your first YAML looks fishy. I'd rather see
```yaml
  config: |
       roles:
       - name: owner
          local:
             users: [ "test" ]
          github:
             teams: [ "org1:team1", "org1:team2" ]
          github:
             users: [ "githubuser" ]
```

**Reply by gowrisankar22** [reply]
@jamieklassen sorry I tried this combination as well earlier, but I forgot to put in the discussion. I almost tried all the combinations but it is not working as expected. Looks like a bug/regression? 

not sure whether it used to work earlier, I just tried recently with 6.2.

**Reply by jamieklassen** [reply]
what i really wanted to see was:
```yaml
  config: |
       roles:
       - name: owner
          local:
             users: [ "test" ]
          github:
             teams: [ "org1:team1", "org1:team2" ]
             users: [ "githubuser" ]
```
but the indentation is wrong too... i still feel like this is probably a config issue. I think you could do some kind of helm dry-run to actually see the rendered templates for your web deployment. Looking at the environment variables could help
