### DISCUSSION TITLE
Task inputs changes after the first attempt.

### DISCUSSION THREAD

**Discussion by jvshahid** [concourse/concourse#5840] [Help & Support]
Summary

Task inputs changes after the first attempt.

## Steps to reproduce

Set the following pipeline

```yml
resources:
- name: s3-resource
  type: git
  source:
    uri: https://github.com/concourse/s3-resource
    branch: master

- name: docker-image                  # Any image with rsync will do
  type: docker-image
  source:
    repository: cloudfoundry/diego-ci
    tag: latest

jobs:
- name: reproduce-bug
  plan:
  - get: s3-resource
  - get: docker-image
  - task: first
    image: docker-image
    input_mapping:
      resource: s3-resource
    params:
      EXIT_CODE: 0
    config: &config
      platform: linux
      inputs:
      - name: resource
      outputs:
      - name: updated-resource
      params:
        EXIT_CODE:
      run:
        path: bash
        args:
        - -c
        - |
          echo "################ begin"
          ls -l resource/
          echo "################ end"
          [ $EXIT_CODE -ne 0 ] && exit $EXIT_CODE
          rsync -a resource/ updated-resource
  - task: second
    image: docker-image
    attempts: 2
    params:
      EXIT_CODE: 1
    input_mapping:
      resource: updated-resource
    config:
      <<: *config
```

Trigger the `reproduce-bug` job and wait until the `second` task fails.

## Expected results

The output of the `second` task attempt `2` should match the output from the attempt `1`.

## Actual results

I see different output in the second attempt.  I see the following in the second attempt:

```
################ begin
total 0
################ end
```

as opposed to the following output from the first attempt:

```
################ begin
total 84
-rw-r--r-- 1 root root    20 Jul  2 16:30 CODEOWNERS
-rw-r--r-- 1 root root 11324 Jul  2 16:30 LICENSE.md
-rw-r--r-- 1 root root   598 Jul  2 16:30 NOTICE.md
-rw-r--r-- 1 root root  9643 Jul  2 16:30 README.md
drwxr-xr-x 1 root root   106 Jul  2 16:30 check
drwxr-xr-x 1 root root    20 Jul  2 16:30 cmd
drwxr-xr-x 1 root root    24 Jul  2 16:30 dockerfiles
drwxr-xr-x 1 root root    32 Jul  2 16:30 fakes
-rw-r--r-- 1 root root   900 Jul  2 16:30 go.mod
-rw-r--r-- 1 root root  6788 Jul  2 16:30 go.sum
drwxr-xr-x 1 root root   120 Jul  2 16:30 in
drwxr-xr-x 1 root root   150 Jul  2 16:30 integration
-rw-r--r-- 1 root root  2242 Jul  2 16:30 models.go
drwxr-xr-x 1 root root   102 Jul  2 16:30 out
-rw-r--r-- 1 root root   289 Jul  2 16:30 progress_reader.go
-rw-r--r-- 1 root root   325 Jul  2 16:30 progress_writer_at.go
-rw-r--r-- 1 root root 12740 Jul  2 16:30 s3client.go
drwxr-xr-x 1 root root     8 Jul  2 16:30 scripts
-rw-r--r-- 1 root root   288 Jul  2 16:30 utils.go
-rw-r--r-- 1 root root  6256 Jul  2 16:30 v2signer.go
drwxr-xr-x 1 root root    98 Jul  2 16:30 versions
################ end
```

The output of the second attempt should match the output from the first attempt.

## Additional context

We have a job that runs `terraform apply` followed by `terraform destroy`.  The job consists of two steps which share the same task definition.  The task definition takes a param specifying the subcommand to run.  After invoking terraform, the task outputs a copy of the repo with the terraform state files which are needed to destroy the environment.

The above artificial pipeline is the minimal reproduction case I could think of. This issue might be related to #5799, although the symptoms are different.

## Triaging info

* Concourse version: v6.2.0
* Did this used to work? I am not sure.
