### DISCUSSION TITLE
waiting for suitable set of input version/ discovering any new versions

### DISCUSSION THREAD

**Discussion by ashmeet72** [concourse/concourse#5843] [Help & Support]
i setup pipeline locally & running on docker image but most of time when i triggered job then pipeline
go into state of waiting for suitable set of input version/ discovering any new versions infinite. i look on google for many things
but not got resolution.below is screen shot.can anyone help me with this.
![image](https://user-images.githubusercontent.com/40124674/86491260-e9dc8780-bd87-11ea-80db-05112b1c48c1.png)

**Comment by jamieklassen** [comment]
can you provide the complete pipeline yaml you are using?

**Reply by ashmeet72** [reply]
```yaml
resources:
  - name: resource-tutorial1
    type: git
    source:
      username: yarn###
      password: yarn77777
      uri: https://github.com/yarn/dob.git
      branch: master


  - name: resource-tutorial2
    type: git
    source:
      username: yarn###
      password: yarn77777
      uri: https://github.com/yarn/dob.git
      branch: master

jobs:
  - name: hello_world_job1
    plan:
      - get: resource-tutorial1
        trigger: true
      - task: tester
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: echo
            args: ["Hello, world!"]
        
  - name: hello_world_job2
    plan:
      - get: resource-tutorial1
        passed: [hello_world_job1]
      - task: tester
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: echo
            args: ["Hello, worlds!"]

  - name: hello_world_job3
    serial: true
    plan:
      - get: resource-tutorial2
      - get: resource-tutorial1
        passed: [hello_world_job1]
        passed: [hello_world_job2]
      - task: tester
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: echo
            args: ["Hello, worlds!"]
```

**Comment by jamieklassen** [comment]
It sounds like you were expecting to be able to trigger `hello_world_job3` and have it run before `hello_world_job2` had completed. Is that correct?

**Reply by ashmeet72** [reply]
situation is like many commits come and job hello_world_job1 got trigger with each commit because of auto trigger.but when i trigger hello_world_job3 without 
triggering hello_world_job2 then many times it got stuck with error waiting for suitable set of input version.yes i want to trigger hello_world_job3 without triggering hello_world_job2 .

**Reply by jamieklassen** [reply]
So this isn't a bug -- `hello_world_job3` has a `get` step on `resource-tutorial1` with a `passed` constraint on `hello_world_job2`. This means that the only versions of `resource-tutorial1` that are suitable inputs for `hello_world_job3` are versions that appeared as inputs or outputs of _successful_ builds of `hello_world_job2`. That's what a passed constraint is for - to ensure that a job will only run on inputs that have "passed" an upstream job.

**Reply by jamieklassen** [reply]
if you want to be able to run `hello_world_job3` without waiting for `hello_world_job2` then you can remove the

```
passed: [hello_world_job2]
```

line from the configuration on `hello_world_job3`.

**Reply by jamieklassen** [reply]
In fact, this snippet of your config is very odd:
```yaml
      - get: resource-tutorial1
        passed: [hello_world_job1]
        passed: [hello_world_job2]
```
it almost looks like a typo -- in general if you specify the same key multiple times in a YAML hash, the last one will take precedence. In this case it means that your `get` step will _only_ accept versions which have passed `hello_world_job2`. Maybe you meant for that to be `hello_world_job1`?

**Reply by ashmeet72** [reply]
but why this problem not occur every time?.

**Reply by jamieklassen** [reply]
When a version of `resource-tutorial1` is available that has passed `hello_world_job2` I would expect the build to start eventually... I can't recreate your pipeline completely because I get 404s on the GitHub links so I can't say if there might be a problem with that configuration. Are there _any_ commits that have passed `hello_world_job2`?

**Reply by jamieklassen** [reply]
I tried using this pipeline (just replacing the git resources with something publicly available):

```yaml
resources:
  - name: resource-tutorial1
    type: git
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: resource-tutorial2
    type: git
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
jobs:
  - name: hello_world_job1
    plan:
      - get: resource-tutorial1
        trigger: true
      - task: tester
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: echo
            args: ["Hello, world!"]
  - name: hello_world_job2
    plan:
      - get: resource-tutorial1
        passed: [hello_world_job1]
      - task: tester
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: echo
            args: ["Hello, worlds!"]
  - name: hello_world_job3
    serial: true
    plan:
      - get: resource-tutorial2
      - get: resource-tutorial1
        passed: [hello_world_job1]
        passed: [hello_world_job2]
      - task: tester
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: echo
            args: ["Hello, worlds!"]
```
And when I got to the state where `hello_world_job3` was pending, I was able to trigger a build of `hello_world_job2` and it got unstuck.
