### DISCUSSION TITLE
templating vars (splitting json, etc)

### DISCUSSION THREAD

**Discussion by allandegnan** [concourse/concourse#5895] [Help & Support]
I'm just wondering if there's a more appropriate way of splitting a json string from a var than how I'm doing it here

https://github.com/secureweb/homelab/blob/addPipeline/ci/pipeline.yml

Basically, the problem is vault secrets manager, which I might configure such as:

```
var_sources:
- name: vault
  type: vault
  config:
    url: http://vault.vault.svc
    path_prefix: /concourse
    client_token: ((auth-token))

- name: aws
  type: dummy
  config:
    vars:
      sts: ((vault:aws/sts/my-role))

- name: private-image
  type: registry-image
  source:
    repository: my-aws-ecr/private-image
    tag: latest
    aws_access_key_id: ((aws.sts.access_key))
    aws_secret_access_key: ((aws.sts.secret_key))
    aws_session_token: ((aws.sts.security_token))
    aws_region: eu-west-1
```
Pulling an azure or aws secret from vault returns a json string.  

Obviously, in a task I can just split the string, but in a resource often there's no way to do it, so I'm wondering if there's a more way to do this without abusing var_sources dummy type.

**Comment by vito** [comment]
Sorry, I'm having a hard time understanding what you mean by splitting. Do you mean accessing fields from it?

Does this not work?:

```yaml
var_sources:
- name: vault
  type: vault
  config:
    url: http://vault.vault.svc
    path_prefix: /concourse
    client_token: ((auth-token))

- name: private-image
  type: registry-image
  source:
    repository: my-aws-ecr/private-image
    tag: latest
    aws_access_key_id: ((vault:aws/sts/my-role.access_key))
    aws_secret_access_key: ((vault:aws/sts/my-role.secret_key))
    aws_session_token: ((vault:aws/sts/my-role.security_token))
    aws_region: eu-west-1
```

Note that this may require the use of [credential caching](https://concourse-ci.org/creds-caching.html) to prevent `aws/sts/my-role` from being fetched 3 times and receiving 3 mismatched values (if they're being generated). Maybe that's the root problem you're trying to work around? I think your example solves that too. 🤔
