### DISCUSSION TITLE
capturing conditional logic in build

### DISCUSSION THREAD

**Discussion by TomWoodward** [concourse/concourse#5913] [Help & Support]
I have a build job where the result may or may not exist already, i'm trying to check if it does and either get/put the resource to make it available for downstream jobs. i could put my noop logic in the resource's out script, but i feel like that is less explicit and the build has multiple steps and i'd really prefer to skip a bunch of them. 

currently i've made a task that checks if the result exists already and use on_success to `get` it and on_failure to build and then `put`. then to make the job actually succeed and move onto downstream jobs i have to wrap the whole thing in `attempts: 2`. this works but is obviously gross, without some kind of [conditional steps](https://github.com/concourse/concourse/issues/3999) i'm not sure how to do it better though.

i would prefer not to store arbitrary state in git or s3 to trigger separate jobs for each condition as discussed [here](https://discuss.concourse-ci.org/t/executing-task-step-conditionally-like-passed/982/5), but even if i did i'm not sure how i could fan in the resulting resource for downstream logic, since only one of the jobs will ever pass for a given version i think i would need something like [optional passed logic](https://github.com/concourse/concourse/discussions/4949).

there may be a way to accomplish what i'm trying to do in a more "concoursey" way, but i'm struggling with the issue, does anyone have any feedback?

**Comment by vito** [comment]
The Concoursey way is for `put` - and the entire build plan - to be idempotent.

How much time are you intending to optimize away? Bear in mind that sometimes folks re-trigger builds to suss out flakes and other nondeterministic behavior even in parts that have already 'succeeded.' The general guidance is to avoid premature optimization and make the build entirely idempotent; it'll pay off someday when it fails halfway through or when the build plan has to be modified and re-run.

**Reply by TomWoodward** [reply]
I feel like the use case is valid without the specifics of my situation, but for context i'll go into detail:

the build takes at least 2 hours, sometimes as much as 5 hours to run. it generates an artifact that is about 3 GB right now but will continue to get bigger. the artifact needs to be uploaded to two mirrors.

currently i have a build phase, then a verification to make sure the package is backwards compatible with what is on production. these are set up as tasks right now. i have a custom resource type that does the uploading, the same resource type is configured as two different resources for each mirror and we put those after the verification.

you're not wrong that if the build was interrupted, for instance between the two uploads, it would be beneficial to go through the whole process again to make sure all the correct files exist even if it involves some duplicate uploading.

however in our specific case, builds failing during upload has never been an issue, but the build time has been a pain point. we would really really like to skip the build phases if we detect an artifact already exists, we can accept the possibility that if a build has failed the results might be corrupt. we have notifications set up for any failures and sometimes it happens during the build but never on the upload.

in order to align with what i think your saying, i can see some options, but i don't particularly love them:

- i could take all the logic i have across my tasks, plus the awareness of multiple mirrors, and push it all down into the custom resource type, then conditionally noop the build in there. i don't like this because i would prefer to have the logic distributed in bite size tasks rather than one resource out script to rule them all. i like using a lot of tasks because they're easy to keep close to the relevant app code and be owned by the app developers. our resource types frequently are involved with multiple code components so we try to have them be as dumb as possible and rely on the tasks to prepare them.
- i could put noop logic in my build tasks and resource out script based on the presence of some config that would be output by a task run at the beginning. i don't like that the noop logic would be basically duplicated throughout several components, and i would prefer for my pipeline structure to actually accurately reflect the logic in the build, rather than obfuscating it in some magic logic in the steps.

in response to the premature optimization comment, i might have put in my original question that i've been using concourse mostly successfully for almost two years. i feel like i have a handle on how to do things in a mostly reasonable way, i like how the resource system provides a way to structure jobs and logic in really nice ways that other platforms like jenkins and github actions don't even really try to handle. i do occasionally run into a situation like i'm asking about here where i feel like the structure of the system is getting in my way more than its helping me. i've seen others asking similar questions about branching logic and i don't, in general, think that it is a sign of premature optimization or even always used for optimization.

since the on_[status] hooks can be used to hack in branching logic, and there are several cases were people talk about how to do this online, i feel like it would be reasonable for the platform to add support for it, even if you personally don't necessarily see the value.

**Reply by vito** [reply]
@TomWoodward Thanks for your detailed feedback! Apologies for the 'premature optimization' comment, it was presumptuous of me to apply it here - I meant it as a more general notion that Concourse tries to avoid. 🙂

I'll do more thinking on your comment and hopefully get back to this soon - juggling a lot of activity today. FWIW, I totally sympathize with the use case, I'd just like to find a way to express it in a way that doesn't result in over-use, abuse, gotchas, or being unable to handle emergent scenarios (without e.g. having to re-configure the pipeline without the skips).

**Reply by vito** [reply]
@TomWoodward Circling back on this, sorry for the wait!

Would it be accurate to frame the problem as this?:

> I would like to be able to `put` an artifact but skip costly setup/build steps if the artifact already exists.

In addition to....

> I would like to upload the same artifact to a mirror.

I'm guessing your current build plan looks something like this:

```yaml
plan:
- get: my-source
- task: expensive-build
  # inputs: [my-source]
  # outputs: [build-output]
- put: my-artifact
  params: {build-output/*.tgz}
- put: my-artifact-mirror
  params: {my-artifact/*.tgz}
```

One assumption I've made here is that you only want to upload to the mirror after it successfully uploads to the origin. This is a little slower but feels safer than letting the mirror become out of sync from the origin. If the artifacts are huge though you may be willing to take that risk and wrap them in `in_parallel`, pointing both at the task output instead of pointing the mirror at the artifact fetched from the origin `put` step's implicit `get`. I'm curious to hear your approach here, since it has a big impact on the potential solution.

Your original request brought up a great point: you need the versions to propagate to downstream jobs, even if the artifacts did not have to be built and uploaded. This implies that Concourse needs some way to know that the desired versions were still "outputs" of the build. The tricky part is that if we completely skip running the `put` step, the desired version will not be recorded as an output. So we can't just add `if` step and call it a day. :thinking:


**Idea 1**

One approach is to express that the `task` is part of necessary setup for the `put` step, and for the `put` step to be able to no-op and record the given version as an output if it already exists.

I'm not sure how your resource type's versions look, but it sounds like you have some way of checking whether the artifact already exists, so there must be some way to come up with a version of some sort from the build's inputs. I'll just wing it and say it's the git ref for now.

```yaml
plan:
- get: my-source
- load_var: ref
  file: my-source/.git/ref
- put: my-artifact
  version: {ref: ((.:ref))}
  params: {build-output/*.tgz}
  if_not_exists:
    task: expensive-build
- put: my-artifact-mirror
  params: {my-artifact/*.tgz}
```

I'm really not in love with the syntax, but hopefully it gets the idea across. In fact I really don't like that the `put` step references the output before the `task` step which produces it.

Another downside of this approach is that the setup `task` is associated to a single `put` step, but in your case you actually have two to run. This means you can't wrap them in an `in_parallel` step, since now the original `put` *has* to run first, since it's also tied to the `task` that builds the artifact.

**Idea 2**

Here's another way we could think about this: if we can make the flow of inputs and outputs explicit, we might be able to lazily evaluate steps only when their outputs are actually needed.

Something like this:

```yaml
plan:
- get: my-source
- load_var: ref
  file: my-source/.git/ref
- task: expensive-build
  lazy: true
- put: my-artifact
  version: {ref: ((.:ref))}
  params: {build-output/*.tgz}
- put: my-artifact-mirror
  version: {ref: ((.:ref))}
  params: {my-artifact/*.tgz}
```

This has the same structure as the original plan, which feels like a big win - this pattern is pretty common, so it's nice that it doesn't involve a dramatic re-structuring of the plan in order to optimize it.

Some notes on how this might work:

* The `lazy: true` added to the `task` step means "don't run the step until another step needs its outputs".

* The `version:` on the `put` steps means "skip running and record the version as an output if it already exists". If the `put` step decides it needs to run, it will need the `build-output` artifact, which will trigger the `task` to run and wait for it to finish.

The nice thing about this approach is that it's way more flexible - all you need to do is sprinkle `lazy: true` on steps that you want to skip. The setup doesn't have to be associated to a single `put`, and can be written ahead of it in the build plan. In fact you could decide to wrap the `put` steps in an `in_parallel`, and they'll both just wait for the task to complete.

Theoretically `lazy: true` config could be added to other steps which produce outputs, like `put` and `get`. :thinking: (The mad scientist in me would even be tempted to make it a default.)

One tricky aspect is if you have some sort of 'build-and-verify' flow (as you mentioned), you'll need some way to run the verify task only if building was needed. I suppose one way to do this is with an `on_success` hook:

```yaml
plan:
- get: my-source
- load_var: ref
  file: my-source/.git/ref
- task: expensive-build
  lazy: true
  on_success:
    task: verify
- put: my-artifact
  version: {ref: ((.:ref))}
  params: {build-output/*.tgz}
- put: my-artifact-mirror
  version: {ref: ((.:ref))}
  params: {build-output/*.tgz}
```

Otherwise you'd need to make both tasks lazy and pass the artifact through them, with the `put` steps referencing the last one - something like this:

```yaml
plan:
- get: my-source
- load_var: ref
  file: my-source/.git/ref
- task: expensive-build
  lazy: true
  # outputs: [build-output]
- task: verify
  lazy: true
  # inputs: [build-output]
  # outputs: [verified-output]
- put: my-artifact
  version: {ref: ((.:ref))}
  params: {verified-output/*.tgz}
- put: my-artifact-mirror
  version: {ref: ((.:ref))}
  params: {verified-output/*.tgz}
```

Sorry for the long response, but really curious to hear what you think! :)
