### DISCUSSION TITLE
tasks have no access to ipv6 services

### DISCUSSION THREAD

**Discussion by Infinoid** [concourse/concourse#5919] [Help & Support]
I run several ipv6-only services, and I'd like concourse pipelines to interact with them.  However, when concourse runs tasks, the tasks have no ipv6 connectivity.

I run a worker in docker, using the `concourse/concourse` docker image.  This worker has a proper ipv6 setup, with address and gateway.  However, the `runc` containers spawned by this worker only have link-local addresses, and no route.  The task can resolve the hostname, but the connection fails with a "No route to host" error.

I'd like to write concourse pipelines that interact with ipv6-only services.  Is this possible?

(from issue #1889)

**Comment by phillbaker** [comment]
This is also an issue if you're running on AWS in private subnets and utilizing the IPv6 Egress only gateways.

**Comment by Infinoid** [comment]
For now, I'm running an http proxy on the same docker network as the worker, and pointing the worker at it via the `http_proxy` and `https_proxy` environment variables.

That seems to help, at least for http stuff.  ssh is still an issue.

(I also tried a socks5 proxy.  That got `git clone` working, but not `docker pull`.)

**Reply by Infinoid** [reply]
> That seems to help, at least for http stuff. ssh is still an issue.

For ssh, the git resource can use the same proxy trick to access ipv6-only `ssh://` URLs through an http proxy.  However, it doesn't obey the `http_proxy` environment variable.  I was able to get it to work by adding an `https_tunnel` section.  It looks like:

```yaml
  name: thing-git
  type: git
  source:
    uri: ssh://git@git.server/user/thing
    branch: master
    private_key: ((git-ssh-key))
    https_tunnel:
      proxy_host: proxy.hostname
      proxy_port: 12345
```

Despite being named "https_tunnel", the worker connects to the proxy via http, and uses that to connect to ssh on the git server.
