### DISCUSSION TITLE
Grouping multiple 'in_parallel' tasks using 'do' steps

### DISCUSSION THREAD

**Discussion by marcransome** [concourse/concourse#5968] [General]
I'm currently investigating running groups of serial steps in parallel, for example:

```yaml
- in_parallel:
    - do:
        - task: generate-output-1
          ..
        - task: use-output-1
          ..
    - do:
        - task: generate-output-2
          ..
        - task: use-output-2
          ..
```

Both `generate-output-*` tasks generate an output of the same name. Similarly, both `use-output-*` tasks expect an input of the same name. My concern is whether there is any likely crossover between the outputs from the `generate-output-*` tasks in terms of what the subsequent `use-output-*` tasks see?

Syntactically the pipeline is valid and it runs as expected—exposing the correct outputs to the individual `use-output-*` tasks—but my question is wether it is generally considered safe to use `do` in this scenario and are there any caveats to this approach?
