### DISCUSSION TITLE
`across` step var interpolation doesn't work with resource names

### DISCUSSION THREAD

**Discussion by spiegela** [concourse/concourse#6061] [Help & Support]
I was trying out the new `across` step for a pipeline, and found that references to resource names don't seem to support the variable interpolation.

In this example, the task parameters work as expected, but the `input_mapping` block does not.

```yaml
  - name: kube-templates
    plan:
      - in_parallel:
          - get: pipelines
          - get: kube-template-v1.18.8
            trigger: true
          - get: kube-template-v1.19.1
            trigger: true
      - across:
          - var: kube_version
            values:
              - v1.18.8
              - v1.19.1
        do:
          - task: import-ova-spec
            file: pipelines/tasks/govc-cmd/task.yml
            input_mapping:
              files: kube-template-((.:kube_version))
            output_mapping:
              output: ova-spec
            params:
              <<: *govc_env
              COMMAND: import.spec
              ARGS: files/kube-((.:kube_version)).ova
```

I also found that `get` and `put` resource names are not interpolated with these variables, but that was easier to work around. Is there a way around this limitation that I'm not thinking of?

This may be expected behavior for this release of the feature. In that case, it would be really helpful to have resource names supported, as `across` works its way to GA.
