### DISCUSSION TITLE
Passed pulls in every version emitted from previous job rather than latest

### DISCUSSION THREAD

**Discussion by samgurtman-zz** [concourse/concourse#6097] [Help & Support]
Hello all,

I've been updating our version of https://github.com/eroad/aws-cloudformation-stack-resource. I've run into an issue in the pipeline snippet bellow. Basically, in the `test-out` job I update the resource multiple times, each time outputing a new version. However, the resource check only ever returns one version (because Cloudformation only ever has one valid version). In the next step `test-in` it appears that concourse tries to use the version that was emitted in the first  of the three updates from `test-out`, even though this version is not in the check, nor exists anymore. How do I stop the check from retaining the non existent versions?

```
- name: test-out
  serial: true
  plan:
  - in_parallel:
    - get: oss-ci
    - get: dev-image
      passed:
      - build
      params:
        skip_download:
    - get: version
      passed:
      - build
  - put: test-stack
    params:
      template: oss-ci/aws-cloudformation-stack-resource/test-stack/template.json
      parameters_aws: oss-ci/aws-cloudformation-stack-resource/test-stack/parameters.json
      tags: oss-ci/aws-cloudformation-stack-resource/test-stack/tags.json
      capabilities:
      - CAPABILITY_NAMED_IAM
      resolve_failed_create: true
  - put: test-stack
    params:
      template: oss-ci/aws-cloudformation-stack-resource/test-stack/template.json
      parameters_aws: oss-ci/aws-cloudformation-stack-resource/test-stack/parameters.json
      tags: oss-ci/aws-cloudformation-stack-resource/test-stack/tags.json
      capabilities:
      - CAPABILITY_NAMED_IAM
  - put: test-stack
    params:
      template: oss-ci/aws-cloudformation-stack-resource/test-stack/template.json
      parameters_aws: oss-ci/aws-cloudformation-stack-resource/test-stack/parameters2.json
      tags: oss-ci/aws-cloudformation-stack-resource/test-stack/tags.json
      capabilities:
      - CAPABILITY_NAMED_IAM
  - put: test-stack
    params:
      template: oss-ci/aws-cloudformation-stack-resource/test-stack/template.json
      tags: oss-ci/aws-cloudformation-stack-resource/test-stack/tags.json
      capabilities:
      - CAPABILITY_NAMED_IAM
- name: test-check-in
  serial: true
  plan:
  - in_parallel:
    - get: oss-ci
      passed:
      - test-out
    - get: test-stack
      trigger: true
      passed:
      - test-out
    - get: dev-image
      passed:
      - test-out
      params:
        skip_download: true
    - get: version
      passed:
      - build
  - task: test
    file: oss-ci/aws-cloudformation-stack-resource/test-check-in/task.yml
    ensure:
      task: delete-stacks
      file: oss-ci/aws-cloudformation-stack-resource/delete-stack/task.yml
      params:
        STACK_NAME: dev-test-deploy-stack
        REGION: ap-southeast-2
```
