### DISCUSSION TITLE
All resources broken with write errors after 6.5.1 -> 6.6.0 upgrade

### DISCUSSION THREAD

**Discussion by Roadmaster** [concourse/concourse#6141] [General]
Hello,

I have a small problem with my concourse after an upgrade, and was hoping someone here might point me in the right direction to get this fixed :)

I only have a very simple toy pipeline, which was working fine under 6.5.1, but all my resources broke once I updated to 6.6.0 and rebooted.

The faily resources are defined as follows (a few details changed for privacy) but note they were working fine with 6.5.1 so I don't believe the problem to be related to resource definition:
```
resources:
  - name: resource-tree
    type: git
    source:
      uri: https://git.launchpad.net/some-project
      branch: master
  - name: resource-concourse
    type: git
    source:
      uri: https://git.launchpad.net/~my-username/+git/concourse-pipeline-repo
      branch: master
  - name: resource-landing-branch
    type: git
    source:
      uri: git+ssh://my-username@git.launchpad.net/~my-username/some-project-test-landing-repo/
      branch: concourse-landing
      private_key: ((landing-ssh-private-key))
      git_config:
          - name: core.sshCommand
            value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
```
I could try running the actual tasks with a local resource, though I suspect they'd fail with a similar error.

The error is:

`run check step: run check step: find or create container: runc run: exit status 1: container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"process_linux.go:405: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"c 5:1 rwm\\\\\\\" to \\\\\\\"/sys/fs/cgroup/devices/system.slice/concourse-worker.service/garden/ef8200ba-a2c7-4e14-488d-309fc250a622/devices.allow\\\\\\\": write /sys/fs/cgroup/devices/system.slice/concourse-worker.service/garden/ef8200ba-a2c7-4e14-488d-309fc250a622/devices.allow: operation not permitted\\\"\""`

The host which is running both the web and worker processes is:

`
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
$ uname -a
Linux concourse 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
It has enough disk space and free RAM.

I didn't change anything else in the system's configuration:

1- 6.5.1 is working fine.
2- stop 6.5.1 worker/node, decompress 6.6.0 tarball, restart worker/node. Confirmed in web UI that it's now 6.6.0.
3- Ran the pipeline a couple of times, it worked...
4- Rebooted the system
5- Noticed all 3 resources are now yellow/failing with the above error.

Any help or advice would be appreciated. Since this is mostly a toy server I don't mind blasting away containers, databases, or anything needed, and rebuilding from scratch if needed. I'm also fine to wait if a solution is forthcoming (e.g. if it's related to https://github.com/concourse/concourse/issues/6118? )

Thanks!
