### DISCUSSION TITLE
Not clear how to pass version info through resource_types to registry-image

### DISCUSSION THREAD

**Discussion by Krenair** [concourse/concourse#6166] [Help & Support]
I'd like to be able to ensure that a resource type uses a specific image, compared against a sha256 digest - to ensure that no one with permissions on the Docker registry has tampered with the image.

The registry-image docs at https://github.com/concourse/registry-image-resource#use-in-tasks talk about a `version` struct outside of `source`.
However, https://concourse-ci.org/resource-types.html#schema.resource_type only talks about passing the `source` through to registry-image, nothing about `version`.

**Comment by taylorsilva** [comment]
Converted this to a discussion.

You're looking at `resource_types` in the docs when you meant to be looking at `resources` which has the `version` field: https://concourse-ci.org/resources.html#schema.resource.version

**Comment by jamieklassen** [comment]
In some sense, I think the party line for solving this problem is with immutable, descriptive tags on your images and access control such that you really trust your docker registry. in a zero-trust world this cannot be achieved, so I think you're asking for a way to checksum your resource type images themselves in some sense.

To be super clear, what you want is a pipeline like this?
```yaml
resource_types:
- name: my-custom-resource-type
  type: registry-image
  source: {repository: my-repo, tag: a-tag-that-might-change} # hence my "immutable" comment
  version: {digest: 'sha256:sha-of-an-exact-image-that-i-trust'} # this is the schema that doesn't exist
resources:
- name: my-custom-resource
  type: my-custom-resource-type
  source: {the: source-config, for: your-type}
jobs:
- name: use-my-custom-resource
  plan:
  - get: my-custom-resource
```

I think this could be a good feature, though it [does not yet exist](https://github.com/concourse/concourse/blob/76187be2e06dc66278ee582a0a50117a2fcbf630/atc/config.go#L189-L200) -- we've had the experience of depending on third-party resource types that maybe don't follow very strict semver (or we just grab `latest`), or whose images sometimes become corrupt. If we could pin an exact version in cases when an upstream dependency broke that could help us unblock our pipelines in such disaster scenarios.
