### DISCUSSION TITLE
Creating a git tag and pushing it to github

### DISCUSSION THREAD

**Discussion by meezaan** [concourse/concourse#6190] [Help & Support] [answered]
Hi folks

I'm new to Concourse and am trying to create a git tag and then push that tag up to GitHub. Perhaps I don't understand how the resource in and out bits works correctly, but I have been unable to find examples to help with in this regard. 

I am running Concourse on K8S using the stable helm chart with version 6.6.0:

Here is what I have:

```
---
resources:
  - name: concourse-php-repo
    type: git
    icon: github
    source:
      uri: git@github.com:somerepo.git
      branch: master
      private_key: ((github_private_key))

jobs:
  - name: test-and-build-app
    public: true
    plan:
      - get: concourse-php-repo
        trigger: true
      - task: unit-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: islamicnetwork/php74, tag: cli }
          inputs:
            - name: concourse-php-repo
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd concourse-php-repo
                composer install
                vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
      - task: git-tag
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          outputs:
            - name: release_tag
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo test-tag > release_tag/VERSION
      - put: concourse-php-repo
        params:
          repository: release_tag
          tag: VERSION
          only_tag: true
```
But the put fails every time saying VERSION does not exist.

Can someone please point me in the right direction?

Thank you!
