### DISCUSSION TITLE
Caching on multi-stage Docker image builds

### DISCUSSION THREAD

**Discussion by funkypenguin** [concourse/concourse#6225] [Help & Support]
Hey gang!

We have pipelines which build several Docker images, using multi-stage builds. Our usual approach is one (or more) stages with development tooling and libraries to actually do the application build, and a final stage (`FROM` scratch or alpine) for the end image.

After enabling caching (example below), we've noticed that the _final_ stage is nicely cached, but the intermediate stages (which are the most time-consuming) are not.

Example:

```
    # Build image to use for unit testing
    - put: image-test
      params: 
        build: git-source
        dockerfile: git-source/ci/Dockerfile.test    
        tag_as_latest: true       
        cache: true
        cache_tag: latest
```

I've read that caching can be a problem on multi-stage builds (https://pythonspeed.com/articles/faster-multi-stage-builds/), and I've also validated that the _entire_ multi-stage build is cached when I run on my local Docker desktop (obviously not the same as running in Concourse).

So I'm seeking advice re how to achieve the best performance on the image builds in my pipeline - I'd originally assumed this to be "cache-to-the-max", but then I realized that I also _wouldn't_ want to cache previously built code, which raises the question of what would cause an invalidation of the cache?

Any ideas / suggestions are welcome ;)

D
