### DISCUSSION TITLE
resource script (/opt/resource/out /tmp/build/put) output a null version

### DISCUSSION THREAD

**Discussion by kalrashubham49** [concourse/concourse#6239] [Help & Support]
## Summary
Custom Resource Not Working

## Steps to reproduce
when trying to run a pipeline with below content out executable is not working

```yaml
resource_types:
    - name: http-api
      type: docker-image
      source:
        repository: kalrashubham49/custom-http-resource
        tag: v2.2

resources:
      - name: clair
        type: http-api
        source:
            uri: http://45.33.90.33:8081/health
            method: GET
jobs:
      - name: test-http
        plan:
          - put: clair
```
            

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?
