### DISCUSSION TITLE
Hashicorp Vault/Concourse setup error: failed to read request: json: cannot unmarshal object into Go struct field Source.source.password of type string

### DISCUSSION THREAD

**Discussion by awidner** [concourse/concourse#6259] [Help & Support] [answered]
Hello,

I am trying to integrate our Hashicorp Vault 1.5.4 instance with Concourse 6.6.0. Upon running the pipeline it errors with the following message:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to read request: json: cannot unmarshal object into Go struct field Source.source.password of type string
```
This is the pipeline configuration:
```
---

resources:
- name: terraform-repo-master
  type: git
  check_every: 1m
  source:
    uri: ((terraform_repo_full))
    branch: ((terraform_repo_branch))

- name: pipeline-repo
  type: git
  source:
    uri: ((pipeline_repo_full))
    branch: ((pipeline_repo_branch))

- name: timer
  type: time
  icon: clock-outline
  source:
    interval: 4h

jobs:
- name: terraform-plan
  serial: true
  plan:
  - get: terraform-repo-master
    version: every
  - get: pipeline-repo
  - get: timer
    trigger: true
  - task: execute-plan
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker_repo))
          tag: "latest"
          username: ((registry-username))
          password: ((registry-password))
      inputs:
        - name: terraform-repo-master
        - name: pipeline-repo
      outputs:
        - name: terraform-repo-master
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            pip3 install --upgrade pip
            pip3 install pygithub
            python3 ./pipeline-repo/python/terraformBuilder.py
      params:
        AZ_LOGIN_TYPE: ((az_login_type))
        TERRAFORM_COMMAND: plan
        TERRAFORM_REPO: terraform-repo-master((terraform_repo_build_directory))
        HIDE_CODE_IN_PR: ((hide_code_in_pr))
        PIPELINE_REPO: pipeline-repo
        ARM_ENVIRONMENT: public
        ARM_CLIENT_ID: ((arm_client_id))
        ARM_CLIENT_SECRET: ((arm_client_secret))
        ARM_SUBSCRIPTION_ID: ((arm_subscription_id))
        ARM_TENANT_ID: ((arm_tenant_id))
        ARM_ACCESS_KEY: ((arm_access_key))
        JIRA_BASIC_AUTH: ((jira_basic_auth))
        GIT_API_KEY: ((git_access_token))
        GIT_ORG: ((git_org))
        GIT_REPO: ((git_repo))
        GIT_USE_MKTP_IO: true
```
I can see that the Concourse web node is getting tokens via the `approle` configuration. 

I really have no idea where to begin troubleshooting that error. I did destroy and re-create the pipeline which resulted in no change. Not sure what additional information would be needed for troubleshooting, just let me know. Thanks
