### DISCUSSION TITLE
Using garden's runtime-plugin to execute GPU-accelerated tasks

### DISCUSSION THREAD

**Discussion by funkypenguin** [concourse/concourse#6261] [Help & Support]
Hey folks!

I'm trying to pass a custom `runtime-plugin` to garden, in order to execute containers using nvidia's runc runtime, so that I run GPU-accelerated workloads. I'm executing concourse worker like this:

```
./bin/concourse worker --tsa-public-key=elpenguino-tsa-public.key-pub --tsa-worker-private-key=worker.key --tsa-host=192.168.32.5:2222 --team=main --tag=gpu-worker --work-dir=/tmp/concourse --runtime=guardian --ephemeral --garden-config=garden-config.ini --log-level=debug
```

And `garden-config.ini` looks like this:

```
[server]
runtime-plugin=/usr/bin/nvidia-container-runtime
log-level=debug
dns-server = 8.8.8.8
dns-server = 8.8.4.4
```

However, the nvidia runtime is not used to execute the containers, and thus I don't have the acceleration :(

Here's a task I'm using to test - note that if nvidia's runtime is not used, then `/usr/bin/nvidia-smi` won't exist:

```
inputs: 
  - name: git-source
outputs:
  - name: model
platform: linux
image_resource:
  type: registry-image
  source:
    repository: nvidia/cuda
    tag: 11.0-base-ubuntu20.04
    username: ((concourse.docker_hub_username))
    password: ((concourse.docker_hub_password))
run: 
  path: /bin/bash 
  args:
    - -c 
    - |
      /usr/bin/nvidia-smi
      exit 0
```

Any ideas / pointers?

Cheers! :)
D
