### DISCUSSION TITLE
git fetching on wrong worker?

### DISCUSSION THREAD

**Discussion by joeld42** [concourse/concourse#6303] [Help & Support]
Hey this is probably a dumb questions but I'm feeling kind of stumped. I'm trying to set up a simple build, right now I have two worker nodes (one linux vm and a mac build server). I'm trying to set up something like the "list files" example where it pulls a github repo and just prints out the files. Right now the problem is that it's pulling the git repo on the linux worker, and then trying do the ls task on the mac build. 

```yml
---
resources:
- name: myproject-src
  type: git
  icon: github
  source:
    branch: master
    uri: ((myproject-uri))    
    private_key: ((myproject-private-key))   

jobs:
  - name: myproject-testflight
    public: true
    plan:
      - get: myproject-src
      - task: build
        config:
          platform: darwin
          inputs:
              - name: myproject-src
          run:
            path: find
            args: [.]
```

When I look at the build log on the web node, the "Selected Worker:" shows the "get" step on the linux machine, "tk_build" and the "build" step on the mac "pareidolia". These both should run on the mac and in the same job.

<img width="1309" alt="Screen Shot 2020-11-20 at 5 19 14 PM" src="https://user-images.githubusercontent.com/24752/99863829-d4a89f80-2b54-11eb-8ad9-e8abf9ad191b.png">

I feel like I'm missing something basic in getting the git pull to run in the same step. My understanding is that having the "myproject-src" as an input should make it fetch it before running the job, but this doesn't seem to happen.

Thanks!

Note: The "job-pass-files" tutorial seems to do the same thing..
