### DISCUSSION TITLE
Issue with automatic trigger on each new repo tag

### DISCUSSION THREAD

**Discussion by giva01121** [concourse/concourse#6341] [Help & Support]
Hello, 
from some time we are facing a problem with the automatic trigger of the pipelines on new tag release. I want the pipeline to be triggered on each new stratos release. Please give me a suggestion if you think that my logic is wrong.
My concourse version is 6.7.1
Here's a snipper from my pipeline

```
---
  platform: linux
  resources:
    - name: github-stratos
      check_every: 1h
      type: git
      source:
        uri: https://github.com/cloudfoundry/stratos.git
        branch: master
        username: ((someuser))
        password: ((somepass))
        tag_filter: "*"
  jobs:
    - name: run-check-script
      public: true
      plan:
      - in_parallel:
        - get: github-stratos
          trigger: true
 ```
