### DISCUSSION TITLE
2 Jobs, Same Trigger Input, One doesn't run

### DISCUSSION THREAD

**Discussion by isaacsanders** [concourse/concourse#6344] [Help & Support]
Hey all,

We have a number of pipelines like this. There is a Pull Request resource that is the input to two jobs, and serves as the triggering input (`trigger: every`) for both.

One job (Generic Checks) picks up the new versions of the Pull Request resource, the other (CI Checks) doesn't.

Our server is on 6.7.0, for context.

**Comment by isaacsanders** [comment]
@vito If you have any ideas for how I can help debug this, please let me know.

**Comment by taylorsilva** [comment]
Hello again! 😁 

> We have a number of pipelines like this

Do you mean in this state you're describing where one job does not trigger automatically?

FYI vito is on vacation... the whole team is really. It's just myself and one other eng hanging around and I'm actually off end of this week too. Things will be back to normal in January.

**Comment by asummers** [comment]
Our pipelines are configured from a template, so there are dozens with the exact same shape (with a few env var substitutions here or there) where there are 2 jobs listening on `version: every` that work how one would expect. But for a few of them, they do not.  

Observed behavior: 

Input is a git PR resource `pr-resource`
Two jobs have `version: every` pointing to `pr-resource`
On the `pr-resource` resource list page, it shows proper version 123 properly as new version, properly detecting everything in order
One of the two jobs kicks off, but the other does not until manual `+` button push, where it pulls in the proper version as expected. 

We had a previous pipeline that exhibited this same behavior, and deleting +recreating seemed to "fix", but it showing up again points to a deeper issue somewhere.

**Comment by taylorsilva** [comment]
Testing this out, I made this pipeline:
```yaml
resources:
- name: time-resource
  type: time
  source:
    interval: 30s

jobs:
- name: job-1
  plan:
  - get: time-resource
    trigger: true
    version: every
- name: job-2
  plan:
  - get: time-resource
    trigger: true
    version: every
```
and set it three times. I'm going to leave it running and see if the issue comes up. I'll know if that happened when the build numbers aren't in sync. It'll mean one of them missed a build
