### DISCUSSION TITLE
How does a pool-resource work throughout a pipeline?

### DISCUSSION THREAD

**Discussion by loewenstein** [concourse/concourse#6374] [Help & Support]
Hi, 

I've got a Question about pool-resource: if I have a chain of jobs, say 'prepare', 'deploy', 'test' and 'cleanup' that should all work on the same environment. 'prepare' claims the env from a pool (or even does add_acquired), the others get the env and 'cleanup' releases (or even removes).

How is it guaranteed that we don't leak environments? I.e. if we have multiple runs of 'prepare' that are fast enough then the passed=prepare directive will be fulfilled by all those runs, but only one of the claims will be used and consequently released, right?

I hope I just got it wrong, because this would drastically limit the usefulness of pools...

**Comment by taylorsilva** [comment]
Looking at the examples: https://github.com/concourse/pool-resource#example-concourse-configuration
it seems like the environments shouldn't leak. For good measure you may want to set `version` to `every` for the [`get step`](https://concourse-ci.org/jobs.html#schema.step.get-step.version) to ensure all envs are eventually released

**Reply by loewenstein** [reply]
With the following configuration, three locks in unclaimed state and triggering 'acquire' 7 times in a row I was able to end up with all three locks in claimed state.

```
resources:
- name: pool
  type: pool
  source:
    uri: <lock-repo>
    branch: main
    pool: pool
    private_key: "<redacted>"


jobs:
- name: acquire
  plan:
    - put: pool
      params: {acquire: true}
    - task: task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        run:
          path: sleep
          args:
          - "1"

- name: use
  plan:
    - get: pool
      trigger: true
      passed: [acquire]
    - task: task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        run:
          path: sleep
          args:
          - "45"

- name: release
  plan:
    - get: pool
      trigger: true
      version: every
      passed: [use]
    - task: task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        run:
          path: sleep
          args:
          - "1"
    - put: pool
      params: {release: pool}
```

Also from a "theoretical' perspective, `version: every` and `passed: [use]' seem to be conflicting. I.e. if a pool that's acquired in `acquire` doesn't get picked up in 'use', then it must not get picked up in `release` either because of `passed`, although `version: every` would require it to be picked up.

I might still be wrong, that's why I'd like to better understand if and why lock leaks cannot happen.
