### DISCUSSION TITLE
Question on serial groups and if they can lead to non-deterministic job execution order

### DISCUSSION THREAD

**Discussion by fauna-chase** [concourse/concourse#6390] [Help & Support]
If I setup a serial group that has 2 jobs in it, job1, job2.  job1 is automatically triggered by new versions of a resource and job2 has a passed constraint on that resource with trigger set too true.  Config shown below:
```
  - name: job1
    serial_groups: [deploy-prod]
    plan:
      - get: deploy-artifact
        trigger: true
      - task: do-stuff

  - name: job2
    serial_groups: [deploy-prod]
    plan:
      - get: deploy-artifact
        passed: [job1]
        trigger: true
      - task: do-more-stuff
```

While job1 is executing, a new version of the deploy-artifact resource is produced.  When job1 finishes executing, is which job will execute next non-deterministic?  Meaning that it could be either job1 with the new deploy-artifact resource or job2 with the deploy-artifact resource passed from job1.
