### DISCUSSION TITLE
set_pipeline step now interpolates variables

### DISCUSSION THREAD

**Discussion by AClarkie** [concourse/concourse#6398] [Help & Support]
As part of [this feature request](https://github.com/concourse/concourse/pull/5277/files) `vars` are now being interpolated, this has broken our usage of the `set_pipeline` step as we rely on passing through the literal string "((X-REPO-DEPLOY-KEY))" so that the pipeline itself loads the key from our secrets store, whereas now the content of the secret is being entered into the pipeline. Which would be fine but we rotate the secret daily.

Is there a workaround to not interpolate the variable?

**Comment by aoldershaw** [comment]
Hm I don't think there is a nice way to do this currently. It would be nice to have a way to escape var interpolation - for our `mock` resource, we invented a hack to avoid interpolating vars using `START_VAR` and `END_VAR` in place of `((`, `))`:

https://github.com/concourse/mock-resource/blob/9009b227e3f897f2cc05feaee4e3e751af03b966/cmd/in/main.go#L117-L118
```go
		str = strings.ReplaceAll(str, "START_VAR", "((")
		str = strings.ReplaceAll(str, "END_VAR", "))")
```

A native way would be ideal, but as a hacky workaround, you could do something like:

* Produce an file containing the string `((X-REPO-DEPLOY-KEY))`
  * Could be a task or using the mock resource with `START_VAR`/`END_VAR`
* Use `load_var` to load that file to a variable
* Use that local var in place of `((X-REPO-DEPLOY-KEY))` in your `set_pipeline` step

Using the mock resource, it could look like:

```yaml
resources:
- name: mock
  type: mock

jobs:
- name: some-job
  plan:
  - get: mock
    params:
      create_files:
        var_name: START_VAR X-REPO-DEPLOY-KEY END_VAR
  - load_var: deploy_key_var_name
    file: mock/var_name
  - set_pipeline: some-pipeline
    file: ...
    vars:
      deploy_key: ((.:deploy_key_var_name))
```

---

Obviously this is a crappy solution, but hopefully it can get you unblocked

**Comment by AClarkie** [comment]
Hey this doesn't seem to work for me I get the error `FATA[0000] invalid payload: json: unknown field "create_files" `

Config is below:

```
jobs:
  - name: set-concourse-non-meta-pipelines
    plan:
      - get: mock
        params:
          create_files:
            var_name: START_VAR x-deploy-key END_VAR
      - load_var: deploy_key_var_name
        file: mock/var_name
      - set_pipeline: x-repo
        file: git-repo-master/ci/x-thing.yaml
        vars:
          github-repo-deploy-key: ((.:deploy_key_var_name))
          github-repo: x-deploy-repo

resources:
  - name: mock
    type: mock
```
