### DISCUSSION TITLE
convert docker-image to s3 resource type

### DISCUSSION THREAD

**Discussion by mshannon68** [concourse/concourse#6451] [Help & Support]
I have an image hosted on harbor. We have a closed network, which only has an ECS S3 repository. I am wondering if there is a pipeline that can convert the docker-image resource to a .tgz that can be pulled through the s3 resource. And use that image as the container to perform work. Thanks.

**Comment by taylorsilva** [comment]
This is totally possible with the [registry-image resource](https://github.com/concourse/registry-image-resource/), s3 resource, and some glue tasks. I don't have an example but hopefully this helps.

With the registry-image you can `get` the image from harbor and have a second step tar the contents. Then you can have a  `put` step for an s3 resource that will store the result in s3. 

With that same s3 resource definition, in another job you can get `get` that resource (and untar it with the `unpack` param) and pass it in as the [`image`](https://concourse-ci.org/jobs.html#schema.step.task-step.image) for your task step.

```yaml
# in one job
- get: image-from-harbor
- task: tar-image
  config:
    inputs:
    - name: image-from-harbor
    outputs:
    - name: image-from-harbor
    ...<rest of config where you tar the contents>
- put: my-s3
  params:
    # or whatever you decide to name the file
    file: image-from-harbor/image.tgz


# in another job
- get: my-s3
  params:
    unpack: true
# have the image use the task!
- task: my-task
  image: my-s3
```

Note: the registry image can output to OCI format, which is a `tgz` file. Sadly Concourse does not currently understand this format which is why the task step is needed to tar the default output format.
