### DISCUSSION TITLE
Still falling into Docker Pull rate limit with Concourse 6.7.3

### DISCUSSION THREAD

**Discussion by erboucherie** [concourse/concourse#6502] [Help & Support]
Hello all , we created recently a Concourse 6.7.3 infra , and i was surprised to fall into the **Docker Pull rate limit** despite of the workaround implemented in [v6.7.0](https://github.com/concourse/concourse/releases/tag/v6.7.0) .
Reading at the documentation , the only difference i can see , is the way we use that image : it's not a get or put , but it's the container image itself  :  

```yaml
platform: linux
image_resource:
  type: docker-image
  source:
    repository: private/myimage
inputs:
- name: other
params:
run:
  path: other/path/tasks/mytask.sh
```

Any ideas ?
Thanks
