### DISCUSSION TITLE
Question regarding how concourse deals with resource and triggers

### DISCUSSION THREAD

**Discussion by DavidFliguer** [concourse/concourse#6534] [Help & Support]
Hi everyone

I'm pretty new to Concourse and I would like to understand better about the flow of the pipelines regarding resources, triggers, etc

I have the following pipeline:

```YAML
resources:
-  name: my-repo
  type: git
  icon: github
  source:
    uri: https://github.com/DavidFliguer/concourse-test-2

jobs:
- name: job
  public: true
  plan:
  - get: my-repo
    trigger: true
  - task: list-files
    config:
      inputs:
        - name: my-repo
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ubuntu }
      run:
        path: bash
        args: ["-c", "sleep 30"]

- name: job2
  public: true
  plan:
  - get: my-repo
    trigger: true
    passed: [job]
  - task: list-files
    config:
      inputs:
        - name: my-repo
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: ls
        args: ["-la", "./my-repo"]
```

Lets say the latest commit for the resource is t6hj7

When I make a new commit (lets say a582e) in the repository, then my understanding of what happens is that when the commit is "discovered" by concourse it updates the resource and set it as the latest commit, since both jobs have trigger they both get triggered but since job2 has the passed flag, it will run on the new commit only when that commited served as a pass 

So the result is 

1 . job1 starts running on a582e
2. job1 finishes running on a582e 
3. job2 starts running on a582e
4. job2 finishes running on a582e

However let's say that after that I make a new commit (lets say b9u32) and once job1 starts to run I manually start job2, then the flow that I see that happens is

1. job1 starts running on b9u32
2. When I manually start, job2 starts running on a582e
3. job2 finishes running on a582e
4. job1 finishes running on b9u32
5. job1 starts running on b9u32
6. job1 finishes running on b9u32

So my question is, if concourse runs job2 in the latest commit that passed job1, then why in the first scenario it does not start running job2 on a582e, instead it is "wise" enough to wait for the new commit to run on job1 and finish, but then why is not enough "wise" in the second scenario ?

Or the idea is that in the second scenario since I made a manual run then it "overrides" and the logic is different for manual triggers than for triggers that come from the external resource ?

Hope you understand my question (I can try to explain myself better if needed)

Thanks beforehand for the help
