### DISCUSSION TITLE
Skipping a step or Conditional execution of a step

### DISCUSSION THREAD

**Discussion by piroux** [concourse/concourse#6560] [Help & Support]
Hi everybody,

I already have a working Concourse cluster which works great for unit/integration tests with multiple projects.

Now I am trying to improve my workflow by deploying new pipeline files against a local "test" Concourse cluster in order to iterate on these pipeline files and check them before deploying them to the "prod" Concourse cluster. 
So I want to find a way to deactivate/skip the build status updates steps (sent to Github/Bitbucket) that I insert at the beginning and at the end of most pipeline jobs when I am deploying the pipelines files on the local "test" Concourse cluster, in order not to pollute the Github/Bitbucket web interface and avoid annoying developers.
It means that I would like those steps to be deactivated based on the value of a variable, hence skipping the execution of the step when an expression is verified like `CLUSTER_NAME == "ci-prod"` for instance.

However **I cannot find a skipping/deactivation mechanism for a job step**, whether the step is a task, a put, or a get.
[Have I missed it ?](https://concourse-ci.org/jobs.html#steps)

What I would need is something like:

- step deactivation based on expression
```
- put: build-status
  params:
    repository: project-repo
    build_status: INPROGRESS
  skip_when: CLUSTER_NAME == "ci-test"
```
- step execution based on expression
```
- put: build-status
  params:
    repository: project-repo
    build_status: INPROGRESS
  when: CLUSTER_NAME == "ci-prod"
```

I have looked into issues and rfcs, but I have not found anything relevant.
Anybody would have pointers on this kind of mechanism ?
Should/Could I open an rfc for this mechanism ?

Thank you very much in advance!
