### DISCUSSION TITLE
is possible to send status from concourse to gitlab

### DISCUSSION THREAD

**Discussion by Mizugorou** [concourse/concourse#6568] [Help & Support]
Hi,

I work on gitlab with concourse. I want to send status from Concourse to Gitlab. So when I open my gitlab, I will be able to go directly to what job is.

I found an [Gitlab api](https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit) to tell what status being and directly link by `target_url` param. I get the metadata from resource and I make my task in job to run with curl. so it can send status `running` and gitlab know it. However, for the `on_success`, `on_failure`, `on_abort`, it doesn't look like to work by same above method. As I understand, `on_success` can not do the `get`, `put`, `task` together in this process. Could please advise me to work with send status?

In additional, I found the `put` in `on_success` can be sent to `out` of  `resource_type`. Or, I have to implement my own `resource_type` ?.
But, if I implement my own `resource_type`, I have to capture every new commit on branch my branch that `type: git` is really implemented. Am I right?

#### Pipeline trigger behavior
run every new commit at watching branch

#### Example Pipeline
```
resource_types:
- name: metadata
  type: docker-image
  source:
    repository: olhtbr/metadata-resource
    tag: 2.0.1
resources:
- name: todoapp
  type: git
  source:
    url: https://gitlab.com/Mizugorou/todoapp.git
    branch: testing
- name: metadata
  type: metadata

jobs:
- name: test-send-status
  plan:
    - get: todoapp
      trigger: true
    - put: metadata
    - put: todoapp
      params:
        repository: todoapp
    - task: send-running
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
            tag: "20.04"
        params:
          PRIVATE_TOKEN: ((private_token))
          PROJECT_PATH: Mizugorou%2Ftodoapp
          repository: todoapp
          status: running
        inputs:
          - name: todoapp
          - name: metadata
        outputs:
          - name: properties
        run:
          path: sh
          args:
            - -c
            - |
              # Grab the metadata
              url=$(cat metadata/atc_external_url)
              team=$(cat metadata/build_team_name)
              pipeline=$(cat metadata/build_pipeline_name)
              job=$(cat metadata/build_job_name)
              build=$(cat metadata/build_name)
              REF_SHA=$(cat ${repository}/.git/ref)
              job_url="$url/teams/$team/pipelines/$pipeline/jobs/$job/builds/$build"
              # send status running to gitlab
              curl --request POST --header "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_PATH}/statuses/${REF_SHA}?state=${status}&target_url=${job_url}"
  on_success:
    - get: todoapp
      trigger: true
    - put: metadata
    - put: todoapp
      params:
        repository: todoapp
    - task: send-success
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
            tag: "20.04"
        params:
          PRIVATE_TOKEN: ((private_token))
          PROJECT_PATH: Mizugorou%2Ftodoapp
          repository: todoapp
          status: success
        inputs:
          - name: todoapp
          - name: metadata
        outputs:
          - name: properties
        run:
          path: sh
          args:
            - -c
            - |
              # Grab the metadata
              url=$(cat metadata/atc_external_url)
              team=$(cat metadata/build_team_name)
              pipeline=$(cat metadata/build_pipeline_name)
              job=$(cat metadata/build_job_name)
              build=$(cat metadata/build_name)
              REF_SHA=$(cat ${repository}/.git/ref)
              job_url="$url/teams/$team/pipelines/$pipeline/jobs/$job/builds/$build"
              # send status running to gitlab
              curl --request POST --header "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "https://gitlab.com/api/v4/projects/${PROJECT_PATH}/statuses/${REF_SHA}?state=${status}&target_url=${job_url}"
```
