### DISCUSSION TITLE
Github OAuth failure - 404

### DISCUSSION THREAD

**Discussion by puckettgw** [concourse/concourse#6666] [Help & Support] [answered]
I'm running Concourse on Kubernetes, using the Helm chart provided by Concourse. The relevant settings are as follows:
```
      github:
        enabled: true
        ## Hostname of GitHub Enterprise deployment (No scheme, No trailing slash)
        ##
        host: github.com

        ## Authentication (Main Team) (GitHub)
        ##
        github:
          ## Comma-separated allow list of GitHub users.
          ##
          user: puckettgw,RedactedNotMe
          ## Comma-separated allow list of GitHub orgs.
          ##
          org: SomeOrg1,SomeOrg2
          ## Comma-separated allow list of GitHub teams.
          ##
          team:

  ## Secrets for GitHub OAuth.
  ##
  githubClientId: REDACTED
  githubClientSecret: REDACTED
  githubCaCert:
```

When I attempt to login via GitHub, I get the error in the attached screenshot.

![image](https://user-images.githubusercontent.com/1858718/111242069-c9322600-85d4-11eb-9a18-b98a751eeaf1.png)

I've checked that my callback URL and client id / client secret are set properly, and GitHub does show that my token was used today (this is the only thing using the token, i created the OAuth app specifically for Concourse.)

This is not the same error that is returned from having an invalid callback URL (I got that error before, it's much shorter and not comprised of a huge pile of HTML)

Has something changed on the GitHub end? Has anyone seen a similar problem and know where I'm going wrong? If you need more info, I'd be happy to provide it.
