### DISCUSSION TITLE
Unable to clone the github repo

### DISCUSSION THREAD

**Discussion by skdubey** [concourse/concourse#6782] [Help & Support]
Hi I am very new to Concourse and trying my hands dirty on this, but has stuck at very first level. 

What am I doing? 
I am trying to pull a private repository from github. 

My config files - 

main.yml
```yaml
---
resources:
- name: pullcode
  type: git
  source:
    uri: git@github.com:user/test.git
    branch: master
    username: git
    password: xyz
    private_key: ((keys.private_key))   

jobs:
- name: buildcode
  plan:
  - get: pullcode
    trigger: false
  - task: create-image
    file: build-image.yml
```

**private.yml -** 
```yaml
keys:
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      -----END RSA PRIVATE KEY-----
```

**Command:**  `.\fly.exe -t devops set-pipeline --pipeline hello -c .\main.yml -l .\private.yml`

git pull is working locally for me but not when I try to un my pipeline in Concourse. Getting error below - 

```
_selected worker: ip-10-30-0-27
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists._
```

Not sure what is missing. 

If I try with url (uri: https://github.com/user/test.git), getting error below - 
selected worker: ip-10-30-0-27
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/user/test.git/': Could not resolve host: github.com

System details - 
1. self hosted concouser on EC2 instance (Linux)
2. Running command from Windows10 using Powershell 
3. Concourse version: 7.0.0
4. Fly.exe version: 7.0.0

**Comment by crsimmons** [comment]
What you have looks mostly correct. Two things:

1. You don't need both `username`/`password` _and_ `private_key` in the git resource source. Use the former with `uri: https://foo.git` and the latter with `uri: git@github.com/foo.git`.
2. Whitespace matters a lot with YAML especially in the vars file. It's hard to tell with the formatting in your post if you got it right. I would expect the following to work:
```
---
# main.yml
resources:
- name: pullcode
  type: git
  source:
    uri: git@github.com:user/test.git
    branch: master
    private_key: ((keys.private_key))

jobs:
- name: buildcode
  plan:
  - get: pullcode
    trigger: false
  - task: create-image
    file: build-image.yml
---
# private.yml
keys:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    -----END RSA PRIVATE KEY-----
```
