### DISCUSSION TITLE
Pass build date in build_args when building Dockerfile

### DISCUSSION THREAD

**Discussion by ddhanak** [concourse/concourse#6810] [General]
Hi! 

Couldn't find this anywhere but is it possible to pass build date in build_args when building a Dockerfile?

Thanks!

**Comment by taylorsilva** [comment]
You'll need to have a task generate the date in the format you want. You could output the date into a file and then use [`load_var`](https://concourse-ci.org/jobs.html#load-var-step) to read the file into a variable that you can then pass into your build step as a param using the var format `((.:my-var))`

Might look something like this:
```yaml
- task: generate-date
  config:
  ...
  outputs:
  - name: todays
  run:
    path: sh
    args:
    - -cx
    - |
      date +'%Y%m%d' > todays/date
- load_var: date
  file: todays/date
- task: build-image
  config:
    ...
    params:
      ARG_DATE: ((.:date))

```
