### DISCUSSION TITLE
Bundle Git repo and pipeline definition?

### DISCUSSION THREAD

**Discussion by robinhuiser** [concourse/concourse#6823] [Help & Support]
Hi all,

From what I understand today of Concourse, the Git repository (storing the source code of the component you want to build) and the pipeline definition file(s) are not linked.

I've been working with Circle CI, Bitbucket, etc... and I am used to define the pipeline within the project's repository.

How would I accomplish the same with Concourse?

Thanks!!!

Robin

**Comment by chbiel** [comment]
it's relatively simple as you can reference yaml task definition files from a git resource like:

your repo file structure:
```
- project
  - ci
    - pipeline.yaml
    - my_task.yaml
  - ... other stuff ....
```

pipeline.yaml
```
resources:
  - name: git
    type: git
    source:
      branch: master
      uri: your_repo
jobs:
  - name: pipeline
    serial: true
    plan:
      - get: git
        trigger: true
      - set_pipeline: my_pipeline
        file: git/ci/pipeline.yaml

  - name: my_job
    serial: true
    plan:
      - in_parallel:
          - get: version
            passed: [pipeline]
            trigger: true

      - task: my_task
        file: git/ci/my_task.yaml
```

you only need to use the fly cli to apply the pipeline config once (with `fly set-pipeline --pipeline my_pipeline`). Ensure that the `--pipeline` has the same value like you use in the `set_pipeline` in the pipeline task.

After that the "pipeline" job will update your pipeline from the pipeline.yaml automatically and after that run the dependent jobs. (you can also leave this out and configure the pipeline manually. You can still reference task definitions in th git resource)

i hope that helped :)

sources:
https://concourse-ci.org/setting-pipelines.html
https://concourse-ci.org/jobs.html#set-pipeline-step
https://concourse-ci.org/jobs.html#schema.step.task-step.file
