### DISCUSSION TITLE
Understanding the new placement strategies and chaining

### DISCUSSION THREAD

**Discussion by chbiel** [concourse/concourse#6824] [Help & Support]
Hey everybody,
first: I saw the other discussions on the placement strategies and slow task-startup performance but non of them helped.

So we saw waiting times between our tasks from 1 to 10 minutes (partly also on the same "task transitions").
When seeing the new placement strategy chaining, I thought "well that will be cool" :) (see https://concourse-ci.org/container-placement.html#chaining-placement-strategies)

So we currently set it to: `volume-locality,fewest-build-containers`

A stripped down version of the job in focus:
```
...
   plan:
      - in_parallel:
          - get: version
            passed: [pipeline]
            trigger: true
          - get: git
            passed: [pipeline]

      - task: test-and-build
        timeout: 10m
        file: git/ci/test-and-build.yaml

      - put: docker
        params:
          build: application-build
          tag: version/number
          tag_as_latest: true
          cache: true
          cache_tag: latest
        get_params:
          skip_download: true
...
```

the `test-and-build.yaml` has the inputs/outputs as:
```
...
inputs:
  - name: git
  - name: version
outputs:
  - name: application-build
    path: output
...
```

As you can see, all the outputs / inputs are mentioned here and reference outputs from the tasks before.

So my expectation now was:
All three tasks should be executed on the same worker due to `volume-locality` strategy.

But what actually happens is:
All tasks are executed on 3 different workers, leading to (as I expect) much streaming time.

So my question is: WHY? :D
Are there ways to debug, how concourse applies the placement strategies?

Someone has a clue? I am open for any ideas... :)
