### DISCUSSION TITLE
registry_mirror erroring

### DISCUSSION THREAD

**Discussion by skreddy6673** [concourse/concourse#6827] [General]
Hello there,

In my concourse Helm values file i configured the registry_mirror like this
```
    baseResourceTypeDefaults: |
       registry-image:
         registry_mirror:
           host: https://dockerhub-mirror.XXX
 ```
 
 When i run below pipeline 
 ```
 jobs:
- build_log_retention:
    builds: 15
  max_in_flight: 1
  name: time-test
  plan:
  - get: time-test
    trigger: true
  - config:
      image_resource:
        source:
          repository: busybox
        type: registry-image
      inputs:
      - name: time-test
      platform: linux
      run:
        args:
        - time-test/input
        path: cat
    task: print-time
  - put: time-test
  public: true
resources:
- check_every: 1m
  name: time-test
  source:
    location: America/New_York
    start: 11:27 AM
    stop: 12:00 AM
  type: time
  ```
  It is failing with error message
  ```
  resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31mERRO[0m[0000] could not resolve registry: registries must be valid RFC 3986 URI authorities: https://dockerhub-mirror.XXX
```

**Comment by skreddy6673** [comment]
When replaced registry-image with docker-image it is working fine.

**Comment by aoldershaw** [comment]
Have you tried getting rid of the `https://` prefix?

**Reply by skreddy6673** [reply]
Yes, 
```
baseResourceTypeDefaults: |
      registry-image:
        registry_mirror:
           host: dockerhub-mirror.XXX
 ```
 
    Still failing when i use docker-image type in the pipeline with below error
    
```
    waiting for docker to come up...
Pulling busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac...
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

```

**Comment by evanchaoli** [comment]
I ever successfully used a mirror with the follow code:

```yaml
  - task: some-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
          registry_mirror:
            host: 10.185.19.14:5000
```

where, `10.185.19.14:5000` is my local registry mirror listening on port 5000.

**Reply by skreddy6673** [reply]
I'm trying to set registry_mirror at the instance level instead of at the Pipeline level as i cannot get all my Application team to make this change to their pipeline.

**Comment by skreddy6673** [comment]
@taylorsilva @vito Any suggestion on how to get it working?

Concourse version: v6.7.2
Helm Chart: v14.5.0

**Reply by taylorsilva** [reply]
Tried to reproduce v7.2.0:

values.yaml
```patch
diff --git a/values.yaml b/values.yaml
index e9e7bee..9a84ced 100644
--- a/values.yaml
+++ b/values.yaml
@@ -285,7 +285,10 @@ concourse:
     ##     registry_mirror:
     ##       host: https://registry.mirror.example.com
     ##
-    baseResourceTypeDefaults: ""
+    baseResourceTypeDefaults: |
+       registry-image:
+         registry_mirror:
+           host: gcr.io

     ## Compression to use when streaming artifacts (values: zstd, gzip)
     ##
```

pipeline.yaml
```yaml
---
jobs:
- name: simple-job
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: google-containers/busybox}
      run:
        path: echo
        args: ['Hello, world!']
```

And got this:
- Appears to initially reach out to `gcr.io`. The check step is successful but the get step...
- then tries downloading from `docker.io` instead and we get an auth error. I can do `docker pull gcr.io/google-containers/busybox` with no auth from my workstation. It appears the final download ignores the registry_mirror?? 
```
fetching gcr.io/google-containers/busybox@sha256:d8d3bc2c183ed2f9f10e7258f84971202325ee6011ba137112e01e30f206de67

WARN[0000] download from mirror gcr.io/google-containers/busybox failed: get image: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377 

fetching google-containers/busybox@sha256:d8d3bc2c183ed2f9f10e7258f84971202325ee6011ba137112e01e30f206de67

ERRO[0000] download failed: get image: GET https://index.docker.io/v2/google-containers/busybox/manifests/sha256:d8d3bc2c183ed2f9f10e7258f84971202325ee6011ba137112e01e30f206de67: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:google-containers/busybox Type:repository]] 
```

If I add the `registry_mirror` stuff directly to my pipeline I get the same error. If I change the repository to include `gcr.io` then the download fails with 
```
fetching gcr.io/google-containers/busybox@sha256:d8d3bc2c183ed2f9f10e7258f84971202325ee6011ba137112e01e30f206de67

ERRO[0000] download failed: get image: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377 
```
Which is fine, at least I KNOW it's pulling from gcr.io now. Something is odd here. Will post the above as a reproducible in the registry-image resource.

**Reply by taylorsilva** [reply]
https://github.com/concourse/registry-image-resource/issues/275

**Reply by mymasse** [reply]
I might be seeing something similar about the mirror not being used, I didn't initially comment on this discussion since I was not seeing any errors just the mirror not being used.

Discussion: [6887](https://github.com/concourse/concourse/discussions/6887)

**Reply by taylorsilva** [reply]
You have a small mistake in your pipeline. After changing that let us know the results, if you're seeing what we're seeing^^

**Reply by mymasse** [reply]
My bad, all is good just ignore me

**Reply by taylorsilva** [reply]
@mymasse would you mind double-checking your output and seeing if the last line still says it's pulling from docker.io?

**Reply by mymasse** [reply]
Yeah it did pull from our Nexus cause it's now mirrored in it (we proxy to docker hub)

**Comment by skreddy6673** [comment]
@taylorsilva 
And also i observed that below resource type
```
resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: pivotalservices/artifactory-resource
      registry_mirror:
        host: dockerhub-mirror.apps.xxx
 ```
 results in 
 ```
 fetching pivotalservices/artifactory-resource@sha256:39f91e9ef471b2ef8f1d36f859533c219ff5034a6d703608eb2f1e2b6cbfd125
WARN[0000] fetching mirror dockerhub-mirror.apps.xxx failed: locate remote image: unsupported status code 404; body: 404 page not found 
ERRO[0000] fetching origin index.docker.io failed: locate remote image: MANIFEST_UNKNOWN: manifest unknown; map[Name:pivotalservices/artifactory-resource Revision:sha256:39f91e9ef471b2ef8f1d36f859533c219ff5034a6d703608eb2f1e2b6cbfd125] 
```
