### DISCUSSION TITLE
Concourse Put step , setup timeout

### DISCUSSION THREAD

**Discussion by kalrashubham49** [concourse/concourse#6866] [General]
Any Ideas, how to setup timeout of Put step through Code,

I have checked for timeout step , but i am unable to give it as PlanSequence

**Comment by taylorsilva** [comment]
How are you writing your pipeline? Sounds like it's not with YAML since you mention "through code".

Linking to the docs but I think you already know about this: https://concourse-ci.org/timeout-step.html
Example from the docs:
```yaml
plan:
- get: foo
- task: unit
  file: foo/unit.yml
  timeout: 1h30m
```
You can add timeout to any step, so your pipeline could also look like:
```yaml
plan:
- get: foo
  timeout: 1h
- task: unit
  file: foo/unit.yml
  timeout: 1h30m
- put: bar
  timeout: 5m
```
