### DISCUSSION TITLE
Registry-image registry_mirror not being taken into account

### DISCUSSION THREAD

**Discussion by mymasse** [concourse/concourse#6887] [Help & Support] [answered]
We have deployed Concourse using the 15.0.2 Helm chart (Concourse 7.1.0). In the helm chart values we have set the following 
```
baseResourceTypeDefaults: |
  registry-image:
    registry_mirror:
      host: <OUR NEXUS DOCKER>
      username: <NEXUS USER>
      password: <NEXUS USER PASSWORD>
```
We can see in kube the following property set on the container `CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS: /brt-defaults.yml` and the file in the container does contain:

```
registry-image:
  registry_mirror:
    host: <OUR NEXUS DOCKER>
    username: <NEXUS USER>
    password: <NEXUS USER PASSWORD>
```

However when we run this simple pipeline
```
---
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world]
```

We get when Concourse pulls the `busybox` image the first time the following message

```
selected worker: concourse-worker-0
waiting for docker to come up...
Pulling busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac...
docker.io/library/busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac: Pulling from library/busybox
f531cdc67389: Pulling fs layer
f531cdc67389: Verifying Checksum
f531cdc67389: Download complete
f531cdc67389: Pull complete
Digest: sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac
Status: Downloaded newer image for busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac
docker.io/library/busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac

Successfully pulled busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac.
```

Why is it not pulling the image from our mirror. My understanding was that this was the way to set a global mirror. I've also checked in our Nexus server and confirm the image is not cached so it seems like it went to docker hub instead.

What are we doing wrong?

**Comment by taylorsilva** [comment, marked as answer]
In your pipeline you're using the `docker-image` resource instead of the `registry-image`. Try switching that out and see what results you get then.

```yaml
---
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image  ## change to registry-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world]
```
