### DISCUSSION TITLE
Can't clone HTTPS git repo: "could not read Username for 'https://gitlab.com': No such device or address"

### DISCUSSION THREAD

**Discussion by patmaddox** [concourse/concourse#6894] [Help & Support] [answered]
I am trying to set up a git resource that clones a gitlab repo via HTTPS:

```yml
resources:
  - name: share_my_contacts
    type: git
    source:
      uri: https://gitlab.com/geometerio/resolve/share_my_contacts.git
      branch: main
      username: concourse
      password: ((gitlab-token))
```

I have set up a secret that I believe will map to the `((gitlab-token))` replacement (the pipeline is named `share-my-contacts`):

```
% kubectl describe secret --namespace=concourse-main share-my-contacts                                              
Name:         share-my-contacts
Namespace:    concourse-main
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
gitlab-token:  21 bytes
```

When the worker tries to clone it, it fails with `fatal: could not read Username for 'https://gitlab.com': No such device or address`.

I have cloned that URL on my local machine, and it prompted me for `Username` and `Password`. The credentials work.

The error message suggests to me that it's prompting concourse for username and password, when I would expect concourse to pass it in directly (perhaps by modifying the URL).

I am not sure how to debug this, because the `git` binary doesn't seem to be on the web or worker pods. So I can't try to clone it directly from the worker.

It's possible that I've misconfigured the kube secret, and so concourse is not using any credentials.

How can I clone this HTTPS repo with the provided credentials?
