### DISCUSSION TITLE
Defaults for resources (not resource types)

### DISCUSSION THREAD

**Discussion by mkocus** [concourse/concourse#6924] [Help & Support]
Hello,

Is it possible to set (for example in the docker-compose) defaults for resources?

**Justification:**
We have a lot of sections in pipelines which looks like that:
```
resources:
- name: fetch-develop
  type: git
  icon: bitbucket
  source:
    uri: *REDACTED*
    branch: develop
    private_key: ((ci_private_key))
```

It would be nice to have defaults for the `private_key`, so we wouldn't have to specify that directly - as it is the same between all pipelines.

We currently use defaults for the resource-types, like that:
`CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS: /opt/concourse/defaults.yml`

**Comment by aoldershaw** [comment]
The base resource type defaults should apply to the resource or resource type that immediately uses the base type.

I tried setting my base resource type defaults file to:

```yaml
git:
  private_key: ((ci_private_key))
```

And I set the following pipeline:
```yaml
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/aoldershaw/concourse-experiments.git

jobs:
- name: job
  plan:
  - get: repo
```

Since I don't have the var `((ci_private_key))` defined in a credential manager, I'm seeing checks fail with `resource config creds evaluation: undefined vars: ci_private_key` - but that just means the default is getting applied.

**Reply by mkocus** [reply]
Thanks for your response @aoldershaw!

Yes, indeed it works the way that you have described for the built-in resource types.

Is there a way to pass defaults not only to the embeeded (base) resource types, but to resource types defined in the pipeline?
For example let take a look at the part of the sample pipeline:
```
resource_types:
  - name: bitbucket-build-status
    type: docker-image
    source:
      repository: shyxormz/bitbucket-build-status-resource

resources:
  - name: set-status
    type: bitbucket-build-status
    icon: bitbucket
    source:
      driver: Bitbucket Cloud
      client_id: ((oauth_key))
      client_secret: ((oauth_secret))
      repository: xxx
```

Because we have 30+ pipelines with the `set-status` resource, it would be nice to be able to define for example client_id, client_secret on the high level.

**Reply by aoldershaw** [reply]
Oh I see. Unfortunately, there's no way to set cross-pipeline defaults for a custom resource type. You can set defaults within a single pipeline, e.g.:

```yaml
resource_types:
  - name: bitbucket-build-status
    type: docker-image
    source:
      repository: shyxormz/bitbucket-build-status-resource
    defaults:
      driver: Bitbucket Cloud
      client_id: ((oauth_key))
      client_secret: ((oauth_secret))

resources:
  - name: set-status
    type: bitbucket-build-status
    icon: bitbucket
    source:
      repository: xxx
```

(which would only be of benefit if there were multiple resources of type `bitbucket-build-status` in the pipeline)

This would probably be supported when we get to implement something like [Projects](https://github.com/concourse/rfcs/pull/32), which allow configuring project-level `resource_types`, where a project can aggregate many pipelines
