### DISCUSSION TITLE
Build an image once, and push to multiple ECRs? (job-level input/output?)

### DISCUSSION THREAD

**Discussion by patmaddox** [concourse/concourse#6942] [Help & Support]
I'm converting a CI setup that builds a docker image, and then needs to push it out to multiple ECRs. Here is a working setup for one build-and-push:

```yaml
resources:
  - name: epi-locator-git
    type: git
    source:
      uri: https://gitlab.com/geometerio/resolve/ct_assist.git
      branch: ((branch))
      username: concourse
      password: ((gitlab-token))

  - name: nj-staging-ecr
    type: registry-image
    source:
      repository: ct-assist-staging
      tag: latest
      aws_access_key_id: ((aws-access-key-id-nj-staging))
      aws_secret_access_key: ((aws-secret-access-key-nj-staging))
      aws_region: us-east-1

jobs:
  - name: test
    public: false
    plan:
      - get: epi-locator-git
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: patmaddox/epi-locator-ci
          inputs:
            - name: epi-locator-git
              path: .
          run:
            path: ./ci/test.sh
          params:
            HEX_RATIO_READ_ONLY_KEY: ((hex-ratio-read-only-key))
            HEX_OBAN_UI_KEY: ((hex-oban-ui-key))

  - name: deploy-nj-staging
    public: false
    serial: true
    plan:
      - get: epi-locator-git
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          params:
            BUILD_ARG_HEX_RATIO_READ_ONLY_KEY: ((hex-ratio-read-only-key))
            BUILD_ARG_HEX_OBAN_UI_KEY: ((hex-oban-ui-key))
          inputs:
            - name: epi-locator-git
              path: .
          outputs:
            - name: image
          run:
            path: build
      - put: nj-staging-ecr
        params: {image: image/image.tar}
```

I would like to split up the `deploy-nj-staging` job into separate jobs, because I will need to push this to multiple ECRs for different applications. So what I want is something like:

```yaml
resources:
  - name: epi-locator-git
    # <SNIP>

  - name: nj-staging-ecr
    type: registry-image
    source:
      repository: ct-assist-staging
      tag: latest
      aws_access_key_id: ((aws-access-key-id-nj-staging))
      aws_secret_access_key: ((aws-secret-access-key-nj-staging))
      aws_region: us-east-1

  - name: nj-prod-ecr
    # <SNIP>

jobs:
  - name: test
    # <SNIP>

  - name: build-image
    public: false
    serial: true
    plan:
      - get: epi-locator-git
      - task: build-image
        # <SNIP>
            
  - name: deploy-nj-staging
    plan:
      - put: nj-staging-ecr
        params: {image: image/image.tar}
        
  - name: deploy-nj-prod
    plan:
      - put: nj-prod-ecr
        params: {image: image/image.tar}
```

But I don't know of a way to use an output from the `build-image` job as an input to the `deploy-*` jobs.

## The questions

1. How can I build the image one time, and then push it to multiple ECRs in separate jobs?
2. How can I ensure that I only push images that have passed the test suite? I have `build-image` running in parallel to the tests, so the build doesn't necessarily need the tests to pass, but the push definitely does. Would it do the job if I added:

```yaml
- get: epi-locator-git
  passed: [test, build-image]
```

to each of the deploy plans? Even though I'm only interested in the `image/image.tar` file?

**Comment by chenbh** [comment]
1. You would have to use an intermediate ECR (e.g. `nj-dev-ecr`):
```yaml
resources:
...
  - name: nj-dev-ecr
    ...
jobs:
...
  - name: promote-dev-to-staging
    plan:
      - get: nj-dev-ecr
        passed: [build]
        params: { format: oci }
      - put: nj-staging-ecr
        params: {image: nj-dev-ecr/image.tar}
```

2. Passing the git through would work. Alternatively, you can use the `in_parallel` step to run the test and the build at the same time. If any of them fail, the `in_parallel` step itself fails, which would halt the build before the `put` step is run:
```yaml
jobs:
...
  - name: test-and-build
    plan:
      - get: epi-locator-git
      - in_parallel:
        - task: run-tests
          ...
        - task: build-image
          ...
      - put: nj-staging-ecr # if it reaches here, then the test and the build both passed
        params: {image: image/image.tar}
```
