### DISCUSSION TITLE
Conditionally running (or possibly triggering) jobs and tasks based on git branches

### DISCUSSION THREAD

**Discussion by patmaddox** [concourse/concourse#6946] [Help & Support]
Here's a config to run tests, build a docker image, push to an ECR, and restart an AWS Fargate instance:

```yaml
resources:
  - name: epi-locator-git
    type: git
    source:
      uri: https://gitlab.com/geometerio/resolve/ct_assist.git
      branch: ((branch))

  - name: dev-ecr
    type: registry-image
    source:
      repository: ct-assist-staging

  - name: nj-staging-ecr
    type: registry-image
    source:
      repository: ct-assist-staging

jobs:
  - name: test
    public: false
    plan:
      - get: epi-locator-git
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: patmaddox/epi-locator-ci
          inputs:
            - name: epi-locator-git
              path: .
          run:
            path: ./ci/test.sh

  - name: build-image
    public: false
    plan:
      - get: epi-locator-git
        passed: [test]
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: epi-locator-git
              path: .
          outputs:
            - name: image
          run:
            path: build
      - put: dev-ecr
        params: {image: image/image.tar}

  - name: deploy-nj-staging
    public: false
    serial: true
    plan:
      - get: epi-locator-git
        passed: [build-image]
        params: {format: oci}
      - get: dev-ecr
        passed: [build-image]
        params: {format: oci}
        trigger: true
      - put: nj-staging-ecr
        params: {image: dev-ecr/image.tar}
      - task: restart-fargate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: geometer/docker-aws
              tag: latest
          inputs:
            - name: epi-locator-git
              path: .
          run:
            path: bash
            args:
              - -exc
              - |
                source "bin/remote/_remote.sh"
                set_target_deployment njstaging
                force_update_service
```

There are three scenarios that I would like to set up:

1. Automatically trigger the `build-image` and `deploy-nj-staging` jobs for the `main` branch
2. _Don't_ automatically trigger those jobs for other branches - require manually triggering the jobs
3. Don't even show the deploy jobs for some branches

I am not sure what is the "Concourse way" to set this up.

Here's my best understanding of things today:

- Concourse doesn't have conditional logic, so I can't say something like `trigger: ((branch == "main"))`
- I may be able to achieve scenarios 1 & 2 by using pipeline instance vars: `fly -t local sp -p epi-locator --instance-var=branch=main --instance-var=auto-deploy=true -c ci/pipeline.yml` and `fly -t local sp -p epi-locator --instance-var=branch=other-branch --instance-var=auto-deploy=false -c ci/pipeline.yml`
- I may be able to achieve scenarios 1, 2, and 3 by using separate pipeline files. One auto-triggers, one doesn't auto-trigger, and one doesn't have the build and deploy jobs

Some questions I have:

1. What is the "Concourse way" to achieve this setup?
2. Can I re-use resources and jobs across pipeline configs? e.g. if I have three separate pipeline YAML files for scenarios 1 / 2 / 3, there's going to be lots of duplication - I basically want to override the `trigger` value for two pipelines, and only include the build and deploy steps in two of the pipelines. I know how to re-use tasks, but not jobs or resources.

**Comment by patmaddox** [comment]
Here is my current best effort at this setup:

# YAML files

## `pipeline-test.yml`

```yaml
resources:
  - name: epi-locator-git
    type: git
    source:
      uri: https://gitlab.com/geometerio/resolve/ct_assist.git
      branch: ((branch))
      username: concourse
      password: ((gitlab-token))

jobs:
  - name: test
    public: false
    plan:
      - get: epi-locator-git
        trigger: true
      - task: run-tests
        file: epi-locator-git/ci/task-run-tests.yml
```

## `pipeline-deploy.yml`

```yaml
resources:
  - name: epi-locator-git
    type: git
    source:
      uri: https://gitlab.com/geometerio/resolve/ct_assist.git
      branch: ((branch))
      username: concourse
      password: ((gitlab-token))

  # This is called dev-ecr, but we're using the NY staging ECR as a holding ground
  # for the time being. At some point we'll replace this with another ECR or a GCR
  - name: dev-ecr
    type: registry-image
    source:
      repository: ct-assist-staging
      tag: latest
      aws_access_key_id: ((aws-access-key-id-ny))
      aws_secret_access_key: ((aws-secret-access-key-ny))
      aws_region: us-east-1

  - name: nj-staging-ecr
    type: registry-image
    source:
      repository: ct-assist-staging
      tag: latest
      aws_access_key_id: ((aws-access-key-id-nj-staging))
      aws_secret_access_key: ((aws-secret-access-key-nj-staging))
      aws_region: us-east-1

  - name: ny-staging-ecr
    type: registry-image
    source:
      repository: ct-assist-staging
      tag: latest
      aws_access_key_id: ((aws-access-key-id-ny))
      aws_secret_access_key: ((aws-secret-access-key-ny))
      aws_region: us-east-1

jobs:
  - name: test
    public: false
    plan:
      - get: epi-locator-git
        trigger: true
      - task: run-tests
        file: epi-locator-git/ci/task-run-tests.yml

  - name: build-image
    public: false
    plan:
      - get: epi-locator-git
        passed: [test]
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          params:
            BUILD_ARG_HEX_RATIO_READ_ONLY_KEY: ((hex-ratio-read-only-key))
            BUILD_ARG_HEX_OBAN_UI_KEY: ((hex-oban-ui-key))
          inputs:
            - name: epi-locator-git
              path: .
          outputs:
            - name: image
          run:
            path: build
      - put: dev-ecr
        params: {image: image/image.tar}

  - name: deploy-nj-staging
    public: false
    serial: true
    plan:
      - get: epi-locator-git
        passed: [build-image]
        params: {format: oci}
      - get: dev-ecr
        passed: [build-image]
        params: {format: oci}
        trigger: ((auto-deploy))
      - put: nj-staging-ecr
        params: {image: dev-ecr/image.tar}
      - task: restart-fargate
        file: epi-locator-git/ci/task-deploy.yml
        vars:
          deploy-target: njstaging
        params:
          AWS_ACCESS_KEY_ID: ((aws-access-key-id-nj-staging))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key-nj-staging))

  - name: deploy-ny-staging
    public: false
    serial: true
    plan:
      - get: epi-locator-git
        passed: [build-image]
        params: {format: oci}
      - get: dev-ecr
        passed: [build-image]
        params: {format: oci}
        trigger: ((auto-deploy))
      - put: ny-staging-ecr
        params: {image: dev-ecr/image.tar}
      - task: restart-fargate
        file: epi-locator-git/ci/task-deploy.yml
        vars:
          deploy-target: staging
        params:
          AWS_ACCESS_KEY_ID: ((aws-access-key-id-ny))
          AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key-ny))
```

## `task-run-tests.yml`

```yaml
platform: linux

image_resource:
  type: registry-image
  source:
    repository: patmaddox/epi-locator-ci

inputs:
  - name: epi-locator-git
    path: .

caches:
  - path: deps
  - path: _build
  - path: assets/node_modules

run:
  path: ./ci/test.sh

params:
  HEX_RATIO_READ_ONLY_KEY: ((hex-ratio-read-only-key))
  HEX_OBAN_UI_KEY: ((hex-oban-ui-key))
```

## `task-deploy.yml`

```yaml
platform: linux

image_resource:
  type: registry-image
  source:
    repository: geometer/docker-aws
    tag: latest

inputs:
  - name: epi-locator-git
    path: .

run:
  path: bash
  args:
    - -exc
    - |
      source "bin/remote/_remote.sh"
      set_target_deployment ((deploy-target))
      deployment=((deploy-target))
      unset AWS_PROFILE
      export AWS_DEFAULT_REGION="us-east-1"
      force_update_service
```

# Usage

Auto deploy: `fly -t local sp -p epi-locator --instance-var=branch=main --instance-var=auto-deploy=true -c ci/pipeline-deploy.yml`

Manual deploy: `fly -t local sp -p epi-locator --instance-var=branch=feature-branch-1 --instance-var=auto-deploy=false -c ci/pipeline-deploy.yml`

Tests only: `fly -t local sp -p epi-locator --instance-var=branch=feature-branch-2 -c ci/pipeline-test.yml`

# Concerns

- `pipeline-deploy.yml` and `pipeline-test.yml` have exact duplication between the `epi-locator-git` resource and `test` job
- `deploy-nj-staging` and `deploy-ny-staging` jobs have near-exact duplication - the only difference being the `put` target, `vars.deploy-target`, and `params`.

We have multiple other deploy targets (including prod environments), I am currently working on the simplest config of only two staging environments.

# Objectives

- auto-deploy `main` to staging environments
- manually deploy other branches to staging environments
- manually deploy `main` to prod environments
- NO deploys of other branches to prod environments
- simplest config possible / minimize duplication

# Observations

It seems like it might be preferable to split up the build and deploy sections into their own pipelines. This would reduce the duplication in the NY and NJ deploy jobs, by extracting a single deploy pipeline and parameterizing it. I believe I'd no longer be able to use the `passed` constraint, so I'd probably want to pull the deploy scripts into a separate repo and ensure that the `build` pipeline only pushes images that have passed the tests.

# Questions

- Generally: What is the most Concourse-y way to do this?
- Can I get rid of the exact duplication between the resource and test jobs of `pipeline-test.yml` and `pipeline-deploy.yml` ?
- Can I reduce the duplication between `deploy-nj-staging` and `deploy-ny-staging` ?
- It appears as though Concourse allows abstracting and parameterizing pipelines (`set-pipeline --instance-var=...` or `set_pipeline` step) and tasks (`task.file` & `task.vars`) but does not allow abstracting or parameterizing jobs. Is that correct? If so, is that an intentional design decision that I need to integrate into my thinking, or something that hasn't been brought up before?
