### DISCUSSION TITLE
passing version string to resource in subsequent step?

### DISCUSSION THREAD

**Discussion by x3nb63** [concourse/concourse#6996] [Help & Support] [answered]
What I have is jobs that build a number of container images using docker-image-resource (image-A to image-N). Its about 10 resources / images.

Whenever such a job finishes it will have a new sha256:xxxx hash. Which means I get a set of 10 such hashes.

What I wanna achieve is: tell these 10 hashes to another resource that will instruct our orchestrator to deploy precisely these 10 hashes/images. This resource I have.

But how can I pass these hashes?

current approach is like so:

```
jobs:
  - name: deploy
  - get: image-A
     params:
         skip_download: true
  - get: image-B
     params:
         skip_download: true
   ...
  - get: image-N
     params:
         skip_download: true
  -  task: orchestrate
     config:
        platform: linux
        image-resource:
            type: registry-image
            source: { repository: busybox }
      inputs:
           - ???
       run:
           path: /bin/sh
           args: ["-c", "echo HERE I WOULD LIKE HASHES"]
```

on the WebUI this looks perfect: I see exactly which hashes get deployed... but I dont have hashes.

I am aware of `load_var` and `vars` / `instance_vars` but have no idea how to use that here. Also image building happens in other pipelines, I dont wanna interfere with them.

(and I also dont wanna use docker tags for other reasons regarding our workflow - the objective is to really pin to the hashes)

**Comment by taylorsilva** [comment, marked as answer]
So the questions is: how do I get the sha's for the image?
My answer is another question: Does anything in the pipeline know the sha already? Most likely answer seems to be the registry-image resource for each image.

If I look at the docs for the registry-image, specifically the docs for the in/get step: https://github.com/concourse/registry-image-resource/#in-fetch-an-image
I see that part of the output from that is a `./digest` file which contains the sha of the fetched image.

You have two options now (and maybe more variations of the two):

### 1. Pass all images as inputs to your task
Read out the sha's from your script.
```yaml
jobs:
  - name: deploy
  - get: image-A
     params:
         skip_download: true
  - get: image-B
     params:
         skip_download: true
   ...
  - get: image-N
     params:
         skip_download: true
  -  task: orchestrate
     config:
        platform: linux
        image-resource:
            type: registry-image
            source: { repository: busybox }
        inputs:
          - name: image-A
          - name: image-N
            ...
         run:
             path: /bin/sh
             args: ["-c", "cat image-A/digest && cat image-N/digest..."]
```

### 2. Use `load_var` and vars
and pass them in as params. You could also embed the `((.:var-name))` in the script, but passing in with params is the more portable version.
```yaml
jobs:
  - name: deploy
  - get: image-A
     params:
         skip_download: true
  - get: image-B
     params:
         skip_download: true
   ...
  - get: image-N
     params:
         skip_download: true
  - load_var: image-A-sha
    file: image-A/digest
  - load_var: image-B-sha
    file: image-B/digest
  - load_var: ...
  - task: orchestrate
    params:
      IMAGE_A_SHA: ((.:image-A-sha))
      IMAGE_B_SHA: ((.:image-B-sha))
      ...
    config:
       platform: linux
       image-resource:
           type: registry-image
           source: { repository: busybox }
        run:
            path: /bin/sh
            args: ["-c", "echo ${IMAGE_A_SHA} ${IMAGE_B_SHA}..."]
```
