### DISCUSSION TITLE
Can I reference a resource's variables / metadata? e.g. to create a docker image linked to a PR

### DISCUSSION THREAD

**Discussion by patmaddox** [concourse/concourse#7069] [Help & Support]
I am using [github-pr-resource](https://github.com/telia-oss/github-pr-resource) to build GitHub PRs. When they pass, I would like to build a docker image, and tag it with `pr-#{pr-number}`. Is that possible? I'm not sure what sort of metadata a resource has, and it it's possible to access it. Below is an example config that doesn't work. I just tried `((pull-request.pr))` because the PR resource says in the check step that `pr` corresponds to the pull request number.

```yaml
- name: pull-request
  type: pull-request
  check_every: 1m
  source:
    repository: RatioPBC/epi-contacts
    access_token: ((github-access-token))

- name: pr-ecr
  type: registry-image
  source:
    repository: share-my-contacts-staging
    tag: pr-((pull-request.pr))
    aws_region: us-east-1
    <<: *ny_credentials
```

**Comment by evanchaoli** [comment]
`metadata.json` is generated by `get` step, so it's unavailable when you define a resource. I think you should do something like below:

```yaml

- get: pull-request
- task: build-your-image
- load_var: pr
  file: pull-request/metadata.json
- put: pr-erc
  params:
    version: ((.:pr.pr)) 
```

The key point here is, use `load_var` step to load `metadata.json` into a var, then `put` step can use the var.

**NOTE: this is just some pseudocode, I don't know what content is included in metadata.json, you will need to figure it out on your own.**
