### DISCUSSION TITLE
`cache_mapping` task step parameter

### DISCUSSION THREAD

**Discussion by antonysouthworth-halter** [concourse/concourse#7169] [Ideas]
Some observations:

1. Caching is a useful technique for speeding up all kinds of things (duh).

2. It's desirable for pull-request builds to be as fast as possible, so that developers can iterate as fast as possible (also, kinda "duh").

3. For pull-request builds, it's important that builds for two different pull-requests do not share the same cache (for obvious reasons, I think --- e.g. if there are two open PRs on a project, they should have their own cache).

4. Example task definition that uses caching, assume this is in a Job which runs for pull requests;

```yaml
platform: linux
inputs:
  - name: input
outputs:
  - name: output
caches:
  - name: cache
run:
  path: bash
  args:
    - -euxo
    - pipefail
    - -c
    - |
      # load some artifact from the cache, if present
      if [ -f cache/some-artifact ]
      then
        cp cache/some-artifact input/some-artifact
      fi

      # build the project, assume it uses or builds some-artifact
      make -C input

      # store some artifact in the cache
      cp input/some-artifact cache/some-artifact
```

The problem is that we can't use (4) to implement caching, because each time the task runs it would re-use the same cache, violating the property described in (3).

Very tersely; to achieve (2) by using (4) to implement (1), we would violate (3).

From a certain point of view, you could consider this a "naming collision" between the different runs of the pull-request Job. `task` steps currently provide `input_mapping` and `output_mapping`, which you can use to avoid naming collisions by explicitly mapping `task` `inputs`/`outputs` onto resources in the pipeline.

I think it might be useful to add `cache_mapping` field, which acts in a similar manner, but against the `caches` of a task. The Job definition might look something like this:

```yaml
jobs:
  - name: pull-request
    serial: true
    plan:
      - get: pull-request
        trigger: true
      - load_var: pull-request-id
        file: pull-request/.git/resources/pr
      - task: build
        file: pull-request/ci/tasks/pull-request.yml
        input_mapping:
          input: pull-request
        cache_mapping:
          cache: cache-((.:pull-request-id))
```

(Assume `pull-request/ci/tasks/pull-request.yml` contains the task definition from (4), and `pull-request/.git/resources/pr` contains an ID that is unique to each pull request).

---

Of course, you can actually still do the same trick without a new `cache_mapping` parameter, but it's not as nice:

```yaml
platform: linux
inputs:
  - name: input
outputs:
  - name: output
caches:
  - name: cache-((.:pull-request-id))
run:
  path: bash
  args:
    - -euxo
    - pipefail
    - -c
    - |
      # alias the cache name to keep our code clean
      ln -s cache cache-((.:pull-request-id))

      # ... rest of the code is the same
      # load some artifact from the cache, if present
      if [ -f cache/some-artifact ]
      then
        cp cache/some-artifact input/some-artifact
      fi

      # build the project, assume it uses or builds some-artifact
      make -C input

      # store some artifact in the cache
      cp input/some-artifact cache/some-artifact
```

But I think most people would say, that's kind of an ugly hack, and also there's this "hidden parameter" to the task, which is a `((var))` instead of a `param` or `input`.

I'm sure something could be done with instanced pipelines instead, but the thing I don't like about that is that the *entire* pipeline gets cloned. At least in our case, pull-requests are just a single job in a larger pipeline, so it's a bit messy for e.g. deployment jobs to be cloned into the pipeline-instance. Perhaps what we want for that is like, "instanced jobs" instead of "instanced pipelines".

Curious to hear what people think about a `cache_mapping` key for the `task` Step!
