### DISCUSSION TITLE
Hello World Task fails with 'create resource config: base resource type not found: docker-image'

### DISCUSSION THREAD

**Discussion by olemaiwald** [concourse/concourse#7172] [Help & Support] [answered]
Hello everyone,

I am just getting started with Concourse and was kind of surprised to see the hello-world from https://concoursetutorial.com/basics/task-hello-world/ fail with 

```
create resource config: base resource type not found: docker-image
create resource config: base resource type not found: docker-image
errored
```

on my M1 Mac Mini, Intel MBP as well as my Fedora VM on Windows Laptop.

task.yaml looks like this:

```
---
  platform: linux

  image_resource:
          type: docker-image
          source: {repository: busybox}

  run:
          path: echo
          args: [hello world]
```
          
Executed with command:

`fly -t tutorial execute -c task.yaml`

I am starting Concourse with the steps laid out in the tutorial. 

Docker Version: 20.10.6
Docker-Compose Version: 1.19.1       

When I tried to work around the base resource of docker-image using code from a git repository, the error becomes 

```
create resource config: base resource type not found: git
create resource config: base resource type not found: git
errored
```

Are there any suggestions on how I can enable Concourse started with docker-compose to reach those base resources?
