### DISCUSSION TITLE
set_pipeline with instance variable values from file

### DISCUSSION THREAD

**Discussion by suhlig** [concourse/concourse#7175] [General]
I have an instanced pipeline with a variable `region`. So far, when setting the pipeline, I iterate over an array of regions so that I can supply one region after the other, resulting in three instances of the pipeline:

```bash
for region in ap emea na; do
  fly set-pipeline \
    --pipeline regional-sales \
    --config regional-sales.yml \
    --instance-var region="$region"
done
```

Now I would like to achieve the same with another pipeline, triggering when there is a new region in `regions`:

```yaml
plan:
- get: my-repo
- get: regions
  trigger: true
- set_pipeline: regional-sales
  file: my-repo/ci/pipeline.yml
  instance_vars:
    region: ???
```

Is it possible to read the values of instance variables from a file (e.g. found in the `regions` resource, or in a file produced by an earlier task? 

Assuming the pipeline config above creates three instances of the "regional-sales" pipeline; when a fourth region is added to an "instance variable file", I would hope to see _four_ instances of the pipeline.

**Comment by taylorsilva** [comment]
I think you can use `load_var` to read a file and then use the `((var))` as the value of `region:` in your pipeline: https://concourse-ci.org/jobs.html#load-var-step. This might look like this:

```yaml
plan:
- get: my-repo
- get: regions
  trigger: true
- load_var: region
  file: regions/region
- set_pipeline: regional-sales
  file: my-repo/ci/pipeline.yml
  instance_vars:
    region: ((.:region))
```

The `.:` before `region` means it's a "local" var, scoped to the current build.

**Reply by aoldershaw** [reply]
If I understand correctly, `regions` contains a file that may have multiple regions, and you want to set a pipeline for each of them.

Unfortunately, that workflow currently isn't supported. Eventually, this can be achieved by using the [`across` step](https://github.com/concourse/rfcs/pull/29), where you'd do something like @taylorsilva suggested:

```yaml
plan:
- get: my-repo
- get: regions
  trigger: true
- load_var: regions
  file: regions/regions.yml
- across:
  - var: region
    values: ((.:regions))
  set_pipeline: regional-sales
  file: my-repo/ci/pipeline.yml
  instance_vars:
    region: ((.:region))
```

We have a basic implementation of the `across` step, but it doesn't yet support dynamic values like this.

---

EDIT: technically you can achieve this, but it requires a bit of hackery. Specifically, you could have one job `set_pipeline: self`, passing in the list of regions in `vars.regions`, and have another job that runs after and iterates `across` the `((regions))`. More concretely, it could look something like:

```yaml
jobs:
- name: update-regions
  plan:
  - get: my-repo
  - get: regions
    trigger: true
  - load_var: regions
    file: regions/regions.yml
  - set_pipeline: self
    file: my-repo/ci/current-pipeline.yml
    vars: {regions: ((.:regions))}

- name: set-children-pipelines
  plan:
  - get: my-repo
  - get: regions
    trigger: true
    passed: [update-regions]
  - across:
    - var: region
      values: ((regions)) # since this is interpolated when the current pipeline is set, it's static
    set_pipeline: regional-sales
    file: my-repo/ci/child-pipeline.yml
    instance_vars: {region: ((.:region))}
```

...but obviously, this isn't so nice! Once we add support for the dynamic `across` step, this workflow will be a lot nicer.
