### DISCUSSION TITLE
Mapping _subfolders_ of resource or output to another task's inputs

### DISCUSSION THREAD

**Discussion by tomasgareau** [concourse/concourse#7177] [Help & Support] [answered]
Is there a way to pass a _subfolder_ of a git resource to a task in a Concourse pipeline?

To illustrate, say you had a repository with the following structure...

```bash
monorepo/
├── project_a/
│   └── ci/
│       ├── pipeline.yml
│       ├── run-unit-tests.yml
│       └── build-unit-test-container.yml
└── project_b/
```

...where `project_a` and `project_b` are independent projects.

One job in project A's CI pipeline might be to build a container in which to run unit tests then to run unit tests using that image. I'd love to be able to write `run-unit-tests.yml` and `build-unit-test-container.yml` as if `project_a` was the top-level resource (i.e., as if `monorepo` didn't exist). For example, `build-unit-test-container.yml` would have:

```yaml
# ... task boilerplate

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: project-a-dir

params:
  CONTEXT: project-a-dir

# ... other options
```

instead of:

```yaml
inputs:
  - name: monorepo

params:
  CONTEXT: monorepo/project_a  # <-- need to know where project A is within monorepo
```

I took a crack at setting something like that up, where I'd pass `monorepo/project_a` to the `build-unit-test-container` task from within `pipeline.yml`:

```yaml
resources:
  - name: monorepo
    type: git
    source:
      uri: https://github.com/someuser/monorepo
      branch: main
      paths:
        - project_a/**  # only trigger on changes to project_a

jobs:
  - name: unit-test-project-a
    plan:
      - get: monorepo
        trigger: true
      - task: build-unit-test-container
        file: monorepo/project_a/ci/build-unit-test-container.yml
        input_mapping:
          project-a-dir: monorepo/project_a  # <---- pass this subfolder of the monorepo resource
      # ... run unit tests with the output image
```

but I get the error: `missing inputs: monorepo/project_a`, which I take to understand means Concourse is looking for an artifact with the literal name `monorepo/project_a`, _not_ a subfolder `project_a` within the `monorepo` artifact.

I'm pretty new to Concourse so if the answer is "don't do that bozo, it's better to pass `monorepo` as an input to those tasks because X, Y, Z" I'd love to hear of better patterns for this (although I'd still be curious to see if mapping subfolders to task inputs is possible).
