### DISCUSSION TITLE
Resolving K8s secrets problem

### DISCUSSION THREAD

**Discussion by cincom-nuryupin** [concourse/concourse#7183] [Help & Support]
I'm running pipeline to deploy backend service. Part of it is a routine that includes allowed origins host names into backend deployment configuration which I store in k8s in each frontend app secret. The problem comes when I try to resolve frontend app secrets using full name of the secret when running backend pipelines.

Backend secrets are using format PIPELINE_NAME.backend:
```
apiVersion: v1
kind: Secret
metadata:
  namespace: concourse-ci
  name: be-service-name.backend
type: Opaque
stringData:
  foo: bar
```
Frontend secrets are the same PIPELINE_NAME.frontend:
```
apiVersion: v1
kind: Secret
metadata:
  namespace: concourse-ci
  name: fe-app-name1.frontend
type: Opaque
stringData:
  hostName: myproject
```
Resloving it like this will fail saying that value for fe-app-name#.frontend is not there:
```
params:
  FOO: ((backend.foo))
  ALLOWED_ORIGIN_HOSTNAME_1: ((fe-app-name1.frontend.hostName))
  ALLOWED_ORIGIN_HOSTNAME_2: ((fe-app-name2.frontend.hostName))
  ALLOWED_ORIGIN_HOSTNAME_2: ((fe-app-name3.frontend.hostName))
```

Of course I could create another secret and put all the available origin host names there, but that would result in duplication of same data that is already defined on frontend app secrets and belongs there. Is there a way to make it work the way I showed above?
