### DISCUSSION TITLE
git resource resolving mDNS hostname

### DISCUSSION THREAD

**Discussion by CJLove** [concourse/concourse#7194] [Help & Support] [answered]
I'm only a day or so into working with Concourse, so what I'm seeing could certainly be pilot error.  Running v7.3.2 deployed via systemd on Ubuntu 20.0.4 LTS.

I'm trying to do a pipeline that pulls from a git repo on a local (Gogs) server using `hostname.local` as the hostname.  

The resource definition in the pipeline is:
```
resources:
- name: repo
  type: git
  source:
    uri: http://fir.local:3000/ChrisLove/concourse-example.git  
```
The resulting error I see for the repo in the UI is:
```
selected worker: aspen
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'http://fir.local:3000/ChrisLove/concourse-example.git/': Could not resolve host: fir.local
```

I'm using containerd as the runtime and trying various DNS server settings for the worker that would hopefully support the mDNS lookups and also external lookups (e.g. so images can be pulled from docker.io). Failing getting mDNS to work would the concourse containers be able to fallback to an entry in the Concourse host's `/etc/hosts` file?

**Comment by taylorsilva** [comment, marked as answer]
I don't think `/etc/hosts` is copied from the host to the container, so your solution would not work sadly :(
I'd suggest a workaround but I can't think of anything else currently.

**Reply by CJLove** [reply]
A partial workaround is to use something like [nip.io](https://nip.io) as the name to be resolved.

The resource definition becomes:
```
resources:
- name: repo
  type: git
  source:
    uri: http://fir.local.192.168.1.129.nip.io:3000/ChrisLove/concourse-example.git  
```
Probably better to stand up a local DNS server...
