### DISCUSSION TITLE
Using local image.tar as image for fly execute

### DISCUSSION THREAD

**Discussion by tomasgareau** [concourse/concourse#7196] [Help & Support]
Is there some way to pass an image tarball (output from say, oci-build-task) from local disk to `fly execute`?

In the interest of avoiding the [XY problem](https://en.wikipedia.org/wiki/XY_problem) (i.e., in case there's a better way to do what I'm trying to do), here's the scenario I've got in mind:
 
### Scenario
Take some imaginary Python unit-testing pipeline where we'd build, test, and run coverage on some package for the purpose of validating pull requests.

In the build stage, we'd create a Docker image that contains all the dependencies & testing tools required for the unit testing & coverage tasks -- we have no interest in storing this image long-term, so ideally we wouldn't need to `put` it to some private Docker repository. Luckily, we can use https://github.com/concourse/oci-build-task to create an image that we pass to tasks down the pipe.

```yaml
resource_types:
  - name: pull-request
    type: docker-iamge
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    source:
      repository: some/repo

jobs:
  - name: validate-pull-request
    plan:
      - get: pull-request
        trigger: true
        version: every
        
      - put: pull-request
        params:
          path: pull-request
          status: pending
          
      # use oci-build-task to create `tmp-testing-image`, which will be the image
      # used by tasks below
      - task: build
        file: pull-request/ci/build.yml
        output_mapping:
          image: tmp-testing-image
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
            comment: "Can't even build this package"  # <-- can respond to each task individually
            
      - task: unit-test
        file: pull-request/ci/unit-test.yml
        image: tmp-testing-image         # <-- use image output from `build` task
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
            comment: "Unit tests don't pass"
            
      - task: coverage
        file: pull-request/ci/unit-test.yml
        image: tmp-testing-image         # <----- use image output from `build` task
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
            comment: "Coverage too low"
      # ... rest of job
```

This is great! I have a bunch of individual tasks to help narrow downwhere something is failing, I can temporarily build an image to run all these tests, and I can respond differently to each type of failure.

This sucks to work with though: since the `unit-test` and `coverage` tasks expect to be passed an image from a previous task, I can't figure out a way to run them with `fly execute` to test my pipeline before committing -- instead, I have to make a series of junk CI commits.

### Ideal solution

Is it possible to somehow:
* pass the saved output of `build` to `fly execute` from local disk?
  * e.g., `fly -t target execute -c unit-test.yml --image /path/to/local/image.tar`
* run a whole job or series of tasks through fly execute, hooking together their outputs/inputs?
  * e.g., `fly -t target execute -c build.yml --output_mapping image=test-image -c unit-test.yml --image test-image`

### Workarounds
Alternative workarounds I've thought of:
* use the `build` task to export a Python environment and pass _that_ instead of an image
  * this is a bit of a pain... Python virtualenvs aren't [super conducive to being moved](https://stackoverflow.com/questions/32407365/can-i-move-a-virtualenv) so I'd need to either:
    * create and use the virtualenv from the same absolute path in different tasks (feels a bit fragile)
    * copy `site-packages` & other installation paths instead of a virtual environment (again, feels a bit fragile)
* collapse the three tasks into a single task that builds, unit tests, AND runs coverage, and use three different outputs to get the results of each task

Are there other "best practices" for these kinds of scenarios?
