### DISCUSSION TITLE
Is put keyword in YAML config merging configs or replacing?

### DISCUSSION THREAD

**Discussion by inoyakaigor** [concourse/concourse#7250] [Help & Support] [answered]
In this configuration, will the email be sent to the first _(notifications@…)_ email or both _(notifications@… and frontend@…)_?
```yaml
resources:
  - name: send-an-email
    type: email
    source:
      smtp:
        server: ((smtp_hostname))
        port: ((smtp_port))
        login: ((smtp_username))
        password: ((smtp_password))
      from: test@inoy.dev
      to: [notifications@inoy.dev]

failure-notification: &failure-notification
  put: send-an-email
  params:
    subject: |
      [concourse] task failed
    body: |
      Concourse task blah-blah-blah
    to: [frontend@inoy.dev]
```

**Comment by taylorsilva** [comment, marked as answer]
This depends on what the resource you're using decides to do with all the info. It'll get both the `params` and `source` so it could merge them if it wants to. You should see if the resource author has documented this in their README.

**Reply by inoyakaigor** [reply]
Did I understand correctly that Concourse will merge the "to" fields and the emails will go to both addresses if the mailer (sendmail for example) can handle multiple addresses?

**Reply by taylorsilva** [reply]
Concourse does no merging between any of the fields under `source` and `params`. To Concourse, the contents of those fields are a black box. It passes them to the resource's script as-is, no modification. 

The resource will get a json request that looks like this (from https://concourse-ci.org/implementing-resource-types.html#resource-out):
```json
{
  "params": {
    "branch": "develop",
    "repo": "some-repo"
  },
  "source": {
    "uri": "git@...",
    "private_key": "..."
  }
}
```

It's then up to the resource to decide what to do. I don't know which email resource you're using, I found four from a quick search. You'll need to read the `README.md` in the resource's git repo to learn the behaviour of the email resource you're using. Do you know which email resource you're using? These are the four I found:

- https://github.com/pivotal-cf/email-resource
- https://github.com/mdomke/concourse-email-resource
- https://github.com/hybris/email-resource
- https://github.com/StateFarmIns/email-resource

**Reply by inoyakaigor** [reply]
**For future newbies as me:**
Go to your pipeline.yml into the `resource_types` section and find something like this:
```yaml
resource_types:
  - name: email
    type: docker-image
    source:
      repository: <LINK_TO_REPO>
```

then go to this repo and find the `out` file (or directory) and then just read the code of the resource
