### DISCUSSION TITLE
Cache path under an output is empty in subsquent tasks

### DISCUSSION THREAD

**Discussion by pn-santos** [concourse/concourse#7259] [Help & Support]
Hi, I'm wondering if the scenario below _should_ work, consider the following tasks:
- **Task 1**
```yaml
inputs:
  - name: my-repo

caches:
  - path: my-repo/cache-dir

outputs:
  - name: my-repo
````

- **Task 2**
```yaml
inputs:
  - name: my-repo
````

Currently in **7.3.2** the second task has an empty `my-repo/cache-dir` even though in the first task that dir is populated. 
Is the above _supposed_ to work?

If I remove the `caches` from the first task, then the second one will have the `my-repo/cache-dir` populated. And if I change it slightly, like so.:

- **Task 1**
```yaml
inputs:
  - name: my-repo

caches:
  - path: my-repo/cache-dir

outputs:
  - name: my-repo
  - name: my-cache
    path: my-repo/cache-dir
````

- **Task 2**
```yaml
inputs:
  - name: my-repo
  - name: my-cache
    path: my-repo/cache-dir
````

then `my-repo/cache-dir` is also correctly populated. 

In case it's relevant we are using btrfs as the baggageclaim driver.
