### DISCUSSION TITLE
Wrong version returned from "get" step after a "put"

### DISCUSSION THREAD

**Discussion by laurenty** [concourse/concourse#7279] [Help & Support] [answered]
I have a pipeline with 2 jobs and using a semver resource (version) with the git driver.
The first job will get the version, doing a local bump (minor) and then persist the version with a put step (I verified that the correct version gets committed in the git repo)
The 2nd job will then fire and does a "get" on version, but somehow returns the previous version.

Any ideas? Thanks

```
jobs:
    - name: job1
      plan:
        - get: version
        params: {bump: minor}  #--> bumps 0.2.0 to 0.3.0
        - task: dosomething
          ...
        - put: git-repo
          params:
              repository: git-repo
        - put: version  #--> commits 0.3.0
          params: {file: version/version}

    - name: job2
      plan:
        - get: git-repo-input
          trigger: true
        - get: version #--> return 0.2.0 instead of 0.3.0
           passed: [job1]
```
