### DISCUSSION TITLE
rootfs must not be empty error while trying to run a job

### DISCUSSION THREAD

**Discussion by Maghil** [concourse/concourse#7297] [Help & Support]
my helloworld.yml

```yaml
jobs:
- name: hello-world
  plan:
  - task: hello-world-task
    config:
      platform: linux
      image-resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["hello world"]
```

I created a pipeline using
`fly -t tutorial set-pipeline -p hello-world -c hello-world.yml`

the started the same using
`fly -t tutorial unpause-pipeline -p hello-world`

then triggered my job
`fly -t tutorial trigger-job --job hello-world/helloworld --watch`

and getting this error 
`find or create container on worker f4f3599d0dc3: new container: garden spec to oci spec: rootfs must not be empty`

It seems to be some problem with container image so I tried using "debian" instead of "busybox" but still getting the same error

System:

> OS : Windows
arch : x64
concourse running in docker with image : [image link](https://concourse-ci.org/docker-compose.yml)
pipeline worker : linux
pipeline docker image : [image link](https://hub.docker.com/_/busybox)

Never worked with Docker or Concourse before so don't know what is going wrong, should a custom image be created if yes, can I get a compatible image online
