### DISCUSSION TITLE
Modify Docker image from concourse

### DISCUSSION THREAD

**Discussion by chandu4b4** [concourse/concourse#7304] [Help & Support]
We have a scenario where there is an docker image in Docker hub.
We are trying to add some users to that image in concourse script.

**Steps1**: Add modifications to image

**Step2**: create a container and login to container using added user

**Step3**: Run build

Is there a way to achieve this in course without modifications in image manually

https://concourse-ci.org/jobs.html#schema.step.task-step.image -

Specifies an artifact source containing an image to use for the task. This overrides any task.image_resource configuration present in the task configuration.

This is very useful when part of your pipeline involves building an image, possibly with dependencies pre-baked. You can then propagate that image through the rest of your pipeline, guaranteeing that the correct version (and thus a consistent set of dependencies) is used throughout your pipeline.

```yaml
---
resource_types:
  - name: task1
    type: docker-image
    source:
      repository: laurentverbruggen/concourse-git-semver-tag-resource
  - name: pull-task
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/concourse/git-resource.git
    branch: master
- name: docker-image
  type: registry-image
  source:
    repository: hub.docker.com/r/telosalliance/ubuntu-20.04
jobs:
- name: build
  plan:
    - get: source-code
      trigger: true
    - put: task2
      params: 
        build:  git-resource/scripts/install_git_crypt.sh
- name: task3
  plan:
  - get: task2
    passed: [build]

```

Please suggest options I can use to achieve this
