### DISCUSSION TITLE
Concourse Conjur Integration

### DISCUSSION THREAD

**Discussion by pcf-user** [concourse/concourse#7373] [Help & Support]
Hi,

Concourse Version: 7.0.0
Cluster mode concourse with web/db/worker nodes

Using vault as credential manager and planning to migrate to Conjur.  ( curl -k htttps://conjur/info  comes back fine)

My concourse manifest with conjur params (Removed vault definition)

      conjur:
        authn:
          api_key: 
        login: host/concourse/SOME_NAME/ENV/concourse
        account: My_Account
        path_prefix: "My_PATH"
        url: https://My Conjur Host
      worker_gateway:
        authorized_keys:

A pipeline that used to pull git key to get a repo is now failing.  

Check-Resource Output
---------------------------

resource config creds evaluation: undefined vars: git_private_key
errored

Are my conjur params on concourse manifest OK?

**Comment by pcf-user** [comment]
Is there a manifest for conjur like this?  https://github.com/rahulkj/concourse-vault/blob/master/concourse.yml

**Comment by taylorsilva** [comment]
The values for the bosh release are listed here: https://github.com/concourse/concourse-bosh-release/blob/04be665dcce6e7ac16d5b3468698a6bd6d8cee91/jobs/web/spec#L1508-L1544

Looks like `url` should be `appliance_url` and the auth stuff should be under an `auth` key and path_prefix does not exist for conjur:

```yaml
  conjur:
    auth:
      api_key: 
      login: host/concourse/SOME_NAME/ENV/concourse
    account: My_Account
    appliance_url: https://My Conjur Host
```
