### DISCUSSION TITLE
Call a function to get the name of the variable to fetch?

### DISCUSSION THREAD

**Discussion by TheSecMaven** [concourse/concourse#7433] [General]
Sample pipeline

```
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: env
      params:
        CF_API: (("secret/path"))

```

We are migrating credential managers, and the ```secret/path``` is changing. We would like to write a single function that lets us swap between credential providers by only changing the function (or 1 piece of code), and still work with the different paths. Something like

```
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: env
      params:
        CF_API: ((secretPathConverter("secret/path")))
```

and ```secretPathConverter``` would handle returning 1 string for 1 credential provider, and another for the other. this would let us simplify how we manage our pipeline code. Is this, or something similar, possible?
