### DISCUSSION TITLE
"Put Steps" in official tutorial doesn't push to git. Mistake in tutorial?

### DISCUSSION THREAD

**Discussion by maestrow** [concourse/concourse#7482] [General]
Official tutorial has section "[Put Steps](https://concourse-ci.org/tutorial-resources.html#put-steps)". In this section, its proposed to create a job that:
1. pulls git repository
2. make a commit
3. push to same

Look at final job config in that tutorial (at the end of [Put Steps section](https://concourse-ci.org/tutorial-resources.html#put-steps)) and note that `task: create-commit` doesn't have `outputs`. Config I use is very similar: 

```yaml
resources:
- name: repo
  type: git
  icon: github
  source:
    uri: git@github.com:maestrow/concourse-examples.git
    private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      ...
      -----END OPENSSH PRIVATE KEY-----
    branch: master
jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: create-commit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gitea/gitea # use any image that has the git cli
      inputs:
      - name: repo
      run:
        path: sh
        args:
        - -cx
        # this is just a bash script
        - |
          cd repo
          git config --global user.name conc
          git config --global user.email conc@local
          date > todays-date
          git add ./todays-date
          git commit -m "Update todays date"
  - put: repo
    params:
      repository: repo
 ```

If `task: create-commit` doesn't have `output`, then job doesn't push. Here is my build logs:

Output logs for `task: create-commit`
```
selected worker: concourse
+ cd repo
+ git config --global user.name conc
+ git config --global user.email conc@local
+ date
+ git add ./todays-date
+ git commit -m 'Update todays date'
[detached HEAD 3a60f42] Update todays date
 1 file changed, 1 insertion(+), 1 deletion(-)
```
Logs for `put: repo`:
```
selected worker: concourse
Identity added: /tmp/git-resource-private-key (root@pve)
Everything up-to-date
```

If I add `output` to task that way:
```
  - task: create-commit # renamed task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gitea/gitea # use any image that has the git cli
      inputs:
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args:
        - -cx
        # this is just a bash script
        - |
          cd repo
          git config --global user.name conc
          git config --global user.email conc@local
          date > todays-date
          git add ./todays-date
          git commit -m "Update todays date"
```

then job makes push.

It turns out that there an error in [tutorial](https://concourse-ci.org/tutorial-resources.html#put-steps)? And `task: create-commit` must have an `output`?
