### DISCUSSION TITLE
custom docker image

### DISCUSSION THREAD

**Discussion by jiege3324** [concourse/concourse#7483] [Help & Support]
The configuration is as follows 

```yaml
  - task: get-paas-db-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-registry))/plumber/yq-jq-git-helm-vault
          username: ((docker-registry-username))
          password: ((docker-registry-password))
          tag: latest
      params:
        org_scope: "{{ $root.global.base.crb_orgScope }}" 
        func_scope: "{{ $root.global.base.crb_funcScope }}"
        environment: "{{ $root.global.base.crb_environment }}"
        region: ((region))
        obsbucket: ((bucket))
        ak: ((iam_ak))
        sk: ((iam_sk))
        vault_endpoint: ((vault-endpoint))
        concourse_token: ((plumber-token))
      inputs:
      - name: plumber-source
      - name: conf-rtm-dashboard-db-configs-{{ $envName }}
      outputs:
      - name: serviceData  
      run:
        path: sh
        args:
        - "-c"
        - "/bin/sh ./source/src/main/concourse/03_deploy_templates/Db/task-scripts/SetInitialData.sh"
```
       
A shell script is run in a custom docker image, the script execution has errors but the concourse web page does not report an error, how can concourse also detect the running script and report an error and return it on the page
