### DISCUSSION TITLE
Please shed some light on how artifacts work under the hood?

### DISCUSSION THREAD

**Discussion by maestrow** [concourse/concourse#7484] [Help & Support] [answered]
What happens if I make changes in input artifact (in task, that does't have output)?

The purpose of this question is to reveal in more details about artifacts internal structure.

I've made an example - job with three tasks (see full config below):
1. step1 produce an output `the-artifact`.
2. step2 has input `the-artifact` and make changes into it. Has no outputs.
3. step3 also has input `the-artifact`.

After running this job we can see that changes from step2 were not included in input of step3, despite of all steps using same artifact. 

It's not hard to explain this behavior - its because of step2 doesn't have `output` in its config. But I want to understand what are the artifacts? If these are just mount points, then what internal mechanism prevents propagate changes when we change same artifact as input and there are no output (as step2)?

Below I attach config for described example:

```yaml
jobs:
- name: artifacts-test
  plan:

  - task: step1
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from step1\n" >> the-artifact/message
          cat the-artifact/message

  - task: step2
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from step2\n" >> the-artifact/message
          cat the-artifact/message

  - task: step3
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from step3\n" >> the-artifact/message
          cat the-artifact/message
```

**Comment by taylorsilva** [comment, marked as answer]
Great question! Not sure if you saw this page, maybe it'll help: https://concourse-ci.org/exploring-task-input-and-output-scenarios.html

By default, linux workers using a filesystem driver called overlay: https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html

I'll let those docs explain what overlay is. The juicy bit is this one: https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html?highlight=overlayfs#upper-and-lower

I'll annotate your pipeline to explain what's happening with the artifacts. For non-linux workers concourse does a lot of copying (`cp`) in order to achieve the same result as overlay, which takes up A LOT more disk space.

```yaml
jobs:
- name: artifacts-test
  plan:

  - task: step1
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      # create an empty artifact called a1, which does appear as a mount on the
      # host, and mount it in the container. At the build-level, "the-artifact"
      # now points to a1
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from step1\n" >> the-artifact/message
          cat the-artifact/message

  - task: step2
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      # create a Copy-On-Write (cow) artifact based on a1 and call this new
      # artifact/mount a2. At the build-level, "the-artifact" still points to a1
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from step2\n" >> the-artifact/message
          cat the-artifact/message

  - task: step3
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      # Look up "the-artifact" in scope of the current build, finds "the-artifact" pointing to a1.
      # Create a COW artifact based on a1, call it a3. At the build-level "the-artifact" still points to a1.
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from step3\n" >> the-artifact/message
          cat the-artifact/message
```
