### DISCUSSION TITLE
Across step: how to set_pipeline using file from variable git branch?

### DISCUSSION THREAD

**Discussion by dmsolow** [concourse/concourse#7489] [Help & Support]
I want to automatically configure a new pipeline for each pull request. I want the pipeline yaml to be defined in the source branch of the pull request. I don't see a way to do this currently. If we take this as a starting point:
```
jobs:
- name: set-pr-pipelines
  plan:
  - task: get-prs
     # get list of pull requests
      outputs:
        - name: prs
  - load_var: pull_requests
    file: prs/prs.json
    reveal: true
  - across: 
    - var: pull_request
      values: ((.:pull_requests))    
    set_pipeline: pr-workflow
    file: ???
```

The output `prs` in the `get-prs` task is an array of objects with the following keys: `from_branch`, `from_commit`. These indicate the state of the source branch involved in the pull request.

What I want to do in the `across/set_pipeline` step is:

1. Check out a specific pipeline file (let's say `pr.yml`) at the specific `from_branch/from_commit` 
2. Create a pipeline using that file

How should I proceed, preferably using the standard git resource?

**Comment by taylorsilva** [comment]
You would need to have your task `get-prs` or some other task, fetch the file or entire branch for you. You may be able to take this resource: https://github.com/aoldershaw/github-pr-resource
and have it download the branch/pr files. It can do that for a single PR, so it may not be too much of a stretch to have it do that for multiple prs.

So assuming your output from your task/resource looks like this:
```
prs/prs.json
prs/2837/<git files>
prs/2874/<git files>
prs/2856/<git files>
...
```
Your pipeline could then look like:
```yaml
jobs:
- name: set-pr-pipelines
  plan:
  - task: get-prs
     # get list of pull requests
      outputs:
        - name: prs
  - load_var: pull_requests
    file: prs/prs.json
    reveal: true
  - across: 
    - var: pull_request
      values: ((.:pull_requests))    
    set_pipeline: pr-workflow-((.:pull_request))
    file: prs/((.:pull_request))/ci/pipeline.yml
```

**Reply by dmsolow** [reply]
Unfortunately I'm using bitbucket (on-prem server) not github. I can probably hack something together to do this however.

Is there a reason the branch/commit can't be passed as params to a git resource in a `get` step? I really think that would be a good decision for this kind of thing. Requiring it to be hardcoded is silly.

**Reply by taylorsilva** [reply]
I think the main reason such a feature hasn't been made is that the git resource has been designed to represent a specific branch in a git repo.

That said, I dug into the git-resource README and noticed that `branch` is optional: https://github.com/concourse/git-resource#source-configuration
and if you can get the head ref/sha for each PR I think you can pass that into the `get.version` field. So it might look like this:

```yaml
jobs:
- name: set-pr-pipelines
  plan:
  - task: get-prs
     # get list of pull requests
      outputs:
        - name: prs
  - load_var: pull_requests
    file: prs/prs.json # contains PR number and ref
    reveal: true
  - across: 
    - var: pull_request
      values: ((.:pull_requests))
    do:
      - get: my-repo
        version:
          ref: ((.:pull_request.ref))
      - set_pipeline: pr-workflow-((.:pull_request))
        file: my-repo/ci/pipeline.yml

```
