### DISCUSSION TITLE
How to perform network communication between resources

### DISCUSSION THREAD

**Discussion by tardisx** [concourse/concourse#7491] [Help & Support]
Hi all,

I think there is a good chance I'm "holding this wrong" so I welcome feedback on the right way to approach this.

I'm setting up CI for a web app, and some of the web app tests utilise a database (PostgreSQL).

I thought an appropriate paradigm would be to have two "registry-image" resources, one is my application builder image, and one a PostgreSQL image. My tests can then have a clean slate database to test against.

However I cannot see how to pass the network details from one to the other. How can my builder image find out what the IP address of the PostgreSQL instance is? The only way I could see to possibly do it is to generate an output on the PostgreSQL image to feed into the builder image, maybe a file containing the IP address - but this seems very clunky.

Am I barking up the wrong tree here?

**Comment by taylorsilva** [comment]
You got the right idea here, but maybe it's the details that you're stuck on? If you have some pipelines snippets you can share we may be able to help untangle your problem.

Anecdotally, we do the same kind of integration level tests, bring up a concoruse with a new db, using docker-compose: https://github.com/concourse/concourse/blob/master/docker-compose.yml
and this is the job in the pipeline that does it: https://github.com/concourse/ci/blob/035a76977a3b3340aefd49c3e29b2b88db5cdec8/pipelines/release.yml#L314-L345
like yours, it fetches postgres and a concourse dev image.

Hopefully that helps you :)

**Comment by tardisx** [comment]
Thanks so much for your response!

Ihave used docker-compose elsewhere - I must admit I considered at an "adjacent" solution, not something I could use within concourse. I haven't (currently) looked at it as part of this particular solution.

Looking at your examples I'm not sure I understand the intersection between the pipeline config which fetches the Postgres image:

```
- name: postgres-image
  type: registry-image
  icon: *image-icon
  source: {repository: postgres}
```

And the docker-compose segment which seems to do the same thing:

```
services:
  db:
    image: postgres:${POSTGRES_TAG:-latest}
```

Here is my pipeline configuration. I'm not far from the "hello world" tutorial :-)

```
resources:
- name: repo
  type: git
  source:
    uri: user@myrepo/myapp.git

- name: db
  type: registry-image
  icon: docker
  source:
    repository: library/postgres
    tag: 13

- name: golang-builder
  type: registry-image
  icon: docker
  source:
    repository: mylocalregistry:5000/golang-builder
    tag: latest
    
jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - get: db
    trigger: false
  - get: golang-builder
    trigger: true
  - task: run-tests
    image: golang-builder
    config:
      platform: linux
      inputs:
        - name: repo
      run:
        path: /bin/sh
        args:
          - -c
          - |
            cd repo
            # here I need to know the DB's IP address to run the tests
            tern migrate
            go test -v ./...

```
