### DISCUSSION TITLE
Running a task in an image built in an earlier step without pushing to a repository

### DISCUSSION THREAD

**Discussion by OddBloke** [concourse/concourse#7498] [Help & Support] [answered]
Hey folks,

I'm currently working on a PR pipeline for a project which builds Docker images, and then runs some things in them. We currently only have access to a naive Docker image repository, which doesn't readily allow for deletion: this means that we don't want to push a new image for every single PR, as that will cause our disk usage to increase substantially.

Is there any way for me to build a Docker image (or rootfs, more likely) and have that used as the task image for a later step in the same job? This would allow me to build an ephemeral image, which would then be discarded at the end of the build.

Thanks!

**Comment by taylorsilva** [comment, marked as answer]
Based off this example: https://github.com/concourse/examples/blob/master/pipelines/build-and-push-simple-image.yml

I removed the `put` step and changed it to a `task` that uses the image from the previous step where the image was built.

```yaml
---
resources:
# The repo with our Dockerfile
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/examples.git
    branch: master

# Where we will push the image
- name: simple-image
  type: registry-image
  icon: docker
  source:
    # You need to provide these variables when
    # setting the pipeline
    repository: ((image-repo-name))/simple-image
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-and-push
  plan:
  - get: concourse-examples
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/vito/oci-build-task
          repository: vito/oci-build-task
      inputs:
      - name: concourse-examples
      outputs:
      - name: image
      params:
        CONTEXT: concourse-examples/Dockerfiles/simple
        UNPACK_ROOTFS: "true" #image needs to be exported in rootfs format
      run:
        path: build
  - task: simple-task
    image: image # using the image output built in the previous step
    config:
      platform: linux
      run:
        path: echo
        args: ["Hello world!"]
```
