### DISCUSSION TITLE
Conditional step to kick off job or task

### DISCUSSION THREAD

**Discussion by VenkataMallareddyNBCU** [concourse/concourse#7521] [Help & Support]
I have a use case where the docker container for the task is big due to the resources being used inside it. Due to this it takes quite some to come up and the script initially checks for a boolean condition to proceed with the deployment. It sounds reasonable to have a conditional step before task to check for condition. I tried using on_failure and on_success for true or false conditions but it would've worked if on_failure wouldn't fail the job on success. Are there any alternatives for this?

**Comment by taylorsilva** [comment]
Is it possible to do the boolean check in a task that uses a smaller container image?

Another thing to look it to try speeding up initialization of the task is what baggageclaim driver the worker is using. We recommend using `overlay` as the driver. If your kernel is new enough that it supports overlay's metacopy (check for the existence of `/sys/module/overlay/parameters/metacopy`) then that ensures your `privileged: true` tasks come up fast as well.

**Reply by VenkataMallareddyNBCU** [reply]
@taylorsilva I did try using a task with smaller container image like busy box just to evaluate the boolean condition with `exit 0` for true and `exit 1` for false and then use `on_failure` to run the script when the condition is false but on_failure fails the job even if the script succeeds and that makes the downstream jobs not get triggered. on-failure should have been configured to enable the job to recover from failure. Anyway,  In my next try I used `on_success` because it doesn't fail the job and depends on the exit code of the script. But even that has a loophole because the job still fails when the boolean is false. If I use `try` to make the job success regardless of the output then that's a major issue because the upstream job generates a file for downstream job to use and downstream job shouldn't start if the script in upstream fails. But `try` step takes precedence and makes the job success regardless of the exit code of its sub-tasks.

All this could've been easy if there was simply a `conditional` step like how `across` was implemented as `for` loop or if on_failure takes the exit code of sub task to decide the success of job. So I am basically expecting something like `when` condition of Jenkins.

**Comment by ThibaultDelaune-pro** [comment]
You can maybe try in 2 steps:

1/ execute the script in busybox image. The script write the boolean condition in a bash file (`true` or `false`).
2/ in a `try` step,  launch the bash file previously generated with `on_success` and `on_failure` processing (on the step)

```yaml
- task: define-the-condition
  config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: busybox
    outputs:
      - name: output
    run:
      path: /bin/sh
      args:
        - -exc
        - |
        your_script.sh

- try:
    task: deployment
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: output
      run:
        path: /bin/sh
        args:
          - -exc
          - |
          output/generated_script.sh
    on_failure: 
      do_domething
    on_success:
      do_some_other_thing
```

**Reply by VenkataMallareddyNBCU** [reply]
@ThibaultDelaune-pro Thanks for taking time for looking into this. Wouldn't the try step make the overall build success even if the tasks under it have failed. I think the try step doesn't take the error from its sub-tasks. So during the scenarios when my deployment have failed, the try step will still show the build as success and this will make the pipeline to trigger the next job in the downstream.

**Reply by timota** [reply]
you can simulate limited condition with `across` step. (i now this is not a concourse way, but it works)
```yml
- name: my_job
  plan:
  - get: original-repo
  - get: latest-release
  - task: get-condition
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
        - name: original-repo
        - name: latest-release
      outputs:
        - name: output
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            NEW_VERSION=$(cat original-repo/VERSION)
            LATEST_VERSION=$(cat  latest-release/version)
            if [ $LATEST_VERSION != $NEW_VERSION ]; then 
              echo '["new version detected"]' > output/condition
            else
              echo "[]" > output/condition
            fi
            exit 0

  - load_var: load-condition
    file: output/condition
    format: json

  - across:
    - var: version
      values: ((.:load-condition))
    do: 
    - name: run_task
```
main tasks here are: 
- `get-condition` - check your condition with if/then/else and create valid `json` array, so it can be processed by next `load_var` step
- `load_var` - load output from previous task. it can be: `[] or ['result']`
- `across` - if `load_var` variable contains any entries - run what inside across, otherwise - pass it.

this is not perfect - but it simulate conditional logic, this is what concourse lack of.
