### DISCUSSION TITLE
how to use USB device in task?

### DISCUSSION THREAD

**Discussion by x3nb63** [concourse/concourse#7529] [General]
concourse-worker is running on Kubernetes an I managed to have the USB device available (and working!) in there. The essential parts from K8s yaml is this:

```
apiVersion: apps/v1
kind: StatefulSet
...
     spec:
       containers:
         - name: concourse-worker
...
           securityContext:
             privileged: true
           volumeMounts:
             - mountPath: /dev/bus/usb
               name: usb-devices
...
       volumes:
         - name:  usb-devices
           hostPath:
             path: /dev/bus/usb
```

getting a shell in that `concourse-worker` pod and I can use `/dev/bus/usb/002/006` quite alright, with its tool. Its a character device, like those from usb-serial.

I noted in #5495 and #2353 that its not possible to map `/dev/bus/usb` right into task containers, so I hijack my task container and create it myself:

```
root@ac48ad61-7876-4d4f-4f45-a4fd1e989bdc:~# mknod /dev/bus/usb/002/006 c 189 133
root@ac48ad61-7876-4d4f-4f45-a4fd1e989bdc:~# ls -la /dev/bus/usb/002/006
crw-r--r-- 1 root root 189, 133 Sep  8 15:37 /dev/bus/usb/002/006

```

then my tool appears to find it, but fails to open:

```
00000135 [140492093220800] ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:0529/0620:libudev:0:/dev/bus/usb/002/006
...
00003470 [140492093220800] ccid_usb.c:560:OpenUSBByName() Can't libusb_open(2/6): LIBUSB_ERROR_IO
00000159 [140492093220800] ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00000100 [140492093220800] ccid_usb.c:799:OpenUSBByName() Device not found?
00000008 [140492093220800] ifdhandler.c:150:CreateChannelByNameOrChannel() failed
00000006 [140492093220800] readerfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:0529/0620:libudev:0:/dev/bus/usb/002/006)
...
```

which is probably because:

```
root@ac48ad61-7876-4d4f-4f45-a4fd1e989bdc:~# cat /dev/bus/usb/002/006
cat: /dev/bus/usb/002/006: Operation not permitted

```

_(this command works in the `concourse-worker` container)_

is this `containerd`? Do I need to configure it to grant additional privileges to the task container? Like the `CAP_ADD_*` ones perhaps?

SELinux is off,  that is certain. And as said above: the `concourse-worker` can access the USB device, so I guess its a matter of pushing that ability down one more layer to the task container.
