### DISCUSSION TITLE
Across step not working

### DISCUSSION THREAD

**Discussion by yasin-amadmia-mck** [concourse/concourse#7604] [General]
Dear Users,

I am following this guide for 'multi branch workflow' https://concourse-ci.org/multi-branch-workflows.html.

However, i am getting this error when I set-pipeline

```
error: error unmarshaling JSON: while decoding JSON: malformed across step: json: cannot unmarshal string into Go struct field AcrossStep.across of type []interface {}
```
fly version is `7.2.0`

Any idea ?

**Comment by taylorsilva** [comment]
Appears to be a YAML formatting error. Looks like you're passing in a `string` instead of an `array of maps` for the `across` key.

Your yaml may looking something like this based on the error:
```yaml
- across: ((.:branches))
```
when it should look like this
```yaml
- across:
  - var: branch
    values: ((.:branches))
```

---

Quickly tested all the yaml blocks in the guide and they all checked out fine when I passed them to Concourse. Share your pipeline and we can probably see what's wrong :)

**Reply by yasin-amadmia-mck** [reply]
The pipeline is actually like this
```
- name: set-feature-pipelines
  plan:
  - in_parallel:
    - get: feature-branches
      trigger: true
    - get: branch
  - load_var: branches
    file: feature-branches/branches.json
  - across:
    - var: branch
      values: ((.:branches))
    set_pipeline: dev
    file: branch/pipelines/dev.yml
    instance_vars: {feature: ((.:branch.groups.feature))}
    vars: {branch: ((.:branch.name))}
```
Could it be this though ? https://github.com/concourse/concourse/issues/7387 (our version is `7.2.0`).
