### DISCUSSION TITLE
Multi-Branch flow without the across construct

### DISCUSSION THREAD

**Discussion by yasin-amadmia-mck** [concourse/concourse#7613] [Help & Support]
Dear Community,
I wanted to check if there was an alternative way of achieving 'MultiBranch' workflow in Concourse than what is documented here. 
https://concourse-ci.org/multi-branch-workflows.html
```
jobs:
- name: set-feature-pipelines
  plan:
  - in_parallel:
    - get: feature-branches
      trigger: true
    - get: examples
  - load_var: branches
    file: feature-branches/branches.json
  - across:
    - var: branch
      values: ((.:branches))
    set_pipeline: dev
    file: examples/pipelines/multi-branch/template.yml
    instance_vars: {feature: ((.:branch.groups.feature))}
    vars: {branch: ((.:branch.name))}
```
Essentially, I want to avoid using the `across` as it does not work with `load_var` from file. See this bug https://github.com/concourse/concourse/issues/7387 . 

Currently we can't upgrade from `7.2.0` and hence we stuck on that version.

My use case is very straight-forward:
1. On feature branches `feature/x/` I want to run some tests etc
2. On master branch, i want run the deployment steps.

Thanks.
