### DISCUSSION TITLE
Enable feature flag on local concourse DockerCompose

### DISCUSSION THREAD

**Discussion by yasin-amadmia-mck** [concourse/concourse#7614] [Help & Support]
Dear Community,

I am experimenting with Concourse and hence currently using a local install on concourse via DockerCompose

https://github.com/concourse/concourse-docker/blob/master/docker-compose.yml

I wanted to enable some of the feature flags like
```
step.across and instanced pipelines are both experimental features, and must be enabled with the feature flags CONCOURSE_ENABLE_ACROSS_STEP and CONCOURSE_ENABLE_PIPELINE_INSTANCES, respectively.
```
I wanted some help on how shall I enable this on my local docker-compose install?

Thanks.

**Comment by taylorsilva** [comment]
Add them as environment variables for the `web` service in your docker-compose.

```yaml
  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
```
