### DISCUSSION TITLE
Pipeline generates a blank webui

### DISCUSSION THREAD

**Discussion by Karunamon** [concourse/concourse#7621] [Help & Support] [answered]
I'm using the docker-compose quickstart along with the following pipeline:

```yaml
---
resources:
- name: vgcc-repo
  type: git
  icon: github
  source:
    uri: https://github.com/karunamon/grc.git

- name: mmark
  type: git
  icon: github
  source:
    uri: https://github.com/mmarkdown/mmark.git

- name: golang-1.16alpine
  type: registry-image
  source:
    repository: golang
    tag: 1.16.8-alpine3.14

- name: python-3.8xalpine
  type: registry-image
  source:
    repository: python
    tag: 3.8.12-alpine3.13


jobs:
- name: docbuild
  public: true
  plan:
    - get: vgcc-repo
      trigger: true
    - get: golang-1.16alpine
    - get: python-3.8xalpine
    - get: mmark

    - task: mmark_md-to-xml
      image: golang-1.16alpine
      config:
        platform: linux
        inputs:
          - name: vgcc-repo
          - name: mmark
        outputs:
          - name: xml
        run:
          path: /bin/sh
          args:
            - -c
            - |
              cd mmark && go get && cd ..
              mmark vgcc-repo/grc.md > xml/grc.xml
    - task: xml2rfc
      image: python-3.8xalpine
      config:
        platform: linux
        inputs:
          - name: xml
        outputs:
          - name: out
        run:
          path: /bin/sh
          args:
          - -c
          - |
            apk add --update --no-cache g++ gcc libxslt-dev libxml2-dev
            pip3 install xml2rfc
            xml2rfc --text xml/grc.xml -o out/grc.txt
            xml2rfc --html xml/grc.xml -o out/grc.html
```
(nothing interesting happening with those outputs yet; i'm halfway through a migration from github actions).

Anyways, viewing the web UI of this pipeline shows me.. nothing:

![image](https://user-images.githubusercontent.com/562413/135384774-5c8916e9-6145-43a7-b76c-dc7b1560f7d4.png)

The javascript console is lit up with an error; it's like some facet of the pipeline is generating bogus data:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#node-job-docbuild-input-golang-1.16alpine-unconstrained' is not a valid selector.
    at Ma (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:3:9928)
    at SVGGElement.<anonymous> (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:1:2222)
    at Array._a.select (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:3:10492)
    at GraphNode.width (http://concourse.rgbcast.lan:8080/public/graph.mjs:629:28)
    at SVGTextElement.<anonymous> (http://concourse.rgbcast.lan:8080/public/index.mjs:157:114)
    at SVGTextElement.o (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:1:2522)
    at http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:3:14537
    at Y (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:1:4463)
    at Array._a.each (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:3:14512)
    at Array._a.attr (http://concourse.rgbcast.lan:8080/public/d3.v355.min.js:3:11364)
```

Note that this pipeline otherwise works. It's visible from the "main" webui screen, and clicking the box there takes me to my list of builds as expected.

Any idea what I should be looking for here?
