### DISCUSSION TITLE
Error while running a pipeline

### DISCUSSION THREAD

**Discussion by cristian-vijelie** [concourse/concourse#7656] [Help & Support]
Hello!
I get the following error while running one of my pipelines:
`run check: start process: backend error: Exit status: 500, message: {"Type":"","Message":"task retrieval: no running task found: task 90efaa1b-70a1-47a6-4cc2-5830fe0dbec0 not found: not found","Handle":"","ProcessID":"","Binary":""}`

Any idea what is wrong?

I have another pipeline, that does the same thing, with the same resources, but on a different repository, and it works.

LE: This happens when getting a resource, before running effective jobs

**Comment by taylorsilva** [comment]
That error is coming from containerd, which is the thing that runs containers on the worker.

Which resource are you getting this with? Do you have a simple pipeline you can share?

**Reply by cristian-vijelie** [reply]
`fly lw` fixed the issue.
I'm using the [PR resource](https://github.com/telia-oss/github-pr-resource).

This is one of the pipelines that didn't work.
```
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: packetCloud-tester
  type: pull-request
  check_every: 24h
  source:
    repository: <private repo>
    access_token: <token>
    base_branch: main

jobs:
- name: run-tests-job
  plan:
  - get: packetCloud-tester
    trigger: true
    version: every
    params:
      submodules: true
      integration_tool: rebase
  - put: packetCloud-tester
    params:
      path: packetCloud-tester
      status: pending
      context: run-tests
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
        - name: packetCloud-tester
      run:
        path: /bin/bash
        args:
          - -xce
          - |
            cd packetCloud-tester
            apt-get update > /dev/null
            export DEBIAN_FRONTEND="noninteractive" 
            apt-get install -y git pkg-config sudo net-tools bridge-utils > /dev/null
            ./run_tests.sh
    on_failure:
      put: packetCloud-tester
      params:
        path: packetCloud-tester
        status: failure
        context: run-tests
  - put: packetCloud-tester
    params:
      path: packetCloud-tester
      status: success
      context: run-tests
```
