### DISCUSSION TITLE
across feature

### DISCUSSION THREAD

**Discussion by yasin-amadmia-mck** [concourse/concourse#7702] [Help & Support]
Dear Concourse users,

I am trying to explore the `across` feature to create multiple pipelines from a template.
Essentially, my use-case is that I want to define a JSON file like the below that would contain source of truth of what i would like to deploy. The below tells me that i want to deploy 'PGAdmin' and 'Nginx' from their respective 'helm' chart locations and their respective `values` files.
```
[
{
  "deploy": {
    "PGAdmin": {
      "chart": "stable_helm_repos/pgadmin",
      "values": "values_path_1"
    },
    "NginX": {
      "chart": "stable_helm_repos/nginx",
      "values": "values_path_2"
    }
  }
}
]
```

I feed that file via an `across`  and `load_vars`
```
- name: deploy-pipeline
  plan:
   ...
   ...
  - load_var: services
    file: <repo>/deploy.json (as above)
  - across:
    - var: service
      values: ((.:services))
    set_pipeline: deployment
    file: pipeline.yml
    instance_vars: {service: ((.:service.deploy))}

```

What I am after is that the pipeline *deployment* should create separate jobs per service, so 'PGAdmin' and 'NginX' in my case, but essentially any number as per my JSON file.

The actual *deployment* pipeline would be this https://github.com/Typositoire/concourse-helm3-resource. I want separate JOBs per service (ex: PGadmin, Nginx etc) and pass the *chart* and *values* for each of the service from the JSON source.
```
jobs:
  # ...
  plan:
  - put: myapp-helm
    params:
      chart: source-repo/chart-0.0.1.tgz
      values: source-repo/values.yaml
```

**Comment by taylorsilva** [comment]
Don't think I fully grokked your problem but _I think_ you'll want to use a yaml templating tool. I say that since it sounds like you expect `set_pipeline` to figure out how many jobs your pipeline should have which is out of scope for that step.

Your across step could look something like this to include the templating tool.

```yaml
- name: deploy-pipeline
  plan:
   ...
   ...
  - load_var: services
    file: <repo>/deploy.json (as above)
  - across:
    - var: service
      values: ((.:services))
    do:
      - task: render-pipeline-template  # generates output "rendered" with a "pipeline.yml" file
        ...<task config here>...
      - set_pipeline: deployment
        file: rendered/pipeline.yml
        instance_vars: {service: ((.:service.deploy))}
```
