### DISCUSSION TITLE
6.7.6 across step issue

### DISCUSSION THREAD

**Discussion by maxknee** [concourse/concourse#7735] [Help & Support] [answered]
If I use this example:

```yaml
resources:
- name: ci
  type: git
  source:
    uri: https://github.com/concourse/examples.git

jobs:
- name: job
  plan:
  - get: ci
  - across:
    - var: pipeline
      values: ["hello-world", "time-triggered"]
    set_pipeline: ((.:pipeline))
    file: ci/pipelines/((.:pipeline)).yml
```

the pipeline name is `((.:pipeline))` is that a known bug?
