### DISCUSSION TITLE
Enable custom RBAC on BOSH Concourse

### DISCUSSION THREAD

**Discussion by richo6030** [concourse/concourse#7779] [Help & Support] [answered]
Hi all,

I'm trying to enable a configured **custom RBAC on a bosh Concourse deployment**, but I'm seeing the following error in the web VM:

```
error: invalid argument for flag `--config-rbac' (expected flag.File): stat member:/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_member,owner:/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_owner: no such file or directory
```

I can see that under
/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_member and /var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_owner 

The env's are there and configured as expected, yet the Web VM is not able to start because of the above error.

This is my **operations.yml** used for the configuration:

```
- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/config_rbac?
  value: ((rbac))
```

This is my **rbac.yaml** file  _(I also tried with .yml extension, the result was the same)_ , which I have configured (_tested on docker-compose Concourse and works fine_):
```
---
member:
- ListContainers
owner:
- ExposePipeline
- RegisterWorker
- LandWorker
- RetireWorker
- PruneWorker
- HeartbeatWorker
- DeleteWorker
- ReportWorkerContainers
- ReportWorkerVolumes
- ListWorkers
- ListVolumes
```

Here is the result in the **bosh manifest** file from all of the above:
```
instance_groups:
  instances: 2
  jobs:
  - name: web
    properties:
      config_rbac:
        member:
        - ListContainers
        owner:
        - ExposePipeline
        - RegisterWorker
        - LandWorker
        - RetireWorker
        - PruneWorker
        - HeartbeatWorker
        - DeleteWorker
        - ReportWorkerContainers
        - ReportWorkerVolumes
        - ListWorkers
        - ListVolumes
```

Also in the bpm.yml the configuration seems fine as well:

```
CONCOURSE_CONFIG_RBAC: "member:/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_member,owner:/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_owner"
```

**Could someone, please help me understand what I'm doing wrong here? Or maybe if this is a new issue?**

Thanks!

**UPDATE:** I can see that some changes were made with https://github.com/concourse/concourse/pull/5415, but I' not sure if they have been adjusted to the bosh deployment of Concourse

**Comment by xtremerui** [comment]
Hi, what version of concoure are you using?

**Comment by richo6030** [comment]
Hi @xtremerui ,

I'm using Concourse 6.5.1

**Comment by xtremerui** [comment, marked as answer]
Your value in operations file is not a yml content, the working one is:

```
instance_groups:
  instances: 2
  jobs:
  - name: web
    properties:
      config_rbac: |     <------------
        member:
        - ListContainers
        owner:
        - ExposePipeline
        - RegisterWorker
        - LandWorker
        - RetireWorker
        - PruneWorker
        - HeartbeatWorker
        - DeleteWorker
        - ReportWorkerContainers
        - ReportWorkerVolumes
        - ListWorkers
        - ListVolumes
```
notice the `|` this tells bosh to write following config to a file; if not, bosh will treat the config as arrays and thus cauisng those /var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_member /var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC_owner

you should only see `/var/vcap/jobs/web/config/env/CONCOURSE_CONFIG_RBAC` as a valid path
