### DISCUSSION TITLE
Pipeline interpolation with across

### DISCUSSION THREAD

**Discussion by yasin-amadmia-mck** [concourse/concourse#7789] [Help & Support]
Dear Team,
I am using *across step* and *load_var* as below:
```
 - load_var: services
    file: file.json
 - across:
    - var: service
      values: ((.:services))
    set_pipeline: test-pipeline
    file: pipeline-file.yml
    instance_vars: {service: ((.:service.name))}
    vars: {chart: ((.:service.chart)), value-file: ((.:service.value-file)), env: "dev", namespace: ((.:service.namespace)), chart-version: ((.:service.chart-version)), secret-values: ((.:service.secret-values))}
```
My *file.json* is as below:
```
[
  {
    "name": "postgresql",
    "chart": "stable/postgresql",
    "chart-version": "8.6.4",
    "value-file": "postgresql/values.yml",
    "namespace": "default",
    "secret-values": [
      {
      "key": "postgresqlUsername",
      "value": "((pg.user))"
      }
    ]
  }
]
```
The *pipeline-file.yml* is:
```
jobs:
- name: ((service))
  plan:
.   ...
  - put: helm-deploy-((service))
    params:
      chart: ((chart))
      version: ((chart-version))
      values: ((value-file))
      release: ((service))
      namespace: ((namespace))
```
The above works, however, i want the pipeline to come out as below, see the `override_values`:
```
params:
      chart: stable/postgresql
      values: postgresql/values.yml
      version: 8.6.4
      release: postgresql
      namespace: default
      override_values:
      - key: postgresqlUsername
         value: ((pg.user))
```
I want the `override_values` to be populated from the `secret-values` of `file.json`. It may be one or more key/value pairs. 
Any idea how I can achieve this ?

Thanks.
