### DISCUSSION TITLE
Are there any workarounds for dynamic version pinning?

### DISCUSSION THREAD

**Discussion by nikicc** [concourse/concourse#7861] [Help & Support]
I've read about "dynamic resource pinning" mentioned in the open issue about [Dynamic build plan generation](https://github.com/concourse/concourse/issues/684) and I'm wondering if there are any known workarounds for that?

Precisely, my issue is this. I have two resources, first is a `git` resource where the logic of my application lives, second is an `registry-image` resource where end-to-end tests for my app live. In Concourse I'd first deploy the application with a given version to my server and then I'd run the end-to-end tests against the app. I would like the version of the end-to-end test that are run to match the version of the `git` resource. So if I'm deploying version `v0.0.42` I'd like to run the same version `v0.0.42` of end-to-end tests even if `v0.0.42` is not the latest version in the `registry-image` resource.

I was able to pin the `registry-image` resource version to a static number, but not to a dynamic one.

Here is my attempt using [load_var](https://concourse-ci.org/load-var-step.html):
```
resources:
  - name: code
    type: git
    icon: github
    source:
      uri: <uri>
      branch: master
      fetch_tags: true
      tag_regex: 'v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'
  - name: e2e-tests
    type: registry-image
    icon: docker
    source:
      repository: <repo>
      variant: e2e
jobs:
  - name: job1
    serial: true
    plan:
      - get: code
        trigger: true
      - load_var: code-version
        file: code/.git/ref
        format: raw
        reveal: true
      - task: print-var
        params:
          VAR: ((.:code-version))
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
              tag: latest
          run:
            path: /bin/ash
            args:
              - "-e"
              - "-c"
              - |
                echo "Code version is $VAR"
  - name: job2
    serial: true
    plan:
      - get: code
        trigger: true
        passed: [ job1 ]
      - get: e2e-tests
        trigger: false
        # dynamic version does NOT work
        version: {tag: ((.:code-version))-vehicle-profiles-api-e2e}
        # static version does work
        # version: {tag: v0.0.42-e2e}
```
