### DISCUSSION TITLE
How webhook URL makes vars work

### DISCUSSION THREAD

**Discussion by bobfw** [concourse/concourse#7894] [Help & Support]
I read the tutorial on the official website and need to dynamically change the variable through webhook, but it cannot take effect

https://concourse-ci.org/resources.html#schema.resource.webhook_token

my yml
```yml
var_sources:
- name: dumm
  type: dummy
  config:
    vars:
      simple: hello!

resources:
- name: every-30s
  type: time
  icon: clock-outline
  webhook_token: a123
  check_every: never
  source:
    interval: 10s

jobs:
- name: triggered-first
  public: true
  plan:
    - get: every-30s
      trigger: true
    - task: simple-task
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: alpine }
        params:
          APP_NAME: ((dumm:simple))
        run:
          path: sh
          args:
            - -exc    
            - env
```
my url
/api/v1/teams/main/pipelines/test/resources/every-30s/check/webhook?webhook_token=a123&vars.dumm:simple="1234"

What is the correct way to write APP_NAME dynamically through webhook?
