### DISCUSSION TITLE
load_var - use array in interpolation

### DISCUSSION THREAD

**Discussion by Berber31** [concourse/concourse#7931] [Help & Support]
We wants to load a yam file in a load_var and use an array value

my-yaml-file.yaml file:
```yaml
ingress:
  hosts:
    - host: my-fqdn.site.org
```

load_var example:
```yaml
- load_var: conf-ti-modele
  format: yaml
  file: input/my-yaml-file.yaml
  reveal: true
```

usage:
```yaml
- task: execute-les-ti
  file: repo-modele-docker-sldng-quarkus-ci/ci/tasks/execute-ti.yaml
  input_mapping:
    source: repo-modele-docker-sldng-quarkus
  params:
    modele_url: http://((.:conf-ti-modele.ingress.hosts[0].host))
```

by this way doesn't work.

Any idea ?
