### DISCUSSION TITLE
Trying to debug a docker in docker setup

### DISCUSSION THREAD

**Discussion by dannystaple** [concourse/concourse#7953] [Help & Support]
I am using the quick start based docker compose, with the latest image.
I am using a docker-in-docker scenario, and seeing errors.
In my task config:
```
      - task: lint
        # image: concourse-dcind-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: karlkfi/concourse-dcind
          inputs:
            - name: repo
          run:
            path: entrypoint.sh
            args:
              - bash
              - -ceux
              - |
                cd repo
                bin/docker-thing
```

Docker thing immediately performs a docker run. It's been used on the desktop. This fails in the entrypoint.sh.
 made an instrumented version of entrypoint to pinpoint the failure - adding set -x.  If fails where it attempts to find cgroup stuff (a bit lower level than I am with docker):
```
grouping="$(cat /proc/self/cgroup | cut -d: -f2 | grep "\\<${sys}\\>")"
```
A pipe fails, right where the grep is - since the group field has an empty string: `0::/d9435fbf-a6f5-4215-7b1a-cc7b8ba6be3c`

If I add `|| true` into the pipe, in theory, the next line should handle it being empty. However, it then fails with:
```
+ mount -n -t cgroup -o cpuset cgroup /sys/fs/cgroup/cpuset
mount: /sys/fs/cgroup/cpuset: permission denied.
```

When starting up the compose set I do see the following (which may be related):
```
concourse_1     | time="2022-01-12T15:44:24.101404800Z" level=error msg="failed to enable controllers ([cpuset cpu io memory hugetlb pids rdma])" error="failed to write subtree controllers [cpuset cpu io memory hugetlb pids rdma] to \"/sys/fs/cgroup/garden/cgroup.subtree_control\": write /sys/fs/cgroup/garden/cgroup.subtree_control: no such file or directory"
```

Concourse version: `version: v7.6.0`.
Running in docker desktop version Docker Desktop 4.3.2 (72729) on MacOS 11.6.2 (20G314).

Anyone got any ideas on how I resolve this?
