### DISCUSSION TITLE
Parallel across..do step - is it possible?

### DISCUSSION THREAD

**Discussion by mbertrand** [concourse/concourse#8003] [Help & Support] [answered]
I have been experimenting with the across step modifier (https://concourse-ci.org/across-step.html), which will "run a step multiple times with different combinations of variable values.".  I've got a sample pipeline working with across, but the do step is run serially per value.  Is there any way to run the step multiple times in parallel?  I tried inserting `in_parallel` at various points in the pipeline definition but didn't have any luck.

```
  - across:
    - var: repo_val
      values: ["val1", "val2", "val3"]
    do:  
    - task: get-repo
      ...etc
```

**Comment by mbertrand** [comment, marked as answer]
Got an answer on the discord channel (thanks Taylor): use `max_in_flight`:

```
  - across:
    - var: repo_val
      values: ["val1", "val2", "val3"]
      max_in_flight: 3
    do:  
    - task: get-repo
      ...etc
```
