### DISCUSSION TITLE
Add a resource type into a worker?

### DISCUSSION THREAD

**Discussion by luis-n4489** [concourse/concourse#8038] [Help & Support]
Searched around the discussions + docs but could not find anything regarding this subject. Can i add a resource type into a worker? Is it possible? Why am i trying to add a resource type into a worker? Since we are using assumed role for ECR - I am using a custom resource that I can reach on dockerhub and then push images to ecr by assuming the aws role. but now its come time to bring all this internally. But the chicken before the egg situation has popped up. I cant assume a role to get the image to be able to assume the role! lol

thanks for the help

**Comment by luis-n4489** [comment]
Or am I 100% incorrect on this and this is the correct doc!? https://concourse-ci.org/concourse-worker.html#worker-resource-types , 😞

**Reply by taylorsilva** [reply]
You found it! This heading specifically https://concourse-ci.org/concourse-worker.html#installing-or-upgrading-bundled-resource-types

**Comment by luis-n4489** [comment]
Went through it and found that i would get this error when the resource tried to check, 
`Error loading shared library libgit2.so.1.1: No such file or directory (needed by /opt/resource/check)
Error relocating /opt/resource/check: git_remote_create_with_opts: symbol not found
Error relocating /opt/resource/check: git_odb_open_wstream: symbol not found
Error relocating /opt/resource/check: git_odb_object_data: symbol not found
`

I added the resource type just fine on the worker and works when pulling images from ecr. 

When i add the concourse-bitbucket-pr to ecr and the resource-type i added checks it, i get the above error.

example 

```
- name: bitbucket-pr
  type: registry-image-ecr <--- the resource-type i added
  source:
    repository: concourse-bitbucket-pr
    tag: REDACTED
    aws_region: REDACTED
    aws_role_arn: arn:aws:iam::REDACTED:role/((concourse_worker)) 
```
