### DISCUSSION TITLE
Build an oci Image not unpacking resulting in "file not found"

### DISCUSSION THREAD

**Discussion by robertsonic** [concourse/concourse#8073] [Help & Support]
Hi, I've followed the guide: https://concourse-ci.org/building-an-image-and-using-it-in-a-task.html

And using the example I get the container built and it runs. If I try and do the same using a different Dockerfile I get "file not found" on the next task step...

**pipeline.yml**

```
jobs:
- name: build-and-run
  plan:
  - get: gitcontents
    trigger: false
  - get: gitstack
    trigger: true
  - get: gitawscdk-((AWS_CDK))
    trigger: false


  - task: build-aws-cdk-((AWS_CDK))
    file: gitcontents/concourse/tasks/buildcdk.yml 
    privileged: true
    vars:
      AWS_CDK: gitawscdk-((AWS_CDK))
      BRANCH: gitcontents

  - task: install-aws-cdk
    file: gitcontents/concourse/tasks/installawscdk.yml
    image: zzpzpzpz
    vars:
      BRANCH: gitcontents
      STACK: gitstack
```

**buildcdk.yml**

```
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: concourse/oci-build-task

inputs:
  - name: ((AWS_CDK))
  - name: ((BRANCH))

outputs:
  - name: zzpzpzpz

params:
  CONTEXT: ((AWS_CDK))
  UNPACK_ROOTFS: true #add this param
  DOCKERFILE: ((BRANCH))/concourse/images/aws-cdk-Dockerfile
  BUILD_ARG_CDK_PATH: ((AWS_CDK))

run:
  path: build
```

Here's the result:

![image](https://user-images.githubusercontent.com/23071053/153852872-669481ab-b0b8-46bb-b21c-1edf69f570ea.png)

I Don't understand what the issue is. Can anyone provide some insight?
