### DISCUSSION TITLE
Json Schema

### DISCUSSION THREAD

**Discussion by brumhard** [concourse/concourse#8084] [Ideas]
Hi there,
I did some research already but only found issues that are from 2018 so I just thought I might ask.

Is there an official JSON schema for concourse pipeline definitions? There are already a few projects maintaining their own schema like:
- The code for [the vscode plugin](https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-concourse) uses a schema if I understand correctly which is defined in Java
- The [jetbrains plugin](https://github.com/cedricziel/idea-concourse) also defines its own schema

There's probably even more.
Are there any plans to provide an official JSON schema anytime or is there already something I have missed until now?
I think that's something the whole ecosystem could benefit from.

**Comment by brumhard** [comment]
Just found #6780 which is probably related.
I don't think that is possible tho since the definition of the tasks is pretty complex in the Go code and would need to be provided as a `oneOf` in JSON schema.

**Comment by andy-paine** [comment]
@cappyzawa kindly keeps this up to date based on the definition from Concourse's Go code 🙂  https://github.com/cappyzawa/concourse-pipeline-jsonschema

**Reply by brumhard** [reply]
Nice, thanks for the hint 🙂 I think that is still lagging the full step definition with `put`, `get`, `in_parallel` etc. but it's definitely something nice to start with.
My current version which also doesn't include everything currently is this one https://github.com/brumhard/pulumi-concourse/blob/main/provider/cmd/pulumi-resource-concourse/schema.json (it's not only json schema but also includes some pulumi stuff)

**Comment by vlfig-iov42** [comment]
You may also be interested in https://github.com/coralogix/dhall-concourse.

**Comment by cynicaljoy** [comment]
Looks like if a schema was published to https://www.schemastore.org/json/ it would get picked up by most editors

**Comment by spion** [comment]
I have some WIP on autogenerating the schema from the docs here https://github.com/spion/concourse-jsonschema-generator

The types should be reasonably decent at this point. The descriptions are generally okay but the lit-to-markdown conversion may need some more work to make it cleaner.

**Reply by spion** [reply]
Just pushed out the latest version of this schema, which ensures the steps union works properly and still doesn't allow additional properties.

The types should now fully and correctly cover any valid pipeline, except for one small exception that I'd like to ask about. 

In the large concourse example pipeline, there is a bump_versions step:
```yaml
  - task: bump-versions
    file: infrastructure/tasks/patch-yaml.yml
    input_mapping: {repo: infrastructure}
    output_mapping: {repo-bumped: infrastructure-bumped}
    params:
      FILE: terraform/environments/production/variables.yml
      PATCH:
        concourse_web_image_repo: ((.:concourse_image_repo))
        concourse_web_image_digest: ((.:concourse_image_digest))
      COMMIT: bump production web to concourse dev
```
https://github.com/concourse/ci/blob/bd63bed5d96acb771f7fa72bf325da52c00fe9cb/pipelines/concourse.yml#L745-L754

According to the docs, task params should be a dictionary of environment variable to a (string) value. Could someone explain how an object value works here? Does it get stringified?
