### DISCUSSION TITLE
How to substitute|remove unique_version_history:true in  resource  type

### DISCUSSION THREAD

**Discussion by jah-jh** [concourse/concourse#8090] [Help & Support]
Hi, 

We have updated from 6.7.1 to 7.6.0 and accidentally got that one of the pipelines has  `unique_version_history: true`  in resource type

Part of config: 
```
resource_types:
  - name: git-prs
    type: registry-image
    unique_version_history: true
    source:
      repository: <some_image>
      tag: latest

  - name: github-status
    type: registry-image
    unique_version_history: true
    source:
      repository: <some_repo>
      tag: latest
      username: ((username))
      password: ((password))
```

I am not sure for what reason `unique_version_history: true` was added so have a next question: 
Can `unique_version_history` be safely removed without any impact?  Or it should be changes to other option?

Thanks in advance.
