### DISCUSSION TITLE
how to use single-repo with multi pipelines

### DISCUSSION THREAD

**Discussion by Srija-ravi** [concourse/concourse#8187] [Help & Support]
I have a repo with three files , I written a playbook like whenever the repo has new change (Even one file has been changes )this pipeline will be triggered . I need only the particular file which has been changed should be triggered not entire files in the Repo.

<img width="849" alt="Screenshot 2022-03-23 at 11 03 03 AM" src="https://user-images.githubusercontent.com/74290219/159630744-449768d7-f85c-4bf9-881e-4cd45f7af09a.png">

**Comment by taylorsilva** [comment]
The [git resource](https://github.com/concourse/git-resource/) takes a field called `paths` where you can list which files should cause the resource to trigger.

Quick example of where you'd configure that:

```yaml
resources:
- name: my-repo
  type: git
  source:
    path:
    - dock.yml
    - hello.sh
```
