### DISCUSSION TITLE
Resource caching causing issues

### DISCUSSION THREAD

**Discussion by luis-n4489** [concourse/concourse#8315] [General]
Hey team! So I am not sure how to avoid this but i have 2 pipelines which interact between each other using pool-resource. 

On pipeline A i have it setting the environment lock
(maybe I am not doing it in the best way BUT here is a sample of the code)
I am using load_var to see if the previous job was for dev or for qa. this works just fine and IF it finds the var then do deploy QA or DEV in this case. It puts the Lock correctly. for some reason i cannot use 1 resource and 1 pool for 2 locks. shouldnt I be able to? any case, once the lock is claimed it triggers the other pipeline to start. 
```
  - try:
      do:
      - load_var: dev
        file: destination/dev.
        on_success:
          try: 
            do:  
            - put: publish-dev
              params: 
                image: image/image.tar
                version: ((.:version))
            - put: dev
              resource: deploy-dev
              params:
                claim: dev
          - task: trigger-deploy
            image: ((docker_build.name))
            file: trigger-url.yaml
            params:
                TF_TRIGGER_URL: URL to other pipeline resource
            - put: pull-request
              params: #@ pr_ci_state("success")

  - try:
      do:
      - load_var: qa
        file: destination/qa
        on_success:
          try:
            do:  
            - put: publish-qa
              params: 
                image: image/image.tar
                version: ((.:version))
            - put: qa
              resource: deploy-qa
              params:
                claim: qa
            - task: trigger-deploy
              image: ((docker_build.name))
              file: trigger-url.yaml
              params:
                TF_TRIGGER_URL: URL to other pipeline resource
```

the issue is in pipeline B, when it goes to GET the 2 pool resources QA and DEV, it has a previous cached result. Which then in turn it does NOT see the claimed lock anymore.  is there any way to avoid this? for NOW i am just getting the entire branch for that pool and seeing which folder the lock is in. but i would like to really use this properly. thanks!

```
INFO: found existing resource cache
```
