### DISCUSSION TITLE
What's the put step puts?

### DISCUSSION THREAD

**Discussion by onlookor** [concourse/concourse#8331] [Help & Support] [answered]
All examples about put step in docs are putting something got in get steps. Is there any example putting something from a task step's outputs?
Or I misunderstand the put step? I suppose the put step would put anything from the working directory, as if the get step places what it gets into the working directory.  
Consider this:
Say I get a piece of source code from a resource, compile it in a "build" task. This task yields binaries in an output "dist", a subdirectory of working directory.
Now then, I want to put the binaries into a resource, such as, rclone, should I explicitly use the output name "dist" in rclone params?

**Comment by tomasgareau** [comment, marked as answer]
> I suppose the put step would put anything from the working directory, as if the get step places what it gets into the working directory.

You got it! Concourse inputs and outputs are just directories. A `get` step is some resource that fetches something from an external "source-of-truth" and sticks it in a directory that other tasks or `put` steps can use. The Concourse guide here is pretty good: https://blog.concourse-ci.org/introduction-to-task-inputs-and-outputs/

Quick example:

```yaml
resource_types: 
  - name: mock-resource
    type: registry-image
    source:
      repository: concourse/mock-resource
      tag: latest

resources:
  - name: mock
    type: mock-resource

jobs:
  - name: output-file
    plan:
      - task: make-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          outputs:
            - name: my-output-dir
          run:
            path: sh
            args:
              - -c
              - |
                echo "testing" > my-output-dir/result.txt
      - put: mock
        params:
          file: my-output-dir/result.txt
```

The pipeline above has:
* a `make-file` task that creates a file called "result.txt" in a directory called `my-output-dir`
* a `put` step that passes that result.txt as a parameter to a mock resource

Let's say I saved that to a file called "example.yml".

**Create and unpause the pipeline**
```
fly -t my-team sp -p example -c example.yml
fly -t my-team up -p example
```

**Trigger a build**
```
fly -t my-team tj -j example/output-file
```

**Intercept the build so we can ssh into the container**
```
fly -t my-team i -j example/output-file
```

> This can take a couple tries... I find the `intercept` command can be a bit finicky/timing sensitive.

If you get the timing right and call it right after the `put` step completes, you should have the option to intercept the `put` container:

```console
foo@bar: $ fly -t my-team i -j example/output-file
1: build #2, step: image, type: check, expires in: 
2: build #2, step: image, type: get
3: build #2, step: make-file, type: task
4: build #2, step: mock, type: put
5: build #2, step: mock-resource, type: check, expires in: 
choose a container: 4
bash-5.1# ls
my-output-dir
bash-5.1# ls my-output-dir/
result.txt
bash-5.1# ls /opt/resource/
check  in     out
bash-5.1# exit
```

And we can see that `my-output-dir` is a directory in this container (and it contains the results of our task). For your `rclone` resource, you would likewise refer to `my-output-dir` in its parameters:

```yml
  - put: my-rclone-resource
    params:
      source: my-output-dir
      destination: ...
```
