### DISCUSSION TITLE
Concourse task to run script can't find the linux command sudo

### DISCUSSION THREAD

**Discussion by martijnvandenboom** [concourse/concourse#8434] [Help & Support]
Dear reader,

Currently I am studying on concourse tasks running scripts.

This is my script:

```
#!/bin/sh
 
whoami
 
env
 
sudo kubectl --context kind-kind get pods --all-namespaces

```

This is my YAML file:

```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
  - name: task-scripts

run:
  path: /bin/sh
  args: ["./task-scripts/task_status-cf.sh"]

```

This is the command:

`$ fly -t tutorial e -c task_status-cf.yml`

This is the output:

```
uploading task-scripts done
executing build 144 at http://localhost:8080/builds/144
initializing
initializing check: image
selected worker: e9f4ac7368bb
INFO: found existing resource cache

selected worker: e9f4ac7368bb
running /bin/sh ./task-scripts/task_status-cf.sh
root
USER=root
SHLVL=1
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/tmp/build/e55deab7
ATC_EXTERNAL_URL=http://localhost:8080
./task-scripts/task_status-cf.sh: line 7: sudo: not found
failed
```

I would very much like to improve my troubleshooting skills.
Can anybody help me?
Does anyone have a tip or an idea to resolve this?
