### DISCUSSION TITLE
How to run a docker image (w/o specify path or command)

### DISCUSSION THREAD

**Discussion by rngtng** [concourse/concourse#8458] [General]
Hey dear concourse community
I've the case where I just want to pull a docker image and execute it. The image is fully self-contained and exits on its own once the (test) job is done. Exit 0 if successful, other wise Exit 1. I now struggle in include this into a pipeline nicely.

As a `task` requires a `config` which requires a `run.path` I don't find a way to archive this w/o a dedicated entrypoint script. That's the working pipeline I have to far:

```
...
jobs:
  - name: test
    plan:
      - task: test
        image: <my image>
        config:
          platform: linux
          run:
            path: /entrypoint.sh
```

Is there any option do avoid the `path: /entrypoint.sh` part?
