### DISCUSSION TITLE
Conditional Steps

### DISCUSSION THREAD

**Discussion by luis-n4489** [concourse/concourse#8471] [General]
I am a bit stomped on how to proceed with something. 
Since concourse really does not work well with conditional steps, I am using the following 
```

  - try: 
      do:
      - load_var: do_deploy
        file: action/do_deploy
      on_success:
        do:
          - put: keyval
            params:
              file: keyvalout/keyval.properties
          - put: comment-deploy
      on_failure:
        do:
          - try:
              put: pipeline
              params:
                release: pipeline
```

IF there is a file in action called do_deploy then load and on success do put keyvals from the information within that file. 
now, since I am locking the pipeline for other jobs / tasks to wait, i unlock the pipeline down the line once the do_deploy is completed. BUT when the load_var fails, it leaves the pipeline locked. NOT good, i tried adding the on_failure but i assume that since this is a try step its not technically "failing" . is there any way around this?
