### DISCUSSION TITLE
Authorization with nested ldap groups

### DISCUSSION THREAD

**Discussion by dwrolvink** [concourse/concourse#8472] [Help & Support]
It seems when using ldap authentication/authorization that group membership is not picked up when it is done via a nested group.

Compare these two setups:
``` yaml
# With UserA being a member of Team_GS, which is a member of Team_DS
roles:
- name: member
  ldap:
    groups: ["Team_DS"]
```
vs
``` yaml
# With UserA being a member of Team_DS
roles:
- name: member
  ldap:
    groups: ["Team_DS"]
```

In both cases authentication works, as in, the user can log in and there is no error. But only in the second setup will the user have member permissions on the respective group.

It seems that the user has to be a direct member of the group that is configured on the team.

**My question is: can we configure Concourse to also pick up on users that are in nested groups? And if so, how?**

This is our configuration:
``` yaml
# Concourse version: v7.8.0
      ldap_auth:
        bind_dn: ((ldap_bind_dn))
        bind_pw: ((ldap_bind_pw))
        group_search_base_dn: DC=ad,DC=comp,DC=nl
        group_search_filter: (objectClass=group)
        group_search_group_attr: member
        group_search_name_attr: cn
        group_search_scope: sub
        group_search_user_attr: DN
        host: ((ldap_host))
        insecure_no_ssl: true
        user_search_base_dn: DC=ad,DC=comp,DC=nl
        user_search_email_attr: userPrincipalName
        user_search_filter: (objectClass=person)
        user_search_id_attr: cn
        user_search_name_attr: cn
        user_search_scope: sub
        user_search_username: cn
```

**Comment by dwrolvink** [comment]
Alright, while closing the hundred tabs I opened researching this issue my eyes fell on a little post that gives the answer: https://github.com/concourse/concourse/issues/2638#issuecomment-658310692

Basically just setting `group_search_group_attr: 'member:1.2.840.113556.1.4.1941:'`. It seems to work for us, will test more but preliminary tests are positive!

**Reply by dwrolvink** [reply]
Update: this method is incredibly slow when logging in. Waiting for 10 seconds or more. Looking into ways to decrease this time.

**Reply by dwrolvink** [reply]
Alright. With the settings below we get a quick login and nesting of groups. 

The prerequisite is that any and all groups that are linked to Concourse are located somewhere under the ou listed in `group_search_base_dn`. Intermediate groups can be anywhere in the AD tree.

``` yaml
      ldap_auth:
        bind_dn: ((ldap_bind_dn))
        bind_pw: ((ldap_bind_pw))
        group_search_base_dn: "OU=Groups,OU=Applications,DC=ad,DC=comp,DC=nl"
        group_search_filter: (objectClass=group)
        group_search_group_attr: member
        group_search_name_attr: cn
        group_search_scope: one        
        group_search_user_attr: DN
        host: ((ldap_host))
        insecure_no_ssl: true
        user_search_base_dn: DC=ad,DC=comp,DC=nl
        user_search_email_attr: userPrincipalName
        user_search_filter: (objectClass=person)
        user_search_id_attr: cn
        user_search_name_attr: cn
        user_search_scope: sub
        user_search_username: cn
```

Notice `group_search_scope: one`, which means that the user can be the member of a group that is a member of our configured group, but not any further away than that.

The trick compared to the first ldap query is that we only look at the groups in the "OU=Groups,OU=Applications,DC=ad,DC=comp,DC=nl" OU instead of looking at ALL the groups in the entire directory; then we expand downward from that short list to see which of those groups the user is a member of, directly or indirectly and we do this only one step down to avoid getting into large deeply nested groups via-via. 

The use case below is tested to work with the settings above:

```
"CN=Function_Admins,OU=Groups,OU=NotInSearchBase,DC=ad,DC=comp,DC=nl"
"CN=Team_DS,OU=Groups,OU=Applications,DC=ad,DC=comp,DC=nl"

User is member of group Function_Admins which is a member of Team_DS
```
