### DISCUSSION TITLE
Why is task step taking a whopping 1 minutes to "check" before pulling the image?

### DISCUSSION THREAD

**Discussion by tgckpg** [concourse/concourse#8509] [Help & Support]
Here I have the following config
```yaml
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine

inputs:
  - name: project-src
    path: .

outputs:
  - name: deploy-confs

run:
  path: sh
  args:
    - -exc
    - |
      VERSION=$( cat commit.sha )
      sed "s/IMAGE_TAG/$VERSION/g" k8s/deployments.yaml >> deploy-confs/prod.yaml
      echo "---" >> deploy-config.yaml
      sed "s/IMAGE_TAG/$VERSION/g" k8s/cronjob.yaml >> deploy-confs/prod.yaml
```

![image](https://user-images.githubusercontent.com/5273654/182017313-6e0aba97-c688-4cd4-885d-2538d5899428.png)

Other steps within the same job does not take this long. Even the `build` tasks only toke about 24s.

This 4 lines of commands only toke ~6s to run. Given the alpine image is small is shouldn't have take this long. Is there anyway to see what it's doing on this particular step?
