### DISCUSSION TITLE
Have pipeline force an ECS redeployment

### DISCUSSION THREAD

**Discussion by paulmiller3000** [concourse/concourse#8539] [Help & Support]
Hi there! We are creating a pipeline that builds a Docker container from GitHub source and pushes it to ECR. That works fine. The last piece we're struggling with is triggering a new ECS service deployment. 

What's the best way to have Concourse trigger the new deployment? We'd be happy just to run a command from bash (e.g., `aws ecs update-service --cluster ((cluster_name)) --service ((service_name)) --force-new-deployment --region ((aws_region))`) but can't figure out how to use an AWS CLI with Concourse.

Here's our pipeline:

```
--- 
resources:
- name: source-code
  type: git
  icon: github
  source:
    uri: https://github.com/redacted
    branch: main
    username: ((github_user_name))
    password: ((github_user_password))

- name: ecr-reg
  type: registry-image
  icon: docker
  source:
    aws_region: ((aws_region))
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    repository: ((aws_ecr_repo))
    tag: "latest"

jobs:
- name: build-and-push
  plan:
  - get: source-code
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: source-code
      outputs:
      - name: image
      run:
        path: build
      params:
        CONTEXT: source-code
  - put: ecr-reg
    params:
      image: image/image.tar
```
