### DISCUSSION TITLE
Task Artifact Output To load_var ?

### DISCUSSION THREAD

**Discussion by rfpludwick** [concourse/concourse#8551] [Help & Support] [answered]
I'm trying to get the date & time a build was executed loaded into a var for usage later in my pipeline. The following spec doesn't seem to be doing the trick. Do I have my mappings incorrect here, or is this simply not possible as of v7.8.1?

```yaml
- task: get-datetime
  config:
    platform: linux
    image_resource:
      type: registry-image
      source:
        repository: arm64v8/alpine
    run:
      path: sh
      args:
        - -exc
        - |
          date +%Y-%m-%dT%H-%M-%S > /datetime.txt
    outputs:
      - name: datetime
- load_var: datetime
  file: datetime/datetime.txt
```
