### DISCUSSION TITLE
How to add docker image tag?

### DISCUSSION THREAD

**Discussion by sooraj-sky** [concourse/concourse#8593] [Help & Support]
Hello I'm tying to add docker tag. But i could't find how to do that. I want to tag my image like imagename:$gitbranch-$concourse_build_id
eg: myimage:test-12.

This is my current Pipeline.

```resources:
- name: sky-meter-git
  icon: github
  type: git
  source:
    uri: https://github.com/sooraj-sky/sky-meter.git
    branch: release
    git_config:
    - name: safe.directory
      value: /tmp/build/get

- name: sky-meter-docker-image
  type: registry-image
  icon: docker
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/sky-meter


jobs:
- name: build-and-push
  plan:
  - get: sky-meter-git
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: sky-meter-git
      outputs:
      - name: image
      params:
        CONTEXT: sky-meter-git
      run:
        path: build
  - put: sky-meter-docker-image
    params:
      image: image/image.tar
```

**Comment by suhlig** [comment]
I'm using the legacy [docker-image](https://github.com/concourse/docker-image-resource) resource, which can read `tag_file` for a custom tag. This file is written in a previous task. The newer [registry-image](https://github.com/concourse/registry-image-resource) resource can likely do similar things, but I haven't migrated yet.

My pipeline looks like this:

```yaml
jobs:
  - name: build-image
    plan:
      - get: tasks
      - task: write-param
        file: tasks/write-param/task.yml
        params:
          file: tag
          content: ((branch))
          reveal: true
        output_mapping: { result: image-tag }
      - get: image-source
        trigger: true
      - put: image
        params:
          build: image-source/images/my-project
          tag_file: image-tag/tag

resources:
  - name: image-source
    type: git
    source:
      uri: git@github.com:my-org/tasks.git
      private_key: ((git-private-key))
      branch: ((branch))
      paths: [ images/my-project/Dockerfile ]

  - name: image
    type: docker-image
    source:
      repository: my-org/image
      username: my-user
      password: ((apikey))
      tag: ((branch))
```

I'm setting `branch` when `fly`ing the pipeline with `--var branch=$GIT_BRANCH`.

The relevant part of the write-params task is

```yaml
params:
  content: # the content to write
  file: # path to file to write to; below output 'result'

outputs:
  - name: result

run:
  path: bash
  args:
  - -c
  - |
    mkdir -p $(dirname result/$file)
    echo "$content" | tee result/$file
```
