### DISCUSSION TITLE
How to overcome `set_pipeline: self` overwrite of parent ref in a multi-branch workflow?

### DISCUSSION THREAD

**Discussion by saj** [concourse/concourse#8646] [Help & Support]
Hello,

I'm looking to set up a multi-branch workflow (on Git) not unlike that described in [Tracking Branches](https://concourse-ci.org/multi-branch-workflows.html#multi-branch-tracking-branches).  Pipelines should appear and disappear (or be archived) with the appearance and disappearance of branch heads.  Ephemeral pipelines should update with each new version from the `git` resource -- prior to execution.  As perhaps one additional complication, my child pipeline definitions reside in the spatial git repo.

In other words, I'm looking to emulate the sort of behaviour that most Git-native CI systems offer with their in-repo pipeline configurations.

I have most of the pieces in place, but have stumbled on what would appear to be an intractable problem:

If the child pipeline is configured **without** `set_pipeline: self`, most things work -- except the child pipeline often (always?) executes with a pipeline configuration from a previous branch tip revision.  The child pipeline is executed before its parent is given an opportunity to `set_pipeline: child`.

If the child pipeline is configured **with** `set_pipeline: self`, the problem above goes away, but is replaced with a new problem.  `set_pipeline: self` overwrites the parent reference on the pipeline, disconnecting the child from its original parent pipeline.  This breaks pipeline garbage collection.  When the branch head is eventually removed from the git repository, the child pipeline is not automatically removed (or archived).  (To add insult to injury, a new build is scheduled on the child pipeline, which fails because the ref is no longer available.)

I don't expect this problem is specific to multi-branch workflows.  Any workflow where a parent->child relationship exists simultaneous with a `set_pipeline: self` (in the child) would probably do it.  Though multi-branch workflows are perhaps more likely to spawn ephemeral pipelines, so the non-functional pipeline GC is more noticeable.

Pipelines below.  I am using Concourse v7.9.0.  Is it possible to solve both of these problems simultaneously?  Thanks!

There are three pipelines.  The grandparent and parent reside in something like a 'Concourse bootstrap' repository.  The child resides in a separate spatial project repository.

grandparent:

```
---
resource_types:
- name: git-branches
  type: registry-image
  source:
    repository: aoldershaw/git-branches-resource

resources:
- name: bootstrap
  type: git
  icon: github
  source:
    uri: git@github.com:org/bootstrap.git
    private_key: ((secret))
  webhook_token: "secret"

- name: project-branches
  type: git-branches
  icon: github
  source:
    uri: git@github.com:org/project.git
    private_key: ((secret))
  webhook_token: "secret"

jobs:
- name: set-self-pipeline
  plan:
  - get: bootstrap
    trigger: true
  - set_pipeline: self
    file: bootstrap/plumb/project.yml

- name: set-branch-pipelines
  plan:
  - get: bootstrap
    trigger: true
    passed: [set-self-pipeline]
  - get: project-branches
    trigger: true
  - load_var: branches
    file: project-branches/branches.json
  - across:
    - var: branch
      values: ((.:branches))
    set_pipeline: plumb-project-branch
    file: bootstrap/plumb/project-branch.yml
    instance_vars:
      branch: ((.:branch.name))
```

parent (`bootstrap/plumb/project-branch.yml` from above):

```
---
resources:
- name: project
  type: git
  icon: github
  source:
    uri: git@github.com:org/project.git
    branch: ((branch))
    private_key: ((secret))
    paths:
    - dist/concourse/pipeline.yml
  webhook_token: "secret"

jobs:
- name: set-branch-pipeline
  plan:
  - get: project
    trigger: true
  - set_pipeline: project
    file: project/dist/concourse/pipeline.yml
    instance_vars:
      branch: ((branch))
```

child (`project/dist/concourse/pipeline.yml` from above):

```
---
resources:
- name: project
  type: git
  icon: github
  source:
    uri: git@github.com:org/project.git
    branch: ((branch))
    private_key: ((secret))
  webhook_token: "secret"

- name: go1
  type: registry-image
  icon: docker
  check_every: 24h
  source:
    repository: golang
    tag: "1-alpine"

jobs:

# (!) this is the problematic part (!)
- name: set-self-pipeline
  plan:
  - get: project
    trigger: true
  - set_pipeline: self
    file: project/dist/concourse/pipeline.yml

- name: work-goes-here
  plan:
    # ...
```
