### DISCUSSION TITLE
Git put - no fast forward

### DISCUSSION THREAD

**Discussion by luis-n4489** [concourse/concourse#8649] [General]
Trying to look for a way to update a semver inside a file on a repo but without FF on the commit ID. bc if the commit ID changes, it triggers CI to run over and over in a loop. Has anyone been successful at doing non fast forward puts?

**Comment by sasha-arrabi** [comment]
I've had success using the [`semver` resource](https://github.com/concourse/semver-resource) and pointing to the same repo, but on another branch (I called my branch `version`, and it contained a single file, also called `version` that contained the semver for the project).

Here's an example resource configuration:

```yaml
- name: version
  type: semver
  icon: tag
  source:
    initial_version: "1.0.0"
    driver: git
    uri: <your-repo>
    branch: version
    file: version
    private_key: <private key for github>
    git_user: <your git user>
    commit_message: "[ci skip] Update version to %version%"
```

That way, it didn't cause any endless loops, since it didn't live on the `main` branch with the rest of the source code.

Not sure if this solution is applicable, but I hope it helps!
