### DISCUSSION TITLE
Fly execute is not writing to output (shows "cancelled" instead)

### DISCUSSION THREAD

**Discussion by sasha-arrabi** [concourse/concourse#8652] [Help & Support] [answered]
Hello! I was hoping I can get some help from the community on an issue I'm having running the [`fly execute` command](https://concourse-ci.org/tasks.html#running-tasks) on Concourse v7.6.0.

I'm trying to extract an output from the one-off task, but when the one-off task executes, it never ends up extracting out the `output` folder. In the web UI, all I see is "cancelled" when I hover over the `put` step on the task output:

![image](https://user-images.githubusercontent.com/1562048/208965520-28d92e7b-de44-4933-a4c5-64a8e860bf18.png)

Here's the overall setup, if it helps:

I'm executing the `fly execute` command using Node.js's `child_process.spawn()` utility, like so:

```typescript
const commandArgs: Array<string> = [];

commandArgs.push('--target', CONCOURSE_TEAM);
commandArgs.push('execute');
commandArgs.push('--privileged');
commandArgs.push('--config', `${ROOT_FOLDER}/${TASK_CONFIG}`);
commandArgs.push('--output', `output=${ROOT_FOLDER}/output`);
commandArgs.push('-v', `worker-image=<redacted>`);
commandArgs.push('-v', `script-name=<redacted>`);

if (VARS_FROM) {
    commandArgs.push('--load-vars-from', `${ROOT_FOLDER}/${VARS_FROM}`);
}

if (INPUTS_FROM) {
    commandArgs.push('--inputs-from', INPUTS_FROM);
}

if (INPUTS_FROM && IMAGE) {
    commandArgs.push('--image', IMAGE);
}

const childProcess = spawn('fly', commandArgs);
```

The task config has the `output` folder specified like so:

```yaml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: <redacted>
    tag: latest

inputs:
  - name: source
  - name: tasks
    optional: true

outputs:
  - name: output

params:
  PROJECTS:
  TARGET:
  EXTRA_ARGS:
  ROOT_FOLDER:
  PR_NUMBER:
  BRANCH:
  BASE:

run:
  path: /bin/bash
  args:
    - -c
    - |
      ((setup-git-access))
      ((job-setup))
      node -r source-map-support/register ci/scripts/out-tsc/((script-name)).js
```

When I ran the `fly intercept` command on the one-off task, I was able to confirm that the output folder is getting written to (there is a `dist` folder inside):

![image](https://user-images.githubusercontent.com/1562048/208966787-a36d436f-026f-4647-a6e1-babacbf95ccc.png)

If anybody has seen this issue before or knows how to help, it would be greatly appreciated!
