### DISCUSSION TITLE
How self-contained are tasks?

### DISCUSSION THREAD

**Discussion by cjdcordeiro** [concourse/concourse#8684] [Help & Support]
Hi there,

I've deployed Concourse via the quickstart guide (i.e. with Docker Compose), and I've been playing around with a few privileged tasks, as one of my pipelines requires making use of a registry-image with `systemd` as the ENTRYPOINT.

So my tasks looks something like:

```yaml
jobs:
- name: hello-world-job
  plan:
  - task: hello-world-task
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ccordeiro/rockcraft
      run:
        path: /usr/local/bin/entrypoint-wrapper.sh
```

And my `/usr/local/bin/entrypoint-wrapper.sh` executable then runs `exec /lib/systemd/systemd --system --system-unit myservice.service`.

When the task runs, it fails, complaining about it now being PID 1 - "Can't run system mode unless PID 1.". By looking inside the Concourse container, I see that the PID namespace is shared with the task's processes, so I can see where this error comes from.

My question though is, aren't tasks fully self-contained? Or does this happen only because Concourse is running in a container itself?

Thanks in advance, cheers
