### DISCUSSION TITLE
Creating a new resource type - how?

### DISCUSSION THREAD

**Discussion by zilti** [concourse/concourse#8689] [Help & Support]
Hello! We are planning to use Concourse at our company. We will use it on FreeBSD, and use Fossil as VCS. So far so good, but I need to create a resource type for Fossil. 

Unfortunately, the documentation is extremely sparse beyond saying "you need `check`, `in`, and `out`". Do these three files just need to be in the root of the repository? 

Also, what do I specify as `type` in `resource_type`? Obviously, since we intend to run Concourse on FreeBSD, a Docker image is not an option.

**Comment by taylorsilva** [comment]
Yeah this page could be so much better: https://concourse-ci.org/implementing-resource-types.html

If you want to get started quickly then I'd use another resource to start writing from. The mock resource is simple enough to parse and do your own stuff with: https://github.com/concourse/mock-resource

> Also, what do I specify as type in resource_type? Obviously, since we intend to run Concourse on FreeBSD, a Docker image is not an option.

There are two ways to add resource types to your worker which are how you define the name/type of your resource type.

## 1 - Locally on the worker
Basically following this guide: https://concourse-ci.org/concourse-worker.html#installing-or-upgrading-bundled-resource-types
and depending on the name of the directory you make under `/usr/local/concourse/resource-types/` will be the name/type of your resource.

## 2 - In your pipelines

This way is faster since you don't have to do anything on the worker. You do need to build a container image of your resource type and push it somewhere that concourse can fetch it from. Then in the `resource_type` section you'll fetch your resource type using the `registry-image` resource: https://github.com/concourse/registry-image-resource/

Example from this page: https://concourse-ci.org/resource-types.html#resource-types
```yaml
resource_types:
- name: rss
  type: registry-image
  source:
    repository: suhlig/concourse-rss-resource
    tag: latest

resources:
- name: booklit-releases
  type: rss
  source:
    url: http://www.qwantz.com/rssfeed.php
```

Hope that helps!
