### DISCUSSION TITLE
Is it possible to "include" values from another pipeline YAML?

### DISCUSSION THREAD

**Discussion by robertsonic** [concourse/concourse#8694] [Help & Support]
I'd like to have job definitions in my pipeline defined by another file. So wi would like to do something like:

**file1.yml**
```
jobs:

 #    update this pipeline from GIT copy, to keep concourse & GIT in sync
  - name: aws-deploy-((ENV))((DEPLOYMENTID))-main
    public: false
    serial: true
    plan:
      - get: gitcontents
        trigger: true

      - !include file2.yml

      - task: get-creds-for-aws-account
        file: gitcontents/concourse/tasks/gettmpcreds.yml
        params:
          CNF_REGION: ((REGION))
          CNF_ACCOUNT: ((ACCOUNT))
          CNF_ROLE:    ((ROLE))
          CNF_KEY:     ((KEY))
          CNF_SECRET:  ((SECRET))
          CNF_WORKFLOW: pcms
        vars:
          REPO: gitcontents
```

**file2.yml**
```
      - task: deploy-aws-resources
        file: gitcontents/concourse/tasks/deploy.yml
        vars:
          REPO: gitcontents
```
Is something like this possible?
