### DISCUSSION TITLE
Ping Errors in my Pipeline

### DISCUSSION THREAD

**Discussion by tommy-mcgee** [concourse/concourse#8697] [General]
I have a pipeline... when it gets ran it pulls a custom docker image from a local registry on  my network.
The Image is pulled fine... 
It starts to run a .sh file that I  have in a home folder under a local user in the image  that is not root.
In the pipeline I set the user to be used to run the command as my local user in the image.
The script starts to run as expected and at some point it uses icmp ping.
The concourse web interface starts to show these results.
```
ping: socktype: SOCK_RAW
ping: socket: Operation not permitted
ping: => missing cap_net_raw+p capability or setuid?

```
Then of course my script will fail ping is not permitted  for this non root user
the odd thing is if I run the docker image in a container outside of concourse ping works fine for that local user
and my script completes successfully 

could I be missing something?..... I even tried the privileged option but I am not sure I have it in the correct location in the yaml file

here is example of my yml
```
---
resources:
- name: test-rsrc
  type: git
  icon: github
  source:
    uri: https://some-github.com/myexample/exampletest

jobs:
- name: test-run
  public: true
  plan:
  - get: test-rsrc
    trigger: true
  - task: add-one
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: IPToMYRegistry/myimage
          tag: latest
      run:
        user: testuser
        path: /bin/sh
        args:
        - -c
        - |
          /home/testuser/test-scripts/runtest.sh
```
Thanks so much for any guidance
