### DISCUSSION TITLE
Conditional Task After Full Repo Testing

### DISCUSSION THREAD

**Discussion by rfpludwick** [concourse/concourse#8701] [Help & Support]
I have a pattern where I'll have a pipeline run testing against every git repo commit, and then conditionally perform a task if that testing passed **and** certain files have changed. The example below is this pattern for setting another pipeline, i.e. "Test the repo, and if the pipeline's files have changed, set it."

```yaml
resources:
  - name: "repo-self"
    type: git
    source:
      uri: "git@github.com:some-repo.git"
      branch: main
  - name: "repo-self-pipeline-1" # for triggering setting that pipeline
    type: git
    source:
      uri: "git@github.com:some-repo.git"
      branch: main
      paths:
        - "concourse/pipeline-1/*"
jobs:
  - name: testing
    plan:
      - get: "repo-self"
        trigger: true
      - in_parallel:
          - task: "test-1"
          - task: "test-2"
          - task: "test-3"
  - name: "set-pipeline-1"
    plan:
      - in_parallel:
          - get: "repo-self"
            passed:
              - testing
          - get: "repo-self-pipeline-1"
            trigger: true
      - set_pipeline: "pipeline-1"
        file: "repo-self-pipeline-1/concourse/pipeline-1/main.yaml"
```

I have a similar pattern for "Test the repo, if the Dockerfile changed, build the image." I cannot seem to get this duality of "need to look at and test the entire repo" but "only execute some type of build operation on certain changed files."

I've tried adding `repo-self-pipeline-1` to the `testing` job without a trigger, but that doesn't ensure that it has the **same git commit sha**. Any ideas here?
