### DISCUSSION TITLE
Tag docker image

### DISCUSSION THREAD

**Discussion by harshini7** [concourse/concourse#8745] [General]
How to tag docker image when building with prod-1.2.2 ?

**Comment by king-jam** [comment]
If you are using the Docker Image resource, something like:

```yaml
resources:
- name: myapp-git-repo
  type: git
  source: # ...

- name: myapp-image
  type: docker-image
  source:
    repository: mydockerhub/myapp-image
    username: username
    password: password

- name: git-resource-rootfs
  type: s3
  source: # ...

jobs:
- name: build-rootfs
  plan:
  - get: myapp-git-repo
  - task: make-tag-file
    file: myapp-git-repo/ci/task-that-creates-tags-file.yaml
  - put: myapp-image
    params:
      build: git-resource
      tag_file: make-tag-file/tags-file
      get_params: {rootfs: true}
```

You need to put a task in the middle that creates a file with your tags inside of it. If you are using the registry-image resource, it's a similar scenario but you need to pass in `additional_tags` instead of `tag_file`.
