### DISCUSSION TITLE
How to detect a branch is created? The pipeline is only active when the branch is created/exists?

### DISCUSSION THREAD

**Discussion by fong1999** [concourse/concourse#8784] [General]
Hi! The use case is I have a concourse pipeline which runs against a certain branch called `release-candidate` branch. Below is the fly command.

`fly sp -t team-name -c ./pipeline.yml -p app-repo-release-candidate -l settings-default.yml -v BRANCH=release-candidate`

Below is how I set up gitrhub repo as a resource.

```
  - name: source-code
    type: git
    source:
      branch: ((BRANCH))
      uri: ((resources.git.code_repo_url))
      private_key: ((pipeline-creds-ssh.privatekey))
    webhook_token: ((pipeline-webhook-token))
    check_every: 1m
```

But the `release-branch` only exists when we have a release, it is deleted after the release. Once it is being deleted, I see concourse pipeline shows red mark around the resource `source-code`. But if I can have a way to let concourse yaml only check when the branch exists/created. Or the pipeline is only active when the branch exists or is created? Any suggestions? 

Thanks much!
