### DISCUSSION TITLE
BUILD_CREATED_BY

### DISCUSSION THREAD

**Discussion by nickhyoti** [concourse/concourse#8804] [Help & Support] [answered]
Hello,

I have seen that this has been added as an option but does anyone have an actual example of how to use it?

**Comment by amayer5125** [comment, marked as answer]
If you run this pipeline you will see that one of the `put` tasks has the `BUILD_CREATED_BY` environment variable set, and the other does not. I imagine this would be useful if you created a custom resource and wanted to use the user that triggered the pipeline somehow.

```yaml
resources:
- name: exposed
  type: mock
  expose_build_created_by: true
- name: not-exposed
  type: mock

jobs:
- name: output-env-vars
  plan:
  - put: exposed
    params:
      version: mock
      print_env: true
    no_get: true
  - put: not-exposed
    params:
      version: mock
      print_env: true
    no_get: true
```
