### DISCUSSION TITLE
How to access artifact from across tasks

### DISCUSSION THREAD

**Discussion by sibevin** [concourse/concourse#8847] [Help & Support] [answered]
Here is an example to run task with across:

```yaml
resources:
  - name: runner-image
    type: registry-image
    source:
      repository: busybox
jobs:
  - name: across-artifact-test-job
    plan:
      - get: runner-image
      - task: build-source-task
        image: runner-image
        config:
          platform: linux
          outputs:
            - name: app-source
          run:
            path: sh
            args:
              - -exc
              - |
                echo "Text from source" > ./app-source/message
      - across:
          - var: plan
            values: ["dev", "free", "full"]
          - var: platform
            values: ["web", "mobile"]
        do:
          - task: append-plan-platform-task
            image: runner-image
            config:
              platform: linux
              inputs:
                - name: app-source
              outputs:
                - name: app-output
              run:
                path: sh
                args:
                  - -cx
                  - |
                    cat ./app-source/message > message_((.:plan))_((.:platform))
                    echo "((.:plan))_((.:platform))" >> message_((.:plan))_((.:platform))
                    mv message_((.:plan))_((.:platform)) ./app-output
      - task: show-result-task
        image: runner-image
        config:
          platform: linux
          inputs:
            - name: app-output
          run:
            path: sh
            args:
              - -cx
              - |-
                cat ./app-output/message_dev_web
```
When running the `show-result-task` task, it shows `missing inputs: app-output`. Are there any ways to access artifacts from across tasks?
