### DISCUSSION TITLE
juggle between "scheduling bias" and "reducing volume stream overhead"

### DISCUSSION THREAD

**Discussion by xdu-opendoor** [concourse/concourse#8849] [Help & Support]
hi all concourse experts!

I've got a concourse performance issue that I need help with. Would really love to see what advices experts have.

## Context

 - a `concourse` cluster running on `k8s`
 - source of builds are from a single large **mono** repo
   - pipeline definition and application source code for all projects live in the same repo
 - concourse chart version is `13.0.0` and concourse image tag is `7.7.1` (inherited configuration, I'm not 100% sure about compatibility)
 - `containerPlacementStrategies`: `["volume-locality", "fewest-build-containers"]`
 - [P2P streaming](https://concourse-ci.org/concourse-worker.html#configuring-peer-to-peer-volume-streaming) is **NOT** turned on.

## Dilemma

2 performance issues that I need to juggle: solution to one would cause the other.

I need to pick my poison between scheduling bias (unable to horizontally scale) and slowing down all pipelines (many redundant volume stream)

### Issue 1: expensive volume stream

job steps contain many redundant volume streaming operations (see the `example.yaml` in the end)

 - step 1 `get` a `git` resource. picked up by worker-1, which does a `git clone`
 - step 2 `get` another `git` resource. picked up by worker-2, which does a `git clone`
 - step 3 `task` a custom initialization step based on step 1. pick up by worker-3 and stream volume from worker-1
 - step 4 `put` to a `terraform` resource. picked up by worker-3 and stream volume from worker-1

`git clone` a large mono repo and streaming that volume both take a long time.

for `clone` I have options to reduce clone depth and reduce unnecessary clones from pipeline definition.
for volume stream, I believe the solution here is to count on the `volume-locality` container placement strategy. not sure if the slowness is caused by streaming itself taking a long time, or bottlenecked by web node networking IO (P2P stream may help)

after a long period of time of testing, another issue was discovered

### Issue 2: scheduling bias

I've configured the cluster to use `volume-locality` as the only container placement strategy on a concourse cluster with a 100+ pipelines running for production facing CI/CD. during peak hours I see 3~4 worker nodes (from a pool of 25) was taking most of the workloads. 

This is measured from `concourse.ci.worker_containers` and `concourse.ci.worker_volumes` metric, broken down by worker. The 3~4 worker nodes will have 100+ containers while all other nodes have less than 20.

I don't think this bias is expected but I don't know what's the best approach to figure out why.

## Questions

1. Is `containerPlacementStragety: volume-locality` the only configuration that can possibly help minimize volume stream? Is there any other env var or chart value, or certain keywords in the pipeline definition that can specify the affinity of volume(s) and `serial` steps? 
2. how can I debug the scheduling bias when `volume-locality` is the only `containerPlacementStragety` ? (logs? metrics?)
3. my understanding is that without P2P streaming, all worker-to-worker volume stream operations go through the web nodes, whose networking io would be a performance bottleneck, is that correct? is 1:8 a healthy ratio between web nodes and worker nodes? (if so, how is this number derived? / if I need to adapt the ratio based on my environment, what metrics should I looking out for?)

Many thanks in advance!!

```
# example.yaml

groups:

- jobs:
  - run-terraform
  name: deploy

jobs:

- name: run-terraform
  plan:
  - get: my-project-source
    trigger: true
  - get: pipeline
  - file: pipeline/shared/pipeline/scripts/my-init.yaml
    params:
      TERRAFORM_DIR: projects/my-project/terraform
    task: my-init
  - params:
      env_name: my-project
      terraform_source: initialized/projects/my-project/terraform
      vars:
        aws_access_key: ((aws-access-key-id))
        aws_secret_key: ((aws-secret-access-key))
    put: terraform-resources
  serial: true

resource_types:

- name: terraform
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.31
  type: docker-image

resources:

- name: my-project-source
  source:
    branch: master
    paths:
    - shared/libs
    - projects/my-project
    uri: <github_url_to_mono_repo>
  type: git

- name: pipeline
  icon: git
  source:
    branch: master
    paths:
    - shared/pipeline/scripts
    - projects/my-project/ci/pipeline
    uri: <github_url_to_mono_repo>
  type: git

- name: terraform-resources
  source:
    backend_config:
      access_key: ((s3-access-key-id))
      bucket: my-terraform-bucket
      key: terraform.tfstate
      region: us-west-2
      secret_key: ((s3-secret-access-key))
      workspace_key_prefix: projects/my-project
    backend_type: s3
    env:
      AWS_ACCESS_KEY_ID: ((aws-access-key-id))
      AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
    env_name: my-project
  type: terraform

```
