### DISCUSSION TITLE
Unique key for resources

### DISCUSSION THREAD

**Discussion by fenech** [concourse/concourse#8891] [Ideas]
I recently ran into an issue where I had a Git resource with `check_every: never` that was checking regularly.

I found out that this was due to the fact that I had [global resources](https://concourse-ci.org/global-resources.html) enabled, and so another resource with the same `source` was triggering new versions of this one.

To workaround this issue, I added a "dummy" parameter to the source, so that they were no longer treated as the same:
```yaml
resources:
- check_every: 1m
  icon: git
  name: every-minute
  source:
    uri: https://github.com/concourse/concourse.git
  type: git
- check_every: never
  icon: git
  name: never
  source:
    uri: https://github.com/concourse/concourse.git
    __unique_key: thing
  type: git
  webhook_token: ((token))

jobs:
  - name: test
    plan:
      - get: every-minute
      - get: never
```

This works fine in this case, but it also depends on the way that the Git resource validates the `source` object, since in principle it could reject this invalid key.

I was wondering if it made sense to add this key to the top-level resource configuration to say "don't share me with other resources"? 

I don't want to disable global resource checking, as I think it's useful in other places, so it'd be nice to have a standardised way of handling this case.
