### DISCUSSION TITLE
Concourse git-prs error run check step: check: resource script '/opt/resource/check []' failed: exit status 1

### DISCUSSION THREAD

**Discussion by ezhilarasikannan** [concourse/concourse#8914] [Help & Support]
Hi Team,

I am facing below issue from last week which was working fine till 22-Jan-2024.  No changes done in pipeline, Vault or Github repo.

Failing in below step:
```
  - name: git-prs
    type: pull-request
    source:
      repo: ((repo.id))
      uri: ((repo.uri))
      access_token: ((repo.access_token))
      private_key: ((repo.deploy_key))
      only_mergeable: true
```

**git-prs errored run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1 stderr: failed to unmarshal request: json: unknown field "only_mergeable"**

Please let me know how to resolve this issue

Commented only_mergeable and tested then getting below error

**git-prs errored run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 1 stderr: failed to unmarshal request: json: unknown field "private_key"**

posted the same in Stack overflow to get help - https://stackoverflow.com/questions/77977690/concourse-git-prs-error-run-check-step-check-resource-script-opt-resource-ch?noredirect=1#comment137471033_77977690

1. Verifiied secrets no expiry date given
2. Changed deploy keys and tested, still the same issue
3. No change done in Github repo or pipeline file
4. No upgrade done in Concourse
5. Concourse version used - 6.7.6
