### DISCUSSION TITLE
Trigger job with HTTP request

### DISCUSSION THREAD

**Discussion by achille1789** [concourse/concourse#8917] [Help & Support] [answered]
Hi, I looked around but I didn't find a proper answer.
I have a job that needs to run a Node JS script and I would like to trigger the job using a HTTP post request. It will be great if the script could look into the payload but it is not essential.
This job doesn't really need to use any resource as it just needs to run the script.
Is there any way to do it?
I am already using webhooks to trigger other jobs, but, as I said, this one doesn't need to use any resource, and tbh I have no idea of what resource I could use.
I tried to use the [Mock Resource](https://github.com/concourse/mock-resource) but it seems to work only setting new versions using the fly command. 
Any suggestions?
Thanks in advance

**Comment by suhlig** [comment, marked as answer]
I think the time resource would make a good trigger. 

```yaml
jobs:
  - name: manually-triggered-job
    plan:
      - get: manual
        trigger: true
      - task: some-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: alpine }
          inputs: [ name: manual ]
          run:
            path: sh
            args:
            - -ec
            - |
              cat manual/input
resources:
  - name: manual
    type: time
    source: { interval: 1s } # ensure there is a new version each time we check manually
    check_every: never
    webhook_token: supers3cret
```

Assmuming this pipeline was set as

```command
$ fly --target example set-pipeline --pipeline manual-trigger --config manual-trigger.yml
```

then you can trigger a new build with

```command
$ curl --request POST 'https://example.com/api/v1/teams/main/pipelines/manual-trigger/resources/manual/check/webhook?webhook_token=supers3cret'
```

Edit: I made a [gist as the canonical source for the example above](https://gist.github.com/suhlig/cdcbe6b69b6f19bcfd4819f676d67264)
