### DISCUSSION TITLE
How to enrich final artifact with changes performed during 'put' step?

### DISCUSSION THREAD

**Discussion by ihormanzii** [concourse/concourse#8921] [Help & Support] [answered]
Greetings! I have created custom concourse resource `mochawesome-report-timeline-parser-resource` which is parsing JSON files and produces HTML report out of it. Custom resource do it under `out` step/phase. I use this resource in `on_success` block after execution of main task which is test execution. The problem is that after executing of my resource in `put`, the file that was created (html file) is for some reason missing from the artifact, which is passed to `ensured` block.
Question is: Does put step modifications are counted in final artifact? If not, how should i implement such logic via custom resource?

![image](https://github.com/concourse/concourse/assets/47399777/4e36843f-cec5-41dc-a2d7-944bc80e2166)

This is my concourse ci pipeline config file

```
---
resource_types:
  - name: email-notification
    source:
      repository: pcfseceng/email-resource
      tag: latest
    type: docker-image

  - name: mochawesome-report-timeline-parser-resource
    source:
        repository: concourse-cypress-mochawesome-report-timeline-parser-resource
        tag: v.2.0
    type: registry-image

resources:
  - name: source-code
    type: git
    icon: github-circle
    source:
      branch: {} 
      uri: {}
      type: git
      icon: github

  - name: email-notification
    icon: email-alert
    source:
      from: {}
      smtp:
        anonymous: true
        host: {}
        port: "25"
        skip_ssl_validation: false
      to:
        - {}
    type: email-notification

  - name: mochawesome-report-timeline-parser-resource
    type: mochawesome-report-timeline-parser-resource
    source:
      disable: false

jobs:
  - name: ima-test
    build_log_retention:
      days: 5
      builds: 10
      minimum_succeeded_builds: 5
    plan:
      - get: source-code
      - task: simple-task
        config:
            platform: linux
            image_resource:
                type: registry-image
                source: { repository: busybox }
            run:
                path: echo
                args: ["Hello world!"]
        on_success:
          put: mochawesome-report-timeline-parser-resource
          params:
            mochawesome_report_path: "source-code/mochawesome/execution_report.json"
            output_html_report_path: "source-code"
          ensure:
            put: email-notification
            params:
              headers: "source-code/mochawesome/MailHeader.txt"
              body: "source-code/execution_report_timeline.html"
              subject_text: "Build : ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} - SUCCESS!"
```
