### DISCUSSION TITLE
Is it possible to cache a directory that is also an output?

### DISCUSSION THREAD

**Discussion by roaaaam** [concourse/concourse#9031] [Help & Support]
Hi there,
I was able to try the cache a given directory that persist files between builds (or runs - as long as the name, worker, etc. do not change of course)
However when I also set the same directory as an output so that it's being used an the next task, the cache is no longer working.
Here is an example pipeline to reproduce:
```yaml
---
jobs:
  - name: job-test-cache
    public: true
    plan:
      - task: write
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          caches:
          - path: abc
          outputs:      # <- Cache do not work with this
          - name: abc   # <- Cache do not work with this
          run:
            path: sh
            args:
            - |
              ls
              echo 1 >> abc/xyz
              cat abc/xyz

      - task: read
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
          - path: abc
          run:
            path: sh
            args:
            - |
              ls
              cat abc/xyz

```
When I do not have the `outputs` and not the second task, I can see the `xyz` file growing on each run.

Is it possible to cache a directory that is meant to be outputed?

Thanks
