### DISCUSSION TITLE
How I can trigger a job from a previous one?

### DISCUSSION THREAD

**Discussion by akaibukai** [concourse/concourse#9032] [General]
Hello,
So I have 3 jobs, A, B and C.
Basically I want that when A pass, it triggers B and C that will run in parallel, but after A.
I saw there's a `passed` option but it's applicable when you have a ressource only (or I miss something?)
Is it possible to do that?
Here is a sample pipeline:
```yml
---
jobs:
- name: job-a
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: sh
        args:
          - -exc
          - ls -la; echo "Created a file on $(date)" > ./files/created_file
      outputs:
        - name: files

- name: job-b
  plan:
  - task: consume-the-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      inputs:
        - name: files
      run:
        path: cat
        args:
          - ./files/created_file

- name: job-c
  plan:
  - task: consume-the-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      inputs:
        - name: files
      run:
        path: cat
        args:
          - ./files/created_file
```
Thanks!
