### DISCUSSION TITLE
vault failed to determine alias name from login request

### DISCUSSION THREAD

**Discussion by DonBower** [concourse/concourse#9190] [General]
I am getting this error in the `/var/vcap/sys/log/web/web.stdout.log` file of the web instance:
```
Error making API request.

URL: PUT http://vault.ag6hq.net:8200/v1/auth/approle/login
Code: 500. Errors:

* failed to determine alias name from login request
```

Here is my manifest:
```
      vault:
        auth:
          backend: approle
          parms:
            role_id: <redacted>
            secret_id: <redacted>
        path_prefix: /concourse
        url: http://vault.ag6hq.net:8200
        tls:
          insecure_skip_verify: true
```

if I run a curl, it works:
```
curl \
  --url http://vault.ag6hq.net:8200/v1/auth/approle/login \
  --request POST \
  --data '{"role_id":"<redacted>","secret_id":"<redacted>"}'
```
returns:
```
{"request_id":"6478aa51-4f57-3840-f88d-30c96e5001dc","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":null,"auth":{"client_token":"<redacted>","accessor":"<redacted>","policies":["concourse","default"],"token_policies":["concourse","default"],"metadata":{"role_name":"concourse"},"lease_duration":1200,"renewable":true,"entity_id":"<redacted>","token_type":"service","orphan":true,"mfa_requirement":null,"num_uses":0}}
```

when I login with the above token, I can list the secrets:
```
vault list /concourse/main
Keys
----
concourse_private_ssh_key
sub/
test
```
I can even read a secret:
```
vault kv get /concourse/main/test
==== Data ====
Key      Value
---      -----
value    test-value
```

Does anyone have a suggestion on how to debug or even what the issue is?

**Comment by taylorsilva** [comment]
> `/var/vcap/sys/`

Hmmm, bosh deployed Concourse?

Since it's a 500 error you might want to check the Vault logs. Might give you a better error message.

**Comment by DonBower** [comment]
I checked my vault logs, and there was zero. 
Yes, Bosh deployed concourse. 
[concourse-bosh-release](https://bosh.io/releases/github.com/concourse/concourse-bosh-release)

**Comment by DonBower** [comment]
I have resolved this issue, my bad.
here is the corrected config:

```
...
      vault:
        auth:
          backend: approle
          params:
            role_id: <redacted>
            secret_id: <redacted>
        path_prefix: /concourse
        tls:
         insecure_skip_verify: true
        url: https://vault.ag6hq.net:8200
...
```

`params:`, not `parms:`

So I would suggest that a different error was presented, indicating that the `params key not found.`
