### ISSUE TITLE
Auto-parallelize fetching resources

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1013]
# Feature Request
Concourse should automatically fetch a job's resources in parallel

## What challenge are you facing?
Concourse takes some time to fetch resources serially for resources that have lots of input resources. Quoting the docs: 
> The aggregate step is also useful for performing arbitrary steps in parallel, for the sake of speeding up the build. It is often used to fetch all dependent resources together:

It would be a good idea to automatically `aggregate` all get steps in a job that stand between tasks. 

Concourse could run e.g. this pipeline
```
plan:
- get: component-a
- get: component-b
- task: build
  file: build/task.yml
- get: component-c
- get: component-d
- task: integration
   file: build/integration.yml
```
Like this
```
plan:
- aggregate:
  - get: component-a
  - get: component-b
- task: build
  file: build/task.yml
- aggregate:
  - get: component-c
  - get: component-d
- task: integration
   file: build/integration.yml
```

I'm not sure if auto-parallelize is a good strategy, it may also be enough to give users a hint when they upload their pipeline?
