### ISSUE TITLE
Concourse hanging on put tasks on vsphere

### ISSUE THREAD

**Issue by adowns01** [concourse/concourse#1028]
* Concourse version: 2.7.3
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vSphere workers that report to ATC on GCP
* Did this used to work?: Yes

Stemcells: 
Our vSphere workers are on: `3312.20`
Our GCP workers are on: `3312.12`
Note our atc, is on GCP 

Issue: 
Currently about 90% of jobs that are running on vsphere, start out fine, the tests pass, then they hangs forever on the last four tasks. Always the same four tasks. I've seen it hang here for over an hour, before I kill the build manually. 

The tasks are: `build-failure-artifact-pngs`, `build-failure-artifact-htmls`, `click-failed-artifact-pngs` (these are all s3 resources) and `environment-openstack` (this is a resource-pool resource).

Example Image:
![image](https://cloud.githubusercontent.com/assets/7025605/25361786/e641f81e-2904-11e7-94aa-65b211cbe51f.png)

Example manifest snippets:
```
name: openstack-clean-install
    serial: true
    plan:
    - do:
      - aggregate:
        - get: installation
          passed:
          - pre-system-fan-in
          trigger: true
          params:
            depth: 200
          tags:
          - can-access-openstack
        - get: task-docker-image
          tags:
          - can-access-openstack
          attempts: 2
        - get: ops-manager-ci
          tags:
          - can-access-openstack
        - get: vm-image
          passed:
          - pre-system-fan-in
          resource: non-promoted-openstack-image-1.11
          tags:
          - can-access-openstack
          attempts: 2
        - get: current-example-product
          passed:
          - pre-system-fan-in
          resource: example-product-1.11
          tags:
          - can-access-openstack
          attempts: 2
        - put: environment
          resource: environment-openstack
          params:
            acquire: true
      - task: provision-environment
        privileged: true
        file: ops-manager-ci/concourse/tasks/shared/provision-clean-install-environment-with-vm-shepherd.yml
        params:
          IAAS: openstack
        image: task-docker-image
        tags:
        - can-access-openstack
      - task: clean-install-spec
        privileged: true
        file: ops-manager-ci/concourse/tasks/shared/run-clean-install-specs.yml
        params:
          IAAS: openstack
        image: task-docker-image
        tags:
        - can-access-openstack
        on_failure:
          aggregate:
          - put: build-failure-artifact-pngs
            params:
              file: failure-artifacts/capybara*\.png
          - put: build-failure-artifact-htmls
            params:
              file: failure-artifacts/capybara*\.html
          - put: click-failed-artifact-pngs
            params:
              file: failure-artifacts/click_failed_.*\.png
      ensure:
        put: environment-openstack
        params:
          release: environment
```

```
    name: build-failure-artifact-pngs
    type: s3
    source:
      access_key_id: <redacted>
      bucket: <redacted>
      region_name: us-west-1
      secret_access_key: <redacted>
      versioned_file: build-failure-artifact-png
      versioned_file: build-failure-artifact-png
```

Context: 
This used to happen occasionally to us. Then last weekend we (accidentally) deleted our entire concourse deployment and the redeployed it. We immediately started getting these errors ~90% of the time. I've tried restarting the baggage claim and (later) recreating all vsphere workers.

Logs: 

atc.stdout.log
it's full of these exact same looking errors
```
{"timestamp":"1493073261.862584829","source":"atc","message":"atc.container-keepaliver.volume.continuous-heartbeat.tick.failed-to-get-volume-size","log_level":2,"data":{"container":"63c3024d-2a1a-478c-46fc-6c0816e32e59","error":"Get http://10.150.0.2:36569/volumes/1caf112e-edca-4e93-7153-7f4f4ee4428d/stats: worker 10168a86-db52-4720-99f9-3aa551bea077 has not checked in recently","handle":"1caf112e-edca-4e93-7153-7f4f4ee4428d","session":"22.31.2.313","volume":"1caf112e-edca-4e93-7153-7f4f4ee4428d"}}
{"timestamp":"1493073261.870697498","source":"atc","message":"atc.syncer.ops-manager-on-stemcells-1.11:radar.scan.tick.init.volume.initial-heartbeat.failed-to-get-volume-size","log_level":2,"data":{"container":"1f4f5de2-6875-44aa-7cc0-b5d8637d42de","error":"failed to get volume stats","handle":"bc646f65-0b23-4e79-6c0d-c2990c3a9ef4","pipeline-scoped-name":"ops-manager-on-stemcells-1.11:resource:build-failure-artifact-htmls","session":"15.33.87.168.1.3.1","volume":"bc646f65-0b23-4e79-6c0d-c2990c3a9ef4"}}
```
atc.stderr.log
``` 
2017/04/24 21:46:08 http: TLS handshake error from 209.234.137.222:11071: EOF
2017/04/24 21:46:28 http2: server: error reading preface from client 209.234.137.222:53440: timeout waiting for client preface
2017/04/24 21:46:28 http2: server: error reading preface from client 209.234.137.222:25091: timeout waiting for client preface
2017/04/24 21:55:10 http2: server: error reading preface from client 209.234.137.222:21124: timeout waiting for client preface
2017/04/24 21:58:58 http2: server: error reading preface from client 209.234.137.222:9019: timeout waiting for client preface
...
2017/04/24 22:34:20 http2: server: error reading preface from client 209.234.137.222:22197: timeout waiting for client preface
```

baggageclaim.stdout.log
```
{"timestamp":"1493069292.115555286","source":"baggageclaim","message":"baggageclaim.repository.get-volume.failed-to-get-volume-stats","log_level":2,"data":{"error":"exit status 1","session":"3.4764","volume":"574aa2aa-7c9a-476e-646a-10938f7dfa31"}}
{"timestamp":"1493069292.816923380","source":"baggageclaim","message":"baggageclaim.driver.run-command.failed","log_level":2,"data":{"args":["qgroup","show","-F","--raw","/var/vcap/data/baggageclaim/volumes/live/f1d1bbb3-d7b9-4a80-4529-f1a5a180475b/volume"],"command":"/var/vcap/packages/btrfs_tools/sbin/btrfs","error":"exit status 1","session":"1.1240","stderr":"ERROR: can't perform the search - No such file or directory\nERROR: can't list qgroups: No such file or directory\n","stdout":""}}
{"timestamp":"1493069292.817001820","source":"baggageclaim","message":"baggageclaim.repository.get-volume.failed-to-get-volume-stats","log_level":2,"data":{"error":"exit status 1","session":"3.4771","volume":"f1d1bbb3-d7b9-4a80-4529-f1a5a180475b"}}
{"timestamp":"1493069292.819144726","source":"baggageclaim","message":"baggageclaim.driver.run-command.failed","log_level":2,"data":{"args":["qgroup","show","-F","--raw","/var/vcap/data/baggageclaim/volumes/live/4b8780c3-bb32-408b-72bf-70bb39b99628/volume"],"command":"/var/vcap/packages/btrfs_tools/sbin/btrfs","error":"exit status 1","session":"1.1241","stderr":"ERROR: can't perform the search - No such file or directory\nERROR: can't list qgroups: No such file or directory\n","stdout":""}}
{"timestamp":"1493069292.819265127","source":"baggageclaim","message":"baggageclaim.repository.get-volume.failed-to-get-volume-stats","log_level":2,"data":{"error":"exit status 1","session":"3.4772","volume":"4b8780c3-bb32-408b-72bf-70bb39b99628"}}
{"timestamp":"1493069547.373653650","source":"baggageclaim","message":"baggageclaim.api.volume-server.failed-stream-out-from-volume","log_level":2,"data":{"error":"write tcp 127.0.0.1:7788-\u003e127.0.0.1:45542: write: connection reset by peer","session":"4.1","src-path":"/var/vcap/data/baggageclaim/volumes/live/61c29011-763b-4c43-605f-dd98737013a2/volume","src-volume-handle":"61c29011-763b-4c43-605f-dd98737013a2"}}
{"timestamp":"1493069790.339649200","source":"baggageclaim","message":"baggageclaim.tick.reaping","log_level":1,"data":{"handle":"18b46a41-5929-4887-799c-4eb59c9cc5d9","session":"140","ttl":300}}
{"timestamp":"1493069790.378856421","source":"baggageclaim","message":"baggageclaim.repository.destroy-volume.destroyed","log_level":1,"data":{"session":"3.7878","volume":"18b46a41-5929-4887-799c-4eb59c9cc5d9"}}
{"timestamp":"1493069790.378936768","source":"baggageclaim","message":"baggageclaim.tick.reaping","log_level":1,"data":{"handle":"1e4d5668-b43d-4b6e-6f20-9c5a9dcdea24","session":"140","ttl":300}}
{"timestamp":"1493069790.454943419","source":"baggageclaim","message":"baggageclaim.repository.destroy-volume.destroyed","log_level":1,"data":{"session":"3.7879","volume":"1e4d5668-b43d-4b6e-6f20-9c5a9dcdea24"}}
...
{"timestamp":"1493070466.171462774","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.9741","volume":"4b8780c3-bb32-408b-72bf-70bb39b99628"}}
{"timestamp":"1493070466.172600985","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.9742","volume":"e2a03ec9-871f-48df-5116-104a22cc7330"}}
{"timestamp":"1493070466.176004410","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.9744","volume":"c9633c11-5391-4915-7b94-ae31ac18176b"}}
{"timestamp":"1493070466.191731691","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.9746","volume":"446f93e0-e5d7-470f-5286-e9dadb5661a6"}}
{"timestamp":"1493070466.214985609","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.9748","volume":"4220c092-1dca-47a1-5662-c7401d3e5757"}}
...
```

**Comment by ClaraFuPivotal** [comment]
This may be indicative of slow or flaky networking. `put` steps will receive all artifacts from the build, which can take a really long time if there are large artifacts living across the network.

To confirm or, in the short term, fix this issue you could shimmy in a `task` step which does nothing but replace the artifacts with empty volumes, e.g.:

```
    ensure:
      do:
      - task: shimmy
        config:
          platform: linux
          outputs:
          - name: task-docker-image
          # repeat one for each `get` or task `output`
          # be sure to *not* override `environment`, as the `put` step needs it
          run: {path: "true"}
      - put: environment-openstack
        params:
          release: environment
```

- @vito, @mariash & @ClaraFuPivotal
