### ISSUE TITLE
Disconnect display name of resource from internal name

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#103]
tldr: It should be possible to explicitly set the display name of a resource because I don't want to have to update a `task.yml` when updating a display name.

I used to have one resource:

```yaml
resources:
- name: goulash
  type: git
  source:
    branch: master
    private_key: {{github-private-key}}
    uri: git@github.com:pivotalservices/goulash.git
```

I now want to pull from `develop` to run tests and push to `master`, which means updating the resources:

```yaml
resources:
- name: goulash-develop
  type: git
  source:
    branch: develop
    private_key: {{github-private-key}}
    uri: git@github.com:pivotalservices/goulash.git
- name: goulash-master
  type: git
  source:
    branch: master
    private_key: {{github-private-key}}
    uri: git@github.com:pivotalservices/goulash.git
```

However, now my `task.yml` has to know about the name change as well:

```yaml
inputs:
- name: goulash-develop
  path: go/src/github.com/pivotalservices/goulash
```

I want them named as `goulash-develop` and `goulash-master` because that makes sense for me when I'm defining my pipeline and viewing it later. It doesn't make sense in the context of the `task.yml`.
