### ISSUE TITLE
docker-image resource changes image digest upon tagging

### ISSUE THREAD

**Issue by dcarastan** [concourse/concourse#1037]
# Bug Report
## What challenge are you facing?

Docker container tagging creates a new image digest. 

## A Modest Proposal

It is extremely difficult to debug a concourse resource code. Consider making the logging level configurable at resource level through a `log_level:` parameter.

# Bug Report

The following code pulls the right image digest for the tag in the get action and creates a new image digest during the put. 

```
- name: tag-test
  serial: true
  plan:
    - aggregate:
      - get: version-src
      - get: test-image
        params: {save: true}
    - put: test-image
      params: {load: test-image, load_base: test-image, tag: version-src/tags/doru}

  - name: tag-image
    type: docker-image
    source:
      repository: gcr.io/example/test
      tag: fresh_build
      username: {{user}}
      password: {{token}}
...
```
- get pulls _test_ digest _sha256:9308ba9792c8accdb4859b009decc7b2557fe388abff118cad04be9f8abced6c_. 
- put writes and pulls _test_ digest _sha256:904a9e346ab0f12c477e9c6d076920c7d6c612a8935564076dd254e74a4a3481_.

Above results can be consistently reproduced 100% of the time. Hijacking the build reveals that the put step was initiated with the right digest:
```
# cat test-image/digest 
sha256:9308ba9792c8accdb4859b009decc7b2557fe388abff118cad04be9f8abced6c
```

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: GCP
* Browser (if applicable): n/a
* Did this used to work? unknown
