### ISSUE TITLE
Difficulty ensuring that Tasks run inside the correct context 

### ISSUE THREAD

**Issue by blt** [concourse/concourse#1041]
Hi folks! 

I apologize that this Issue doesn't fit into the Feature Request / Bug matrix suggested. It's more of a question and I hope this is the correct venue for questions. 

Consider the following pipeline: 

```yaml
---
resources:
  - name: cernan
    type: git
    source:
      uri: git@github.com:postmates/cernan.git
      access_token: {{github-access-token}}
      private_key: {{github-private-key}}
      branch: master
  - name: cernan-test-image
    type: docker-image
    source:
      repository: postmates/cernan-test

jobs:
  - name: cernan-master-stable-test-img
    plan:
      - get: cernan
        trigger: true
      - task: master-test-tag
        config:
          image_resource:
            type: docker-image
            source:
              repository: concourse/git-resource
          platform: linux
          inputs:
            - name: cernan
          outputs:
            - name: tag
          run:
            path: bash
            args:
              - -c
              - |
                set -eux
                pushd cernan
                  git rev-parse --short HEAD > ../tag/name
                popd
      - put: cernan-test-image
        params:
          build: cernan
          tag_prefix: "stable-"
          tag: tag/name
          dockerfile: cernan/docker/test/Dockerfile
          build_args:
            channel: stable

  - name: master-stable-test
    plan:
      - get: cernan-test-image
        passed:
          - cernan-master-stable-test-img
        trigger: true
      - get: cernan
      - task: cargo_test
        image: cernan-test-image
        config:
          platform: linux
          inputs:
            - name: cernan
          run:
            dir: cernan
            path: sh
            args:
              - -exc
              - |
                cargo test
```

For every commit to the `master` branch of [cernan](https://github.com/postmates/cernan) this pipeline builds a test image using [this dockerfile](https://github.com/postmates/cernan/blob/master/docker/test/Dockerfile) and the executes the cernan tests. What we've observed is that if two commits are made very rapidly to `master` with substantive differences between the test Dockerfile it's possible for builds to fail. Say we have two commits:

* e2cfc89fae5b43594b2c649fd4c05bcc6d2d12ac
* 56a8b4c50d4269dc3f88727472933fd81231f63b

What we'd hope to see are pipeline runs like the following:

                   |-----------------------------------------------|
                   |                                               \/
    cernan[e2cfc89f] -> cernan-master-stable-test-img[e2cfc89f] -> master-stable-test[e2cfc89f]

                   |-----------------------------------------------|
                   |                                               \/
    cernan[56a8b4c5] -> cernan-master-stable-test-img[56a8b4c5] -> master-stable-test[56a8b4c5]

That is, for master e2cfc89f we build an image from the repo at that SHA then, in that same image, execute the tests present in e2cfc89f. Similarly for 56a8b4c5. Say that 56a8b4c5 is slower to build. Because the `get` we have for the build image uses the [documented default](https://concourse.ci/get-step.html#get-version) of `version: latest` what we've found is that we'll see pipeline executions like so:

                   |-----------------------------------------------|
                   |                                               \/
    cernan[e2cfc89f] -> cernan-master-stable-test-img[56a8b4c5] -> master-stable-test[e2cfc89f]

                   |-----------------------------------------------|
                   |                                               \/
    cernan[56a8b4c5] -> cernan-master-stable-test-img[56a8b4c5] -> master-stable-test[56a8b4c5]

That is, the tests for e2cfc89f run on the image for 56a8b4c5. The version documentation says that we can set an explicit version like `{ref: abcdef123}` but it's not clear how this could be used to ensure that `master-stable-test` stays pegged to the correct SHA image. It seems as well that the `cernan -> cernan-master-stable-test-img -> master-stable-test` could be declared as a [serial group](https://concourse.ci/configuring-jobs.html#serial_groups) but this seems like an anti-pattern. Ideally the pipelines should be able to run in parallel as their resources are not overlapping. This is especially true if the frequency of commits to master is high or as the duration of the tests increase. 

Is there a way to conceptually thread the SHA through to `master-stable-test` so that it runs on the correct `cernan-master-stable-test-img` without forcing the pipelines to run in serial? 

/cc @benley @blakebarnett @tsantero
