### ISSUE TITLE
Notification resources clutter up pipeline UI

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1052]
# Feature Request

## What challenge are you facing?

Configuring a Slack notification resource or other similar resources that "augment" the pipeline is verbose and clutters up the pipeline UI with resources that don't actually influence pipeline semantics.

## A Modest Proposal

We should find a pattern for using these resources that reduces the amount of copy/paste pipeline code, and also allows us to express them more meaningfully (or just hide them) from the pipeline UI.

The initial focus of this is in the Slack notification resource, and other fire-and-forget resources that have no bearing to the build plan they're tacked on to.

Maybe we could support something like this:

```yaml
decorators:
- name: slack-notify
  on_success: 
    put: slack
    params:
      channel: '#team'
      text: |
        [$BUILD_PIPELINE_NAME/BUILD_JOB_NAME #$BUILD_NAME]($ATC_EXTERNAL_URL/builds/$BUILD_ID) succeeded!

  on_failure:
    put: slack
    params:
      channel: '#team'
      text: |
        [$BUILD_PIPELINE_NAME/BUILD_JOB_NAME #$BUILD_NAME]($ATC_EXTERNAL_URL/builds/$BUILD_ID) failed. :'(

jobs:
- name: job-a
  decorators: [slack-notify]
  plan: [...]

- name: job-b
  decorators: [slack-notify]
  plan: [...]
```
