### ISSUE TITLE
Can't abort-build for jobs that no longer exist in the pipeline

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1055]
If a pipeline has a stuck job, then that pipeline gets re-set but without that same job and without canceling the build where the job was stuck. I can still see the stuck job with `fly builds` (v 2.7.3) , but when I try to do `fly abort-build` I get:
```error: Unexpected Response
Status: 500 Internal Server Error
Body:
```
If I navigate to the UI at `.../builds/[build id of the stuck job]` then I can still use the UI to abort the stuck job. 

Other fly subcommands (e.g. hijack) have the ability to specify the build id without specifying the pipeline/job, abort-build is apparently not one of these.

A test pipeline that can easily reproduce this by setting and starting a build, then removing the stuck-job, resetting the pipeline, then trying to cancel the last build with fly:
```
---
jobs:
  - name: stuck-job
    plan:
      - task: infinite-loop
        config:
          platform: linux
          run:
            path: /bin/sh
            args:
              - "-c"
              - "while true; do sleep 2; done"
  - name: finished-job
    plan:
      - task: finish-zero
        config:
          platform: linux
          run:
            path: /bin/sh
            args:
              - "-c"
              - "exit 0" 
```

---
Moved from concourse/fly#166
/cc @kmacoskey
