### ISSUE TITLE
Fly execute with -j doesn't support input_mappings

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1062]
If I have a "generic" task set up with input mappings I can't easily run it with `fly execute` and also give it inputs from a previous job.

For instance this is the section of my build plan:

```
- name: update-dockerfiles
  plan:
  - get: my-project
  - get: common-image
    passed: [common-image-build]
    trigger: true
  - task: update-dockerfiles
    file: utils/task-update-dockerfiles.yml
    input_mapping:
      repo: my-project
      dockerimage: common-image
```

There is a previous build job that does put on the docker-image resource to build it. Since the inputs to my task don't share the name with the outputs there is no way for me to run this task without pushing a commit and triggering it somehow.

---
Moved from concourse/fly#152
/cc @ashb
