### ISSUE TITLE
`fly execute ...` panics when setting the output directory for a task with no outputs

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1086]
We're setting up a new task in our pipeline which _will_ have an output but _currently doesn't_. For one-off testing, we have been using a command like:
`fly -t foo execute --config=task.yml --input=source=. --output=artifact=./tmp`

This succeeds when `--output` is not specified (although task.yml does specify an output with the same name). But with it, most of the way through our command's output in the terminal, we get:

```
panic: unexpected EOF

goroutine 36 [running]:
github.com/concourse/fly/commands/internal/executehelpers.Download(0x7fff5fbffbac, 0x5, 0x820a8c240, 0x35, 0x820a747e0, 0x24, 0x820a437a0)
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:45 +0x6de
...
```

Clearly this was user error, but a meaningful error message would be great here.

---
Moved from concourse/fly#51
/cc @alidaka @mandyozhao

**Comment by dumbbell** [comment]
Hi!

We hit the same issue, using Concourse 3.4.1.

Here is the (generated) tasks:
```yaml
platform: linux
inputs:
  - name: rabbitmq_shovel
  - name: amqp_client
  - name: ci
  - name: cth_fail_fast
  - name: cth_styledout
  - name: proper
  - name: rabbit
  - name: rabbit_common
  - name: rabbitmq_codegen
  - name: rabbitmq_ct_client_helpers
  - name: rabbitmq_ct_helpers
  - name: ranch
outputs:
  - name: test-output
image_resource:
  type: docker-image
  source:
    repository: pivotalrabbitmq/rabbitmq-server-buildenv
    tag: linux-erlang-R16B03
run:
  path: ci/server-release/scripts/test-erlang-app.sh
  args:
    - rabbitmq_shovel
params:
  V: "0"
  MAKE_TARGET: "ct"
```

And the `fly execute` command line:
```
fly -t ci-aws execute \
	--config "/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbitmq_shovel/.erlang.mk/concourse-task.yaml" \
	--input="rabbitmq_shovel=." \
        --input="amqp_client=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/amqp_client" \
        --input="ci=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/ci" \
        --input="cth_fail_fast=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/cth_fail_fast" \
        --input="cth_styledout=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/cth_styledout" \
        --input="proper=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/proper" \
        --input="rabbit=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbit" \
        --input="rabbit_common=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbit_common" \
        --input="rabbitmq_codegen=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbitmq_codegen" \
        --input="rabbitmq_ct_client_helpers=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbitmq_ct_client_helpers" \
        --input="rabbitmq_ct_helpers=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbitmq_ct_helpers" \
        --input="ranch=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/ranch" \
	--output="test-output=/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbitmq_shovel/logs/on-concourse"
```

The `test-output` directory is filled by the task script with many files and directories (they are the logs of a testsuite). The local directory (`.../logs/on-concourse`) is created before running fly(1).

The command fails in the middle of the execution (differently each time) with the following output:
```
(...)
----------------------------------------------------
2017-10-02 10:38:07.233
+ /tmp/build/e55deab7/rabbit/scripts/rabbitmq-plugins (pid <0.152.0>)

panic: tar extract failed (unexpected EOF). output: ""

goroutine 29 [running]:
github.com/concourse/fly/commands/internal/executehelpers.Download(0xcfd940, 0xc4201d98a0, 0x7fffffffdd13, 0xb, 0x7fffffffdd1f, 0x5f, 0xc4200932c0, 0x24, 0xc4203c42d0, 0x4d, ...)
	/wrkdirs/usr/ports/net/concourse-fly/work/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x271
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xcfd940, 0xc4201d98a0, 0x7fffffffdd13, 0xb, 0x7fffffffdd1f, 0x5f, 0xc4200932c0, 0x24, 0xc4203c42d0, 0x4d, ...)
	/wrkdirs/usr/ports/net/concourse-fly/work/src/github.com/concourse/fly/commands/execute.go:126 +0x7d
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
	/wrkdirs/usr/ports/net/concourse-fly/work/src/github.com/concourse/fly/commands/execute.go:124 +0x957
gmake: *** [/home/dumbbell/Projects/pivotal/rabbitmq-public-umbrella/deps/rabbit_common/mk/rabbitmq-test.mk:73: ct-on-concourse] Error 2
```

If this is a user error, what should we do instead?

**Comment by wagdav** [comment]
Hello @chendrix  and @jama22 !

@marco-m and I wanted to provide a PR for this issue, but we didn't manage to reproduce it.

We started with the following task configuration:

```
# task.yml
platform: linux

image_resource:
  type: registry-image
  source:
    repository: busybox

inputs:
  - name: source

outputs:
  - name: artifact

run:
  path: echo
  args:
    - hello world
```

This task has both inputs and outputs.

We tried to run the following commands:
```
fly -t dev execute -c task.yml
error: missing required input `source`  # OK, as expected

fly -t dev execute -c task.yml  --input=source=. 
# the task finishes successfully.

fly -t dev execute -c task.yml  --input=source=.  --output=artifact=./tmp
# the task finishes successfully and the ./tmp directory is created
```

We also modified the task to put some files in the artifact directory. The file is correctly streamed back to the specified local directory.

We suggest this issue to be closed.
