### ISSUE TITLE
A job without `trigger: true` on an input shouldn't show as pending

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#109]
This is related to https://github.com/concourse/concourse/issues/107, in that pending isn't always pending.

If I have a pipeline configured with a job:

```yml
jobs:
- name: deploy
  plan:
  - get: goulash-master
    passed:
    - unit
  - put: staging
    params:
      manifest: goulash-master/manifests/staging.yml
      path: goulash-master
```

The job appears as pending but it won't actually run because `trigger: true` is missing from the plan. It would help me to know when something isn't actually pending by drawing a different kind of line to the job with the non-triggered input to show that it won't actually run, or to just mark the entire rest of the pipeline as in non-pending stasis because it isn't pending--it's frozen.
