### ISSUE TITLE
Fly Execute fails with gzip: invalid magic

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1095]
I am with the Diego development team and when we try to execute our inigo tests remotely from several machines we quite regularly (especially from my machine in Canada) get the following error when doing the upload step in the fly execute ...

```
executing build 150754
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0
curl: (18) transfer closed with outstanding read data remaining
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
100 42.1M    0 42.1M    0     0   303k      0 --:--:--  0:02:22 --:--:--  206k
failed

upload request failed: Put https://diego.ci.cf-app.com/api/v1/pipes/3df3e884-3b6c-40ba-6800-e04b061e2fc5: EOF
```

The run-inigo script we use is as follows ...

```
#!/bin/bash

set -e

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

echo "checking code for compilation errors..."

pushd $DIEGO_RELEASE_DIR/src/code.cloudfoundry.org/inigo > /dev/null
  for pkg in `find . -maxdepth 1 -type d ! -path . -not -path '*/\.*'`; do
    echo $pkg
    go test -c ./${pkg} > /dev/null
  done
popd > /dev/null

echo "compilation done"

if [ -n "${DIEGO_CI_TARGET}" ]; then
  target="-t ${DIEGO_CI_TARGET}"
else
  target="-t local"
fi

if [ -z "${USE_GARDEN_RUNC}" ]; then
  fly ${target} execute -p -x \
    -c $DIEGO_RELEASE_DIR/scripts/ci/run_inigo_glinux.build.yml \
    -i diego-release=$PWD \
    -i garden-linux-release=$HOME/workspace/garden-linux-release \
    -- "$@"
else
  fly ${target} execute -p -x \
    -c $DIEGO_RELEASE_DIR/scripts/ci/run_inigo_grunc.build.yml \
    -i diego-release=$PWD \
    -i garden-runc-release=$HOME/workspace/garden-runc-release \
    -- "$@"
fi
```

The run_inigo_grunc.build.yml is as follows:

```

platform: linux

image: docker:///cloudfoundry/inigo-ci

inputs:
- name: diego-release
- name: garden-runc-release

params:
  GINKGO_PARALLEL: "true" # we check for the literal string "true" in the run_inigo script
  DEFAULT_EVENTUALLY_TIMEOUT:
  INIGO_REPEAT_COUNT: 1
  SKIP_PACKAGES:
  SKIP_REGEX:
  USE_SQL:
  USE_GARDEN_RUNC: "true"

run:
  path: diego-release/scripts/ci/run_inigo
```

This does seem to occur mostly from my slower upload connection but we have also seen this happen from machines in the Pivotal SF office.

---
Moved from concourse/fly#102
/cc @andrew-edgar @vito
