### ISSUE TITLE
fly execute --inputs-from does not support custom resource types

### ISSUE THREAD

**Issue by talset** [concourse/concourse#1148]
Hi there!

# Bug Report

I tried to use ```fly execute --inputs-from ```.

Here is a part of my pipeline jobs definition
```
  - name: extract-data
    plan:
      - get: vault
        params:
          paths:
            - secret/foo
        outputs:
          - name: vault
      - task: extract-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: radial/busyboxplus
              tag: latest
          inputs:
          - name: vault
          run:
            path: /bin/sh
            args:
            - -c
            - |
              ls .
```

Here is my vault resource definition

```
- name: vault
  type: vault
  source:
    url: https://vault.foo.io
    expose_token: true
    role_id: foo
    secret_id: bar
    auth_method: AppRole
    paths:
      - secret/foo
```

If I run my pipeline from concourse UI it works perfectly.

So I created a builder.yml containing my task to execute with fly

```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: radial/busyboxplus
    tag: latest

inputs:
- name: vault

run:
  path: /bin/sh
  args:
  - -c
  - |
    ls .
```

How I execute this builder.yml

```
fly -t test execute --config builder.yml --inputs-from mypipeline/extract-data
executing build 8067
no workers satisfying: resource type 'vault'

available workers: 
  - platform 'linux'
  - platform 'linux', tag 'demo'
  - platform 'linux'
errored
```

As you can see "no workers satisfying: resource type 'vault'".
To validate my work, I created a s3 resource on the same way and it works. Any idea why I am not able to use vault resource ?

* Concourse version: 2.7.4
* Deployment type: docker
