### ISSUE TITLE
Verify in fly that all jobs are visible in the UI

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1150]
# Feature Request

## What challenge are you facing?

If you have no groups, then all jobs in your pipeline are always visible.

If you have any groups, and forget to put a job in a group, that job will still exist in your pipeline, but there will be no way to see it leading to some potentially dangerous situations.

## A Modest Proposal

We should verify in `fly set-pipeline` that no job will be invisible (i.e. no un-grouped jobs)

**Comment by jama-pivotal** [comment]
Tried with a sample pipeline:

```
groups:
- name: tests
  jobs:
  - hello-world

jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]

- name: hello-world2d
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
```

...and got error message

```
error: invalid configuration:
invalid groups:
	job 'hello-world2d' belongs to no group
```

Accepting!
