### ISSUE TITLE
Allow unknown/extra keys for anchors/aliases

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#116]
Use case: **Extracting common configurations/tasks into anchors & aliases**

We wanted our pipeline yaml file to look like

``` yaml
do-that-thing: &do-that-thing
  task: do-that-thing
  file: my-repo/ci/scripts/do-that-thing

jobs:
- name: do-that-thing-over-here
  plan:
  - *do-that-thing
- name: do-that-thing-over-there
  plan:
  - *do-that-thing
```

When you fly configure, it parses correctly, but when it attempts to configure, gives you errors

```
failed to update configuration.
  response code: 400 Bad Request
  response body:
    unknown/extra keys:
      - do-that-thing
```

cc @robdimsdale
