### ISSUE TITLE
Docker image down and upload takes "forever"

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1170]
# Bug Report

* Concourse version: 3.0.0
* Deployment type (BOSH/Docker/binary): Docker (both worker and atc)
* Infrastructure/IaaS: CoreOS (ATC) + Fedora(worker)

The followin setup maxes out 25mbit/s downstream and 2mbit/s upstream for almost an hour before this container completes. This equals 11 GB (!!, makes no sense at all) of data transfer in 900 MB up (makes sense)

```
resources:
- name: continuous-integration
  type: git
  source:
    branch: master
    uri: https://github.com/ratpoison-io/continuous-integration.git

- name: container
  type: docker-image
  source:
    repository: quay.io/ratpoison/machine-learning-container
    username: {{quay-username}}
    password: {{quay-password}}

jobs:
  - name: build-container
    serial: true
    public: true
    plan:
      - get: continuous-integration
        trigger: true
      - put: container
        params:
          cache: true
          tag_as_latest: true
          build: continuous-integration/container
```
