### ISSUE TITLE
Large amount of logs from scanning s3 resource

### ISSUE THREAD

**Issue by jfmyers9** [concourse/concourse#1174]
# Bug Report
* Concourse version: 3.0.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): N/A
* Did this used to work?
Yes?

```
web/07638cad-07ab-46e8-a52f-0ee3ff75989d:/var/vcap/sys/log/atc# grep "atc.syncer.main:radar.scan-resource.tick.versions-found" atc.stdout.log > file
web/07638cad-07ab-46e8-a52f-0ee3ff75989d:/var/vcap/sys/log/atc# ls -larth
total 95M
drwxr-x--- 5 root vcap 4.0K May 16 06:01 ..
-rw-r--r-- 1 vcap vcap 4.6M May 16 13:59 atc.stdout.log.4.gz
-rw-r--r-- 1 vcap vcap 4.7M May 16 22:29 atc.stdout.log.3.gz
-rw-r--r-- 1 vcap vcap 4.7M May 17 06:59 atc.stdout.log.2.gz
-rw-r--r-- 1 vcap vcap 4.6M May 17 15:14 atc.stdout.log.1.gz
drwxr-xr-x 2 vcap vcap 4.0K May 17 15:15 .
-rw-r--r-- 1 vcap vcap  12K May 17 20:39 atc.stderr.log
-rw-r--r-- 1 root root  38M May 17 21:25 file
-rw-r--r-- 1 vcap vcap  39M May 17 21:25 atc.stdout.log
````
This single log line `atc.syncer.main:radar.scan-resource.tick.versions-found` is taking up the vast majority of the logs on the atc and is causing log rotation to occur very quickly. As seen above, in a 39M log file, this log line accounts for 39M.

The resources that are showing this problem are s3 resources. Here is an example s3 configuration:
```
- name: diego-trace-time-rotor-benchmark-logs
  type: s3
  source:
    bucket: diego-trace-logs
    regexp: time-rotor-benchmarks/benchmark-bbs\.(0\.0\.0)\.[\d\.\-]+.tgz
    access_key_id: REDACTED
    secret_access_key: REDACTED
```

The log line appears to have the entirety of the s3 bucket in it's lager data.
