### ISSUE TITLE
cannot rename resource type using custom resource type

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1178]
# Bug Report

```
resource_types:
- name: docker-image
  type: docker-image
  source:
    repository: concourse/docker-image-resource
    tag: docker-1.12.6

resources:
- name: alpine
  type: docker-image
  source:
    repository: alpine

jobs:
- name: foo
  plan:
  - get: alpine
```

This was the workaround we told people to use in concourse/docker-image-resource#101

It doesn't work, it hangs on "finding new versions" and the logs show

```
{"timestamp":"1495128898.151854992","source":"atc","message":"atc.syncer.foo:radar.scan-resource-type.lock.failed-to-get-lock","log_level":2,"data":{"error":"custom resource type 'docker-image' version not found","pipeline-scoped-name":"foo:resource-type:docker-image","resource-type":"docker-image","session":"17.147.1.1"}}
```

* Concourse version: 3.0.1

**Comment by chendrix** [comment]
If you need a workaround in the meantime, if you don't rename an existing base resource type, it works.

```
resource_types:
- name: docker-image-2
  type: docker-image
  source:
    repository: concourse/docker-image-resource
    tag: docker-1.12.6

resources:
- name: alpine
  type: docker-image-2
  source:
    repository: alpine

jobs:
- name: foo
  plan:
  - get: alpine
```

**Comment by emcniece** [comment]
This _did_ get merged, right? I started experiencing this problem after a 3.0.1 upgrade, now I'm at 3.1.1 and it's still happening :(

**Comment by chendrix** [comment]
There's a regression. We're aware of it. It's highly prioritized.

**Comment by emcniece** [comment]
Wow, @chendrix - I just fixed my pipeline after doing an upgrade to 3.2.0. Turns out I didn't have any issues with resources - just a duplicate `resource_types:` declaration.

```yml
resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: simple-s3
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
```

Slack notifications were working fine, but the pull-request and S3 resources were failing with the exact error you shared in the first comment. The dumb, it hurts...

**Comment by mariash** [comment]
@emcniece cool thanks for update!

**Comment by gabro** [comment]
Ah, my bad. The image I'm using was private by mistake. Making it public solved it.

**Comment by robbruce** [comment]
I'm getting this when using a private docker repository, on version 3.4.1

```yaml
---
resource_types:
  - name: concourse-git-resource
    type: docker-image
    source:
      repository: nexus.myinternaldomain.internal:8445/mycompany/concourse-git-resource
      insecure_registries:
        - nexus.myinternaldomain.internal:8445
      username: {{nexus_user}}
      password: {{nexus_pass}}
      tag: latest
```

No duplicate resource_types.

Results in the error _custom resource type 'concourse-git-resource' version not found_

This is taken from a working setup on 2.6.0 and checking if we can upgrade to 3.4.1, deployed next to our 2.6.0 setup with same network connectivity etc.

**Comment by chrinor2002** [comment]
I was seeing this error when _not_ using the `text` param. Example:

```
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack
  type: slack-notification
  source:
    url: ...

jobs:
- name: slack-test
  plan:
  - put: slack
    params:
      channel: {{slack_notification_channel}}
      always_notify: true
      text_file: some-input.txt
```

By re-adding the `text` param using `$TEXT_FILE_CONTENT` this error went away for me.

```
...
jobs:
- name: slack-test
  plan:
  - put: slack
    params:
      channel: {{slack_notification_channel}}
      always_notify: true
      text_file: some-input.txt
      text: "$TEXT_FILE_CONTENT"
```

**Comment by devdavidkarlsson** [comment]
🛑  custom resource type 'npm_cache' version not found

Seeing this as well for my setup with a private docker registry that is populated from another pipeline:

resource_types:
# https://github.com/ymedlop-sandbox/npm-cache-resource
- name: npm_cache
  type: docker-image
  source:
    repository: {{docker-registry-npm-cache}}
    insecure_registries:
    - {{docker-registry}}

Removing and adding the pipeline does not help... Pruneing everything from the database might help, but it's rather drastic...

**Comment by Sispheor** [comment]
same here
```yml
resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest
```

Output:
```
custom resource type 'rsync-resource' version not found
```
