### ISSUE TITLE
task.config.image isn't working for me

### ISSUE THREAD

**Issue by markalanrichards** [concourse/concourse#1188]
# Bug Report

Bug reports are pretty free-form; just replace this with whatever. If applicable, though, please include steps to reproduce. Help us help you!

The following can also be handy:

* Concourse version: v3.0.1
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: Ubuntu 16:04 vm, docker-compose up
* Browser (if applicable): Firefox
* Did this used to work? Yes

I have a docker image:
```
- name: pipeline-worker
  type: docker-image
  source:
    repository: "192.168.56.101:5000/pipeline-worker"
    insecure_registries: ["192.168.56.101:5000"]
```

If I build this and use an image_resource in a task it works.

But I want to use image as I like this feature and it saves me repeating myself, so I try the following and it doesn't work.
```
- name: hello-world
  plan:
  - get: pipeline-worker
  - task: say-hello
    config:
      platform: linux
      image: pipeline-worker
      run:
        path: echo
        args: ["Hello, world!"]

```
I get an error `volume graph is disabled`
I've used this before (maybe 2.7.0 in an old project) where it worked.
