### ISSUE TITLE
I should be able to control which artifacts a `put` receives

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1202]
In a build with many `get`s, `put`s, and/or `tasks`, even the simplest `put` can sometimes take a long time, as it may need to stream all the artifacts preceding it.

A simple fix would be having the ability to list the inputs a `put` actually needs. This should be backwards-compatible, and if omitted all artifacts should propagate to it, as it does today.

**Comment by clarafu** [comment]
After discussing with @vito , we decided that we will add a new configuration to the put step in the pipeline config where you can specify which artifacts (a task output or a resource) will be taken as an input to the put. 
```
- get: repo
- put: some-resource
  inputs: [repo]
  params:
    repository: some/repo
```

There will also be an option for specifying all artifacts as inputs to the put with an "all" option.
```
- get: repo
- put: some-resource
  inputs: all
  params:
    repository: some/repo
```
