### ISSUE TITLE
`fly execute` does not work, when only tagged workers are available

### ISSUE THREAD

**Issue by friegger** [concourse/concourse#1208]
Re-opened from concourse/archive-resource#7

Still getting `no workers satisfying: resource type 'archive'`, if only tagged workers are available. Tested with fly `3.0.1` with `--tag=<worker-tag>`.

**Comment by chendrix** [comment]
@friegger are your tagged workers all windows/macOS binaries?

Can you describe a bit of how your concourse deployment looks?

**Comment by friegger** [comment]
We have multiple infrastructures. Concourse itself, i.e. the web and db instance_groups, are running on one infrastructure without any workers. Then we have other infrastructures, where only tagged workers are running. Concourse and the workers are deployed with BOSH and run on a current ubuntu stemcell.
We have now deployed a single untagged worker on one of the infrastructures as a workaround.

**Comment by ls-avanier** [comment]
I also just encountered that bug. We're running our `web` service in GKE on a container, while our `worker` instances are running in GCE on CoreOS. With only tagged workers, I get

```plaintext
no workers satisfying: resource type 'git'

available workers: 
  - platform 'linux', tag 'coreos', tag 'gce'
```

Not only am I unable to `fly -t [target] e`, no containers will get scheduled at all.

With all workers with no tags, all is good. I haven't tried mixed workers, tags and no tags.

We're running Concourse `3.5.0` on linux.

I believe this may be handled by [#130691187](https://www.pivotaltracker.com/story/show/130691187)

**Comment by avanier** [comment]
I also just encountered that bug. We're running our `web` service in GKE on a container, while our `worker` instances are running in GCE on CoreOS. With only tagged workers, trying `fly e`, I get :

```plaintext
no workers satisfying: resource type 'git'

available workers: 
  - platform 'linux', tag 'coreos', tag 'gce'
```

Not only am I unable to `fly -t [target] e`, no containers will get scheduled at all.

With all workers with no tags, all is good. I haven't tried mixed workers, tags and no tags.

We're running Concourse `3.5.0` on linux.

I believe this might get addressed by [#130691187](https://www.pivotaltracker.com/story/show/130691187).

**Comment by xtremerui** [comment]
@friegger @avanier is this still an issue for you? I could not reproduce this with latest concourse.
How I tested:

1. spin up a concourse with one worker tagged as `test`
2. Set a pipeline with test.yml
```
---
resources:
  - name: my-app
    type: git
    tags: [test]
    source:
      uri: http://192.168.1.18:1313/test.git
jobs:
  - name: test
    plan:
    - get: my-app
      tags: [test]
    - task: run
      tags: [test]
      file: my-app/task.yml
```

task.yml
```
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: busybox

inputs:
- name: my-app

run:
  path: my-app/test
```

3. run the job in UI making sure it is working
4. ` fly -t dev execute -c dev-git-repos/test/task.yml -j test/test` returns the error you have seen.
5. ` fly -t dev execute -c dev-git-repos/test/task.yml -j test/test --tag=test` returns
```
executing build 6 at http://localhost:8080/teams/main/pipelines/test/builds/2
initializing
running my-app/test
my-app
succeeded
```

I would close this issue for now. Feel free to open new one if you still encounter such problem.
