### ISSUE TITLE
Include inputs/outputs in fly validate-pipeline

### ISSUE THREAD

**Issue by dmlemos** [concourse/concourse#1213]
# A Modest Proposal

When inputs/outputs are out of place, `fly validate-pipeline` should give a warning.

Given pipeline definition:
```yaml
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/concourse/bin.git

jobs:
- name: test
  plan:
  - get: repo
    trigger: false
    params:
      depth: 1
      submodules: none
      disable_git_lfs: true

  - task: hello-world
    inputs:
    - name: repo

    outputs:
    - name: files

    config:
      platform: darwin
      run:
        dir: repo
        path: /bin/sh
        args:
        - -euc
        - |
          mkdir files
          echo "file1" > files/file1
```

Both `inputs` and `outputs` must be inside `config` block :trollface:

Fly doesn't complain: :umbrella:
```shell
$ fly validate-pipeline -c x.yml
looks good
```

Thanks to @clarafu for helping out on the slack channel
