### ISSUE TITLE
Allow for "soft triggering"

### ISSUE THREAD

**Issue by mschirmacher** [concourse/concourse#1214]
# Feature Request

## What challenge are you facing?

Consider a pipeline with a single git resource like:
```
- name: source
  type: git
  source:
    ignore_paths: [.version]
```
Then we have a job with the step: 
```
- get: source
  trigger: true
```

Later on the job would build an artifact for the version contained in `.version` uploads the artifact somewhere, increase the number contained in `.version` etc.
So far so good. You push your code changes pipeline is triggere. Works.

But now consider this scenario: `.version` contains `1.0.0` the job is startet. The build passes the artifact is created, now `.version` contains `1.0.1` building the artifact passes, the artifact is uploaded and then... *bam* something bad happens the job is red. You trigger the job again but now the job fails even much earlier, becase you alread build `1.0.1`. No problem, just write `1.0.2` into the file and we can build it! We push the button and... *bam* still red, because you already built `1.0.1`. Wait what? `1.0.1`? But we have `1.0.2` in `.version`! Yeah, but we have an `ignore_path` item configured for `.version` - too bad this feature works excactly like documented!

## A Modest Proposal

I think this is pretty much connected to https://github.com/concourse/concourse/issues/1176
git change sets containing changes only for ignored paths should not trigger a build, but still it might make sense to consider this changes if we trigger the build manually

**Comment by mindscratch** [comment]
I'm using "paths" in my git resource so I only clone when changes are made, however, I noticed that concourse is "using version of resource found in cache" (but that version is a few commits behind).

I have a resource, setup like so:

```
- name: python-source
  type: git
  source:
    uri: {{git_uri}}
    branch: {{git_branch}}
    private_key: {{private_key}}
    paths: ["python/**/*.*"]
```

I'd like some way to force Concourse to clone again, aka clear its cache.
