### ISSUE TITLE
When doing a `fly configure`, if the only change is the order of nodes, nothing is show in the "has changed" output

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#122]
For example, if my pipeline.yml is:

```
groups:
- name: secondary-group
  jobs:
  - secondary-job

- name: primary-group
  jobs:
  - primary-job
```

and I want the primary group to show first in the group listing, I want to change my pipeline.yml to:

```
groups:
- name: primary-group
  jobs:
  - primary-job

- name: secondary-group
  jobs:
  - secondary-job
```

This succeeds (and correctly reorders the groups on the website), but the output from doing a `fly configure` is:

```
apply configuration? (y/n): y
configuration updated
```

I would expect to see something like:

```
groups have changed:
 groups:
-- name: secondary-group
-  jobs:
-  - secondary-job
-
 - name: primary-group
   jobs:
   - primary-job

+- name: secondary-group
+  jobs:
+  - secondary-job
+

apply configuration? (y/n): y
configuration updated
```
