### ISSUE TITLE
Pipeline mechanics should be aware of resource configs

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1256]
# Feature Request
Some mechanics of pipelines can wind up being super inefficient and make **poor life choices** about how to deal with resources, due to the new global resource configs.

## What challenge are you facing?
If a user for some reason configures a bunch of custom resource types with the same underlying base resource + config. It takes a long time to check for new versions of the custom resource, since there is a lock around the resource config check; so it waits for the checking lock and runs redundant checks for new versions of each custom resource type.

## A Modest Proposal
We should look for improvements in Radar, and internally in pipelines that share resource configs with other pipelines

eg. in Radar, we could deal with the case of a pipeline with a bunch of recurring resource configs by accounting for the pre-exising checks for the exact same underlying config, rather than redundantly repeating.

eg. for pipelines; a pipeline that uses a resource that is configured the same as an existing pipeline's resource config, and the existing pipeline has some versions of the resource; the new pipeline could inherit the existing version history.

# Example pipeline
```
resource_types:
- name: git-resource-dupe-1
  type: docker-image
  source:
    repository: concourse/git-resource

- name: git-resource-dupe-2
  type: docker-image
  source:
    repository: concourse/git-resource

- name: git-resource-dupe-3
  type: docker-image
  source:
    repository: concourse/git-resource

- name: git-resource-dupe-4
  type: docker-image
  source:
    repository: concourse/git-resource

- name: git-resource-dupe-5
  type: docker-image
  source:
    repository: concourse/git-resource

- name: git-resource-dupe-6
  type: docker-image
  source:
    repository: concourse/git-resource

resources:
  - name: concourse
    type: git
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: concourse-git-dupe-1
    type: git-resource-dupe-1
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: concourse-git-dupe-2
    type: git-resource-dupe-2
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: concourse-git-dupe-3
    type: git-resource-dupe-3
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: concourse-git-dupe-4
    type: git-resource-dupe-4
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: concourse-git-dupe-5
    type: git-resource-dupe-5
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master
  - name: concourse-git-dupe-6
    type: git-resource-dupe-6
    source:
      uri: https://github.com/concourse/concourse.git
      branch: master

jobs:
- name: hello-world
  plan:
  - get: concourse
  - get: concourse-git-dupe-1
  - get: concourse-git-dupe-2
  - get: concourse-git-dupe-3
  - get: concourse-git-dupe-4
  - get: concourse-git-dupe-5
  - get: concourse-git-dupe-6
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["hello"]
```
