### ISSUE TITLE
Using put with params in a job results in the get to be missing the same params

### ISSUE THREAD

**Issue by literatesnow** [concourse/concourse#1261]
# Bug Report

When ``put`` is used with ``params`` in the pipeline, the subsequent ``get`` is not passed the same ``params`` as the ``put`` via ``stdin``.

Consider the following job:

```yaml
jobs:
- name: example-job
  serial: true
  plan:
    - get: do-stuff
      trigger: false
    - put: s3-bucket
      params:
        working_directory: do-stuff
    - get: s3-bucket
      params:
        working_directory: do-stuff
```

## Stdin as received from each step

1. ``put`` s3-bucket (as expected):

    ```json
      {"source":{...},"params":{"working_directory":"do-stuff"}}
    ```

1. ``get`` s3-bucket (missing params, expecting the same ``stdin`` as the ``put`` - this step is automatically run even when not specified in the job):

    ```json
      {"source":{..}}
    ```

1. ``get`` s3-bucket (as expected, calling ``get`` directly from the job has ``params``):

    ```json
    {"source":{...},
     "params":{"working_directory":"do-stuff"},
     "version":{"LastModified":"2017-06-07T03:34:52.000Z"}}
    ```

* Concourse version: 3.1.1
* Deployment type: worker - binary, web - AWS ECS
* Infrastructure/IaaS: AWS
* Did this used to work? Yes, in 2.7.x
