### ISSUE TITLE
Two or more serial jobs are not enqueued

### ISSUE THREAD

**Issue by kei-yamazaki** [concourse/concourse#1267]
# Bug Report

In the case of serial job, even if multiple versions are added, only one build is enqueued.
And un-enqueued versions will not be built.

As build 1 is running as in the screenshot below, I added three new versions.
<img width="1002" alt="running-build1" src="https://user-images.githubusercontent.com/1715090/26913045-63ee26fe-4c53-11e7-9b5e-55cc0b5f9557.png">

However, only one build is enqueued.
<img width="994" alt="build2-enqueued" src="https://user-images.githubusercontent.com/1715090/26913047-63f04aec-4c53-11e7-8327-dd99360f61c3.png">

After that, Build 2 is executed, but the remaining version is not enqueued.
<img width="1002" alt="build2-started-but-not-queuing" src="https://user-images.githubusercontent.com/1715090/26913044-63ede0e0-4c53-11e7-8422-4f40358dc4aa.png">

I thought that it was a problem of git-multibranch-resource, but a similar problem occurred in pullrequest-resource.

Here is pipeline and environments.
```yaml
resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
    tag: v0.1.0

resources:
- name: concourse-sandbox
  type: git-multibranch
  source:
    uri: git@github.com:kei-yamazaki/concourse-sandbox.git
    private_key: {{github-private-key}}
    branches: '.*'

jobs:
- name: serial-job
  serial: true
  plan:
  - get: concourse-sandbox
    trigger: true
  - task: sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sleep
        args: ["300"]
```

* Concourse version: 3.1.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: OpenStack

**Comment by SHyx0rmZ** [comment]
Concourse only ever uses the most recent version when running jobs. To get it to use the remaining versions, too, you have to specify `version: every` on your `get` like so:
```yaml
- name: serial-job
  serial: true
  plan:
  - get: concourse-sandbox
    trigger: true
    version: every
  - task: sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sleep
        args: ["300"]
```
