### ISSUE TITLE
Allow special characters in database password

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#1280]
When specifying a password for db in concourse bosh deployment manifest with special characters like `%`, ATC will fail to start up and create that user.

Example of bosh deployment manifest snippet:
```
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        role: admin
        password: some-password%T
```

There is no escaping happening here: https://github.com/concourse/concourse/blob/master/jobs/postgresql/templates/postgresql_ctl.erb#L69
