### ISSUE TITLE
Pipelines with non-Concourse keys newly rejected

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#1290]
In Concourse 3.1.1, the following manifest was parsed and [rendered properly](https://java-experience.ci.springapps.io/teams/strepsirrhini-army/pipelines/chaos-lemur):

```
---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: nebhale/slack-notification-resource

resources:
- name: chaos-lemur
  type: git
  source:
    uri:    https://github.com/strepsirrhini-army/chaos-lemur.git
    branch: master

- name: slack
  type: slack-notification
  source:
    url: ((slack-strepsirrhini-army))

jobs:
- name: unit-test
  public: true
  plan:
  - get: chaos-lemur
    trigger: true
  - task: unit-test
    file: chaos-lemur/ci/unit-test.yml
    on_failure: *slack-failure

- name: deploy
  public: true
  serial: true
  plan:
  - get: chaos-lemur
    trigger: true
    passed:
    - unit-test
  - task: deploy
    file: chaos-lemur/ci/deploy.yml
    params:
      ARTIFACTORY_USERNAME: ((artifactory-username))
      ARTIFACTORY_PASSWORD: ((artifactory-password))
    on_failure: *slack-failure
    on_success: *slack-success

slack-failure: &slack-failure
  put: slack
  params:
    attachments:
    - color: danger
      fallback: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME <FAILURE>"
      text: "<!here> Build has failed"
      title: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME"
      title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

slack-success: &slack-success
  put: slack
  params:
    attachments:
    - color: good
      fallback: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME <SUCCESS>"
      text: "Build has succeeded"
      title: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME"
      title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
```

In 3.2.0 this no longer works, failing with the following error:

```
error: invalid configuration:
unknown/extra keys:
  - slack-failure
  - slack-success
```

It would appear the new implementation validates that there are no keys in pipeline definitions that aren't part of the official declaration.  However, given how YAML anchors work, I think that this should be relaxed and reverted to the pre 3.2.0 behavior.
