### ISSUE TITLE
set-pipeline -v mangles multiline strings

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#1292]
# Bug Report

in 3.2.0 running `fly set-pipeline` with `  -v "GIT_BOT_KEY=$(lpass show --notes REDACTED/fake_key)"` turns this:
```
-----BEGIN_RSA_PRIVATE_KEY-----
Lorem_ipsum_dolor_sit_amet,_consectetur_adipiscing_elit._Phasell
us_malesuada_dui_eget_mauris_lobortis,_interdum_convallis_orci_d
apibus._Suspendisse_id_imperdiet_lorem._Sed_hendrerit_mauris_ant
e,_in_placerat_turpis_tincidunt_eget._Suspendisse_potenti._Morbi
_in_lacinia_augue._Vivamus_laoreet_purus_et_auctor_accumsan._Nul
lam_gravida_vitae_dui_id_blandit._Suspendisse_congue_ac_quam_sed
_luctus._Etiam_feugiat,_nisi_vel_consequat_tristique,_dui_eros_o
rnare_ante,_quis_elementum_ex_ipsum_a_arcu._Quisque_sapien_enim,
_vestibulum_non_mattis_sed,_mattis_a_urna._Morbi_euismod_euismod
_aliquet.
-----END_RSA_PRIVATE KEY-----
```
into this:
```
      private_key: '-----BEGIN_RSA_PRIVATE_KEY----- Lorem_ipsum_dolor_sit_amet,_consectetur_adipiscing_elit._Phasell
        us_malesuada_dui_eget_mauris_lobortis,_interdum_convallis_orci_d apibus._Suspendisse_id_imperdiet_lorem._Sed_hendrerit_mauris_ant
        e,_in_placerat_turpis_tincidunt_eget._Suspendisse_potenti._Morbi _in_lacinia_augue._Vivamus_laoreet_purus_et_auctor_accumsan._Nul
        lam_gravida_vitae_dui_id_blandit._Suspendisse_congue_ac_quam_sed _luctus._Etiam_feugiat,_nisi_vel_consequat_tristique,_dui_eros_o
        rnare_ante,_quis_elementum_ex_ipsum_a_arcu._Quisque_sapien_enim, _vestibulum_non_mattis_sed,_mattis_a_urna._Morbi_euismod_euismod
        _aliquet. -----END_RSA_PRIVATE KEY-----'
```
which makes the git resource think it's got a passphrase, but it's probably just failing to understand it.

The following can also be handy:

* Concourse version: 3.2.0
* Deployment type (BOSH/Docker/binary): bosh create-env
* Infrastructure/IaaS: vsphere
* Browser (if applicable): n/a
* Did this used to work? totes, big oats

**Comment by xtreme-gavin-enns** [comment]
Workaround on Mac:
```
  -v "GIT_BOT_KEY=\"$(lpass show --notes REDACTED/git-bot-user | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')\""
```

**Comment by vito** [comment]
Is this with `{{params}}` or `((params))`?

I'm actually not sure if there's anything we can do about this. It might be getting mangled by the shell before it even gets to us. How does your workaround work?

**Comment by kelvich** [comment]
Same here. Both `{{params}}` or `((params))` now smashes private key.
In 3.1.1 following was working, but right now doesn't:
```
> fly -t ci set-pipeline -c pgproee9_6.yml -p PGPROEE9_6 -v "private-repo-key=$(cat ~/.ssh/ci)"
```

**Comment by kelvich** [comment]
Seems that interpolation have nothing to do with it. Just putting key directly into pipeline causes the same formatting.

**Comment by vito** [comment]
@kelvich what do you mean by directly in the pipeline? Can you paste a snippet?

Make sure you use the yaml multilinear syntax via `|`.

**Comment by kelvich** [comment]
@vito my bad, i tried to insert it as a single line string. `|` seems to help.

But to reproduce original problem it is enough to have any pipeline with key and try to evaluate it with set-pipeline. Even in diff it will be visible that some of newlines were translated to spaces.

For example:

pipeline.yml:
```yml
resources:

- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    private_key: {{private-repo-key}}

jobs:

  - name: test
    plan:
    - get: concourse
    - task: test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        inputs:
        - name: concourse
        run:
          path: true
```

And interpolate that with some random key:
```sh
> ssh-keygen -f example
> fly -t ci3 set-pipeline -c pipeline.yml -p mypipeline -v "private-repo-key=$(cat example)"
```

Checked that on osx and linux with the same result.

**Comment by xtreme-gavin-enns** [comment]
@vito this was with {{params}}, apologies.

Similar to the other issue I posted yesterday, this was a scripted set-pipeline so we have a high degree of confidence that nothing changed except the concourse upgrade. Also, this should be very easy to reproduce; we could easily stand up a 3.0.1 environment to compare against if that would help.

Our workaround was to escape the newline characters and also to surround with escaped quotes. Not sure why that worked or why the bugged behaviour was to ignore every other newline character.

**Comment by vito** [comment]
This will actually be fixed for `{{params}}` as part of the same fix for #1291, however I'm going to go a step further and just have `-v` *always* mean "just take this string value and template it in verbatim", even for `((params))`. To support templating in YAML values with `((params))` (the original goal of the change), I've added a second flag, `-y` (`--yaml-var`).

This feels more consistent / less surprising as the behavior is consistent regardless of the type of params you're using.

**Comment by fhanik** [comment]
For future search reference, our variables retained their multiline when using `|` in the task yaml

```
run:
  path: ci/tasks/some-task.sh
  args:
    - |
      ((multi-line-var-1))
    - |
      ((multi-line-var-2))
    - |
      ((multi-line-var-3))
  dir: git-repo
```
