### ISSUE TITLE
Updating to 3.2.0 results in unmarshal errors when setting pipeline on previously working yaml

### ISSUE THREAD

**Issue by kyleshoaf** [concourse/concourse#1293]
# Bug Report

After upgrading to the latest concourse version I am unable to set my pipeline. Unmarshaling errors are thrown each time I attempt to set-pipeline. My yaml has not changed since the update.  I have confirmed that the same yaml still works with previous versions.  

my set-pipeline:
fly -t lite set-pipeline -p main -c pipeline-dev-ci.yml --load-vars-from credentials.yml

error: yaml: unmarshal errors: 
  line 107: cannot unmarshal !!seq into map[string]string
  line 119: cannot unmarshal !!seq into atc.Params
  line 122: cannot unmarshal !!seq into atc.Params
  line 189: cannot unmarshal !!seq into atc.Params

lines 106-120:
```
- name: git-app-project-cicd
  type: git
  source:
    uri: git@github.com:project/app-project-cicd.git
    <<: *git-defaults

######
# S3
######
- name: s3-cf-template
  type: s3
  source:
    <<: *s3-defaults
    versioned_file: cftemplates/project.cf.yaml
```

* Concourse version: 3.2.0
* Deployment type (BOSH/Docker/binary): Docker and Vagrant
* Infrastructure/IaaS: VirtualBox
* Browser (if applicable):
* Did this used to work? Yes
