### ISSUE TITLE
Add the ability to group resources together

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#1299]
# Feature Request

## What challenge are you facing?

We end up passing a giant block of resources between jobs in our pipeline. Example here: https://ci.kubo.sh. It would be nice if we had a way to group these resources in order to make the yaml more manageable and the pipeline easier to understand.

## A Modest Proposal

I was thinking something along the lines of a `resource_group` that can be defined at the top level and treated as any other resource within the step definition. Then from within the task I can consume that resource through `my-resource-group/my-code`.

```
resources:
- name: my-code
  type: git
  source:
    uri: https://github.com/some-org/my-code
    branch: master

- name: my-code-acceptance-tests
  type: git
  source:
    uri: https://github.com/some-org/my-code-acceptance-tests
    branch: master

resource_groups:
- name: my-resource-group
  resources: [my-code, my-code-acceptance-tests]
```
