### ISSUE TITLE
Issues with setting up Darwin iOS worker

### ISSUE THREAD

**Issue by mervyn777** [concourse/concourse#1310]
Hi,

I'm a newbie to this whole Concourse pipelines so kindly bear with me.

So far I've tried to setup a concourse build server and the Darwin worker on a mac mini for our iOS projects.

I've installed the Build Server using docker-compose and my yaml looks like this:

```
version: '3'

services:
    concourse-db:
      image: postgres:9.5
      environment:
        POSTGRES_DB: concourse
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        PGDATA: /database

    concourse-web:
      image: concourse/concourse
      links: [concourse-db]
      command: web
      ports: ["8080:8080", "2222:2222"]
      volumes: ["./keys/web:/concourse-keys"]
      environment:
        CONCOURSE_BASIC_AUTH_USERNAME: user
        CONCOURSE_BASIC_AUTH_PASSWORD: password
        CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
        CONCOURSE_POSTGRES_DATA_SOURCE: |-
            postgres://user:password@concourse-db:5432/concourse?sslmode=disable

    concourse-worker:
      image: concourse/concourse
      privileged: true
      links: [concourse-web]
      command: worker
      volumes: ["./keys/worker:/concourse-keys"]
      environment:
        CONCOURSE_TSA_HOST: concourse-web
```

Later I generated all necessary SSH keys and stored them in the appropriate folders.
And I'm able to successfully open the concourse web ui from my local machine (not the mac mini)

Now I installed the Darwin worker in the same mac mini by installing the [concourse](https://github.com/concourse/concourse/releases/download/v3.2.1/concourse_darwin_amd64) to `usr/local/bin/concourse`
then generating the necessary SSH keys for the worker and then running: `sudo concourse worker --work-dir /opt/concourse/worker --tsa-host 127.0.0.1 --tsa-public-key ./keys/worker/tsa_host_key.pub --tsa-worker-private-key ./keys/worker/darwin_worker_key` from the concourse folder in ~

Later I created a pipeline as follows:

```
---
groups:
-   name: ios-build
    jobs:
    -   build-test

resources:
-   name: src-dev
    type: git
    source:
        branch: master
        uri: https://github.com/tenten0213/ios-concourse.git

jobs:
-   name: build-test
    plan:
    -   get: src-dev
        trigger: true
    -   task: build-test
        config:
            platform: darwin
            inputs:
            -   name: src-dev
            run:
                path: src-dev/concourse/build_test.sh
```

and my build_test.sh looks like:

```
#!/bin/bash -el

xcodebuild -scheme "SampleProject" -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest" test
```

Please note that I'm not pointing the git resource to my internal private repo (because it was unsuccessful) but I'm only pointing to some external public git repo just to check if git clone even works successfully in the first place.

But when I set and run the pipeline I get the following error:

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/tenten0213/ios-concourse.git/': Couldn't resolve host 'github.com'
```

Do I have to change any network params within the container to expose it to external network? I've ran out of ideas. Please help.
