### ISSUE TITLE
no versions of image available

### ISSUE THREAD

**Issue by dweidenfeld** [concourse/concourse#1315]
# Bug Report

* Concourse version: 3.2.1 / docker
* Deployment type (BOSH/Docker/binary): docker + kubernetes (see configuration below)

Hi there,

I've deployed concourse on my kubernetes cluster and managed to get it work like with the docker-compose version.
Just for correctness I've attached my kubernetes configuration below

## Problem
I followed the hello-world tutorial https://concourse.ci/hello-world.html but if I want to start the ci process of the hello.yaml it just gives me this error:

"no versions of image available"

### postgresql
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: concourse-db
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: concourse-db
        spec:
            containers:
            - name: concourse-db
              image: postgres:9.5
              imagePullPolicy: Always
              ports:
              - containerPort: 5432
              env:
              - name: POSTGRES_DB
                value: concourse
              - name: POSTGRES_USER
                value: concourse
              - name: POSTGRES_PASSWORD
                value: changeme
              - name: PGDATA
                value: /database
---
apiVersion: v1
kind: Service
metadata:
    name: concourse-db
spec:
    ports:
    - name: db
      targetPort: 5432
      port: 5432
    selector:
        app: concourse-db
```

### web
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: concourse-web
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: concourse-web
        spec:
            volumes:
            - name: keys
              hostPath:
                path: "/app/concourse/keys/web"
            containers:
            - name: concourse-web
              image: concourse/concourse
              imagePullPolicy: Always
              command: ["concourse", "web"]
              ports:
              - name: http
                containerPort: 8080
              - name: tsa
                containerPort: 2222
              volumeMounts:
              - name: keys
                mountPath: "/concourse-keys"
              env:
              - name: CONCOURSE_BASIC_AUTH_USERNAME
                value: concourse
              - name: CONCOURSE_BASIC_AUTH_PASSWORD
                value: changeme
              - name: CONCOURSE_EXTERNAL_URL
                value: ci.sh0k.de
              - name: CONCOURSE_POSTGRES_HOST
                value: concourse-db
              - name: CONCOURSE_POSTGRES_USER
                value: concourse
              - name: CONCOURSE_POSTGRES_PASSWORD
                value: changeme
              - name: CONCOURSE_POSTGRES_DATABASE
                value: concourse
---
apiVersion: v1
kind: Service
metadata:
    name: concourse-web
spec:
    ports:
    - name: http
      targetPort: 8080
      port: 80
    - name: tsa
      targetPort: 2222
      port: 2222
    selector:
        app: concourse-web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: concourse-web
spec:
    rules:
    - host: ci.example.de
      http:
        paths:
        - path: /
          backend:
            serviceName: concourse-web
            servicePort: http
```

### worker
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: concourse-worker
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: concourse-worker
        spec:
            volumes:
            - name: keys
              hostPath:
                path: "/app/concourse/keys/worker"
            containers:
            - name: concourse-worker
              image: concourse/concourse
              imagePullPolicy: Always
              command: ["concourse", "worker"]
              volumeMounts:
              - name: keys
                mountPath: "/concourse-keys"
              env:
              - name: CONCOURSE_TSA_HOST
                value: concourse-web
              securityContext:
                privileged: true
```

## Error Log from build
```
{"timestamp":"1498216494.269340754","source":"tsa","message":"tsa.connection.channel.forward-worker.heartbeat.start","log_level":1,"data":{"remote":"10.42.217.137:60254","session":"3.1.1.7","worker-address":"127.0.0.1:33505","worker-platform":"linux","worker-tags":""}}
{"timestamp":"1498216494.271286488","source":"guardian","message":"guardian.list-containers.starting","log_level":1,"data":{"session":"22"}}
{"timestamp":"1498216494.271376133","source":"guardian","message":"guardian.list-containers.finished","log_level":1,"data":{"session":"22"}}
{"timestamp":"1498216494.273505449","source":"tsa","message":"tsa.connection.channel.forward-worker.heartbeat.reached-worker","log_level":0,"data":{"baggageclaim-took":"1.535103ms","garden-took":"2.287736ms","remote":"10.42.217.137:60254","session":"3.1.1.7"}}
{"timestamp":"1498216494.282093525","source":"tsa","message":"tsa.connection.channel.forward-worker.heartbeat.done","log_level":1,"data":{"remote":"10.42.217.137:60254","session":"3.1.1.7","worker-address":"127.0.0.1:33505","worker-platform":"linux","worker-tags":""}}
{"timestamp":"1498216494.730656147","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.10","volume":"abb7a9c8-0a1f-43ee-6a85-2edf94ce179c"}}
{"timestamp":"1498216494.730758667","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"4.1.4","volume":"abb7a9c8-0a1f-43ee-6a85-2edf94ce179c"}}
{"timestamp":"1498216495.108893871","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.12","volume":"014ca9fd-2a50-4312-4279-a8494e7d7a70"}}
{"timestamp":"1498216495.108942986","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"4.1.6","volume":"014ca9fd-2a50-4312-4279-a8494e7d7a70"}}
{"timestamp":"1498216495.147850752","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.14","volume":"4e869cc9-f5cc-4b08-635d-521859f169b4"}}
{"timestamp":"1498216495.147976398","source":"baggageclaim","message":"baggageclaim.api.volume-server.get-volume.volume-not-found","log_level":1,"data":{"session":"4.1.8","volume":"4e869cc9-f5cc-4b08-635d-521859f169b4"}}
{"timestamp":"1498216495.155633450","source":"guardian","message":"guardian.create.start","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23"}}
{"timestamp":"1498216495.155752420","source":"guardian","message":"guardian.create.containerizer-create.start","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.2"}}
{"timestamp":"1498216495.203521013","source":"guardian","message":"guardian.create.containerizer-create.depot-create.started","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.2.1"}}
{"timestamp":"1498216495.204626083","source":"guardian","message":"guardian.create.containerizer-create.depot-create.finished","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.2.1"}}
{"timestamp":"1498216495.204685211","source":"guardian","message":"guardian.create.containerizer-create.create.creating","log_level":1,"data":{"bundle":"/worker-state/depot/704df6b7-3791-4740-75a3-ca39c425b8d9","bundlePath":"/worker-state/depot/704df6b7-3791-4740-75a3-ca39c425b8d9","handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","logPath":"/worker-state/depot/704df6b7-3791-4740-75a3-ca39c425b8d9/create.log","pidFilePath":"/worker-state/depot/704df6b7-3791-4740-75a3-ca39c425b8d9/pidfile","runc":"/worker-state/3.2.1/assets/bin/runc","session":"23.2.3"}}
{"timestamp":"1498216495.265771866","source":"guardian","message":"guardian.create.containerizer-create.create.finished","log_level":1,"data":{"bundle":"/worker-state/depot/704df6b7-3791-4740-75a3-ca39c425b8d9","handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.2.3"}}
{"timestamp":"1498216495.265866041","source":"guardian","message":"guardian.create.containerizer-create.finished","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.2"}}
{"timestamp":"1498216495.274799585","source":"guardian","message":"guardian.create.containerizer-create.watch.watching","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.2.4"}}
{"timestamp":"1498216495.290389061","source":"guardian","message":"guardian.create.network.started","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.5","spec":""}}
{"timestamp":"1498216495.290536880","source":"guardian","message":"guardian.create.network.config-create","log_level":1,"data":{"config":{"ContainerHandle":"704df6b7-3791-4740-75a3-ca39c425b8d9","HostIntf":"wilrt1vabsiu-0","ContainerIntf":"wilrt1vabsiu-1","IPTablePrefix":"w--","IPTableInstance":"ilrt1vabsiu","BridgeName":"wbrdg-0afe0000","BridgeIP":"10.254.0.1","ContainerIP":"10.254.0.2","ExternalIP":"10.42.217.137","Subnet":{"IP":"10.254.0.0","Mask":"/////A=="},"Mtu":1402,"PluginNameservers":null,"OperatorNameservers":[],"AdditionalNameservers":["10.42.217.137"]},"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.5","spec":""}}
{"timestamp":"1498216495.374887705","source":"guardian","message":"guardian.create.network.finished","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23.5","spec":""}}
{"timestamp":"1498216495.374965191","source":"guardian","message":"guardian.create.created","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"23"}}
{"timestamp":"1498216495.375190973","source":"guardian","message":"guardian.api.garden-server.create.created","log_level":1,"data":{"request":{"Handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","GraceTime":0,"RootFSPath":"raw:///worker-state/volumes/live/014ca9fd-2a50-4312-4279-a8494e7d7a70/volume","BindMounts":[{"src_path":"/worker-state/volumes/live/4e869cc9-f5cc-4b08-635d-521859f169b4/volume","dst_path":"/scratch","mode":1}],"Network":"","Privileged":true,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.4"}}
{"timestamp":"1498216495.384531498","source":"guardian","message":"guardian.api.garden-server.get-properties.got-properties","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","session":"3.1.5"}}
{"timestamp":"1498216495.388299465","source":"guardian","message":"guardian.run.started","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24"}}
{"timestamp":"1498216495.388419867","source":"guardian","message":"guardian.run.exec.start","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2"}}
{"timestamp":"1498216495.388548374","source":"guardian","message":"guardian.run.exec.prepare.start","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2.1"}}
{"timestamp":"1498216495.400548458","source":"guardian","message":"guardian.run.exec.prepare.finished","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2.1"}}
{"timestamp":"1498216495.400641203","source":"guardian","message":"guardian.run.exec.execrunner.start","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2.2"}}
{"timestamp":"1498216495.413304806","source":"guardian","message":"guardian.run.exec.execrunner.read-exit-fd","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2.2"}}
{"timestamp":"1498216495.434912205","source":"guardian","message":"guardian.run.exec.execrunner.runc-exit-status","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2.2","status":0}}
{"timestamp":"1498216495.434991837","source":"guardian","message":"guardian.run.exec.execrunner.done","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2.2"}}
{"timestamp":"1498216495.435089588","source":"guardian","message":"guardian.run.exec.finished","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24.2"}}
{"timestamp":"1498216495.435443640","source":"guardian","message":"guardian.run.finished","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","path":"/opt/resource/check","session":"24"}}
{"timestamp":"1498216495.435525417","source":"guardian","message":"guardian.api.garden-server.run.spawned","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"1facfdaf-b631-423c-7456-3c5313c89a80","session":"3.1.6","spec":{"Path":"/opt/resource/check","Dir":"","User":"root","Limits":{},"TTY":null}}}
{"timestamp":"1498216495.605370045","source":"guardian","message":"guardian.api.garden-server.run.exited","log_level":1,"data":{"handle":"704df6b7-3791-4740-75a3-ca39c425b8d9","id":"1facfdaf-b631-423c-7456-3c5313c89a80","session":"3.1.6","status":0}}
```

Thank you for every kind of support :)

**Comment by dweidenfeld** [comment]
Hey... got it fixed... it has been the DNS problem.... to fix it replace the worker config from above with

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: concourse-worker
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: concourse-worker
        spec:
            volumes:
            - name: keys
              hostPath:
                path: "/app/concourse/keys/worker"
            - name: workdir
              emptyDir: {}
            containers:
            - name: concourse-worker
              image: concourse/concourse
              imagePullPolicy: Always
              args: ["worker"]
              volumeMounts:
              - name: keys
                mountPath: "/concourse-keys"
              - name: workdir
                mountPath: "/concourse-work-dir"
              env:
              - name: CONCOURSE_TSA_HOST
                value: concourse-web
              - name: CONCOURSE_WORK_DIR
                value: "/concourse-work-dir"
              - name: CONCOURSE_GARDEN_ADDRESS
                value: concourse-worker
              - name: CONCOURSE_BAGGAGECLAIM_ADDRESS
                value: concourse-worker
              - name: CONCOURSE_GARDEN_FORWARD_ADDRESS
                value: concourse-worker
              - name: CONCOURSE_BAGGAGECLAIM_FORWARD_ADDRESS
                value: concourse-worker
              - name: CONCOURSE_GARDEN_DNS_SERVER
                value: 8.8.8.8
              securityContext:
                privileged: true
```
