### ISSUE TITLE
Allow specification of custom resources in manifest without overriding default resources 

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#132]
We would like to add a non-default resource to concourse. It looks like this can be accomplished by adding the following to your manifest:
```yaml
jobs:
- name: worker
  properties:
    groundcrew:
      resource_types:
      - type: MY_RESOURCE
        image: MY_IMAGE
```

However, this would remove all the default resources like `git` and `s3`. We would have to copy all the default resources from the spec file and then add our resource to the end of the list. We would then have to manually add to this list every time an official concourse resource is added. We would like to specify something like `custom_resource_types` while leaving `resource_types` at its default value.
