### ISSUE TITLE
Metadata vars not being substituted

### ISSUE THREAD

**Issue by philicious** [concourse/concourse#1320]
Hi there!

# Bug Report

The metadata variables arent substituted everywhere. The first `put` (slack) gets the substitutions but the second `put` keeps the variables instead of the values

```
      - task: unit test
         .....
        on_failure:
          do:
            - put: slack
              params:
                attachments:
                  - color: danger
                    text: "unit test #$BUILD_NAME of PRs on foobar failed http://acme.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
                    mrkdwn_in: ["text"]
                channel: "#ci"
                username: concourse
                icon_url: http://seeklogo.com/images/C/concourse-logo-42A9F81B42-seeklogo.com.png
            - put: foobar-prs
              params:
                state: FAILED
                key: "$BUILD_PIPELINE_NAME_$BUILD_NAME"
                name: "unit test"
                url: "http://acme.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
```

* Concourse version: 3.2.1
