### ISSUE TITLE
Docker resources and tasks with private CAs are broken

### ISSUE THREAD

**Issue by DRuggeri** [concourse/concourse#1340]
# Bug Report

Internal registries signed by a private CA (when you don't want to disable all validation with insecure_registries) are broken. I've verified it works in 3.1.1 and 3.1.0 but no prior or older versions.

I assume this is a side effect or regression after 3.1.1, but a guess makes me think it's related to the introduction of (( params )) in 3.2.0.

When using 3.3.0, I can only reproduce the issue when
* A task is using in-line config instead of from file
* ... or is a custom resource
* The config is using [docker-image](https://github.com/concourse/docker-image-resource)
  * with CA certs defined
  * with client certs defined

When attempting to set the following pipeline (on v3.3.0) works. However, removing the comments in the CA certs section results in `failed to save config: json: error calling MarshalJSON for type *atc.LoadTaskConfig: json: unsupported type: map[interface {}]interface {}`. It seems that the source schema when inside a config element in the pipeline permits only key/value or key/array pairs.

*EDIT*
I have also found that custom resource types using docker-image are also broken. The error there (not seen when set-pipeline is called, but rather when the resource attempts to check) is `json: unsupported type: map[interface {}]interface {}`. With fly, forcing a check simply returns a 500.

**Sample Pipeline**
````
jobs:
- name: hello
  plan:
  - task: hithere
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: alpine
#Remove these hashes to become sad
#          ca_certs:
#            - domain: foobar
#              cert: abc
      run:
        path: sh
        args: [ '-c', 'echo Hello' ]
````
