### ISSUE TITLE
Resource configuration cannot contain more than one level of maps

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#1345]
Having resource with nested source configuration raises a JSON error:

```
resources:
- name: my-resource
  type: git
  source:
    some-source:
      param1: value1

jobs:
- name: hello-job
  plan:
  - put: my-resource
```

Will raise an error:

```
json: unsupported type: map[interface {}]interface {}
```
