### ISSUE TITLE
When accessing multiple fields of the same key via params, the key should only be fetched once

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1349]
# Feature Request

## What challenge are you facing?

If I've configured a key with a backend that rotates the value on every fetch, then doing something like:

```yaml
source:
  access_key: ((my_s3_key.access_key))
  secret_key: ((my_s3_key.secret_key))
```

...will currently end up with broken credentials, as it'll be fetched twice.

## A Modest Proposal

We should fetch `my_s3_key` once per resolution "scope" (i.e. `source`), and fetch the fields off the same value.
