### ISSUE TITLE
Docker in Docker Image fails to creating aufs mount after Concourse v3.0.1

### ISSUE THREAD

**Issue by DoingItNow** [concourse/concourse#1351]
# Bug Report

## What challenge are you facing?
I have a job that would run server tests in a docker in docker image which creates a docker compose stack to run the necessary containers. The job can be seen below

```
- name: run-server-tests
  public: true
  plan:
  - get: server-repo
    passed: [pull-server-repo]
    trigger: true
  - get: emailservice-repo
    trigger: true
  - task: set-up-testing-stack
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
        - name: server-repo
        - name: emailservice-repo
      run:
        path: sh
        args:
        - -exc
        - |

          # Start up the docker daemon`
          source /docker-lib.sh
          start_docker
          docker info
        
          cd server-repo

          # Create the docker image local registry and build the backend image
          docker run -d -p 5000:5000 --restart=always --name registry registry:2
          export branch=develop
          docker build -t localhost:5000/server-${branch} . &&  docker push localhost:5000/server-${branch}

          # Build the mock service image and store it into the registry
          cd ../emailservice-repo/mock-service
          docker build -t localhost:5000/mock-email-service . &&  docker push localhost:5000/mock-email-service

          # Run the tests.
          # What this will do is spin up backend and any containers that link to it
          cd ../../server-repo
          docker-compose run --service-ports backend npm run test:coverage:docker

```
This job was working fine on concourse v3.0.1. After that version it will fail to build the aufs mount when the job starts. A snippet of error can be seen below

`docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/dd74897216ccfefb3052af98b488c9fc56d6ffdaf090e35ede8c82f3bfa26060-init: invalid argument.`

I suspect it is the change in v3.1.0  where the filesystem uses overlay rather than btrfs. I am not 100% sure but any version of concourse from 3.1.0 and onwards does not work anymore.

## Reproducing the issue
While my job is quite specific, if you want to see a general issue, run the following job
```
- name: run-failed-job
  plan:
  - get: random-repo
  - task: set-up-testing-stack
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
        - name: random-repo
      run:
        path: sh
        args:
        - -exc
        - |

          # Start up the docker daemon
          source /docker-lib.sh
          start_docker
          docker info
      
          # Create the docker image local registry and build the backend image
          docker run -d -p 5000:5000 --restart=always --name registry registry:2
```
Running the image registry:2 will fail to pull down the image.

If anyone can give some insight to the problem that would be great. I can stick to 3.0.1 for now, but there are some really nice features from later versions I would like to use.

* Concourse version: 3.1.0 and onwards
* Deployment type (BOSH/Docker/binary):Docker
* Infrastructure/IaaS: ubuntu 16.04
* Browser (if applicable): Chrome
* Did this used to work? Since 3.0.1
