### ISSUE TITLE
garden-init: permission denied on OSX worker

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#1353]
# Bug Report

I started running Concourse 3.3.0 (docker-compose) connected to a OSX worker.
I am getting the below error on my OSX Worker now:

runc create: exit status 1: container_linux.go:264: starting container process caused “process_linux.go:339: container init caused \“rootfs_linux.go:57: mounting \\\“/worker-state/3.3.0/assets/bin/init\\\” to rootfs \\\“/worker-state/volumes/live/ddf79092-50b9-4f5d-49ee-055c43b9dc99/volume\\\” at \\\“/worker-state/volumes/live/ddf79092-50b9-4f5d-49ee-055c43b9dc99/volume/tmp/garden-init\\\” caused \\\“open /worker-state/volumes/live/ddf79092-50b9-4f5d-49ee-055c43b9dc99/volume/tmp/garden-init: permission denied\\\“\”"

Earlier it worked.

The following can also be handy:

* Concourse version: 3.3.0
* Deployment type (BOSH/Docker/binary): Docker compose for ATC, binary+dedicated machines for workers
* Did this used to work?  ~3.0.1 was working.

**Comment by devdavidkarlsson** [comment]
(I have chmoded the entire volumes directory to 777, did not help...)

**Comment by devdavidkarlsson** [comment]
For my ATC Setup I have the following setup, note: I am not using the linux worker, the error appears in a job that is running against my darwin worker.


```

concourse-db:
  container_name: concourse-db-1
  image: postgres:9.5
  restart: always
  privileged: true
  volumes: ["pgres-data:/database"]
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database

concourse-web:
  container_name: concourse-web-1
  image: concourse/concourse
  restart: always
  links:
    - concourse-db
    - docker-registry
  command: web
  ports: ["8080:8080", "2222:2222"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: concourse
    CONCOURSE_BASIC_AUTH_PASSWORD: changeme
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  container_name: concourse-worker-1
  image: concourse/concourse
  privileged: true
  restart: always
  links: [concourse-web, docker-registry]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

docker-registry:
  container_name: docker-registry-1
  image: registry:2
  privileged: true
  restart: always
  ports: ["5000:5000"]
  # IF https registry is desired:
  # environment:
  #  REGISTRY_HTTP_TLS_CERTIFICATE: /keys/docker-registry/docker-registry.crt
  #  REGISTRY_HTTP_TLS_KEY: /keys/docker-registry/docker-registry.key
  volumes:
    - docker-registry-data:/tmp/registry

# https://download.pureftpd.org/pub/pure-ftpd/doc/README
# https://github.com/vimagick/dockerfiles/tree/master/pure-ftpd
test-report-server:
  container_name: test-report-server-1
  image: jumanjiman/caddy
  privileged: true
  restart: always
  ports:
    - "8082:8082"
  volumes:
    - ./caddy/Caddyfile:/home/Caddyfile
    - ./caddy/.caddy:/root/.caddy
    - ./caddy/www:/srv
  command: -port 8082 -conf="/home/Caddyfile"

nexus:
  container_name: nexus-server-1
  image: sonatype/docker-nexus3
  privileged: true
  restart: always
  volumes:
    - "nexus-data:/nexus-data"
  ports:
    - "8081:8081"

```
