### ISSUE TITLE
Not able to persist Concourse Pipelines after Server restarts on MacOS

### ISSUE THREAD

**Issue by mervyn777** [concourse/concourse#1359]
I have setup a concourse ci using docker on Mac Mini. 

My docker compose file looks like:
```
version: '3'

services:
  concourse-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    command: web
    ports: ["8080:8080", "2222:2222"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: user
      CONCOURSE_BASIC_AUTH_PASSWORD: password
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://db_user:db_password@concourse-db:5432/concourse?sslmode=disable

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
```

After loading all iOS/other pipelines everything builds and works just fine. But when the server is restarted either manually or through some other event I'll have to manually execute `docker-compose up` to restart all the concourse services once again. (I plan to create a launchagent daemon script to restart these services on startup) And the list is empty without any pipelines!

Is there something I have to do to persist the data from PostGres DB to reuse it later to bring back all the pipelines and build logs?

I thought the db container configured in docker-compose already backs up the data to `/database` folder but thats empty or does not exist in the root.

**Comment by svrc-pivotal** [comment]
Generally this only happens if you lose the Postgres container and it gets recreated.   If you declare a volume, it will survive recreates..

Here's what i did to fix my running concourse deployment:
```
docker-compose stop concourse-db
docker cp -a <postgres container id>:/database . 
```   
Now I edit docker-compose.yml to add a   **volumes: ["./database:/database"]** entry in concourse-db:
```
concourse-db:
  image: postgres:9.5
  volumes: ["./database:/database"]
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database
```
Then I ran
```
docker-compose up -d --no-deps concourse-db
```

And I had my PG database running on my Mac instead of in the container.    see also this gist, which uses docker volume local driver:
https://gist.github.com/SeerUK/59fc5ae5371cab37aafa46cff54c14bf
