### ISSUE TITLE
Custom Resources not available on tagged workers

### ISSUE THREAD

**Issue by Rukenshia** [concourse/concourse#1371]
Similar to #152 , I can only access the default provided resources from concourse and not custom resources on tagged workers. The resource is defined with the tag:

```
resource_types
  - name: artifactory
# i also tried putting tags here, without any effect
    type: docker-image
    source:
      repository: pivotalservices/artifactory-resource

resources
- name: artifact
  tags: ["my-worker"]
  type: artifactory
  source:
    endpoint: xxx
    repository: xxx
    regex: xxx
    username: {{artifactory-user}}
    password: {{artifactory-key}}
```

Error in the UI: `custom resource type 'artifactory' version not found`

* Concourse version: 3.3.1
* Deployment type (BOSH/Docker/binary): binary (linux worker)

**Comment by SHyx0rmZ** [comment]
Have you also tried setting `tags` in both `resource_types` and `resources` at the same time?

**Comment by Rukenshia** [comment]
@SHyx0rmZ yes, I tried putting them _everywhere_. `resource_types`, `resources`, `get` tasks

**Comment by jtarchie** [comment]
@Rukenshia, a resource-type docker image has to be downloaded first before it can be run. The error you are receiving is the one passed along while the base resource-type docker image is being downloaded, too.

Do you find that your pipelines start to work after awhile?

**Comment by jtarchie** [comment]
Actually, I've been able to recreate this on my local concourse.

The pipeline I've used:

```
resource_types:
- name: abc-def
  type: docker-image
  source:
    repository: concourse/git-resource

resources:
- name: atc
  tags: ["asdf"]
  type: abc-def
  source:
    uri: https://github.com/concourse/atc

jobs:
- name: first
  plan:
  - get: atc
```

I deployed my workers with the tag `asdf` (very scientifical).

The repeating logs I am seeing from ATC when I trigger a build

```
{"timestamp":"1499961519.941831350","source":"atc","message":"atc.syncer.test:scheduler.tick.scheduling.try-start-next-pending-build.scan.failed-to-find-or-create-resource-config","log_level":2,"data":{"build-id":6,"build-name":"1","error":"custom resource type 'abc-def' version not found","input":"atc","resource":"atc","session":"16.52.2.3.2.2"}}
{"timestamp":"1499961529.923763275","source":"atc","message":"atc.syncer.test:radar.scan-resource.interval-runner.failed-to-find-or-create-resource-config","log_level":2,"data":{"error":"custom resource type 'abc-def' version not found","pipeline-scoped-name":"test:resource:atc","session":"16.53.2.1"}}
{"timestamp":"1499961529.924729347","source":"atc","message":"atc.syncer.test:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Name":"abc-def"},"session":"16.53"}}
{"timestamp":"1499961529.941065073","source":"atc","message":"atc.syncer.test:radar.scan-resource-type.interval-runner.acquire.acquired","log_level":0,"data":{"id":[0,6],"pipeline-scoped-name":"test:resource-type:abc-def","session":"16.53.1.1.2"}}
{"timestamp":"1499961529.947188377","source":"atc","message":"atc.syncer.test:radar.scan-resource-type.interval-runner.release.released","log_level":0,"data":{"id":[0,6],"pipeline-scoped-name":"test:resource-type:abc-def","session":"16.53.1.1.3"}}
{"timestamp":"1499961529.947210550","source":"atc","message":"atc.syncer.test:radar.scan-resource-type.interval-runner.lock.did-not-get-lock","log_level":0,"data":{"pipeline-scoped-name":"test:resource-type:abc-def","resource-type":"abc-def","session":"16.53.1.1.1"}}
{"timestamp":"1499961539.942351818","source":"atc","message":"atc.syncer.test:scheduler.tick.scheduling.try-start-next-pending-build.scan.failed-to-find-or-create-resource-config","log_level":2,"data":{"build-id":6,"build-name":"1","error":"custom resource type 'abc-def' version not found","input":"atc","resource":"atc","session":"16.54.2.3.2.2"}}
```

**Comment by RMeharg** [comment]
We have also been running into this issue and are unable to use custom resource types on a tagged worker.

**Comment by yevster** [comment]
I appear to be seeing the same issue running this "sample" configuration on the "out-of-the-box" [docker-compose configuration provided on the setup instruction page](https://concourse.ci/docker-repository.html). 

The worker does not appear to be tagged by default:
```
$ fly -t ci workers
name          containers  platform  tags  team  state    version
4aab25cfa336  0           linux     none  none  running  1.1 
```

Here's a sample pipeline that reproduces it:
```
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: testytest-pr
  type: pull-request
  source:
    repo: yevster/smoke
    access_token: '((access-token))'

jobs:
- name: hello-world
  plan:
  - get: testytest-pr
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: 'ls -ltR; echo '
        args: ["Hello, world!"]
```
