### ISSUE TITLE
Please explain "invalid magic" and necessary workaround

### ISSUE THREAD

**Issue by paulwalker** [concourse/concourse#1385]
I have attempted to get concourse running in minikube as well as a k8 cluster on GCM with no success. While I can get the web UI to show up and some commands to run, whenever I try to add input I get an error `gzip: invalid magic`

I have attempted concourse on K8 with:

`helm install -f concourse/values.staging.yaml stable/concourse`

with values.staging.yaml:
```
concourse:
  externalURL: http://ci.mydomain.io
web:
  service:
    type: NodePort
  ingress:
    enabled: true
    hosts:
      - ci.mydomain.io
```

```
$ fly --target tutorial execute --config inputs_required.yml --input some-important-input=.
executing build 2
curl: (6) Couldn't resolve host 'ci.mydomain.io'
gzip: invalid magic
```

What is wrong here?
