### ISSUE TITLE
When updating a running job the containers from the old job seem to stay alive

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1393]
# Bug Report

When running a dummy pipeline like:
```
---
resources:
- name: 1s
  type: time
  source: {interval: 1s}
- name: alpine
  type: docker-image
  source:
    repository: alpine

jobs:
- name: get-1s
  plan:
  - get: 1s
    trigger: true
  - get: alpine
  - task: foo
    image: alpine
    config:
      platform: linux
      run:
        path: false
```

if you update the pipeline while it is running, say by replacing all the `1s`s with `60s`:

```
---
resources:
- name: 60s
  type: time
  source: {interval: 60s}
- name: alpine
  type: docker-image
  source:
    repository: alpine

jobs:
- name: get-60s
  plan:
  - get: 60s
    trigger: true
  - get: alpine
  - task: foo
    image: alpine
    config:
      platform: linux
      run:
        path: false
``` 

Then a few containers from the old pipeline stay alive indefinitely:

```
$fly -t vbox containers                                                                                           DX243: Tue Jul 18 15:04:13 2017

04278b20-2724-4281-7c42-a266bab32043  60e69eeb-c870-403a-8fee-0c33e907024c  none  none     none  none  check  none  n/a
4f1cb352-7d96-4af6-4cbb-4ef4ca2c1be1  60e69eeb-c870-403a-8fee-0c33e907024c  test  get-60s  45    273   get    60s   n/a
5a7554b4-9428-40b9-4875-fe2d639f674e  60e69eeb-c870-403a-8fee-0c33e907024c  test  get-60s  45    273   task   foo   n/a
7f6ed3c3-652c-4942-5e0e-fa95c6354ef0  60e69eeb-c870-403a-8fee-0c33e907024c  none  none     none  none  check  none  n/a
8d1ce359-8724-49b6-652e-3fdde55eab94  60e69eeb-c870-403a-8fee-0c33e907024c  none  none     none  none  check  none  n/a
b1483bde-86e3-4adb-42d2-ad0748292993  60e69eeb-c870-403a-8fee-0c33e907024c  test  get-1s   3     228   get    1s    n/a
eb4a80e1-1496-4a54-7ebe-2c5f302110da  60e69eeb-c870-403a-8fee-0c33e907024c  test  get-1s   3     228   task   foo   n/a
```

Note the `get-1s` containers that are still alive minutes after the pipeline has updated.

The following can also be handy:

* Concourse version: 3.3.2
* Deployment type (BOSH/Docker/binary): BOSH (testflight, locally running)
* Browser (if applicable): N/A
* Did this used to work? Unknown
