### ISSUE TITLE
set-pipeline with ./ as the name prefix yields inconsistent behaviour

### ISSUE THREAD

**Issue by jhvhs** [concourse/concourse#1403]
With fly CLI 3.3.0 we have encountered the following behaviour:

 `fly -t ... set-pipeline -n ./pipeline-name` correctly recognizes the pipeline and displays a YAML diff followed by a confirmation prompt. However the changes never get applied. This can be verified by running the same command again and seeing the same diff being output. It seems that non-alphanumeric characters are sometimes, but not always are ignored.

**Comment by jtarchie** [comment]
@jhvhs, that's an incorrect usage of `fly set-pipeline`. You are missing the `-p` and `-c`.

**Comment by andrewedstrom** [comment]
@jhvhs Do you observe this same issue after adding `-p` and `-c`?

**Comment by alex-slynko** [comment]
yes, we have observed that behaviour with `-p`  and `-c` flags.
We have omitted some flags since we were running `fly` using our script which was setting environment properties.

**Comment by jtarchie** [comment]
@jhvhs, are you able to provide a reproducible example? I've not observed this behaviour.

**Comment by alex-slynko** [comment]
@jtarchie 
```
$ fly -t target get-pipeline -p pipeline > ./pipeline
 modify the file
$ fly -t target set-pipeline -p ./pipeline -c ./pipeline
```
We are using fly 3.3.0

**Comment by jtarchie** [comment]
@alex-slynko, sorry, I meant with a reproducible YAML file.

**Comment by alex-slynko** [comment]
@jtarchie I was able to reproduce it with sample pipeline config from concourse.ci

```
fly -t kubo sp -p ./test -c 1.yml
jobs:
  ←[33mjob hello-world has changed:
    name: hello-world
    plan:
    - task: say-hello
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: echo
          args:
          - Hello, world!
          - Hello, world!!!
          dir: ""

```

When I create new pipeline, I got: " error:  resource not found"

**Comment by jtarchie** [comment]
Can you copy+paste the original YAML please for the pipeline, not just the output.

**Comment by alex-slynko** [comment]
@jtarchie 
```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
```
& 
```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!!!"]
```
