### ISSUE TITLE
After fly version update to 3.3.2 cannot unmarshal !!seq into atc.Params error

### ISSUE THREAD

**Issue by Puthiaraj1** [concourse/concourse#1459]
Hi

# Bug Report

Recently I update my fly version from 3.1.1 to 3.3.2 any while set-up the pipeline getting "cannot unmarshal !!seq into atc.Params error" . 

I didnt face this issue in 3.1.1 version. Can you someone help me to fix this issue

The following can also be handy:

* Concourse version: 3.3.2 
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: virtualBox
* Browser (if applicable):
* Did this used to work? pipeline worked with 3.1.1 version

**Comment by jtarchie** [comment]
@Puthiaraj1, this error is because our YAML parser became stricter.

This error is caused by a map being provided as an array, for example:

```yaml
params:
- ENV_VAR1: value
- ENV_VAR2: value
- ENV_VAR3: value
```

When it actually should be:

```yaml
params:
  ENV_VAR1: value
  ENV_VAR2: value
  ENV_VAR3: value
```

The difference being the leading *-* for each of the `ENV_VAR` key-value pairs.
