### ISSUE TITLE
s3 resource with regex not picking up double digit versions

### ISSUE THREAD

**Issue by mandyozhao** [concourse/concourse#146]
Below is an s3 resource configuration from our pipeline. We recently produced a file using a different pipeline with the file name 'example-product-1.5.5-build.10.zip', and this resource did not pick up the new version, staying at 'example-product-1.5.5-build.9.zip'.

```
- name: example-product
  type: s3
  source:
    regexp: example-product-(1\.5.*).zip
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
    bucket: example-product-files
```

~ Ops Manager
