### ISSUE TITLE
`atc.urls` documentation or code is wrong, unable to override bosh links

### ISSUE THREAD

**Issue by aeijdenberg** [concourse/concourse#1466]
# Bug Report

`jobs/tsa/spec` states:

```yaml
  atc.urls:
    description: |
      ATC API endpoints to which workers will be advertised.
      If not specified, they will be autodiscovered via BOSH links.
    default: ["http://127.0.0.1:8080"]
```

However the code appears to do the opposite:

```ruby
  atc_urls = []
  if_link("atc") do |atc|
    atc.instances.each do |instance|
      atc_urls << "http://#{instance.address}:#{atc.p("bind_port")}"
    end
  end

  atc_urls = p("atc.urls") if atc_urls.empty?
```

i.e., it will use the ATC API endpoint discovered via BOSH links, unless not specified, in which case it will use these properties.

It would have been more useful for us to be able to override the values provided by the BOSH links - and that's what I would have expected that property to do, however if that's not possible, the documentation should be updated to match what the code does.

**Comment by jtarchie** [comment]
@aeijdenberg, you are able to disable the link in your bosh-deployment manifest.

```yaml
consumes:
  atc: nil
```

**Comment by aeijdenberg** [comment]
Thanks @jtarchie, I'm not able to get that to work though (perhaps I'm missing exactly where to put that?). For full context, our deployment manifest is [here](https://github.com/AusDTO/bosh-deployments/blob/master/concourse/concourse.yml#L36). I tried adding to our operator file:

```yaml
- type: replace
  path: /instance_groups/name=web/jobs/name=tsa/consumes?/atc
  value: nil
```

and while I was able to confirm that `bosh int` appeared to generate what I would expect:

```yaml
instance_groups:
  ...
  jobs:
  - name: atc
    properties:
      ...
    release: concourse
  - name: tsa
    consumes:
      atc: nil
    properties: {}
    release: concourse
```

when I tried to deploy I received an error: `Error: Link path was not provided for required link 'atc' in instance group 'web'`.
