### ISSUE TITLE
Parameters not being retrieved

### ISSUE THREAD

**Issue by jgeorge300** [concourse/concourse#1490]
# Bug Report
* Concourse version: 3.3.4
* cf-resource

I have a pipeline configured to retrieve credentials from vault to do a cf deploy. When concourse runs the pipeline, it does not replace the parameters with the values from vault. If I use the parameter elsewhere in the pipeline, the value is retrieved and replaced as expected.

Pipeline snippet: 
```
jobs:
- name: deploy-service-broker
  serial: true
  plan:
  - get: src
  - put: deploy
    params:
      manifest: ((manifest))
      path: src
      environment_variables:
        VAULT_ADDR: ((uri))
```

Error:
```
error invalid manifest path: found 0 files instead of 1 at path: /tmp/build/put/((manifest))
```
