### ISSUE TITLE
Button for a job with `disable_manual_trigger: true` is still enabled in builds UI

### ISSUE THREAD

**Issue by rowanjacobs** [concourse/concourse#1496]
We have a [job](https://wings.concourse.ci/teams/cf-infrastructure/pipelines/bosh-bootloader/jobs/github-release) with `disable_manual_trigger: true` set in the build plan. Accordingly, the "trigger build" button on that page is grayed-out with a little tooltip explanation of why the build can't be triggered, which is great. However, on [the page showing an individual build](https://wings.concourse.ci/teams/cf-infrastructure/pipelines/bosh-bootloader/jobs/github-release/builds/14), the trigger build button is enabled and gives no feedback when pressed. (Fortunately, this does not actually kick off a build, so it looks like a UI issue only.)

This is occurring in Wings, with Concourse version 3.4.0.

Here's the YML config for the job in question: 
```
- name: github-release
  public: true
  disable_manual_trigger: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-version
      trigger: true
      resource: version
    - get: bosh-bootloader
      passed:
      - aws-acceptance-tests
      - gcp-acceptance-tests
      - aws-concourse-acceptance-tests
      - gcp-concourse-acceptance-tests
      - bbl-aws-cf
      - bbl-gcp-cf
      - bbl-gcp-cf-jumpbox
  - task: build-binaries
    file: ci/scripts/bosh-bootloader/build-final-release/task.yml
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      body: builds/body
      globs:
      - builds/bin/bbl-*
```

What it looks like in `jobs/github-release/builds/14`:
![enabled button](https://user-images.githubusercontent.com/6798170/29390448-4bebadbe-82a5-11e7-9933-8de9a5b2806a.png)

What we expect it to look like (and what it looks like in `jobs/github-release`):
![grayed-out button with "manual triggering disabled in job config" tooltip](https://user-images.githubusercontent.com/6798170/29390473-74a48b86-82a5-11e7-96ce-ebfbff5bfc45.png)
