### ISSUE TITLE
Document how to use inputs to tasks

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#151]
The documentation around tasks, particularly inputs, is woefully inadequate.

We were told by @robdimsdale and @evanshort73 that you can actually put a prior task as an input to a later task, like

```
- task: a
  ...
- task: b
      config:
        platform: linux
        image: docker:///ubuntu/trusty
        inputs:
          - name: a
          - name: some-repo
        run:
          path: some-repo/scripts/do-something
```

This is **not** documented. The documentation for inputs states:

> This determines which **artifacts** will propagate into the task, as the build plan executes. If any specified inputs are not present, the task will end with an error, without running.

and then does not ever describe what is an artifact.
