### ISSUE TITLE
Concourse doesn't run any jobs if Vault missconfigured

### ISSUE THREAD

**Issue by aleksey-hariton** [concourse/concourse#1516]
If I'll set wrong connection parameter to Vault ATC works but doesn't want to start any jobs and doesnt shows any error messages, I'm just hitting "+" and nothing happens. 

* Concourse version: 3.3.4
* Deployment type: BOSH

Tons of  error messages in `/var/vcap/sys/log/atc/atc.stdout.log`, something like `cant connect to vault with creds...`

BOSH manifest:
```
...
      vault:
...
        auth:
          params: 
            role_id: WRONG_ROLE_ID
            secret_id: OR_WRONG_SECRET_ID

```
