### ISSUE TITLE
Vault field syntax not working as documented

### ISSUE THREAD

**Issue by HCanber** [concourse/concourse#1517]
Concourse version: 3.4.0

In the docs, in section [Credential Management > Using Vault > Credential Lookup Rules](https://concourse.ci/creds.html#section_credential-lookup-rules) it says:

> Vault credentials are actually key-value, so for `((foo))` Concourse will default to the field name `value`. You can specify the field to grab via `.` syntax, e.g. `((foo.bar))`.

I can't get this to work.

I add this to vault:

```
$> vault write /concourse/main/foo value=Hi bar=Hello
Success! Data written to: concourse/main/foo
$> vault read /concourse/main/foo
Key             	Value
---             	-----
refresh_interval	768h0m0s
bar             	Hello
value           	Hi
```

## Working example

This pipeline works as expected:

```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      image_resource:
        source:
          repository: ubuntu
        type: docker-image
      params:
        FOO: ((foo))
      platform: linux
      run:
        path: env
```

When running, _say-hello_ writes

```
FOO=Hi
```

## Failing example

However, if I add two more params, using the field syntax it fails

```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      image_resource:
        source:
          repository: ubuntu
        type: docker-image
      params:
        FOO: ((foo))
        FOO_BAR: ((foo.bar))
        FOO_VALUE: ((foo.value))
      platform: linux
      run:
        path: env
```

This time, _say-hello_ fails with:

> Finding variable 'foo.bar': Expected to find a map at path '/bar' but found 'string'
