### ISSUE TITLE
Resources appear unavailable on tagged workers

### ISSUE THREAD

**Issue by code-engine** [concourse/concourse#152]
Hi,

Background:

What I'm trying to achieve, is that certain jobs should only be run on certain tagged workers.

When a worker is tagged in the concourse BOSH manifest like so:

```yaml
properties:
  groundcrew:
    tags: [web]
```

And then implemented in the CI config to make sure that certain tasks are only run on those specific nodes:

```yaml
- task: do-something
  tags: [web]
```

When there are no other nodes available (i.e. it is the only node in the worker pool), the following error occurs:

```
no workers satisfying: resource type 'git'

available workers: 
  - platform 'linux', tag 'web'
```

So it is partially working, in that jobs other than those tagged do not get executed on the worker, but the ATC is unable to determine that the worker has a required resource available.

When I look at the `worker.json` on the node, all of the required resources are there, including Git (it is the only resource required to perform the failing step, hence the only resource that is not satisfied. I believe it would occur with any built in resource). So it could be that it is not being sent in the beacon, it is not being read / passed correctly somewhere between the config and the ATC or something along these lines.

Any help greatly appreciated.

**Comment by vito** [comment]
ATC won't place things on tagged workers by default; this is because typically they're tagged for a reason (e.g. living in a private network or on a funny architecture) and shouldn't be considered equivalent to the rest.

You can add `tags` to your `get` steps as well, but the other problem would be that we don't have anywhere to put the checking container. We could add support for tagging resources as well (in fact maybe that would be a way to avoid tagging all `get`s and `put`s... hmm). Until then I'd just spin up another un-tagged worker for those containers.

**Comment by code-engine** [comment]
Hi vito,

Thanks for your response. Just to clarify before closing (for my own understanding and in case it may be helpful to someone else), if a worker is tagged, for example:

```yaml
- name: worker
  instances: 1
  resource_pool: workers
  templates:
    - {release: concourse, name: consul-agent}
    - {release: concourse, name: groundcrew}
    - {release: garden-linux, name: garden}
  networks: [{name: concourse}]
  properties:
    garden:
      listen_network: tcp
      listen_address: 0.0.0.0:7777

    consul:
      agent:
        servers: {lan: [*discovery_static_ip]}

    groundcrew:
      tags: [web]
```

Then that worker will not be able to perform any `get`s, `put`s or tasks unless it is tagged like so:

```yaml
- do:
  - get: some-resource
    trigger: true
    tags: [web]
  - task: so-something
    tags: [web]
    timeout: 10m
    file: path/to/task.yml
```

Is this correct? If so, I was a little confused by the error:

```
no workers satisfying: resource type 'git'

available workers: 
  - platform 'linux', tag 'web'
```

As it suggests that there are available workers, but none with a Git resource.

Thanks again
