### ISSUE TITLE
Container limitations on iOS and Windows should be better documented

### ISSUE THREAD

**Issue by chaodhib** [concourse/concourse#1523]
In the documentation and to be specific in [this page](https://concourse.ci/architecture.html#architecture-worker), it says:

> Workers have no important state configured on their machines, as everything runs in a container and thus shouldn't care about what packages are installed on the host (well, except for those that allow it to be a worker in the first place). This is very different from workers in other non-containerized CI solutions, where the state of packages on the worker is crucial to whether your pipeline works or not.

I feel like this part is a bit misleading for Windows and iOS because as far as I understand, any job running on a MacOS or Windows worker will not be running inside a container and will run natively inside the host OS.

Shouldn't this important detail be included in the doc until a time where those limitations are lifted?

Also linked to the issue:
https://stackoverflow.com/questions/38324845/concourse-with-windows-containers

**Comment by iswix-llc** [comment]
IMO the documentation is misleading.  It claims that "builds run every step in their own container, with their own dependencies, so workers never need to be configured in the first place".   This simply isn't true. 

I went through the trouble of creating a docker image for windows and trying to use it in a build only to find out that according to one concourse engineer  that containers are always linux vms.  He became very hostile / defensive with me when I tried to point out that  Windows has docker support.  It became evident to me at that point that windows workers aren't really a first class citizen in concourse.

**Comment by vito** [comment]
@iswix-llc It's true that Windows images are not a first-class citizen at the moment. The core team simply doesn't have the capacity to map out that path more, and no one has tried to contribute in this area.

Please don't attempt to call out or shame contributors for things like that without proof, though. It doesn't exactly help build an environment where we can work together. Keep in mind that OSS is give-and-take and that there are humans on the other side in every scenario; this sounds like such a petty thing that it'd be silly to be genuinely hostile about it. Perhaps they were drained from all the "take" that we deal with every day.

If you'd like to help improve the experience for Concourse on Windows feel free to open a discussion with us as @chaodhib has. Remember that this is all open-source. We're in this together; you don't work for us any more than we work for you, and if you're here there are probably a lot of common goals between us. There isn't some "Concourse Co." with a vendetta against Windows support and its advocates.

@chaodhib We should definitely flesh out the docs to paint a clearer picture of how things work on Darwin/Windows. One teensy detail I'd like to point out though is that even though they may run in the same host environment, Concourse's "containers" do at least present a clean room in terms of the bits exposed to the build. But you definitely don't get package management and process isolation, so we should call that out.

**Comment by iswix-llc** [comment]
@vito I have proof, except for the parts where he edited his comments after. It's not hard to find.  I simply asked about using containers on Windows. I didn't come looking for a fight.  Now I know where Windows stands and I use it accordingly.  

I would argue that concourse "containers" (it's a stretch to call it that IMO)   actually creates issues on windows by contributing to path length exceeded errors.  Perhaps there is a feature request in there to assign the path a temporary drive letter during the build to shorten the paths.  The only usefulness to it from my perspective is to not let you learn bad habits and force you to learn the way to move files around in a concourse world.  Otherwise you'll go over to the Linux platform and be in a for a shock.

**Comment by iswix-llc** [comment]
@chaodhib  one thing that should be possible that I haven't tried is to run the concourse worker inside a container.  This wouldn't be exactly the same but it might have some value.

**Comment by dukeluke16** [comment]
I have a workable prototype with Docker on Windows and Concourse.

I have this line in my userdata for a terraform'd concourse windows worker running in AWS.
```
Start-Process c:\concourse\concourse.exe "worker /work-dir C:\concourse /tsa-host ${tf_concourse_tsa_host}:2222 /tsa-public-key C:\concourse\ssh-keys\tsa_host_key.pub /tsa-worker-private-key C:\concourse\ssh-keys\worker_key ${tf_tags}"
```

Here's my pipeline...  I use Amazon Secrets Manager for the super secrets (repository key).  I use a script to inject some of the parameters.

```
fly -t mytarget set-pipeline -p build-code -c pipeline.yml -v "proxy-url=$proxyurl" -v "proxy-url=$proxyport" -v "github=$github" -v "organization=$organization" -v "project=$project" -v "container-image=dukeluke16/vs15-build:latest" -v "container-name=vs15-build-$organization-$project" -v "command=$command"
```

```
---
resources:
- name: code
  type: git
  source:
    uri: git@((github)):((organization))/((project)).git
    branch: master
    private_key: ((private-repo-key))
    https_tunnel:
      proxy_host: ((proxy-url))
      proxy_port: ((proxy-port))

jobs:
  - name: build
    plan:
    - get: code
    - task: docker-pull-and-mount
      tags: [windows]
      privileged: true
      config:
        platform: windows
        inputs:
        - name: code
        run:
          dir: code
          path: powershell
          args:
          - -c
          - |
            docker rm -f ((container-name)) 2>&1> $null
            docker pull ((container-image))
            docker run --rm -id --name ((container-name)) -v "${PWD}:c:\code" --workdir "c:\code" ((container-image))
    - task: build-and-test
      tags: [windows]
      privileged: true
      config:
        platform: windows
        inputs:
        - name: code
        run:
          dir: code
          path: powershell
          args:
          - -c
          - |
            docker exec -i ((container-name)) cmd "/C C:\BuildTools\Common7\Tools\VsDevCmd.bat && ((command)) && exit"
    ensure:
      do:
        - task: docker-cleanup
          tags: [windows]
          privileged: true
          config:
            platform: windows
            inputs:
            - name: code
            run:
              dir: code
              path: powershell
              args:
              - -c
              - |
                docker stop -t 3 ((container-name))
```
