### ISSUE TITLE
Problem accessing Vault with AppRole

### ISSUE THREAD

**Issue by janaurka** [concourse/concourse#1534]
Hi there!

I’m having a problem accessing Vault with the `AppRole` auth provider.
The important parts of the `manifest` look like this:

```
     vault:
       auth:
         backend: approle
         params:
           role_id: XXXX
           secret_id: XXXX
       path_prefix: "/concourse"
       tls:
         insecure_skip_verify: true
       url: https://10.217.148.XX:8200/
```

The pipeline basically looks like this:

```
jobs:

  - name: deploy
    serial: true
    plan:
      - aggregate:
        - get: infraservices-src
          trigger: true
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{concourse_image_repository}}
              username: {{docker_registry_username}}
              password: {{docker_registry_password}}
              insecure_registries: [ {{docker_insecure_registry}} ]
          inputs:
            - name: infraservices-src
```

and the variables point to `vault`, eg.:

```
#concourse/main/vault
vault_addr: ((vault.url))
```

The `git-resource` errors:

```
Finding variable 'git.key': Error making API request.

URL: GET https://10.217.148.55:8200/v1/concourse/main/logsearch-deployment/git
Code: 403. Errors:

* permission denied
```

The interesting thing is, when `ssh` to the vm with the `atc` running, using the exact same `role_id` and `secret_id`:

```
## Get the Token
# curl -k -XPOST -d '{"role_id":"XXXX","secret_id":"XXXX"}' https://10.217.148.55:8200/v1/auth/approle/login
{"request_id":"6b735823-f2f7-7a2f-7bd7-0983946641f3","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":null,"auth":{"client_token":"nope :)","accessor":"9e32ea3d-4c3e-1d30-a
cab-ab8bc697aa05","policies":["concourse","default"],"metadata":{},"lease_duration":1200,"renewable":true}}

## Get a non existing secret -> This errors out when using Concourse :(
# curl -k -XGET -H "X-Vault-Token: nope :)" https://10.217.148.55:8200/v1/concourse/main/logsearch-deployment/git
{"errors":[]}

## Get an existing secret
# curl -k -XGET -H "X-Vault-Token: nope :)" https://10.217.148.55:8200/v1/concourse/main/git
{"request_id":"aac600a5-6b38-0b7d-83c3-9cc57ae7be4d","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"some content"}
```

Since this works, this looks like a problem within `concourse`, right?

* Concourse version: 3.4 (also tested with 3.3.4)
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: vSphere
* Did this used to work? Nope :)
