### ISSUE TITLE
dedicated/preconfigured Vault just for storing pipeline secrets

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#1545]
# Feature Request

## What challenge are you facing?

Our team recently started using vault for credentials, specifically because we wanted to share our pipelines so that when folks with access run `fly get-pipeline` they do not see the sensitive information. The new vault integration feature appeared to be the only way to achieve this.

We never used vault before, so we set up a bosh deployment that includes concourse and vault together. Initially we thought we could describe the connection between the vault and concourse releases as a bosh link, but only later noticed that the concourse release does not consume a bosh link for vault. So we realized we would need to use a static IP for our vault server, which is not beautiful. Moreover it took quite a while to figure out how to get all the SSL certificates working properly to manage communication between concourse and vault, when we really didn't need to know about it since it was all happening between VMs on the same subnet.

We wrote some scripts to help automate our vault-related tasks (unsealing, auth, writing a policy for concourse to access secrets, writing secrets as pipelines develop), and we wound up with a deployment looking like this (not valid, just the gist) so we can use `bosh int` to generate the gory SSL stuff:

```
...

variables:
- name: default_ca
  type: certificate
  options:
    is_ca: true
    alternative_names: ["127.0.0.1"]
- name: vault_client_ssl
  type: certificate
  options:
    ca: default_ca
    alternative_names: ["127.0.0.1"]
    extended_key_usage:
    - client_auth
- name: vault_server_ssl
  type: certificate
  options:
    ca: default_ca
    alternative_names: ["127.0.0.1"]

releases:
- name: concourse
  version: latest
- name: vault
  version: latest

instance_groups:
- name: vault
  networks: [{name: private, static_ips: [10.0.31.190]}]
  jobs:
  - name: vault
    release: vault
    properties:
      tls: ((vault_server_ssl))
      concourse: ((vault_client_ssl))

- name: web
  jobs:
  - name: atc
    release: concourse
    properties:
      vault:
        url: https://10.0.31.190:8200
        auth:
          backend: cert
        tls:
          ca_cert: ((default_ca))
          client_cert: ((vault_client_ssl))
...
```

## A Modest Proposal

Maybe the [docs](http://concourse.ci/creds.html#vault) could include a link to [this helpful example](https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/concourse-pipeline-patterns/vault-integration). This would certainly have removed some of the headache of figuring out how to get these two services talking to each other; but even so this example uses a periodic token to secure the communication between vault and concourse, whereas we wanted to use SSL certificates.

Maybe the bosh release could be configured to use a bosh link for the vault connection if it is provided. This just seems like a sensible use of the bosh links feature.

Finally (and most ideal of all), there could be a default behaviour or flag to set in the bosh release that would automatically run a vault server and configure all the communication channels between concourse and vault so that nobody had to think about it and you just got a secure credential store for free!

In general, it would be great to have some communication with the Concourse team regarding our approach to vault and its potential to inform future features -- in particular it doesn't seem too difficult to make a PR for the bosh link feature.
