### ISSUE TITLE
task config not found.

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#1562]
Hi there!

# Bug Report

After last time I upgraded concourse I am seeing a lot of "task config 'devops-repo/oasis-pipeline/tasks/prepopulate-nexus.yml' not found" the devops-repo is passed as an input to the task that fails, and it appears to be cloned before the failing step. Any ideas?

![screen shot 2017-09-05 at 14 32 15](https://user-images.githubusercontent.com/2795016/30061406-7fb58af0-9247-11e7-9415-ba02e4dbfbe3.png)

The following can also be handy:

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): Binary
* Did this used to work? Not seen error before

**Comment by jtarchie** [comment]
Does the file actually appear in that checked out SHA of the `devops-repo`?

**Comment by devdavidkarlsson** [comment]
it does, I am trying to intercept the build job to look in the actual concourse checkout but I am having some issues there:

fly intercept -t dev_refactor -j oasis_dev/unit-test-client

no containers matched your search parameters!

**Comment by devdavidkarlsson** [comment]
Where there any breaking changes to the intercept command the last few releases?

**Comment by jtarchie** [comment]
> Where there any breaking changes to the intercept command the last few releases?

Nope.

**Comment by jtarchie** [comment]
@devdavidkarlsson, are you able to provide a reproducible example? I'm having no luck reproducing.

**Comment by topherbullock** [comment]
@devdavidkarlsson Trying to validate this as an issue; we need some more details to do so. 

Here's some clarifying questions that might help us out:
- What type of resource is this task being pulled in by? 
- Is that resource get an input to the task? 
- What type of image is the task using?

**Comment by devdavidkarlsson** [comment]
From pipeline.yml:

```
#Unit test frontend:
- name: unit-test-client
  public: true
  plan:
  - aggregate:
    - get: node_modules_cache
      passed: [cache]
      trigger: true
    - get: oasis-client-repo
      passed: [cache]
      trigger: true
    - get: devops-repo
    - get: docker-registry-node
    - get: docker-registry-protractor
  - task: karma-test
    file: devops-repo/pipelines/oasis/tasks/test-client.yml
    image: docker-registry-protractor
    params:
      NEXUS_URL: {{nexus-url}}
      NEXUS_USER: {{nexus-user}}
      NEXUS_PASS: {{nexus-pass}}
```
