### ISSUE TITLE
setuid root executables lose sticky bit above Concourse version 3.0.1

### ISSUE THREAD

**Issue by thardeck** [concourse/concourse#1569]
The setuid issue as described in #802 is not fixed yet. We are experiencing this issue with every Concourse version after 3.0.1.

The issue happens with baggeclain btrfs but also overlayfs. I have reproduced it with btrfs and Concourse 3.4.1 and also in the Concourse Lite Vagrant Box 3.2.1 which uses overlayfs I suppose.

Concourse Lite 3.4.1 had DNS issues so I could not test it there.

This is the error message:

```
=== Configuring 'base_debootstrap' stage ===
== Started Thu Sep  7 14:41:07 UTC 2017 ==
sudo env  /mnt/stemcells/null/null/ubuntu/build/build/stages/base_debootstrap/config.sh /mnt/stemcells/null/null/ubuntu/build/build/etc/settings.bash 2>&1
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

For help with stemcell building, see: <https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/README.md>

rake aborted!
Failed: 'sudo env  /mnt/stemcells/null/null/ubuntu/build/build/stages/base_debootstrap/config.sh /mnt/stemcells/null/null/ubuntu/build/build/etc/settings.bash 2>&1' from /tmp/build/e1bf2b15/src, with exit status 256

 sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set/home/ubuntu/.gem/ruby/2.3.1/gems/bosh-core-1.3262.24.0/lib/bosh/core/shell.rb:52:in `report'
```

The issue can be reproduced with this manifest. It works fine in 3.0.1 but no version above.
```
---
jobs:
  - name: build-os-image-ubuntu-trusty
    serial_groups: [builds]
    plan:
      - aggregate:
        - get: src
          trigger: true
        - get: ci
          trigger: true
      - task: build-os-image
        file: ci/tasks/build-os-image-ubuntu-centos.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      ubuntu
          OPERATING_SYSTEM_VERSION:   trusty

resources:
  - name: ci
    type: git
    check_every: 30m
    source:
      uri: https://github.com/SUSE/bosh-linux-stemcell-builder-ci.git
      branch: master

  - name: src
    type: git
    check_every: 30m
    source:
      uri: https://github.com/SUSE/bosh-linux-stemcell-builder.git
      branch: opensuse_stemcell_with_patched_go_agent
```
