### ISSUE TITLE
Concourse doesn't work with AWS ECR after upgrade to 3.4.0 (error: "no basic auth credentials")

### ISSUE THREAD

**Issue by k0nstantinv** [concourse/concourse#1571]
# Bug Report

We have been using Concourse for 5 month and we really like it. First of all, thanks for your work!
After upgrade to 3.4.0 communication between our concourse and AWS ECR is completely lost. Concourse could not check resources. The job exited with error:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch manifest: Get https://xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/v2/xxxxxxxxxxxx/manifests/xxxxxx: no basic auth credentials
```
We use docker-image resource with AWS repositroy:
```
- name: xxxxxxxxxxxx
  type: docker-image
  source:
    repository: xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxxxxxx
    tag: latest
    aws_access_key_id: {{aws-access-key-id}}
    aws_secret_access_key: {{aws-secret-access-key}}
  tags: [shared]
```
credentials are located in vars .yml file. 

this is how we load pipelines:
```$ fly -t <target> sp -p <pipeline-name> -c < pipeline .yml file path> -l <vars .yml file path>```

Git resources with Bitbucket uri works fine:
```
- name: xxxxxxxxxxxxxx
  type: git
  source:
    uri: git@bitbucket.org:xxxxxx/xxxxxxxxxx.git
    branch: master
    private_key: {{private-repo-key}}
  tags: [shared, prod]
```

We didn't make any changes in .yml files, just upgrade concourse, workers, fly to the latest version. We checked all possible permissions in AWS, gave FullAccessECR permissions for user used by concourse, gave all possible permissions to image repository, our network engineers opened all ports between workers and ATC, to internet, and wherever it's possible. 

Problem with AWS ECR still persists. We have shut down all the workers except for one:
```
$ fly -t <target> workers 
name                        containers  platform  tags          team  state    version
concourse-worker-04.xxxxxx  6           linux     shared, prod  none  running  1.1
```
Our installation:
1) ATC via docker-compose
2) PostgreSQL via docker-compose
3) some workers via binary

Hope for your help! We are ready  to show any logs that are needed, but we didn't find anything useful there...

this issue duplicates this https://github.com/concourse/docker-image-resource/issues/138
PS: Sorry for the duplicate. However, there were no updated information for 2 weeks.
