### ISSUE TITLE
Quick start & Hello world not working!

### ISSUE THREAD

**Issue by emichaf** [concourse/concourse#1581]
**Bug Report**

Tried the Quick start with docker.compose successfully. Instruction followed at: https://concourse.ci/docker-repository.html

Then tried the Hello, world! example:
https://concourse.ci/hello-world.html

**Result:**
..
Successfully pulled ubuntu@sha256:34471448724419596ca4e890496d375801de21b0e67b81a77fd6155ce001edad.

runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/worker-state/3.4.1/assets/bin/init\\\" to rootfs \\\"/worker-state/volumes/live/68196365-b072-445b-4bd1-d10040bbb944/volume/rootfs\\\" at \\\"/worker-state/volumes/live/68196365-b072-445b-4bd1-d10040bbb944/volume/rootfs/tmp/garden-init\\\" caused \\\"open /worker-state/volumes/live/68196365-b072-445b-4bd1-d10040bbb944/volume/rootfs/tmp/garden-init: permission denied\\\"\""

**Comment by srs** [comment]
I have the same problem too. It seems that the owner is `4294967294` for the `volume` folder under `/worker-state/volumes/live/<uid>`.

Any ideas?

**Comment by jtarchie** [comment]
@emichaf on what platform are you using the `docker-compose` on? Local, docker swarm, k8, etc?

**Comment by awsum** [comment]
@jtarchie have same issue running on local.

**Comment by jtarchie** [comment]
Please provide more information about your deployment. I am unable to reproduce.

For example:
* What version of docker?
* What version docker compose?
* What OS are you on?
* etc.

**Comment by bewatts** [comment]
I'm encountering the same problem, using the [concourse-lite](http://concourse.ci/concourse-lite.html) instructions

OS: running on macOS Sierra 10.12.6 (16G29)
```
balboa:ci-crocus pivotal$ docker -v
Docker version 17.07.0-ce, build 8784753
```

**Comment by vito** [comment]
@bewatts Your task is missing an `image_resource`, so it's trying to use Garden's configured default rootfs, which won't work properly.

Try this:

```yaml
resources:
- name: crocus
  type: git
  source:
    uri: git://10.80.135.23/crocus
    branch: master

jobs:
- name: test-app
  plan:
  - get: crocus
  - task: tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: ["Hello, world!"]
```
