### ISSUE TITLE
Concourse Worker always executes iptables

### ISSUE THREAD

**Issue by cetra3** [concourse/concourse#1587]
When trying to run the concourse worker on linux, it appears to be making adjustments to the iptables.

Trying to run with `--garden-skip-setup` does not turn off this behaviour.  I would assume that this would be skipped with this cli argument.

**Comment by vito** [comment]
I'm not sure what you're trying to do by having it not run `iptables`. That's a required part of Garden's networking stack. What problem are you facing, or what are you trying to do?

**Comment by cetra3** [comment]
I'd like it to not run iptables.  We have existing iptables rules that are conflicting. 
 Why do you need to run iptables to spool up a few docker containers exactly?

What I was trying to do was just to run a worker without dependency on docker, using our standard image.  But I don't think this is possible at the moment unless you are using mac or windows workers.

**Comment by vito** [comment]
> Why do you need to run iptables to spool up a few docker containers exactly?

Docker itself uses `iptables`, so that shouldn't be very surprising. Networking is a pretty fundamental aspect of containerization, and involves `iptables`. Concourse don't use Docker, though; it uses [Garden-runC](https://github.com/cloudfoundry/garden-runc-release) for Linux. Workers don't depend on Docker. We run them all the time with the binaries, BOSH, or on bare metal.

Could you go into more detail as to what conflicts you're running into? The network range it sets up is configurable with `--garden-network`, if that's all your problem is. Again, please go into more detail on the actual *problem* you're running into, and maybe we can help with that. As it stands the issue is posed as an [X/Y problem](http://xyproblem.info/). There may be a flag to fix it, or an issue to open on Garden-runC, but I can't know how to help you without more information.

**Comment by cetra3** [comment]
You're right. It is an X, Y Problem.  I was investigating an appropriate CI solution which would marry closer to our existing environment, and then discovered when testing that the CI worker is doing a lot more than what is mentioned in the documentation.

Currently there is no indication that docker is a hard requirement on linux if you read through the [manual installation guide](http://concourse.ci/binaries.html).  It does mention Garden though, but that just points to some github project, which itself does not mention docker in the main readme, just that it's a container creation management system.

As it stands, I can't run this:
```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      run:
        path: echo
        args: ["Hello, world!"]
```

But this works fine on Mac OS X.

**Comment by vito** [comment]
Docker is not a hard requirement on Linux. The documentation doesn't mention everything because the binaries package everything they need, automate all the setup, and 99.9% of the time it doesn't matter; it's not a good idea to help people get lost in the details.

Your example doesn't have an `image_resouce` in the task, so that may be one problem. Could you provide the error message you're seeing, and where it's occurring?

It should look like how we have it on the front page of our site:

```yaml
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
```

If it was removed because you don't want Docker, it should make no difference; you don't need Docker installed or running on the worker for that to work. Resources run in containers, and the `docker-image` resource's container image brings its own `docker`.

**Comment by cetra3** [comment]
Do I require an `image_resource` in the task to run it?  Shouldn't the absence of that just run on the OS/VM the worker is running on as it does on OSX/Windows?

Is there a way to specify a different type of `image_resource` or is `docker-image` the only type supported?

BTW this works on Mac OSX just fine:

```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: darwin
      run:
        path: echo
        args: ["Hello, world!"]
```
