### ISSUE TITLE
Implicit GET after a tagged PUT does not seem to inherit the tag

### ISSUE THREAD

**Issue by derwei** [concourse/concourse#1590]
We have a custom resource that can only be accessed on an internal network. So we need to run it on a tagged worker. 

When we do a PUT to the resource with a tagged worker, the PUT step succeeds but the implicit GET step will give the following error

```
custom resource type '<resource>' version not found
```

Our pipeline looks like this:

```
resource_types:
- name: custom-resource
  type: docker-image
  source:
    <params>

resources:
- name: resource-name
  type: custom-resource
  source:
  	<params>
  tags:
  - tagged-worker

jobs:
- name: do-something
  plan:
  - put: resource-name
    params:
      <params>
    tags:
    - tagged-worker
```

When we run this pipeline on the following concourse setup, we get the error

```
Concourse A setup
- tagged worker on internal network
- untagged workers on external network (no access to internal network)
```

When we run the same pipeline on another concourse setup, it works

```
Concourse B setup
- tagged worker on internal network
- untagged workers also on internal network
```

* Concourse version: 3.4.1 (concourse B setup) / 3.4.2 (concourse A setup)

**Comment by derwei** [comment]
Update: Seems like this maybe a resource-type tagging issue...
Context: We have a custom resource that we host on an internal docker registry.

Tried both pipelines on a concourse that is on an external network, with untagged workers on external network but tagged workers on internal. (Concourse A setup above)

Pipeline setup A (Not working):
```
resource_types:
- name: custom-resource
  type: docker-image
  source:
    <params for internal docker>
  tags: [tagged-worker]
```

Pipeline B setup (working):
```
resource_types:
- name: custom-resource
  type: docker-image
  source:
    <params for dockerhub>
```


I no longer get the `custom resource type '<resource>' version not found` error.
