### ISSUE TITLE
Latest Releases api url points to version 2.2.2

### ISSUE THREAD

**Issue by stevewallecs** [concourse/concourse#1639]
# Bug Report

The api url https://api.github.com/repos/concourse/fly/releases/latest returns metadata for the 2.2.2 cli release.

```
curl -s https://api.github.com/repos/concourse/fly/releases/latest 
{
  "url": "https://api.github.com/repos/concourse/fly/releases/4243543",
  "assets_url": "https://api.github.com/repos/concourse/fly/releases/4243543/assets",
  "upload_url": "https://uploads.github.com/repos/concourse/fly/releases/4243543/assets{?name,label}",
  "html_url": "https://github.com/concourse/fly/releases/tag/v2.2.2-rc.16",
  "id": 4243543,
  "tag_name": "v2.2.2-rc.16",
  "target_commitish": "master",
  "name": "v2.2.2-rc.16",
```

**Comment by jtarchie** [comment]
We don't mark fly releases as a final release. Please pull those from the releases under [this](https://github.com/concourse/concourse/releases) repo. It is the one source of truth.

**Comment by jtarchie** [comment]
Here is what we use in one of our pipelines to pull from it:

```
- name: fly
  type: github-release
  check_every: 1h
  source:
    user: concourse
    repository: concourse
    access_token: ((concourse_github_dummy.access_token))
```
