### ISSUE TITLE
Docker build takes a long time (13 min.) to start

### ISSUE THREAD

**Issue by eembsen** [concourse/concourse#1642]
I am using the latest concourse (just downloaded) and have a pipeline running that uses 2 git repos and produces a docker image that is uploaded to a private registry, nothing special. The problem is that it takes an awful lot of time for the pipeline to actually start building the image, After checking the repos, which is done in less than a minute, it takes another 13 to 15 minutes before it starts the docker build (?) Why? What can I do to speed this up?

* Concourse version:
3.5.0

* Deployment type (BOSH/Docker/binary):
Docker

* Infrastructure/IaaS:
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

* Browser (if applicable):
Firefox

* Did this used to work?
?

**Comment by jtarchie** [comment]
@eembsen, this is usually do to having to mount a rather large file system being mounted into the container. More because the docker-image resource is a privileged container. 

Are you using overlayfs?

**Comment by eembsen** [comment]
Hi JT,

Here is some Docker info:

Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true

So I am AUFS.

And my Ubuntu install is on one large partition of 1.8 Tb

Cheers,
Erwin

**Comment by jtarchie** [comment]
Sorry, I meant what do you have `baggageclaim` set to?

**Comment by eembsen** [comment]
I have not set baggageclaim, don't know how to do that. I am on a standard Docker concourse install using docker-compose.yml from the website

**Comment by eembsen** [comment]
Please tell me what info you need and how to retrieve that. I would like to have this problem solved as quickly as possible. Otherwise I might have to revert to Jenkins and I do not want that.

**Comment by jtarchie** [comment]
If you don't mind experimenting.

On the `concourse worker` try this CLI option:

```
          --baggageclaim-driver=[detect|naive|btrfs|overlay] Driver to use for managing volumes. (default: detect)
                                                             [$CONCOURSE_BAGGAGECLAIM_DRIVER]
```

I'm willing to bet it auto detected to `overlay`, which is more stable, but usually has problems with lots of files (your git repo).

**Comment by eembsen** [comment]
JT, you saved my day. I set CONCOURSE_BAGGAGECLAIM_DRIVER to naive like this:

```
  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_BAGGAGECLAIM_DRIVER: naive
```

and the build time is down to 4 minutes and 50 seconds. Thank you so much!!!
