### ISSUE TITLE
Support adding hooks at the job level, rather than individual steps

### ISSUE THREAD

**Issue by vito** [concourse/concourse#166]
e.g.:

```yaml
name: my-job
plan:
- get: something
- task: run-something
on_failure: {...}
on_success: {...}
ensure: {...}
```

would be equivalent to:

```yaml
name: my-job
plan:
- do:
  - get: something
  - task: run-something
  on_failure: {...}
  on_success: {...}
  ensure: {...}
```

**Comment by robdimsdale** [comment]
+1

**Comment by bendodd** [comment]
+1

**Comment by mtekel** [comment]
+1. I'd like to be add `ensure` into `do` or `aggregate` blocks (and not directly to each task).

**Comment by mtekel** [comment]
As it turns out, it does what I need to do in concourse 0.76, but the interface only shows ensure block for the last task (yet it works as ensure block for whole do):
```
      - do:
        - task: create-temp-user
          file: paas-cf/concourse/tasks/create_admin.yml
          config:
            params:
              PREFIX: smoketest-user

        - task: smoke-tests-config
          file: paas-cf/concourse/tasks/smoke-tests-config.ymll

        - task: smoke-tests-run
          file: paas-cf/concourse/tasks/smoke-tests-run.yml
        ensure:
          task: remove-temp-user
          file: paas-cf/concourse/tasks/delete_admin.yml
```
renders as
![image](https://cloud.githubusercontent.com/assets/483891/15114312/42e1b3e8-15f1-11e6-9ff3-74c2f8709a93.png)
