### ISSUE TITLE
Concourse credhub not resolving values

### ISSUE THREAD

**Issue by gdenn** [concourse/concourse#1685]
# Bug Report
Concourse version: 3.5.0
Deployment Type: Bosh cluster
IaaS: vSphere
Browser: chrome

hi, i deployed Concourse with my credhub properties as described [here](http://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=3.5.0). Here is my [manifest](https://gist.github.com/gdenn/aa27e6deba775f328b3205b3f7fd5001).

The deployment showed no problems afterwards so i guess the credentials have been correct (also double checked).

I import my credentials to credhub with `credhub import -f credentials.yml` using this import [file](https://gist.github.com/gdenn/3134b970d1262005eab1a95464e0d0f7). 

According to the documentation [here](https://concourse.ci/creds.html) i imported my credentials into credhub using `/concourse/main/runtime-acceptance/value_xyz`

When i upload my pipeline with `fly sp runtime-acceptance -c runtime-acceptance.yml` i receive this error at the web UI

```
Expected to find variables: s3_pg_backup_access_key_id
s3_pg_backup_secret_access_key
s3_pg_bucket_name
s3_pg_region
```

This is the part of the pipeline which causes the error message.

```
- name: uaadb-backup
  type: s3
  source:
    bucket: ((s3_pg_bucket_name))
    access_key_id: ((s3_pg_backup_access_key_id))
    secret_access_key: ((s3_pg_backup_secret_access_key))
    region_name: ((s3_pg_region))
    versioned_file: uaadb-backup.sql
```

`credhub get --name /concourse/main/runtime-acceptance/s3_pg_backup_access_key_id` reports correct credentials.
