### ISSUE TITLE
Epic: spatial resource flows

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1707]
# Feature Request

## What challenge are you facing?

Concourse makes it very easy to model changes over time. Resources do this for you; you point them at a given source of truth, and it'll let you know everything that happened.

Some workflows, however, can't just be modeled as change over time. Multiple branches of a repo, or pull requests to a repository, are over *space*, not *time*. They are parallel pipelines, which today are hard to manage, and impossible to correlate (you cannot fan-in).

Build matrixes are another example of wanting to run over many spaces (i.e. versions of a product). This can be done today, within a pipeline, but results in a massive pipeline with every combination explicitly configured.

## A Modest Proposal

This issue ties together #1172, #1176, and introduces the ability to have arbitrary build matrixes within one pipeline, which should dramatically improve the experience for people testing many variations/combinations.

Resources would have an additional interface to discover *spaces*. What these are depends on the resource. For the `git` resource, it would return each branch. For a resource tracking pull requests, it would return each PR number. For a resource tracking a semver'd product, it'd emit one space for each supported version line, at each granularity (i.e. `2, 2.1, 2.0, 1, 1.9, 1.8, ...`).

All versions would then be for a respective space, and Concourse would detect all versions across all spaces.

Jobs could then specify which spaces their `get` and `put` steps should run against. This would automatically "expand" into a job for each combination of spaces described by its steps. They can say `all` for all spaces (dynamically discovered), a list of static space names (e.g. `[2.0, 1.9]`), or a list of space name filters (e.g. `[feature/*]` for feature branches).

### Run against all branches of a repo, but only progressing one to the rest

In the simplest case, this makes it easy for me to have CI run against all branches in my side-project. It would just be a matter of adding `spaces: {booklit: all}` to the job:

```yaml
jobs:
- name: unit
  public: true
  spaces: {booklit: all}
  plan:
  - get: booklit
    version: every
    trigger: true
  - task: unit
    file: booklit/ci/test.yml

- name: rc
  public: true
  serial_groups: [version]
  plan:
  - get: booklit
    passed: [unit]
    trigger: true
  - get: version
    params: {pre: rc}
  - put: version
    params: {file: version/version}

- name: ship
  public: true
  serial_groups: [version]
  plan:
  - get: booklit
    passed: [rc]
  - get: final-version
    resource: version
    passed: [rc]
    params: {bump: final}
  - get: release-notes
  - put: version
    params: {file: final-version/version}
  - put: booklit-rel
```

### Run multiple versions against all branches

In more complicated cases, you may want to run against all branches, and for each branch run against different versions of the language the project is written in:

```yaml
jobs:
- name: unit
  spaces:
    my-repo: all
    ruby: [2.0, 1.9]
  plan:
  - get: my-repo
  - get: ruby
  - task: unit
    image: ruby
    file: my-repi/ci/unit.yml
```

### Propagating through a pipeline

Each combination of spaces progresses through the pipeline on its own accord. This means that if the case of `ruby-1.9` above fails, `ruby-2.0` can continue on its own. This seems in line with how most people would want these "dynamic pipelines" to work as it lets you get the most feedback possible for each combination. It's also how things would work if they were explicitly configured as different jobs/pipelines.

```yaml
jobs:
- name: unit
  spaces:
    my-repo: [master, develop]
    ruby: [2.0, 1.9]
  plan:
  - get: my-repo
  - get: ruby
  - task: unit
    image: ruby
    file: my-repi/ci/unit.yml

- name: integration
  spaces:
    my-repo: [master, develop]
    ruby: [2.0, 1.9]
  plan:
  - get: my-repo
    passed: [unit]
  - get: ruby
    passed: [unit]
  - task: integration
    image: ruby
    file: my-repo/ci/integration.yml
```

Here's how this works: each resource mentioned in a plan is pinned to a single space. This space applies to all `get` and `put` steps, but *also* the spaces used in jobs that `passed` constraints refer to, when those jobs use the same resource.

This means that this:

```yaml
- name: integration
  spaces:
    my-repo: [master, develop]
  plan:
  - get: my-repo
    passed: [unit]
```

...expands to two jobs, looking something like:

```yaml
- get: my-repo{master}
  passed: [unit{my-repo:master,ruby:2.0}, unit{my-repo:master,ruby:1.9}]

- get: my-repo{develop}
  passed: [unit{my-repo:develop,ruby:2.0}, unit{my-repo:develop,ruby:1.9}]
```

...but then by adding a `get: ruby` with its own spaces, like so:

```yaml
- name: integration
  spaces:
    my-repo: [master, develop]
    ruby: [2.0, 1.9]
  plan:
  - get: my-repo
    passed: [unit]
  - get: ruby
    passed: [unit]
```

...that results in more combinations, each with their `passed` constraints reduced to the same spaces that their peer `get` steps are pinned to:

```yaml
- get: my-repo{master}
  passed: [unit{ruby:2.0,my-repo:master}]
- get: ruby{2.0}
  passed: [unit{ruby:2.0,my-repo:master}]

- get: my-repo{master}
  passed: [unit{ruby:1.9,my-repo:master}]
- get: ruby{1.9}
  passed: [unit{ruby:1.9,my-repo:master}]

- get: my-repo{develop}
  passed: [unit{ruby:2.0,my-repo:develop}]
- get: ruby{2.0}
  passed: [unit{ruby:2.0,my-repo:develop}]

- get: my-repo{develop}
  passed: [unit{ruby:1.9,my-repo:develop}]
- get: ruby{1.9}
  passed: [unit{ruby:1.9,my-repo:develop}]
```

### Explicitly fanning in

The above behavior can be configured, and often should be in the case of shipping something, as it can otherwise quickly lead to fanning-out, something you *may* not want for publishing your final artifacts.

When it comes to shipping, there are a few differences:

* You probably only want to ship the `master` branch, not all of them.
* You may want to only ship things that passed all versions of `ruby`.

This can be done like so:

```yaml
- name: ship
  spaces:
    my-repo: [master]
  plan:
  - get: my-repo
    passed: [integration: all]
  - put: rubygems
```

There's actually a few things to explain here. The `integration: all` means "get only versions from the `master` branch, having passed all cases of `integration` in which it was present". However, even if we hadn't specified it, that's also the only reasonable interpretation. We're being explicit, because there's also a case where you may want to get a single version of `ruby` but still do a fan-in, not just "continue" that version's sub-pipeline.

One use case for this is when you want the pipeline to have succeeded against both versions but only need one to perform some menial shipping task. In that case you'd end up with something like:

```yaml
- name: ship
  spaces:
    my-repo: [master]
    ruby: [2.0]
  plan:
  - get: my-repo
    passed: [integration: all]
  - get: ruby
  - task: build-erb-release-notes
    image: ruby
    task: my-repo/ci/build-release-notes.yml
  - put: rubygems
```

Normally, the presence of `ruby-2.0` would have selected for that space within the passed constraints of the `my-repo` step. By saying `all`, it prevents that reduction, preserving the fan-in.

## How will this look in the UI?

idk lol

@Lindsayauchin halp
