### ISSUE TITLE
[Multi-Pipeline View] Hanging on circular pipelines

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#1710]
Given a pipeline configured as follows:

```yaml
---
resources:
- name: some-resource
  type: docker-image
  source: {repository: busybox}

jobs:
- name: job-a
  plan:
  - get: some-resource
    passed: [ job-b ]

- name: job-b
  plan:
  - get: some-resource
    passed: [ job-a ]
```

This is supported by `fly` and the pipeline UI, but it breaks the dashboard (it loops forever trying to compute the thumbnail).
