### ISSUE TITLE
Trigger on a subset of versions (or force a check on get)

### ISSUE THREAD

**Issue by william-tran** [concourse/concourse#1719]
# Feature Request

## What challenge are you facing?

I have a git repo `my-repo`:
```
|---trigger-on
|---still-relevant
``` 

And a job `build` that needs files in both `trigger-on` and `still-relevant`. I want:

a) `build` to automatically trigger only on changes to `my-repo/trigger`. 
b)  to be able to manually trigger `build`
c)  to use the `HEAD` of `my-repo` branch `master` in all cases.

If I configure `paths:` on the `git-resource` to be `["trigger-on"]` I get a) but not c), eg. if the latest change was to `still-relevant`, that won't be picked up until a subsequent change to `trigger-on` is made. If I configure two separate resources `trigger-build` and `my-repo`, where `trigger-build` has `paths:` but isn't used as input, and `my-repo` doesn't have `paths:` and is used as input to the task, then when `trigger-build` triggers `build`, sometimes `my-repo` isn't at the latest version which triggered `trigger-build`. I guess I could get my task to figure out which resource is most recent and use that, but that's kinda lame.

## A Modest Proposal

Either a way to force a resource check on [get](https://concourse.ci/single-page.html#get-step) eg:
```
- get: trigger-build
  trigger: true
- get: my-repo
  force-check: true
```

Or a way for resources to say that some versions are triggers and others aren't (but still available).

**Comment by jtarchie** [comment]
Every time a `get` happens it always performs a `check` to pull the latest version. You can also `trigger` to say some resources are only a trigger.

**Comment by william-tran** [comment]
When I had my job set up like this:
```
- get: trigger-build
  trigger: true
- get: my-repo
- task: build
  config:
    inputs:
    - my-repo
...
```
`trigger-build` would sometimes have a version ahead of `my-repo`.

**Comment by william-tran** [comment]
>Every time a get happens it always performs a check to pull the latest version.
@jtarchie I'm pretty sure this doesn't happen. I'm using 3.5.0, and with the following pipeline:

```
resources:
- name: trigger
  type: git
  check_every: 10s
  source:
    uri: https://github.com/william-tran/pipeline-test.git
- name: repo
  type: git
  check_every: 1000h
  source:
    uri: https://github.com/william-tran/pipeline-test.git
jobs:
- name: output-readme
  plan:
  - get: trigger
    trigger: true
  - get: repo
  - task: output-readme
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: repo
      run:
        path: /bin/sh
        args: ["-c", "cat repo/README.md"]
```

`repo` is always stuck at the first version.
