### ISSUE TITLE
[Feature] Implement TCPKeepAlive for db session to add robustness in case of network glitches.

### ISSUE THREAD

**Issue by CyrilPeponnet** [concourse/concourse#1738]
Somehow using a docker network overlay, after an idle time, the session hang for 15min.

# Bug Report

Symtoms:

```
141  Backups/Backup           39     started    2017-10-23@10:33:06-0700  n/a                       14m6s+
140  Backups/Backup           38     succeeded  2017-10-22@11:22:03-0700  2017-10-22@11:38:01-0700  15m58s
139  Backups/Backup           37     succeeded  2017-10-21@11:21:34-0700  2017-10-21@11:37:33-0700  15m59s
136  Backups/Backup           36     succeeded  2017-10-20@16:37:40-0700  2017-10-20@16:38:11-0700  31s
135  Backups/Backup           35     succeeded  2017-10-20@16:31:56-0700  2017-10-20@16:32:24-0700  28s
```

From time to time, jobs are hanging in started mode.

and

```
curl --cookie ATC-Authorization="Bearer ..." http://127.0.0.1:8080/api/v1/builds/85/events
```
hangs for 15 minutes as well.

Here is the workflow

1/ I start ATC, I get logged through the UI, checking for a job history, events is hanging (same with curl from the ATC itself)
2/ After ~15min when `received-atc-shutdown-message` shows in ATC logs, the build logs appears.
3/ Everything will work fine until I stop browsing the builds
4/ After a while, we are back to step 1/

here are the full logs: (20 minutes logs including a hang).

https://gist.github.com/CyrilPeponnet/cbd3983d81a18b2839f578f15c3c1472

and here is a log in debug when it unclog:

```
{"timestamp":"1508519181.602664948","source":"atc","message":"atc.build-tracker.track.start","log_level":0,"data":{"session":"18.708"}}
{"timestamp":"1508519181.602728367","source":"atc","message":"atc.collector-runner.lock-task.tick","log_level":0,"data":{"session":"20.235","task-name":"collector"}}
{"timestamp":"1508519181.602736712","source":"atc","message":"atc.build-reaper-runner.lock-task.tick","log_level":0,"data":{"session":"32.235","task-name":"build-reaper"}}
{"timestamp":"1508519181.624410391","source":"atc","message":"atc.build-tracker.track.done","log_level":0,"data":{"session":"18.708"}}
{"timestamp":"1508519181.624785900","source":"atc","message":"atc.collector-runner.lock-task.acquire.acquired","log_level":0,"data":{"id":[3,-824445620],"session":"20.235.1","task-name":"collector"}}
{"timestamp":"1508519181.624813080","source":"atc","message":"atc.collector-runner.lock-task.run-task","log_level":0,"data":{"session":"20.235","task-name":"collector"}}
{"timestamp":"1508519181.624830961","source":"atc","message":"atc.build-collector.start","log_level":0,"data":{"session":"22"}}
{"timestamp":"1508519181.641266108","source":"atc","message":"atc.build-reaper-runner.lock-task.acquire.acquired","log_level":0,"data":{"id":[3,997540461],"session":"32.235.1","task-name":"build-reaper"}}
{"timestamp":"1508519181.641296387","source":"atc","message":"atc.build-reaper-runner.lock-task.run-task","log_level":0,"data":{"session":"32.235","task-name":"build-reaper"}}
{"timestamp":"1508519181.642317533","source":"atc","message":"atc.build-collector.done","log_level":0,"data":{"session":"22"}}
{"timestamp":"1508519181.642338991","source":"atc","message":"atc.worker-collector.run.start","log_level":0,"data":{"session":"23.235"}}
{"timestamp":"1508519181.660918474","source":"atc","message":"atc.worker-collector.run.done","log_level":0,"data":{"session":"23.235"}}
{"timestamp":"1508519181.663983583","source":"atc","message":"atc.build-reaper-runner.lock-task.release.released","log_level":0,"data":{"id":[3,997540461],"session":"32.235.2","task-name":"build-reaper"}}
{"timestamp":"1508519181.713765383","source":"atc","message":"atc.container-collector.run.start","log_level":0,"data":{"session":"29.235"}}
{"timestamp":"1508519181.719601393","source":"atc","message":"atc.container-collector.run.found-containers-for-deletion","log_level":0,"data":{"created-containers":[],"creating-containers":[],"destroying-containers":[],"session":"29.235"}}
{"timestamp":"1508519181.719647408","source":"atc","message":"atc.container-collector.run.done","log_level":0,"data":{"session":"29.235"}}
{"timestamp":"1508519181.719670296","source":"atc","message":"atc.volume-collector.run.start","log_level":0,"data":{"session":"27.235"}}
{"timestamp":"1508519181.725684881","source":"atc","message":"atc.volume-collector.run.done","log_level":0,"data":{"session":"27.235"}}
{"timestamp":"1508519181.728947163","source":"atc","message":"atc.collector-runner.lock-task.release.released","log_level":0,"data":{"id":[3,-824445620],"session":"20.235.2","task-name":"collector"}}
{"timestamp":"1508519191.602680683","source":"atc","message":"atc.build-tracker.track.start","log_level":0,"data":{"session":"18.709"}}
{"timestamp":"1508519191.606373072","source":"atc","message":"atc.build-tracker.track.done","log_level":0,"data":{"session":"18.709"}}
{"timestamp":"1508519201.602694035","source":"atc","message":"atc.build-tracker.track.start","log_level":0,"data":{"session":"18.710"}}
{"timestamp":"1508519201.631547928","source":"atc","message":"atc.build-tracker.track.done","log_level":0,"data":{"session":"18.710"}}
{"timestamp":"1508519210.815513372","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:54604: write: broken pipe","id":3}}
{"timestamp":"1508519210.827029467","source":"atc","message":"atc.tracker-runner.received-atc-shutdown-message","log_level":1,"data":{"session":"19"}}
{"timestamp":"1508519210.827272654","source":"atc","message":"atc.build-tracker.track.start","log_level":0,"data":{"session":"18.711"}}
{"timestamp":"1508519210.849106789","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55390: write: broken pipe","id":3}}
{"timestamp":"1508519210.852025032","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55634: write: broken pipe","id":3}}
{"timestamp":"1508519210.860105991","source":"atc","message":"atc.build-tracker.track.done","log_level":0,"data":{"session":"18.711"}}
{"timestamp":"1508519210.865641832","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55048: write: broken pipe","id":3}}
{"timestamp":"1508519210.865645885","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55400: write: broken pipe","id":3}}
{"timestamp":"1508519211.077051401","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55394: write: broken pipe","id":3}}
{"timestamp":"1508519211.077225447","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55352: write: broken pipe","id":3}}
{"timestamp":"1508519211.084618807","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55670: write: broken pipe","id":3}}
{"timestamp":"1508519211.084633350","source":"atc","message":"atc.failed-to-write-event","log_level":1,"data":{"error":"write tcp 127.0.0.1:8080-\u003e127.0.0.1:55404: write: broken pipe","id":3}}
{"timestamp":"1508519211.602660894","source":"atc","message":"atc.build-tracker.track.start","log_level":0,"data":{"session":"18.712"}}
{"timestamp":"1508519211.602699041","source":"atc","message":"atc.build-reaper-runner.lock-task.tick","log_level":0,"data":{"session":"32.236","task-name":"build-reaper"}}
{"timestamp":"1508519211.602701664","source":"atc","message":"atc.collector-runner.lock-task.tick","log_level":0,"data":{"session":"20.236","task-name":"collector"}}
{"timestamp":"1508519211.630598307","source":"atc","message":"atc.build-reaper-runner.lock-task.acquire.acquired","log_level":0,"data":{"id":[3,997540461],"session":"32.236.1","task-name":"build-reaper"}}
```

And the stack during a hang:

https://gist.github.com/CyrilPeponnet/913aa272feeb6a9c0fc70f346509c30c

Goroutines 8186230 and and 8133142 seem suspect maybe the listener doesn't reconnect gracefully or handle the termination.

here is my docker stack (base is coreos latest with docker 17.06 CE
```
version: "3.3"

services:
  database:
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.hostname == {{db_node}}
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: {{db_user}}
      POSTGRES_PASSWORD: {{db_password}}
      PGDATA: /database
    networks:
      - db_backend

  web:
    image: concourse/concourse:latest
    deploy:
      replicas: {{replicas}}
      labels:
        - "traefik.frontend.rule=Host:{{concourse_url}}"
        - "traefik.port=8080"
        - "traefik.frontend.entryPoints=https"
        - "traefik.docker.network=proxy_backend"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.weight=10"
    depends_on:
      - database
    command: web
    secrets:
      - tsa_host_key
      - session_signing_key
      - authorized_worker_keys
    configs:
      - source: ca-certificates-{{certificates.stat.checksum | truncate(8, false, '', 0)}}
        target: /etc/ssl/certs/ca-certificates.crt

    environment:
      CONCOURSE_VAULT_URL: {{vault_url}}
      CONCOURSE_VAULT_CLIENT_TOKEN: {{vault_token}}
      CONCOURSE_VAULT_PATH_PREFIX: {{vault_prefix}}
      CONCOURSE_BASIC_AUTH_USERNAME: {{concourse_user}}
      CONCOURSE_BASIC_AUTH_PASSWORD: {{concourse_password}}
      CONCOURSE_GITHUB_AUTH_CLIENT_ID: {{concourse_oauth_id}}
      CONCOURSE_GITHUB_AUTH_CLIENT_SECRET: {{concourse_oauth_secret}}
      CONCOURSE_GITHUB_AUTH_AUTH_URL: "{{github_url}}/login/oauth/authorize"
      CONCOURSE_GITHUB_AUTH_TOKEN_URL: "{{github_url}}/login/oauth/access_token" 
      CONCOURSE_GITHUB_AUTH_API_URL: "{{github_url}}/api/v3/"
      CONCOURSE_GITHUB_AUTH_TEAM: "{{github_team}}"
      CONCOURSE_TSA_HOST_KEY: /run/secrets/tsa_host_key
      CONCOURSE_SESSION_SIGNING_KEY: /run/secrets/session_signing_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /run/secrets/authorized_worker_keys
      CONCOURSE_EXTERNAL_URL: "https://{{concourse_url}}"
      CONCOURSE_POSTGRES_DATA_SOURCE: postgres://{{db_user}}:{{db_password}}@database:5432/concourse?sslmode=disable
      CONCOURSE_PEER_URL: "http://{%raw%}{{.Task.Name}}{%endraw%}:8080"
      CONCOURSE_INFLUXDB_URL: http://influx:8086
      CONCOURSE_INFLUXDB_DATABASE: concourse
    networks:
      - traefik_backend
      - db_backend
      - workers

  worker:
    image: docker
    deploy:
      mode: global
      placement:
        constraints: [node.labels.flavor == concourse.builder]
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - concourse-keys:/concourse-keys
    secrets:
      - source: tsa_host_key.pub
        target: /concourse-keys/tsa_host_key.pub
      - source: worker_key
        target: /concourse-keys/worker_key
    command: |-
      sh -c "exec docker run --name worker-`hostname` --volumes-from `hostname` --rm --privileged --network concourse_workers concourse/concourse:latest worker --tsa-host web --garden-dns-server={{ concourse_garden_dns }}"

volumes:
  concourse-keys:

networks:
  db_backend:
    driver: overlay
    driver_opts:
      encrypted: "true"
  workers:
    driver: overlay
    attachable: true
  traefik_backend:
    external:
      name: proxy_backend

secrets:
  authorized_worker_keys:
    file: "{{tmp_dir.path}}/keys/web/authorized_worker_keys"
  session_signing_key:
    file: "{{tmp_dir.path}}/keys/web/session_signing_key"
  tsa_host_key:
    file: "{{tmp_dir.path}}/keys/web/tsa_host_key"
  tsa_host_key.pub:
    file: "{{tmp_dir.path}}/keys/web/tsa_host_key.pub"
  worker_key:
    file: "{{tmp_dir.path}}/keys/worker/worker_key"

configs:
  ca-certificates-{{certificates.stat.checksum | truncate(8, false, '', 0)}}:
    file: "{{tmp_dir.path}}/ca-certificates.crt"
```

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Docker swarm
* Browser (if applicable): Safari
* Did this used to work? Nope
