### ISSUE TITLE
Resource get does not perform a check

### ISSUE THREAD

**Issue by william-tran** [concourse/concourse#1748]
# Bug Report

Raised as feature request #1719 but this looks like a bug.

Given a pipeline:

```
resources:
- name: trigger
  type: git
  check_every: 10s
  source:
    uri: https://github.com/william-tran/pipeline-test.git
- name: repo
  type: git
  check_every: 1000h
  source:
    uri: https://github.com/william-tran/pipeline-test.git
jobs:
- name: output-readme
  plan:
  - get: trigger
    trigger: true
  - get: repo
  - task: output-readme
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: repo
      run:
        path: /bin/sh
        args: ["-c", "cat repo/README.md"]
```

When I push a commit to https://github.com/william-tran/pipeline-test, I would expect `output-readme` to reflect that change, but it doesn't. Previous behaviour was that

> Every time a get happens it always performs a check to pull the latest version.

But that doesn't seem to happen now.

* Concourse version: 3.5.0
* Deployment type (BOSH/Docker/binary): Helm chart
* Infrastructure/IaaS: AWS
* Did this used to work? Yes from what I hear.
