### ISSUE TITLE
Permit overlapping inputs, outputs, and task caches

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1799]
# Feature Request

## What challenge are you facing?

It's pretty convenient in some cases to be able to have an output directory reside underneath an input, or be the same as an input, e.g. when making a commit to a repo.

This was a limitation from Garden-Linux that probably doesn't apply anymore with Garden-runC. As long as the mounts are given in the right order.

## A Modest Proposal

Let's uh...allow it? Just remove the validation and see that it works.

One gotcha: if an input is the *exact same path* as an output, we shouldn't mount over it. We can just use the input COW volume as the output and not make a volume just for the output?

**Comment by codesuki** [comment]
My use case would be the following.
I have several build steps that all build different docker images, later I want to all upload them somewhere from one task. Now I need to collect them from different output folders. Would be nice if the output paths would be shared and you could add things to it.

**Comment by cirocosta** [comment]
Hey,

<br />

During the development of this feature, we were unsure about one use case: when two inputs overlap.

For instance, consider the following plan:

https://github.com/concourse/concourse/blob/bf98b6129ff5956e24cc6f4d1bbc44159194d430/testflight/fixtures/volume-mounting.yml#L208-L230

There we have two separate resources pointing to the same path `some-resource`. Intuitivelly, this would mean that we'd have two volumes pointed to the same place:

```
VOLUMES         CONTAINER DIR TREE


 vol1 -----.
           |
           +--> /tmp/build/<build-id>/some-resource
           |
           |
 vol2 -----*

``` 

Given that we'd not like to stack those mounts, we end up picking one of them (based on alphabetical ordering - not necessarily in the order the inputs provided).

<br />

**Do you think that's an interesting case to support?**

thx!

**Comment by vito** [comment]
I think picking one is fine. I wouldn't expect anything else tbh. We could
add a validation for that but it's no big deal; it seems somewhat unlikely
to happen in the real world.

**Comment by jamie-pate** [comment]
One thing that's unclear from the docs is how this affects input_mapping/output_mapping

This should work as expected right?

```yaml
- get: git-src # some git resource
  version: every
  trigger: true
- task: prep
  file: git-src/prep_task.yaml
  input_mapping: {src: git-src}
  output_mapping: {src: prepped-src}
- task: test # imagine this uses multiple parallel tests or a separate container or something
  file: prepped-src/test_task.yaml # this fails trying to find the yaml file?
  input_mapping: { src: prepped-src }
```

prep_task.yaml:

```yaml
---
# ... configure platform/image_resource etc
inputs:
- name: src
run:
  dir: src
  path: prep.sh
```
