### ISSUE TITLE
Mangled multiline params value

### ISSUE THREAD

**Issue by melnikaite** [concourse/concourse#1802]
# Bug Report

I have following pipeline:
```
jobs:
  - name: deploy
    plan:
      - get: sourse
        trigger: true
      - task: deploy
        file: src/deploy.yml
        params:
          private_key: |
            first line
            second line
```
But env variable `private_key` has corrupted value: `first line second line`. All newlines are replaced with space.

* Concourse version: v3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Did this used to work? No

Similar issue #1292
