### ISSUE TITLE
unknown handle on repository.

### ISSUE THREAD

**Issue by ihulsbus** [concourse/concourse#1821]
# Bug Report

I'm regularly encountering an `unknown handle` on the repository resource:
`unknown handle: 479a6ba9-cc14-4d3b-74fe-7785d4ee9144`

The repository is currently configured as following:
```
- name: repository
  type: git
  source:
    branch: master
    password: ((git-pwd))
    uri: https://private.git.server/repo.git
    username: ((git-user))
  check_every: 24h
  webhook_token: <webhook_token>
```
Sometimes the `unknown handle` goes away after a manual trigger of the webhook, or when re-creating the workers. The webhook does not always work. 

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: OpenStack
* Browser (if applicable): Any
* Did this used to work? Yes
