### ISSUE TITLE
3.7.0 bosh deployed worker has an empty known_hosts

### ISSUE THREAD

**Issue by camattin** [concourse/concourse#1862]
# Bug Report

The following can also be handy:

* Concourse version: 3.7.0
* Deployment type: BOSH
* Infrastructure/IaaS: vSphere
* Browser (if applicable): n/a
* Did this used to work? Yes

The changes from [#1834](http://github.com/concourse/concourse/issues/1834) appear to have broken the 3.7.0 bosh deployed worker. Relevant snippet from the worker bosh manifest:

```
  - name: groundcrew
    release: concourse
    consumes: {baggageclaim: {from: <workername>}}
    properties:
      tsa:
        worker_key:
          private_key: |
            <WORKER PEM PRIVATE KEY>
          public_key: "ssh-rsa <worker public key>"
        host: <tsa IP>
        host_public_key: "ssh-rsa <tsa public key>"
```

This results in an empty known_hosts file on the worker, so then he cannot talk back to the tsa, of course.

Our only fix as of now is to put the workers back to 3.6.0. As the generated* pieces were previously responsible for creating the known_hosts file in 3.6.0, it seems that this is the relevant change which created this new issue?
