### ISSUE TITLE
Adding a / to a job name causes the UI to remove the "Trigger Build" button.

### ISSUE THREAD

**Issue by simonjohansson** [concourse/concourse#1877]
Hello!

Concourse version 3.7.0.

If you have a slash in the name of a job, you cannot trigger it from the UI. 

![screen shot 2017-12-06 at 17 20 26](https://user-images.githubusercontent.com/736248/33672468-90893af6-daaa-11e7-9a02-dbe6aa605a46.png)

If I replace said `/`, with say a `.`

![screen shot 2017-12-06 at 17 23 28](https://user-images.githubusercontent.com/736248/33672510-a6e12ef8-daaa-11e7-93dc-c408bc869a13.png)

The trigger button is there as expected.

Triggering via CLI still works as expected
```
$  fly -t ci trigger-job -j "asdf/ci/show-env.sh"
started asdf/ci/show-env.sh #4
```

Manifest
```
---
resources:
- name: test-repo
  type: git
  source:
    uri: https://github.com/simonjohansson/test-repo.git

jobs:
- name: ci/show-env.sh
  plan:
  - get: test-repo
    trigger: true
  - task: ci/show-env.sh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: latest
      run:
        path: ./ci/show-env.sh
        dir: test-repo
      inputs:
      - name: test-repo
```
