### ISSUE TITLE
Jobs running despite version constraints not being satisfied

### ISSUE THREAD

**Issue by rcw5** [concourse/concourse#1885]
I am having a problem where Concourse is running jobs despite a resource not satisfying version constraints.

We are using pipelines for production deployments and want to be declarative with the versions of s3 resources being used. So we are specifying the version in the `regexp` of the s3 resource definition:

```
resources:
- name: ubuntu-resource-image
  type: docker-image
  source:
    repository: ubuntu

- name: release
  type: s3
  source:
    bucket: mybucket-12345
    region_name: eu-west-1
    regexp: test-(0\.0\.1)\.txt
    access_key_id: foobar
    secret_access_key: raboof

jobs:
- name: job
  plan:
  - get: ubuntu-resource-image
  - get: release
  - task: say-hello
    image: ubuntu-resource-image
    config:
      platform: linux
      inputs:
      - name: release
      run:
        path: sh
        args:
        - -exc
        - cat release/test*.txt

- name: job-two
  plan:
  - get: ubuntu-resource-image
  - get: release
    passed: [job]
  - task: say-hello
    image: ubuntu-resource-image
    config:
      platform: linux
      inputs:
      - name: release
      run:
        path: sh
        args:
        - -exc
        - cat release/test*.txt
```

(Pre-req: the bucket contains two text files, `test-0.0.1.txt` and `test-0.0.2.txt`)

With the definition above the pipeline runs just fine with version 0.0.1.

If I change the version to 0.0.2 then run `set-pipeline` I can trigger the `job-two` job (without triggering `job-one`) and it will run immediately but fail with `error running command: regex does not match provided version: s3resource.Version{Path:"test-0.0.1.txt", VersionID:""}` 

I would have expected Concourse to put the job in the pending state because there are no resources available that satisfy the `passed` and `version` constraints. If I then ran `job-one` both constraints would be satisfied and `job-two` should then run.

I also tried using a wildcard match for the s3 resource regexp and pinning the version in the `get` step. After bumping the pinned version to 0.0.2 I can trigger `job-two` and it will actually start successfully but with the old version of the resource. 

* Concourse version: 3.7
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: n/a
* Browser (if applicable): Chrome
* Did this used to work?: Not sure but definitely doesn't work on 3.5 either.
