### ISSUE TITLE
4 resources collapsed into 1, rendering pipeline with fan in-out dependencies

### ISSUE THREAD

**Issue by dliebreich** [concourse/concourse#193]
concourse 0.65.1

jobA gets 4 resources. jobB takes resource1 (passed: [jobA]), jobC takes resource2 (passed: [jobA]) etc. when rendered, we only see resource1 as an output of jobA, but it feeds into a big black box labelled resource1, and resource1+resource2+resource3+resource4 are outputs of this black box. is this what is supposed to happen?

we will attach a snippet of our pipeline.yml and a picture of the rendering

**Comment by dliebreich** [comment]
![resource_woes](https://cloud.githubusercontent.com/assets/1817843/10897329/fa723698-8174-11e5-9b0c-2241940e914f.png)

**Comment by dliebreich** [comment]
```
---
resources:
  - name: p-runtime
    type: git
    source:

  - name: latest-opsman-aws
    type: s3
    source:

  - name: environment-aws
    type: pool
    source:

  - name: latest-opsman-openstack
    type: s3
    source:

  - name: environment-openstack
    type: pool
    source:

  - name: latest-opsman-vsphere
    type: s3
    source:

  - name: environment-vsphere
    type: pool
    source:

  - name: latest-opsman-vcloud
    type: s3
    source:

  - name: environment-vcloud
    type: pool
    source:

  - name: kickoff-time
    type: time
    source:
      interval: 1s

jobs:
  - name: kickoff
    plan:
    - get: kickoff-time
    - get: latest-opsman-aws
    - get: latest-opsman-vsphere
    - get: latest-opsman-vcloud
    - get: latest-opsman-openstack
    - get: p-runtime

  - name: wait-for-all-iaas
    plan:
    - get: kickoff-time
      trigger: true
      passed:
      - run-cats-aws
      - run-cats-vsphere
      - run-cats-vcloud
      - run-cats-openstack
    - get: p-runtime
      passed:
      - run-cats-aws
      - run-cats-vsphere
      - run-cats-vcloud
      - run-cats-openstack

  - name: claim-environment-aws
    plan:
      - get: kickoff-time
        passed: [kickoff]
        trigger: true
      - get: p-runtime
        passed: [kickoff]
      - put: environment
        resource: environment-aws
        params:
          acquire: true

  - name: destroy-environment-aws
    plan:
      - get: kickoff-time
        passed: [claim-environment-aws]
      - get: p-runtime
        passed: [claim-environment-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [claim-environment-aws]

  - name: deploy-ops-manager-aws
    plan:
      - get: kickoff-time
        passed: [destroy-environment-aws]
      - get: p-runtime
        passed: [destroy-environment-aws, kickoff]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [destroy-environment-aws]
      - get: ops-manager
        resource: latest-opsman-aws
        passed: [kickoff]

  - name: configure-microbosh-aws
    plan:
      - get: kickoff-time
        passed: [deploy-ops-manager-aws]
      - get: p-runtime
        passed: [deploy-ops-manager-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [deploy-ops-manager-aws]

  - name: deploy-microbosh-aws
    plan:
      - get: kickoff-time
        passed: [configure-microbosh-aws]
      - get: p-runtime
        passed: [configure-microbosh-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [configure-microbosh-aws]

  - name: upload-pivotal-aws
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [deploy-microbosh-aws]
        - get: p-runtime
          passed: [deploy-microbosh-aws]
        - get: environment
          resource: environment-aws
          trigger: true
          passed: [deploy-microbosh-aws]

  - name: configure-ert-aws
    plan:
      - get: kickoff-time
        passed: [upload-pivotal-aws]
      - get: p-runtime
        passed: [upload-pivotal-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [upload-pivotal-aws]

  - name: import-stemcell-aws
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [configure-ert-aws]
        - get: p-runtime
          trigger: true
          passed: [configure-ert-aws]
        - get: environment
          resource: environment-aws
          trigger: true
          passed: [configure-ert-aws]

  - name: deploy-ert-aws
    plan:
      - get: kickoff-time
        passed: [import-stemcell-aws]
      - get: p-runtime
        passed: [import-stemcell-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [import-stemcell-aws]

  - name: run-cats-aws
    plan:
      - get: kickoff-time
        passed: [deploy-ert-aws]
      - get: p-runtime
        passed: [deploy-ert-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [deploy-ert-aws]

  - name: promote-ops-manager-aws
    plan:
    - get: p-runtime
      passed:
      - wait-for-all-iaas
    - get: kickoff-time
      trigger: true
      passed:
      - wait-for-all-iaas
      - kickoff
    - get: ops-manager
      resource: latest-opsman-aws
      passed:
      - kickoff

  - name: destroy-environment-final-aws
    plan:
     - get: kickoff-time
       passed: [claim-environment-aws]
     - get: p-runtime
       passed: [claim-environment-aws]
     - get: environment
       resource: environment-aws
       passed: [claim-environment-aws]

  - name: release-environment-aws
    plan:
      - get: kickoff-time
        passed: [destroy-environment-final-aws]
      - get: p-runtime
        passed: [destroy-environment-final-aws]
      - get: environment
        resource: environment-aws
        trigger: true
        passed: [destroy-environment-final-aws]
      - put: environment-aws
        params:
          release: environment

  - name: claim-environment-openstack
    plan:
      - get: kickoff-time
        passed: [kickoff]
        trigger: true
      - get: p-runtime
        passed: [kickoff]
      - put: environment
        resource: environment-openstack
        params:
          acquire: true

  - name: destroy-environment-openstack
    plan:
      - get: kickoff-time
        passed: [claim-environment-openstack]
      - get: p-runtime
        passed: [claim-environment-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [claim-environment-openstack]

  - name: deploy-ops-manager-openstack
    plan:
      - get: kickoff-time
        passed: [destroy-environment-openstack]
      - get: p-runtime
        passed: [destroy-environment-openstack, kickoff]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [destroy-environment-openstack]
      - get: ops-manager
        resource: latest-opsman-openstack
        passed: [kickoff]

  - name: configure-microbosh-openstack
    plan:
      - get: kickoff-time
        passed: [deploy-ops-manager-openstack]
      - get: p-runtime
        passed: [deploy-ops-manager-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [deploy-ops-manager-openstack]

  - name: deploy-microbosh-openstack
    plan:
      - get: kickoff-time
        passed: [configure-microbosh-openstack]
      - get: p-runtime
        passed: [configure-microbosh-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [configure-microbosh-openstack]

  - name: upload-pivotal-openstack
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [deploy-microbosh-openstack]
        - get: p-runtime
          passed: [deploy-microbosh-openstack]
        - get: environment
          resource: environment-openstack
          trigger: true
          passed: [deploy-microbosh-openstack]

  - name: configure-ert-openstack
    plan:
      - get: kickoff-time
        passed: [upload-pivotal-openstack]
      - get: p-runtime
        passed: [upload-pivotal-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [upload-pivotal-openstack]

  - name: import-stemcell-openstack
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [configure-ert-openstack]
        - get: p-runtime
          trigger: true
          passed: [configure-ert-openstack]
        - get: environment
          resource: environment-openstack
          trigger: true
          passed: [configure-ert-openstack]

  - name: deploy-ert-openstack
    plan:
      - get: kickoff-time
        passed: [import-stemcell-openstack]
      - get: p-runtime
        passed: [import-stemcell-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [import-stemcell-openstack]

  - name: run-cats-openstack
    plan:
      - get: kickoff-time
        passed: [deploy-ert-openstack]
      - get: p-runtime
        passed: [deploy-ert-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [deploy-ert-openstack]

  - name: promote-ops-manager-openstack
    plan:
    - get: p-runtime
      passed:
      - wait-for-all-iaas
    - get: kickoff-time
      trigger: true
      passed:
      - wait-for-all-iaas
      - kickoff
    - get: ops-manager
      resource: latest-opsman-openstack
      passed:
      - kickoff

  - name: destroy-environment-final-openstack
    plan:
     - get: kickoff-time
       passed: [claim-environment-openstack]
     - get: p-runtime
       passed: [claim-environment-openstack]
     - get: environment
       resource: environment-openstack
       passed: [claim-environment-openstack]

  - name: release-environment-openstack
    plan:
      - get: kickoff-time
        passed: [destroy-environment-final-openstack]
      - get: p-runtime
        passed: [destroy-environment-final-openstack]
      - get: environment
        resource: environment-openstack
        trigger: true
        passed: [destroy-environment-final-openstack]
      - put: environment-openstack
        params:
          release: environment

  - name: claim-environment-vsphere
    plan:
      - get: kickoff-time
        passed: [kickoff]
        trigger: true
      - get: p-runtime
        passed: [kickoff]
      - put: environment
        resource: environment-vsphere
        params:
          acquire: true

  - name: destroy-environment-vsphere
    plan:
      - get: kickoff-time
        passed: [claim-environment-vsphere]
      - get: p-runtime
        passed: [claim-environment-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [claim-environment-vsphere]

  - name: deploy-ops-manager-vsphere
    plan:
      - get: kickoff-time
        passed: [destroy-environment-vsphere]
      - get: p-runtime
        passed: [destroy-environment-vsphere, kickoff]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [destroy-environment-vsphere]
      - get: ops-manager
        resource: latest-opsman-vsphere
        passed: [kickoff]

  - name: configure-microbosh-vsphere
    plan:
      - get: kickoff-time
        passed: [deploy-ops-manager-vsphere]
      - get: p-runtime
        passed: [deploy-ops-manager-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [deploy-ops-manager-vsphere]

  - name: deploy-microbosh-vsphere
    plan:
      - get: kickoff-time
        passed: [configure-microbosh-vsphere]
      - get: p-runtime
        passed: [configure-microbosh-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [configure-microbosh-vsphere]

  - name: upload-pivotal-vsphere
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [deploy-microbosh-vsphere]
        - get: p-runtime
          passed: [deploy-microbosh-vsphere]
        - get: environment
          resource: environment-vsphere
          trigger: true
          passed: [deploy-microbosh-vsphere]

  - name: configure-ert-vsphere
    plan:
      - get: kickoff-time
        passed: [upload-pivotal-vsphere]
      - get: p-runtime
        passed: [upload-pivotal-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [upload-pivotal-vsphere]

  - name: import-stemcell-vsphere
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [configure-ert-vsphere]
        - get: p-runtime
          trigger: true
          passed: [configure-ert-vsphere]
        - get: environment
          resource: environment-vsphere
          trigger: true
          passed: [configure-ert-vsphere]

  - name: deploy-ert-vsphere
    plan:
      - get: kickoff-time
        passed: [import-stemcell-vsphere]
      - get: p-runtime
        passed: [import-stemcell-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [import-stemcell-vsphere]

  - name: run-cats-vsphere
    plan:
      - get: kickoff-time
        passed: [deploy-ert-vsphere]
      - get: p-runtime
        passed: [deploy-ert-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [deploy-ert-vsphere]

  - name: promote-ops-manager-vsphere
    plan:
    - get: p-runtime
      passed:
      - wait-for-all-iaas
    - get: kickoff-time
      trigger: true
      passed:
      - wait-for-all-iaas
      - kickoff
    - get: ops-manager
      resource: latest-opsman-vsphere
      passed:
      - kickoff

  - name: destroy-environment-final-vsphere
    plan:
      - get: kickoff-time
        passed: [claim-environment-vsphere]
      - get: p-runtime
        passed: [claim-environment-vsphere]
      - get: environment
        resource: environment-vsphere
        passed: [claim-environment-vsphere]

  - name: release-environment-vsphere
    plan:
      - get: kickoff-time
        passed: [destroy-environment-final-vsphere]
      - get: p-runtime
        passed: [destroy-environment-final-vsphere]
      - get: environment
        resource: environment-vsphere
        trigger: true
        passed: [destroy-environment-final-vsphere]
      - put: environment-vsphere
        params:
          release: environment

  - name: claim-environment-vcloud
    plan:
      - get: kickoff-time
        passed: [kickoff]
        trigger: true
      - get: p-runtime
        passed: [kickoff]
      - put: environment
        resource: environment-vcloud
        params:
          acquire: true

  - name: destroy-environment-vcloud
    plan:
      - get: kickoff-time
        passed: [claim-environment-vcloud]
      - get: p-runtime
        passed: [claim-environment-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [claim-environment-vcloud]

  - name: deploy-ops-manager-vcloud
    plan:
      - get: kickoff-time
        passed: [destroy-environment-vcloud]
      - get: p-runtime
        passed: [destroy-environment-vcloud, kickoff]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [destroy-environment-vcloud]
      - get: ops-manager
        resource: latest-opsman-vcloud
        passed: [kickoff]

  - name: configure-microbosh-vcloud
    plan:
      - get: kickoff-time
        passed: [deploy-ops-manager-vcloud]
      - get: p-runtime
        passed: [deploy-ops-manager-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [deploy-ops-manager-vcloud]

  - name: deploy-microbosh-vcloud
    plan:
      - get: kickoff-time
        passed: [configure-microbosh-vcloud]
      - get: p-runtime
        passed: [configure-microbosh-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [configure-microbosh-vcloud]

  - name: upload-pivotal-vcloud
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [deploy-microbosh-vcloud]
        - get: p-runtime
          passed: [deploy-microbosh-vcloud]
        - get: environment
          resource: environment-vcloud
          trigger: true
          passed: [deploy-microbosh-vcloud]

  - name: configure-ert-vcloud
    plan:
      - get: kickoff-time
        passed: [upload-pivotal-vcloud]
      - get: p-runtime
        passed: [upload-pivotal-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [upload-pivotal-vcloud]

  - name: import-stemcell-vcloud
    plan:
      - aggregate:
        - get: kickoff-time
          passed: [configure-ert-vcloud]
        - get: p-runtime
          trigger: true
          passed: [configure-ert-vcloud]
        - get: environment
          resource: environment-vcloud
          trigger: true
          passed: [configure-ert-vcloud]

  - name: deploy-ert-vcloud
    plan:
      - get: kickoff-time
        passed: [import-stemcell-vcloud]
      - get: p-runtime
        passed: [import-stemcell-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [import-stemcell-vcloud]

  - name: run-cats-vcloud
    plan:
      - get: kickoff-time
        passed: [deploy-ert-vcloud]
      - get: p-runtime
        passed: [deploy-ert-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [deploy-ert-vcloud]

  - name: promote-ops-manager-vcloud
    plan:
    - get: p-runtime
      passed:
      - wait-for-all-iaas
    - get: kickoff-time
      trigger: true
      passed:
      - wait-for-all-iaas
      - kickoff
    - get: ops-manager
      resource: latest-opsman-vcloud
      passed:
      - kickoff

  - name: destroy-environment-final-vcloud
    plan:
      - get: kickoff-time
        passed: [claim-environment-vcloud]
      - get: p-runtime
        passed: [claim-environment-vcloud]
      - get: environment
        resource: environment-vcloud
        passed: [claim-environment-vcloud]

  - name: release-environment-vcloud
    plan:
      - get: kickoff-time
        passed: [destroy-environment-final-vcloud]
      - get: p-runtime
        passed: [destroy-environment-final-vcloud]
      - get: environment
        resource: environment-vcloud
        trigger: true
        passed: [destroy-environment-final-vcloud]
      - put: environment-vcloud
        params:
          release: environment

groups:
  - name: common
    jobs:
    - kickoff
    - wait-for-all-iaas

  - name: vsphere-edge
    jobs:
    - claim-environment-vsphere
    - destroy-environment-vsphere
    - deploy-ops-manager-vsphere
    - configure-microbosh-vsphere
    - deploy-microbosh-vsphere
    - upload-pivotal-vsphere
    - configure-ert-vsphere
    - import-stemcell-vsphere
    - deploy-ert-vsphere
    - run-cats-vsphere
    - promote-ops-manager-vsphere
    - destroy-environment-final-vsphere
    - release-environment-vsphere

  - name: openstack-edge
    jobs:
    - claim-environment-openstack
    - destroy-environment-openstack
    - deploy-ops-manager-openstack
    - configure-microbosh-openstack
    - deploy-microbosh-openstack
    - upload-pivotal-openstack
    - configure-ert-openstack
    - import-stemcell-openstack
    - deploy-ert-openstack
    - run-cats-openstack
    - promote-ops-manager-openstack
    - destroy-environment-final-openstack
    - release-environment-openstack

  - name: aws-edge
    jobs:
    - claim-environment-aws
    - destroy-environment-aws
    - deploy-ops-manager-aws
    - configure-microbosh-aws
    - deploy-microbosh-aws
    - upload-pivotal-aws
    - configure-ert-aws
    - import-stemcell-aws
    - deploy-ert-aws
    - run-cats-aws
    - destroy-environment-final-aws
    - promote-ops-manager-aws
    - release-environment-aws

  - name: vcloud-edge
    jobs:
    - claim-environment-vcloud
    - destroy-environment-vcloud
    - deploy-ops-manager-vcloud
    - configure-microbosh-vcloud
    - deploy-microbosh-vcloud
    - upload-pivotal-vcloud
    - configure-ert-vcloud
    - import-stemcell-vcloud
    - deploy-ert-vcloud
    - run-cats-vcloud
    - destroy-environment-final-vcloud
    - promote-ops-manager-vcloud
    - release-environment-vcloud
```
