### ISSUE TITLE
Resource usage in job level `on_failure`, `on_success` blocks don't get validated

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#1937]
The resource used in the `on_failure` block is not defined, yet it still passes the pipeline validation stage.

```yaml
jobs:
- name: test-job
  on_failure:
    do:
    - put: some-resource-that-hasnt-been-defined
```

thanks @freynca
