### ISSUE TITLE
fly set-pipeline shows unneccessary diffs for large numbers

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1952]
# Bug Report

The fly cli incorrectly renders diffs for large numbers when invoking `fly set-pipeline`, even though the numbers didn't change in the pipeline `.yml` definition.

For example, this yaml: 
```yaml
        params:
          delete_after: 2592000
```

renders this diff: 
```yaml
        params:
          delete_after: 2.592e+06
          delete_after: 2592000
```

* Concourse version: 3.8

**Comment by petergtz** [comment]
This is a duplicate of https://github.com/concourse/concourse/issues/1407.

**Comment by edtan** [comment]
I thought I'd share some of my notes on this while trying to debug through this.  Note that this was tested against `master`.  It seems like the threshold that changes the number to a float is now a uint64.  For example:

```
jobs:
- name: Test Large Numbers
  plan:
  - task: Echo Large Number
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine, tag: latest }
      params:
        LARGE_NUM: 18446744073709551616 # 2^64 + 1
      run:
        path: sh
        args:
          - -exc
          - echo ${LARGE_NUM}
````
renders this diff:
```
params:
  LARGE_NUM: "18446744073709551615"
  LARGE_NUM: "1.8446744e+19"
```
As the new config is being parsed in atc_config.h within resolveTemplates(),  tpl.Evaluate() is called.  (tpl is a Template from the bosh-cli project.)  These lines in tpl.Evaluate() seem to make the LARGE_NUM to be treated like a float:
```
var obj interface{}                                                  
err := yaml.Unmarshal(t.bytes, &obj)
```

I could not reproduce this issue for numbers smaller than 2^64 as in the original example.
