### ISSUE TITLE
Bug: CloudFoundry Static Build Pack does not include StaticFile configuration file when using 'path:'

### ISSUE THREAD

**Issue by bigorangemachine** [concourse/concourse#1957]
When you are deploying using something like [create-react-app](https://github.com/facebookincubator/create-react-app) and you deploy using concourse & cloudfoundry using a static-bundle pack with a staticfile config; the file doesn’t get pushed.  Due to how create-react-app does the build and when you setup your yml file to push that build folder; it does not deploy the`StaticFile` ([CloudFoundry StaticFile Doc](https://docs.cloudfoundry.org/buildpacks/staticfile/#configuration-options) - we are using`pushstate` for the default react router) correctly.  I have determined that when you push locally using ‘cf push’ that you need the StaticFile in the same directory as StaticFile config file.  However when you copy it into the build directory the push doesn't happen in the build directory.

Concourse version: v3.5.0
Deployment type (BOSH/Docker/binary): BOSH
Infrastructure/IaaS: AWS
Did this used to work?: I assume No

pipeline.yml
```
jobs:
  ...
  - name: deploy-cf-dev-web
    plan:
      - get: project
        trigger: true
        passed: [test-web]
      - task: build
        file: project/build_dev.yml
        params:
          REACT_APP_API_URL: //dev-project-api.cfapps.io
          REACT_APP_DISPLAY_URL: //dev-project.cfapps.io
      - put: cf-dev-web
        params:
          manifest: build/manifest_dev.yml
          path: build
          current_app_name: dev-project
```

project/build_dev.yml
```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '8-alpine'

inputs:
  - name: project
outputs:
  - name: build

run:
  path: sh
  args:
  - -exc
  - |
    cd build/web
    yarn install --no-progress
    REACT_APP_API_URL=$REACT_APP_API_URL yarn build
    cp manifest_dev.yml ./build
    cp StaticFile ./build
    cp -r build ../../
```
