### ISSUE TITLE
Feature Request: Cloud Foundry 'run-task' support

### ISSUE THREAD

**Issue by bigorangemachine** [concourse/concourse#1958]
Is it possible to be able to run ‘cf run-task’ from concourse?
The feature is [noted in the documentation](https://docs.cloudfoundry.org/devguide/using-tasks.html) but it doesn't appear to be in the concourse source code anywhere.

## What challenge are you facing?

When deploying over concourse we need to manually update our databases or kluge it together through a bash script that is called when `npm start` or `npm install` (for a node project).  For our testing environment we have a series of seeders that need to be setup for testing fixtures (user accounts, view scenarios and 3rd Party Unique Identifiers).  

Currently we have implemented it using a bash script and `npm install` which detects the `NODE_ENV` environment variable (as set by our CloudFoundry Environment variables).

## A Modest Proposal

Allow `cf run-task` to be performed as a job

pipeline.yml
```
jobs:
  ...
  - name: deploy-cf-dev-web
    plan:
      - get: project
        trigger: true
        passed: [test-web]
      - task: build
        file: project/build_dev.yml
      - put: cf-dev-web
        params:
          manifest: build/manifest_dev.yml
          path: build
          current_app_name: dev-project
      - put: cf-dev-web
        run-task:
          name: db-migrate
          command: "npm run db:migrate"
```
