### ISSUE TITLE
Custom resource - reference other resources in `in`?

### ISSUE THREAD

**Issue by cjohansen** [concourse/concourse#1962]
# Bug Report

I have two custom resources. The first one is only used with `put` to trigger deployments. With a `put` I am passing it files from other resources, which it then proceeds to read and process:

```yml
- name: deploy-staging
  plan:
  - get: repo
    passed: [build]
  - put: custom-deployment-resource
    params:
      version: repo/.git/HEAD
```

This works fine. However, I'm not having any luck doing the same on `get`:

```yml
- name: deploy
  plan:
  - get: repo
    passed: [build]
  - get: generate-config
    params:
      version: repo/.git/HEAD
```

This resolves in "No such file or directory repo/.git/HEAD". Is this a feature, or am I doing something wrong?
