### ISSUE TITLE
Bug? not found get files at darwin worker.

### ISSUE THREAD

**Issue by masaki-takano** [concourse/concourse#2001]
# Bug Report

not found get files at darwin worker.

```
resources:
  - name: repo-master-build-mac
    type: git
    source:
      uri: {{gitlab-repo-uri}}
      branch: master
      private_key: {{gitlab-private-key}}

jobs:
  - name: sandbox-worker-mac
    plan:
      - get: repo-master-build-mac
      - task: worker-mac
        config:
          platform: darwin
          inputs:
            - name: repo-master-build-mac
          run:
            path: sh
            args:
              - -c
              - |
                find .
                find /opt/concourse

```

```
.
./repo-master-build-mac      <----- EMPTY
/opt/concourse
/opt/concourse/worker
/opt/concourse/worker/containers
/opt/concourse/worker/containers/00001j9cpfa
/opt/concourse/worker/containers/00001j9cpfa/scratch
/opt/concourse/worker/containers/00001j9cpfa/tmp
/opt/concourse/worker/containers/00001j9cpfa/tmp/build
/opt/concourse/worker/containers/00001j9cpfa/tmp/build/e7b4b77f
/opt/concourse/worker/containers/00000esrrjp
/opt/concourse/worker/containers/00000esrrjp/scratch
/opt/concourse/worker/containers/00000esrrjp/tmp
/opt/concourse/worker/containers/00000esrrjp/tmp/build
/opt/concourse/worker/containers/00000esrrjp/tmp/build/e7b4b77f
/opt/concourse/worker/volumes
/opt/concourse/worker/volumes/dead
/opt/concourse/worker/volumes/init
/opt/concourse/worker/volumes/live
/opt/concourse/worker/volumes/live/cb991aa6-4c2e-4f8f-58c5-20d4426a31a3
/opt/concourse/worker/volumes/live/cb991aa6-4c2e-4f8f-58c5-20d4426a31a3/ttl.json
/opt/concourse/worker/volumes/live/cb991aa6-4c2e-4f8f-58c5-20d4426a31a3/properties.json
/opt/concourse/worker/volumes/live/cb991aa6-4c2e-4f8f-58c5-20d4426a31a3/privileged.json
/opt/concourse/worker/volumes/live/cb991aa6-4c2e-4f8f-58c5-20d4426a31a3/volume
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427/ttl.json
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427/properties.json
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427/privileged.json
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427/volume
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427/volume/ci      <---- GET SUCCESS
/opt/concourse/worker/volumes/live/5bf5d26b-5b38-453c-5a3f-158d59c84427/volume/ci/tasks
...
/opt/concourse/worker/volumes/live/91f21dac-6588-4d73-753c-df7985957913
/opt/concourse/worker/volumes/live/91f21dac-6588-4d73-753c-df7985957913/ttl.json
/opt/concourse/worker/volumes/live/91f21dac-6588-4d73-753c-df7985957913/properties.json
/opt/concourse/worker/volumes/live/91f21dac-6588-4d73-753c-df7985957913/privileged.json
/opt/concourse/worker/volumes/live/91f21dac-6588-4d73-753c-df7985957913/volume
/opt/concourse/worker/volumes/live/91f21dac-6588-4d73-753c-df7985957913/volume/repo-master-build-mac
```

```
mac $ chwon -R takano:staff /opt/concourse/

mac $ sudo ./concourse_darwin_amd64 worker --work-dir /opt/concourse/worker --tsa-host XXXXX --tsa-public-key ./keys/worker/tsa_host_key.pub --tsa-worker-private-key ./keys/worker/darwin_worker_key
```

* Concourse version: 3.8.0
* Deployment type: Docker & darwin worker
* Infrastructure/IaaS: CoreOS
* Browser (if applicable):
* Did this used to work?

**Comment by masaki-takano** [comment]
Maybe 3.9.0 fixed.

**Comment by neofreko** [comment]
I'm still experiencing this with v4.0.0 darwin worker. One thing I can narrow down is, it's reproducible when we are using docker image with custom tag, eg:
```
image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: 2.4-jessie
```

This one works:
```
image_resource:
        type: docker-image
        source:
          repository: ruby
```

The following yaml can be use to reproduce this issue on concourse 4.0
```
groups: []
resource_types: []
jobs:
- name: my job
  plan:
  - task: say hi
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: 2.4-jessie
      run:
        path: sh
        args:
        - -exc
        - |
          echo hello world
```
