### ISSUE TITLE
Use consistent indents in docs

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#2021]
## A Modest Proposal

The http://concourse.ci/build-plans.html page shows what some may consider an "anti-pattern" of yml indents and some yml parsers even fail to parse correctly: 

The doc has this example of a job:
```yml
name: banana-unit
plan:
- get: banana
  trigger: true
- task: unit
  file: banana/task.yml
```

A more correct version I believe is to indent the list items below the plan: 

```yml
name: banana-unit
plan:
  - get: banana
    trigger: true
  - task: unit
    file: banana/task.yml
```

Should the docs be fixed or am I on the wrong path here? 

Background: we had issues processing our pipeline.yml through build tooling which used the first form, not with the second form.

**Comment by ktchen14** [comment]
In this case I believe the documentation shows consistent usage and this style of indentation is acceptable according to the YAML specification. It's in fact used at the homepage of http://yaml.org/:

```yaml
Projects:
  C/C++ Libraries:
  - libyaml       # "C" Fast YAML 1.1
  - Syck          # (dated) "C" YAML 1.0
  - yaml-cpp      # C++ YAML 1.2 implementation
```

In addition in section `8.2.1. Block Sequences` of the [YAML specification](http://www.yaml.org/spec/1.2/spec.html#id2797293) it says:

> ... [B]oth the “-” indicator and the following spaces are considered to be part of the of the nested collection ...

If a YAML parser is failing to parse this then it's not compliant.
