### ISSUE TITLE
runc error, preparing rootfs caused "permission denied"

### ISSUE THREAD

**Issue by fewknow** [concourse/concourse#2048]
Hi there!

# Bug Report

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

The following can also be handy:

* Concourse version: 3.6
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work? Local pipeline yes.
* Stemcells : 
bosh-aws-xen-hvm-ubuntu-trusty-go_agent  3541.4*  ubuntu-trusty  -    ami-feb1ad84 light
* Releases: 
Name         Version  Commit Hash
concourse    3.9.0    37b4b66
~            3.6.0*   cba2a51
garden-runc  1.0.0*   33181c87

I have deployed concourse cluster using bosh cli v2.   I have pushed up my pipeline 
```
---

resources:

- name: version
  type: semver
  source:
    driver: git
    uri: https://bitbucket.org/corvestadevops/devops.artifacts.git
    branch: master
    username: ((bitbucket-user))
    password: ((bitbucket-password))
    file: version

- name: resource-devops.ci
  type: git
  source:
    uri: https://bitbucket.org/corvestadevops/devops.artifacts.git
    branch: master
    username: ((bitbucket-user))
    password: ((bitbucket-password))

jobs:
- name: build-ci-repo
  public: true
  plan:
    - get: resource-devops.ci
      trigger: true
    - put: version
      params: {bump: minor}
    - task: build-ci-repo
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: 038131160342.dkr.ecr.us-east-1.amazonaws.com/concourseci-build-java
            aws_secret_access_key: ((MGMT_AWS_SECRET_ACCESS_KEY))
            aws_access_key_id: ((MGMT_AWS_ACCESS_KEY_ID))
            tag: 1.0.0
        run:
          path: sh
          args:
            - -exc
            - |
              echo 'Built version of ci repo'

```

This is to simply bump the version of the bitbucket repository.  After I `set-pipeline` and created it I get this error `runc create: exit status 1: rootfs_linux.go:42: preparing rootfs caused "permission denied"` under ` - get: resource-devops.ci`

I found this (https://github.com/concourse/concourse/issues/598)  but I don't see how to add privileged to the `-get`.  I have tried added it the `params` but this didn't do anything.

![screen shot 2018-02-20 at 4 38 53 pm](https://user-images.githubusercontent.com/22297806/36450802-165cd0fa-165d-11e8-99d6-2535d6d7dfd6.png)

![screen shot 2018-02-20 at 4 43 26 pm](https://user-images.githubusercontent.com/22297806/36450818-31b556ce-165d-11e8-95e6-048399bf05fe.png)
