### ISSUE TITLE
Can no longer forward a baggageclaim/garden with bind_ip set to 127.0.0.1

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2059]
The `garden.forward_address` and `baggageclaim.forward_address` properties are no longer respected. If BaggageClaim has `bind_ip: 127.0.0.1`, registration will fail as it'll try to use the instance's IP.

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): BOSH
* Did this used to work? Yes, in 3.9.0

/cc @topherbullock

**Comment by geofffranks** [comment]
I just ran into this today on v3.8.0, I think. If not, it seems pretty similar. The tsa config is using the link IP address, but bind_ip is restricting the port to only be localhost:

https://github.com/concourse/concourse/blob/v3.8.0/jobs/tsa/templates/tsa_ctl.erb#L19-L24

**Comment by geofffranks** [comment]
Looks like overriding the `atc.urls` value in the TSA spec is also not being honored

https://github.com/concourse/concourse/blob/v3.8.0/jobs/tsa/templates/tsa_ctl.erb#L26

^^ is preferring the link values to the value the spec says will override the links

**Comment by vito** [comment]
Still doesn't work. The values for the `forward_address` properties are not respected, and if I configure a bind IP of `127.0.0.1` I see:

```
==> /var/vcap/sys/log/groundcrew/beacon.stderr.log <==
2018/03/08 19:06:33 failed to forward remote connection: dial tcp 10.1.0.8:7788: connect: connection refused
```

**Comment by topherbullock** [comment]
@vito hmm, I guess I was kinda fuzzy on what the `forward_address` would be if it isn't the same as the bind ip?? My assumption was that we could just assume that the presence of `forward_address` means that they want the new `registration_mode` flag set to `forward` which sets up the forwarding, but for the `baggageclaim.bind_ip` configuration we wind up getting the link's ip for the `baggageclaim.url`.

We should just remove `registration-mode` in favour of `*-forward-address` flags to worker and follow the same logic as here for setting up the proxies and call it a day: https://github.com/concourse/concourse/blob/v3.9.0/jobs/groundcrew/templates/beacon_ctl.erb#L91-L101

**Comment by vito** [comment]
@topherbullock That'd be another way of doing it, yeah. But it doesn't seem to be working. I didn't dig in much to see why, I just noticed our PR worker still can't register. Here's its config:

```yaml
- azs:
  - z1
  instances: 1
  jobs:
  - consumes:
      baggageclaim:
        from: untrusted-baggageclaim
    name: groundcrew
    properties:
      baggageclaim:
        forward_address: 127.0.0.1:7788
      garden:
        forward_address: 127.0.0.1:7777
      tags:
      - pr
      tsa:
        registration_mode: forward
        worker_key: "((worker_key))"
    release: concourse
  - name: baggageclaim
    properties:
      bind_ip: 127.0.0.1
      log_level: debug
    provides:
      baggageclaim:
        as: untrusted-baggageclaim
    release: concourse
  - name: garden
    properties:
      garden:
        deny_networks:
        - 10.0.0.0/16
        dns_servers:
        - 8.8.8.8
        - 8.8.4.4
        listen_address: 127.0.0.1:7777
        listen_network: tcp
    release: garden-runc
  name: untrusted-worker
  networks:
  - name: private
  stemcell: trusty
  vm_type: worker
```

@xtremerui has picked this up again
