### ISSUE TITLE
load image does not preload image - no such file or directory

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#2068]
# load_image fails to load image

The error code message is: `open fedora-preload/image: no such file or directory` (which is true)

I followed the answer/guide on [stackoverflow](https://stackoverflow.com/questions/44475165/concourse-ci-leverage-docker-image-cache/44959191#44959191)

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: custom / CoreOS / Fedora
* Browser (if applicable): Firefox

```bash
    $ fly -t example hijack -j dummy/build-fedora-native -s container-fedora-native
    # cd fedora-preload
    # ls -1
    digest
    docker_inspect.json
    image-id
    metadata.json
    repository
    rootfs
    tag
```

![Fails with file not found](https://user-images.githubusercontent.com/667047/36934587-3f708d5a-1eec-11e8-9a8e-a54f4bb50f2f.png)

The snippet defining the procedure:

```YAML
resources:
# // ** snip ** \\
- name: container-fedora
  type: docker-image
  source:
    repository: fedora
    max_concurrent_downloads: 1
    max_concurrent_uploads: 1

- name: fedora-preload
  type: docker-image
  source:
    repository: fedora

jobs:
  - name: build-fedora-native
    plan:
    - get: ci
      resource: git-ci
      trigger: true

    - get: fedora-preload
    - put: container-fedora-native
      params:
        load_base: fedora-preload
        build: copycat
        tag_as_latest: true

    - task: composition
      image: container-doc
      config:
        platform: linux
        inputs:
        - name: ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv ci/container/fedora ./copycat/
            cp -rfv ci/container/fedora/native/Dockerfile ./copycat/
            cp -rfv ci/container/*.sh ./copycat/
```

Any idea what is wrong?

The image itself does not contain a directory called `image` , only `rootfs` and `image-id` exist.
