### ISSUE TITLE
ATC scheduler sometimes skips job executions

### ISSUE THREAD

**Issue by jochenehret** [concourse/concourse#2072]
Hi Concourse team,

we have some monitoring jobs which are triggered by a 5-minute time resource. Sometimes builds are skipped, i.e. it takes 10 minutes (or even longer) until the next job runs. The problem cannot be easily reproduced, but it usually appears after initial deployment of a Concourse instance or after a (stemcell) update. We run Concourse v3.8.0 with *two* web nodes. concourse-deployment revision is [https://github.com/concourse/concourse-deployment/commit/f6abcfeb0324410fa8d82e11e24200e3d8e1fb86].

Below are the atc logs from the two nodes (timestamps converted to readable format). You can see that there is no job run at 07:50.
```
web/0

{"timestamp":"07:45:34","source":"atc","message":"atc.syncer.landscape-monitoring-pipeline:scheduler.tick.scheduling.try-start-next-pending-build.running","log_level":1,"data":{"build":152,"build-id":152,"build-name":"3","job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"52.2.61.3.37"}}
{"timestamp":"07:45:39","source":"atc","message":"atc.build-tracker.track.lock.acquire.not-acquired-already-held-locally","log_level":0,"data":{"build":152,"build_id":152,"id":[1,152],"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.70.1.1"}}
{"timestamp":"07:45:39","source":"atc","message":"atc.build-tracker.track.build-already-tracked","log_level":0,"data":{"build":152,"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.70"}}
{"timestamp":"07:55:49","source":"atc","message":"atc.build-tracker.track.lock.acquire.not-acquired-already-held-in-db","log_level":0,"data":{"build":158,"build_id":158,"id":[1,158],"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.131.1.1"}}
{"timestamp":"07:55:49","source":"atc","message":"atc.build-tracker.track.build-already-tracked","log_level":0,"data":{"build":158,"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.131"}}

web/1

{"timestamp":"07:45:37","source":"atc","message":"atc.build-tracker.track.lock.acquire.not-acquired-already-held-in-db","log_level":0,"data":{"build":152,"build_id":152,"id":[1,152],"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.66.1.1"}}
{"timestamp":"07:45:37","source":"atc","message":"atc.build-tracker.track.build-already-tracked","log_level":0,"data":{"build":152,"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.66"}}
{"timestamp":"07:55:40","source":"atc","message":"atc.syncer.landscape-monitoring-pipeline:scheduler.tick.scheduling.try-start-next-pending-build.running","log_level":1,"data":{"build":158,"build-id":158,"build-name":"4","job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"52.2.121.3.37"}}
{"timestamp":"07:55:47","source":"atc","message":"atc.build-tracker.track.lock.acquire.not-acquired-already-held-locally","log_level":0,"data":{"build":158,"build_id":158,"id":[1,158],"job":"monitor-bosh","pipeline":"landscape-monitoring-pipeline","session":"53.127.1.1"}}
```
Can you please check? We can increase log level if that helps.

Thanks and Best Regards,

  Jochen.

**Comment by topherbullock** [comment]
@jochenehret This is a side-effect of anther known issue other users have been reporting, #1298 , where resource versions seem to never actually be passed along to jobs when the checks happen, which leads to the behaviour you're seeing.

Are you able to provide a simplified representation yml for the pipeline you're seeing this issue on?

**Comment by jochenehret** [comment]
Hi @topherbullock, 

here is a stripped down version of our pipeline:
```
resources:
- name: landscape
  type: git
  source:
    branch: master
    password: ""
    private_key: |-
      -----BEGIN RSA PRIVATE KEY-----
      <redacted>
      -----END RSA PRIVATE KEY-----
    skip_ssl_verification: true
    uri: git@github.<redacted>
    username: concourse-hcp
- name: 5-min
  type: time
  source:
    interval: 5m

jobs:
- name: monitor-bosh
  public: true
  build_logs_to_retain: 1500
  plan:
  - aggregate:
    - get: landscape
    - get: 5-min
      trigger: true
  - task: execute-bosh-monitoring-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          password: <redacted>
          repository: <redacted>
          tag: v33
          username: docker-dev
      params:
        CONCOURSE_DEPLOYMENT_NAME: concourse
        DEPLOYMENT_NAME: bosh
        IAC_ACTION: action monitoring-test
      run:
        path: landscape/products/product-cf-hcp/components/concourse/scripts/iac-action.sh
      inputs:
      - name: landscape
        path: ""
    timeout: 5m
```
Please tell us if you need more information.

Best Regards,

   Jochen.
