### ISSUE TITLE
Resource Groups

### ISSUE THREAD

**Issue by cppforlife** [concourse/concourse#210]
## Problem

BOSH core team runs a pipeline to produce a bosh release and bosh cli gem combination. It also tests them against a specific version of bats git repo. 

BOSH cpi team runs a pipeline that expects to consume bosh release, cli gem and bats repo combination so that it can test it all against a specific version of cpi release. Ultimately this pipeline publishes a new cpi release referencing other asset versions.

We would like to capture group of resource versions instead of just individual resource versions, so that cpi team's pipeline can run against a specific set of resources that passed core team's pipeline.

Other examples:

- concourse release + garden release combination
- cf-release + diego release + cats src combination
- pieces of cf-release

## Proposal

I think concourse should introduce a new primitive for specifying resource groups. Resource groups would be versioned similarly to any other resource. Builds would be able to produce a resource group version and consume specific resource group version.

In UI this could look like a box around multiple resources to indicate that they come as a whole.

```
  +--------------+
  | +----------+ |   +-------+
  | | bats-src |-|---|       |
  | +----------+ |   |       |
  | +----------+ |   |       |
  | | cli-ver  |-|---| tests |
  | +----------+ |   |       |
  | +----------+ |   |       |
  | | bosh-rel |-|---|       |
  | +----------+ |   +-------+
  +--------------+
```

Resources mentioned in a resource group are not any different from any other resources. They will be configured with all the other resources and have exactly same semantics.

Backing store for resource groups could work similarly to any resource's backing store. For example concourse release can include s3_resource_group that stores and retrieves files from a bucket just like s3_resource.

Contents of each resource group will only include versions for other resources so that storage/retrieval is delegated to each resource. For example contents of v1 of core-assets resource group will be:

candidate-core-assets-bucket/core-asset-1.json

(json in yaml)

```yaml
bats-src:
  ref: 329ryfvbqeg83490tk549h39q40
cli-ver:
  version: 1.34.0
bosh-rel:
  version: 223
```

Possible configuration in the pipeline:

```yaml
resources:
- name: bosh-init
  type: s3
  source:
    regexp: bosh-init-([0-9.]+)-linux-amd64
    bucket: {{init_bucket}}
- name: bats
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
    branch: master
- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh

resource_groups:
- name: core-assets
  type: s3
  resources: [bosh-init, bats, bosh-release]
  source:
    regexp: core-assets-([0-9.]+)
    bucket: {{combos_buckets}}
```

I'll skip details of how concourse will be able to fetch specific versions of group's resources and its api format.

**Comment by cppforlife** [comment]
@vito @xoebus let's talk more about this some time today/tomorrow.

/cc @Amit-PivotalLabs @calebamiles @mariash

**Comment by xoebus** [comment]
@dliebreich What do you think of this instead of Airfreight?

**Comment by dliebreich** [comment]
I'm not sure how the example yml and json describes the solution. Otherwise, conceptually, it seems like it would meet our needs.

One problem I can foresee is that you need to have the component resource configs match in the producer of the group and in the consumer of the group. If different teams maintained the producer and the consumer, that coordination might be somewhat expensive.

**Comment by amitkgupta** [comment]
For the purposes of integrating releases for Cloud Foundry (and this generalizes to any BOSH-deployed service composed of many releases), we require:

- some builds can produce an artifact recording the tuple of input releases that passed the build, and are therefore "blessed"
- some builds that can consume said artifact, and generate a BOSH deployment manifest consisting of all or some of the blessed releases
- end users (human operators) can also consume said artifact, and produce a manifest

We accomplish this like so:

https://github.com/cloudfoundry/cf-deployment/blob/master/blessed_versions.json

We maintain our own code for writing and reading this artifact because it needs to be used (at least read) outside the context of Concourse.  We also specifically *do not* want to fetch the resources referenced in that `blessed_versions.json` file, because we use the data to construct a manifest where we can then delegate to the Director to fetch only the resources that it needs, and do it all Director-side to avoid unnecessary download-then-uploads on the client side.

**Comment by dliebreich** [comment]
+1 on not fetching all the resources in a group. We would group the ops manager images and stemcells for each of the 4 IaaSs with the .pivotal file, but we would only want the one stemcell and one ops manager for the IaaS we are testing in that pipeline.

**Comment by vito** [comment]
Here's a more fleshed out example:

```yaml
resources:
- name: aws-stemcell
  type: bosh-io-stemcell
  source: {...}

- name: vsphere-stemcell
  type: bosh-io-stemcell
  source: {...}

- name: cf-release
  type: bosh-io-release
  source: {...}

- name: diego-release
  type: bosh-io-release
  source: {...}

resource_groups:
- name: diego-cf-compat
  type: s3
  source: {...}
  resources: [cf-release, diego-release]

- name: cf-stemcell-compat
  type: s3
  source: {...}
  resources: [cf-release, vsphere-stemcell, aws-stemcell]

jobs:
- name: something-with-cf-and-diego-on-aws
  plan:
  - aggregate:
    - get: cf-release
      groups: [diego-cf-compat, cf-stemcell-compat]
    - get: diego-release
      groups: [diego-cf-compat]
    - get: aws-stemcell
      groups: [cf-stemcell-compat]
```

So, you could pick and choose what parts of the tuple you actually want, and you're still dealing with regular old Concourse resources, rather than passing around giant "union tarballs" or something. If you wanted to just produce URLs for the director to upload that would be done on a resource-by-resource basis, i.e. a param telling the resource to just give you the URL and not download it (which a few already support).

Notes:

* `resource_groups` configure where to find the "tuples" and what resources they map to. (May need a map here instead of a list, not sure what the actual contents of the resource would look like.)
* You'll notice strong parallels between `groups` and `passed` on the `get` steps.
* The resources themselves are configured and used as normal, making this a drop-in feature so you can reuse your tasks and much of your pipeline config.
