### ISSUE TITLE
Multiple resource listing on a single edge

### ISSUE THREAD

**Issue by loganmzz** [concourse/concourse#2101]
Hi there!

# Bug Report

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Laptop (CPU: Intel Core i7-7500U / RAM: 16 Go)
* Browser (if applicable): Chrome, Firefox

When a resource is process by multiple jobs in parallel but finally joined with intermerdiate job(s), resource is drawn multiple times on a single edge.
![wrong graph](https://user-images.githubusercontent.com/5030510/37662936-74c63e0e-2c58-11e8-99a3-652abc3103d7.png)

For example (idiom): I have an init job which generates a new resource (r0). This last one is processed by two jobs (j1, j2) in parallel. One of them (j1) also consumes resource (r0). When complete, all is joined into a final job.

For example (pipeline.yml):

```yml
---
resources:
- name: r0
  type: time

jobs:
- name: j0
  plan:
  - put: r0

- name: j1
  plan:
  - get: r0
    trigger: true
    passed: [j0]

- name: j1-1
  plan:
  - aggregate:
    - get: r0
      trigger: true
      passed: [j1]

- name: j2
  plan:
  - get: r0
    trigger: true
    passed: [j0]

- name: j9
  plan:
  - aggregate:
    - get: r0
      passed: [j1-1, j2]
```
