### ISSUE TITLE
3.10.0 and 3.11.0 error - /var/vcap/data/baggageclaim/volumes/live/xxxx/volume is not a mount point

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2166]
# Bug Report

* Concourse version: 3.10.0 or 3.11.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack (stemcell 3541.10)
* Did this used to work? yes, in 3.9.2

We deployed our workers (1 ATC, 2 workers) with workers using configuration such as the following (to use 'external workers'):
```
    name: worker
    release: concourse
    consumes: {baggageclaim: {from: worker-baggageclaim}}
    properties:
      drain_timeout: ((drain_timeout))
      log_level: ((groundcrew_log_level))
      tsa:
        worker_key: ((worker_key))
        host:  ((dns_name))
        port:  2222
        host_public_key: ((tsa_host_key.public_key))
        registration_mode: forward
      garden:
        forward_address: 127.0.0.1:7777
      baggageclaim:
        forward_address: 127.0.0.1:7788
      tags: ((worker_tags))
      http_proxy_url: ((http_proxy))
      https_proxy_url: ((http_proxy))
      no_proxy: ((no_proxy))
```
We are seeing the following error when we execute a pipeline:
```
	
unpaused 'test-put'
	
started test-put/put-test #5
	

	
initializing
	
/var/vcap/data/baggageclaim/volumes/live/6d167d93-281e-415b-4dfd-4bf6de939ede/volume is not a mount point
	
errored
	
```

We see the following in our logs:
```
<14>1 2018-04-17T17:42:46.493476Z 3b47a3a7-a18b-4ca8-a72d-491c712da800.worker.default.xxx.bosh garden rs2 - [instance@47450 director="" deployment="xxx" group="worker" az="z1" id="3b47a3a7-a18b-4ca8-a72d-491c712da800"] {"timestamp":"1523986966.247489929","source":"guardian","message":"guardian.api.garden-server.create.failed","log_level":2,"data":{"error":"/var/vcap/data/baggageclaim/volumes/live/6d167d93-281e-415b-4dfd-4bf6de939ede/volume is not a mount point","request":{"Handle":"60bd2a02-bb82-4e4c-6a12-04a9468e8b4c","GraceTime":0,"RootFSPath":"raw:///var/vcap/data/baggageclaim/volumes/live/9af86cc8-e592-447e-67fa-683973e9b8dc/volume","BindMounts":[{"src_path":"/var/vcap/data/baggageclaim/volumes/live/6d167d93-281e-415b-4dfd-4bf6de939ede/volume","dst_path":"/etc/ssl/certs"},{"src_path":"/var/vcap/data/baggageclaim/volumes/live/d96c0631-bd7e-4015-7f22-0efb078ae013/volume","dst_path":"/scratch","mode":1}],"Network":"","Privileged":true,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"3.1.10"}}
```
