### ISSUE TITLE
[BUG] Concourse web UI freezes when two jobs form a loop

### ISSUE THREAD

**Issue by marco-m** [concourse/concourse#2174]
# Bug Report

This is the return of #84, but now it requires two jobs in a loop situation to manifest itself. The following pipeline will freeze the web UI:

```
resources:

- name: repo.git
  type: git
  source:
    uri: ...
    branch: master

- name: version
  type: semver
  source:
    driver: s3
    ...

jobs:

- name: job1
  plan:
  - get: repo.git
    passed: [job2]
    trigger: true
  - get: version
    params: {pre: rc}
  - put: version
    params: {file: version/version}

- name: job2
  plan:
  - get: repo.git
    passed: [job1]
  - task: build-linux
    file: repo.git/ci/build.yml
```
This is the minimal pipeline that still reproduces the issue. I noticed that if I use only one resource, then the UI shows a nice loop :-) but doesn't freeze.

The problem is that if you introduce the loop by error (as it happened to me), it can take a lot of time to figure out what is the cause of the freeze. The logs don't mention anything.

The following can also be handy:

* Concourse version: 3.10.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: VM
* Browser (if applicable): both Chrome and Firefox
* Did this used to work? Don't know
