### ISSUE TITLE
resource type not found: git

### ISSUE THREAD

**Issue by stela** [concourse/concourse#2196]
# Bug Report

I receive a `resource type not found: git` error when viewing a resource pipeline using the web interface. Concourse fails to check out anything from git and start the build job state of the pipeline.

* Concourse version: 3.13.0 on macOS 10.13.4
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: macOS and `concourse quickstart` or `concourse web` + `concourse worker`
* Browser (if applicable): current stable chrome on macOS
* Did this used to work? Yes, in an older 3.x.x release deployed via bosh instead of as a binary.

Log output:
```json
{"timestamp":"1525361872.408726454","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"127.0.0.1:59324","session":"1","type":"keepalive"}}
{"timestamp":"1525361872.411205053","source":"atc","message":"atc.syncer.myproject-pipeline:radar.scan-resource.interval-runner.tick.failed-to-find-or-create-resource-config-check-session","log_level":2,"data":{"error":"resource type not found: git","pipeline-scoped-name":"myproject-pipeline:resource:myproject","session":"34.1.15.1.1"}}
{"timestamp":"1525361872.412256479","source":"atc","message":"atc.syncer.myproject-pipeline:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Name":"git"},"session":"34.1"}}
{"timestamp":"1525361872.420531988","source":"atc","message":"atc.syncer.myproject-pipeline:radar.scan-resource.interval-runner.tick.failed-to-find-or-create-resource-config-check-session","log_level":2,"data":{"error":"resource type not found: cf","pipeline-scoped-name":"myproject-pipeline:resource:deploy-myproject-dev","session":"34.1.16.1.1"}}
{"timestamp":"1525361872.422108650","source":"atc","message":"atc.syncer.myproject-pipeline:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Name":"cf"},"session":"34.1"}}
{"timestamp":"1525361872.672489643","source":"tsa","message":"tsa.connection.channel.forward-worker.heartbeat.start","log_level":1,"data":{"remote":"127.0.0.1:59324","session":"1.1.1.22","worker-address":"127.0.0.1:59328","worker-platform":"darwin","worker-tags":""}}
```

pipeline:
```yaml
resources:
- name: myproject
  type: git
  source:
    uri: git@github.com:mycompany/myproject.git
    branch: monorepo-first-attempt
    private_key: ((github-private-key))
- name: deploy-myproject-dev
  type: cf
  source:
    api: https://cf.endpoint.here
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: false

jobs:
- name: build-and-test-job
  public: false
  plan:
  - get: myproject
  - task: tests
    file: myproject/concourse/build.yml
  - put: deploy-myproject-dev
    params:
      manifest: cloudfoundry/manifest.mf
```

In the `atc` postgresql database, some tables contain data, but seemingly related tables are empty:
```sql
atc=# SELECT * FROM resource_types;
 id | pipeline_id | name | type | version | last_checked | config | active | nonce | resource_config_id 
----+-------------+------+------+---------+--------------+--------+--------+-------+--------------------
(0 rows)

atc=# SELECT * FROM base_resource_types;
 id | name 
----+------
(0 rows)
```

I mainly followed this guide to install concourse: 
https://gist.github.com/kevin-smets/f20afd45a24ab3f88d01b2049ce7744f
