### ISSUE TITLE
apparent race condition when replacing an existing artefact and then feeding it to another task

### ISSUE THREAD

**Issue by kalfa** [concourse/concourse#2205]
# Bug Report

The problem raises when I trigger manually the task, which takes from devel-branch the latest version, passes it to buid.sh which places the files in the respective buckets. The files are then fed to another task.

It seems to be some sort of race condition for which the tasks which are subsequently fed by those artefacts (in my case testing tasks) receive two different versions of the artefacts:

```
jobs:
- name: build and test
  plan:
  - get: devel-branch
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        [snip]  
      inputs:
      - name: devel-branch
      outputs:
      - name: pipenv-lock
      - name: built-package
      run:
        path: ci-scripts/ci/build.sh

  - aggregate:
    - put: pipenv-lock
      params:
        file: pipenv-lock/Pipfile*.lock
    - put: built-package
      params:
        file: built-package/((PYPI_PACKAGE_BASE_FILE_NAME))-*.whl
```

Where the actual filename for pipenv-lock is e.g Pipfile-0.0.79+gdead53c.lock
and for built-package is e.g. mypkg-0.0.79+gdead53c-py3-none-any.whl

pipenv-lock is then fed to (chopped-off yaml):
```
aggregate:
    - task: one
      inputs:
      - pipenv-lock
    - task: two
      inputs:
      - pipenv-lock
```

I noticed that they receive two different versions of pipenv-lock, one seem to be the one just created by the build and test task, which replaced the "old" (for some difinition of it) lock file, the other  received the the "old" version. 
It's clear because between the two builds (the fist one triggered by the commit and the manual one) the content changed (e.g., a pacakge the build depends on had a version bump) which in one case makes the task fail and in the other makes the task go happy.

For the records, a pipenv lock file contains the pinned versions of all the deps the pacakge depends on.

This clearly happens only when there is a previous version in the bucket, which has been replaced by the build task.
It might be that the aggregate bit is relevant.

the expected behaviour is that they are going to use the same version.
I personally would say the right one to choose is the latest one, just placed in the bucket.

* Concourse version: 3.11.0
* Deployment type: binary on linux.
