### ISSUE TITLE
Pipelines paused forever with no error for user if vault credentials do not exist

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2208]
# Bug Report

We are using VAULT to store secrets for our pipelines.  We have found that if vault tokens are referenced, particularly in resource type definitions, and they don't exist, the user is 'told' that no versions are found and a job is pending when the truth is that the pipeline will never run.

Example:
![image](https://user-images.githubusercontent.com/10414523/39804631-7b34a2ea-536c-11e8-84e0-950a68618e9a.png)

However, if the credentials exist, but are invalid, the user will see information denoting this fact:
![image](https://user-images.githubusercontent.com/10414523/39804644-858f23d2-536c-11e8-9db8-ab6a33ab583c.png)

![image](https://user-images.githubusercontent.com/10414523/39804688-a34d5b0a-536c-11e8-98ae-230993840f15.png)

There are errors listed in the ATC logs, but users certainly can not see these.

* Concourse version: 3.8.0, 3.9.2
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
* Browser (if applicable): N/A
* Did this used to work? No.

**Comment by colmtuohy** [comment]
+1

**Comment by a459259** [comment]
+1

**Comment by robtec** [comment]
I have also reproduced this issue around the missing vault tokens, on the same environment as @keithkroeger 

Both `vault-image-resource-micky-mouse` and `vault-image-resource-pwd-mouse` don't exist in our Vault

```
---
resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: private.docker.com/springio/artifactory-resource
    username: ((vault-image-resource-micky-mouse))
    password: ((vault-image-resource-pwd-mouse))

resources:
- name: artifactory
  type: artifactory-resource

jobs:
- name: reproduce
  plan:
  - get: artifactory
```

This pipeline results in the `artifactory` resource checking forever :cry: 

![issue-conc](https://user-images.githubusercontent.com/8657653/39871978-71e3930c-545e-11e8-96f1-9a162b61266f.JPG)

Now lets change our pipeline

Instead of using a `get: artifactory` under `jobs.plan`, lets use `put: artifactory`

Bingo, now we get a nice error and the pipeline fails :tada: 

![issue-conc2](https://user-images.githubusercontent.com/8657653/39872065-ab69a350-545e-11e8-9867-1b20c8935eb4.JPG)


Why though?
