### ISSUE TITLE
Shared webhook endpoint for multiple resources

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#2230]
# Feature Request

## What challenge are you facing?

We have one single GitHub repository that includes many different conceptual resources. For example, _n_ directories, one for each application we release. We use `source.paths` to generate versions for the resources only when the folder representing the contents of the resource has changed. This results in _n_ checks every `check_interval`, which puts a lot of strain on our workers.

We want to use `webhook_token`s to reduce strain (and setting `check_interval` to a very high number), but each resource has its own webhook URL, which means we must create a GitHub webhook for each resource. Not only is this an operational burden, but GitHub has a limit of 20 webhooks for a single repository (see [docs](https://developer.github.com/webhooks/)), preventing us from using this solution as our number of resources grows.

## A Modest Proposal

I would like to be able to define a single webhook URL that can trigger all _n_ resources. This would still result in _n_ checks on every push, but would greatly reduce the total number of checks that are run. Some YAML like this would be good:

```
resources:
- name: app-one
  type: git
  source:
    uri: git@github.com:org/repo.git
    branch: master
    paths: [app_one]
  webhook:
    name: MY_WEBHOOK
    token: WEBHOOK_TOKEN

- name: app-two
  type: git
  source:
    uri: git@github.com:org/repo.git
    branch: master
    paths: [app_two]
  webhook:
    name: MY_WEBHOOK
    token: WEBHOOK_TOKEN
```

Which would allow me to configure GitHub with a webhook path of `https://my-concourse.example.com/api/v1/teams/TEAM_NAME/pipelines/PIPELINE_NAME/webhooks/MY_WEBHOOK?webhook_token=WEBHOOK_TOKEN`.

An alternate structure:

```
webhooks:
- name: MY_WEBHOOK
  token: WEBHOOK_TOKEN

resources:
- name: app-one
  type: git
  source:
    uri: git@github.com:org/repo.git
    branch: master
    paths: [app_one]
  webhooks: [MY_WEBHOOK]

- name: app-two
  type: git
  source:
    uri: git@github.com:org/repo.git
    branch: master
    paths: [app_two]
  webhooks: [MY_WEBHOOK]
```

**Comment by billimek** [comment]
👍 for this as well.  We end up creating a ton of webhooks on the github side and would love to have just one trigger a check for everything.

**Comment by a459259** [comment]
+1 - We have a similar use-case, would make a lot of sense to have this in place...

**Comment by haganbmj** [comment]
Echoing these sentiments. Currently putting off transitioning a couple dozen projects because it would mean manually creating 4+ webhooks per each one while still not having support for building feature branches.

**Comment by databus23** [comment]
FYI: I created a small service to solve this issue with our concourse deployment:  https://github.com/sapcc/webhook-broadcaster

**Comment by vito** [comment]
@wendorf Neat! I like the second form. Is there a use case for listing multiple webhook names? (It makes sense to me, just curious.)

@databus23 That's awesome, thanks for open-sourcing it!

**Comment by wendorf** [comment]
@vito I prefer the second form as well. I don't think I had any use-case for multiple webhooks—probably just overeager.

Took a look at @databus23 's webhook-broadcaster, which looks super useful in the interim. That use case has even tougher requirements, though, with 70 pipelines, and would still not be satisfied by this proposal. It'd be worth thinking if there's an elegant solution to share webhooks across pipelines (scoped to teams, likely), but that's above my pay grade.

**Comment by timrchavez** [comment]
We have not discovered a need for a single resource to have multiple webhook tokens. Also, now that we've made webhook tokens Vault-able, reusing tokens has become very simple with Concourse cred interpolation. I think @databus23 actually solves the problem we're having and that is, having to configure a million web hooks in GHE. Even having to configure webhooks per-pipeline is cumbersome. I think their little service solves the UX problem nicely.

**Comment by schmurfy** [comment]
I just found this, is there anything happening for that issue ?
Sure the broadcaster may solve the issue but this should be done by concourse itself and not need an external application.

**Comment by taylorsilva** [comment]
@schmurfy This issue is not part of the team's backlog. Someone in the community could pick this one up, as indicated by the [help wanted](https://github.com/concourse/concourse/labels/help%20wanted) label

**Comment by vito** [comment]
@schmurfy I've been working on an RFC proposing a new design for this, but I'm currently too busy with other things to finish it up. A very very messy WIP is [here](https://github.com/vito/rfcs/blob/webhooks/000-webhooks/proposal.md) if you care to poke around. Note that some ideas the document are scrapped but still left around, so take it with a grain of salt.

**Comment by schmurfy** [comment]
@vito after looking at this I think one such system should be even simpler, I was thinking you could just define webhooks on one side with no intelligence and link them to resources of other entities by using their name/id/whatever:

```yaml
webhooks:
- name: hook1
  token: hook1-token


resources:
- name: mygit
  webhook: hook1

```

The webhook would have no intelligence by itself (other than maybe allowing to respond to challenge but I am pretty sure a first version could even ignore this) aside from keeping a list of "things" to trigger.
