### ISSUE TITLE
Build view shows multiple icons for the same build

### ISSUE THREAD

**Issue by andrewedstrom** [concourse/concourse#2250]
# Bug Report

When we create a new job and run it for the first time (triggering it from the empty build view), we see multiple icons for the build show up.

![lots of icons](https://i.imgur.com/Tzbb70T.png)

If we refresh the page, it goes down to a single icon, then starts adding icons one at a time every second or two.

Here is the job description from the pipeline.yml:
```
- name: deploy-production
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    passed: [deploy-review]
  - put: production-deployment
    params:
      manifest: pal-tracker/manifest-production.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from the production environment"
```

and our cf manifest is

```
---
applications:
- name: pal-tracker
  path: build/libs/pal-tracker.jar
  host: pal-tracker
```

* Concourse version:  3.13.1-rc.42 
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Whatever wings is running on
* Browser (if applicable): Chrome
* Did this used to work? Yes. We first noticed this after the update of wings to 3.13.1-rc.42
