### ISSUE TITLE
Feature Request: check_every for resource types

### ISSUE THREAD

**Issue by billimek** [concourse/concourse#2251]
# Feature Request

## What challenge are you facing?

As a pipeline,
I want to be able to override the default check interval for resource types,
So that I can configure custom check intervals for resource types like I do for resources via the `check_every` setting

When the default global check interval set to some large interval via the  `CONCOURSE_RESOURCE_CHECKING_INTERVAL` env variable this appears to have a negative impact on resource types not checking for updates (e.g. new docker images for the same or new tag).

We have observed that when we set `CONCOURSE_RESOURCE_CHECKING_INTERVAL` to a very large value, the resource types (e.g. using a docker image) appears to continually use just the cached image it first pulled-down.  When updating to a new tag and re-flying the pipeline, we continue to see the originally tagged image sha being referenced.

## A Modest Proposal

Enhance concourse to allow the `check_every` stanza to be passed to resource types like we do for resources.  Something like this:

```
resource_types:
  - name: my-awesome-resource-type
    type: docker-image
    source:
      repository: some/image
      tag: 'some_tag'
    check_every: 1h
```

Maybe allow this to be overridden in [resource_type_scanner.go](https://github.com/concourse/atc/blob/master/radar/resource_type_scanner.go) and related modules?

**Comment by clarafu** [comment]
We added the check_every config to the configuration of a custom resource type on the pipeline. For example, 

```yaml
resource_types:
  - name: my-awesome-resource-type
    type: docker-image
    check_every: 10ms
    source:
      repository: some/image
      tag: 'some_tag'
```

We also added a flag (`--resource-type-checking-interval`) to the atc which allows configuring a default check interval for resource types.
