### ISSUE TITLE
check_every does not default to 1m

### ISSUE THREAD

**Issue by alkar** [concourse/concourse#2280]
# Bug Report

Unless `check_every` is specified, resources are only checked once when the pipeline is unpaused.

Example:
```
resources:
- name: 10s
  type: time
  source:
    interval: 10s
jobs:
- name: check-every-10s
  plan:
  - get: 10s
    trigger: true
```

To fix this simply specify `check_every: 5s` for the resource.
However, updating the pipeline does not seem to work - deleting the pipeline and re-creating it will do the trick.

I expected the resource to be checked every `1m` as per the default value mentioned in the documentation for resources.

* Concourse version: 3.14.0
* Deployment type (BOSH/Docker/binary): N/A
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): N/A
* Did this used to work? Docs seem to imply it did.

First seen: https://github.com/concourse/time-resource/issues/28
