### ISSUE TITLE
Configurable grace period for garbage collection of one-off build containers

### ISSUE THREAD

**Issue by databus23** [concourse/concourse#2289]
# Bug Report
I noticed that `fly execute` task containers get reaped almost instantly after they have finished executing.
The exit code of the task is not relevant, in both cases they container is gone within seconds.

## Steps to reproduce
task.yaml:
```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: sh
  args:
    - -ec
    - |
      echo hello
      exit 1
```
```
> fly execute -t ... -c task.yaml
(wait 5-10 seconds)
> fly hijack -b $BUILDNR /bin/sh
# either returns:
error: websocket: bad handshake
# or after a couple more seconds:
no containers matched your search parameters!

they may have expired if your build hasn't recently finished.
```

If you execute the `hijack` command really quickly it works but giving that you have to get the build number from the build output its practically impossible to achieve.

I'm pretty sure this used to work and the expiry times of one-off containers where somewhat similar to regular containers.

* Concourse version: 3.13,3.14,master
* Did this used to work? Yes
