### ISSUE TITLE
cannot unmarshal !!seq into map[string]string

### ISSUE THREAD

**Issue by dober** [concourse/concourse#2298]
Bug Report

it happening with paths

error: yaml: unmarshal errors:
  line 23: cannot unmarshal !!seq into map[string]string

```
---
resource_types:
  - name: maven-cache
    type: docker-image
    source:
        username: ((docker_registry_user))
        password: ((docker_registry_password))
        repository: "registry/maven"
        tag: "3.5.3-jdk-8-alpine"

resources:
  - name: git-repo
     type: git
     source: &some-source
       uri: git@bitbucket.org:git-repo/
       private_key: ((ssh_key))
       branch: master

  - name: some-cache
    type: maven-cache
    source:
        <<: *some-source
        paths:   # line 23
            - pom.xml
```

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: QEMU/KVM
* Browser (if applicable):
* Did this used to work?
