### ISSUE TITLE
Caching directories between runs of a task

### ISSUE THREAD

**Issue by vito** [concourse/concourse#230]
Common use case: fetching dependencies, syncing BOSH blobs, etc.

Caching the directories that these fetch into and update would dramatically speed up a bunch of builds. Our own ATC JS build spends 99% of its time just downloading `npm` packages.

Proposal:

Add a `cache` field to task configs, like so:

``` yaml

---
platform: linux

inputs:
- name: my-release

cache:
- path: my-release/.blobs

run:
  path: my-release/ci/scripts/create-release
```

Then, given I have a pipeline like so:

``` yaml
jobs:
- name: make-release
  plan:
  - get: my-release
  - task: create-release
    file: my-release/ci/create-release.yml
```

This would cache the directory `my-release/.blobs` between runs of that specific task in its job's build plan. So, the cache lookup key would be something like `team-id+pipeline-id+job-name+task-name`.

Notes:
- This should also have the guarantee that two concurrent builds of the same job do not pollute each others' caches. There should be some sort of copy-on-write semantics, such that each job gets its own copy of the cache (initially empty), and at the end all other caches are marked "stale" and are set to expire.
- Assumes tools will be durable to the directory being initially present + empty on the initial cache run. I think this should be fine. Without this it'll be very annoying to orchestrate.
- The caching is for purely ephemeral data, so it doesn't sacrifice Concourse's "not being a source of truth" principle.
- Has the same cache warming semantics as `get`s, i.e. it may take a bit for the cache to warm across the workers; it does not influence worker placement.
- Has no effect on one-off builds, as there is not enough information to scope/correlate the caches (compared to a job build).

**Comment by xoebus** [comment]
:+1:

It's an important feature but I can see it getting abused. Maybe we need a best practices document that sets some guidelines for having a sane pipeline. e.g. don't publish a different artefact to the same version number otherwise nothing will work properly.

**Comment by nicorikken** [comment]
I'd certainly like to see this come about. Our use-case includes downloading NPM dependencies as well, but also downloading Nix-packages. Copy-on-write would suit that use-case.

Sharing this cache even among pipelines would make sense efficiency-wise, although that would introduce (semantic) dependencies between pipelines.

**Comment by vito** [comment]
@nicorikken We'll probably not start with cross-pipeline or even cross-job caching as that opens another can of worms: how to configure which caches apply to which tasks/etc. I could see that becoming a nightmare pretty quickly if you e.g. copy a job from another pipeline that has a cache name the same as yours because it was called something too generic.

So we'll probably just stick with as tightly-scoped as possible (individual task within job).

**Comment by nicorikken** [comment]
@vito Totally agree, makes most sense. There are other 'hacks' for getting around such issues, and worst-case somebody would have to write a specific resource targeting the local disk.

**Comment by jchester** [comment]
:+1: from me, both privately (I have a pipeline pulling umpteen zillion jars) and professionally (pivnet is a hungry gem consumer).

**Comment by devcurmudgeon** [comment]
not sure i understand this discussion properly, but i think just supporting the possibility to have 'cache' directory/ies untouched between jobs would be useful on its own. various tools have their own cache lookup processes (eg bitbake)

**Comment by tomwhoiscontrary** [comment]
👍 we've got microservices built with Gradle, so every one of our 27 tasks starts by downloading Gradle, then all our dependencies, and it's horrendous. Cache plox.

As a stop-gap, could we write some sort of pre-loading resource? It would somehow download the Gradle binary and some set of dependencies, then we would copy that into place before kicking off the build. That would let us exploit Concourse's local caching of resources, right?

**Comment by simonvanderveldt** [comment]
> @nicorikken We'll probably not start with cross-pipeline or even cross-job caching as that opens another can of worms: how to configure which caches apply to which tasks/etc. I could see that becoming a nightmare pretty quickly if you e.g. copy a job from another pipeline that has a cache name the same as yours because it was called something too generic.
> 
> So we'll probably just stick with as tightly-scoped as possible (individual task within job).

@vito While I do understand it will be hard to make sure people don't use it for the wrong reasons we see a serious speedup with shared caches between pipelines (and by extension also between jobs).
But the caches we share in these cases are the "normal" per user package manager's caches, so for example for npm this is [`~/.npm/](https://docs.npmjs.com/misc/config#cache) and for sbt this is `~/.ivy2/`. 

Would it be possible to support this somehow?


> @vito Totally agree, makes most sense. There are other 'hacks' for getting around such issues, and worst-case somebody would have to write a specific resource targeting the local disk.

@nicorikken Can you share those other "hacks"?

**Comment by seadowg** [comment]
As a wee push: not having this feature is still causing major problems with Concourse at some enterprise companies due to terrible connections (usually through a VPN). I've seen this drop down the backlog a couple of times so just thought I'd add my feelings from the world of self important anecdotal evidence.

**Comment by tomwhoiscontrary** [comment]
@seadowg Oh, i really should mail out about this: we made a Gradle-specific caching thingy on our project. Because Docker Hub automatic builds need public repos, i had to make it public, so i guess you can read it?

https://github.com/projectfalcon/gradle-cache-resource

You might be able to do something similar. The example pipeline builds Spring with it.

The way it works is that you still need to download all the dependencies in one go, but only once, after that it's cached. Until one of them changes, then you have to download them all again.

Also, i've been off sick, so by now Thorbs may have replaced this with some rival saucer science.

**Comment by nicorikken** [comment]
@simonvanderveldt The hacks were a while ago, and I hope Concourse has improved on many levels since then. We tried sharing the local directories, but that didn't go so well (don't remember). We eventually were having Dockers on Docker Hub in multiple stages in the pipeline: [Base build dependency image] -> (fetch latest dependencies) -> [Up-to-date build dependency image] -> (build) -> [finished build] -> (test) -> [build and tested image]

**Comment by poida** [comment]
We also need to be able to cache folders (NPM modules folder) between jobs.
Currently Concourse runs 2-3 times slower than similar pipeline on Jenkins just because of NPM INSTALL.
Any ideas, hacks to speed it up?

**Comment by chipx86** [comment]
For ours, we're using a fork of concourse-rsync-resource (https://github.com/beanbaginc/concourse-rsync-resource) and define a resource for each type of build we need to share. This looks like:

```yaml
- name: my-project-env
  type: rsync-resource
  check_every: 10m
  source:
      server: our-builds.example.com
      base_dir: /path/to/unique/build/dest
      user: build-username
      private_key: {{builds-ssh-key}}
```

We have a job for each of these that builds the environment and puts it:

```yaml
- name: my-project-prep
  plan:
      - task: prep
        file: tasks/my-project/prep.yaml
        input_mapping:
            source: my-project-src

      - put: my-project-env
        name:
             sync_dir: env
```

Jobs that need it just do a `get`:

```yaml
- get: my-project-env
  trigger: true
  passed:
      my-project-prep
```

That `prep.yaml` file looks like:

```yaml
platform: linux

image_resource:
    ...

inputs:
    ...

outputs:
    - name: env
      path: env

run:
    path: tasks/my-project/prep.sh
```

The `prep.sh` just does what it needs to do, and then outputs to wherever it needs in the `env` directory. Other tasks can then make use of what's in there.

For node packages, we use `npm-cache` to help with the cache. We have a helper function for use in the `prep.sh` scripts to set up that cache, install the modules, and store them in the environment:

```shell
function build_and_store_node_modules() {
    cache_dir=$BUILDS_DIR/env/.package_cache

    mkdir $cache_dir
    ln -s $cache_dir ~/.package_cache

    echo Installing node modules...
    npm install -g npm-cache
    npm-cache install
}
```

Scripts that need to load the environment then just call this helper:

```shell
function restore_node_modules() {
    echo Restoring node modules...
    ln -s $BUILDS_DIR/env/.package_cache ~
}
```

Hope that helps! I can provide more examples if needed.
