### ISSUE TITLE
Feature: Combined/aggregated triggers

### ISSUE THREAD

**Issue by romerojunior** [concourse/concourse#2324]
# Feature Request

## What challenge are you facing?

We currently need a way of aggregating a trigger, for example: 
* If you have a integration test job that depends on two (or more) resources outputted by previous jobs, you would want this test to ONLY be triggered after all previous jobs have been successfully completed.

## A Modest Proposal

Currently, when using multiple `get` steps with triggers, the expected behaviour is similar to an `OR` operation, for example:

```
 - name: INTEGRATION_TEST
    plan:
    - aggregate:
      - get: package_A
        passed: [BUILD_PACKAGE_A]
        trigger: true
      - get: package_B
        passed: [BUILD_PACKAGE_B]
        trigger: true
```

In the example above, the INTEGRATION_TEST will be triggered whenever package_A `OR` package_B is successfully outputted by their respective build jobs. 

My proposal is to come up with a way of (optionally) changing the default `OR` behaviour to an `AND`, where both BUILD_PACKAGE_A and BUILD_PACKAGE_B jobs have to successfully output the resources fetched by the INTEGRATION_TEST in order for the trigger to work. In other words: INTEGRATION_TEST would wait for all `get` steps to be triggered.

```
 - name: INTEGRATION_TEST
    plan:
    - trigger:
      - get: package_A
        passed: [BUILD_PACKAGE_A]
      - get: package_B
        passed: [BUILD_PACKAGE_B]
```

**Comment by cloudsquirrel** [comment]
precisely what we've been looking for! 👍

**Comment by vito** [comment]
I'm not sure I follow. How is this different from a normal fan-in, where you list multiple jobs in `passed`? Can you provide a full pipeline example for this?

**Comment by romerojunior** [comment]
Hallo!

@vito currently we're limited to: if a single condition is met, the job will be triggered.

As I see it, the limitation is not related to the `passed` functionality, but the `trigger`. Imagine you wish to start (trigger) a job **only** if a series of conditions have been met.

One example for this would be an application that requires multiple modules/libraries/whatever to be compiled/tested separately, but still, at some point in the pipeline, if they all pass a series of jobs, they can be put together, tested and packaged.

With this "if a single condition is met, the job will be triggered" logic in place, this "final packaging job" (as described above) will be triggered for each time a single module/library/whatever hits the trigger, generating a bad package.

**Comment by vito** [comment]
@romerojunior But don't you need something correlating the packages so that you know they're "for" each other in the first place? Or do you want it to only run when there are new versions of *all 3* resources? (...But what if you only need to make a change to one?)

I'd recommend taking a look at the "Fanning In" example here, if you haven't already: https://concourse-ci.org/get-step.html - it shows how `passed` implements fan-in and also correlates jobs across `get` steps. Not sure understanding this is core to your issue but it should help anyway.

As a real-world example, the Concourse project puts all of our components in one repo as submodules. This way each commit of the toplevel repo is the "source of truth" for the versions that are expected to be compatible with each other. We push a bump commit, which then triggers individual unit tests, each with the same resource as their input. We then "fan in" on that same resource (`concourse` in our case) having `passed` all of the individual unit test jobs, and pass it along to the next job.

You can see the rendered pipeline here: https://ci.concourse-ci.org/teams/main/pipelines/main - and the config here: https://github.com/concourse/pipelines/blob/ae3d57a596adb063b2066d1c3b096b172d32a86c/ci.concourse-ci.org/concourse.yml#L57-L184 (I've highlighted a subset that's relevant, but there are other examples of this workflow in the same config.)

Without having a single resource that you can correlate the jobs and resources to, you would need something like https://github.com/concourse/concourse/issues/604 if you want to only trigger on them all changing. But then I'm still not sure how you'd handle the (I'd expect common) case of only changing one of the packages.

**Comment by loganmzz** [comment]
To handle such cases I passed original resource (source code ?) across entire pipeline to form a single stream. It doesn't do the job ?

```yml
---
resources:
- name: source-code
- name: package-common
- name: package-a
- name: package-b

jobs:
- name: build-common
  plan:
  - get: source-code
  - task: build-common
  - put: package-common

- name: build-a
  plan:
  - aggregate:
    - get: source-code
      passed: [build-common]
    - get: package-common
      passed: [build-common]
  - task: build-a
  - put: package-a

- name: build-b
  plan:
  - aggregate:
    - get: source-code
      passed: [build-common]
    - get: package-common
      passed: [build-common]
  - task: build-b
  - put: package-b

- name: check-integration
  plan:
  - aggregate:
    - get: source-code
      passed: [build-a, build-b]
    - get: package-a
      passed: [build-a]
    - get: package-b
      passed: [build-b]
  - task: run-integration-test
```
