### ISSUE TITLE
BOSH deployed Influxdb emitter not sending metrics.

### ISSUE THREAD

**Issue by fewknow** [concourse/concourse#2381]
# Bug Report
The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS:  AWS 
* Browser (if applicable): Chrome
* Did this used to work?  No 

I have configured my bosh manifest for the atc to have influxdb metric emmiter according to (https://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=3.14.1#p%3dvault) . 
 ```
 jobs:
  - release: concourse
    name: atc
    properties:
      log_level: debug

      token_signing_key: ((token_signing_key))
      external_url: ((external_url))
      
      vault:
        auth:
          backend: token
          client_token:<redacted>
        url: https://vault.mgmt.corvesta.net
        
      influxdb:
        database: telegraf
        username: <redacted>
        password: <redacted>
        url: http://10.90.34.27:8086 
```
 but it doesn't seem to be sending any stats to influxdb as I don't see any in the UI.  Is there a way I can check this or is there something else that needs to be done?

I do see it registered a `web-0` so I am assuming it saw this web server.  I have 1 web and 10 workers.

<img width="876" alt="screen shot 2018-07-16 at 12 27 31 pm" src="https://user-images.githubusercontent.com/22297806/42770983-b4f17212-88f3-11e8-873d-df575a102f1b.png">
