### ISSUE TITLE
Not able to pull docker images

### ISSUE THREAD

**Issue by prasenforu** [concourse/concourse#2388]
Help Need:

I have my own Private DNS server 10.90.1.78 running on AWS VPC.
And I have a Private Registry (Harbor) running on 10.90.1.78 (same server)

Another host running concourse in Amazon Linux with following docker file.

```
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL
    - CONCOURSE_BASIC_AUTH_USERNAME
    - CONCOURSE_BASIC_AUTH_PASSWORD
    - CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH=true
    - CONCOURSE_WORKER_GARDEN_NETWORK
```
Concourse server /etc/resolve.conf file 

```
[root@ip-10-90-1-163 ~]# more /etc/resolv.conf
options timeout:2 attempts:5
; generated by /sbin/dhclient-script
search tcs-ally.tk
nameserver 10.90.1.78
```
and able to ping 

```
[root@ip-10-90-1-163 ~]# ping 10.90.1.78
PING 10.90.1.78 (10.90.1.78) 56(84) bytes of data.
64 bytes from 10.90.1.78: icmp_seq=1 ttl=64 time=0.469 ms
64 bytes from 10.90.1.78: icmp_seq=2 ttl=64 time=0.605 ms
```

my pipeline as follows.

```
---
clair_scan_params: &clair_scan_params
  CLAIR_ADDR: {{clair_addr}}
  CLAIR_IMAGE: {{clair_image}}
  HARBOR_USERNAME: {{harbor_username}}
  HARBOR_PASSWORD: {{harbor_password}}

notary_sign_params: &notary_sign_params
  HARBOR_USERNAME: {{harbor_username}}
  HARBOR_URL: {{harbor_url}}
  HARBOR_IMAGE: {{harbor_image}}
  HARBOR_PASSWORD: {{harbor_password}}
  HARBOR_CA_CERT: {{harbor_ca_cert}}
  HARBOR_CA_KEY: {{harbor_ca_key}}
  NOTARY_FILE_1: {{notary_file_1}}
  NOTARY_KEY_1: {{notary_key_1}}
  NOTARY_FILE_2: {{notary_file_2}}
  NOTARY_KEY_2: {{notary_key_2}}
groups:

- name: Image-Pipeline
  jobs:
  - build-docker-image
  - cve-scan-harbor-image
  - push-harbor-image

resources:
- name: git-spring1-ci
  type: git
  source:
    uri: https://github.com/prasenforu/concourse-ci
    branch: master

- name: git-go-http
  type: git
  source:
    uri: https://github.com/prasenforu/dockerapp
    branch: master

- name: harbor-image
  type: docker-image
  source:
    username: {{harbor_username}}
    password: {{harbor_password}}
    repository: {{harbor_repository}}
    insecure_registries:
    - {{harbor_insecure_registry}}

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-go-http
    trigger: true
  - put: harbor-image
    params:
      build: git-go-http

- name: cve-scan-harbor-image
  plan:
  - aggregate:
    - get: git-spring1-ci
    - get: harbor-image
      passed: [build-docker-image]
      trigger: true
  - task: clair-scan-image
    file: git-spring1-ci/tasks/clair-scan-image/task.yml
    params: *clair_scan_params

- name: push-harbor-image
  plan:
  - aggregate:
    - get: git-spring1-ci
    - get: harbor-image
      passed: [cve-scan-harbor-image]
      trigger: false
  - task: notary-sign-image
    privileged: true
    file: git-spring1-ci/tasks/notary-sign-image/task.yml
    params: *notary_sign_params
```

Getting following error ..

```
Login Succeeded
Sending build context to Docker daemon  132.6kB
Step 1/4 : FROM busybox
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.18.0.3:53: read udp 10.254.0.18:50602->172.18.0.3:53: i/o timeout
```
![image](https://user-images.githubusercontent.com/19322497/42800492-bccfef92-89b9-11e8-9dfd-d52b3941ba58.png)

NOTE: If I use Docker Hub then all works fine but issue is when use Private Registry server with local DNS.
