### ISSUE TITLE
Trouble deploying concourse boshrelease cluster with external ssl postgres server 

### ISSUE THREAD

**Issue by donghoang89** [concourse/concourse#2397]
## What challenge are you facing?

ENVIRONMENT:

> stemcell: bosh-aws-xen-hvm-ubuntu-trusty-go_agent  3586.25*  ubuntu-trusty  aws  ami-75ae8e0a light
> bosh releases:
> - concourse: v3.14.1
> - garden-runc: v1.15.1
> - postgres: latest

ISSUE:

I am trying to deploy a concourse cluster of 1 web server, 3 worker servers and 1 db server. The postgres server is configured to run on ssl. 

When deployed, the db and worker servers would come up just fine. However, the web server would fail. The reason is because the atc fails to present a valid certificate when it tried to connect to the postgres server.

I bosh-ssh into the web server and take a look at the **/var/vcap/jobs/atc/bin/atc_ctl** file

What I expect to see:
>      61       --peer-url http://xxxxx:8080 \
>      62       --external-url https://web-atc.service.consul \
>      63       --postgres-host xxxxx \
>      64       --postgres-port 5432 \
>      65       --postgres-database atc \
>      66       --postgres-sslmode verify-ca \
>      67       --postgres-user concourse \
>      68       --postgres-password '' \
>      69        \
>      70       --postgres-ca-cert $POSTGRESQL_CA_CERT \
>      71       --postgres-client-cert $POSTGRESQL_CLIENT_CERT \
>      72       --postgres-client-key $POSTGRESQL_CLIENT_KEY \
>      73        \
>      74        \
>      75       --postgres-connect-timeout 5m \
>      76        \
>      77        \
>      78        \
>      79       --log-level debug \

What I actually see:

>      61       --peer-url http://XXXXX:8080 \
>      62       --external-url https://web-atc.service.consul \
>      63       --postgres-host XXXXX \
>      64       --postgres-port 5432 \
>      65       --postgres-database atc \
>      66       --postgres-sslmode verify-ca \
>      67       --postgres-user concourse \
>      68       --postgres-password '' \
>      69        \
>      70       --postgres-ca-cert $POSTGRESQL_CA_CERT \
>      71        \
>      72        \
>      73       --postgres-connect-timeout 5m \
>      74        \
>      75        \
>      76        \
>      77       --log-level debug \

  
The two lines for 'postgres-client-cert' and 'postgres-client-key' are missing. I can verify that my cert is valid. If i copy and paste those two lines to the file, 'monit start atc' would succeed, and concourse would work as intended.

Below is the ATC block in my concourse manifest file. I am using a pre-generated cert, instead of letting variable type certificate generate client_cert for me. ((postgres_cert)) is a hash of ca, certificate and private_key.

```
  - name: atc
    release: concourse
    properties:
      token_signing_key:
        public_key: |
          XXXXX
        private_key: |
          XXXXX
      postgresql:
        sslmode: verify-ca
        database: atc
        role:
          common_name: XXXXX
          name: concourse
        ca_cert: |
          XXXXX
        client_cert: ((postgres_cert))
        client_key: true
      main_team:
        auth:
          allow_all_users: true
      add_local_users:
      - XXXXX:XXXXX
      emit-to-logs: true
      external_url: https://web-atc.service.consul
      tls_bind_port: 443
      tls_cert: |
        XXXXX
      tls_key: |
        XXXXX
      log_level: debug
      basic_auth_username: XXXXX
      basic_auth_password: XXXXX
```

I went to https://github.com/concourse/concourse/blob/master/jobs/atc/templates/atc_ctl.erb to take a look and see the following block [line 129-135]

>       <% if_p("postgresql.ca_cert") do |_| %> \
>       --postgres-ca-cert $POSTGRESQL_CA_CERT \
>       <% end %> \
>       <% if_p("postgresql.client_cert", "postgresql.client_key") do |*_| %> \
>       --postgres-client-cert $POSTGRESQL_CLIENT_CERT \
>       --postgres-client-key $POSTGRESQL_CLIENT_KEY \
>       <% end %> \

I wonder how are "postgresql.client_cert" and "postgresql.client_key" being checked in this case? I can't seem to find any mention of "postgresql.client_key" in the https://github.com/concourse/concourse/blob/master/jobs/atc/spec file.

How should I add "postgresql.client_cert" and "postgresql.client_key" properties in the manifest file to get the expected result in the **/var/vcap/jobs/atc/bin/atc_ctl** file?
