### ISSUE TITLE
Concourse Seems to Expose Secrets on Web Nodes

### ISSUE THREAD

**Issue by ryanaross** [concourse/concourse#2415]
# Bug Report

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

The following can also be handy:

* Concourse version: 3.13.0
* Deployment type (BOSH/Docker/binary): BOSH / concourse-release

Hello Concourse devs, 

Great product, but am having an issue with plaintext communication between web and workers. 

Here is a sample of output from running 
`tcpdump -i eth0 'port 7777' -X`
On a 'web' instance:
```
17:15:25.387058 IP c3b9--asdgd-9f64-4b70-bfd4-903bd604509f.web.default.concourse-airlock.bosh.34000 > 1663-e497-4b98-a2323-8db2-e60b3997cc55.worker.default.concourse-airlock.bosh.7777: Flags [P.], seq 252:713, ack 196, win 229, options [nop,nop,TS val 16542092 ecr 16460566], length 461
	0x0000:  4500 0201 0fd3 4000 4006 f7f2 0a83 0e0a  E.....@.@.......
	0x0010:  0a83 0e22 84d0 1e61 c450 67ac ffeb 8fa9  ..."...a.Pg.....
	0x0020:  8018 00e5 3325 0000 0101 080a 00fc 698c  ....3%........i.
	0x0030:  00fb 2b16 7b22 7072 6f63 6573 735f 6964  ..+.{"process_id
	0x0040:  223a 2230 6236 6437 3735 622d 3732 3034  ":"xxxxxxx-xxxx
	0x0050:  2d34 6232 392d 3563 6235 2d64 6436 3061  -xxxx-xxxx-xxxxx
	0x0060:  3035 6662 6232 3022 2c22 736f 7572 6365  xxxxx","source
	0x0070:  223a 302c 2264 6174 6122 3a22 7b5c 2273  ":0,"data":"{\"s
	0x0080:  6f75 7263 655c 223a 7b5c 2261 6363 6573  ource\":{\"acces
	0x0090:  735f 6b65 795f 6964 5c22 3a5c 2250 5346  s_key_id\":\"X\",
	0x00b0:  5c22 6275 636b 6574 5c22 3a5c 2263 6f6e  \"bucket\":\"con
	0x00c0:  636f 7572 7365 2d62 6163 6b75 7073 5c22  course-backups\"
	0x00d0:  2c5c 2264 6973 6162 6c65 5f73 736c 5c22  ,\"disable_ssl\"
	0x00e0:  3a66 616c 7365 2c5c 2265 6e64 706f 696e  :false,\"endpoin
	0x00f0:  745c 223a 5c22 736c 6364 3030 3070 6662  t\":\"xxxxxxxxxx
	0x0100:  3030 312d 3134 2e73 7475 6263 6f72 702e  xxxxx.xxxxxxxx.
	0x0110:  636f 6d5c 222c 5c22 7265 6765 7870 5c22  xxxx\",\"regexp\"
	0x0120:  3a5c 2263 6f6e 636f 7572 7365 2d61 6972  :\"xxxxxxxxxxxxx
	0x0130:  6c6f 636b 2e75 736e 312e 6e70 7374 7562  xxxxxxxxxxxxxxxx
	0x0140:  7379 732e 696f 2f28 2e2a 292e 7467 7a5c  sys.io/(.*).tgz\
	0x0150:  222c 5c22 7365 6372 6574 5f61 6363 6573  ",\"secret_acces
	0x0160:  735f 6b65 795c 223a 5c22 3943 3045 3030  s_key\":\"XXXXXX
	0x0170:  3030 342b 3662 6438 4341 3243 3241 4444  XXXXXXXXXXXXXXXX
	0x0180:  3837 3466 3665 3838 464e 4d4b 4947 424b  XXXXXXXXXXXXXXXX
	0x0190:  4c43 5045 4d45 4a46 5c22 7d2c 5c22 7665  XXXXXXXX\"},\"ve
	0x01a0:  7273 696f 6e5c 223a 7b5c 2270 6174 685c  rsion\":{\"path\
	0x01b0:  223a 5c22 636f 6e63 6f75 7273 652d 6169  ":\"xxxxxxxxxxxx
	0x01c0:  726c 6f63 6b2e 7573 6e31 2e6e 7073 7475  xxxxxxxxxxxxxxxx
	0x01d0:  6273 7973 2e69 6f2f 636f 6e63 6f75 7273  xxxxxxx/concours
	0x01e0:  652d 6174 632d 6462 2d64 756d 702d 3230  e-atc-db-dump-20
	0x01f0:  3138 3037 3234 2e74 677a 5c22 7d7d 227d  180724.tgz\"}}"}
	0x0200:  0a                           
```
As you can see, there are secrets (parameters sent to concourse task) exposed in plaintext which I have x'd out.

Here is the BOSH manifest:
```
---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: postgres
    properties:
      databases:
        databases:
        - name: atc
        port: 5432
        roles:
        - name: atc
          password: "((/bosh/concourse/atc-db-password))"
    release: postgres
  name: db
  networks:
  - name: default
  persistent_disk_type: large
  stemcell: default
  vm_type: large
- azs:
  - z1
  instances: 2
  jobs:
  - name: atc
    properties:
      basic_auth_password: "((atc_basic_auth.password))"
      basic_auth_username: "((atc_basic_auth.username))"
      credhub:
        client_id: concourse_credhub_id
        client_secret: "((client_secret))"
        tls:
          ca_cert:
            certificate: "((xxxx.certificate))"
          insecure_skip_verify: false
        url: https://xxxxxxx:8844
      encryption_key: "((encryption-key))"
      external_url: https://xxxxxxxxx:443
      postgresql:
        database: atc
        host: xxxxxxxxxx
        role:
          name: atc
          password: "((atc-db-password))"
        sslmode: disable
      tls_bind_port: 443
      tls_cert: "((xxxxxxx.certificate))"
      tls_key: "((xxxxxxxx.private_key))"
      token_signing_key: "((token_signing_key))"
    release: concourse
  - name: tsa
    properties:
      authorized_keys:
      - "((worker_key.public_key))"
      host_key: "((tsa_host_key))"
      token_signing_key: "((token_signing_key))"
    release: concourse
  name: web
  networks:
  - name: default
  stemcell: default
  vm_type: large
- azs:
  - z1
  instances: 2
  jobs:
  - consumes:
      baggageclaim:
        from: worker-baggageclaim
    name: worker
    properties:
      drain_timeout: 10m
      tsa:
        worker_key: "((worker_key))"
    release: concourse
  - name: baggageclaim
    properties:
      log_level: debug
    provides:
      baggageclaim:
        as: worker-baggageclaim
    release: concourse
  - name: garden
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
    release: garden-runc
  name: worker
  name: worker
  networks:
  - name: default
  stemcell: default
  vm_type: large
name: concourse
releases:
- name: concourse
  version: 3.13.0
- name: garden-runc
  version: 1.15.1
- name: postgres
  version: '28'
stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3586.26'
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 1
  serial: true
  update_watch_time: 10000-1200000
```
