### ISSUE TITLE
could not fetch pivnet-stemcell resource

### ISSUE THREAD

**Issue by mandyozhao** [concourse/concourse#246]
we have a pivnet-stemcell resource, recently it returns error "failed to fetch resource" on our pipeline, and when we click on job that depend on this resource, it will return a total blank page, message from JS console "Failed to load resource: the server responded with a status of 500 (Internal Server Error)", we are using version 70 
```
- name: ***
     type: pivnet-stemcell
     source:
     api_url: "https://network.pivotal.io"

```
