### ISSUE TITLE
BOSH DNS should be reachable by workers

### ISSUE THREAD

**Issue by sharms** [concourse/concourse#2482]
# Feature Request
As a user of CloudFoundry and BOSH, our systems are configured to use BOSH DNS.  This DNS cannot currently be resolved by default with Concourse workers without adding `iptables` rules by various out-of-band and hard to maintain methods.

## What challenge are you facing?

By default Concourse should allow containers to reach `169.254.0.2` to conform with the default BOSH configuration

## A Modest Proposal

Add iptables rules by default which allow workers to contact BOSH DNS

**Comment by MattSurabian** [comment]
After rolling out `bosh-dns` we saw our pipeline run times skyrocket which led us here. Now we know that workers trying to fetch resources hang until a timeout for `169.254.0.2` forces them to the next resolver in `/etc/resolv.conf`. 

Hoping this wouldn't be an issue re: worker principles; my understanding is that `bosh-dns` will soon be the default which would make this a bit more pressing. I only wish I had a decent suggestion on how to make a generic-ish configuration property to account for cases like this where "external" or otherwise sequestered resources need to be reachable from the worker's containers.

**Comment by tlwr** [comment]
While upgrading cf-deployment from pre-v3.0.0 to v3.6.0 we followed the CF guidance to move bosh-dns from cf-deployment to our global bosh runtime-config.

### Behaviour

We observed the same issues:
- able to do DNS resolution using bosh-dns on the host
- able to do DNS resolution using VPC cidr inside containers
- not able to do DNS resolution using bosh-dns inside the containers

---

### Verification

Ruby to illustrate (run via `fly hijack`):
```
require 'resolv'
require 'benchmark'

[{
  name: 'backup',
  resolver: Resolv.new([Resolv::DNS.new(nameserver:'10.0.0.2')]),
},{
  name: 'default',
  resolver: Resolv::DefaultResolver,
},{
  name: 'bosh',
  resolver: Resolv.new([Resolv::DNS.new(nameserver:'169.254.0.2')]),
}]
.map { |r| r.values_at(:name, :resolver) }
.map do |name, resolver|
  print "resolver #{name.ljust(10, ' ')} => "
  print (Benchmark.realtime do
    resolver.getaddress 'login.jonm-dep.dev.cloudapps.digital'
  end)
  puts ' seconds'
end
```
```
resolver backup     => 0.005594876998657128 seconds
resolver default    => 5.004335433997767 seconds
resolver bosh       => Traceback (most recent call last): ...
```

i.e. the DNS resolver would try bosh-dns, timeout after 5s, then use the VPC DNS, this caused many jobs in our concourse pipelines to tcp dial timeout.

---

### Workaround

We have our own concourse manifest and we manually overrode the default `dns_servers` value to point to our VPC DNS:
```
instance_groups:
  - name: concourse
    instances: 1
    jobs:
      - name: garden
        release: garden-runc
        properties:
          garden:
            # Override concourse containers to use VPC DNS instead of bosh-dns
            # See https://github.com/concourse/concourse/issues/2482 for details
            dns_servers:
              - 10.0.0.2
```

### Collaborators
- @richardtowers
- @jpluscplusm
