### ISSUE TITLE
4.0.0 (this is crazy) darwin concourse worker 'failed to create volume' when passing output to input

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#2495]
# Bug Report

This was extremely burdensome to track down, but I found a consistent repro!!

When passing an output from one darwin task to the input of a following darwin task, the task fails with "failed to create volume" if the task input contains symlinks to system paths.

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Docker (Web, Linux Worker, DB) Binary (Darwin)
* Infrastructure/IaaS: Local System (Mac High Sierra)
* Browser (if applicable): N\A
* Did this used to work? Unknown

I consistently started reproing this was when I was extracting the contents of a release of Homebrew and then trying to export that as an 'output' and then bring it into the following darwin task as an 'input.

The task (which used the output from the previous task) always failed with 'failed to create volume'. By systematically removing each file path from the contents of the input, I was able to identify the files which were causing concourse to fail.

Note that these are the only potentially related errors generated during the build in the logs and I see nothing that indicates the root cause of failure (this is from the darwin worker, nothing useful found in the linux worker logs)

```
{"timestamp":"1534359087.849576473","source":"baggageclaim","message":"baggageclaim.repository.create-volume.failed-to-materialize-strategy","log_level":2,"data":{"error":"exit status 1","handle":"408c5bc1-b605-4a89-5caf-1a5ab733329a","session":"1.1663"}}
{"timestamp":"1534359087.849710703","source":"baggageclaim","message":"baggageclaim.api.volume-server.create-volume-async.failed-to-create","log_level":2,"data":{"error":"exit status 1","handle":"408c5bc1-b605-4a89-5caf-1a5ab733329a","privileged":false,"session":"2.1.882","strategy":{"type":"cow","volume":"55bdfb5a-1829-482d-6217-0d3de37dd04c"},"ttl":0}}
```

Anyway, here's how to repro:

pipeline.yaml

```
resources:
- name: homebrew
  type: github-release
  check_every: 12h
  source:
    owner: Homebrew
    repository: brew

jobs:
- name: test-homebrew-export
  plan:
  - get: homebrew
    params:
      include_source_tarball: true
  - task: test-homebrew-install
    config:
      platform: darwin
      inputs:
      - name: homebrew
      outputs:
      - name: homebrew-install
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          root_location="$(pwd)"
          cd homebrew
          homebrew_location="$(pwd)"
          cd "${root_location}"
          cd homebrew-install
          tar -zxf "${homebrew_location}"/*.tar.gz
  - task: check-homebrew-install
    config:
      platform: darwin
      inputs:
      - name: homebrew-install
      run:
        path: bash
        args:
        - -c
        - |
          cd homebrew-install
          ls
```

Now, for the 'root cause' (or at least the suspect)...

There's a path inside the archive:

```
homebrew-install/Homebrew-brew-d6a245c/Library/Homebrew/os/mac/pkgconfig/fuse
```

Inside this path it contains two symlinks to system paths:

```
/opt/concourse/local/worker/volumes/live/cc577f0e-8366-4204-42a2-9c7f2c857e15/volume/homebrew-install/Homebrew-brew-d6a245c/Library/Homebrew/os/mac/pkgconfig/fuse
total 0
drwxrwxr-x   4 root  wheel  128 Jul 23 11:46 .
drwxrwxr-x  14 root  wheel  448 Jul 23 11:46 ..
lrwxrwxrwx   1 root  wheel   32 Jul 23 11:46 fuse.pc -> /usr/local/lib/pkgconfig/fuse.pc
lrwxrwxrwx   1 root  wheel   35 Jul 23 11:46 osxfuse.pc -> /usr/local/lib/pkgconfig/osxfuse.pc
```

For whatever reason, these files cause the homebrew task to fail when using this 'output' as an 'input'. If I remove these files, then the task works.

Here's the 'working' pipeline, with a single change (removing that folder):

```
resources:
- name: homebrew
  type: github-release
  check_every: 12h
  source:
    owner: Homebrew
    repository: brew

jobs:
- name: test-homebrew-export
  plan:
  - get: homebrew
    params:
      include_source_tarball: true
  - task: test-homebrew-install
    config:
      platform: darwin
      inputs:
      - name: homebrew
      outputs:
      - name: homebrew-install
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          root_location="$(pwd)"
          cd homebrew
          homebrew_location="$(pwd)"
          cd "${root_location}"
          cd homebrew-install
          tar -zxf "${homebrew_location}"/*.tar.gz
          cd Homebrew-brew-d6a245c
          cd ./Library/Homebrew/os/mac/pkgconfig
          rm -rf ./fuse
  - task: check-homebrew-install
    config:
      platform: darwin
      inputs:
      - name: homebrew-install
      run:
        path: bash
        args:
        - -c
        - |
          cd homebrew-install
          ls
```

In addition, this problem is ONLY exhibited when going from `darwin` to `darwin` (and maybe only on the same machine? I can't test that) If we go from a darwin task to a linux task, it works fine:

```
resources:
- name: homebrew
  type: github-release
  check_every: 12h
  source:
    owner: Homebrew
    repository: brew

jobs:
- name: test-homebrew-export
  plan:
  - get: homebrew
    params:
      include_source_tarball: true
  - task: test-homebrew-install
    config:
      platform: darwin
      inputs:
      - name: homebrew
      outputs:
      - name: homebrew-install
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          root_location="$(pwd)"
          cd homebrew
          homebrew_location="$(pwd)"
          cd "${root_location}"
          cd homebrew-install
          tar -zxf "${homebrew_location}"/*.tar.gz
  - task: check-homebrew-install
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: 18.04
      inputs:
      - name: homebrew-install
      run:
        path: bash
        args:
        - -c
        - |
          cd homebrew-install
          ls
```

As it stands, this breaks the ability for me to use the input-to-output process for this use case.

(Edit: `set -u` to `set -e`)
