### ISSUE TITLE
Allow define new resource types from docker images in the pipeline manifest

### ISSUE THREAD

**Issue by keymon** [concourse/concourse#250]
To add new custom resource types, currently it is necessary to redeploy the job `groundcrew` to change the property [`groundcrew.additional_resource_types`](https://github.com/concourse/concourse/blob/master/jobs/groundcrew/spec#L112)

For the tasks, instead, [any new image can be defined in the manifest itself](https://concourse.ci/running-tasks.html) with the key `image: ...`, so this should not be a difference in terms of security or permissions.

What I propose allow the pipeline definition to specify the docker image for resource directly, without requiring redeploy groundcrew job with bosh in concourse. 

This would allow seamless use custom resources in any concourse installation, even in the vanilla concourse-lite, and make the pipelines more portable, as they don't have a dependency on the installed resources but can specify their own resources.

A pair of possible pipeline syntax can be:

* Per resource definition, adding an image:
    ```
  - name: something
    type: my-semver
    image: docker://keymon/semver
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      key: build-all-trigger
```

* Special paragraph for defining resource types:
    ```
resource_types:
  - name: my-semver
    image: docker://keymon/semver
resources:
  - name: something
    type: my-semver
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      key: build-all-trigger
```

**Comment by vito** [comment]
Yep this makes sense; we've been discussing ways of versioning resources themselves, and it may end up being something like this. With the caveat that the resource will also have to say which platform it runs on (i.e. linux/darwin/etc.).

**Comment by vito** [comment]
Building on #252, I think this'll look something like:

```yaml
resource_types:
- type: bosh-init-deployment
  image:
    type: docker-image
    source:
      repository: somethirdparty/bosh-init-deployment-resource

resources:
- name: bosh-director-deployment
  type: bosh-init-deployment
  source: # ...
```
