### ISSUE TITLE
Outputs are unavailable after a timeout on a task

### ISSUE THREAD

**Issue by saliceti** [concourse/concourse#251]
After a task fails, `ensure` or `on_failure` are triggered. We are normally able to read the files generated in the failed task and do something useful with it.

But in the case of a timeout, these files are not available. This example shows this:

```
    - task: write_date
      config:
        run:
          path: sh
          args:
          - -c
          - |
            date | tee date.txt
            sleep 20
      timeout: 10s
      ensure:
        put: recorded_date
        params:
          from: write_date/date.txt
```
It errors with: `error running command: no matches found for pattern: write_date/date.txt`

When hijacking the `put` task:
```
/tmp/build/put # ls -l
total 0
```
