### ISSUE TITLE
Proposal: task images should be specified as resources

### ISSUE THREAD

**Issue by vito** [concourse/concourse#252]
The goal of this proposal is to solve the following problems:

1. Implement more explicit caching semantics, not subject to Garden Linux's image caching, which should fix the issue of running out of disk as images are fetched over time.
2. Support images that live in private registries or require credentials, without having to reconfigure the workers to support insecure registries.
3. Fix a sort of hole in the abstraction wherein task images are not versioned yet have a clear impact on the task's result.
4. Support arbitrary container image mediums (Docker, ACI downloads, etc.) via the resource interface.
5. Support building-and-then-using Docker images in a pipeline flow, which is a pattern people already do for e.g. baking in dependencies at the start of a pipeline so that later stages don't have to fetch them.
6. Support remembering the exact version of the image used for the steps in the build, making it entirely reproducible once we implement build re-triggering.

Concrete proposal:

1. Change `image` in tasks to refer to a resource description, rather than a URI string. (The old URI string would be still supported for a period of time, for backwards-compatibility.)
2. Allow pipeline configs to override `image` by pointing to their own resource.

The intent of 1) is to keep task config files self-contained, so that `fly execute` and such still work.

The intent of 2) is to support configuring resources with credentials in a pipeline, so that credentials don't have to be hardcoded into a task config.

I'm not wild about 2) as it introduces the possibility of the pipeline config specifying an entirely different image than is specified in the task config. It also doesn't cover running `fly execute` with credentials.

Anyway, assuming those two changes, task configs would look something like:

**`atc-go.yml` (using public image)**

```yaml
---
platform: linux

image:
  type: docker-image
  source: {repository: concourse/atc-ci}

inputs:
- name: concourse

run:
  path: concourse/ci/scripts/atc-go
```

Here's an example of overriding it with a private image in a pipeline:

```yaml
resources:
- name: my-repo
  type: git
  source: # not interesting ...

- name: my-secret-image
  type: docker-image
  source:
    repository: user/repo
    username: secret-user
    password: secret-password

jobs:
- name: some-job
  plan:
  - get: my-repo
  - task: task-using-secret-image
    file: my-repo/atc-go.yml
    image: my-secret-image
```

Another option instead of 2) would be to introduce some sort of templating, but that'd take some thinking since right now all templating is done client-side (and I quite like it that way).

Issues this is relevant to:

* https://github.com/concourse/concourse/issues/157
* https://github.com/concourse/atc/issues/30
* https://github.com/concourse/concourse/issues/27
