### ISSUE TITLE
Cannot perform rolling bosh deployment (problem with drain)

### ISSUE THREAD

**Issue by cloudyday** [concourse/concourse#2523]
# Bug Report

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: doesn't matter
* Browser (if applicable): not applicable
* Did this used to work? yes. in 3.9.2

## Short description
We've recently updated from 3.9.2 to 3.14.1 and encountered the issue that we cannot perform a rolling bosh deployment anymore due to the drain scripts of the workers stalling and finally timing out.
**We generate new atc, tsa and worker keys before every deployment.**

## Setup
**Our setup (also order in deployment.yml):**
1 web (instance group A)
3 worker (instance group B)

**update settings**
```
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-60000
```

## Problem
What happens during deployment:
1. 1 worker and the web get updated in parallel --> both succeed
2. next worker deployment times out

On the worker you can observe that **the drain script is still running**.

In the log files 
- `/var/vcap/sys/log/worker/drain.stdout.log`
- `/var/vcap/sys/log/worker/beacon.stdout.log` 

you get following error
```
{"timestamp":"1535034986.909739017","source":"worker","message":"worker.drain.failed-to-land-worker","log_level":2,"data":{"error":"failed to construct client connection: ssh: handshake failed: remote host public key mismatch","session":"1"}}
```

Running `monit stop all` solves the problem and the drain script finishes

## Workaround
When we set...
```
update:
  canaries: 0
  canary_watch_time: 1000-30000
  max_in_flight: 3
  serial: false
  update_watch_time: 5000-60000
```

...all VMs get updated in parallel. And the update succeeds. But this cannot be the solution. 

## Looking at the error message from the log...
...something with the key rotation and how the drain script handles this situation seems to be wrong.
**We generate new atc, tsa and worker keys before every deployment.**
In version 3.9.2 this was no issue.
