### ISSUE TITLE
[ BUG ] Pipeline circular dependency passes `fly sp` validations.

### ISSUE THREAD

**Issue by Typositoire** [concourse/concourse#2559]
# Bug Report

So basically if you do this

```yaml
- name: build
  plan:
    - get: sources
      trigger: true
    - get: jvm-8-docker
      passed: [build]
```

The UI just hang your browser forever if it tries to load that pipeline which makes sense, you can't graphically represent that. But it shouldn't be able to pass `sp` validation. Validation should check whether or not it has a circular dependency.

The following can also be handy:

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: AWS/Kubernetes/Kops
* Browser (if applicable): Chrome/Firefox
* Did this used to work? NO idea I hope not!

**Comment by jama-pivotal** [comment]
Ah, the good old circular pipeline. Thanks for reporting the issue. Unfortunately closing as a duplicate of #1710 and #2174

**Comment by Typositoire** [comment]
Actually it's not, this pipeline is self-referencing. Was that also fixed?

**Comment by cirocosta** [comment]
Hey @Typositoire , yeah, 5.1 should be fine:

```yaml
resources:
  - type: git
    name: repository
    source: { uri: 'https://github.com/cirocosta/chicken-gun' }


jobs:
  - name: test
    public: true
    plan:
      - get: repository
        passed: [ 'test' ]
```

<img width="805" alt="Screen Shot 2019-04-26 at 3 10 26 PM" src="https://user-images.githubusercontent.com/3574444/56830825-752dc500-6835-11e9-8e48-e6acf720cbb2.png">
