### ISSUE TITLE
Add support to pin or specify resource versions

### ISSUE THREAD

**Issue by keymon** [concourse/concourse#256]
This issue is to continue [the discussion initiated in slack](https://concourseci.slack.com/archives/general/p1452699345008416)

## What

I would like to suggest that one can "pin" the version of the resource to be consumed in the manifest or when triggered the job.

This way we can keep defining dependencies as resources in concourse but force the jobs to always use the same specific version. 

## Example of pinning version in the manifest

For example, a user wants to be being able to use the resources `bosh-io-stemcell`, `bosh-io-release` together with bosh-release. He wants to keep using always the same version of the release and stemcell, regardless a new one is released.

The definition in the pipeline can be like this:

```
  - name: deploy
    serial: true
    plan:
      - aggregate:
        - get: cf-stemcell
          version: {{ stemcell_version }}
        - task: cf-release
          version: 215
        - get: cf-manifest
          passed: ['generate-manifest']
          trigger: true
      - put: cf-deployment
        params:
          manifest: cf-manifest/cf-manifest.yml
          stemcells: 
            - cf-stemcell/stemcell.tgz
          releases:
            - cf-release/release.tgz
``` 

## Example of triggering a job with a specific version

Here the idea is implement the interface and API controllers required to start a new execution of a job but specifying a valid upstream version of the resources consumed.

This would allow to create custom builds based on specific versions of dependent resources picked adhoc, but without having to re-upload the pipeline to pin some specific versions (providing the pin feature exists ;)) 

GoCD supports this feature and is explained here: https://www.go.cd/documentation/user/current/advanced_usage/trigger_with_options.html

## Use cases

 * Pin versions of dependencies

**Comment by ScarletTanager** [comment]
+1 - this would be IMHO a really valuable feature - our team could use it right now, were it available.

**Comment by tylerschultz** [comment]
+1 - sounds delightful!

**Comment by medvedzver** [comment]
+1. Would use!

**Comment by rnandi** [comment]
+ 1 - this feature would make me fly!

**Comment by vito** [comment]
Scheduled this, but we're going to do #382 first.

I think the user-specified version should still come from the set of collected versions and still satisfy `passed` constraints, etc. - otherwise we're blindly passing potentially bogus info along to `in`.

Given that one of the use cases of this is to force using an older version of a resource, without #382 that won't be possible (for newly configured resources), so we'll tackle that first.

So, with:

```yaml
get: some-repo
version: {ref: "abcdef"}
passed: [some-job]
```

...this would just change the input resolution to force that input to the job to be that version, and potentially fail to resolve inputs if the version is not present on the `some-repo` resource, or if that version is present but does not satisfy the `passed` constraints present on the `get` step.
