### ISSUE TITLE
Allow a pipeline config to pass params to a task which are not defined in the task.yml

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#2560]
In Concourse v5.0 there is a breaking change planned where Concourse will raise an error if the pipeline config attempts to pass a param (environment variable) to a task if the task.yml does not explicitly define that param. This behavior is allowed in the current version of Concourse, but this causes some UX issues as Concourse is unable to verify typos in pipeline params and the current plan is to add validation on undeclared params in v5.0: #2510.

However, we currently have a use case for relying on specifying params in the pipeline that are not defined in the `task.yml`. We're creating a re-usable set of tasks that will be used across many pipelines. We want the authors of those pipelines to be able to specify env vars with a given prefix, e.g. `BOSH_some_variable`, and the `task.sh` will consume all env vars starting with that prefix similar to `bosh --vars-env BOSH interpolate some-template.yml`. So we have a shared task authored by one team with the pipeline env vars and the config template being authored by other teams. Would y'all consider somehow supporting this use case going forward?

As an initial proposal, the `task.yml` could opt into allowing undeclared params to be passed through to the task script:

```yaml
---
platform: linux

params: {}
allow_undeclared_params: true # <-------- add this key to opt back into old behavior

image_resource:
...
```

**Comment by ljfranklin** [comment]
> allow params matching specific patterns (e.g. BOSH_*)

That would work for our use case, but I worry we're hitting diminishing returns in terms of validation at that point. It would catch a typo like `BSH_` but there might be other use cases where you do want to allow any params to be forwarded through regardless of prefix.

**Comment by eedwards-sk** [comment]
I'm running into this same issue, as I'm working on some task files that need better parameterization (something that is sorely lacking with tasks, yet much better with resources... hmmm...)

I'm trying to do something similar, where I pass multiple values similar to how terraform does it with `TF_VAR_<variable>`, I'll be doing `BACKEND_CONFIG_<var>=<value>` so that I can turn it into a series of arguments `-backend-config=<var>=<value>`

Because the names of these params cannot be known in advance, and because there's no easy or good way to pass an array of values in through params, this change would negatively impact my workflow.

**Comment by ogradyjd** [comment]
This is a non-started for my group as well.  We are creating a list of parameters in our pipeline config of which sub-sets are used by different tasks.  You are basically adding cruft if you are going to force every task to define all of those parameters now under threat of erroring out.   That means tasks developed by other teams would be forced to needlessly define those parameters with no real benefit.

I understand the drive for this feature, but I would second the suggestion above for the `allow_undeclared_params` switch with one addendum.  With the switch not present (false), instead of throwing an error, isn't there a way you can just not pass in parameters that are not defined in the task.yml?  That would give you the validation and control you want, where you want it, while allowing the current flexibility where it's needed in an "opt-in" fashion so devs can't complain if task script environmental variable values are overwritten by the pipeline config.

**Comment by eedwards-sk** [comment]
hey @vito thanks for the response

For my use case, it's currently highly related to the [concourse-terraform](https://github.com/Snapkitchen/concourse-terraform) project I made.

I use tasks for the various lifecycle types (plan/apply/etc) and concourse resources to pass plan file archives around.

Here's an [example](https://github.com/Snapkitchen/concourse-terraform/blob/master/examples/s3-plan-approve-apply.yaml) of a pipeline leveraging the tasks.

However, here's an example (real world, from my actual consuming project) of the yaml templates in a pipeline that I use for the task params.

Note the number of varying variables, all using the same underlying tasks.

```yaml
- name: terraform
  aws_credentials_params: &tf-aws-credentials-params
    AWS_ACCESS_KEY_ID: ((aws_access_key_id))
    AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
    AWS_DEFAULT_REGION: *aws_region
  common_backend_params: &tf-common-backend-params
    TF_BACKEND_TYPE: s3
    TF_BACKEND_CONFIG_access_key: ((aws_access_key_id))
    TF_BACKEND_CONFIG_secret_key: ((aws_secret_access_key))
    TF_BACKEND_CONFIG_bucket: *aws_bucket_name
    TF_BACKEND_CONFIG_region: *aws_region
    TF_BACKEND_CONFIG_encrypt: true
    TF_BACKEND_CONFIG_acl: bucket-owner-full-control
  consul_cluster_plan_params: &tf-consul-cluster-plan-params
    TF_WORKING_DIR: terraform-source-dir/terraform/consul/cluster
    TF_BACKEND_CONFIG_key: *consul_cluster_backend_config_key
    TF_VAR_aws_bucket_name: *aws_bucket_name
    TF_VAR_aws_region: *aws_region
    TF_VAR_ami_id: ((consul_cluster_ami_id))
    TF_VAR_vpc_id: *consul_cluster_vpc_id
    TF_VAR_subnet_ids: *consul_cluster_subnet_ids
    TF_VAR_datadog_api_key: ((datadog_api_key))
    TF_VAR_environment_name: ((environment_name))
    TF_VAR_environment_type: *environment_type
    TF_VAR_gossip_encryption_key: ((consul_gossip_encryption_key))
  consul_monitors_plan_params: &tf-consul-monitors-plan-params
    TF_WORKING_DIR: terraform-source-dir/terraform/consul/monitors
    TF_BACKEND_CONFIG_key: *consul_monitors_backend_config_key
    TF_VAR_cluster_backend_bucket: *aws_bucket_name
    TF_VAR_cluster_backend_key: *consul_cluster_backend_config_key
    TF_VAR_cluster_backend_region: *aws_region
    TF_VAR_datadog_api_key: ((datadog_api_key))
    TF_VAR_datadog_app_key: ((datadog_app_key))
    TF_VAR_datadog_alert_targets: ((datadog_alert_targets))
    TF_VAR_datadog_critical_alert_targets: ((datadog_critical_alert_targets))
    TF_VAR_pagerduty_token: ((pagerduty_token))
  vault_storage_plan_params: &tf-vault-storage-plan-params
    TF_WORKING_DIR: terraform-source-dir/terraform/vault/storage
    TF_BACKEND_CONFIG_key: *vault_storage_backend_config_key
    TF_VAR_aws_region: *aws_region
    TF_VAR_environment_name: ((environment_name))
    TF_VAR_environment_type: *environment_type
  vault_cluster_plan_params: &tf-vault-cluster-plan-params
    TF_WORKING_DIR: terraform-source-dir/terraform/vault/cluster
    TF_BACKEND_CONFIG_key: *vault_cluster_backend_config_key
    TF_VAR_ami_id: ((vault_cluster_ami_id))
    TF_VAR_aws_bucket_name: *aws_bucket_name
    TF_VAR_aws_region: *aws_region
    TF_VAR_environment_name: ((environment_name))
    TF_VAR_environment_type: *environment_type
    TF_VAR_datadog_api_key: ((datadog_api_key))
    TF_VAR_kms_key_name: *vault_cluster_key_alias_name
    TF_VAR_storage_backend_bucket: *aws_bucket_name
    TF_VAR_storage_backend_key: *vault_storage_backend_config_key
    TF_VAR_storage_backend_region: *aws_region
    TF_VAR_subnet_ids: *vault_cluster_subnet_ids
    TF_VAR_vpc_id: *vault_cluster_vpc_id
  vault_monitors_plan_params: &tf-vault-monitors-plan-params
    TF_WORKING_DIR: terraform-source-dir/terraform/vault/monitors
    TF_BACKEND_CONFIG_key: *vault_monitors_backend_config_key
    TF_VAR_cluster_backend_bucket: *aws_bucket_name
    TF_VAR_cluster_backend_key: *vault_cluster_backend_config_key
    TF_VAR_cluster_backend_region: *aws_region
    TF_VAR_datadog_api_key: ((datadog_api_key))
    TF_VAR_datadog_app_key: ((datadog_app_key))
    TF_VAR_datadog_alert_targets: ((datadog_alert_targets))
    TF_VAR_datadog_critical_alert_targets: ((datadog_critical_alert_targets))
    TF_VAR_pagerduty_token: ((pagerduty_token))
```

these get merged into the task jobs e.g.:

```yaml
# plan-consul-cluster
# ===================
- name: plan-consul-cluster
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: source
    - get: concourse-terraform
    - get: concourse-terraform-image
  - task: plan
    image: concourse-terraform-image
    file: concourse-terraform/tasks/plan.yaml
    input_mapping:
      terraform-source-dir: source
    params:
      <<: *tf-aws-credentials-params
      <<: *tf-common-backend-params
      <<: *tf-consul-cluster-plan-params
      ERROR_ON_NO_CHANGES: false
```
