### ISSUE TITLE
Fail to install concourse's worker on k8s

### ISSUE THREAD

**Issue by zeusro** [concourse/concourse#2561]
# Feature Request

## What challenge are you facing?

Well,installing concourse's worker on swarm is easy.Just like 

```yaml
concourse-worker:
  image: concourse/concourse:4.0.0
  privileged: true
  command: worker --work-dir /opt/concourse/worker
  volumes:
    - /root/docker/concourse/keys/worker:/concourse-keys
    - /root/docker/concourse/worker:/opt/concourse/worker
  environment:
    - 'CONCOURSE_TSA_HOST=concourse-web:2222'
    - 'CONCOURSE_GARDEN_DNS_SERVER=114.114.114.114'
```
But the problem is,`  privileged: true` in k8s will be an issue.

I have been tried creating a StatefulSet to replace (as following,but I remove the volume part).
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:    
    security.alpha.kubernetes.io/unsafe-sysctls: net.core.somaxconn=65535
  labels:
    app: concourse-worker
  name: concourse-worker
  namespace: 17zwd
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: concourse-worker
  serviceName: concourse-worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: concourse-worker
      name: concourse-worker
    spec:
      containers:
      - args:
        - worker
        - --work-dir
        - /worker
        command:
        - concourse
        env:
        - name: CONCOURSE_TSA_HOST
          value: concourse-web:2222
        - name: CONCOURSE_GARDEN_DNS_SERVER
          value: 114.114.114.114
        image: concourse/concourse:4.0.0
        imagePullPolicy: Always
        name: concourse-worker
        resources:
          requests:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
          name: worker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
```

I have allready added the `securityContext` part ,but seems not worked. Affter it starts,I can see
erros on the logs.Just like

```
{"timestamp":"1536207712.483908176","source":"worker","message":"worker.beacon.beacon.beacon-client.failed-to-connect-to-tsa","log_level":2,"data":{"error":"dial tcp 172.30.1.177:2222: i/o timeout","session":"4.1.1"}}
Exit trace for group:
garden exited with error: Exit trace for group:
garden-runc exited with error: bulk starter: mounting subsystem 'cpuset' in '/sys/fs/cgroup/cpuset': operation not permitted
dns-proxy exited with nil
 sweeper exited with nil
baggageclaim exited with nil
beacon exited with error: failed to connect to TSA
```

I checked out the document but found nothing help.

Sincerely,I need your help.Help me,please.

**Comment by Typositoire** [comment]
It might be a bit hard to read but you can probably help yourself with this: https://github.com/helm/charts/blob/master/stable/concourse/templates/worker-statefulset.yaml

If you want to use helm to install concourse it works SUPER well also.

**Comment by zeusro** [comment]
@Typositoire  Oh,thanks a lot .I created a new StatefulSet to replace the old one,and it worked!

But there is a new problem,I create a pipeline jiust like ever before,but is doesn't work !

It seems like the pipeline was waiting something .

![image](https://user-images.githubusercontent.com/5803609/45194485-db091480-b285-11e8-91c8-72c6e4e5ef49.png)

But when I see the logs,I could not see any helpful messages.That is weird...

**Comment by zeusro** [comment]
runc run: exit status 1: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused \"exit status 40\""

**Comment by rjain15** [comment]
I am not able to use the helm chart, I get errors on the workers, when I describe the worker pod

    kubectl describe pod concourse-worker-1

```
done' exited with 137: failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
failed to connect to TSA
, message: "failed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\nfailed to connect to TSA\n"
```

**Comment by cirocosta** [comment]
Hey @zeusro ,

Thanks for reporting the issue!

Have you been still facing the problem? 

@rjain15 , this looks more like a connectivity issue, which seems unrelated to the problem originally raised by @zeusr; if you're still facing such issue, would you mind opening one specifically at the `helm/charts` repo pls?

Thank you!

**Comment by encodeering** [comment]
for reference if someone runs into this as well

found this issue based on the `operation not permitted` message when installing concourse using helm. the cluster uses docker with systemd as cgroup driver and found this article to go back to [cgroup v1](https://sleeplessbeastie.eu/2021/09/10/how-to-enable-control-group-v2/) which solved my issue after a reboot.

please ensure that v1 is what you need from all the perspectives, but this change unblocked the worker pods.

```
kubectl -n concourse get pods
NAME                             READY   STATUS    RESTARTS         AGE
concourse-postgresql-0           1/1     Running   1 (7m38s ago)    51m
concourse-web-6b65f44555-22mgm   1/1     Running   1 (14m ago)      51m
concourse-worker-0               1/1     Running   13 (14m ago)     51m
concourse-worker-1               1/1     Running   14 (9m14s ago)   51m

```

```
helm show chart concourse/concourse
apiVersion: v2
appVersion: 7.6.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.16.2
description: Concourse is a simple and scalable CI system.
home: https://concourse-ci.org/
icon: https://avatars1.githubusercontent.com/u/7809479
keywords:
- ci
- concourse
- concourse.ci
maintainers:
- email: concourse@vmware.com
  name: concourse-team
name: concourse
sources:
- https://github.com/concourse/concourse-chart
- https://github.com/concourse/concourse
type: application
version: 16.1.20
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

```
