### ISSUE TITLE
Unable to update generic_oauth scopes via bosh config (since cached in db)

### ISSUE THREAD

**Issue by rkoster** [concourse/concourse#2562]
# Bug Report

Adding a oauth scope is not picked up via bosh manifest is not picked up untill config is removed from `connector` table and atc is restarted by hand.

While trying to configure generic oauth I found that I needed the `openid` scope to be able to login, since it is required for the userinfo endpoint.

```yaml
      generic_oauth:
        display_name: UAA
        client_id: concourse
        client_secret: ((uaa_concourse_client_secret))
        auth_url: https://((internal_ip)):8443/oauth/authorize
        token_url: https://((internal_ip)):8443/oauth/token
        userinfo_url: https://((internal_ip)):8443/userinfo
        ca_cert:
          certificate: ((uaa_ssl.ca))
        scopes: [ openid, concourse.main ]
```

I noticed however that only `concourse.main` was still showing up in the uaa access log. After a lot of debugging I found that the config was cached in the database and not updated. If this is the expected behaviour this should at least be documented somewhere.

* Concourse version: 4.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: vsphere
* Browser (if applicable): Chrome
