### ISSUE TITLE
Resources put in previous job not triggering consecutive jobs

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#2569]
# Bug Report

We have a pipeline with (simplified) two jobs, triggering like this:

git-branch-heads resource ----> [build] ----> swift resource -----> [acceptance tests]

I've stripped it down to this pipeline definition
```yaml
- name: "payment build [feature]"
  max_in_flight: 2
  plan:
  - aggregate:
    - get: repo
      resource: meshstack-feature
      version: every
      trigger: true
    - get: backend-ci-docker-image
  - aggregate:
    - task: build-payment
      file: repo/ci/payment/build.yml
  - aggregate:
    - put: swift-drop-payment
      params:
        from: drop-payment/payment-([.a-z0-9]+)\.tar\.gz
        delete_after: 172800

- name: "payment acceptance [feature]"
  max_in_flight: 2
  plan:
  - aggregate:
    - get: repo
      resource: meshstack-feature
      version: every
      trigger: false
      passed: ["payment build [feature]"]
    - get: drop-payment
      resource: swift-drop-payment
      passed: ["payment build [feature]"]
      trigger: true
    - get: backend-ci-docker-image
      passed: ["payment build [feature]"]
```

The build step executes a `put` step against the swift resource and produces a new version. The swift resource itself cannot `check` for new versions as we use git hashes derived from the repository to version our artifacts. However, since Concourse does an implicit `get` after the put the artifact in the swift-resource is known to Concourse and correctly shows up on the UI:

![image](https://user-images.githubusercontent.com/130103/45281788-31ba5c80-b4d9-11e8-976e-56d880fd844a.png)

However, the new resource version produced by the build job does not trigger the acceptance tests job. As recommended by @vito in https://discuss.concourse-ci.org/t/resource-shows-updated-but-next-trigger-job-not-run/102 I queried 
`https://your-ci.example.com/api/v1/teams/(team)/pipelines/(pipeline)/jobs/(job)/inputs` and indeed, concourse picks up entirely wrong (i.e. old) versions of inputs for the job, even though a newer set of versions would be available. 

```json
[
  {
    "name": "drop-payment",
    "resource": "swift-drop-payment",
    "type": "swift",
    "source": {
    },
    "version": {
      "path": "payment-f21a143200cf7edbe66a5b98b1a4acb402aac976.tar.gz"
    }
  },
  {
    "name": "backend-ci-docker-image",
    "resource": "backend-ci-docker-image",
    "type": "docker-image",
    "source": {
    },
    "version": {
      "digest": "sha256:ad9f037e165026f71f431b749f8dd6cf9fe68bee6ab0883ad19e5978d0989f7c"
    }
  },
  {
    "name": "repo",
    "resource": "meshstack-feature",
    "type": "git-branch-heads",
    "source": {
      "branches": [
        "feature/*"
      ]
    },
    "version": {
      "changed": "feature/incremental-subsystem-pipeline",
      "feature/incremental-subsystem-pipeline": "e740f637496d4b792134e863f8a824e477a5cd7b"
    }
  }
]
```

So while the job should detect the most-recent version of the swift resource `38eb996056cf1d1227932ae5d074489e3edecd93`, it detects the _first_ version of the resource `f21a143200cf7edbe66a5b98b1a4acb402aac976` instead. What I find very confusing is that we re-use the same swift-resource in another job combination (develop branch builds) using a different git-resource (plain git-resource, without `version: every`). For those builds, the triggering based on the new version generated by the `put` step in the `build [develop]` job appears to tirgger the `acceptance [develop]` job just fine. 

I've also had a read through the following related issues, but none of them exactly match the situation with our pipeline (which is also brand-new btw.). 

- https://github.com/concourse/concourse/issues/2270
- https://github.com/concourse/concourse/issues/1298
- https://github.com/concourse/concourse/issues/2347

The following can also be handy:

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: Meshcloud OpenStack
* Did this used to work? It used
