### ISSUE TITLE
All operations fail with error: forbidden

### ISSUE THREAD

**Issue by robin-rpr** [concourse/concourse#2578]
Hey there!

* Concourse version: {"version":"4.1.0","worker_version":"2.1"}
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: N/A
* Browser (if applicable): Chrome Stable 69.0.3497.81 (MacOS)
* Did this used to work? N/A

> **Note**: Confidential information has been replaced.

##### `.ci/pipline.yml`
```yaml
---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: node-gpu
    trigger: true
  - put: docker-image
    params:
      build: node-gpu/.ci/docker

resources:
- name: node-gpu
  type: git
  source:
    uri: https://github.com/node-gpu/node-gpu.git
    branch: dev

- name: docker-image
  type: docker-image
  source:
    email: ((docker_hub.email))
    username: ((docker_hub.username))
    password: ((docker_hub.password))
    repository: ((docker_hub.repository))
```

##### `.ci/config/default.yml`
```yaml
---
"docker_hub":
    "username": fooBar
    "email": fooBar@example.com
    "password": 1234
    "repository": fooBar/myRepository
```

##### `.ci/setup.sh`
```bash
fly login -t concourse -c https://concourse.example.com
# Outputs:
# logging in to team 'main'
#
# navigate to the following URL in your browser:
#
# https://concourse.example.com/sky/login?redirect_uri=http://127.0.0.1:50220/auth/callback
#
# or enter token manually:
# target saved

fly validate-pipeline --config .ci/pipeline.yml --load-vars-from .ci/config/default.yml
# Outputs: looks good

fly -t myTarget set-pipeline -p node-gpu -c .ci/pipeline.yml -l .ci/config/default.yml
# Outputs:
# resources:
#  resource node-gpu has been added:
# + name: node-gpu
# + type: git
# + source:
# +   branch: dev
# +   uri: https://github.com/node-gpu/node-gpu.git
#
#   resource docker-image has been added:
# + name: docker-image
# + type: docker-image
# + source:
# +   email: fooBar@example.com
# +   password: 1234
# +   repository: fooBar/myRepository
# +   username: fooBar
#
# jobs:
#   job build-docker-image has been added:
# + name: build-docker-image
# + public: true
# + serial: true
# + plan:
# + - get: node-gpu
# +   trigger: true
# + - put: docker-image
# +   params:
# +     build: node-gpu/.ci/docker
#
# apply configuration? [yN]: y
# error: forbidden
```

##### (Server) `docker-compose.yml`
```yaml
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=foobar
    - POSTGRES_PASSWORD=foobar
    - POSTGRES_USER=foobar
    - PGDATA=/database

  concourse-web:
    image: concourse/concourse
    command: quickstart
    links: [concourse-db]
    depends_on: [concourse-db]
    privileged: true
    ports: ["1234:1234"]
    environment:
    - CONCOURSE_POSTGRES_HOST=foobar-db
    - CONCOURSE_POSTGRES_USER=foobar
    - CONCOURSE_POSTGRES_PASSWORD=1234
    - CONCOURSE_POSTGRES_DATABASE=foobar
    - CONCOURSE_BIND_PORT=1234
    - CONCOURSE_EXTERNAL_URL=https://concourse.example.com
    - CONCOURSE_ADD_LOCAL_USER=foobar:1234
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_WORKER_GARDEN_NETWORK

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
```
Regards,
Robin Rpr.
