### ISSUE TITLE
Concourse 4.1.0 Authentication Fails for PingFederate

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#2583]
# Bug Report

We have configured our authentication through BOSH as:
```
        auth_url: https://our-pf.com/as/authorization.oauth2
        client_id: Client
        client_secret: hidden
        groups: groups
        scopes:
        - openid profile email
        token_url: https://our-pf.com/as/token.oauth2
        userinfo_url: https://our-pf.com/idp/userinfo.openid
```
atc_ctl notes the values correctly:
```
      --oauth-client-id Client \
      --oauth-client-secret hidden \
      --oauth-auth-url https://our-pf.com/as/authorization.oauth2 \
      --oauth-token-url https://our-pf.com/as/token.oauth2 \
      --oauth-userinfo-url https://our-pf.com/idp/userinfo.openid \
     --oauth-scope openid\ profile\ email \
       \
      --oauth-groups-key groups \
       \
```
The user endpoints can be seen at:  https://documentation.pingidentity.com/pingfederate/pf83/index.shtml#concept_openIdConnectMetadataEndpoint.html

And, when I browse to https://our-pf.com/idp/userinfo.openid, I do receive an HTTP 401 (unauthorized), so I assume it exists.

Log entry:
```
{"timestamp":"1536838807.155656338","source":"atc","message":"atc.sky.userinfo.failed-to-parse-authorization-header","log_level":1,"data":{"session":"4.3"}} 
{"timestamp":"1536838807.152057409","source":"atc","message":"atc.sky.userinfo.failed-to-parse-authorization-header","log_level":1,"data":{"session":"4.2"}}
    {"timestamp":"1536838810.296653986","source":"atc","message":"atc.dex.event","log_level":2,"data":{"fields":{},"message":"Failed to authenticate: OAuth Connector: failed to execute request to userinfo: Get : unsupported protocol scheme \"\"","session":"5"}}
```
![image](https://user-images.githubusercontent.com/10414523/45481678-0dae8380-b744-11e8-8153-4619fca039b1.png)

Bug reports are pretty free-form; just replace this with whatever. You can also help us triage the issue by including steps to reproduce, expected results, and the actual result. Help us help you!

These settings did work in 3.13 (barring the userurl)

* Concourse version: 4.1.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack
