### ISSUE TITLE
Question: Change the branch from external github raw file or anyother approach

### ISSUE THREAD

**Issue by Pasupathi-Rajamanickam** [concourse/concourse#2585]
## What challenge are you facing?
I would like to customize or change the branch from external github raw file or any other approach for changing branch.
Ex.
```
#-RESOURCE-
- name: myrepo
  type: git
  source:
    branch: https://raw.github.com/myrepo/staticbranch/currentBranch.txt
```
So I keep change my branch which I want to build out of, and I can update that branch in text file at `staticbranch`, this will allow me not to deploy my pipeline with new branch, whenever I want to build new build from different branches. 

## A Modest Proposal

`source.branch` could accept http/s URL for dynamic branches

The following can also be handy:

* Concourse version:  v4.1.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? New feature I guess.

**Comment by marco-m** [comment]
It seems your goal is to be able to have a pipeline not only for the master branch but also for feature branches. Concourse is developing the "Spaces" concept to enable this, see the epic  #1707. In the meantime, you can obtain what you want today (no changes to the Concourse git resource) by using `((params))`. The git resource could be something like

```
- name: myrepo
  type: git
  source:
    ....
    branch: ((branch))
```

and then you could set that pipeline with `fly --var=branch=mybranch`.

Note that this has the advantage that the pipeline build history represents always the same branch, while the approach you are proposing would have a mixed build history. Only aspect to be careful with the `((param))` approach is that you will need to clean up (destroy) the feature branch pipeline when done, otherwise they will build up and generate load with the concourse git resource. A way we use to reduce load is to increase the concourse git resource check interval to 5 min from the default 1 min.
