### ISSUE TITLE
Be able to easily determine which resource(s) `passed` constraints for a build have been or haven't been satisfied

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#2591]
# Feature Request

## What challenge are you facing?

Rather than jumping to a solution, describe the problem you're facing, and provide context. It helps us more to understand your problem first. This way we may be able to connect the dots between your issue and others and perhaps come up with a more general proposal, rather than tacking on feature after feature.

When a job has a many resources each with many `passed` constraints, trying to determine which resource doesn't have a version that satisfies the constraints is non-trivial, error-prone and tedious. 

For example, in the sample pipeline
```
- name: some-job
  serial: true
  plan:
  - aggregate:
    - get: some-resource-1
      resource: some-resource-1
      passed:
      - some-other-distinct-jobs-1
      - some-other-distinct-jobs-2
      - some-other-distinct-jobs-.
      - some-other-distinct-jobs-.
      - some-other-distinct-jobs-N

    - get: some-resource-2
      resource: some-resource-2
      passed:
      - some-other-distinct-v2-jobs-1
      - some-other-distinct-v2-jobs-2
      - some-other-distinct-v2-jobs-.
      - some-other-distinct-v2-jobs-.
      - some-other-distinct-v2-jobs-N

.
.
.
.
 
    - get: some-resource-N
      resource: some-resource-N
      passed:
      - some-other-distinct-vN-jobs-1
      - some-other-distinct-vN-jobs-2
      - some-other-distinct-vN-jobs-.
      - some-other-distinct-vN-jobs-.
      - some-other-distinct-vN-jobs-N

    - task: some-task
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: some-repo/image
        inputs:
        - name: some-resource-1
        - name: some-resource-2
.
.
.
        - name: some-resource-N
        run:
          path: SOME_TASK.sh
```

When a job is triggered, it will wait indefinitely until for each resource there is a version that satisfies the `passed` constraints.  So, if `some-resource-40` doesn't have a version that satisfies the `passed` constraints, concourse will correctly prevent the build from running.
It would be super useful to be able to bubble the information to the user so that they may be able to take action to address the problem. Trying to go through each resource's page to determine this seems error-prone.

## A Modest Proposal

During the `Preparing Build` -> `waiting for a suitable set of input versions` phase of a build, it would be great to see which resources have/have NOT satisfied the constraints. This would simplify the task of finding that one resource that is blocking everything.
