### ISSUE TITLE
Job failing with out any errors

### ISSUE THREAD

**Issue by thejaswis** [concourse/concourse#2609]
I am integration sonar runner with concourse pipeline. I am able to see analysis report but job fails with out any error.

Job config:

```
jobs:
- name: job-unit-test
  public: true
  serial: true
  plan:
  - get: service-repo-trigger
    trigger: true
  - get: service-repo
    trigger: false
  - get: ci-resources
  - task: unittests
    params:
      SERVICE_NAME: ((service-name))
    file: ci-resources/ci-tasks/sample_task_go_unit_test.yml
  - put: code-analysis
    params:
      project_path: sonar-path
      additional_properties:
        sonar.go.coverage.reportPaths: coverage.out
```

Out put from watch:
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 14.224s
INFO: Final Memory: 13M/313M
INFO: ------------------------------------------------------------------------
Reading SonarQube scanner report (./.scannerwork/report-task.txt)...
failed

This I am running for a hello world application. No error message before failing. I am using sonar runner from [cathativ sonar resource](https://github.com/cathive/concourse-sonarqube-resource)
