### ISSUE TITLE
LDAP Group Authentication for teams is not working

### ISSUE THREAD

**Issue by drduker** [concourse/concourse#2638]
## Bug Report

I've been able to create teams and assign ldap users specifically
<fly -t concourse-4 set-team -n team1 --local-user admin --ldap-user user1>

tailing the /var/vcap/sys/log/atc/atc.stdout.log file during ldap user login:
{"timestamp":"1538080212.178583622","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector "ldap", username="user1", email="user1@email.com", groups=[]","session":"5"}}

note= no other logs seem to show the ldap group search part initiating or taking place.

But the --ldap-group flag with an ldap group is not working to grant access to any concourse team.

Can you provide an example manifest patch for ldap configuration? Or is there problem with ldap still?

## Steps to Reproduce

create team with ldap groups assigned in version 4.2.1

## Expected Results

to be able to login with a user that is a member of the --ldap-group/s assigned.

## Actual Results

User does not see teams after ldap login they should have access to after granting ldap-group permissions to the team.

## Additional Context
Deploying in cluster method.  I've only been able to get the --ldap-user working.  I need ldap-group working to actually use ldap.

Type of settings i'm using are below.  I've tried different things for group_search_name_attr.  2016 MS AD.
concourse-bosh-deployment/cluster/concourse.yml:
ldap_auth:
    host: <server>:389
    bind_dn: CN=<path of bind user>
    bind_pw: <password>
    insecure_no_ssl: true
    start_tls: false
    user_search_filter: objectClass=person
    user_search_base_dn: <ou location here>
    user_search_username: sAMAccountName
    user_search_scope: sub
    user_search_id_attr: sAMAccountName
    user_search_email_attr: mail
    user_search_name_attr: name
    group_search_base_dn: <ou location here>
    group_search_filter: objectClass=group
    group_search_scope: sub
    group_search_group_attr: member
    group_search_name_attr: cn
## Version Info

* Concourse version: 4.2.4
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work?

**Comment by drduker** [comment]
Finally resolved for MSAD config.  Example:
```
ldap_auth:
        host: server...:389
        bind_dn: CN=bind users....
        bind_pw: password....
        insecure_no_ssl: true
        start_tls: false
        user_search_base_dn: OU=...
        user_search_username: sAMAccountName
        user_search_scope: sub
        user_search_id_attr: sAMAccountName
        user_search_email_attr: mail
        user_search_name_attr: name
        group_search_base_dn: OU=...
        group_search_scope: sub
        group_search_group_attr: member
        group_search_name_attr: cn
        group_search_user_attr: distinguishedName

```
