### ISSUE TITLE
empty pgsql password table after upgrade from 4.1.0 to 4.2.1

### ISSUE THREAD

**Issue by dober** [concourse/concourse#2662]
## Bug Report
After upgrade it contains only concourse local user. All local users are dissapeared.

```
concoursedb=# \x
Expanded display is on.
concoursedb=# select * from password;
-[ RECORD 1 ]------------------------------------------------------------------------------------------------------------------------
email    | concourse
hash     | \x_longhash
username | concourse
user_id  | concourse
```
If i try add local user from concourse web command for example - **it will replace current user** o.O:
```
docker exec concourse web --add-local-user test1:test
```
```
-[ RECORD 1 ]------------------------------------------------------------------------------------------------------------------------
email    | test1
hash     | \x24326124313024783679685a53565855732f50546479537655784761656171592f326
653465a6b64524e474b4f4d58346e4938542f35594e59574a2e
username | test1
user_id  | test1
```

Okay, i can restore table from a dump. But after next compose down/up i get an empty table again with single user.

working docker-compose.yml since 3.14 concourse version:

```
version: '3'

services:
  pgsql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concoursedb
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: some_password
      PGDATA: /database
    volumes:
      - ./pgdata:/database

  concourse-web:
    image: concourse/concourse:4.2.1
    links: [pgsql]
    command: web
    depends_on: [pgsql]
    ports:
      - "127.0.0.1:8080:8080"
      - "0.0.0.0:2222:2222"
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until concourse-db comes up
    environment:
      CONCOURSE_ADD_LOCAL_USER: concourse:$$2a$$10$$hash
      CONCOURSE_MAIN_TEAM_LOCAL_USER: concourse
      CONCOURSE_EXTERNAL_URL: https://domain.tld
      CONCOURSE_POSTGRES_HOST: pgsql
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: password
      CONCOURSE_POSTGRES_DATABASE: concoursedb
      CONCOURSE_VAULT_URL: https://domain.tld
      CONCOURSE_VAULT_PATH_PREFIX: /concourse
      CONCOURSE_VAULT_CLIENT_TOKEN: token
```

## Steps to Reproduce
1. Use 4.1.0 concourse image
1. Add some local users to database via concourse web and check them via psql cli
2. Upgrade image from 4.1.0 to 4.2.1 and check table again

## Version Info
* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): docker
