### ISSUE TITLE
fly execute cannot find build inputs on a job that hasn't been ran

### ISSUE THREAD

**Issue by browne0** [concourse/concourse#2677]
## Bug Report

I tried to run a fly execute command with some AWS creds, and fly returned back build inputs not found.

All of my files were committed, yet the command still failed.

## Steps to Reproduce

```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: meetup/node-awscli
    tag: 'latest'

inputs:
- name: events-proxy-repo

params:
  AWS_ACCESS_KEY_ID: ((aws_access_key_id))
  AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
  AWS_DEFAULT_REGION: ((aws_default_region))

run:
  path: events-proxy-repo/packages/events-proxy/ci/scripts/deploy.sh
```

### failing job in the pipeline

```yaml
- name: events-proxy-lambda-deploy
  plan:
  - get: events-proxy-repo
    trigger: true
    passed:
    - events-proxy-lambda-test
  - task: deploy
    file: events-proxy-repo/packages/events-proxy/ci/tasks/deploy.yml
```

## Expected Results

fly would execute a command with build inputs locally even if a job hasn't been ran yet

## Actual Results

fly errored out with this:

```
$ fly --verbose -t aws execute -c packages/events-proxy/ci/tasks/deploy.yml --inputs-from groups/events-proxy-lambda-deploy --input events-proxy-repo=.
2018/10/12 12:26:05 GET /api/v1/info HTTP/1.1
Host: concourse.dev.meetuphq.io
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2018/10/12 12:26:05 HTTP/1.1 200 OK
Content-Length: 43
Content-Type: application/json
Date: Fri, 12 Oct 2018 16:26:06 GMT
X-Concourse-Version: 4.1.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block

{"version":"4.1.0","worker_version":"2.1"}

2018/10/12 12:26:05 GET /api/v1/teams/main/pipelines/groups/jobs/events-proxy-lambda-deploy/inputs HTTP/1.1
Host: concourse.dev.meetuphq.io
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2018/10/12 12:26:05 HTTP/1.1 404 Not Found
Date: Fri, 12 Oct 2018 16:26:06 GMT
X-Concourse-Version: 4.1.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Content-Length: 0


error: build inputs not found
```

## Version Info

https://github.com/EngineerBetter/concourse-up/releases/tag/0.13.8
FLY VERSION: v4.1.0
CREDHUB: v2.0.2

Concourse VM: stemcell bosh-aws-xen-hvm-ubuntu-xenial-go_agent 97.22
* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BOSH through Concourse-Up
* Infrastructure/IaaS: AWS
* Browser (if applicable): N/A
* Did this used to work? idk
