### ISSUE TITLE
Name is not a required parameter on task outputs

### ISSUE THREAD

**Issue by alidaka** [concourse/concourse#268]
E.g., this:
```
jobs:
- name: my-job
  plan:
  - get: repo
  - task: my-task
    config:
      ...
      outputs:
        - name: foo
        - path: foobar
```

Gets parsed into:
```
      ...
      outputs:
        - name: foo
          path: ""
        - name: ""
          path: foobar
```

It's possible this has an impact elsewhere, but we got tripped up with our output naming. Via `fly hijack`, we additionally found this wiped out everything in concourse's execution root folder with the contents of our empty-named output.
