### ISSUE TITLE
Security bug: everyone who is logged via OIDC is member of team "main"

### ISSUE THREAD

**Issue by ralekseenkov** [concourse/concourse#2680]
## Bug Report

We have a very simple setup:
1) `team1` = allows local `user1` and oidc group `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`
2) `main` team can only be accessed by local user `concourse` and no one else (we don't really want anyone to have access to `main`)

When you log in as `user1`, it can only see `team1` pipelines as expected.

When you log in via OIDC, a user can both see `team1` pipelines (expected) and `main` pipelines (unexpected). Moreover it says that OIDC user is a member of team `main`, i.e. has full privileges.

## Steps to Reproduce

The following config
```
# fly -t test teams -d
name               users                                                   groups
team1              local:user1                                             oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
main               cf:,github:,gitlab:,ldap:,oauth:,oidc:,local:concourse  cf:,cf:,github:,github:,gitlab:,ldap:,oauth:,oidc:
```

## Expected Results

Any user logged in via OIDC should only have access to `team1`

## Actual Results

Any user logged in via OIDC is a member of `main` team and has super privileges 😞

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Helm
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): Chrome

**Comment by ralekseenkov** [comment]
@vito @jama-pivotal is there anything we are doing wrong here?

**Comment by vito** [comment]
This looks like a bug with configuring the `main` team. The last line of your `fly teams -d` looks super suspicious:

```
main               cf:,github:,gitlab:,ldap:,oauth:,oidc:,local:concourse  cf:,cf:,github:,github:,gitlab:,ldap:,oauth:,oidc:
```

What's with all those empty users and groups?

**Comment by vito** [comment]
Could you run `fly teams --verbose` and paste the output? (Be careful to censor any sensitive info.)

**Comment by ralekseenkov** [comment]
@vito that's how params were passed in the official Helm chart. I just wasn't seeing a reason why "oidc:" would make anyone super admin.

here is the output of verbose (sensitive information replaced)
every team is mapped to 1 service local user and OIDC

```
251
[{"id":1,"name":"main","auth":{"groups":["cf:","cf:","github:","github:","gitlab:","ldap:","oauth:","oidc:"],"users":["cf:","github:","gitlab:","ldap:","oauth:","oidc:","local:concourse"]}},{"id":5,"name":"team-eng","auth":{"groups":["oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"],"users":["local:team-eng"]}},{"id":6,"name":"team-prod","auth":{"groups":["oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"],"users":["local:team-prod"]}},{"id":8,"name":"team-infra","auth":{"groups":["oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"],"users":["local:team-infra"]}}]

0


name               users                                                   groups
team-eng    local:team-eng                                   oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
team-infra  local:team-infra                                 oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
team-prod   local:team-prod                                  oidc:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
main               cf:,github:,gitlab:,ldap:,oauth:,oidc:,local:concourse  cf:,cf:,github:,github:,gitlab:,ldap:,oauth:,oidc:
```

**Comment by pivotal-jwinters** [comment]
@ralekseenkov In the helm chart `values.yml` did you comment out all the providers that you don't want under `auth.mainTeam` or did you leave them empty?

**Comment by ralekseenkov** [comment]
@pivotal-jwinters Another thing is - we are still running off https://github.com/helm/charts/pull/6951 and official Helm chart went a slightly different route just a few days ago.

Our config is:
```
  mainTeam:
    localUsers: ["concourse"]

    allowAllUsers: false

    cfUsers: []

    cfOrgs: []

     ...... (everything is empty)
```

If the issue is in "oidc:" and other empty values, we can definitely get them removed.

But I think treating empty values as "everyone a super admin" seems pretty dangerous.

**Comment by vito** [comment]
@ralekseenkov It definitely doesn't make sense to have empty mean admin. I'm wondering if this is a nasty case of missing validation somewhere. And also wondering how those empty values were configured into the system in the first place (env vars? flags?). (And why the main team lists two `cf:` groups.)

**Comment by ralekseenkov** [comment]
@vito the previous Helm chart PR didn't care much about the presence of each value, so it would just take each list and concatenate:
```
env:
            - name: CONCOURSE_MAIN_TEAM_CF_USER
              value: {{ join "," .cfUsers }}
            - name: CONCOURSE_MAIN_TEAM_CF_ORG
              value: {{ join "," .cfOrgs }}
...
```

so answering your question -- it was done via env vars set to empty values.
and no idea why there are two "cf:" groups, but I hope it doesn't matter much

**Comment by ralekseenkov** [comment]
from Kubernetes pod:
```
      CONCOURSE_MAIN_TEAM_LOCAL_USER:          concourse
      CONCOURSE_MAIN_TEAM_CF_USER:
      CONCOURSE_MAIN_TEAM_CF_ORG:
      CONCOURSE_MAIN_TEAM_CF_SPACE:
      CONCOURSE_MAIN_TEAM_GITHUB_USER:
      CONCOURSE_MAIN_TEAM_GITHUB_ORG:
      CONCOURSE_MAIN_TEAM_GITHUB_TEAM:
      CONCOURSE_MAIN_TEAM_GITLAB_USER:
      CONCOURSE_MAIN_TEAM_GITLAB_GROUP:
      CONCOURSE_MAIN_TEAM_LDAP_USER:
      CONCOURSE_MAIN_TEAM_LDAP_GROUP:
      CONCOURSE_MAIN_TEAM_OAUTH_USER:
      CONCOURSE_MAIN_TEAM_OAUTH_GROUP:
      CONCOURSE_MAIN_TEAM_OIDC_USER:
      CONCOURSE_MAIN_TEAM_OIDC_GROUP:
```
