### ISSUE TITLE
Make 'username' claim name configurable for OAuth and OIDC

### ISSUE THREAD

**Issue by ralekseenkov** [concourse/concourse#2683]
Per conversation with @pivotal-jwinters 

## What challenge are you facing?

WIth Azure OIDC, username is always empty in the logs when user does login into Concourse.

## What would make this better?

There is already "oauth-auth-groups-key" and "oidc-auth-groups-key" parameters for how the "group" claim is called (default should be "groups").

For consistency, it might make sense to add "oauth-auth-username-key" and "oidc-auth-username-key" parameters for the "username" claim (default should be "username").

For Azure, we'd prob need to set it to "name" or "preferred_username". Here is the list of supported claims:
```
"claims_supported":["sub","iss","cloud_instance_name","cloud_instance_host_name","cloud_graph_host_name","msgraph_host","aud","exp","iat","auth_time","acr","nonce","preferred_username","name","tid","ver","at_hash","c_hash","email"]
```
Needs a Concourse change + Helm chart change.

## Are you interested in implementing this yourself?

Likely not. If anything, we are more interested in stability (we have issues related to resource checks hanging, worker stability, etc). Trying to reproduce other higher-priority Concourse issues right now.

**Comment by mmb** [comment]
We also run into this issue with ADFS OIDC. It causes the UI to show the long "sub" hash as the user id.

**Comment by ralekseenkov** [comment]
For us UI was showing hash when neither email nor username was available.

When we got Azure to return email claim correctly, Concourse picked it up and started showing email in the upper right corner in UI. But it still didn't pick up username, so fly set-team would not operate correctly if you want to add OIDC users to teams based on the username.

**Comment by mmb** [comment]
The only way we could get set-team to with individual oidc users was using `--oidc-user=<long hash>`. Good to know that if we can get it to return username we can use that instead.

**Comment by mattronix** [comment]
How do you find the users long hash @ralekseenkov ?

**Comment by making** [comment]
I see this issue when integrating UAA as an OIDC provider.

`name` claim is currently hardcoded for username. https://github.com/concourse/concourse/blob/d666f91e6e0ab2432f53db8f67cb5764e2698b4f/skymarshal/token/verifier.go#L75
and UAA does not support `name` in id token.
https://github.com/cloudfoundry/uaa/issues/932
As a result, login username is always empty.

Some PKS customers want to integrate its UAA to Concourse. I don't this it is possible now.

I'd like concourse to have the ability to customize username claim like Kubernetes has
https://github.com/kubernetes/kubernetes/blob/v1.13.1/pkg/kubeapiserver/options/authentication.go#L228-L231
https://github.com/kubernetes/kubernetes/blob/v1.13.1/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L564-L597

**Comment by keithkroeger** [comment]
Any support for this, @pivotal-jwinters ?

**Comment by keithkroeger** [comment]
> 
> 
> I see this issue when integrating UAA as an OIDC provider.
> 
> `name` claim is currently hardcoded for username and UAA does not support `name` in id token.
> [cloudfoundry/uaa#932](https://github.com/cloudfoundry/uaa/issues/932)
> As a result, login username is always empty.
> 
> Some PKS customers want to integrate its UAA to Concourse. I don't this think it is possible now.
> 
> I'd like concourse to have the ability to customize username claim like Kubernetes has
> https://github.com/kubernetes/kubernetes/blob/v1.13.1/pkg/kubeapiserver/options/authentication.go#L228-L231
> https://github.com/kubernetes/kubernetes/blob/v1.13.1/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L564-L597
> 
> Maybe need to change concourse/dex to support `UsernameKey` first
> https://github.com/concourse/dex/blob/master/connector/oidc/oidc.go
> 
> Updated: As a workaround for UAA integration, OAuth works instead of OIDC.

@making, can you provide any further details on the workaround?  Sounds like you configured UAA for OAuth and then use UAA with Concourse?

**Comment by pivotal-jwinters** [comment]
@keithkroeger it probably won't make it into 5.0, but hopefully soon after.

If you're using UAA you should probably use the OAuth connector instead of OIDC anyway. UAA doesn't work with the OIDC connector because the `iss` in the token has `/token` appended to it. In order for OIDC to work the issuer needs to match the base path used to construct the `/.well-known/openid-configuration` request.

**Comment by keithkroeger** [comment]
@pivotal-jwinters thank you for the reply.
We attempted using OAUTH (https://github.com/concourse/concourse/issues/2618), but that issue was closed since it closely related to this issue.

We'll wait in baited breath.  Thank you, again

**Comment by making** [comment]
@keithkroeger What's your problem?
I'm using the following ops-file for uaa deployment:

``` yaml
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/concourse?
  value:
    access-token-validity: 604800
    refresh-token-validity: 1209600
    authorized-grant-types: authorization_code,refresh_token
    override: true
    redirect-uri: https://concourse.example.com/sky/issuer/callback
    scope: openid,email,profile,roles
    secret: my-secret
```

and for concourse deployment

```yaml
- type: replace
  path: /instance_groups/name=web/jobs/name=atc/properties/generic_oauth?
  value:
    client_id: concourse
    client_secret: my-secret
    auth_url: https://uaa.example.com/oauth/authorize
    token_url: https://uaa.example.com/oauth/token
    userinfo_url: https://uaa.example.com/userinfo
```

works well.
