### ISSUE TITLE
Yellow arrow for new version of a resource doesn't show correctly on manual build

### ISSUE THREAD

**Issue by ryanmattcollins** [concourse/concourse#2713]
## Bug Report

We kicked off a job that has a `get` git resource with a new version. When we initially kicked it off, the "new version" yellow resource was present, but when we refreshed the resource no longer had the yellow arrow.

## Steps to Reproduce

Not sure if it is easily reproducible, but here are some details that might help debug:

- The job was kicked off manually
- There are no triggers on the job
- There was one version of the `prod-aws` between the two builds that was not used

The relevant pipeline yml is below:
```
resources:
- name: prod-aws
  type: git
  source:
    branch: master
    private_key: ((REDACTED))
    uri: git@github.com:pivotal-cf/prod-aws.git
...
jobs:
- name: bosh-create-env
  serial: true
  build_logs_to_retain: 1000
  plan:
  - aggregate:
    - get: cloudops-ci
    - get: prod-aws
      params:
        submodules: none
  - task: bosh-create-env
    file: cloudops-ci/concourse/tasks/bosh-create-env.yml
    params:
      ((REDACTED))
    ensure:
      do:
      - put: prod-aws
        params:
          rebase: true
          repository: updated-prod-aws
        get_params:
          submodules: none
```

## Expected Results

`prod-aws` resource has a yellow arrow next to it in build 56

## Actual Results

`prod-aws` resource does not have a yellow arrow next to it in build 56

![screen shot 2018-10-19 at 11 17 45 am](https://user-images.githubusercontent.com/4941777/47311829-c223ab00-d608-11e8-91ad-410fc1f5b1f7.png)
![screen shot 2018-10-19 at 11 17 28 am](https://user-images.githubusercontent.com/4941777/47311828-c223ab00-d608-11e8-9a3e-0b9cabfc853c.png)

## Version Info

* Concourse version: 4.2.1
* Deployment type: BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work?: Presumably
