### ISSUE TITLE
inconsistent resources order returned by get-pipeline command

### ISSUE THREAD

**Issue by alpha-er** [concourse/concourse#2814]
fly version: 3.14.1

There will always be at least one team pipeline whose config when returned by `fly get-pipeline` command will have varying order of its resources. For example, first run of `fly get-pipeline -p mypipeline` returns:
```
...
resources:
- name: a
  type: git
- name: b
  type: docker-image
- name: c
  type: git
...
```
The next run may return:
```
...
resources:
- name: c
  type: git
- name: a
  type: git
- name: b
  type: docker-image
...
```
Affects concourse-pipeline-resource `check` command (concourse/concourse-pipeline-resource#38)
