### ISSUE TITLE
Support lists in variable files

### ISSUE THREAD

**Issue by mikemol** [concourse/concourse#2817]
Scenario: I have a single common pipeline structure represented as a `pipeline.yml` file, but I need various inputs and outputs parameterized. One of those is the `paths` parameter of the `git` resource, which takes a list.

What I've found so far is that I can't say

```
params:
  paths: {{my_paths}}
```

in `pipeline.yml` and, in the variable file,

```
my_paths:
  - path1
  - path2
  - path3
```

or

```
my_paths: ['path1', 'path2', 'path3']
```

or even

```
my_paths: "['path1', 'path2', 'path3']"
```

The last is the only one that doesn't blow up with

```
error: could not resolve old-style template vars: yaml: unmarshal errors:
  line 4: cannot unmarshal !!seq into string
```

but if I run `get-pipeline` against the resulting pipeline, I can see that variable expanded to a string, not YAML data.

As a workaround, I'm going to try providing a hardcoded list path placeholders, but that's just...ugly.

**Comment by MatthiasPanisson** [comment]
i have same issue.
in my pipeline.yml

`policy_templates: {{policy_templates}}`

in config.yml
`policy_templates:
  - envSoa: dev
    name: multiplexeurV1
    routingEndpoint: https://gggg
  - envSoa: qa
    name: multiplexeurV1
    routingEndpoint: https://dddd
  - name: validateJWTBearerAddSignedJWT
    audience: oel
  - name: failoverRouteV1
    routingEndpointSiteA: https://ggg
`
error:
`error: could not resolve old-style template vars: yaml: unmarshal errors:
  line XX: cannot unmarshal !!seq into string`


Have we an estimation date... 
As a workarround i,m going to put that config in other file and make a batch replace before the set-pipeline. Just horrible but only solution it seems

**Comment by vito** [comment]
This has long been supported by using `((these vars))` instead of `{{these vars}}`. The `{{}}` style has been out of favor for a long time, and we should probably just remove it soon.

See https://concourse-ci.org/setting-pipelines.html#pipeline-vars

**Comment by MatthiasPanisson** [comment]
same errors using policy_templates: ((policy_templates))

**Comment by vito** [comment]
@mqueb Make sure you either use `-l` or `-y`; `-v` is for string values only.

**Comment by mqueb** [comment]
was using -l
fly vp -c pipeline.yml -l config.yml

**Comment by dangthanh360** [comment]
I got the same error using fly 4.2.3:
```bash
fly -t my-team set-pipeline -p my-pipeline -c pipeline.yml  -l config.yml

error: could not resolve old-style template vars: yaml: unmarshal errors:
  line 4: cannot unmarshal !!map into string
```

**Comment by jpmorin** [comment]
For anyone stumbling upon this issue, know that it has been fixed in recent versions. You can test it with the following pipeline and parameter file.

#### pipeline.yml
```yml
jobs:
- name: test-job
  plan:
  - task: test-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: stedolan/jq
          tag: latest
      run:
        path: sh
        args:
        - -c
        - |
          echo $MULTILINE_PARAMS | jq . -c
    params:
      MULTILINE_PARAMS:
        ((multiline-params))
```

#### parameters.yml
```yml
multiline-params:
  params1: "value1"
  params2: 2
  params3: true
  params4:
    - "first"
    - "second"
    - "third"
  params5: [1, 2, 3]
  params6:
    - name: Fred
      lastname: Flintstone
    - name: Barney
      lastname: Rubble
```

#### set-pipeline
```bash
$ fly -t {target-name} sp -p test-multiline-params -c pipeline.yml -l parameters.yml 
```

The `MULTILINE_PARAMS` parameter is passed as json to the task. Execution the job will produce the following output:
```json
{"params1":"value1","params2":2,"params3":true,"params4":["first","second","third"],"params5":[1,2,3],"params6":[{"lastname":"Flintstone","name":"Fred"},{"lastname":"Rubble","name":"Barney"}]}
```
**P.S.** tested on concourse v5.7.0
