### ISSUE TITLE
Concourse couldn't find local docker image

### ISSUE THREAD

**Issue by mehdishahdoost** [concourse/concourse#2930]
## Bug Report

When I execute task that contains  docker image resource that locally available and not exists on docker hub got "failed to fetch digest: 403 Forbidden" error.

## Steps to Reproduce

execute https://gist.github.com/mehdishahdoost/8cfc59d710dd35e19c423b4e3dc79f4f task with below command:

fly -t tutorial execute -c task_hello_world.yml

myubuntu is exists on my local docker. and my machine doesn't have internet connection.

## Expected Results

print hello world.

## Actual Results

executing build 13 at http://127.0.0.1:8080/builds/13 
initializing
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 403 Forbidden

errored

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by xtremerui** [comment]
```
resource_types:
- name: docker-image-resource
  type: docker-image
  privileged: true
  source:
    repository: example.com:5000/docker-image-resource
    tag: latest
```

here is an example of using custom docker registry. In you case you will need to host a [local docker registry](https://docs.docker.com/registry/deploying/) with a repo that has `myubuntu` docker image.
