### ISSUE TITLE
load parameter string value from resource

### ISSUE THREAD

**Issue by frankbecker** [concourse/concourse#2942]
## What challenge are you facing?

I have created a custom resource type that pulls in data with every check and provides to the higher level resource. I then would like to set parameters values for other tasks based on the data I retrieve with **check** and **in**.
Currently I can only set variables with the `fly` command. i.e.
`fly -t dev set-pipeline -p my-pipeline -c pipeline.yml -v MY_CUSTOM_VALUE=foo`
And then it's used like:
```
- task: integration-test
  params:
    TASK_PARAMETER: ((MY_CUSTOM_VALUE))
```

## What would make this better?

I would like to load the `TASK_PARAMETER` value from a dynamic source, ideally from a resource, somehow.

```
- get: my-resource
- task: integration-test
  params:
    TASK_PARAMETER: cat my-resource/TASK_PARAMETER.txt
```

## Are you interested in implementing this yourself?

I don't really know how to implement this.
This would be extremely helpful. I feel like this is a major Concourse limitation, I was hoping it could be a bit more flexible and dynamic.

**Comment by marco-m** [comment]
As a workaround, you can do the `cat my-resource/TASK_PARAMETER.txt` in the task itself, maybe wrapping the actual task with a shell script.

**Comment by marco-m** [comment]
First of all, I begun by mentioning "workaround", so I agree situation could be better :-)
But, why would you have to fork the resources ? The whole point of resources is that you write them in the language you want, their API is super simple, they give you back a file, like the one we are talking about `my-resource/TASK_PARAMETER.txt`. The task would have as `input` directory `my-resource`. Another feature that might help you is input and output mapping, see https://concourse-ci.org/task-step.html#input_mapping

**Comment by frankbecker** [comment]
Yes, I understand, but that would require me to modify and update the existing resources that I am using, which take a file name, or any string value, and instead I would have to load from an input mapping which you just described. I just wish there was an easier way :) I appreciate your comments 👍

**Comment by frankbecker** [comment]
Could I maybe create a task that can serve as an interface for this resource that I am using, that can maybe pass this dynamic string value? Uhmm....

**Comment by frankbecker** [comment]
Still wasn't able to get this done. :(

**Comment by tomasgareau** [comment]
@frankbecker -- I believe this is now possible with the [`load_var` step](https://github.com/concourse/rfcs/pull/27), which allows setting a build-local variable from the contents of a file.

The original example in this issue would look something like:

```yaml
- get: my-resource
- load_var: task-param-var                # I can name this whatever I want
  file: my-resource/TASK_PARAMETER.txt    # `task-param-var` will be loaded with the contents of this file
- task: integration-test
  params:
    TASK_PARAMETER: ((.:task-param-var))  # now I can refer to this var with ((.:<my_var_name>))
```
