### ISSUE TITLE
Resource gets stuck on old version

### ISSUE THREAD

**Issue by tanner-bruce** [concourse/concourse#2948]
## Bug Report

After running our pipeline through to completion, the git resource marked `@develop` used by `deploy-test` will get stuck on SHA that was last used by `deploy-prod`. On each commit to the develop branch, `build-image` will still be triggered and build a new image and bump the `build-version` resource properly, however, `deploy-test` will *NOT* be triggered using that new version. Further, manually triggering `deploy-test` will cause that now stuck SHA

## Steps to Reproduce

Apply [pipeline](https://gist.github.com/tanner-bruce/aaffc5fe5251e88c89d0c621f73bb9f6). Run pipeline all the way to `deploy-prod`. Commit to the repo. `deploy-test` will use the SHA that was last used in `deploy-prod`

## Expected Results

The commits should not get 'stuck'

## Actual Results

The resource versions get 'stuck'

## Additional Context

I am available to help debug this using my infrastructure as I understand this one is hard to reproduce.

## Version Info

* Concourse version: 4.2.1 (also happened on 4.0.0)
* Deployment type (BOSH/Docker/binary): kubernetes
* Infrastructure/IaaS: GKE
* Did this used to work? Yes. Even on the same servers, it was working, then stopped. Now it reproduces reliably even on new pipelines.

**Comment by tanner-bruce** [comment]
@vito is there any additional information I can provide, or things I can run that would help diagnose this? I've played around with various modifications to the pipeline and am somewhat convinced it is related to the `git` resource

**Comment by tanner-bruce** [comment]
Here are the most relevant parts I can think of. I showed the most recent run of `build-image`, and the subsequent manually triggered `release-test`. You can see `release-test` does not pull the proper commit. It pulled `ea3c407ae3e9154c049a1d75458d7bdbf721402c` when it should have been `f643f6b17dfe9c88f3927456f9fc5f770e6fccf1`


![image](https://user-images.githubusercontent.com/21345430/50993063-5b62af00-14de-11e9-99e3-e3edcccc6678.png)

![image](https://user-images.githubusercontent.com/21345430/50993089-661d4400-14de-11e9-873d-241ce0acb3ca.png)

![image](https://user-images.githubusercontent.com/21345430/50993103-6e757f00-14de-11e9-8370-6ebea7508987.png)

![image](https://user-images.githubusercontent.com/21345430/50993486-64a04b80-14df-11e9-998a-2ed72039635d.png)


```
    - name: build-image
      plan:
      - get: build-version
        params:
          pre: build
      - get: us.gcr.io/image-place/gcloud
      - get: source-code
        resource: boldapps/moes-tavern-sample-php-app.git
        params: {depth: "1"}
        trigger: true
      - put: us.gcr.io/image-place/sample-app
        get_params:
          skip_download: "true"
        params:
          build: source-code
          build_args:
            SSH_PRIVATE_KEY: ((ssh-key))
          dockerfile: source-code/Dockerfile
          tag: build-version/number
      - params:
          file: build-version/number
        put: build-version

    - name: release-test
      plan:
      - aggregate:
        - get: us.gcr.io/image-place/sample-app
          params: {skip_download: "true"}
          passed: [build-image]
        - get: boldapps/moes-tavern-sample-php-app.git
          passed: [build-image]
          params: {depth: "1"}
        - get: build-version
          passed: [build-image]
        - get: next-version
          resource: build-version
          params:
            pre: test
          passed: [build-image]
        - get: gcloud
          resource: us.gcr.io/image-place/gcloud
      - config:
          inputs:
          - name: source-version
          - name: dest-version
          platform: linux
          run:
            args:
            - -c
            - |2

              set -e
              export IMAGE=us.gcr.io/image-place/sample-app
              OLD=$(cat source-version/number)
              NEW=$(cat dest-version/number)
              gcloud auth activate-service-account "((gcp-service-account))" --key-file <(echo '((gcp-service-account-key))')
              set -x
              gcloud config set project image-place
              gcloud container images add-tag ${IMAGE}:${OLD} ${IMAGE}:${NEW} -q
            path: bash
        image: gcloud
        input_mapping:
          dest-version: next-version
          source-version: build-version
        task: tag-image
      - put: test-version
        params:
          file: next-version/number
```
