### ISSUE TITLE
Tagged resources should not re-use check containers from workers that don't have the configured tags

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3002]
## Bug Report

I noticed that it might be possible to a resource that can only be checked in a worker that's tagged with a specific tag, but have that never happen due to global resources taking just `source` in consideration (if I understood correctly).

For instance, consider the case where only `aws`-tagged workers are capable of performing certain actions (like, accessing S3 buckets because they have IAM Roles attached to them):

```yaml
- name: release-from-aws
  tags: [ aws ]
  type: s3
  source: &release-source
    bucket: sample-concourse-s3-resource
    initial_path: binary-1.0.0.tgz
    regexp: binary-(.*).tgz
    region_name: us-east-1
    skip_download: true

- name: release-from-gke
  type: s3
  source: *release-source
```

I'm not sure if this is a *bug* or not - should we consider `tags`?

## Steps to Reproduce

1. have two workers - one tagged, the other not
2. create a pipeline with two resources that share the same config, but differ by having `tags` in one of them
3. verify that the checks always happen in one of the workers (global resources!) - not necessarily in the one with the tag.

## Expected Results

I'm not really sure; eventually, happen over both? Although, I guess that could generate weird results if the worker is not only providing credentials. Maybe this could even end up leaking info somehow?

## Version Info

* Concourse version: master (c862322702eea2fd561b1a04de18ab1c1ef4810b)
