### ISSUE TITLE
Multi-level Parameters

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#302]
Currently the `params` configuration element only allows a single level object depth.  In attempt to support [Slack Message Attachments](https://api.slack.com/docs/attachments), it'd be great if we could have arbitrarily deep configuration objects.

Having this ability results in messages with a bit more flash:

<img width="383" alt="screen shot 2016-02-28 at 10 07 32" src="https://cloud.githubusercontent.com/assets/60754/13381029/0444ec9a-de06-11e5-949e-e4ebe5b93d34.png">

instead of

<img width="363" alt="screen shot 2016-02-28 at 10 07 41" src="https://cloud.githubusercontent.com/assets/60754/13381032/0b67333e-de06-11e5-9095-7c3b8a84fb67.png">

Currently a configuration like

```yaml
---
jobs:
- name: some-job
  plan:
  - put: slack-alert
    params:
      attachments:
      - color: good
        fallback: $BUILD_PIPELINE_NAME #$BUILD_NAME has been deployed: $ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        text: $BUILD_PIPELINE_NAME <$ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|#$BUILD_NAME> has been deployed
```

results in

```
error: Unexpected Response
Status: 500 Internal Server Error
Body:
failed to save config: json: unsupported type: map[interface {}]interface {}
```
