### ISSUE TITLE
Check-resource-type causes pipeline stuck

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3048]
## Bug Report

We found that sometime after a job is triggered, the job is stuck to run, no container can be started. This intermittently occurs.

The other finding is that, when we do "fly check-resource-type", sometime it's very fast, but sometime it's just stuck, seem never terminate, we have to use ctrl-c to terminate it.

Then I created a pipleline to monitor a cluster. This pipeline is triggered by a timer every 20 minutes, then send an email to me. Most of time, emails reach to my mailbox in time, but intermittently I see delayed emails. The pattern is like, every 40-50 minutes, there is a delayed email, but the delays are all around 16-17 minutes.

We further found that "concourse web" has an option "--resource-type-checking-interval", default value is 1 minute. Then we tried to set this interval to 48 hours. After that, frequency of delayed emails is significantly dropped, like every day there is a delayed email.

Obviously we don't want to use 48 hours as resource-type-checking-interval in production cluster, but we don't like job stuck the more. 

## Steps to Reproduce

My pipeline to send email by timer:

```yaml
resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource


resources:
- name: my-timer
  type: time
  source:
    interval: 10m

- name: email-sender
  type: email
  source:
    smtp:
      host: xxxx
      port: "25"
      anonymous: true
      skip_ssl_validation: true
    from: runway-dev-noreply@vmware.com
    to: ["my@mail"]

jobs:
- name: ping-from-concourse
  public: true
  plan:
  - get: my-timer
    trigger: true

  - task: copy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: my-timer
      outputs:
      - name: email
      run:
        path: sh
        args:
         - -exc
         - |
           cp my-timer/input email/body
           echo >> email/body
           date
           echo "Task execution time: $(date)" >> email/body
           echo "BUILD: \${BUILD_NAME}" >> email/body

  - put: email-sender
    params:
      subject_text: Ping from Concourse
      body: email/body
```

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Web Nodes on K8S, Worker Nodes on VM (vSphere)
* Browser (if applicable): Chrome, Firefox
* Did this used to work? Intermittent issue
