### ISSUE TITLE
USABILITY: Add cyclical pipeline references to validation errors

### ISSUE THREAD

**Issue by jghiloni** [concourse/concourse#3053]
## Bug Report

If you have a cyclical reference in a job, for example:

```yaml
jobs:
- name: my-job
  plan:
  - get: some-resource
    trigger: true
    passed: [my-job]
```

You can set the pipeline via `fly` but the UI ... is unhappy

## Steps to Reproduce

Create a pipeline with a job that conforms to the passed criteria seen above

## Expected Results

`fly set-pipeline` should error and point out the cyclical reference

## Actual Results

`fly set-pipeline` works but the ATC doesn't render unless you remove the pipeline or log in as a user that doesn't have access to that pipeline

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): any
* Infrastructure/IaaS: any
* Browser (if applicable): chrome (probably any)
* Did this used to work? shouldn't have!
