### ISSUE TITLE
Concurrent tasks modifying shared volumes produce non-deterministic results

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#3058]
## Steps to Reproduce

Suppose I have the following Job that concurrently runs two deployments that each consist of 

- 1) processing a manifest stored in the repo
- 2) deploying something based on the processed manifest from the output of task 1)

```yaml
- name: "deploy"
  max_in_flight: 1
  plan:
  - aggregate:
    - do:
      - task: process manifest a # 1.1)
        file: repo/ci/util/manifest.yml
        params:
          MANIFEST: ci/x/manifests/a.yml
      - put: cf # 1.2)
        params:
          manifest: processed-manifests/a.yml
    - do:
      - task: process manifest b # 2.1)
        file: repo/ci/util/manifest.yml
        params:
          MANIFEST: ci/x/manifests/b.yml
      - put: cf # 2.2)
        params:
          manifest: processed-manifests/b.yml
```
(some details cut for brevity).

We noticed that sometimes the step 2) 's in each aggregate/do pair would fail to find the manifest from step 1). What I think is happening here is that both step 1)'s  concurrently access the volume `processed-manifests` whenever they happen to run on the same worker. Which "branch" (assuming volumes are copy on write) of the `processed-manifests` volume ends up in step 2) is not deterministic and depends on task scheduling onto workers.

I think we are hit so often by this issue as we use the random-worker scheduling strategy to achieve equal task distribution in our cluster.

## Expected Results

I feel either one of these two things should happen: 

- copy-on-write volumes/layers should correctly follow "task step branches" i.e. the volume that a task step sees is guaranteed to have been processed by a previous task step
- warn the user that his tasks are concurrently accessing overlapping volumes

I'm leaning towards the second option, as I think it's possible to come up with a case where the first option can't be defined in a sound way. 

## Actual Results

The task outputs on the shared volume clobber each other in an non-deterministic way (task execution order/worker volumes) leading to pipeline failures. I think this is similar to https://github.com/concourse/concourse/issues/483 but also related to https://github.com/concourse/concourse/issues/1799

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): K8s Helm
* Infrastructure/IaaS: Meshcloud OpenStack
