### ISSUE TITLE
Improve message for malformed pipeline ("cannot unmarshal !!map into string")

### ISSUE THREAD

**Issue by walterdolce** [concourse/concourse#3098]
## Feature request

Improve error reporting on pipeline YAML.

Formerly: _Setting a pipeline as seen from the documentation does not work._

## Steps to Reproduce

Create the following file:
```
---
resources:
- name: myapp-code-repository
  type: git
  source:
    uri: "some-github-repository-url"

jobs:
- name: unit tests
  plan:
  - get: myapp-code-repository
    trigger: true
  - task:
      platform: linux
      image_resource: docker-image
      source:
        repository: python
        tag: 3.4
      inputs:
        name: myapp-code-repository
      run:
        path: path/to/some/script
```

Download and start concourse locally (command taken from the [Quick Start guide on the official website](https://concourse-ci.org/)):
```
wget https://concourse-ci.org/docker-compose.yml
docker-compose up
```

Login to concourse, then set the pipeline:
```
fly -t tutorial login -c http://127.0.0.1:8080 -u test -p test
fly -t tutorial validate-pipeline -c pipeline.yaml
```

## Expected Results

The pipeline should be set

## Actual Results

YAML validation fails with:
```
error: yaml: unmarshal errors:
  line 7: cannot unmarshal !!map into string
```

## Additional Context
N/A

## Version Info

* Concourse version: 4.2.2
* Deployment type: docker
* Infrastructure/IaaS: my laptop (macOS)
* Browser (if applicable): N/A
* Did this used to work?: This is a fresh install and bootstrap of Concourse
