### ISSUE TITLE
topgun/k8s: ATC TLS termination 

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3105]
Hey,

After https://github.com/helm/charts/pull/9665 got introduced, `web` became able to perform [TLS termination](https://www.cloudflare.com/learning/ssl/transport-layer-security-tls/) directly on it, not needing someone to use an [L7 (application-layer)](https://en.wikipedia.org/wiki/Application_layer) load-balancer in order to provide HTTPS capabilities.

The way one can configure the necessary TLS parameters is as follows:

```yaml
concourse:
  web:
    externalUrl: https://test.com
    tls:
      enabled: true
      bindPort: 443
secrets:
  webTlsCert: $CERT
  webTlsKey: $KEY
```

Internally, the Chart puts the certificate and the private key at a specific location (configurable through [`web.tlsSecretsPath`](https://github.com/helm/charts/blob/641b216a13e86e9f29e5071f2b036df5a17fc7df/stable/concourse/templates/web-deployment.yaml#L125-L126)) which `web` is then able to pick up.

We could have that type of deployment verified with a test that attests that such a scenario is possible.
