### ISSUE TITLE
topgun/k8s: ensure worker lifecycle works 

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3111]
Hey,

With the changes that Concourse recently went through in terms of having the `retire`ing and `land`ing done through signals, the Chart moved from `fly retire`ing to using `SIGUSR2` in its `preStop` hook for the `concourse worker` container.

```yaml
          lifecycle:
            preStop:
              exec:
                command:
                  - "kill"
                  - "-s"
                  - {{ .Values.concourse.worker.shutdownSignal | quote }}
                  - "1"
```

(see https://github.com/helm/charts/blob/d33e4999a5c2a8c8800d48a874807120be3499f6/stable/concourse/templates/worker-statefulset.yaml#L81-L88)

To increase our confidence regarding the way that the Chart manages that worker lifecycle, we'd be a in better place ensuring that:

- [x] upon pod deletion, the worker goes through the desired lifecycle: `running -> retiring -> <none> -> running`;
- [x] upon new pod creation, the worker comes back gently (without facing any connection issues / volumes not found problems); and 
- [x] having workloads still running, `terminationGracePeriod` is honored.

```yaml
      {{- if .Values.worker.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      {{- end }}
```

(see https://github.com/helm/charts/blob/d33e4999a5c2a8c8800d48a874807120be3499f6/stable/concourse/templates/worker-statefulset.yaml#L38-L40)

Thanks!
