### ISSUE TITLE
Newly added job is triggered despite being dependent on a failing one

### ISSUE THREAD

**Issue by walterdolce** [concourse/concourse#3115]
## Bug Report

Adding a new job which depends on a failed one sees Concourse triggering it (!)

<img width="1182" alt="screenshot 2019-01-21 at 22 52 05" src="https://user-images.githubusercontent.com/6195629/51502843-de81e000-1dcf-11e9-9fab-6f77840041cd.png">

## Steps to Reproduce

Use this configuration file:
```
---
resources:
- name: myapp-code-repository
  type: git
  source:
    uri: "https://github.com/some-repository"

jobs:
- name: run unit tests
  plan:
  - get: myapp-code-repository
    trigger: true
  - task: run unit tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.4
      inputs:
        - name: myapp-code-repository
      run:
        path: python
        args:
          - "myapp-code-repository/some_file_with_a_failing_test_or_similar.py"
```

Add it to Concourse (4.2.2). Make it fail. Then add this to the pipeline YAML:
```
- name: deploy to production
  plan:
  - get: myapp-code-repository
    trigger: true
    passed:
      - run unit tests
  - task: deploy to production
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: google/cloud-sdk
          tag: 229.0.0
      inputs:
        - name: myapp-code-repository
      run:
        path: kubectl
        args:
          - "appy -f my-application.yml"
```

You should see the step being triggered despite job being dependent (via the `passed` key) on a step that was failing (!)

## Expected Results
Concourse should not trigger the newly added job/step, given it depends on another one that last failed

## Actual Results
Concourse ran the newly added job/step.

## Additional Context
N/A

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Docker (via the docker compose provided in the quick start guide on the official documentation)
* Infrastructure/IaaS: N/A
* Browser (if applicable): N/A
* Did this used to work? N/A
