### ISSUE TITLE
"inputs passed" should be configurable to be OR rather than AND

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse#313]
I have a job that I want to trigger on the passing of either of a pair of other jobs.

I can have the job require a resource that has passed BOTH of the jobs, but I want some way of saying the job should trigger if EITHER of the other jobs have passed.

**Comment by vito** [comment]
This came up a while back in Slack; one interesting idea was to make the resulting dependency nodes a first-class concept called "buckets". Buckets would behave the same as resources, but their entries would be explicitly populated, rather than detected via `/check`, and they could even hold different types of resources (so long as they all have the same filesystem interface).

The following would model a bucket that represents the union of two resources:

```yaml
resources:
- name: some-repo
  type: git
  
- name: some-repo-prs
  type: pr

buckets:
- name: commits
  sources:
  - resource: some-repo
  - resource: some-repo-prs

jobs:
- name: unit
  plan:
  - get: commits
```

The following would model a bucket that represents resources having passed either job `a` or `b` (this issue):

```yaml
resources:
- name: some-repo
  type: git

buckets:
- name: commits-from-a-or-b
  sources:
  - resource: some-repo
    passed: [a]
  - resource: some-repo
    passed: [b]

jobs:
- name: a
  plan:
  - get: some-repo

- name: b
  plan:
  - get: some-repo
```

Today's semantics of adding `passed` constraints on `get` steps would be effectively syntax sugar on top of these buckets.
