### ISSUE TITLE
Git resource does not start pipeline

### ISSUE THREAD

**Issue by bs76** [concourse/concourse#3156]
## Bug Report

Checking GitHub git repo gets new hash commits, does not start pipeline.

Git resource checks remote git repository, displays new commit hash in UI. That new fetched version does not kick off the jobs listening to the resource changes. Pipeline will not start.

## Steps to Reproduce

K8s + helm concourse chart, concourse 4.2.2. 
Have a git repository in github:
- commit to git
- see the last change picked up
- wait for pipeline to start -- it does not.

All misbehaving pipelines  behaved as expected before Sat. Pipelines worked fine last week.

Downgrade to git resource 1.0 explicitly using
```
- name: git 
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: 1.0.0
```
behaves as it should

All the councourse-worker as well as concourse-web pods had been restarted, the issue went away in some instances, but we have other (less frequently run) pipelines where the behaviour persists.

## Expected Results

commit to git triggers pipeline

## Actual Results

the new hash is displayed in UI,  pipelines stalled

## Additional Context

Kubernetes deployment

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS: GCP
* Browser (if applicable):
* Did this used to work? Absolutely, till Saturday 28th Jan 2019

**Comment by vito** [comment]
Could you provide a simpler reproduction case? For example a full pipeline that demonstrates the issue? e.g. right now I can't even tell if this is a simple case of not having `trigger: true` configured.

If there aren't simple steps to reproduce, this may be better to debug via the [support forums](https://discuss.concourse-ci.org) instead.

**Comment by bs76** [comment]
Here is part of the pipeline that did not work.
```yaml

resources:
- name: screening
  type: git
  source:
    uri: git@github.com:xrepo/screening.git
    private_key: ((xrepo-github-key))
    branch: ((branch))

- name: client
  type: git
  source:
    uri: git@github.com:xrepo/client.git
    private_key: ((xrepo-github-key))
    branch: ((branch))

- name: esm
  type: git
  source:
    uri: git@github.com:xrepo/external-services-mock.git
    private_key: ((xrepo-github-key))
    branch: develop

# Repository infra provides helper scripts. New commits to the repo never trigger
# a new build.
- name: infra
  type: git
  source:
    uri: git@github.com:xrepo/infra.git
    private_key: ((xrepo-github-key))
    branch: master

- name: locks
  type: pool
  source:
    uri: git@github.com:xrepo/infra.git
    branch: locks
    pool: merlon
    private_key: ((xrepo-github-key))

- name: test-env
  type: helm
  source:
    cluster_url: ((k8s-cluster-endpoint))
    cluster_ca: ((k8s-cluster-ca))
    namespace: test

- name: build-number
  type: semver
  source:
    driver: git
    uri: git@github.com:xrepo/infra.git
    branch: version
    file: version
    private_key: ((xrepo-github-key))

# Latest build manifest for the specified branch.
- name: manifest-branch
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    versioned_file: manifests/((branch))/latest.json

# Build manifests for the specified branch.
- name: manifest-build
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    regexp: manifests/((branch))/(\d+)\.json$

# Sub-repository manifest for screening.
- name: manifest-screening
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    versioned_file: _tmp/((branch))-screening.json

# Sub-repository manifest for client.
- name: manifest-client
  type: gcs-resource
  source:
    bucket: builds
    json_key: ((gcs-key))
    versioned_file: _tmp/((branch))-client.json

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-web-hook))

jobs:
- name: build-screening
  build_logs_to_retain: 100
  serial: true
  plan:
  - aggregate:
    - get: screening
      trigger: true
    - get: infra
  - do:
    - task: build-screening
      file: screening/ci/build.yaml
      privileged: true
    - put: locks
      params:
        claim: screening
    - do:
      - aggregate:
        - task: upload-coverage
          file: infra/pipelines/tasks/upload-artifacts.yaml
          input_mapping:
            artifacts: coverage
            target-path: screening
          params:
            BUCKET: builds/coverage
            TARGET_PATH_FILE: .git/ref
        - task: upload-artifacts
          file: infra/pipelines/tasks/upload-artifacts.yaml
          input_mapping:
            artifacts: tgz-artifacts
        - do:
          - task: filter-images
            file: infra/pipelines/tasks/filter-images.yaml
            input_mapping:
              repo: screening
          - task: build-images
            file: infra/pipelines/tasks/build-images.yaml
            privileged: true
            input_mapping:
              repo: screening
              docker-staging: missing-images
      ensure:
        put: locks
        params:
          release: locks
    - task: prepare-manifest
      file: infra/pipelines/tasks/prepare-manifest.yaml
      params:
        GIT_REPO: screening
        BRANCH: ((branch))
      input_mapping:
        repo: screening
    - put: manifest-screening
      params:
        file: ./manifest/manifest.json
    on_failure:
      do:
      - task: prepare-alert
        file: infra/pipelines/tasks/prepare-alert.yml
        input_mapping:
          repo1: screening
      - put: slack-alert
        params:
          icon_emoji: ':scream:'
          channel: '#build-investigations'
          channel_file: alert/channels
          text_file: alert/message
          always_notify: true
          text: |
            $TEXT_FILE_CONTENT
            *Build details:* <https://location/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.11.0-1

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
    tag: v0.3.0

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.4.2
    

```

Also pls check the attached screen capture: commits 49d432, 16736a0, e44200cdbe, 8ab2c7dd, 34a121 did not trigger the build

![cc_capture](https://user-images.githubusercontent.com/5235784/51906236-f5be6000-23c3-11e9-8292-c097a30d607b.png)
