### ISSUE TITLE
Support for custom resource in fly execute

### ISSUE THREAD

**Issue by tom-meyer** [concourse/concourse#318]
We just came across an issue when trying to `fly execute` where one of the inputs is a user-defined resource_type. Concourse gives us this for the output of the `get` for our custom git-lfs resource:

```
no workers satisfying: resource type 'git-lfs'

available workers:
  - platform 'linux'
  - platform 'linux'
  - platform 'linux'
  - platform 'linux'
```
Our custom resource is defined like this:
```
resource_types:
- name: git-lfs
  type: docker-image
  source:
    repository: "docker.ci.eng.pivotal.io:443/git-lfs-resource"
```

**Comment by muv** [comment]
+1 just got the same

**Comment by benmoss** [comment]
Yep, not clear how to make this work since this is specified in the pipeline.

**Comment by mtekel** [comment]
+1

**Comment by combor** [comment]
+1

**Comment by vito** [comment]
We had planned on getting to this "soon" at one point but a ton of more urgent things have come up. At this point it'd probably be quicker for someone to contribute this as a PR.

Here's what we were planning to do:

`fly execute -j` should support the custom resource types defined in the job's pipeline.

Let's have it so you can submit a build with a set of custom resource types. This command would then get the config for the pipelines, pluck off the custom resource types, and tack it onto the request body.

When creating a build, rather than just submitting a plan, a JSON payload like the following should be submitted:

```yaml
{
  "resource_types": [], # the resource types
  "plan": {} # the plan
}
```

Where `"plan"` is today's payload, and `"resource_types"` is a `atc.ResourceTypes`: https://github.com/concourse/atc/blob/master/config.go#L67

Should be relatively easy to add; all the internal bits in place, just gotta pass that slice around.
