### ISSUE TITLE
Custom resource with invalid configuration gets scan-resource into a loop

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3249]
## Bug Report

Providing a resource type configuration that can never work, `scan-resource` seems to get in a loop, taking with it a bunch of the resources of `web`.

## Steps to Reproduce

1. create a pipeline with a resource type that uses an invalid configuration

```yaml
resource_types:
- name: git
  type: registry-image
  source:
    repsitory: concourse/git-resource  # error: repsitory instead of repository

resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/concourse/concourse

jobs:
- name: foo
  plan:
  - get: concourse
```

2. set the pipeline and unpause;
3. (optionally) check the resource

## Expected Results

An error here or there from time to time popping out in the logs

## Actual Results

A *lot* of error logs and checks happening

## Version Info

* Concourse version: master a988db838444cc380b24fabb1d9eec9cc30a4c8d
* Deployment type (BOSH/Docker/binary): docker (local dev)
