### ISSUE TITLE
Fly doesn't report any errors when pipeline has passed resource loop.

### ISSUE THREAD

**Issue by kkitai** [concourse/concourse#3359]
## Bug Report

I'm using concourse v4.2.2 and I realized that fly-cli doesn't report any errors when do set-pipeline having passed resource loop like:                                                                    

```
jobs:
- name: job-1
  plan:
    - get: git-repo
      passed:
      - job-2
- name: job-2
  plan:
    - get: git-repo
      passed:
      - job-1
```

Then, look at web-ui, I can't see pipelines and so on.-
Moreover, pc's fan sounds noisily and browser is very heavy.
           
![image](https://user-images.githubusercontent.com/5709450/53153180-f92bbc80-35fa-11e9-8138-2cd6535f189c.png)
                                                                                   

full example pipeline [here(gist)](https://gist.github.com/kkitai/eb1223eb55e913ca56b57caa65ead3f0).

Passed loop case are not validated successfully?

## Expected Results

Fly would be provide loop passed definition, expects to prints errors like a following:
```
error: yaml: unmarshal errors:
  line 10: loop passed definition are detected. [job-1],[job-2]
```

## Actual Results

* "fly set-pipeline" was success.
* web-ui dashboard was down.
 
## Version Info

* Concourse version: v4.2.2
* Deployment type (BOSH/Docker/binary):  BOSH
* Infrastructure/IaaS: Openstack
* Browser (if applicable): Chrome
