### ISSUE TITLE
Freeze before PUT/build docker image

### ISSUE THREAD

**Issue by socek** [concourse/concourse#3362]
I have deployed Concourse IO using docker-compose. Everything worked good on local machine (Arch Linux), but on the destination server (CentOS 7) something is wrong, and the build freezes for some time.

![screenshot_2019-02-21 build backend 5 - concourse](https://user-images.githubusercontent.com/317401/53200601-36577500-3622-11e9-950e-abeb37d169be.png)
As you can see on the log, the time between one part and the second is about 40 minutes.

My question is: how can I debug if further? I can read the log on the worker, but I have no idea what to look for, so it will be very hard for me to find anything.

Standard data, pipeline:
```
resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: https://github.com/socek/cashcat.git
    username: {{gitUsername}}
    password: {{gitPassword}}
    branch: master
    file: backend/version
- name: cashcat-git
  type: git
  source:
    uri: https://github.com/socek/cashcat.git
    branch: versions
    username: {{gitUsername}}
    password: {{gitPassword}}
- name: cashcat-image
  type: docker-image
  source:
    email: ((dockerEmail))
    username: ((dockerUsername))
    password: ((dockerPassword))
    repository: socek/cashcat
- name: python-image
  type: docker-image
  source:
    repository: python
    tag: 3.7
jobs:
- name: Build Backend
  public: true
  plan:
  - get: cashcat-git
  - put: version
    params:
      bump: minor
  - get: python-image
    params:
      save: true
  - put: cashcat-image
    params:
      build: cashcat-git/backend
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          load_base: cashcat-image
          repository: socek/cashcat
      run:
        path: /bin/sh
        args: ['-c', 'export']
- name: Do Something
  plan:
  - get: cashcat-git
  - get: version
    passed: [Build Backend]
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: version
      run:
        path: /bin/cat
        args: ['version/number']
```

uname:
```
Linux tygrys 4.4.175-1.el7.elrepo.x86_64 #1 SMP Wed Feb 20 08:49:56 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

sha256 of the docker image:
```
sha256:652b3a898fd409fd814bc1671e383977ace633601277d2548854a22a42640b83
```

docker-compose.yaml
```
version: '3.3'

services:
  db:
    image: postgres
    env_file: env
    volumes:
    - pgdata:/database
    networks:
    - default

  web:
    image: concourse/concourse
    command: web
    volumes:
    - ./keys/web:/concourse-keys
    env_file: env
    networks:
    - default
    - apps

  worker:
    image: concourse/concourse
    command: worker --garden-dns-server 8.8.8.8 --garden-insecure-docker-registry registry-1.docker.io
    privileged: true
    volumes:
    - ./keys/worker:/concourse-keys
    env_file: env
    networks:
    - default

  worker2:
    image: concourse/concourse
    command: worker --garden-dns-server 8.8.8.8 --garden-insecure-docker-registry registry-1.docker.io
    privileged: true
    volumes:
    - ./keys/worker:/concourse-keys
    env_file: env
    networks:
    - default

volumes:
  pgdata:

networks:
  apps:
    external:
      name: apps
```
