### ISSUE TITLE
webhook_token does not work to trigger pipeline

### ISSUE THREAD

**Issue by jrobison-sb** [concourse/concourse#3411]
## Bug Report

I'm trying to create a pipeline which would be triggered via an incoming HTTP request to Concourse:

```
---
resources:
- name: my-repo
  type: git
  source:
    branch: master
    uri: git@github.com:...
    private_key: ((github_deploy_private_key))
  webhook_token: foobarbaz
  check_every: 24h

jobs:
- name: some-job
  plan:
  - get: my-repo
    trigger: true
```

After creating this pipeline, I can curl it using an HTTP GET request (`curl https://MYSERVER/api/v1/teams/main/pipelines/my-pipeline/resources/devops-repo/check/webhook?webhook_token=foobarbaz`), and I get `Method Not Allowed`. If I try curl'ing it with a POST request (`curl -X POST https://MYSERVER/api/v1/teams/main/pipelines/my-pipeline/resources/devops-repo/check/webhook?webhook_token=foobarbaz`), the HTTP request doesn't give me any error, but my pipeline also does not trigger.

## Steps to Reproduce

Create a pipeline with a resource similar to the above, which uses a webhook_token as part of a resource. Then curl the Concourse server as shown above to attempt to trigger the pipeline using the webhook.

## Expected Results

The pipeline should trigger via incoming webhook.

## Actual Results

It does not trigger.

## Additional Context

It's very possible that I'm just doing something wrong when trying to trigger this. But the only [documentation](https://concourse-ci.org/resources.html#resource-webhook-token) I found shows how to create the `webhook_token`, but not how to actually use it (via curl or similar). If I'm simply using this wrong, I'd be happy to get an example of how I should be curling it.

## Version Info

* Concourse version: 4.2.3
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS
* Browser (if applicable): curl
* Did this used to work? This is my first time trying to use webhook_tokens.
