### ISSUE TITLE
topgun/k8s: use of config file for main team roles configuration

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3423]
Hey,

With the new possibility of now configuring team auth for the `main` team through a configuration file, it'd be nice to have a test that ensures that:

- with a `ConfigMap` paired with the right file location under `concourse.web.auth.mainTeam.config` one can have the `main` team parameters configured.

For instance:

```yaml
roles:
- name: member
  local:
    users: ["local-user-previously-added"]
```
