### ISSUE TITLE
Wrong resource ref marked as successful input for a job

### ISSUE THREAD

**Issue by ripa1993** [concourse/concourse#3451]
## Bug Report

Discrepancy between the resource ref that has actually been used as input for a job and the ref concourse marks as used.

## Steps to Reproduce

Running this simple pipeline exposes the issue

```yaml
resources:
- name: 5m
  type: time
  source: {interval: 5m}
  check_every: 1m

- name: 1m
  type: time
  source: {interval: 1m}
  check_every: 1m

- name: bash-image
  type: docker-image
  source:
    repository: bash

jobs:

- name: manual
  plan:
  - aggregate:
    - get: 5m
    - get: 1m
    - get: bash-image
  - task: print
    image: bash-image
    config:
      platform: linux
      inputs:
        - name: 5m
        - name: 1m
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "Sleeping 300"
          sleep 300
          echo "5m: $(cat 5m/input)"
          echo "1m: $(cat 1m/input)"

- name: manual-passed
  plan:
  - aggregate:
    - get: 5m
      passed: [manual]
      trigger: true
    - get: 1m
      passed: [manual]
      trigger: true
    - get: bash-image
  - task: print
    image: bash-image
    config:
      platform: linux
      inputs:
        - name: 5m
        - name: 1m
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "5m: $(cat 5m/input)"
          echo "1m: $(cat 1m/input)"
```

Simply trigger `manual` job and wait termination.

## Expected Results

I expect the versions displayed in the two views to be the same, but actually they aren't

- http://${CONCOURSE}/teams/${TEAM_NAME}/pipelines/${PIPELINE_NAME}/jobs/manual/builds/1 (Fig A)
- http://${CONCOURSE}/teams/${TEAM_NAME}/pipelines/${PIPELINE_NAME}/jobs/manual (Fig B)

See the attached screenshot, the values `manual` job build 1 are different in the two views.

I expect the first from bottom resource (Fig C) to be marked as input for `manual` build 1 but instead the second from the bottom was marked.

## Actual Results

`manual` and `manual-passed` actually executed using two different version of the same resource, even though there was a "passed" dependecy between them.

This seems to be caused by the fact that new resource ref have been discovered during the execution of the job. The "real input" that was used by the `manual` job is not the resource ref that is marked as input for the job after the job has completed

## Attachments
Fig A
<img width="1680" alt="schermata 2019-03-08 alle 12 41 28" src="https://user-images.githubusercontent.com/5972762/54028792-83048980-41a6-11e9-986c-f0c055f08939.png">

Fig B
<img width="1680" alt="schermata 2019-03-08 alle 12 41 09" src="https://user-images.githubusercontent.com/5972762/54028814-94e62c80-41a6-11e9-837d-0f92b80d33e5.png">

Fig C
<img width="1680" alt="schermata 2019-03-08 alle 12 56 35" src="https://user-images.githubusercontent.com/5972762/54028821-9adc0d80-41a6-11e9-9370-1f9f71cc4204.png">

## Version Info

* Concourse version: 4.1.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: AWS EC2
* Browser (if applicable): Chrome
* Did this used to work? No idea
