### ISSUE TITLE
Add cwd option to run

### ISSUE THREAD

**Issue by ndarilek** [concourse/concourse#349]
I'd like to do something like:

```
  - task: getVersion
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: 14.04}
      run:
        path: git
        args: [describe --tags >version]
        cwd: myrepo
```

Not sure about that syntax but hope it conveys the idea. I have a ton of tasks that are either a line or two but need to be run in the git repository, and it'd be annoying to clutter the repo with a bunch of tiny shell scripts just to ensure that these commands are run in the right context.

Thanks.
