### ISSUE TITLE
Naming clash between resource_types and resource brings down concourse web

### ISSUE THREAD

**Issue by torarnv** [concourse/concourse#356]
```yml
resource_types:
- name: foo
  type: docker-image
  source:
    repository: ubuntu

resources:
- name: foo
  type: foo

jobs:
- name: oops
  plan:
  - get: foo
```

Starting the `oops` job results in `concourse web` going down with a `panic: member inserted twice: "oops:foo"` message.
