### ISSUE TITLE
Add an option to skip fetching the resource in get steps

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#3572]
## What challenge are you facing?
If a resource is used to trigger a job, Concourse will always run the `in` script and fetch the resource. This can lead to unnecessary work if I only care about the trigger event (e.g. notify me on slack every time someone commits to a repo). 

Note that by skipping the fetch script we would not have access to the metadata emitted by it. This means that while I can get notified on a new commit, the only thing I will know about is the version (commit hash) and things like commiter, commit message, etc will not be available.

## What would make this better?
Add an option in the pipeline yaml to indicate that a `get` step is only used as a trigger and can skip fetch the resource

```
plan:
- get: some-repo-that-takes-forever-to-clone
  trigger: true
  trigger-only: true

- put: notify-slack
  ....
```

## Are you interested in implementing this yourself?
Sure, freedom fridays
