### ISSUE TITLE
Spike: can we transition the `time` resource to an inbound notification that triggers connected jobs when it fires?

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3595]
Related: concourse/rfcs#10, #3585 

Previously we've thought of notifications as purely outbound, but in light of the pain of 'resource scopes' (and how it will be exacerbated by 'spaces'), can we remodel the `time` resource as an inbound notification for triggering jobs? This way we can eliminate `unique_version_history` and resource scopes without any hacky business.

**Comment by vito** [comment]
### Notes from the mini-inception/meeting

Example of a pipeline with a timed trigger:

```yaml
resources:
- name: some-repo
  type: git
  source: # ...

notifications:
- name: periodic
  type: time
  config: {interval: 10m}

jobs:
- name: run-tests-periodically
  potato:
  - periodic
  plan:
  - get: some-repo
    trigger: true
```

How this works:

* A long-running process for `periodic` handles and emits events.

Inbound events:

* build created
* build started
* build finished
* webook payload

Outbound events:

* create build of job X

The `time` notification resource would handle build state events to determine whether to emit a new 'create build' event, based on the time that the build was created (or finished?).

A `github-pr` notification resource would make use of webhooks to create builds, and would make use of the build status events to update the pull request state on GitHub.

Events would be recorded in the database and processed like a queue. Events coming from Concourse would be fed to the notification resource. Events coming from the resource would be processed and used to trigger builds. Those builds could also be associated to the event that triggered them, to support things like #2752 (we would extend this to 'manual triggers' - they would just be another type of event).

We're planning to start by implementing the `time` notification "resource" in-process so we can get quick feedback on the interface in lieu of fleshing out an entire RFC. This would also allow people to start transitioning to this new flow more quickly.

These notification resources would be modeled as a long-running process, and they would be fed all events that ahve not yet been processed. Outbound events would similarly be processed like a queue, and we would be sure not to double-queue pending builds.
