### ISSUE TITLE
Having team / tagged workers, scheduling feedback doesn't direct the user to team/tag constraints

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3614]
Hey, 

I was wondering whether it'd be interesting for users to have a more accurate description of what's making them have their workloads not schedulable due to constraints when using `team` and `tag`s.

Here's an example:

Having a deployment where we *only* have `tag`ged workers

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 1e81ab6b1..14247fc8b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -40,6 +40,8 @@ services:
     - 7788:7788
     stop_signal: SIGUSR2
     environment:
+      CONCOURSE_TAG: a
+
       CONCOURSE_LOG_LEVEL: debug
       CONCOURSE_TSA_HOST: web:2222
```

```sh
fly -t local workers --json | jq  -c '.[] | {name: .name, tags: .tags, platform: .platform}'
{"name":"4b836a9fa0c3","tags":["a"],"platform":"linux"}
```

and a pipeline that has everything tagged except a task

```yaml
resources:
  - name: image
    type: time
    tags: [ a ]
    source:
      repository: busybox

jobs:
  - name: job
    plan:
      - get: image
        tags: [ a ] 
      - task: something
        image: image
        config:
          platform: linux
          run:
            path: true
```

we end up with the following error when it reaches the `task` step:

```sh
no workers satisfying: platform 'linux'
```

Naturally, adding a `tags` step modifier to the `task` makes it work without problems, but it might not be very immediate for a user that that's the issue.

Now, if we remove the `tags` modified from the `get` step:

```sh
no workers satisfying: resource type 'registry-image'
```

---

I can totally see that for the scheduler, within the pool of possible workers to pick from (those that are tagged), no workers match the `platform: linux` constraint, but there might be an opportunity for us to be more helpful by also letting the user know that the pool of workers that is being considered is the one that only includes the tagged workers.

Do you think that makes sense?

Thanks!
