### ISSUE TITLE
Feature req.: HTML and graphics in task output in web UI

### ISSUE THREAD

**Issue by mtekel** [concourse/concourse#365]
Hi,

do you have any plans for supporting more fancy task output formats? Currently console displays text, colors and can even do **bold**. What about supporting HTML (e.g. for a task that outputs some HTML formatted table). Or what about pictures? E.g. a task outputs some graph (...from a perf test).

I understand that `fly intercept` should also be able to show the output, but I'd say that in that case it's ok to show raw HTML or binary picture data - as the users control their task outputs and they can chose not to create such output that's not easily viewable by `fly intercept`...

**Comment by jonrob** [comment]
I would also like a way to expose different kinds of outputs, although I'm not sure if I'd want it embedded in job/task output, just a link to make it easy to get to the output, or perhaps a more general purpose 'project dashboard' that tracked artefact results etc (eg test coverage) over time/builds.

**Comment by metatype** [comment]
Would be awesome to support JUnit test output from gradle natively.  Currently we upload the html output from tests to an S3 bucket and configure as a static website.

**Comment by pms1969** [comment]
:+1:  for this feature.  

I'd be happy enough with a way of making a resource have a link to the desired output.  I was thinking that this might be implemented by having a convention for the output.  you already accept version, and that contains certain key-value pairs, so a key named `link` would mean that it gets displayed as an html anchor - like `<a href="{{.version.value}}">{{.version.value}}</a>` 

(forgive my clumsiness, I'm not that familiar with how concourse does this stuff, so it's just a sad attempt)

**Comment by airtonix** [comment]
exposing a web-socket into each task container that accepts html would allow us to stream formatted information throughout the life-cycle of a task container.

```yml
- task: foo
  config:
    platform: linux
    type: docker-image
      repository: node:6-alpine
    inputs:
      - repo
    outputs:
      - build
    run:
      path: /usr/bin/node
      args: -e |
        var WebSocket = require('some-websocket-client');
        var SomeReportGenerator = require('some-report-generator');
        const {CONCOURSE_REPORTER, CONCOURSE_BUILD_ID} = process.env;
        const ws = new WebSocket(`ws://${CONCOURSE_REPORTER}:1234/build/${CONCOURSE_BUILD_ID}`, 'echo-protocol');
        ws.send(SomeReportGenerator.render({foo: bar});        
```

But having contemplated that, it could just be a resource-container that talks to the current job websocket.

```yml
jobs:
  - get: repo
  - task: code-coverage
     file: repo/ci/code-coverage.yml
  - put: concourse-build-reporter
    params:
      file: build/reports/code-coverage.html
  - task: compile-code
    file: repo/ci/compile.yml 
  - put: concourse-build-reporter
     file: build/reports/build-states.html
  - put: deploy
```
