### ISSUE TITLE
Tags on job and pipeline level

### ISSUE THREAD

**Issue by loewenstein** [concourse/concourse#371]
We want to run the openstack cpi pipelines against different versions of OpenStack. We have an OpenStack Liberty installation in a private network and already setup a worker there.

Unfortunately tags only apply to individual steps.

We would like to tag an entire pipeline instead of tagging each and every step in our pipeline.

**Comment by gaelL** [comment]
Additionally to that, it would be really great to be also able to force it on team level.

We have different team like QA, DEV, PROD, ... with dedicated workers for them.

Currently the dev team can tag pipelines with prod tags and end up on prod workers. Which is a problem.
It would be great to force it at team level to be sure everything in dev team stay on dev workers only.

**Comment by taylorsilva** [comment]
I think we can make tagging easier to do. Right now it is annoying to tag each and every step. I think we should let users define `tags` at the `job` level and for the step wrappers: `do` and `in_parallel`. Defining `tags` at one of those levels would set it for all child steps. Child steps can override `tags` by defining their own `tags`.

```yaml
jobs:
- name: my-job
  tags: ["some-tag"]
  plan:
    - ... # a bunch of steps that are automatically tagged with "some-tag"
```

or
```yaml
jobs:
- name: my-job
  plan:
    - tags: ["some-tag"]
      in_parallel: # these get steps are tagged
        - get: ...
        - get: ...
        - get: ...
    - task: ... # this is not tagged
```

Going to start working on this.
