### ISSUE TITLE
Fly anchors don't work in 5.0.1 for variables

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#3714]
## Bug Report

Pipelines that have properties set within the pipeline are no longer usable as anchors

## Steps to Reproduce

pipeline.yml:
```
resources:
  - name: ref-app
    type: git
    check_every: 60m
    source:
      <<: *resource-params

jobs:
- name: test
  interruptible: true
  build_logs_to_retain: 20
  serial: true
  plan:
  - get: ref-app

resource-params: &resource-params
      branch: feature/ref-app-test
      uri: ssh://git@stash.com/project/repo.git
      private_key: ((vault-capability-repo-private-key))
```

## Expected Results

pipeline to be set

## Actual Results

```
bash-4.3# fly sp -p a -c pipeline.yml
error: yaml: unknown anchor 'resource-params' referenced

```
## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack/vSphere
* Did this used to work? Yes, in 3.13
