### ISSUE TITLE
Continuously test `quickstart`

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3774]
## What challenge are you facing?

Having `concourse quickstart` advertised as the quick way of getting Concourse up, this ends up being the first interaction that new users have with it, thus, making sure that it works is essential to ensure that we don't break the expectations right away (e.g., see https://github.com/concourse/concourse/issues/3758).

In the past, we used to have such code tested in our CI - https://github.com/concourse/pipelines/blob/9801dac567cbeeb5bfbc82af483a3193403dd54c/ci.concourse-ci.org/concourse.yml#L954-L958 - although maybe more than enough (there's probably no need to run the entire `testflight` suite). 

## What would make this better?

Have in our test pipeline a job that verifies that `concourse quickstart` can do the very minimal of at least getting up and running - perhaps, `smoke` against `quickstart` is enough.

Thanks!

**Comment by vito** [comment]
@cirocosta Where do you think we should prioritise this? Maybe TP backlog? :thinking:

**Comment by cirocosta** [comment]
yeppp, sounds about right in the priorities of keeping Concourse shippable 👍

**Comment by scottietremendous** [comment]
@vito - Wondering if we should make this more discoverable seeing as we're investing in it.

**Comment by vito** [comment]
@scottietremendous Not sure what you mean - like move it to another project?

**Comment by cirocosta** [comment]
@vito IIRC, it was brought up during IPM that we were not using `concourse quickstart` in `concourse-ci.org`, but that's not the case:

```
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart      # <<<<<<<
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
```
