### ISSUE TITLE
Regression with resource names: forward slashes in name break webui in >4.2.2

### ISSUE THREAD

**Issue by tanner-bruce** [concourse/concourse#3787]
## Bug Report

Post 4.2.2 resource names with forward slashes break the web ui. It was noted in #751 after the ticket was closed, but was never addressed so I am opening a new issue. This worked up fine until 4.2.2

## Steps to Reproduce

```
resources:
   - name: tanner-bruce/redis_killer.git@master
      source:
        branch: master
        uri: git@github.com:tanner-bruce/redis_killer.git
      type: git
```
## Expected Results

I should be able to view the info page for that resource

## Actual Results

The page briefly displays and then 404's

## Additional Context

This worked fine up until 4.2.2. We found it when upgrading to 5.x

## Version Info

* Concourse version: 5.0.1
* Deployment type (BOSH/Docker/binary): k8s
* Infrastructure/IaaS: k8s
* Browser (if applicable): Chrome
* Did this used to work? yes
