### ISSUE TITLE
feature request: support credential interpolation with concourse configured credential management

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse#3802]
## What challenge are you facing?

We have been developing a "tasks as a service" solution for some customers.
These tasks take inputs (mostly YAML files), which can contain credentials.
To be better citizens, we'd like to separate the configuration file from the credentials.

Concourse has native integration with several credential management systems.
We'd like to use concourse's integration to interpolate the config files.
This would allow input artifacts to have access to credentials.

We've attempted two solutions thus far:

1. Creating a task that connects credential server and interpolates the YAML. This is where the [`credhub interpolate`](https://github.com/cloudfoundry-incubator/credhub-cli/blob/master/commands/interpolate.go) command came from.
2. Pass every credential directly in as a `param` (environment variable) into the task.

Some long term issues.

With [1], we were successful, but now getting requests for `vault` support. Which we may not be able to replicate.
With [2], we can support, but every time everyone adds a credential, they have to add it to the cred server, the pipeline as a `param`, (if they're good ci-tizens) the task YAML, and a YAML config file to reference. We've learned that this causes configuration _drift_.

## What would make this better?

We'd like to utilize concourse's native cred management system.
As of recently, it has support evaluating a `task` YAML file,
can we use this same mechanism for `inputs` that have YAML files?

## Are you interested in implementing this yourself?

Sure-ish.

**Comment by osis** [comment]
Hey @jtarchie, thanks for the thought.

Question: Can you not create config file with the ('s and leave Concourse to interpolate?

**Comment by jtarchie** [comment]
@osis, I am not aware of any native interpolation beyond `fly set-pipeline` at the moment.

These config files come external resources, they are not defined inline with the pipeline YAML.

An example of the current workflow is,

Given a `config.yml` in an accessible `git` repo:

```yaml
secret: ((password))
```

Given a pipeline:

```yaml
resources:
- name: config-git
  type: git
  source:
    uri: ((git_url))
jobs:
- name: test
  plan:
  - get: config-git
  - task: bosh-interpolate-config
    params:
      # this reads the secrets directly from concourse integration
      # so it can support vault, aws, k8s, etc.
      SOME_PREFIX_PASSWORD: ((password))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bosh # this is pretending there is a image with bosh cli
      inputs:
      - name: config-git
      run:
        path: bash
        args:
        - -c
        - |
          cat config-git/config.yml
          bosh interpolate config-fit/config.yml --vars-env SOME_PREFIX

  - task: credhub-interpolate-config
    params:
      CREDHUB_USERNAME: ((credhub-username))
      CREDHUB_PASSWORD: ((credhub-password))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: credhub-cli # this is pretending there is a image with credhub-cli
      inputs:
      - name: config-git
      run:
        path: bash
        args:
        - -c
        - |
          cat config-git/config.yml
          # this is reading directly from credhub, based on the username/password
          # passed directly into the task, but this only supports credhub
          credhub interpolate config-fit/config.yml
```


These are solutions. I believe we can streamline and consolidate already built functionality.

Having concourse evaluate the `inputs` for the YAML files means we wouldn't have to pass in `params` or invent a new `interpolate`.
