### ISSUE TITLE
Configurable ceiling for how long containers can still be intercepted / hijacked

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3892]
## What challenge are you facing?

Containers hang around for a very long time after the build that they're related to fail.

Even though we only keep the last failed build as "interceptible" as `builds.interceptible` ends up being used as a check when determining whether the container should be marked for destruction or not, in some cases (where many many many containers are created per-build and builds are not often), the number of containers hanging around can become a problem as the number of containers that a worker has is a limiting resource.

E.g., consider `strabo` whose builds happen infrequently but, when they happen, they create a bunch of containers:

![idle-containers](https://user-images.githubusercontent.com/3574444/58103887-c5d4db80-7bb1-11e9-8250-92a96752fba2.png)
  

## What would make this better?

Possibly having a collector that would mark builds as non-interceptible after a configurable amount of time  🤔 

Thanks!

**Comment by cirocosta** [comment]
Hey,

Another reason for getting rid of those containers after a given amount of time
is that in those cases where the main process spawns other processes and they
keep around consuming resources:

![container-still-around](https://user-images.githubusercontent.com/3574444/61079854-be7fc080-a3f1-11e9-9c6d-416c18838f1a.png)

For instance, consider the following pipeline:

```yaml
jobs:
- name: test
  plan:
  - task: run
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: ubuntu }
      run:
        path: /bin/bash
        args:
        - -cex
        - |
          # install `stress`
          apt update && apt install -y stress

          # daemonize an instance of `stress` that keeps a cpu spinning
          # indefinitely
          nohup stress --cpu 1 &
          sleep 1

          # make the task fail so that we see the container being around
          false
```

We've seen this in [hush-house](https://github.com/concourse/hush-house) where
folks who daemonize processes have them running around for a long time (for
jobs that don't run that often).

Thanks!
