### ISSUE TITLE
Build stuck at pending state when preparation endpoint returns all not_blocking

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#3904]
## Bug Report

If a check fails due to an external reason (e.g. the s3 bucket it was checking is gone/down) then any builds that are pending will get stuck in the pending state. These pending builds will not show why they are stuck pending though and can't be aborted as per #3900 
![Screen Shot 2019-05-22 at 3 37 44 PM](https://user-images.githubusercontent.com/4583837/58203677-b3899900-7ca8-11e9-97e7-2b37701577da.png)
GET request to `http://localhost:8080/api/v1/builds/14/preparation` returns:
```json
{
   "build_id":14,
   "paused_pipeline":"not_blocking",
   "paused_job":"not_blocking",
   "max_running_builds":"not_blocking",
   "inputs":{
      "release":"not_blocking"
   },
   "inputs_satisfied":"not_blocking",
   "missing_input_reasons":{

   }
}
```

## Steps to Reproduce
Append the following to the concourse [docker-compose.yml](https://github.com/concourse/concourse/blob/master/docker-compose.yml):
```yaml
  gitweb:
    image: emarcs/nginx-git
    ports:
      - '8081:80'
    volumes:
      - '/Users/pivotal/workspace/concourse/repositories:/srv/git'
      - './htpasswd:/srv/htpasswd'
    environment:
      GIT_POSTBUFFER: 1048576
```
Then run:
```bash
htpasswd -c htpasswd admin
# will prompt you for password, enter 'admin'
docker-compose up
```
This will create a `repositories` folder at the same location as your `docker-compose.yml` file. Run the following commands to make a repo that the http-git-server can serve:
```bash
cd repositories/
git init --bare myrepo.git
```

Next, set this pipeline.yml:

```yaml
resources:
  - name: release
    type: git
    source:
      uri: http://gitweb:80/myrepo.git
      username: admin
      password: admin

jobs:
- name: test
  plan:
    - get: release
```
Now trigger the job. Once it succeeds delete the git repo you made:

```
cd repositories/
rm -rf myrepo/*
``` 
Now resource check should fail. Trigger the job now and you'll see it get stuck in the pending state but it doesn't tell you that it's pending because of the failed resource.
Failed resource with a previous good version:
![Screen Shot 2019-05-22 at 3 37 24 PM](https://user-images.githubusercontent.com/4583837/58204452-4d9e1100-7caa-11e9-8f89-5fe50b3132c3.png)

## Expected Results

Pending job should say it's waiting to do a resource check.

## Actual Results

Pending job shows all constraints passed.

## Version Info

* Concourse version: 5.2.0
* Did this used to work? maybe regression? not sure...
