### ISSUE TITLE
Specified version on github-release-resource not detected by job

### ISSUE THREAD

**Issue by o-orand** [concourse/concourse#3990]
## Bug Report
Using a specified version with github-release-resource is not working. Versions specified either by pinned-version or by get-step are not detected by related jobs. See below

* Pinned version:
```
vault-config-pinned
tag	v1.1.4
checking successfully
    id	16742082
    tag	v1.1.4
    timestamp	2019-04-13T10:29:14Z
```
Output after manual trigger: 
```
waiting for a suitable set of input versions
    vault-config-pinned - no versions available
```
* Get step:
```
vault-using-get-version
checking successfully

    id	16742082
    tag	v1.1.4
    timestamp	2019-04-13T10:29:14Z
```
Output after manual trigger: 
```
waiting for a suitable set of input versions
    vault-using-get-version - pinned version {"tag":"v1.1.4"} is not available
```

## Steps to Reproduce
Use the pipeline below based on latest vault github release:  https://gist.github.com/o-orand/f04815c573f82360d271233809b03a51
It may be relevant to use a previous version of vault boshrelease to avoid latest auto-detection, but it requires to add a `check-resource`

## Expected Results

Concourse detects specified version, and build triggers

## Actual Results

No version detected

## Version Info

* Concourse version: 5.2
* Deployment type (BOSH/Docker/binary): Bosh
* Infrastructure/IaaS: Openstack
* Browser (if applicable):
* Did this used to work? yes, like a charm in 3.14.1

**Comment by vito** [comment]
The version specifiers are currently *exact* matches, so you'll need to include the other fields as well:

```yaml
version:
  id: 16742082
  tag: v1.1.4
  timestamp: 2019-04-13T10:29:14Z
```

Pretty annoying UX though. Maybe #3932 could be applied here too? 🤔

**Comment by o-orand** [comment]
Thanks @vito, specifing all fields works for `vault-config-pinned` resource, but the `get` step doesn't detect the version :cry:. Using the snippet bellow:

```
- name: get-step-version-no-detected-BUG
  serial: true
  plan:
    - get: vault-using-get-version
      trigger: true
      version:
        tag: "v1.1.4"
        id: 16742082
        timestamp: 2019-04-13T10:29:14Z
```
is still getting:
```
waiting for a suitable set of input versions
    vault-using-get-version - pinned version {"tag":"v1.1.4","timestamp":"2019-04-13T10:29:14Z"} is not available
```

It could be great, to be able to apply #3932 in this case, it will lead to a better UX, IMO.

**Comment by thelangley** [comment]
Using concourse 5.3.0. This is impacting our env as we pin regularly to ensure consistency. We've had to unpin and use tag_filters which is ok for tagged resources

Suggest original tagging of "bug" is maintained.

**Comment by vito** [comment]
@o-orand Another thing to try: it may be failing because some of those fields are integers, not strings, and versions always have string values. If you explicitly quote them and provide all three exact version fields, is it able to match?

```yaml
version:
  id: "16742082"
  tag: v1.1.4
  timestamp: 2019-04-13T10:29:14Z
```

@thelangley Concourse has never supported partial field matching for version pinning. Adding support for it would fix the issue, while adding a feature. These labels are primarily to communicate to the engineers who pick up the GitHub issue from the backlog, and also to make it easier to notice that an actual feature was added when it comes time to write the release notes.

**Comment by o-orand** [comment]
@vito Thanks adding quote is working. 
To sum up, inside a get step, something like this is required:
```
- name: get-step-version
  serial: true
  plan:
    - get: vault-using-get-version
      trigger: true
      version:
        tag: "v1.1.4"
        id: "16742082"
        timestamp: "2019-04-13T10:29:14Z"
```
but quotes are not required at resource version:
```
- name: vault-config-pinned
  icon: github
  type: github-release
  source:
    repository: vault-boshrelease
    user: cloudfoundry-community
  version:
    tag: v1.1.4
    id: 16742082
    timestamp: 2019-04-13T10:29:14Z
```

It could be nice to have a consistent behavior :smile:
