### ISSUE TITLE
Unable to auth via Github personal

### ISSUE THREAD

**Issue by chrisduong** [concourse/concourse#4002]
## Bug Report

After a successful login on Github, Github return 404 page.

## Steps to Reproduce

1. Setting Github OAuth following this direction - [Github Auth](https://concourse-ci.org/github-auth.html)

2. Create OAuth App under Github personal account.

3. Click 'Login' on Web GUI with Github.

## Expected Results

Successful login into Web GUI, and belong to main Team.

## Actual Results

Return **404 Github Page**: https://github.com/login/oauth/authorize?client_id=xxxxxxxxxxx%0A&response_type=code&scope=user%3Aemail+read%3Aorg&state=xxxxxxxxxxx

## Additional Context

I'm using Helm chart _stable/concourse_ version `6.2.1` with this Value file, shown only Github Authentication part

```yaml
concourse:
  web:
    # Authentication
    auth:
      mainTeam:
        ## Configuration file for specifying team params.
        ## Ref: https://concourse-ci.org/managing-teams.html#setting-roles
        ##
        config:

        ## List of local Concourse users to be included as members of the `main` team.
        ## Make sure you have local users support enabled (`concourse.web.localAuth.enabled`) and
        ## that the users were added (`local-users` secret).
        ##
        localUser: "concourse"

        github:
          user: chrisduong # My personal Github account

      ## Authentication (GitHub)
      ##
      github:
        enabled: true
```

- GitHub Client Key and Github Client Secrets had been uploaded outside of Helm values. And they are correct.
- Callback URL: https://my-server/sky/issuer/callback
- I had turn **DEBUG** log on Web  but there was no ERROR. 
- I can login normally for my own local user.

## Version Info

* Concourse version: **5.2.0**
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): Safari, Chrome
* Did this used to work? First time I tried concourse.
