### ISSUE TITLE
User connecting through Generic OAuth when user does not have an email address

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#4003]
## Bug Report

Our service accounts don't typically have email addresses.

When I log on to Concourse using generic_oauth, with a user without an email address, we see in the logs:
1)  user is successfully logged in:
```
timestamp":"2019-06-12T09:21:19.256945060Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oauth\", username=\"\", email=\" (unverified)\", groups=[\"a\" \"b\" ]","session":"7"}}
```
2) a token can not be received
```
{"timestamp":"2019-06-12T09:21:19.275030676Z","level":"error","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","data":{"error":"Missing user id in verified claims","session":"6.26576"}}
```
I've looked to https://github.com/concourse/concourse/issues/2683 and when the user has an email address, this works perfectly.  I would like to change hte user-id to something that is common, say the user's 'preferred_name'

## Steps to Reproduce

Deploy concourse with BOSH
settings for generic oauth:

```
- type: replace
  path: /instance_groups/name=((deployment_name))-web/jobs/name=web/properties/generic_oauth?
  value:
    display_name: Ping
    client_id: ((generic_oath_client_id))
    client_secret: ((generic_oath_client_secret))
    auth_url: ((generic_oath_auth_url))
    token_url: ((generic_oath_token_url))
    scopes: ["openid profile email"]
    groups_key: "groups"
    userinfo_url: ((generic_oath_userinfo_url))
    user_id_key: "email"
```

I've attempted other user_id_key values such as preferred_name and others with no success

## Expected Results

User should be able to connect

## Actual Results

```
timestamp":"2019-06-12T09:21:19.256945060Z","level":"info","source":"atc","message":"atc.dex.event","data":{"fields":{},"message":"login successful: connector \"oauth\", username=\"\", email=\" (unverified)\", groups=[\"a\" \"b\" ]","session":"7"}}

{"timestamp":"2019-06-12T09:21:19.275030676Z","level":"error","source":"atc","message":"atc.sky.callback.failed-to-issue-concourse-token","data":{"error":"Missing user id in verified claims","session":"6.26576"}}
```

## Version Info

* Concourse version: 5.2.0
* Deployment type: BOSH
* Infrastructure/IaaS: Openstack and vSphere
* Did this used to work? Works in 3.13
