### ISSUE TITLE
no versions available after job triggered

### ISSUE THREAD

**Issue by mengxu2018** [concourse/concourse#4021]
below is the yaml file named with 2.yaml.
```
---
resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/ruanbekker/concourse-test
    branch: basic-helloworld

jobs:
- name: hello-world-job
  public: true
  plan:
  - get: my-git-repo
  - task: task_print-hello-world
    file: my-git-repo/ci/task-hello-world.yml
```

```
fly --target example login --team-name main --concourse-url  http://192.168.77.132:8080/ -u test -p test
fly -t example sp -c 2.yaml -p pipeline-01
fly -t example up -p pipeline-01
fly -t example tj -j pipeline-01/hello-world-job --watch

```
After run the job.
![image](https://user-images.githubusercontent.com/20497420/59577122-fa767d00-90f4-11e9-9983-9234ce6f6b8b.png)

I am new to concourse, I want to learn it, but I was stuck on the hello world job.
How to fix it ? thanks. I can see similar issues in github, but no useful information.

I am using the latest 5.3 version.

I also tried to run the https://concourse-ci.org/hello-world-example.html.
But it report below error.
runc run: exit status 1: container_linux.go:345: starting container process caused "process_linux.go:297: getting the final child's pid from pipe caused \"EOF\""
![image](https://user-images.githubusercontent.com/20497420/59577318-cea7c700-90f5-11e9-8495-b78899343fdb.png)
