### ISSUE TITLE
Git ssh key invalid format

### ISSUE THREAD

**Issue by MadHatter122312** [concourse/concourse#4029]
Based on the documentation in the tutorial, I am trying to setup a simple CI pipeline

In my pipeline.yml, I have:

```
---
resources:
   - name: my-resource
     type: git
     source:
      uri: git@git.mycompany.net:repo.git
       branch: master
       private_key: |-
         ----BEGIN RSA PRIVATE KEY----
           ssh-rsa <KEY>== email@company.com
         ----END RSA PRIVATE KEY----
 
 jobs:
   - name: sample-job
     public: true
     plan:
       - get: my-resource
       - task: ci-task
         file: ./ci-task.yml
```
 
 I have attempted to format this key many different ways, but I always get the error:
 
` Error loading key "/tmp/git-resource-private-key": invalid format`

Might it have an issue because this is a GitLab instead of GitHub?  This is proving quite difficult to debug.
