### ISSUE TITLE
When executing a task with non-root user, inputs should be owned by that user

### ISSUE THREAD

**Issue by jochenehret** [concourse/concourse#403]
We are using a Docker image with a non-root user (Dockerfile contains a "USER" command). All inputs (e.g. obtained by the git resource) are owned by root. Therefore, to make a commit we need to chown all files first. It seems like Concourse should do that for me when mounting the inputs.

**Comment by georgehaidar** [comment]
I am currently facing this problem as well and cannot, for example, run in `npm install` in my node project (the task input) as a non-root user.

**Comment by endzyme** [comment]
+1

**Comment by jpf91** [comment]
>  All inputs (e.g. obtained by the git resource) are owned by root. 

Outputs as well, unfortunately. So it's not possible to generate outputs either.

**Comment by miromode** [comment]
+1 for us as well - with all the root escape bugs docker has had up to very recently, I think this is extra important

**Comment by ashb** [comment]
@miromode the root-escape bugs in docker might not affect Concouse as it uses it's own container runtime (caled "garden") to run containers, not docker, so there's a chance that the same bugs won't exist here. (Or they could share the same code from libcontainer and might be vulnerable. I don't know at either way)

**Comment by wrl** [comment]
This is a hard requirement for building OpenWRT as well. We can hack around it by wrapping commands with `su` but it's a hack.

**Comment by duncanatkinson** [comment]
I have hit this issue trying to use [gradle image](https://hub.docker.com/_/gradle/) to build a gradle project, can work around it by specifying root, but I don't like being forced to do so. I think this is a bug, you have different behaviour when running gradle via docker 
`docker run --rm -v "$PWD":/project -w /project --name gradle gradle:alpine gradle <gradle-task>`
This is not consistent.

**Comment by fbiville** [comment]
I'm currently stuck with docker-node and this Concourse limitation.
Here is the Dockerfile:
```
FROM node:8.2
ENV NPM_CONFIG_LOGLEVEL warn
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN apt-get update && \
    apt-get install -y sudo && \
    adduser node sudo && \
    echo "node:supersecretpassword" | chpasswd && \
    chown root:root /usr/bin/sudo && chmod u+xs /usr/bin/sudo && \
    mkdir -p /usr/src/app
ADD mikado-web/web /usr/src/app/web
RUN chown node:node -R /usr/src/app

USER node
WORKDIR /usr/src/app/web

RUN npm install -g @angular/cli karma karma-phantomjs-launcher tslint && \
    npm install --quiet --no-progress && \
    npm cache clean --force

ENV PATH "$PATH:/home/node/.npm-global/bin"
```

Then write any Concourse task with something as simple as `sudo echo "hello"` based on this image. It will fail with:

```
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

I tried to make the `node` user a sudoer because Concourse would not allow a non-root user to write things in an output directory. I have tried other workarounds to achieve this, they all fail differently.

The only solution I have found is to duplicate the entire node image and remove the creation of the non-root user.

**Comment by fbiville** [comment]
Here is a dumbed-down version of the task that actually fails in our pipeline:

```
inputs:
outputs:
- name: output
platform: linux
image_resource:
  type: docker-image
  source:
    #see Dockerfile in previous comment
    repository: "xxx/my-custom-node-image-from-docker-registry"
    insecure_registries: ["xxx"]
run:
  path: /bin/bash
  args:
  - -c
  - |-
    cd output
    echo "supersecretpassword" | sudo -S touch file
```

**Comment by fbiville** [comment]
As discussed on Slack yesterday, I also tried setting a specific user in the task and I still get `Permission denied` error messages. This has been confirmed to be a bug by @jtarchie. 

```
inputs:
outputs:
- name: output
platform: linux
image_resource:
  type: docker-image
  source:
    #see Dockerfile in penultimate comment
    repository: "xxx/my-custom-node-image-from-docker-registry"
    insecure_registries: ["xxx"]
run:
  user: node
  path: /bin/bash
  args:
  - -c
  - |-
    cd output
    echo "supersecretpassword" | sudo -S touch file
```

**Comment by vito** [comment]
@fbiville Are you on v3.4.0? That's the version where we fixed setuid permissions, which should fix `sudo`.

You can also set `user` on a task, which will override the image's configuration: http://concourse.ci/running-tasks.html#task-run-user

**Comment by fbiville** [comment]
@vito touché, we're on `2.7.0`. I suppose this cannot be easily backported there? 😇

**Comment by lnhrdt** [comment]
In one of my pipelines I needed to run as a non-root user (to make ChromeDriver work properly) but also needed that non-root user to own the inputs and outputs so it could install dependencies, write files during tests, etc. If someday I could do:

```yaml
inputs:
- name: some-input
run:
  user: nonrootuser
  # ...
```

and have `some-input` owned by `nonrootuser`  that would simplify my pipelines (and I think be sensible default behavior generally). In the meantime, letting the user default to `root` (determined by my Docker image) and then using `chown` and `su` commands seems to be the cleanest solution. Here's an example in one of my pipelines in case it helps get someone going:
https://github.com/codebandits/twauth/blob/205adb5/pipeline/tasks/e2e.yml

**Comment by track0x1** [comment]
Hey folks, here's a solution I came up with to workaround in the meanwhile incase you want something that's reusable (this is specific to my nodeJS scenario... modify as needed):

_perm-patch.sh_
```sh
#!/bin/bash

# This script will "patch" an issue with Concourse (https://github.com/concourse/concourse/issues/403)
# where the resources provided to a job/task are owned by the `root` user. However, it is best to run NodeJS
# with a non-root user as there are issues where it will refuse to run lifecycle scripts like `pre` and `post`.

if [ -z "$1" ]; then
  echo ERROR: You must provide the script to run with permission-patch as a parameter.
  exit 1
fi

chown -R node:node /tmp/build

exec sudo -u node $1
```

_task.yml_
```yml
inputs:
  - name: ci-tasks

run:
  path: ./ci-tasks/perm-patch.sh
  args:
    - ./ci-tasks/tasks/install-version-publish.sh
```

This will run my actual task `install-version-publish` with the proper permissions. So I don't need to have logic for `chmod`ding or `sudo`ing all throughout my scripts. Then hopefully when this issue is addressed I can just remove the need to `perm-patch`.
