### ISSUE TITLE
Job hanging in Prepare state if pinned version is not fetchable

### ISSUE THREAD

**Issue by FloThinksPi** [concourse/concourse#4031]
## Bug Report

When defining a resource e.g. image-registry-resource and pinning it to a specific digest, we end up in an endless loop when this image cannot be pulled (registry down or image not found).

## Steps to Reproduce

1. Define Image-Resource that is pinned to a specific digest

```
name: hello-world
 type: registry-image
 version:
   digest: sha256:fce289e99eb9bca977dae136fbe2a82b6b7d4c372474c9235adc1741675f587e
 source:
   repository: hello-world
```

2. Block internet connection on worker to registry-1.docker.io (e.g. iptables)

3. Run the job, see it stalling at `waiting for version to be available`

4. Unblock registry-1.docker.io

## Expected Results

1. Concourse continues execution once the resource can be fetched and pulled.

2. Job can be canceled manually even if the prepare job is waiting for the registry to be available.

## Actual Results

1. The state will never recover, the prepare job will always stay on `waiting for version to be available` although the registry is reachable and other jobs work fine again. (tested for one day)
2. The job is also not cancelable manually and will hang forever.

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
