### ISSUE TITLE
Lost OIDC setting on main team, when web pod recreated

### ISSUE THREAD

**Issue by liuyuewen91** [concourse/concourse#4039]
## Bug Report

Lost OIDC setting of main team, when web pod recreated

## Steps to Reproduce

I have two teams setting: **main** and **shared**

#### Role setting
main_role.yaml: 

```yaml
roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["/ci/main/owner"]
- name: member
  oidc:
    groups: ["/ci/main/member"]
- name: pipeline-operator
  oidc:
    groups: ["/ci/main/pipeline-operator"]
- name: viewer
  oidc:
    groups: ["/ci/main/viewer"]
```

shared_role.yaml: 

```yaml
roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["/ci/shared/owner"]
- name: member
  oidc:
    groups: ["/ci/shared/member"]
- name: pipeline-operator
  oidc:
    groups: ["/ci/shared/pipeline-operator"]
- name: viewer
  oidc:
    groups: ["/ci/shared/viewer"]
```
#### Set up Role

```bash
TARGET=main
fly -t $TARGET set-team -n main -c main_role.yaml
fly -t $TARGET set-team -n shared -c shared_role.yaml
```
#### Check teams details
````
fly -t main teams --details
````
<pre><b>name/role</b>                  <b>users</b>            <b>groups</b>                                      
main/member                none             oidc:/ci/main/member              
main/owner                 local:admin      oidc:/ci/main/owner               
main/pipeline-operator     none             oidc:/ci/main/pipeline-operator   
main/viewer                none             oidc:/ci/main/viewer                       
shared/member              none             oidc:/ci/shared/member            
shared/owner               local:admin      oidc:/ci/shared/owner             
shared/pipeline-operator   none             oidc:/ci/shared/pipeline-operator 
shared/viewer              none             oidc:/ci/shared/viewer </pre>

## Expected Results

After web pod recreated, it should be

````
fly -t main teams --details
````
<pre><b>name/role</b>                  <b>users</b>            <b>groups</b>                                      
main/member                none             oidc:/ci/main/member              
main/owner                 local:admin      oidc:/ci/main/owner               
main/pipeline-operator     none             oidc:/ci/main/pipeline-operator   
main/viewer                none             oidc:/ci/main/viewer                       
shared/member              none             oidc:/ci/shared/member            
shared/owner               local:admin      oidc:/ci/shared/owner             
shared/pipeline-operator   none             oidc:/ci/shared/pipeline-operator 
shared/viewer              none             oidc:/ci/shared/viewer </pre>

## Actual Results
After web  pod recreated

````
fly -t main teams --details
````
<pre><b>name/role</b>                  <b>users</b>            <b>groups</b>                                      
main/owner                 local:admin      oidc:/ci/main/owner               
shared/member              none             oidc:/ci/shared/member            
shared/owner               local:admin      oidc:/ci/shared/owner             
shared/pipeline-operator   none             oidc:/ci/shared/pipeline-operator 
shared/viewer              none             oidc:/ci/shared/viewer </pre>

The main team has only owner role setting, other setting are lost. 

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: AWS K8s
* Browser: Chrome Version 75.0.3770.90 (Official Build) (64-bit)

**Comment by liuyuewen91** [comment]
This is because in helm  [concourse/templates/web-deployment.yaml](https://github.com/concourse/charts/blob/master/stable/concourse/templates/web-deployment.yaml
) , this env reset the main team setting, when web pod restarted or recreated.
``` yaml
{{- if .Values.concourse.web.auth.mainTeam.oidc.group }}
 - name: CONCOURSE_MAIN_TEAM_OIDC_GROUP
   value: {{ .Values.concourse.web.auth.mainTeam.oidc.group | quote }}
{{- end }}
```
The main/owner role was define by web web-deployment env. Other addition oidc setting are set up after concourse deployed through fly cli. 

### To fix this

1.   remove value of  `{{.Values.concourse.web.auth.mainTeam.oidc.group}}`.
2.    use helm upgrade, upgrade your  concourse.
