### ISSUE TITLE
Add ability to pause/resume all jobs within a pipeline

### ISSUE THREAD

**Issue by riker09** [concourse/concourse#4084]
## What challenge are you facing?

I have a pipeline that contains quite a few jobs in multiple groups. When I add or change a part in that pipeline (eg. a new task) I pause all other jobs but the one I'm working on to speed up getting a result.

```bash
fly -t my-target pause-job --job my-pipeline/my-job-a
fly -t my-target pause-job --job my-pipeline/my-job-b

# Repeat for 15-20 times with different and hard to memorate job names.
```

Now I know that I can pause an entire pipeline, but this is not what I need. I hope this is clear by the example above. 

## What would make this better?

```bash
# Pausing all jobs in a pipeline
fly -t my-target pause-job --pipeline my-pipeline

# Unpausing
fly -t my-target resume-job --pipeline my-pipeline
```

## Are you interested in implementing this yourself?

I don't believe I have the expertise to do this on my own. But if this proposal gets accepted because you think this is a great idea I would give it a shot.

## Additional thoughts

I can see that this could lead to some confusion. Maybe it could be implemented as switch in the `pause-pipeline` command instead? I would like to hear the thoughts of the developers first.

[Edit]
I'm not sure if ticket #1706 is talking about something similar.

**Comment by marco-m** [comment]
You can obtain this with fly and some minimal shell scripting. The trick is (1) to know that fly supports JSON output, so it is easily scriptable and (2) to know the power of `jq` https://stedolan.github.io/jq/ .

Consider this pipeline as an example

```
job: &job
  plan:
  - task: task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, world!"]

jobs:
- name: j1
  <<: *job
- name: j2
  <<: *job
- name: j3
  <<: *job
- name: j4
  <<: *job  
```

And assume we set it with name `foo`:

```
fly -t ci set-pipeline --pipeline foo -c foo.yml
```

Let's have a look at `fly jobs`:

```
fly -t ci jobs -p foo --json | jq '.[].name'
"j1"
"j2"
"j3"
"j4"
```

Let's get rid of the quotes `"`:

```
fly -t ci jobs -p foo --json | jq -r '.[].name'
j1
j2
j3
j4
```

We are ready to go! The example below is with the fish shell:

```
for j in (fly -t ci jobs -p foo --json | jq -r '.[].name')
    fly -t ci pause-job -j foo/$j
end

paused 'j1'
paused 'j2'
paused 'j3'
paused 'j4'
```

That's it! Then you unpause one-by-one the few jobs you want unpaused.

When done with the changes, we use almost the same to unpause all the jobs:

```
for j in (fly -t ci jobs -p foo --json | jq -r '.[].name')
    fly -t ci unpause-job -j foo/$j
end

unpaused 'j1'
unpaused 'j2'
unpaused 'j3'
unpaused 'j4'
```

The same with bash:

```
for j in $(fly -t ci jobs -p foo --json | jq -r '.[].name'); do
    fly -t ci pause-job -j foo/$j
done
```
