### ISSUE TITLE
Error: failed to interpolate task config: Finding variable 'test': AuthURL not found

### ISSUE THREAD

**Issue by vf-ford** [concourse/concourse#4093]
## Bug Report

On attempting to access a credhub contained value, get the error:
`failed to interpolate task config: Finding variable 'test': AuthURL not found`
Have verified that credhub functions outside of concourse with the credhub-api
Using the same url and port, and same credentials

## Steps to Reproduce

Run pipeline with interpolated variable
```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: [((test))]
```

## Expected Results

Pipeline completes

## Actual Results

failed to interpolate task config: Finding variable 'test': AuthURL not found

## Additional Context

Set credhub integration via

`-o concourse-bosh-deployment/cluster/operations/credhub.yml`
There are 2 CA's, one for UAA, one for API
Credhub is co-located on bosh director

## Version Info

* Concourse version: 5.3.0
* Credhub version: 2.4.0
* UAA version: 73.3.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? No
