### ISSUE TITLE
New 'check_every' value needs pipeline re-creation

### ISSUE THREAD

**Issue by propalparolnapervom** [concourse/concourse#4144]
## Bug Report

Concourse 5.3.0

I can see via `fly -t <target_name> gp -p <pipeline_name>` that new value of `check_every` applied successfully.
But in fact pipeline works with previous `check_every` value.
New value of `check_every` works only after pipeline re-creation.

## Steps to Reproduce

Create initial pipeline with `check_every` parameter:
```
- name: pr
  type: pull-request
  source:
    access_token: <access_token>
    repository: "<repository>"
  check_every: 1m
```
Make sure pipeline works with defined check time.
Update pipeline with new value of `check_every` parameter.
```
- name: pr
  type: pull-request
  source:
    access_token: <access_token>
    repository: "<repository>"
  check_every: 30s
```

## Expected Results

Pipeline checks resource with newly defined `check_every` parameter (`30s`).

## Actual Results

Pipeline checks resource with old `check_every` parameter (`1m`).
Thus, `fly -t <target_name> gp -p <pipeline_name>` shows new `check_every` parameter (`30s`).

Pipeline has to be re-created to start work as expected.

## Version Info

* Concourse version: 5.3.0
