### ISSUE TITLE
`fly execute` uploads current directory without inputs

### ISSUE THREAD

**Issue by zoetian** [concourse/concourse#4145]
## Bug Report

When running `fly -t target execute -c config-file`  command, it uploaded the current working directory before creating the build. This is not the expected behaviour for `fly`. 

## Steps to Reproduce

i.e. run `fly -t prod execute -c test.yml` 

example test.yml

```yaml
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/unit
run:
  path: find
  args: [ . ]
```

## Expected Results

When running the `fly` command without any inputs, the uploading of the current directory should not happen. If this is an intended feature, we should also expect users can pass in the "uploading directory" as an input parameter. 

In this case:
```
executing build 6568944 at https://ci.concourse-ci.org/builds/6568944
initializing
running find .
```

## Actual Results

it uploaded everything from local.

In this case:
```
uploading concourse-bosh-deployment done
executing build 6568944 at https://ci.concourse-ci.org/builds/6568944
initializing
running find .
```

## Version Info

* Concourse version: 5.4.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Did this used to work? I think so...
