### ISSUE TITLE
Do not show image_resource docker-image password in a task file

### ISSUE THREAD

**Issue by martinsbalodis** [concourse/concourse#415]
Right now tasks can only contain plain text passwords. That means that these passwords will be stored in a git repository in plain text. Here is how it the image resource definition looks right now in a task file:
```yml
# task.yml in repository
image_resource:
  type: docker-image
  source:
    repository: my.local.registry:8080/my/image
    insecure_registries: ["my.local.registry:8080"]
    username: myuser
    password: mypass
    email: x@x.com
```

This could be resolved by adding a `--load-vars-from=` option to the `fly execute` command similarly how it works with the `fly set-pipeline` command. The task definition could look like this after the enhancement:

```yml
# task.yml in repository
image_resource:
  type: docker-image
  source:
    repository: my.local.registry:8080/my/image
    insecure_registries: ["my.local.registry:8080"]
    username: {{docker_user}}
    password: {{docker_pass}}
    email: {{docker_mail}}
```

This would be partly resolved by #252. This proposal solves the problem when task is run within the CI but doesn't solve the problem when it is run via fly command locally.
