### ISSUE TITLE
Random DNS resolution issues on workers (5.4.0)

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#4153]
After upgrading to 5.4.0, it looks like our workers are seeing seemingly random DNS resolution failures.

14 minutes into the build (after downloading things successfully from a host), dns resolution randomly fails.

Here's an example:

```
Resolving package dependencies ...
--2019-07-23 18:38:54--  https://eu.hpkg.haiku-os.org/haikuports/master/build-packages//packages/groff-1.22.3-1-x86_64.hpkg
Resolving eu.hpkg.haiku-os.org (eu.hpkg.haiku-os.org)... 62.210.188.85
Connecting to eu.hpkg.haiku-os.org (eu.hpkg.haiku-os.org)|62.210.188.85|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7633254 (7.3M) [application/octet-stream]
Saving to: 'download/groff-1.22.3-1-x86_64.hpkg'

download/groff-1.22.3-1-x86_64.hpkg                                                                                          100%[==============================================================================================================================================================================================================================================================================================================================================>]   7.28M  6.30MB/s    in 1.2s    

2019-07-23 18:38:56 (6.30 MB/s) - 'download/groff-1.22.3-1-x86_64.hpkg' saved [7633254/7633254]

--2019-07-23 18:38:56--  https://eu.hpkg.haiku-os.org/haikuports/master/build-packages//packages/libiconv-1.15-4-x86_64.hpkg
Resolving eu.hpkg.haiku-os.org (eu.hpkg.haiku-os.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'eu.hpkg.haiku-os.org'

export imagePath="haiku.image"
export isImage="1"
export isVMwareImage=""
../haiku-git/build/scripts/build_haiku_image /tmp/build/e05da604/generated.x86_64/./haiku.image-init-vars /tmp/build/e05da604/generated.x86_64/./haiku.image-make-dirs /tmp/build/e05da604/generated.x86_64/./haiku.image-copy-files /tmp/build/e05da604/generated.x86_64/./haiku.image-extract-files

...failed BuildHaikuImage1 haiku.image ...
...removing haiku.image

BUILD FAILURE:
...failed updating 1 target(s)...
...skipped 1 target(s)...
...updated 14957 target(s)...
```

a wget works as expected, then 5 seconds later a wget from the same host fails to resolve.

**Comment by kallisti5** [comment]
Worker info:
Env:
CONCOURSE_WORK_DIR=/opt/concourse/worker
CONCOURSE_TSA_WORKER_PRIVATE_KEY=aprivatekey
CONCOURSE_TSA_PUBLIC_KEY=tsakey
CONCOURSE_TSA_HOST=ci.haiku-os.org:aport
CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8
CONCOURSE_GARDEN_DNS_PROXY_ENABLE=false

**Comment by kallisti5** [comment]
Worker is Fedora 30, selinux is disabled, 5.1.18-300.fc30.x86_64

**Comment by kcmannem** [comment]
known issue https://github.com/concourse/concourse/issues/4141

A temporary workaround is you can try setting this env var
`export GODEBUG=netdns=go`

**Comment by kwri-avongluck** [comment]
This applies to workers as well as fly?

**Comment by kallisti5** [comment]
This bug applies to workers (concourse worker) as well as fly?

**Comment by kcmannem** [comment]
It might as we introduced a new dependency that caused this issue. The side effect of this is that dns resolution changes. Setting an env var to test it shouldn’t hurt anyway. I just want to eliminate that it’s the same issue otherwise.

**Comment by kallisti5** [comment]
can-do. Will test

**Comment by kallisti5** [comment]
Added to worker and web (for good measure).  Testing now...
https://ci.haiku-os.org/teams/nightly/pipelines/master-x86_64/jobs/image-master-x86_64/builds/2

**Comment by kcmannem** [comment]
Looks like the job passes now? The failure seems to be something else.

**Comment by kallisti5** [comment]
Yeah, looks better.  I'm fixing that other error now and will rebuild for good measure.

**Comment by kallisti5** [comment]
Rebuild confirms dns resolution on workers is working as expected after adding ```GODEBUG=netdns=go``` to the worker and web instances of concourse.

**Comment by kallisti5** [comment]
actually, it just randomly happened again.

https://ci.haiku-os.org/teams/nightly/pipelines/master-x86_64/jobs/image-master-x86_64/builds/4

Is it possible this is an issue with runc / garden?  With the 5.4.0 upgrade, I also broke the worker out to a separate machine.

**Comment by vito** [comment]
Hmm, if this is happening within a build it should be unrelated to #1411 as the builds would be running their own code, not relying on the `concourse` binary's DNS stack.

To be honest I can't think of much in Concourse that would cause this kind of behavior. The only thing I can think of is to make sure your container network pool (default 10.254.0.0/22) doesn't overlap with any other addresses in your network.

Can you confirm that DNS resolution works reliably on the worker itself? Maybe just start a `while curl` loop or something on the worker VM and watch for it to eventually fail?

**Comment by kallisti5** [comment]
Ran this for a period of 4 hours:
```
while true; do date; curl https://eu.hpkg.haiku-os.org -o /dev/null -s -S; sleep 30; done >> nettest
```

no network / DNS resolution failures on the host running concourse. They only seem to occur within the runc containers.

As a side note, i've been seeing some other random failures as well.
  * Random worker disconnects during large jobs (sudden "no workers") warning in jobs about "no workers"
  * Random resource script failures:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31mERRO[0m[0001] failed to get cursor image digest: UNAUTHORIZED: "authentication required" 
```

I have no idea :-(   Host is healthy, no memory issues, no network issues, etc

**Comment by kallisti5** [comment]
For the stalled worker, no errors in worker logs. On web:
```
{"timestamp":"2019-07-24T20:10:01.142800425Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.heartbeat.start","data":{"command":"forward-worker","remote":"70.112.18.26:49270","session":"5.4.1.2507","worker-address":"127.0.0.1:45077","worker-platform":"linux","worker-tags":""}}
{"timestamp":"2019-07-24T20:10:18.913503945Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-volumes","data":{"command":"report-volumes","remote":"70.112.18.26:54566","session":"11316.1.1"}}
{"timestamp":"2019-07-24T20:10:20.256698742Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-volumes","data":{"command":"sweep-volumes","remote":"70.112.18.26:54570","session":"11317.1.1"}}
{"timestamp":"2019-07-24T20:10:29.776860942Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.heartbeat.done","data":{"command":"forward-worker","remote":"70.112.18.26:49270","session":"5.4.1.2507","worker-address":"127.0.0.1:45077","worker-platform":"linux","worker-tags":""}}
{"timestamp":"2019-07-24T20:10:30.084213279Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-containers","data":{"command":"report-containers","remote":"70.112.18.26:54568","session":"11315.1.1"}}
{"timestamp":"2019-07-24T20:10:31.413013320Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-containers","data":{"command":"sweep-containers","remote":"70.112.18.26:54572","session":"11318.1.1"}}
{"timestamp":"2019-07-24T20:10:48.873922545Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-volumes","data":{"command":"report-volumes","remote":"70.112.18.26:54748","session":"11320.1.1"}}
{"timestamp":"2019-07-24T20:10:48.909326990Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-containers","data":{"command":"report-containers","remote":"70.112.18.26:54750","session":"11319.1.1"}}
{"timestamp":"2019-07-24T20:10:50.181293951Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-volumes","data":{"command":"sweep-volumes","remote":"70.112.18.26:54752","session":"11321.1.1"}}
{"timestamp":"2019-07-24T20:10:50.211431067Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-containers","data":{"command":"sweep-containers","remote":"70.112.18.26:54754","session":"11322.1.1"}}
{"timestamp":"2019-07-24T20:10:59.777258487Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.heartbeat.start","data":{"command":"forward-worker","remote":"70.112.18.26:49270","session":"5.4.1.2508","worker-address":"127.0.0.1:45077","worker-platform":"linux","worker-tags":""}}
{"timestamp":"2019-07-24T20:11:18.877781494Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-containers","data":{"command":"report-containers","remote":"70.112.18.26:54764","session":"11323.1.1"}}
{"timestamp":"2019-07-24T20:11:18.885686049Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-volumes","data":{"command":"report-volumes","remote":"70.112.18.26:54762","session":"11324.1.1"}}
{"timestamp":"2019-07-24T20:11:20.253286749Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-containers","data":{"command":"sweep-containers","remote":"70.112.18.26:54768","session":"11325.1.1"}}
{"timestamp":"2019-07-24T20:11:20.261998104Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-volumes","data":{"command":"sweep-volumes","remote":"70.112.18.26:54766","session":"11326.1.1"}}
{"timestamp":"2019-07-24T20:11:48.896261493Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-containers","data":{"command":"report-containers","remote":"70.112.18.26:54772","session":"11328.1.1"}}
{"timestamp":"2019-07-24T20:11:48.899224356Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-volumes","data":{"command":"report-volumes","remote":"70.112.18.26:54774","session":"11327.1.1"}}
{"timestamp":"2019-07-24T20:11:50.197047244Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-containers","data":{"command":"sweep-containers","remote":"70.112.18.26:54780","session":"11329.1.1"}}
{"timestamp":"2019-07-24T20:11:50.231098391Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-volumes","data":{"command":"sweep-volumes","remote":"70.112.18.26:54778","session":"11330.1.1"}}
{"timestamp":"2019-07-24T20:12:18.886073515Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-volumes","data":{"command":"report-volumes","remote":"70.112.18.26:54784","session":"11331.1.1"}}
{"timestamp":"2019-07-24T20:12:18.938620744Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-report-containers","data":{"command":"report-containers","remote":"70.112.18.26:54786","session":"11332.1.1"}}
{"timestamp":"2019-07-24T20:12:19.462126630Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.heartbeat.done","data":{"command":"forward-worker","remote":"70.112.18.26:49270","session":"5.4.1.2508","worker-address":"127.0.0.1:45077","worker-platform":"linux","worker-tags":""}}
{"timestamp":"2019-07-24T20:12:20.195325957Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-volumes","data":{"command":"sweep-volumes","remote":"70.112.18.26:54788","session":"11333.1.1"}}
{"timestamp":"2019-07-24T20:12:20.262844063Z","level":"info","source":"tsa","message":"tsa.connection.channel.command.successfully-sweep-containers","data":{"command":"sweep-containers","remote":"70.112.18.26:54790","session":"11334.1.1"}}
{"timestamp":"2019-07-24T20:12:21.167110355Z","level":"info","source":"atc","message":"atc.collector.tick.worker-collector.marked-workers-as-stalled","data":{"count":1,"session":"18.2821.3","workers":["hci01.discord.local"]}}
{"timestamp":"2019-07-24T20:12:27.476205123Z","level":"info","source":"atc","message":"atc.pipelines.radar.scan-resource.interval-runner.tick.versions-found","data":{"pipeline":"master-x86_64","resource":"checksum-image","session":"15.13.35.1.3","team":"nightly","total":2,"versions":[{"path":"x86_64/haiku-master-hrev53290-x86_64-anyboot.zip"},{"path":"x86_64/haiku-master-hrev53290-x86_64-anyboot.zip.sha256"}]}}
{"timestamp":"2019-07-24T20:12:27.481227282Z","level":"error","source":"atc","message":"atc.pipelines.radar.scan-resource.interval-runner.tick.failed-to-choose-a-worker","data":{"error":"no workers","pipeline":"master-x86_64","resource":"upload-repo","session":"15.13.38.1.4","team":"nightly"}}
.
```

Any ideas why a worker would be happily chugging along, then suddenly:
```
{"timestamp":"2019-07-24T20:12:21.167110355Z","level":"info","source":"atc","message":"atc.collector.tick.worker-collector.marked-workers-as-stalled","data":{"count":1,"session":"18.2821.3","workers":["hci01.discord.local"]}}
```

**Comment by kcmannem** [comment]
😞 I was hoping it wasn't a repeat of that issue. This one is gunna take a bit more effort to solve as we haven't been able to reproduce it.

**Comment by jsievers** [comment]
we have seen the same issue running concourse 5.2.0 on AWS.

Here is what we found:

on two of our 3 worker VMs, DNS resolution wasn't working intermittently:

```
$ dig www.google.com
; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com
;; global options: +cmd
;; connection timed out; no servers could be reached

$ cat /etc/resolv.conf
nameserver 10.254.0.2
search ec2.internal

nc -zv 10.254.0.2 53
nc: connect to 10.254.0.2 port 53 (tcp) failed: Connection refused

$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.254.254.1    0.0.0.0         UG    0      0        0 eth0
10.254.0.0      0.0.0.0         255.255.255.252 U     0      0        0 wbrdg-0afe0000
10.254.0.4      0.0.0.0         255.255.255.252 U     0      0        0 wbrdg-0afe0004
10.254.0.12     0.0.0.0         255.255.255.252 U     0      0        0 wbrdg-0afe000c
10.254.254.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

we suspected that route entry 

```
10.254.0.0      0.0.0.0         255.255.255.252 U     0      0        0 wbrdg-0afe0000
```

was causing the problem because it wasn't present on the other worker nodes that did not show the problem. It looks like traffic to DNS server 10.254.0.2 is going to NIC wbrdg-0afe0000 (I think it should go to default route 0.0.0.0/interface eth0 instead)

In fact after removing this route

```
route del -net 10.254.0.0 gw 0.0.0.0 netmask 255.255.255.252 dev wbrdg-0afe0000
```

DNS resolution started to work again.

To summarize, we think there is something wrong with the route entry 

```
10.254.0.0      0.0.0.0         255.255.255.252 U     0      0        0 wbrdg-0afe0000
```

we suspect the problem may be intermittent as containers (and associated NICs/route entries) are garbage collected.

One possible workaround is to configure a public DNS server (like 8.8.8.8) using `garden.dns_servers`

https://github.com/concourse/concourse-bosh-release/blob/4056e00a5acde9da11d406cf7aeb009cc1f532d2/jobs/worker/spec#L187

so the rogue route entry 10.254.0.0 does not match for DNS resolution.

**Comment by jsievers** [comment]
> The only thing I can think of is to make sure your container network pool (default 10.254.0.0/22) doesn't overlap with any other addresses in your network.

it looks like this is exactly what's happening on AWS. The nameserver 10.254.0.2 happens to be in the container network pool (default 10.254.0.0/22)

Is there a way to configure the container network pool?

**Comment by thoHeinze** [comment]
@jsievers The network pool can be configured using the environment variable CONCOURSE_GARDEN_NETWORK_POOL. However, this is currently not possible in the concourse boshrelease. I created a PR https://github.com/concourse/concourse-bosh-release/pull/56. @vito Can you maybe take a look on my PR?

**Comment by marco-m** [comment]
We are seeing the same, Concourse 5.5.1 (so the latest at the date of this message), deployed on AWS, no BOSH (we handle the binaries ourselves).

**Comment by kallisti5** [comment]
Still seeing the same issue on 5.6.0. Interestingly, the container was still "hanging around" on the worker *hours* after it failed with dns resolution issues.

build 64:
```
(lots of successful downloads from this host)
.
C++ objects/haiku/x86_64/release/kits/storage/Err.o 
C++ objects/haiku/x86_64/release/kits/storage/DisjList.o 
C++ objects/haiku/x86_64/release/kits/storage/Pattern.o 
failed: Temporary failure in name resolution.
wget: unable to resolve host address 'eu.hpkg.haiku-os.org'

source="objects/haiku/x86_64/packaging/repositories/HaikuPorts-checksum"
wget --retry-connrefused --timeout 30 -O "download/icu_devel-57.1-3-x86_64.hpkg" https://eu.hpkg.haiku-os.org/haikuports/master/build-packages/`cat $source`/packages/icu_devel-57.1-3-x86_64.hpkg || exit 1
touch "download/icu_devel-57.1-3-x86_64.hpkg"
```

```
$ fly -t main containers
handle                                worker               pipeline       job                  build #  build id  type   name                   attempt
204bbd8e-4b96-4d8e-4fc9-a78f7367cead  hci01.discord.local  none           none                 none     none      check  none                   n/a    
258cb510-6d50-4f11-4ca6-4420ca39986a  hci01.discord.local  master-x86_64  image-master-x86_64  64       1474      task   build master anyboot   n/a    
3fefd25e-89e5-412c-5477-4310aafe87dd  hci01.discord.local  none           none                 none     none      check  none                   n/a    
43db43a7-6434-4b0a-447c-c6c0f54f6ab6  hci01.discord.local  none           none                 none     none      check  none                   n/a    
6a90484f-62df-4027-62b5-9997a7300c9b  hci01.discord.local  master-x86_64  image-master-x86_64  64       1474      get    pipeline-time-trigger  n/a    
88457628-dc5e-4700-49a3-e9b45bfe1e30  hci01.discord.local  none           none                 none     none      check  none                   n/a    
8af823c0-c3c3-459f-779a-eabc03915235  hci01.discord.local  none           none                 none     none      check  none                   n/a    
9b260c9f-6653-4928-48f0-66248f18c25d  hci01.discord.local  none           none                 none     none      check  none                   n/a    
a8ae01cf-c6b8-45e1-765c-7bfbc8defa7b  hci01.discord.local  none           none                 none     none      check  none                   n/a    
aa930e2a-d137-4cca-6dd0-c46f3d833c07  hci01.discord.local  none           none                 none     none      check  none                   n/a    
b4133334-c61c-40cb-72cd-fb850fc1427f  hci01.discord.local  none           none                 none     none      check  none                   n/a    
d26a6381-f810-4324-7b4a-7416d66199f5  hci01.discord.local  none           none                 none     none      check  none                   n/a    
d9ed0399-0565-4b7e-5c61-c93d474ff379  hci01.discord.local  none           none                 none     none      check  none                   n/a    
```

```
[root@hci01 log]# runc exec -t 3fefd25e-89e5-412c-5477-4310aafe87dd /bin/bash -l

root@258cb510-6d50-4f11-4ca6-4420ca39986a:/# while(true); do date; wget -v google.com -O test.html; sleep 5; done
Thu Oct 17 00:10:42 UTC 2019
--2019-10-17 00:10:42--  http://google.com/
Resolving google.com (google.com)... 172.217.6.174, 2607:f8b0:4000:80c::200e
Connecting to google.com (google.com)|172.217.6.174|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2019-10-17 00:10:42--  http://www.google.com/
Resolving www.google.com (www.google.com)... 216.58.194.132, 2607:f8b0:4000:80c::2004
Connecting to www.google.com (www.google.com)|216.58.194.132|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'test.html'

test.html                                                       [ <=>                                                                                                                                      ]  12.31K  --.-KB/s    in 0s      

2019-10-17 00:10:43 (247 MB/s) - 'test.html' saved [12602]
.
.
```
 Waiting to see if the wget above fails.  Might also try changing my container to Fedora from Debian.
```

**Comment by kcmannem** [comment]
@marco-m did you see this after an upgrade to 5.5.1 or was this always present in past versions as well?

**Comment by kcmannem** [comment]
@kallisti5 the latest failed build for a job will have its container stick around for a while so it lets you hijack it and debug.

**Comment by kallisti5** [comment]
@kcmannem dns resolution worked 100% of the time :-|  It seemed to only trigger within concourse-automated builds.

I switched us over to Fedora-based build containers from Debian-based build containers, and haven't seen the DNS failures occur since.  Still testing.

**Comment by vito** [comment]
@kallisti5 Thanks for hanging in there and trying to get to the bottom of this! These kinds of things are a pain to figure out especially without having access to the environment ourselves. :( 

It'd be nice if we could more quickly demonstrate the issue, even in your own environment for starters. If that fails pretty easily in the affected environment, maybe we can try to replicate the same environment ourselves and get closer to a solution.

Would you be able to configure a pipeline to just run a bunch of `wget`s every minute? And maybe configure that pipeline a bunch of times to notice it more quickly? Or maybe add more jobs so a bunch run at once? Not really sure where to start here to be honest.

Something like this:

```yaml
resources:
- name: 1m
  type: time
  source: {interval: 1m}

jobs:
- name: run-wget
  serial: true
  plan:
  - get: 1m
    trigger: true
  - task: wget
    config:
      platform: linux

      image_resource:
        type: registry-image
        # random image with wget installed, you could use your own
        source: {repository: mwendler/wget}

      run:
        path: wget
        args: [https://example.com]

      # or maybe do a loop or something
```

**Comment by kallisti5** [comment]
Just saw it again.  Started a wget job here:
https://ci.haiku-os.org/teams/continuous/pipelines/wget-test

**Comment by kcmannem** [comment]
@kallisti5 looks like the pipelines not public

**Comment by kallisti5** [comment]
sorry, should be public now.

Here's the pipeline:
```
resources:
- name: 1m
  type: time
  source: {interval: 1m}
jobs:
- name: run-wget
  serial: true
  public: true
  plan:
  - get: 1m
    trigger: true
  - task: wget
    config:
      platform: linux
      image_resource:
        type: registry-image
        # random image with wget installed, you could use your own
        source: {repository: haiku/general-worker}
      run:
        path: /bin/bash
        args:
          - -c
          - |
            wget --retry-connrefused --timeout 30 https://git.kernel.org/torvalds/t/linux-5.4-rc3.tar.gz
            wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/a52dec_source-0.7.4-5-source.hpkg
            wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/apache-2.4.37-1-x86_64.hpkg
            wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/aqemu-0.9.2-2-x86_64.hpkg
            wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/artpaint-2.1.0git-7-x86_64.hpkg
            wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/avr_binutils-2.26.1_2016_07_22-5-x86_64.hpkg
      # or maybe do a loop or something
```

**Comment by kcmannem** [comment]
@kallisti5 I'll set the pipeline on our envs as well and see how many failures we get over the weekend.

**Comment by kallisti5** [comment]
Ugh.  My only guess is it has something to do with the length of the build step, or the amount of network traffic during the build.

Here's a random dns failure ~8 hours ago:
https://ci.haiku-os.org/teams/continuous/pipelines/master-x86_gcc2h/jobs/haiku-master-x86_gcc2h/builds/206

Then, the wget job (running every 5 minutes, and downloading multiple files from the same failed location and other locations like kernel.org) working as expected for the last two days with zero issues:
https://ci.haiku-os.org/teams/continuous/pipelines/wget-test/jobs/run-wget

**Comment by kallisti5** [comment]
Another random dns failure:
https://ci.haiku-os.org/teams/nightly/pipelines/master-x86_gcc2h/jobs/image-master-x86_gcc2h/builds/57

wget job still running without any failures.   Thinking of stopping the wget test pipeline and running a tcpdump filtering for DNS traffic... thoughts?

**Comment by kallisti5** [comment]
Err.. wait.  

  * 19m 9s - https://ci.haiku-os.org/teams/continuous/pipelines/master-x86_gcc2h/jobs/haiku-master-x86_gcc2h/builds/206
  * 23m 32s  - https://ci.haiku-os.org/teams/nightly/pipelines/master-x86_gcc2h/jobs/image-master-x86_gcc2h/builds/57
  * 47m 28s (waiting on a builder for 45 minutes) - https://ci.haiku-os.org/teams/nightly/pipelines/master-x86_gcc2h/jobs/image-master-x86_gcc2h/builds/39
  * 14m 16s -  https://ci.haiku-os.org/teams/continuous/pipelines/master-x86_gcc2h/jobs/haiku-master-x86_gcc2h/builds/187

All the wget testing jobs run < 3 minutes and are 100% successful.
Could this issue require a "long build time"?

**Comment by vito** [comment]
@kallisti5 To test increased/concurrent network activity you could try the same task many times `in_parallel`:

```
resources:
- name: 30m
  type: time
  source: {interval: 30m}
jobs:
- name: run-wget
  serial: true
  public: true
  plan:
  - get: 30m
    trigger: true
  - in_parallel:
    - &wget_task
      task: wget
      config:
        platform: linux
        image_resource:
          type: registry-image
          # random image with wget installed, you could use your own
          source: {repository: haiku/general-worker}
        run:
          path: /bin/bash
          args:
            - -c
            - |
              wget --retry-connrefused --timeout 30 https://git.kernel.org/torvalds/t/linux-5.4-rc3.tar.gz
              wget --retry-connrefused --timeout 30 https://git.kernel.org/torvalds/t/linux-5.4-rc4.tar.gz
              wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/a52dec_source-0.7.4-5-source.hpkg
              wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/apache-2.4.37-1-x86_64.hpkg
              wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/aqemu-0.9.2-2-x86_64.hpkg
              wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/artpaint-2.1.0git-7-x86_64.hpkg
              wget --retry-connrefused --timeout 30 https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/avr_binutils-2.26.1_2016_07_22-5-x86_64.hpkg
        # or maybe do a loop or something
    - *wget_task
    - *wget_task
    - *wget_task
    - *wget_task
    - *wget_task
    - *wget_task
    - *wget_task
    - *wget_task
    - *wget_task
```

I removed the `sleep 1200` in this example but you could try adding it back if this doesn't reproduce it.
