### ISSUE TITLE
Network latency from web to postgres causes slow initialization in task and put steps

### ISSUE THREAD

**Issue by edtan** [concourse/concourse#4162]
## Bug Report

When there is a slow connection from the web node(s) to the database, this causes the "initialization" part of `task` and `put` steps to slow down quite a bit.  In one setup where the web and database nodes were in different data centers, we saw the initialization period going up to a minute for each `task` and `put` step in a job.  When the web and database nodes were placed in the same data center, the initialization period went down to 5 seconds.

## Steps to Reproduce

This can be reproduced on `master` using the docker-compose setup, but pointing the database to a remote database.  I've tried this with postgres on AWS M5.large instances, AWS RDS in us-east-1 and eu-west-1, as well as GCP CloudSQL in europe-north1.

I used this pipeline for the tests:
```
---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/concourse/git-resource
    branch: master

jobs:
- name: test
  plan:
  - get: git-repo
  - task: print
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sh
        args:
          - -exc
          - |
            lssdf
    attempts: 2
```

When the database was on my local machine, the initialization took about 3 seconds.  When it was in us-east-1, latencies were around 30 ms to the database, and the initialization took about 9 seconds.  When it was in Europe, latencies were around 100ms, and the initialization took 20 seconds.

## Additional Context

I suspect that network latency to the database leads to some type of compounding effect in Concourse with the number of queries and the mutexes protecting each database access.  I tried adding `runtime.SetMutexProfileFraction(1)` to the ATC, and captured some of the info which I've made available [here](https://gist.github.com/edtan/e2ef9592c86ee10d13c2069dce3d9c90).  Also, in the web logs, I noticed `lock.acquire.not-acquired-already-held-locally` popped up a few times.

## Version Info

* Concourse version: v5.4.0
* Deployment type (BOSH/Docker/binary): Docker, Kubernetes, binary
* Infrastructure/IaaS: 
* Browser (if applicable):
* Did this used to work?
