### ISSUE TITLE
Removing of `webhook_token` requires pipeline re-creation to run with new `check_every`

### ISSUE THREAD

**Issue by propalparolnapervom** [concourse/concourse#4163]
## Bug Report

Concourse 5.3.0/5.4.0

Removing of `webhook_token` parameter from pull-request resource doesn't allow pipeline to be triggered with new value of `check_every`.

Please,
see reproducing steps for further explanation.

## Steps to Reproduce

Create initial pipeline with following pull-request resource:

```
resources:
- name: pr
  type: pull-request
  source:
    access_token: <access_token>
    repository: <repository>
  webhook_token: <webhook_token>
  check_every: 48h

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
```

Each pull-request triggers initial pipeline almost immediately.

Desired updates for pipeline:

 - removing of `webhook_token`
 - updating of `check_every` with new value: `48h` -> `30s`

So updated pipeline looks like:
```
resources:
- name: pr
  type: pull-request
  source:
    access_token: <access_token>
    repository: <repository>
  check_every: 30s

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
```

Apply latest updates via `fly set-pipeline` to already existing (initial) pipeline.

Make sure latest updates are visible via `fly get-pipeline`.

## Expected Results

Each pull-request triggers updated pipeline within time defined by new value of `check_every`: `30s`.

## Actual Results

Seems like each pull-request triggers updated pipeline within time defined by old value of `check_every`: `48h`.

To make pipeline work as expected it has to be re-created from the scratch:

 - destroy updated pipeline via `fly destroy-pipeline` 
 - create new pipeline (with those updated parameters) via `fly set-pipeline`

## Version Info

* Concourse version: `5.3.0`, `5.4.0`
