### ISSUE TITLE
Warn instead of fail on unused resources

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#4177]
## What challenge are you facing?

It would be *great* to be able to leverage unused resources within pipelines.  We deploy multiple pipelines using the same yaml. These pipelines are "one per branch" (master, release1, release2, etc)

We template the branch out within our yaml.  It would be awesome to have our pipelines "select" the resource they want based on the branch name... however unused resources result in pipelines erroring out:

```
error: invalid pipeline config:
invalid resources:
	resource 'master-time-trigger' is not used
	resource 'r1beta2-time-trigger' is not used
```
Example:
```yaml

resources:
  - name: master-time-trigger
    type: time
    source:
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
  - name: r1beta1-time-trigger
    type: time
    source:
      days: [Sunday]
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
  - name: r1beta2-time-trigger
    type: time
    source:
      days: [Monday,Friday]
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
.
.
# Jobs
jobs:
  - name: image-((branch))-((arch))
    public: true
    plan:
      - get: ((branch))-time-trigger
        trigger: true
      - get: haiku-git
        trigger: false
      - task: build ((branch)) anyboot
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: haiku/toolchain-worker-((branch)) }
          inputs:
            - name: haiku-git
          outputs:
            - name: generated.((arch))
          run:
            path: /bin/bash
            args:
```

## What would make this better?

Concourse should warn the user about unused triggers instead of erroring out about them. Unused resources could be valuable in more complex pipelines.  Assuming the user knows what their doing and "just letting them know" vs blocking their attempts would be ideal.

## Are you interested in implementing this yourself?

Maybe depending on complexity.

**Comment by kallisti5** [comment]
See PR https://github.com/concourse/concourse/pull/4178

**Comment by kcmannem** [comment]
This isn't really my area in the code so I don't know what side effects unused resources will cause. Another approach we can try is to remove unused resources invisibly from the interpreted yaml before calling out to the ATC. This way we can spit out a warning such as: `Unused resources referenced. Excluding them from pipeline config.`

**Comment by clarafu** [comment]
@kallisti5 Hi! I can see your point about it being useful to use the same yaml for multiple pipelines. If we were to allow for resources that arn't used by the pipeline, it would result in those unused resources being checked even though it is never used and shown within the pipeline view in the UI. So in your case, it would result in all those unused resources that would be for the other branches to continue to be checked and consuming worker resources. Could an alternative to this be to template out the resource configurations to make them use the same resource but have different configurations for each pipeline?

**Comment by kallisti5** [comment]
Would it be difficult to just omit resources that are unused?

**Comment by trucken** [comment]
Just like @clarafu says, you could have just one resource and let configuration files dictate how it functions for different pipelines.
E.g.
```
master-cfg.yml
branch: master
days: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday"

r1beta1-cfg.yml
branch: r1beta1
days: "Sunday"

pipeline.yml
resources:
  - name: ((branch))-time-trigger
    type: time
    source:
      days: [((days))]
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
.
.
# Jobs
jobs:
  - name: image-((branch))-((arch))
    public: true
    plan:
      - get: ((branch))-time-trigger
        trigger: true
```

```
fly set-pipeline -p master -l master-cfg.yml -p pipeline.yml
fly set-pipeline -p r1beta1 -l r1beta1-cfg.yml -p pipeline.yml
```

Not sure if that is what you're after. 

I personally am in favor of the error and backing out creating a pipeline with unused resource since they would just hang there, creating volumes and containers and periodically ping their endpoint without actually contributing anything to your pipeline or system.

**Comment by trucken** [comment]
You can also make the configuration multi-layered.

E.g.
```
default-cfg.yml
branch: default
days: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday"
arch: ARM64

master-cfg.yml
branch: master

r1beta1-cfg.yml
branch: r1beta1
days: "Sunday"

r1beta2-cfg.yml
branch: r1beta1
days: "Monday,Friday"

pipeline.yml
resources:
  - name: ((branch))-time-trigger
    type: time
    source:
      days: [((days))]
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
.
.
# Jobs
jobs:
  - name: image-((branch))-((arch))
    public: true
    plan:
      - get: ((branch))-time-trigger
        trigger: true
```

```
fly set-pipeline -p master -l default-cfg.yml -l master-cfg.yml -c pipeline.yml
fly set-pipeline -p r1beta1 -l default-cfg.yml -l r1beta1-cfg.yml -c pipeline.yml
fly set-pipeline -p r1beta1 -l default-cfg.yml -l r1beta1-cfg.yml -c pipeline.yml
```

The configuration files are read from left to right so any parameter declared in any of the -l files to the right will override its value so you can customize your pipeline.

**Comment by kallisti5** [comment]
I was able to get a working pipeline by templating our the days fields.  I still think "not using" unused resources with a warning is more flexible though.

Leaving this one open for commentary.. otherwise, feel free to close if consensus is it is unimportant :-)

**Comment by kallisti5** [comment]
actually.. this didn't work.

```yaml
resources:
  - name: pipeline-time-trigger
    type: time
    icon: alarm
    source:
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
      days: [((days))]
```

In the web ui:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
parse error: unknown weekday: Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
```

I guess the only option is overlaying another yml?

**Comment by vito** [comment]
@kallisti5 To provide an array, the value needs to be an array in the vars file, not a string as in @trucken's comment.

vars file:

```yaml
days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
```

config file:

```yaml
resources:
  - name: pipeline-time-trigger
    type: time
    icon: alarm
    source:
      start: 1:00 AM
      stop: 6:00 AM
      location: America/Chicago
      days: ((days))
```

This works for any arbitrary YAML value.

If you're not using `-c`, make sure you use `-y` which parses its value as YAML instead of as a raw string: `-y days=[Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday]`
