### ISSUE TITLE
YAML anchor tags aren't deep merged anymore

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#424]
On v1.2.0 we noticed that YAML anchor tags are shallow merged. As of v1.0.0 they were being deep merged.

To illustrate, here is an example 

```
top:
  config: &config
  	key1: value1
  	map1: 
  	  mapkey1: value1
  	  mapkey2: value2

  otherconfig:
  	<<: *config
  	map1:
  	  mapkey1: some-other-value
```
here's what we get on v1.0.0

```
top:
  config: &config
  	key1: value1
  	map1: 
  	  mapkey1: value1
  	  mapkey2: value2

  otherconfig:
  	key1: value1
  	map1:
  	  mapkey1: some-other-value
  	  mapkey2: value2
```

Here's what we're getting on v1.2.0
```
top:
  config: &config
  	key1: value1
  	map1: 
  	  mapkey1: value1
  	  mapkey2: value2

  otherconfig:
  	key1: value1
  	map1:
  	  mapkey1: some-other-value
```   

We use anchor tags extensively to cut down on the duplication in our YAML files.

**Comment by jfrank-pivotal** [comment]
We hit this as well.

For now, we're using YAML like this with nested anchors (because `params` isn't being deep merged correctly):

```yaml
templates:
  - &setup-config
    task: setup-config
    params: &setup-config-params
      ACCESS_TOKEN: {{digitalocean-access-token}}

      SSH_USER: {{digitalocean-ssh-user}}
      SSH_KEY: {{digitalocean-ssh-key}}

      REGION: sfo1
      IMAGE: ""
      SIZE: 1gb
      PRIVATE_NETWORKING: 'false'
      BACKUPS_ENABLED: 'false'
      IP6: 'false'
      OS: ""
```

which we reference like

```yaml
jobs:
- name: digitalocean-centos-7

- name: digitalocean-ubuntu-xenial
  serial: true
  plan:
  - get: bin-rc
    params:
      globs:
      - concourse_linux_amd64

  - <<: *setup-config
    params:
      <<: *setup-config-params
      IMAGE: ubuntu-16-04-x64
      OS: ubuntu
```
