### ISSUE TITLE
Custom icon support for resources

### ISSUE THREAD

**Issue by mattdodge** [concourse/concourse#4308]
##  What challenge are you facing?

Sometimes I want a resource to have an icon that doesn't exist in the [material design set](https://materialdesignicons.com/). Also, community icons (e.g., `kubernetes`) don't seem to be supported either.

## What would make this better?

Support for a URL in addition to an icon name would extend this to allow any icon. There may be some style concerns but I think it's ok to put that onus on the user if they are going the custom icon route.

Example:
```yml
resource:
  - name: git-repo
    type: git
    icon: https://www.pngkey.com/png/detail/178-1787508_github-icon-download-at-icons8-white-github-icon.png
```

We could even restrict to only SVG if there's an issue using PNG or other image types.

## Are you interested in implementing this yourself?

Of course! If this sounds like a good feature to have I'd love to throw a PR up.
