### ISSUE TITLE
Ensure rendered only for last task of `do` block

### ISSUE THREAD

**Issue by mtekel** [concourse/concourse#434]
In concourse 0.76, but also in 1.1, when I define a `do` block like:

```
      - do:
        - task: create-temp-user
          file: paas-cf/concourse/tasks/create_admin.yml
          config:
            params:
              PREFIX: smoketest-user

        - task: smoke-tests-config
          file: paas-cf/concourse/tasks/smoke-tests-config.ymll

        - task: smoke-tests-run
          file: paas-cf/concourse/tasks/smoke-tests-run.yml
        ensure:
          task: remove-temp-user
          file: paas-cf/concourse/tasks/delete_admin.yml
```

This is rendered as ensure for the last job only:
![image](https://cloud.githubusercontent.com/assets/483891/15114312/42e1b3e8-15f1-11e6-9ff3-74c2f8709a93.png)
but works as ensure for the whole `do` block:
![image](https://cloud.githubusercontent.com/assets/483891/15114361/816ba22c-15f1-11e6-8f95-1fa61d4d629e.png)
