### ISSUE TITLE
Modifying variable interpolation shows "no changes to apply"

### ISSUE THREAD

**Issue by ryanmattcollins** [concourse/concourse#4385]
## Bug Report

I have a variable in a resource that is being interpolated as a number, but due to the resource that is consuming it, it wants it to be a string.
```
type: tracker
   source:
     token: ((pivotal-tracker-api-token))
     project_id: ((pivotal-tracker-project-id))        <== This one
     tracker_url: https://www.pivotaltracker.com
```

When I modify the line in either of the following ways:
`project_id: "((pivotal-tracker-project-id))"` 
= OR = 
`project_id: {{pivotal-tracker-project-id}}`

and run `fly set-pipeline` again, it reads `no changes to apply`

## Steps to Reproduce

1. Set a pipeline using a pipeline yaml with a variable `((variable))` that is a number
1. Modify the pipeline so the variable is interpolated with quotes or braces (i.e., `"((variable))"` or `{{variable}}`)
1. Set pipeline again
1. Observe `no changes to apply` message
1. Cry

## Expected Results

I expected it to apply the changes and interpolate the variable as a string

## Actual Results

It did not apply the changes and my pipeline is still broken

## Version Info

* Concourse version: v.5.5.0
* Deployment type (BOSH/Docker/binary): K8s
* Infrastructure/IaaS: Hushhouse
* Did this used to work? Unsure
