### ISSUE TITLE
How to set multiple caches path?

### ISSUE THREAD

**Issue by gugegev5** [concourse/concourse#4396]
I need to cache two location: "node_modules", "util_modules". And the following config didn't work for ***caches***
```
jobs:
- name: package
  public: true
  plan:
  - get: source-code-h5
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gugege/node_12_4_cnpm_rsync
          tag: '1.0'
      inputs:
      - name: source-code-h5
      run:
        path: /bin/bash
        args:
        - source-code-h5/concourse-build.sh
      caches:
      - path: source-code-h5/node_modules,source-code-h5/util_modules
```
