### ISSUE TITLE
Fly cannot parse float64 from vars file

### ISSUE THREAD

**Issue by stuart-c-moore** [concourse/concourse#4397]
## Bug Report

Fly 5.5 cannot parse a line in a vars file that was parsed successfully in 5.4.1

## Steps to Reproduce

```bash
% head -4 ci/vars/pm-concourse-master.yml
# Destroy resources automatically. Pay close attention to this one!
terraform_destroy: false
terraform_destroy_disable_manual_trigger: true
terraform_destroy_sleep_seconds: 7200

% fly vp -c ci/pipeline.yml -l ci/vars/common.yml -l ci/vars/pm-concourse-master.yml
error: cannot interpolate non-primitive value (float64) from var: terraform_destroy_sleep_seconds
```

## Expected Results

The file is parsed successfully. This is the case in 5.4.1

## Actual Results

The following error is shown:

```
error: cannot interpolate non-primitive value (float64) from var: terraform_destroy_sleep_seconds
```

## Additional Context

I have noticed that values of type float64 are not permitted:

https://github.com/concourse/concourse/blob/be412879cbf5a3c52a583c7ba194a7976d21e1a1/vars/template.go#L106

**Comment by migs** [comment]
I found a "workaround" - the variable name length seems to have a cap of 30 characters. The 31st character introduces the error.

**Comment by migs** [comment]
I have come up with a workaround, although I don't know *why* this works ...

- If I reduce the length of the variable to 30 characters in both the vars file and the pipeline, the file can be parsed.
- If the variable name exists in both the vars file and the pipeline, and is 31 characters or greater, the error is generated.
- If the variable name exists in the vars file but does not exist in the pipeline, the file can be parsed.
- If the variable name exists in the pipeline but does not exist in the vars file, the file can be parsed.

So, for now, I just need to keep the variable name to 30 characters or less.

This only seems to be a problem where the value is numerical - strings seem to have no such name length limit

**Comment by migs** [comment]
I've found a reliable way to recreate the problem:

Given a vars.yml file with the following contents:

```yaml
sleep: 7200
```

This **works**:

```yaml
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: slack-warning
  type: slack-notification

jobs:
- name: terraform-destroy
  serial: true
  serial_groups: [terraform]
  plan:
  - put: slack-warning
    params:
      text: "((sleep))"
  - task: terraform destroy
    file: concourse/ci/tasks/terraform-destroy.yml
    params:
      TERRAFORM_DESTROY_SLEEP_SECONDS: ((sleep))
```
```bash
% fly vp -c pipeline.yml -l vars.yml
looks good
```

This **errors**:
```yaml
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: slack-warning
  type: slack-notification

jobs:
- name: terraform-destroy
  serial: true
  serial_groups: [terraform]
  plan:
  - put: slack-warning
    params:
      text: " ((sleep))"
  - task: terraform destroy
    file: concourse/ci/tasks/terraform-destroy.yml
    params:
      TERRAFORM_DESTROY_SLEEP_SECONDS: ((sleep))
```
```bash
% fly vp -c pipeline.yml -l vars.yml
error: cannot interpolate non-primitive value (float64) from var: sleep
```

Note the additional space I entered before `((sleep))` on the `text:` line.
