### ISSUE TITLE
Concourse is trying to use Secrets manager with instance role but only SSM is configured with user credentials

### ISSUE THREAD

**Issue by RuBiCK** [concourse/concourse#4401]
## Bug Report

I'm using Concourse in Kubernetes. The workers have some AWS IAM roles but I have configured Concourse to use AWS access key and secret vey to access SSM via user with a policy attached.
Concourse is trying to use Secrets manager with instance role but only SSM is configured with user credentials

## Steps to Reproduce
pipeline.yaml
```
---
resources:
  - name: source-code
    type: git
    check_every: 5m
    source:
      uri: ((git-uri))
      branch: develop
      private_key: ((git_ssh_privatekey))
jobs:
- name: check-gitlab
  max_in_flight: 2
  build_logs_to_retain: 30
  plan:
  - get: source-code
    trigger: true
    version: every
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: lts-alpine
      inputs:
      - name: source-code
      run:
        path: sh
        args: ['-c', 'ls -la && npm install  --registry ((nexus_url)) -strict-ssl false -f install && npm run build']
        dir: source-code
```

AWS env related variables loaded on docker web
```
root@concourse-web-5b676b87b9-9xc7r:/# env | grep -i aws
CONCOURSE_AWS_SSM_ACCESS_KEY=xxxxxxxx
CONCOURSE_AWS_SSM_TEAM_SECRET_TEMPLATE=/concourse/{{.Team}}/{{.Secret}}
CONCOURSE_AWS_SSM_PIPELINE_SECRET_TEMPLATE=/concourse/{{.Team}}/{{.Pipeline}}/{{.Secret}}
CONCOURSE_AWS_SSM_SECRET_KEY=xxxxxxxx
CONCOURSE_AWS_SSM_REGION=eu-west-1
```

Policy associated to user:
Please, note this policy is prepared to use KMS and secrets manager but now I'm only using SSM
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ssm:GetParameter*",
                "kms:Decrypt",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret"
            ],
            "Resource": [
                "arn:aws:ssm:eu-west-1:xxxxx:parameter/concourse/*",
                "arn:aws:kms:eu-west-1:xxxxxx:key/xxx-xxxx-x-x-xxxxxxxx",
                "arn:aws:secretsmanager:::secret:/concourse/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "secretsmanager:ListSecrets",
            "Resource": "*"
        }
    ]
}
```
## Expected Results

Concourse be able to read SSM  but it is trying to read from Secrets Manager that is disabled (there is no SecretsMangager env variables on docker running)

## Actual Results

```
Finding variable 'git_ssh_privatekey': AccessDeniedException: User: arn:aws:sts::xxxxxxxxx:assumed-role/eks-eks-marketplace-worker/i-02xxxxxx50431d7 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-west-1:xxxxxxx:secret:/concourse/shopping/frontend/git_ssh_privatekey-MRronW
	status code: 400, request id: 504d01fe-5876-4133-a333-11c333ac286e

```
## Additional Context
SSM parameters:
```
$ aws ssm describe-parameters | jq '.[][].Name'
"/concourse/shopping/frontend/git-uri"
"/concourse/shopping/frontend/git_ssh_privatekey"
"/concourse/shopping/git_ssh_privatekey"
"/concourse/shopping/nexus_url"
```
## Version Info

* Concourse version: v.5.4.1
* Deployment type (BOSH/Docker/binary): Helm (Kubernetes)
* Infrastructure/IaaS: AWS EKS
* Did this used to work? Yes
