### ISSUE TITLE
Pipeline UI breaks with some cases of circular dependencies 

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#4445]
## Bug Report

Although we got rid of a class of problems regarding circular dependencies in previous PRs (see https://github.com/concourse/concourse/pull/3433), there's still another class of pipelines that still break: those that also contain resources that don't depend on previous steps.

## Steps to Reproduce

Create a self-referencing job that works just fine in the UI:

```yaml
jobs:
  - name: myjob
    plan:
      - get: res-1
        passed: [myjob]

resources:
  - name: res-1
    type: time
    source: {interval: 2m}
```

Notice how we're not including any other resources here other than the ones that the dependency is made upon (`res-1` via `get: res-1` w/ `passed` on `myjob`).

This works perfectly on a 5.1+ Concourse installation.

Once we introduce a resource that imposes no constraints though, you can no longer get the web UI rendering the pipeline:

```yaml
jobs:
  - name: myjob
    plan:
      - get: res-1
        passed: [myjob]
      - get: res-2

resources:
  - name: res-1
    type: time
    source: {interval: 2m}

  - name: res-2
    type: time
    source: {interval: 2m}
```

## Expected Results

Show the pipeline 😁  

## Actual Results

Hanging forever 😅 

## Additional Context

I created a little tool to help aid folks who are having this problem and want to have a way of seeing how jobs depend on each other: https://github.com/cirocosta/pipeline2dot

## Version Info

* Concourse version: 5.5
* Deployment type (BOSH/Docker/binary): k8s
* Infrastructure/IaaS: gcp
* Browser (if applicable): firefox
* Did this used to work? 🤔
