### ISSUE TITLE
pipeline should have new top-level tasks key

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#446]
Similar to resources, if the pipeline has a `tasks` key, it could be used to define a task once per-pipeline, and then we can reference this task name later on when we want to invoke it.

This provides a symmetry between `resources` and `tasks`, which helps pave the way for more sharable tasks, as well as the convenience of a job not having to `get` the task's repo.

I would expect it to look something like:

```
tasks:
- name: my-task # logical name used to reference the task elsewhere in the pipeline
  resource: my-ci-scripts # logical name of a resource already defined in the pipeline which contains the tasks scripts
  path: scripts/ci/some-task/task.yml # relative to root of resource above
```

And elsewhere in the pipeline we would consume it:

```
jobs:
- name: my-job
  plan:
    task: my-task
```

Notice that we don't have to `get` the repo the task lives in as part of the the `plan`.
