### ISSUE TITLE
Containers with processes in uninterruptible state can't be GCed

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#4477]
Hey,

it seems like if you have a container who's process stays in the
uninterruptible state, `gdn` blocks forever on the deletion of such container,
which, coupled with https://github.com/concourse/concourse/issues/4467 leads to
a forever growing number of containers in the affected worker (until
`max_containers` is reached).

Here's a breakdown of the events, and a small reproducible,

### event

Recently, we noticed that [`wings`] had a funny thing going on in a worker:

<img width="1836" alt="wings-20sept-1" src="https://user-images.githubusercontent.com/3574444/65355528-20ae2c00-dbc0-11e9-8623-00027ff0217c.png">

Exploring a bit, we could see that in it we had a process sitting there in the uninterruptible state:

```
ps axl | awk '$10 ~ /D/'
4     0 2744003 2729299  20   0 391476 26240 -      Dsl  ?     
                                                    ^
                                               D means uninterruptible
```

looking at where it's blocked:

```
sudo cat /proc/2744003/stack
[<0>] __refrigerator+0x76/0x150
[<0>] futex_wait_queue_me+0x11e/0x120
[<0>] futex_wait+0x119/0x260
[<0>] do_futex+0x3c4/0x590
[<0>] SyS_futex+0x7f/0x180
[<0>] do_syscall_64+0x73/0x130
[<0>] entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[<0>] 0xffffffffffffffff
```

Interestingly, it turns out that this meant that the process was frozen:

> Namely, as the first step of the hibernation procedure the function `freeze_processes()` (defined in kernel/power/process.c) is called.  
> A system-wide variable `system_freezing_cnt` (as opposed to a per-task flag) is used to indicate whether the system is to undergo a freezing operation. 
> And `freeze_processes()` sets this variable.  
> After this, it executes `try_to_freeze_tasks()` that sends a fake signal to all user space processes, and wakes up all the kernel threads.  

> **All freezable tasks must react to that by calling `try_to_freeze()`, which results in a call to `__refrigerator()` (defined in kernel/freezer.c), which sets the task's `PF_FROZEN` flag, changes its state to `TASK_UNINTERRUPTIBLE` and makes it loop until `PF_FROZEN` is cleared for it**

Assuming that this was not frozen due to the system going to a "suspended"
state (we're just running on a VM "in the cloud", that'd be nuts), it made
sense that at some point, something had put this process in the freezer cgroup
for whoknows reason:

```
cat /proc/2744003/cgroup
cat /sys/fs/cgroup/freezer/docker/634bfe13f23c.../kubepods/burstable/podd0e3.../0736.../freezer/state
  FROZEN
```

We can verify that the container that holds such task would indeed take forever
to delete by trying to do what `gdn` was doing under the hood: issuing `runc
kill` followed by `runc delete --force`.

To do so though, we need to figure out what's the container handle that `runc` is keeping track of for that container.
As each container gets a `garden-init` associated with it, that meant that from the `host` we'd need to know that `pid`:

```
pstree -sp 2744003

systemd(1)───garden-init(2605510)───systemd-shutdow(2729299)───flanneld(2744003)─┬─{flanneld}(2744062)
                                                                                 ├─{flanneld}(2744063)
                                                                                 ├─{flanneld}(2744064)
                                                                                 ├─{flanneld}(2744065)
                                                                                 ├─{flanneld}(2744096)
                                                                                 ├─{flanneld}(2744162)
                                                                                 ├─{flanneld}(2744163)
                                                                                 ├─{flanneld}(2744232)
                                                                                 ├─{flanneld}(2744233)
                                                                                 └─{flanneld}(2744234)
```

Now, running the `runc` commands:

```
# get the handle
#
runc --root /run/runc list | grep 2605510
  (2605510 is the pid of the `garden-init` process)


# send a graceful termination signal (sigterm)
#
./runc --root /run/runc kill fe349861-0eed-4c4e-4c9c-fedd5abdc287

# try to forcebly delete (as we can see that the previous signal is never acted
# upon)
#
./runc --root /run/runc delete --force fe349861-0eed-4c4e-4c9c-fedd5abdc287

    --> this hangs forever
```

### reproducible

1. create a pipeline that puts `pid=1` into the `freezer`

```yaml
jobs:
- name: brrr
  plan:
    - task: brrrrrrrrrr
      privileged: true
      config:
        platform: linux
        image_resource: {type: "registry-image", source: { repository: "alpine" }}
        run:
          path: /bin/sh
          args:
            - -cex
            - |

              mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
              mount -o remount,rw none /sys/fs/cgroup
              mkdir -p /sys/fs/cgroup/freezer
              mount -n -t cgroup -o freezer cgroup /sys/fs/cgroup/freezer
              mkdir -p /sys/fs/cgroup/freezer/foo
              echo "1" > /sys/fs/cgroup/freezer/foo/tasks
              echo "FROZEN" > /sys/fs/cgroup/freezer/foo/freezer.state

              sleep 3s

              echo "byebye"
```

set it

```
fly -t local set-pipeline -p test -c ./pipeline.yml
```

trigger a job

```
fly -t local tj -j test/brrr -w
```

2. create a very simple pipeline with a very simple job that definitely succeeds

```
jobs:
- name: brrr
  plan:
    - task: brrrrrrrrrr
      config:
        platform: linux
        image_resource: {type: "registry-image", source: { repository: "alpine" }}
        run:
          path: true
```

set

```
fly -t local set-pipeline -p test -c ./pipeline.yml
```

run a bunch of times

```
for i in $(seq 1 100); do fly -t local tj -j test/brrr ; done
```

3. see the number of containers never going down, all staying as destroying

```
fly -t local containers --json | jq '.[] | select(.state == "destroying") | .state' | wc -l
```

### how to kill a process ini such state?

given that once the process is thawed, the kernel will "do the right thing"™️ and forcibly terminate the process, all we need is a mechanism for doing so.

there's been a very recent PR to `runc` to deal with that: https://github.com/opencontainers/runc/pull/2106.
