### ISSUE TITLE
Failed to pull from private docker registry. Bad request.

### ISSUE THREAD

**Issue by mdomke** [concourse/concourse#448]
We are running a private docker registry with a self-signed certificate, where I'm trying to pull an image from.

My pipeline configuration file looks like this:

```yaml
resources:

- name:my-repo
  type: git
  source:
  # ..

jobs:
- name: package
  plan:
  - get: my-repo
    trigger: true
  - task: build-package
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: my.registry.tld:5043/myrepo/python-builder
          insecure_registries: ["my.registry.tld:5043"]
          username: user
          password: passwd
          email: me@email.com
      run:
        path: "/tmp/run.sh"
```

The registry is basically setup following the example in the [docker docs](https://docs.docker.com/registry/nginx/). The logs of the nginx reverse proxy say

```nginx
nginx_1     | 172.17.0.1 - - [20/May/2016:12:19:43 +0000] "GET /v2 HTTP/1.1" 301 185 "-" "Go-http-client/1.1" "-"
nginx_1     | 172.17.0.1 - - [20/May/2016:12:19:44 +0000] "GET /v2 HTTP/1.1" 301 185 "-" "Go-http-client/1.1" "-"
nginx_1     | 172.17.0.1 - - [20/May/2016:12:19:46 +0000] "GET /v2 HTTP/1.1" 301 185 "-" "Go-http-client/1.1" "-"
nginx_1     | 172.17.0.1 - - [20/May/2016:12:19:50 +0000] "GET /v2 HTTP/1.1" 301 185 "-" "Go-http-client/1.1" "-"
nginx_1     | 172.17.0.1 - - [20/May/2016:12:19:58 +0000] "GET /v2 HTTP/1.1" 301 185 "-" "Go-http-client/1.1" "-"
nginx_1     | 172.17.0.1 - - [20/May/2016:12:20:14 +0000] "GET /v2 HTTP/1.1" 400 271 "-" "Go-http-client/1.1" "-"
nginx_1     | 172.17.0.1 - - [20/May/2016:12:20:14 +0000] "GET /v2/myrepo/python-builder/manifests/latest HTTP/1.1" 400 271 "-" "Go-http-client/1.1" "-"
```

The output of the test-job is

```log
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 400 Bad Request

errored
```

Is this supposed to work or does it fail because of #27?
