### ISSUE TITLE
Problem upgrading to 5.5: TaskConfig.caches

### ISSUE THREAD

**Issue by mohsen0** [concourse/concourse#4512]
In the task files, if the path field is not a list, the task fails with this error in concourse 5.5

```
failed to create task config from bytes git_master/ci/test.yml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field TaskConfig.caches of type []atc.TaskCacheConfig
```

``` yaml
---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: <a image>
    tag: gitsha-c630c1a
inputs:
  - name: git_resource
  - name: version
outputs:
  - name: target
caches:
  path: cache
run:
```

and changing that to

```yml
caches:
  - path: cache
```

will fix the issue.

## Expected Results

I expected to see this change as breaking change in the changelog
Maybe it can be added in the changelog

## Version Info

* Concourse version: 5.51
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?
