### ISSUE TITLE
Paramaterise task files

### ISSUE THREAD

**Issue by ymedlop** [concourse/concourse#454]
I have a pipeline YAML with configuration variables (that are read correctly) and this file references a task in another YAML file. From this file, I cannot read the configuration variables in the pipeline's scope. I have created an example of this case [here](https://gist.github.com/ymedlop/fe7d9804684971cb24d3f091119acbed ). 

Is there a way for accessing the variables from the second YAML file?

**Comment by gunta** [comment]
+1

**Comment by zachgersh** [comment]
@ymedlop why don't you just move your image definition up into your task? I think this is what you are after:

https://concourse.ci/task-step.html#task-image

**Comment by vito** [comment]
This'll become more viable with https://github.com/concourse/concourse/issues/291 - we may be able to have tasks run in the "context" of a pipeline's credential store/config source.

**Comment by holycheater** [comment]
@zachgersh and I have "volume graph is disabled" error when I try to use `image: `.
https://github.com/concourse/concourse/issues/402#issuecomment-223619301
Someone says here its unsupported.
I'm running concourse worker from an official docker image.

**Comment by clarafu** [comment]
@ymedlop The Concourse v3.3.0 introduced being able to template out the `source:` in the `image_resource` within the task file. Does this solve your issue or were you looking for only using a configuration file with `--load-from-vars`?

**Comment by eedwardsav** [comment]
I have a similar issue as above...

When developing locally, I want to be able to run tasks using local docker images in a local insecure registry.

To accomplish this I can specify a local image_resource:

```
image_resource:
  type: docker-image
  source:
    repository: local-ci:5000/my/docker/image
    insecure_registries: ["local-ci:5000"]
    tag: latest
```

or I can leave out `image_resource` entirely, and specify it on the pipeline

**The problem with that approach** is that then I can't run the task without a pipeline, and the pipeline requires a proper input resource like a commit, which means to test a small change locally I still have to:
- commit changes to repo
- wait for local ci to see it (slow)
- execute it
- repeat...
when instead, it's a lot easier to just run the task using `fly execute` and ship the source files directly to it

The only approach I see right now to deal with this is to maintain **two copies** of my tasks, one for 'local dev' and one for 'central ci'... however, I consider this an anti-pattern, since I want to use the same set of config files for local or remote CI and simply bind them differently depending on the environment

(e.g. locally I want to use my local docker repo, but on a central ci server I'll push images to a central docker repo... however the task run logic should be the same... so why would I want to maintain it twice??)

**Comment by codesuki** [comment]
@clarafu I would still like to be able to use `--load-from-vars`, we don't have a credential management server here, yet. It would be good to have a choice.

**Comment by track0x1** [comment]
agreed. this feature is much needed if you're not using credential management.

**Comment by bmhkb4** [comment]
I, too, require this.

**Comment by ralekseenkov** [comment]
Needed for us as well. Without it, it's pretty much impossible to build a good workflow around developing pipelines.

We spent a little bit of time on studying Concourse source code for external tasks (garden_factory.go, task_config_source.go, and so on) and figured out that external tasks are not very useful with params right now.

Params from cred managers works fine, but tasks cannot use pipeline params.

Example:
```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((private-image-repo))   # we want this to be passed from the pipeline
    username: ((private-image-username)) # from vault
    password: ((private-image-password)) # from vault
run:
  path: bash
  args:
    - -c
    - echo test ((another-param-from-pipeline))
```

The biggest issues right now are:

1. When pipeline is uploaded, variable resolution is done on the client side. After that all parameters which were passed with '-l' are forgotten
    - https://github.com/concourse/concourse/blob/master/fly/commands/internal/setpipelinehelpers/atc_config.go#L194

2. When task is a part of pipeline, its params can only be resolved in runtime after resource with task.yaml has been retrieved via "get". Therefore these tasks can not be pre-processed via fly

The ideal situation would be is that you just **take a task from pipeline, copy/paste it to the external file, and everything keeps working as if the task was embedded into the pipeline**.

I think one of the simplest options to achieve this behavior without changing too much code would be to:
1. Deprecate the current way of overriding params https://concourse-ci.org/task-step.html#task-step-params. It seems pretty hacky.
2. Introduce "vars" to pass to tasks and make it a preferred way of passing params
3. Render task template using the provided vars after loading its config from file source

Then you should be able to use it from the pipeline like:
```
  - task: mytask
    file: repo/mytask.yaml
    vars:
      private-image-repo: ((some-private-image-repo))
      another-param-from-pipeline: ((some-param-from-pipeline))
```

Looks pretty clean, requires minimal changes. There will be some passing params in the pipeline, but at the same time you can clearly see which parameters are expected by the task.

We might also need to do some minor changes on the fly execute side as well to support "-l".

I can take a stab on the pull request, if this sounds reasonable.
