### ISSUE TITLE
Docs or Ability for multi-site pipelines/workers

### ISSUE THREAD

**Issue by maxnbk** [concourse/concourse#4575]
I am having a difficult time understanding if this is something I can manage in any other way than the way I am thinking about it. Part of me imagines that a custom resource type could help with this, but there are other aspects that seem not covered, so I feel I must feature-request this, and then let someone tell me what fundamental thing I have ignored after poring over the docs.

I am interested in using concourse for, at first, basic unit-test and integration-test CI.

However, I am interested in a use case where the pipeline definitions are set/synced to a single concourse CI master server, but that there are site-specific workers (and possibly web nodes?) in multiple sites, because in our specific workflows, a unit, and eventually integration test, is only able to be considered complete if the tests ran correctly on workers in that specific site. (Imagine that one of your resources is a file system, and that file system could vary - These tests would be desired to be run in all sites to ensure all tests pass despite the varying filesystem)

Unfortunately from my understanding, if I set up concourse in a single-master kind of way, a test would be complete if it ran correctly in any site and not all sites.

On the flip side, I would be okay with running multiple concourse deployments, one for each site, but I desire a way to keep all of the pipelines "set" identically in all sites, so that by setting a pipeline in one site, I have set it in all sites, ensuring all tests run in all sites. A pipeline being manually triggered need not necessarily trigger in another site, but the typical "being triggered by version control" use-case should mean that the tests are run everywhere eventually, even if someone tests a bunch local to their site first.

The only way I can see this happening is, rather volatiley, wrappering "fly" to perform pipeline operations on all concourse deployments, and hoping that none of them are down or tweaked manually. Less than ideal.

Since all the concourse pipeline state is stored in postgres(?), perhaps there is a way to set concourse to sync pipeline state with other postgres instances, and thus maintain a degree of pipeline state sync?

Happy to be blasted out of the water with a better way to achieve this. Thanks for your thoughts/time/energy.

**Comment by pivotal-jamie-klassen** [comment]
shooting from the hip a bit here, but I'm imagining [tagged workers](https://concourse-ci.org/concourse-worker.html#worker-configuration) might suit your use-case?
if I need the integration tests to pass in `site-a` and `site-b`, maybe I do something like
```
resources:
- name: code
  type: git
  source: {uri: git@github.com:your/repo.git}
jobs:
- name: integration-tests
  plan:
  - get: code
  - in_parallel:
    - task: site-a
      tags: [site-a]
      file: code/ci/integration-tests.yml
    - task: site-b
      tags: [site-b]
      file: code/ci/integration-tests.yml
```

Does this make sense?
