### ISSUE TITLE
Task inputs not working

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#458]
According to the docs tasks can use other tasks as inputs.  However it doesn't seem to work.  Her is a simple example:

```yaml
jobs:
  - name: test-inputs
    serial: true
    plan:
      - task: create-file
        config: 
          platform: linux
          run: 
            path: touch
            args: 
              - file.ext

      - task: ls-file
        config:
          platform: linux
          inputs:
            - name: create-file
          run:
            path: ls
```

The error reported is `missing inputs: create-file`.  I tried specifying an `image_resource` too in case that was the issue but I get the same result.
