### ISSUE TITLE
Error when lidar enabled and resource and resource type have the same name

### ISSUE THREAD

**Issue by robwhitby** [concourse/concourse#4599]
## Bug Report

In Concourse 5.6.0 with lidar enabled, resources error when named the same as a resource type.

```
checking failed
base resource type not found: slack
```

## Steps to Reproduce

Create a pipeline with a resource and resource type named the same:

```yaml
resource_types:
- name: slack
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
resources:
- name: slack
  type: slack
jobs:
- name: test
  plan:
  - put: slack
```

## Version Info

* Concourse version: 5.6.0 + lidar enabled
* Did this used to work? yes, works pre 5.6

This looks like the source of the problem, but I don't understand the context well enough to propose a fix: https://github.com/concourse/concourse/blob/master/atc/db/resource_type.go#L60
