### ISSUE TITLE
Error `malformed config` when uses yaml anchors in Concourse 5.5.1

### ISSUE THREAD

**Issue by dangthanh360** [concourse/concourse#4618]
I want to change default Git branch for DEV environment to `develop`. I use YAML anchor as below: 
```yaml
git_source: &git_source
  uri: ((GIT_SSH_URI))
  private_key: ((GIT_PRIVATE_KEY))
  skip_ssl_verification: true
  branch: "master"

resources:
- name: src-((ENV_DEV))
  type: git
  source: 
    "<<": *git_source
    branch: ((GIT_BRANCH_DEV))
```

I got this error when update pipeline:
```
error: invalid pipeline config:
malformed config
```
![image](https://user-images.githubusercontent.com/22902812/67139745-a8e62680-f27d-11e9-8fec-418c40f5f1ac.png)

My `fly` version is `5.5.1`. It works normally on fly version 4
