### ISSUE TITLE
`in_parallel` using `steps:` produce `has not action specified`

### ISSUE THREAD

**Issue by EduardoAC** [concourse/concourse#4642]
## Bug Report

> Setting pipeline using `in_parallel` steps using `fly` version `5.6` generate a `{}` instead of the right sequence

Failure example
```
...
jobs:
...
  - ensure:
    name: tests
    plan:
    - in_parallel:
      steps:
        - get: service-def-candidate
          passed:
            - deploy-stage
          trigger: true
        - put: timestamp
        - get: alpine-awscli-image
```
However, this other sequence works fine:
```
...
    - in_parallel:
      - get: service-def-candidate
      - put: timestamp
      - get: alpine-awscli-image
```

## Steps to Reproduce

1. Take an existing pipeline from Concourse 4 
2. Migrate it to Concourse 5
3. Replace `aggregate` for `in_parallel`
4. Add a `limit` which require to use `steps:` 

## Expected Results

```
  - in_parallel:
      steps:
      - get: service-def-candidate
        passed:
          - deploy-stage
        trigger: true
      - put: timestamp
      - get: alpine-awscli-image
```
## Actual Results

Outcome of validation `fly validate-pipeline -c pipeline.yaml`:
```
Error loading existing config:
  - invalid jobs:
	jobs.tests.plan[0] has no action specified
```

Output set-pipeline
```
+ - {}
```

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: v5.6.0
* Deployment type: Docker

**Comment by pivotal-jamie-klassen** [comment]
@EduardoAC I haven't deeply investigated here, but something is standing out to me. In your first yaml snippet, I see
```yaml
...
    plan:
    - in_parallel:
...
```
which suggests your YAML arrays will be indented at the same level as their parent, but then slightly further down in your first snippet I see
```yaml
      steps:
        - get: service-def-candidate
```
which has the list items indented two spaces further than their parent. If you dedent the array under `steps:` does the problem go away?

**Comment by EduardoAC** [comment]
@pivotal-jamie-klassen the reason of the discrepancy. It's to reduce the amount of line that I am coding both example use exactly the same code with the exception of the content within `in_parallel`. 

Full example in the second case will look like
```
...
jobs:
...
  - ensure:
    name: tests
    plan:
    - in_parallel:
        - get: service-def-candidate
          passed:
            - deploy-stage
          trigger: true
        - put: timestamp
        - get: alpine-awscli-image
```

Which works without any problem. However the introduction of the `steps:` break the code even it's being included within the documentation
