### ISSUE TITLE
Substitute vars then lookup secrets

### ISSUE THREAD

**Issue by esauser** [concourse/concourse#4664]
## What challenge are you facing?

We frequently duplicate a decent amount of code in our pipeline yaml files due to many environments.  For example, if we have `dev`, `qa`, and `prod` we might have

```yaml
- task: flyway-info-dev
  file: ci/tasks/flyway-info.yml
  image: flyway-info
  output_mapping:
    flyway-info: flyway-info-dev
  params:
    FLYWAY_USER: ((dev-database.user))
    FLYWAY_PASSWORD: ((dev-database.password))

- task: flyway-info-qa
  file: ci/tasks/flyway-info.yml
  image: flyway-info
  output_mapping:
    flyway-info: flyway-info-qa
  params:
    FLYWAY_USER: ((qa-database.user))
    FLYWAY_PASSWORD: ((qa-database.password))

- task: flyway-info-prod
  file: ci/tasks/flyway-info.yml
  image: flyway-info
  output_mapping:
    flyway-info: flyway-info-prod
  params:
    FLYWAY_USER: ((prod-database.user))
    FLYWAY_PASSWORD: ((prod-database.password))
```

## What would make this better?

With the relatively new `vars` on tasks we were hoping we'd be able to pass `dev`, `qa`, and `prod` as an `ENV` var.  We _can_ do this, but then the secret isn't evaluated.  It would be better if it was.  If it was, our pipeline would look like this

```yaml
- task: flyway-info-dev
  file: ci/tasks/flyway-info.yml
  image: flyway-info
  vars:
    ENV: dev

- task: flyway-info-qa
  file: ci/tasks/flyway-info.yml
  image: flyway-info
  vars:
    ENV: qa

- task: flyway-info-prod
  file: ci/tasks/flyway-info.yml
  image: flyway-info
  vars:
    ENV: prod
```

and our task would look like this

```yaml
platform: linux
inputs:
  - name: pull-request
  - name: task-docker-images
outputs:
  - name: flyway-info-((ENV))
run:
  dir: pull-request
  path: ../task-docker-images/flyway-info/flyway-info.sh
  user: root
params:
  FLYWAY_USER: ((((ENV))-database.user))
  FLYWAY_PASSWORD: ((((ENV))-database.password))
```

## Are you interested in implementing this yourself?

No
