### ISSUE TITLE
Handling failures is extremely inconvenient for complex jobs

### ISSUE THREAD

**Issue by Nopik** [concourse/concourse#47]
Lets assume that there is a job which runs one task:
```
- task: task1
  file: foo/task1.yml
```
and we have some resource sending out notifications about success or failure (e.g. via email or slack). It goes like this (assuming that resources are configured):
```
- task: task1
  file: foo/task1.yml
- aggregate:
  - conditions: [success]
    put: email
    params:
      text: Success!
  - conditions: [failure]
    put: email
    params:
       text: Failure!
```

That already is increase from 2 lines to 11. Now, lets suppose that we have 2 tasks running inside job:

```
- task: task1
  file: foo/task1.yml
- aggregate:
  - conditions: [success]
    name: task1-succeeded
    do:
    - task: task2
      file: foo/task2.yml
    - aggregate:
      - conditions: [success]
        put: email
        params:
          text: Success!
      - conditions: [failure]
        put: email
        params:
           text: Failure!
  - conditions: [failure]
    put: email
    params:
       text: Failure!
```
Which is 21 lines. Adding 3rd and 4th tasks would be overkill.

I'm looking for try / catch / finally kind of approach, where one could add just one error handler at the end or something like this.

**Comment by vito** [comment]
Created https://www.pivotaltracker.com/story/show/95308862 with a proposed solution

**Comment by vito** [comment]
As of 0.57, we have replaced `conditions` with a hook-based approach:

http://concourse.ci/on-success-step.html
http://concourse.ci/on-failure-step.html
http://concourse.ci/ensure-step.html

This allows you to reduce those to...:

```yaml
- task: task1
  file: foo/task1.yml
  on_success:
    put: email
    params:
      text: Success!
  on_failure:
    put: email
    params:
       text: Failure!
```

...and...

```yaml
- do:
  - task: task1
    file: foo/task1.yml
  - task: task2
    file: foo/task2.yml
  on_success:
    put: email
    params:
      text: Success!
  on_failure:
    put: email
    params:
       text: Failure!
```

(note the use of `do` to wrap all steps in the hooks)

A later iteration that may be nice is to be able to attach these hooks to the job itself, which would allow you to remove the additional `do` nesting. Which would be nice if they're hooks that're truly added to every single job (as alerting services tends to be) where having the additional nesting gets old quick.
