### ISSUE TITLE
fly format-pipeline assumes (()) variables are strings

### ISSUE THREAD

**Issue by z4ce** [concourse/concourse#4713]
## Bug Report

`fly format-pipeline` assumes (()) variables are strings. This leads to errors when you run format-pipeline if attempt to use variables as yaml.

## Steps to Reproduce
1. Create a pipeline like:
```
resources:
- name: pipelines
  type: git
  source: ((pipelines_source))
jobs:
- name: set-pipelines
  plan:
  - get: pipelines
```
2. run `fly fp -c pipeline.yml`
3. Observe error `could not unmarshal config: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field ResourceConfig.resources.source of type atc.Source`
## Expected Results

The pipeline would be formatted and printed

## Actual Results

Got error

## Version Info

* fly  version: 5.2.0 and 5.7.0 tested

**Comment by xtremerui** [comment]
The error is specific to the type of resource source in golang, which is 

https://github.com/concourse/concourse/blob/ee6730b995688e0f7ce902a607a9b01c8bf16b0d/atc/resource_types.go#L14

So you would need to give it a key 
```
resources:
- name: pipelines
  type: git
  source:
    foo: ((pipelines_source))
jobs:
- name: set-pipelines
  plan:
  - get: pipelines
```
works fine. 

In your example it would return same error when doing `fly set-pipeline`. So it is a case concousre doesn't support.

**Comment by z4ce** [comment]
@xtremerui `fly set-pipeline` does work this if you do:

`fly sp -p foo -c pipelline.yml -l my-vars.yml`

pipeline.yml:
```yaml
resources:
- name: pipelines
  type: git
  source: ((pipelines_source))
jobs:
- name: set-pipelines
  plan:
  - get: pipelines
```

my-vars.yml:
```yaml
pipelines_source:
  uri: https://github.com/foo
  branch: master
```
Basically, `fly fp` doesn't account for the fact that variables that come from variable files might be yaml and not strings.
