### ISSUE TITLE
putting the same artifact to two resources: file missing in second put?

### ISSUE THREAD

**Issue by evanshort73** [concourse/concourse#473]
We had a slack question: https://concourseci.slack.com/archives/general/p1465594650001612

"""

We're seeing some weird behavior with a task output being used by multiple put steps

So we have a task like this:
```
outputs:
- name: my-dir
```

It prints a value to a file in `my-dir/file`.

Then, we have two `put`'s in our pipeline, each of which uses the output of that task
 ```
- put: resource-1
  params:
    file_path: my-dir/file
- put: resource-2
  params:
    file_path: my-dir/file
```

The file is present in the first `put`, but not the second one

"""
