### ISSUE TITLE
fail_fast within in_parallel yields error, not failure

### ISSUE THREAD

**Issue by esauser** [concourse/concourse#4746]
## Bug Report

Occasionally jobs continue beyond `in_parallel` when `fail_fast` is set to `true` when one of the steps failed, resulting in an `error` instead of `failure`.  Below is an example of how the task immediately following the `in_parallel` looks when this occurs.  

The 7 tasks above `determine-scripts-to-execute` are within the `in_parallel`.  `test` failed and `validate-naming-standards` was interrupted correctly, but the job incorrectly continued on to `determine-scripts-to-execute` which was also killed, but not gracefully, resulting in the `error`.

![image](https://user-images.githubusercontent.com/24945592/68606417-08e27e00-0474-11ea-8b94-10bd6aceeec8.png)

This is problematic because we have steps listed on the `on_failure` hook, but not `on_error`.  When the next step does not incorrectly trigger and then get killed like this, the `in_parallel` correctly falls into `on_failure`.

## Steps to Reproduce

It is relatively difficult to cause on demand, but it is happening a fair amount in our pipelines.  We recently upgraded from 4.2.3 to 5.7.0 and have been working through to update all instances of 
```
aggregate
```
to
```
in_parallel:
  fail_fast: true
  steps
```
so we're starting to notice it more and more.  It seems to happen more often when the `in_parallel` `steps` take longer and several have started, one fails, and the others get interrupted.

## Expected Results

The task following the `in_parallel` doesn't start and it falls into `on_failure` every time.

## Actual Results

Occasionally the next task starts resulting in an error similar to above, and falling instead into `on_error`.

## Version Info

* Concourse version: 5.7.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: GKE for web, GCP Compute VMs for workers
* Did this used to work? It works as expected with `aggregate` and without `fail_fast` set to `true`.

**Comment by esauser** [comment]
@vito this is becoming increasingly more problematic.  To the point where we are considering not using `fail_fast` at all.

**Comment by vito** [comment]
@esauser Yeah noticed this too. I'll drag this in the side-road but it'd probably be faster if someone else looked into it and submitted a PR, so I'll add a 'help wanted' label.

**Comment by vito** [comment]
We try to handle the error here https://github.com/concourse/concourse/blob/77489bce14821733c9667c1c5fe64433e0dd4a4e/atc/exec/in_parallel.go#L72
but it seems like the error might be wrapped, which is why it is not caught.

- [ ] Check to see if the wrapped error is using go 1.13 error wrapping
- [ ] If using the error wrapping: can use `errors.Is` https://golang.org/pkg/errors/. If not... figure something else out.

**Comment by xtremerui** [comment]
@esauser could you specify the step type of `validate-naming-standards`, `test` and `determine-scripts-to-execute`? It looks like they are all `task` but just want to make sure.

**Comment by esauser** [comment]
@xtremerui here's the relevant job.

```yaml
  - name: pr-verify
    public: true
    plan:
      - in_parallel:
          fail_fast: true
          steps:
          - do:
              - get: pull-request
                resource: ((github_repository))-pull-request
                passed: [pr-verify-check-last-commit]
                trigger: true
                version: every

              - put: pull-request-status
                resource: ((github_repository))-pull-request
                inputs:
                  - pull-request
                params:
                  path: pull-request
                  status: pending

          - get: ci
            resource: shared-databases-ci

          - get: master
            resource: ((github_repository))

          - get: docker-image-util
          - get: validate-files
          - get: tsqllint
          - get: task-docker-images
          - get: flyway-info
          - get: validate-pending-migrations

      - in_parallel:
          fail_fast: true
          steps:
          - task: validate-files
            file: ci/tasks/validate-files.yml
            image: validate-files

          - task: tsqllint
            file: ci/tasks/tsqllint.yml
            image: tsqllint

          - task: validate-naming-standards
            file: ci/tasks/validate-naming-standards.yml
            image: docker-image-util
            params:
              DATABASE_NAME: ((databases.docker.name))

          - task: test
            file: ci/tasks/test-docker.yml
            image: docker-image-util
            input_mapping:
              test-repo: pull-request
            params:
              DATABASE_NAME: ((databases.docker.name))

          - do:
              - in_parallel:
                  fail_fast: true
                  steps:
                  - task: flyway-info-qa
                    file: ci/tasks/flyway-info.yml
                    image: flyway-info
                    output_mapping:
                      flyway-info: flyway-info-qa
                    params:
                      FLYWAY_USER: ((qa-database.user))
                      FLYWAY_PASSWORD: ((qa-database.password))
                      HOSTNAME: ((databases.qa.instance))
                      DATABASE_NAME: ((databases.qa.name))

                  - task: flyway-info-prod
                    file: ci/tasks/flyway-info.yml
                    image: flyway-info
                    output_mapping:
                      flyway-info: flyway-info-prod
                    params:
                      FLYWAY_USER: ((prod-database.user))
                      FLYWAY_PASSWORD: ((prod-database.password))
                      HOSTNAME: ((databases.prod.instance))
                      DATABASE_NAME: ((databases.prod.name))

                  - task: flyway-info-docker
                    file: ci/tasks/flyway-info-docker.yml
                    image: docker-image-util
                    output_mapping:
                      flyway-info: flyway-info-docker
                    params:
                      DATABASE_NAME: ((databases.docker.name))

              - task: determine-scripts-to-execute
                file: ci/tasks/determine-scripts-to-execute.yml
                image: docker-image-util
                params:
                  DATABASE_NAME: ((databases.docker.name))

              - task: validate-pending-migrations-docker
                file: ci/tasks/validate-pending-migrations-docker.yml
                image: docker-image-util
                input_mapping:
                  scripts-to-execute: scripts-to-execute-docker
                params:
                  DATABASE_NAME: ((databases.docker.name))
                on_failure:
                  put: slack-alert
                  inputs:
                    - sqlcmd
                  params:
                    text: |
                      ((github_repository)) validate pending migrations validate failed.
                      $ATC_EXTERNAL_URL/builds/$BUILD_ID
                      $TEXT_FILE_CONTENT
                    text_file: sqlcmd/sqlcmdOutput.file
                    channel: "#shared-databases-pri"

              - in_parallel:
                  fail_fast: true
                  steps:
                  - task: validate-pending-migrations-prod
                    file: ci/tasks/validate-pending-migrations.yml
                    image: validate-pending-migrations
                    input_mapping:
                      scripts-to-execute: scripts-to-execute-prod
                    params:
                      SQLCMDUSER: ((prod-copy-database.user))
                      SQLCMDPASSWORD: ((prod-copy-database.password))
                      SQLCMDSERVER: ((databases.prod_copy.instance)),((databases.prod_copy.port))
                      VALIDATE_DATABASE_USER: ((prod-copy-database.user))
                      DATABASE_NAME: ((databases.prod_copy.name))

                  - task: validate-pending-migrations-qa
                    file: ci/tasks/validate-pending-migrations.yml
                    image: validate-pending-migrations
                    input_mapping:
                      scripts-to-execute: scripts-to-execute-qa
                    params:
                      SQLCMDUSER: ((qa-database.user))
                      SQLCMDPASSWORD: ((qa-database.password))
                      SQLCMDSERVER: ((databases.qa.instance)),((databases.qa.port))
                      VALIDATE_DATABASE_USER: ((qa-database.user))
                      PLACEHOLDER_SOURCE: flyway-qa-placeholders.conf
                      DATABASE_NAME: ((databases.qa.name))
    on_success:
      put: pull-request-status
      resource: ((github_repository))-pull-request
      inputs:
        - pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      <<: *pull-request-status-failure
    on_abort:
      <<: *pull-request-status-failure
    on_error:
      <<: *pull-request-status-failure
```
