### ISSUE TITLE
fly execute should only upload the current working directory if its name matches a task input

### ISSUE THREAD

**Issue by goldstar611** [concourse/concourse#4828]
## Bug Report

```Fly execute``` fails if there are unreadable files in the current working directory.

## Steps to Reproduce

```
cd ~
sudo touch unreadable.file
sudo chmod 600 unreadable.file
fly -t local execute -c task.yml
```

## Expected Results

Random unreadable files in current working directory don't cause ```fly execute``` to fail

## Actual Results

```Fly execute``` fails because tar fails to open some unreadable files in current working directory

## Additional Context
task.yml

**Notice there are no inputs, so no directories should be compressed and sent to remote server**
```YAML
platform: linux

params:
  some_variable: some-default-value

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:

outputs:

caches:

run:
  path: sh
  args:
  - -exc
  - |
    apt-get update
    apt-get -y install curl wget
    whoami
    cat /etc/issue
    id
    uname -a
    echo "$some_variable"
    env
```
command and return value
```bash
user@host:~$ fly -t local execute -c task.yml
uploading user ⠸ (35.4MiB/s)

error: 'uploading user' failed: Post https://localhost:8443/api/v1/teams/main/artifacts?platform=linux: tar compress failed (exit status 2). output: "/bin/tar: ./.rnd: Cannot open: Permission denied\n/bin/tar: ./.config/htop: Cannot open: Permission denied\n/bin/tar: Exiting with failure status due to previous errors\n"

user@host:~$ ls -alh
total 400K
drwxr-xr-x 11 user  user  4.0K Nov 26 07:28 .
drwxr-xr-x  4 root root 4.0K Jun  4 09:33 ..
...
-rwxrwxr-x  1 user  user   792 Nov 26 10:52 .flyrc
...
-rw-------  1 root root 1.0K Sep  7  2018 .rnd
...
-rw-rw-r--  1 user  user   506 Nov 25 15:52 task.yml
...
```

## Version Info

* Concourse version: 5.5.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Virtual Machine
* Browser (if applicable): N/A
* Did this used to work? Yes (until some unreadable files were created)
