### ISSUE TITLE
UI should show check error

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4844]
## Bug Report

When I work on PR #4777, I forgot to configure Vault to my dev concourse, then I can't run any build. The build page shows "discovering any new version of tiny", and the resource page just shows "checking successfully". But from ATC log, I can see error:

```
web_1     | {"timestamp":"2019-11-29T02:44:09.935027500Z","level":"error","source":"atc","message":"atc.failed-to-create-check","data":{"error":"undefined vars: my-vault-token"}}
```

This bug is worse than #4811. For #4811, it at least shows error on the build page. But for this error, user will have no any hint what is the error. 

Looking at https://github.com/concourse/concourse/blob/master/atc/db/check_factory.go#L135, there are multiple places returning errors. If UI doesn't show the error, user will only request Concourse OPs to check ATC logs, which will definitely add OPs cost.

## Steps to Reproduce

The problem can be easily reproduced by the following pipeline:

```yaml
resource_types:
- name: rt-tiny
  type: registry-image
  source:
    repository: evanli/tiny2
    tag: v4

resources:
- name: tiny
  type: rt-tiny
  source:
    key: ((foobar)) # foobar is a non-exist var

jobs:
- name: test
  public: true
  plan:
  - get: tiny
```

## Expected Results

UI shows some error like "unknown var foobar".

## Actual Results

UI doesn't show any error, but build cannot start.

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 5.7, but the problem should exist on all versions
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?
