### ISSUE TITLE
"fly set-team" shows unclear message when there is a role having no user and group

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4852]
## Bug Report

For example, we use this team file:

```yaml
name: some-team
roles:
- name: owner
  local:
    users:
    - test
- name: member
  ldap:
    users:
    - user1
    - user2
- name: viewer
  ldap:
    users: []
```

Then `fly set-team` will raise an error:

```
$ fly -t prod set-team --team-name some-team -c some-team.yml                          
You have not provided a list of users and groups for one of the roles in your config yaml.
```

This error message is very confused. Then I checked the code https://github.com/concourse/concourse/blob/master/skymarshal/skycmd/flags.go#L136:

```go
		if len(users) == 0 && len(groups) == 0 {
			return nil, ErrAuthNotConfiguredFromFile
		}
```

So if a role has no any user and group defined, then `fly set-team` will raise such an error.

Why don't just ignore the role if there is no user and group? Is there any special consideration?

We have a use case, where we maintain a team file, and dynamically assign on-duty folks as pipeline-operator, sometime there is no pipeline-operator. With this bug, when there is no pipeline-operator on-duty, we have to delete the operator role from the team file, which is inconvenient. 

## Steps to Reproduce

As described above.

## Expected Results

Ignore roles without user and group.

## Actual Results

`fly` returned an error, and the error message is not clear.

## Version Info

* Concourse version: 5.7.2
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?
