### ISSUE TITLE
Core: automatically archive pipelines produced by builds whose job no longer configure them

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4873]
Say I have a job with the following build plan:

```yaml
plan:
- set_pipeline: a
- set_pipeline: b
```

Given that I've run the build, configuring pipelines `a` and `b`, and then re-configure the job as follows:

```yaml
plan:
- set_pipeline: a
```

When a new build runs, the `b` pipeline should be automatically archived.
