### ISSUE TITLE
Angular 8 Builds Hanging Upon Completion

### ISSUE THREAD

**Issue by rosshardy** [concourse/concourse#4891]
## Bug Report

My company is running into an issue where Angular 8 builds are hanging in Concourse upon completion of the build. This is only happening in Angular 8, and only in Concourse. 

## Steps to Reproduce

1. Generate a brand new Angular 8 app using the Angular CLI. 
2. Run the task below to build the app. 

## Expected Results

The build task to complete. 

## Actual Results

The build _appears_ to reach completion based the output (I’m using --verbose and comparing progress against local builds), however Concourse hangs upon completing the build. 

## Additional Context

Task: 
```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 11.12
inputs:
  - name: source
run:
  path: sh
  args:
  - -exc
  - |
    eval "export NG_CLI_ANALYTICS=ci"
    cd "source/myApp"
    eval "npm install"
    eval "./node_modules/.bin/ng build --verbose"
```

Hijacking into the container, I can see the `ng build` process is still running via `top`, but it’s not using any CPU. I can also run the build via with fly execute, same behavior. 

We have tried various things like changing the base image, redirecting the build output, and more, without any luck. 

## Version Info

Concourse v5.4.1
Angular 8.2
Concourse deployed via Helm on Kuberenetes on top of EC2 (I can dig up version details if needed)

**Comment by rosshardy** [comment]
Posted on forum as well a few days back, but no responses yet. 

https://discuss.concourse-ci.org/t/angular-8-builds-hanging-upon-completion/1932/2

**Comment by pivotal-jamie-klassen** [comment]
@rosshardy I just spent an hour trying to reproduce this with `fly execute` and every time my build succeeded. I tried it against 5.4.1 deployed with docker-compose and 5.7.2 deployed on k8s with various combinations of inputs and outputs. The only place I can think to look is at what else might be going on in your `source` input - what exactly did you mean by 'Generate a brand new Angular 8 app'? This is the task I ended up using for testing, so maybe you can see some obvious difference between what I'm doing and what you have been doing:
```yaml
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 11.12
run:
  path: sh
  args:
  - -exc
  - |
    npm init -y
    npm install @angular/cli@8.2
    ./node_modules/.bin/ng new myApp --defaults
    cd myApp
    ../node_modules/.bin/ng build --verbose
```

If you run my task config here, do you get the error?

**Comment by rosshardy** [comment]
@pivotal-jamie-klassen thank you very much for looking into this. 

I ran this same task on Concourse at my company and it hung upon completing the step: 
`./node_modules/.bin/ng new myApp --defaults` The last output was `Successfully initialized git.` then hang. 

I did have to add these 3 lines: 
```
export NG_CLI_ANALYTICS=ci
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
so that I wouldn't get prompted to report analytics to Google, and so that when creating the Angular project Git wouldn't complain about who I am.

**Comment by pivotal-jamie-klassen** [comment]
@rosshardy Coming back to this Monday morning, I do get the angular CLI prompting about analytics. Good catch, I guess I wasn't doing quite what I said. Anyway, to get us on the same page, now when I run

```yaml
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 11.12
run:
  path: sh
  args:
  - -exc
  - |
    export NG_CLI_ANALYTICS=ci
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    npm init -y
    npm install @angular/cli@8.2
    ./node_modules/.bin/ng new myApp --defaults
    cd myApp
    ../node_modules/.bin/ng build --verbose
```

My build does not hang. Does yours? If it does, you can reasonably start to investigate if there's something funny in your Concourse cluster. Otherwise I'd look more closely at whatever you were doing to 'Generate a brand new Angular 8 app' before.
