### ISSUE TITLE
setting pipeline  with`var_source` of type `vault` with `auth_params` fails

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4934]
## Bug Report

While performing acceptance on #4927 I configured a vault server with the approle auth backend. When I tried to set a pipeline that made use of this vault server as a var_source, I got some wacky errors.

## Steps to Reproduce

1. I used the following `docker-compose.override.yml`:

```yaml
version: '3'
services:
  vault:
    image: vault
    cap_add: [IPC_LOCK]
    ports: ["8200:8200"]
    volumes:
    - ./vault-config:/vault/config
    command: server
```

and the directory `./vault-config` contains the following `config.hcl`:

```hcl
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = true
}

storage "file" {
  path = "/vault/file"
}
```

With this configuration running against my local Docker server, I followed the [approle instructions from our docs](https://concourse-ci.org/vault-credential-manager.html#vault-approle-auth) to set up the approle auth backend. Then I tried to run `fly -t dev set-pipeline -p pipeline -c pipeline.yml` with the following `pipeline.yml`

```yaml
var_sources:
- name: vault
  type: vault
  config:
    url: http://vault:8200
    path_prefix: concourse
    auth_backend: approle
    auth_params:
      role_id: "<the role id i got when following instructions>"
      secret_id: "<the secret id i got when following instructions>"
jobs:
- name: test
  public: true
  plan:
  - task: echo-secret
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: echo
        args: ["((vault:text))"]
```

## Expected Results

```
pipeline created!
you can view your pipeline here: http://localhost:8080/teams/main/pipelines/pipeline
```

## Actual Results

```
could not reach the Concourse server called dev:

    Put http://localhost:8080/api/v1/teams/main/pipelines/pipeline/config: EOF

is the targeted Concourse running? better go catch it lol
```

## Additional Context

when I look in the web logs, I see
```
2019/12/19 16:01:50 http: panic serving 172.20.0.1:46490: interface conversion: interface {} is map[string]interface {}, not map[string]string
goroutine 1709 [running]:
net/http.(*conn).serve.func1(0xc000696460)
	/usr/local/go/src/net/http/server.go:1767 +0x149
panic(0x33f7de0, 0xc00089c390)
	/usr/local/go/src/runtime/panic.go:679 +0x1e0
github.com/concourse/concourse/atc/creds/vault.(*VaultManager).Config(0xc00062e1e0, 0xc00089c300)
```

so I'm thinking [this type cast](https://github.com/concourse/concourse/blob/master/atc/creds/vault/manager.go#L135) doesn't work.

## Version Info

* Concourse version: 5.8.0 RC (master)
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): n/a
* Did this used to work? no
