### ISSUE TITLE
`var_source` of type `vault` errors when CA contents are passed to `ca_cert` field

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4935]
## Bug Report

While performing acceptance on #4927, I was following the instructions in [our docs](https://concourse-ci.org/vault-credential-manager.html) and ended up setting up a vault server with TLS enabled. So when I tried to run a test pipeline, I used the `ca_cert` field and instinctively pasted the CA I generated into that field as a multi-line YAML string. Unfortunately this gave an error!

## Steps to Reproduce

`docker-compose up` with the following `docker-compose.override.yml`:
```yaml
version: '3'
services:
  web:
    volumes:
    - ./vault-certs:/vault-certs
  vault:
    image: vault
    cap_add: [IPC_LOCK]
    ports: ["8200:8200"]
    volumes:
    - ./vault-config:/vault/config
    - ./vault-certs:/vault/certs
    command: server
```
where `./vault-config` contains this `config.hcl`:
```hcl
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_cert_file = "/vault/certs/vault.crt"
  tls_key_file = "/vault/certs/vault.key"
}

storage "file" {
  path = "/vault/file"
}
```
and `./vault-certs` contains `vault-ca.crt` (the CA), `vault.crt` and `vault.key` (a certificate signed by that CA, and its private key).

Then follow the steps in our docs for [configuring the secrets engine](https://concourse-ci.org/vault-credential-manager.html#configuring-the-secrets-engine), and do a `vault write /concourse/main/text value='Hello World!'`.

Then run `fly -t dev set-pipeline -p pipeline -c pipeline.yml` where `pipeline.yml` is:
```yaml
var_sources:
- name: vault
  type: vault
  config:
    url: https://vault:8200
    path_prefix: concourse
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      MIIE5jCCAs6... contents of vault-ca.crt
      -----END CERTIFICATE-----
    client_token: "<client token from https://concourse-ci.org/vault-credential-manager.html#vault-periodic-token>"
jobs:
- name: test
  public: true
  plan:
  - task: echo-secret
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: echo
        args: ["((vault:text))"]
```
Then unpause the pipeline and run `fly -t dev trigger-job -w -j pipeline/test`.

## Expected Results

```
started pipeline/test #1

initializing
fetching busybox@sha256:24fd20af232ca4ab5efbf1aeae7510252e2b60b15e9a78947467340607cd2ea2
322973677ef5 [======================================] 743.1KiB/743.1KiB
running echo Hello World!
Hello World!
succeeded
```

## Actual Results

```
started pipeline/test #1

create var_source 'vault' error: Error loading CA File: open -----BEGIN CERTIFICATE-----
MIIE5jC... contents of vault-ca.crt
-----END CERTIFICATE-----
: file name too long
errored
```

## Additional Context

I tried changing the value of `ca_cert` to `/vault-certs/vault-ca.crt` and it worked, but since I see a different parameter called [`ca_path`](https://github.com/concourse/concourse/blob/master/atc/creds/vault/manager.go#L121) I would expect that `ca_cert` should contain the contents of the cert itself, rather than a filesystem path.

## Version Info

* Concourse version: 5.8.0 RC (master)
* Deployment type (BOSH/Docker/binary): docker-compose
* Infrastructure/IaaS: local
* Browser (if applicable): n/a
* Did this used to work? no
