### ISSUE TITLE
Executing tasks does not stream output

### ISSUE THREAD

**Issue by wezzynl** [concourse/concourse#4939]
## Bug Report

`fly execute` does not stream task output while running task.

## Steps to Reproduce

Run a task using `fly execute`.

## Expected Results

The output of the running task to stream into the terminal, seeing output as it happens.

## Actual Results

Output looks like being buffered and only shows when a task completes or errors. So `executing build X at https://Y` is what you see when you start the task and only after the task finishes or errors you see the output that the task has generated. Previously, in 5.7.0 and before, task output would stream into the terminal.

## Version Info

* Concourse version: 5.7.2
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: On-premise, Kubernetes
* Did this used to work? Yes, versions before 5.7.2.

**Comment by pivotal-jamie-klassen** [comment]
@wezzynl can you give an example task? Does the same task in a pipeline have this issue too, or just `fly execute`? I also have to wonder - do you have [secret redaction](https://concourse-ci.org/creds-redacting.html) enabled?

It is striking that this worked for you in v5.7.0, since we noted that v5.7.0 suffered from #4799 and the point of putting #4817 into v5.7.2 was to fix issues like this!

**Comment by wezzynl** [comment]
@pivotal-jamie-klassen I do not have secret redaction enabled (it's off by default, right?). Running the job in the web interface it works correctly, streaming output as it comes in.

Now that you mention 5.7.0 I'm not 100% sure anymore, the version before I upgraded might be indeed before 5.7.0. I am sure I'm running 5.7.2 now though. ;)

I ran a quick test with a simple task:

tasks/ci/tasks/test.yml
```yml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: private.local.repo/some-image
    tag: latest
    username: ((registry-username))
    password: ((registry-password))

inputs:
  - name: tasks

run:
  path: ./tasks/ci/build/scripts/test.sh

```

tasks/ci/build/scripts/test.sh

```sh
#!/bin/sh

set -e

echo "line 1"
sleep 10
echo "line 2"
sleep 10
echo "line 3"
```

When running `fly -t ss execute --input tasks=../../ -c tasks/test.yml --load-vars-from=vars.yml` first it shows this:

```
uploading tasks done
executing build 96 at https://xxx/builds/96
initializing
running ./tasks/ci/build/scripts/test.sh
```

Then after some time it dumps the echo's of the task output at once instead of one by one with a 10 second delay inbetween :

```
line 1
line 2
line 3
succeeded
```
