### ISSUE TITLE
less restrictive "passed" semantics for fan-in on a microservices monorepository 

### ISSUE THREAD

**Issue by tkellen** [concourse/concourse#4949]
## What challenge are you facing?
I want to visually show that a task depends on a successful build of numerous discrete jobs that will never share the same commit.

I have a monorepository that deploys ~20 odd microservices. Our `master` pipeline has one build/deploy job per project. Each project build/deploy job pair has its own resource watching the master branch for changes in its project folder only. I would like to "fan in" off of all the project deploys builds to run e2e testing.

Current "passed" semantics assume there will be one shared commit for all "passing" builds. In my context, this commit will never occur without making a spurious dummy commit affecting all projects. Each project is self-contained even though it appears on the same pipeline.

## What would make this better?
If it was possible to indicate that passing only required a current/successful build of the dependent tasks.

## Are you interested in implementing this yourself?
Yes! I just need feedback on the approach. I see two possible solutions:
```
plan:
- get: a
  anyPassed: [a-unit, integration]
- get: b
  anyPassed: [b-unit, integration]
- get: x
  anyPassed: [integration]
```
...or
```
plan:
- get: a
  passed:
  - name: a-unit
    group: null (my semantics, we don't care about the same commits between these) 
  - name: integration
    group: null (my semantics, we don't care about the same commits between these)
- get: b
  passed:
  - name: b-unit
    group: pass-group (existing semantics but allowed to group different sets of passing)
  - name: integration
    group: pass-group (existing semantics but allowed to group different sets of passing)
- get: x
  passed: ['integration'] (existing semantics)
```

**Comment by vito** [comment]
Hey, I think I have a vague notion of the problem you're talking about but it's so far off in my memory that I'm having a hard time piecing it together from the example given so far. Would you be able to provide a working example to demonstrate the use case? This stuff's tricky to convey with words. :sweat_smile: Thanks in advance!

Here's my attempt, but I found myself with more questions than answers (embedded as comments):

```yaml
---
resources:
- name: a
  type: git
  source:
    uri: ...
    paths: [a/]

- name: b
  type: git
  source:
    uri: ...
    paths: [b/]

- name: x
  # does this relate to a or b or is it just here for example?
  # type:
  # source:

jobs:
- name: a-unit
  plan:
  - get: a

- name: b-unit
  plan:
  - get: b

- name: integration
  plan:
  - get: a
    passed: [a-unit]
  - get: b
    passed: [b-unit]
  - get: x
    # does this relate to a-unit or b-unit?

  # actually, i guess if you're integrating everything, is 'x' actually the
  # monorepo itself?

- name: ship
  plan:
  - get: a
    # why not just depend on [integration] here?
    passed: [a-unit, integration]
  - get: b
    passed: [b-unit, integration]
  - get: x
    passed: [integration]
```

**Comment by tkellen** [comment]
Hi! Just wanted to drop a note to say thanks for taking the time to respond, and that I can provide a fully working example tomorrow. The example code I shared was just copied from the Concourse docs around existing `passed` semantics, sorry if it was confusing!

**Comment by tkellen** [comment]
Well, this is quite verbose. Basically, every project folder has one of these (an Inceptionfile):
```
project:
  wip: true
  name: service-echo
  repository:
    prefix: <redacted>.dkr.ecr.us-east-1.amazonaws.com/<redacted>
  groups:
  - all
  - services
  commands:
    build: make
    test: make test
    version: make version
    manifest: make manifest
    deploy: make deploy
  triggers:
    build:
    - src/*
    - Dockerfile
    - Makefile
    - ../shared/components/go/endpoints/*
    - ../shared/components/go/version/*
    deploy:
    - ../../bin/versions
    - ../../bin/render-manifest
    - infrastructure/deployments/base/*
    - infrastructure/deployments/${DEPLOYMENT_NAME}/*
    - ../shared/kubernetes/*
```

Then we have automation that watches for commits to any branch.  Branches that match a specified regex are checked against concourse itself to see if there is a matching pipeline. If there isn't, the system creates an "empty" pipeline waiting to be unpaused. Once it is unpaused the pipeline runs the "curate-pipeline" task which introspects the branch looking for any Inceptionfile where `wip` is true. The pipeline then rewrites itself, adding the projects which are wip, in this form:

```yaml
groups:
- jobs:
  - build-service-poller
  - deploy-service-poller
  - build-service-echo
  - deploy-service-echo
  - e2e-test
  name: all
- jobs:
  - build-service-poller
  - deploy-service-poller
  - build-service-echo
  - deploy-service-echo
  name: services
- jobs:
  - curate-pipeline
  - initialize-ephemeral-environment
  name: ∞ tasks
jobs:
- name: build-service-poller
  plan:
  - get: service-poller-sources
    trigger: true
  - try:
      config:
        container_limits: {}
        image_resource:
          source:
            repository: ((registry/base))/ci-ops
          type: docker-image
        inputs:
        - name: service-poller-sources
        outputs:
        - name: build
        params:
          AWS_DEFAULT_REGION: us-east-1
          IMAGE: service-poller
          REGISTRY_ID: ((registry/aws-account-id))
        platform: linux
        run:
          args:
          - -o
          - pipefail
          - -c
          - |-
            SHA=$(cd service-poller-sources && git rev-parse HEAD) && \
            highlight() { echo -e "\e[1;34m$1\e[0m"; } && \
            printf "reading build triggers in projects/service-poller/Inceptionfile...\n" && \
            printf '["projects/service-poller/src/*","projects/service-poller/Dockerfile","projects/service-poller/Makefile","projects/service-poller/../shared/components/go/endpoints/*","projects/service-poller/../shared/components/go/version/*"]' | jq && \
            printf "last commit to change project build triggers: $(highlight ${SHA})" && \
            printf "\nexisting container tags:\n" && \
            aws ecr list-images --registry-id ${REGISTRY_ID} --repository "${IMAGE}" --filter "tagStatus=TAGGED" \
              | jq -re '.imageIds[].imageTag' | sed "s|${SHA}|$(highlight ${SHA})|g" | tee /dev/tty | grep -q ${SHA} && \
              echo -e "\nFOUND: skipping build" || { echo -e "\nMISSING: running build"; exit 1; }
          path: bash
      on_failure:
        do:
        - config:
            container_limits: {}
            image_resource:
              source:
                repository: ((registry/base))/ci-build
              type: docker-image
            inputs:
            - name: service-poller-sources
            outputs:
            - name: build
            params:
              PROJECT_PATH: service-poller-sources/projects/service-poller
            platform: linux
            run:
              args:
              - -c
              - (cd ${PROJECT_PATH} && make) && cp -r ${PROJECT_PATH}/* build
              path: bash
          task: build-service-poller
        - inputs:
          - service-poller-sources
          - build
          params:
            build: build
            skip_download: true
            tag_as_latest: false
            tag_file: service-poller-sources/.git/ref
          put: service-poller
      task: build-skip-gate
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-ops
        type: docker-image
      inputs:
      - name: service-poller-sources
      - name: build
      params:
        AWS_DEFAULT_REGION: us-east-1
        IMAGE: service-poller
        REGISTRY_ID: ((registry/aws-account-id))
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - |-
          SHA=$(cd service-poller-sources && git rev-parse HEAD)
          MANIFEST=$(aws ecr batch-get-image --registry-id ${REGISTRY_ID} --repository-name "${IMAGE}" --image-ids imageTag="${SHA}")
          printf "show sha tagged container manifest:\n"
          echo $MANIFEST | jq -re '.images[0].imageManifest' | jq || { printf "ERROR/MISSING: assuming build or container push failed"; exit 1; }
          aws ecr describe-image-scan-findings --registry-id ${REGISTRY_ID} --repository-name "${IMAGE}" --image-id imageTag="${SHA}" || true
        path: bash
    task: audit-container
  serial: true
- name: deploy-service-poller
  plan:
  - in_parallel:
      steps:
      - get: service-poller-sources
        passed:
        - build-service-poller
        trigger: true
      - get: service-poller-ephemeral
        trigger: true
      - get: sample
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-ops
        type: docker-image
      inputs:
      - name: sample
      outputs:
      - name: manifest
      params:
        BRANCH_NAME: sample
        DEPLOYMENT_NAME: ephemeral
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - |-
          (
            export PATH=${PATH}:${PWD}/sample/bin && \
            cd sample/projects/service-poller && \
            ([[ "latest-build" == "latest-build" ]] && export TAG=$(make version) || true) && \
            make manifest \
          ) | tee manifest/resources.yml
        path: bash
    task: render-service-poller-ephemeral-manifest
  - params:
      kubectl: apply -f manifest/resources.yml
      wait_until_ready: 0
    put: dev-cluster
- name: build-service-echo
  plan:
  - get: service-echo-sources
    trigger: true
  - try:
      config:
        container_limits: {}
        image_resource:
          source:
            repository: ((registry/base))/ci-ops
          type: docker-image
        inputs:
        - name: service-echo-sources
        outputs:
        - name: build
        params:
          AWS_DEFAULT_REGION: us-east-1
          IMAGE: service-echo
          REGISTRY_ID: ((registry/aws-account-id))
        platform: linux
        run:
          args:
          - -o
          - pipefail
          - -c
          - |-
            SHA=$(cd service-echo-sources && git rev-parse HEAD) && \
            highlight() { echo -e "\e[1;34m$1\e[0m"; } && \
            printf "reading build triggers in projects/service-echo/Inceptionfile...\n" && \
            printf '["projects/service-echo/src/*","projects/service-echo/Dockerfile","projects/service-echo/Makefile","projects/service-echo/../shared/components/go/endpoints/*","projects/service-echo/../shared/components/go/version/*"]' | jq && \
            printf "last commit to change project build triggers: $(highlight ${SHA})" && \
            printf "\nexisting container tags:\n" && \
            aws ecr list-images --registry-id ${REGISTRY_ID} --repository "${IMAGE}" --filter "tagStatus=TAGGED" \
              | jq -re '.imageIds[].imageTag' | sed "s|${SHA}|$(highlight ${SHA})|g" | tee /dev/tty | grep -q ${SHA} && \
              echo -e "\nFOUND: skipping build" || { echo -e "\nMISSING: running build"; exit 1; }
          path: bash
      on_failure:
        do:
        - config:
            container_limits: {}
            image_resource:
              source:
                repository: ((registry/base))/ci-build
              type: docker-image
            inputs:
            - name: service-echo-sources
            outputs:
            - name: build
            params:
              PROJECT_PATH: service-echo-sources/projects/service-echo
            platform: linux
            run:
              args:
              - -c
              - (cd ${PROJECT_PATH} && make) && cp -r ${PROJECT_PATH}/* build
              path: bash
          task: build-service-echo
        - inputs:
          - service-echo-sources
          - build
          params:
            build: build
            skip_download: true
            tag_as_latest: false
            tag_file: service-echo-sources/.git/ref
          put: service-echo
      task: build-skip-gate
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-ops
        type: docker-image
      inputs:
      - name: service-echo-sources
      - name: build
      params:
        AWS_DEFAULT_REGION: us-east-1
        IMAGE: service-echo
        REGISTRY_ID: ((registry/aws-account-id))
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - |-
          SHA=$(cd service-echo-sources && git rev-parse HEAD)
          MANIFEST=$(aws ecr batch-get-image --registry-id ${REGISTRY_ID} --repository-name "${IMAGE}" --image-ids imageTag="${SHA}")
          printf "show sha tagged container manifest:\n"
          echo $MANIFEST | jq -re '.images[0].imageManifest' | jq || { printf "ERROR/MISSING: assuming build or container push failed"; exit 1; }
          aws ecr describe-image-scan-findings --registry-id ${REGISTRY_ID} --repository-name "${IMAGE}" --image-id imageTag="${SHA}" || true
        path: bash
    task: audit-container
  serial: true
- name: deploy-service-echo
  plan:
  - in_parallel:
      steps:
      - get: service-echo-sources
        passed:
        - build-service-echo
        trigger: true
      - get: service-echo-ephemeral
        trigger: true
      - get: sample
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-ops
        type: docker-image
      inputs:
      - name: sample
      outputs:
      - name: manifest
      params:
        BRANCH_NAME: sample
        DEPLOYMENT_NAME: ephemeral
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - |-
          (
            export PATH=${PATH}:${PWD}/sample/bin && \
            cd sample/projects/service-echo && \
            ([[ "latest-build" == "latest-build" ]] && export TAG=$(make version) || true) && \
            make manifest \
          ) | tee manifest/resources.yml
        path: bash
    task: render-service-echo-ephemeral-manifest
  - params:
      kubectl: apply -f manifest/resources.yml
      wait_until_ready: 0
    put: dev-cluster
- name: curate-pipeline
  on_failure:
    params:
      alert_type: failed
    put: slack-notify
  plan:
  - get: sample
    trigger: true
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-ops
        type: docker-image
      inputs:
      - name: sample
      outputs:
      - name: concourse
      params:
        BRANCH_NAME: sample
        DEPLOYMENT_NAME: ephemeral
        ENVIRONMENT_NAME: dev
        PIPELINE_CAN_REWRITE_ITSELF: "true"
        PROMOTE_TO_ENVIRONMENT_NAME: ""
        STAGES_ENABLED: build,deploy
        TAG_BUILT_CONTAINERS_AS_LATEST: "false"
        TAG_DEPLOYED_CONTAINERS_WITH: latest-build
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - sample/bin/inception render-pipeline | tee concourse/pipeline.yml
        path: bash
    task: curate-pipeline
  - params:
      pipelines:
      - config_file: concourse/pipeline.yml
        name: sample
        team: main
    put: self
- name: initialize-ephemeral-environment
  on_failure:
    params:
      alert_type: failed
    put: slack-notify
  plan:
  - in_parallel:
      steps:
      - get: shared-deployments
        trigger: true
      - get: sample
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-ops
        type: docker-image
      inputs:
      - name: sample
      outputs:
      - name: manifest
      params:
        BRANCH_NAME: sample
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - (cd sample && bin/render-manifest projects/shared/deployments/ephemeral)
          | tee manifest/resources.yml
        path: bash
    task: render-manifest projects/shared/deployments/ephemeral
  - params:
      kubectl: apply -f manifest/resources.yml
      wait_until_ready: 0
    put: dev-cluster
- name: e2e-test
  plan:
  - in_parallel:
      steps:
      - get: sample
        passed:
        - deploy-service-poller
        - deploy-service-echo
      - get: every-ten-minutes
        trigger: true
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-build
        type: docker-image
      inputs:
      - name: sample
      outputs:
      - name: sample-e2e-build
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - |-
          printf "building and testing end-to-end automation... \n"
          (cd sample/projects && ./gradlew :e2e-automation:build)
          cp -r sample/projects/shared/e2e-automation/build/* sample-e2e-build
        path: bash
    task: sample-e2e-build
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ((registry/base))/ci-build
        type: docker-image
      inputs:
      - name: sample-e2e-build
      params:
        APPS: service-poller,service-echo
        ENVIRONMENT_NAME: dev
        NAMESPACE: sample
      platform: linux
      run:
        args:
        - -o
        - pipefail
        - -c
        - |-
          printf "run eligible tests in \e[1;34mdev\e[0m with \e[1;34m${APPS}\e[0m in namespace \e[1;34m${NAMESPACE}\e[0m\n"
          java -jar sample-e2e-build/libs/e2e-automation.jar
        path: bash
    task: end-to-end-tests
resource_types:
- name: concourse-pipeline
  source:
    repository: concourse/concourse-pipeline-resource
  type: docker-image
- name: kubernetes
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.14"
  type: docker-image
- name: slack-alert
  source:
    repository: arbourd/concourse-slack-alert-resource
  type: docker-image
resources:
- icon: ship-wheel
  name: dev-cluster
  source:
    aws_eks_cluster_name: ((eks/name))
    certificate_authority: ((eks/ca))
    server: ((eks/host))
    use_aws_iam_authenticator: true
  type: kubernetes
- name: every-ten-minutes
  source:
    interval: 10m
  type: time
- icon: git
  name: sample
  source:
    branch: sample
    private_key: ((repo/private_key))
    uri: ssh://((repo/username))@git-codecommit.us-east-1.amazonaws.com/v1/repos/geneva
  type: git
- icon: concourse-ci
  name: self
  source:
    target: http://concourse.ci.svc.cluster.local:8080
    teams:
    - name: main
      password: ((fly/password))
      username: ((fly/username))
  type: concourse-pipeline
- icon: docker
  name: service-echo
  source:
    repository: ((registry/base))/service-echo
  type: docker-image
- icon: git
  name: service-echo-ephemeral
  source:
    branch: sample
    paths:
    - projects/service-echo/../../bin/versions
    - projects/service-echo/../../bin/render-manifest
    - projects/service-echo/infrastructure/deployments/base/*
    - projects/service-echo/infrastructure/deployments/ephemeral/*
    - projects/service-echo/../shared/kubernetes/*
    private_key: ((repo/private_key))
    uri: ssh://((repo/username))@git-codecommit.us-east-1.amazonaws.com/v1/repos/geneva
  type: git
- icon: git
  name: service-echo-sources
  source:
    branch: sample
    paths:
    - projects/service-echo/src/*
    - projects/service-echo/Dockerfile
    - projects/service-echo/Makefile
    - projects/service-echo/../shared/components/go/endpoints/*
    - projects/service-echo/../shared/components/go/version/*
    private_key: ((repo/private_key))
    uri: ssh://((repo/username))@git-codecommit.us-east-1.amazonaws.com/v1/repos/geneva
  type: git
- icon: docker
  name: service-poller
  source:
    repository: ((registry/base))/service-poller
  type: docker-image
- icon: git
  name: service-poller-ephemeral
  source:
    branch: sample
    paths:
    - projects/service-poller/../../bin/versions
    - projects/service-poller/../../bin/render-manifest
    - projects/service-poller/infrastructure/deployments/base/*
    - projects/service-poller/infrastructure/deployments/ephemeral/*
    - projects/service-poller/../shared/kubernetes/*
    private_key: ((repo/private_key))
    uri: ssh://((repo/username))@git-codecommit.us-east-1.amazonaws.com/v1/repos/geneva
  type: git
- icon: git
  name: service-poller-sources
  source:
    branch: sample
    paths:
    - projects/service-poller/src/*
    - projects/service-poller/Dockerfile
    - projects/service-poller/Makefile
    - projects/service-poller/../shared/components/go/endpoints/*
    - projects/service-poller/../shared/components/go/version/*
    private_key: ((repo/private_key))
    uri: ssh://((repo/username))@git-codecommit.us-east-1.amazonaws.com/v1/repos/geneva
  type: git
- icon: git
  name: shared-deployments
  source:
    branch: sample
    paths:
    - bin/render-manifest
    - projects/ci-inception/*
    - shared/concourse/*
    - projects/shared/kubernetes/*
    - projects/shared/deployments/ephemeral/*
    - projects/shared/monitoring/*
    private_key: ((repo/private_key))
    uri: ssh://((repo/username))@git-codecommit.us-east-1.amazonaws.com/v1/repos/geneva
  type: git
- name: slack-notify
  source:
    channel: ""
    url: ((slack/webhook))
  type: slack-alert
```

Every test in our e2e suite is tagged with which apps are required for the test to run. In this manner the e2e suite runs the appropriate tests no matter what is being worked on. Right now, the test will never run unless a file which is shared between two projects is changed in a single commit.

...does that make any sense? The config is way too long to just read, I *think* you'll be able to import it into a blank concourse to see the layout. If not, maybe a brief pairing session to demo this would be good? Basically we just have one pipeline that we create by hand and the rest of the system just manages itself.

**Comment by tkellen** [comment]
PS: as somewhat of an aside, the fact that concourse can tolerate successfully having its pipelines rewrite themselves and that the UI just updates automatically and everything works is flipping amazing. Ya'll have made an amazing tool and I love using it.

**Comment by tkellen** [comment]
Also, here is what the pipeline looks like:
![pipeline](https://user-images.githubusercontent.com/1004324/71527861-32802900-28ab-11ea-8b26-f06dd8441237.png)

`service-echo-sources` triggers a `build-service-echo` when the source files for the echo service change (enumerated under `project.triggers.build` in per-project config file I shared at the top of https://github.com/concourse/concourse/issues/4949#issuecomment-569151538). 

A successful build of `build-service-echo` triggers `deploy-service-echo` (it is also possible to trigger a `deploy-service-echo` on changes to deployment config files only, which are enumerated in `project.triggers.deploy`).

The above pipeline is created for every project where `wip` is true. It is possible during the course of work to push commits turning as many services on or off as you need.

What I want to have happen which I do not believe concourse can do currently, is have `e2e-test` run only after all services have been deployed at least once, and run every time any time any of the services has a new successful build. The reason it doesn't trigger, based on my understanding, is that all deploy jobs need to have a passing build from the same commit. This happens very rarely in my work (only when we edit some common shared config file like the base kubernetes deployment manifest that all projects use).

**Comment by tkellen** [comment]
If you're reading this via email I've pedantically edited my comment a few times in the hopes that I have used the precise correct terminology to communicate the issue... please read the actual issue on github and sorry for the runaround!

**Comment by tkellen** [comment]
Well. That took a bit. Here's a shell script that reproduces the issue. To run it you must:
1. Change `REPO` a git repo URI you can push to from your local machine.
2. Change `CONCOURSE_TARGET` to point to a concourse in your `~/.flyrc` (that can also clone the repo located at `REPO`).
3. Not have a folder `test-folder` in the directory where you execute the script (at least, not the very first time).
4. The script will run, push some initial commits to master, make a feature branch, create a pipeline, pause with instructions, push another commit, and then the issue will be visible.

It should be possible to run this as many times as you need and it will replace the pipeline with a new one pointing to a new branch each time.
```sh
#!/usr/bin/env bash
REPO="https://github.com/tkellen/concourse-passed-issue.git"
CONCOURSE_TARGET="dev"
REPO_FOLDER="test-repo"
BRANCH="feature-$(date '+%H%M')"

# create repo
if [[ ! -d ${REPO_FOLDER} ]]; then
(
  mkdir ${REPO_FOLDER}
  cd ${REPO_FOLDER}
  git init
  git remote add origin ${REPO}

  # create mock app source and deployment config
  mkdir -p projects/service/deployments/dev
  echo "hello world" > projects/service/main
  echo "APP_DB_NAME=hello-world" > projects/service/deployments/dev/config
  git add -A
  git commit -m "add app ${app}"

  # create mock shared deploy script
  mkdir -p bin
  printf "#!/bin/sh\necho deploying\ncat -" > bin/deploy-script
  chmod +x bin/deploy-script
  git add -A
  git commit -m "create shared deploy script"

  # create end to end testing script
  mkdir -p projects/shared/e2e
  printf "#!/bin/sh\necho testing" > projects/shared/e2e/main
  chmod +x projects/shared/e2e/main
  git add -A
  git commit -m "create end to end testing script"

  # push to origin
  git add -A
  git push -u origin master -f
)
fi

# create a feature branch for this test
(
  cd ${REPO_FOLDER}
  git checkout master # for repeat runs of this script
  git checkout -b ${BRANCH}
  git push origin ${BRANCH} -f
)

# build pipeline
fly -t dev dp -p test -n
fly -t dev sp -p test -n -c <(cat <<EOF
jobs:
- name: build-service
  serial: true
  plan:
  - get: service-source
    trigger: true
  - task: build
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: service-source
      platform: linux
      run:
        path: /bin/true
- name: deploy-service
  plan:
  - in_parallel:
      steps:
      - get: service-source # used to trigger a deploy after a
        passed:             # build. without this we would only
        - build-service     # deploy on config changes.
        trigger: true
      - get: service-config # used to trigger a deploy when
        trigger: true       # files affecting config change
      - get: e2e            # only here so we can use passed
  - task: run-deploy-script
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: service-config
      platform: linux
      run:
        path: sh
        args:
        - -c
        - service-config/bin/deploy-script < service-config/projects/service/deployments/dev/config
- name: e2e
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: e2e
        passed:
        - deploy-service
        trigger: true
      - get: every-minute
        trigger: true
  - task: run-tests
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: e2e
      platform: linux
      params:
        APPS: "service"
      run:
        path: e2e/projects/shared/e2e/main
resources:
- name: service-source
  type: git
  icon: git
  source:
    branch: ${BRANCH}
    paths:
    - projects/service/*
    uri: ${REPO}
- name: service-config
  type: git
  icon: git
  source:
    branch: ${BRANCH}
    paths:
    - projects/service/deployments/dev*
    - bin/deploy-script
    uri: ${REPO}
- name: e2e
  type: git
  source:
    branch: ${BRANCH}
    uri: ${REPO}
    paths:
    - projects/shared/e2e/*
- name: every-minute
  type: time
  source:
    interval: 1m
EOF
)
fly -t ${CONCOURSE_TARGET} up -p test

cat <<EOF
Please follow these steps.
1. view pipeline
2. build will succeed (runs /bin/true)
3. deploy triggers after build (runs deploy script on project config)
4. e2e will trigger on deploy pass and every minute after
5. once this cycle completes, hit enter and the e2e suite will be modified
   but it will not trigger because it has not "passed" through the deploy
   and every 10 minutes it will run with the "wrong" commit.
EOF
read

# modify e2e test script
(
  cd ${REPO_FOLDER}
  printf "#!/bin/sh\necho testing new" > projects/shared/e2e/main
  git add -A
  git commit -m "modify end to end testing script"
  git push origin ${BRANCH} -f
)
```
This boils the problem down to shortest / easiest possible representation I could muster. Before you say to switch the `passed` declaration to `service-source` instead of e2e remember that more complex versions of this pipeline have up to 20 completely distinct "service-sources" (one for each project).

God, I hope this make some sense. Thanks in advance once more for looking at this.

**Comment by tkellen** [comment]
Gentle nudge @vito. Just to say it, I'm not looking for you to resolve this issue, I'm more than happy to contribute the feature if we can identify an approach that makes sense.

**Comment by vito** [comment]
Woops sorry forgot to check back on this! I'll save a bookmark and remember for tomorrow. :stuck_out_tongue: 

...but if I keep forgetting keep poking me, I do want to get to the bottom of this!

**Comment by tkellen** [comment]
No worries, I know this issue represents a corner case without a ton of impact given all you're trying to accomplish right now. Thanks for taking a look! I'll be happy to keep pinging now that I know I'm not bothering you :smile:

**Comment by vito** [comment]
@tkellen Thanks for working on a repro, I was able to verify it myself and it really helped me see the problem!

To test my understanding, I'm going to put myself in your shoes and try to express what you're trying to do:

* I want my pipeline to run against a single monorepo, which would most intuitively be represented as a single resource, as I plan to "fan in" on it later in the pipeline.
* For any versions (commits) which affect files under `projects/service/deployments/dev*`, run the `build-service` and `deploy-service` jobs.
  * For any versions which *don't* affect files under this path, treat them as if they had `passed` the jobs implicitly.
  * If these jobs fail, downstream `passed` constraints should not be able to progress past the failed version.
* Repeat above point for any other sub-paths.
* At the very end of the pipeline, I would like to fan in on the monorepo resource across all upstream `deploy-*` jobs and run tests in an `e2e` job.
  * This will naturally pick up changes to only the `e2e` suite or any other files in the repo, as all commits will have implicitly passed all upstream jobs.

Does this sound accurate?

(Assuming it is, ...)

The most challenging aspect to me is the 'implicit' behavior of propagating versions which don't affect the required paths.

Say the following sequence happens:

1. User pushes a commit which changes the affected paths; jobs run and go green. Versions flow along to downstream `passed` constraints.
1. User pushes a commit which does *not* change the affected paths; versions implicitly flow along to downstream `passed` constraints.
1. User pushes another commit which changes the affected paths; jobs run and *fail*.
1. User pushes a commit which does *not* change the affected paths.

In this case, we have to be sure *not* to implicitly flow these newly pushed commits along, as the most recent build has failed. Tricky, huh?

Sidebar: I have no idea how we would make this implicit propagation clear in the UI. It's kind of interesting to reason about and mentally visualize, and it strikes me as something that may be represented in a better way than with `passed` constraints, but I'm not sure how. :thinking:

**Comment by tkellen** [comment]
@vito thank you for taking the time to look at this. I'm so glad the reproduction made sense, it was pretty hard to make this behavior easily understandable and repeatable :relieved:.

Your description of my workflow is almost correct but I don't think it's worth trying to describe the subtle places where it is wrong because the sequence you outlined as being intractable has made me realize we need to be thinking about this concept in an entirely different way.

I can see now that what I'm actually reaching for is a way to express dependencies between jobs without referencing resources at all. **In my context, the resources / versions are not related.** My workaround for the problem being described in this issue is to not use `passed` at all. Today, I just have an e2e box floating on its own running all the time, many times when it shouldn't.

In effect, the only reason I ever used  `passed` was to trick the concourse UI into showing what I visually want to see. It seems the config I actually need looks something like this:
```yaml
- name: e2e
  serial: true
  depends_on:
  - task: deploy-service-bar
    state: passing
  - task: deploy-service-foo
    state: passing
  plan:
  - in_parallel:
      steps:
      - get: e2e
        trigger: true
      - get: every-minute
        trigger: true
  - task: run-tests
    config:
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: e2e
      platform: linux
      params:
        APPS: "service"
      run:
        path: e2e/projects/shared/e2e/main
```

Here is a visual (not shown is that the e2e box should have an e2e resource that isn't connected to either deploy):
![image](https://user-images.githubusercontent.com/1004324/72996947-91ad5c80-3dc9-11ea-9aa7-e1c825009716.png)

...it's not lost on me that this is effectively introducing branching logic into jobs. I don't have a clear picture of the impacts this could have but I imagine they are pretty vast.

What do you think?

**Comment by tkellen** [comment]
To take this idea a bit further, this config:
```yaml
- name: e2e
  serial: true
  depends_on:
  - task: deploy-service-bar
    state: passing
  - task: deploy-service-foo
    state: failing
```

....could be shown like this:
<img width="757" alt="245b78dd-a9d2-4eff-b52c-72a25341f36a" src="https://user-images.githubusercontent.com/1004324/72999522-78a6aa80-3dcd-11ea-91ab-17d7654587ff.png">
