### ISSUE TITLE
Bad column width

### ISSUE THREAD

**Issue by vector623** [concourse/concourse#4961]
## Bug Report

Column width settings are too wide when executing shell tasks.

## Steps to Reproduce

Execute the following task:

```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      stty -a
```

## Expected Results

`stty -a` should return a reasonable column width setting.

## Actual Results

Column width is set to 500:
```
fly -t concourse execute -c reproduce.yml
uploading concourse done
executing build 173 at https://concourse.nbsupply.net/builds/173
initializing
running sh -exc stty -a

+ stty -a
speed 38400 baud; rows 500; columns 500; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho
succeeded
```

## Additional Context

This doesn't seem to disrupt output in most cases.  However, some commands, like `ansible-playbook`, don't handle the wide rows well.  See this screenshot for an example:

![bad_ansible_output](https://user-images.githubusercontent.com/463698/71708554-2ff86480-2dc0-11ea-9ea5-487b544af2b8.PNG)

Ideally, concourse would feed `sh` (via the task runner) a reasonable column width, calculated from the viewscreen of the browser.  In case of `fly` invocation, column width could possibly be read in from the executing environment.

## Workaround

Use the `stty` command to manually set a terminal output width:

```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: sh
  dir: repo
  args:
    - -exc
    - |
      stty cols 120
      stty -a
```

## Version Info

* Concourse version: 5.7.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: GCP Debian 10 VM
* Browser (if applicable): Brave browser (latest)
* Did this used to work? No
