### ISSUE TITLE
Default docker(oci) image for a concourse pipeline

### ISSUE THREAD

**Issue by danail-branekov** [concourse/concourse#4981]
Hi,

I am not sure whether this is a feature request, or we (CF Garden) simply do not know how to do what we need. In short, we have a CI pipeline with lots of jobs. Each job is configured to execute one or more task definition ymls so you can imagine that we have gazilions of them. Each task file begins with the following identical docker image definition:

```
image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.25'
``` 

Every time we want to bump to a new version of `cfgarden/garden-ci` we need to change, test and push gazilion task ymls across multiple github repositories which is quite a pain in the back.

My question is: is there a way to configure a default `image_resource` per pipeline/concourse deployment to be used whenever a task yml does not explicitly define it?

We have considered using the `latest` tag, but then we would loose traceability (dockerhub does not provide tags history).

## What challenge are you facing?
Bumping the docker image for all tasks in our pipeline is tedious and error-prone 

## What would make this better?
Ability to configure default docker image to be used by tasks by default. Ideally that should be in a file that is pushed to version control, for example the pipeline configuration yml would be perfect.

## Are you interested in implementing this yourself?
Sure, we would however want to get your feedback on the suggestion and guidelines on what/how to change and test.

**Comment by pivotal-jamie-klassen** [comment]
Instead of answering your question about setting a pipeline-/cluster-scoped default `image_resource` for tasks, I'd like to add a little nuance to the workflow discussion.

The pattern generally followed in https://github.com/concourse/ci is this: rather than specifying `image_resource:` in our task configs, we track the image used to run those tasks in a resource and specify it dynamically in the task step using the [`image:`](https://concourse-ci.org/task-step.html#task-step-image) field.

In this case, you could pin the resource that defines your image to a specific tag in your pipeline config and then you wouldn't need to maintain that version in multiple places across your task configs. You could even pin the resource dynamically (using [`fly pin-resource`](https://concourse-ci.org/managing-resources.html#fly-pin-resource)). Regardless, you'd still need to duplicate the resource itself across multiple pipelines.

In response to your official question I think there is a default image that concourse will use to run containers if you don't specify, but I don't remember exactly where it's configured... I think it might be possible to specify at the Garden level?

**Comment by danail-branekov** [comment]
Oh, interesting, pinning a docker image resource and use that resource in the ymls would totally work for us as well.
How do I use a pinned resource in a task yml, a simple example would be highly appreciated!

Thanks!

**Comment by cirocosta** [comment]
>  I think there is a default image that concourse will use to run containers if you don't specify, but I don't remember exactly where it's configured...

IIRC we used to have `gdn`'s default rootfs configured (https://github.com/cloudfoundry/guardian/blob/90961f153e3c4eccf6c461e9efa5165ac454f47c/guardiancmd/command.go#L115)

**Comment by pivotal-jamie-klassen** [comment]
@danail-branekov Let's make some assumptions about your current workflow.

I assume that your task.yml lives in a git repo, your pipeline looks like:
```yaml
resources:
- name: config-files
  type: git
  source: {uri: http://your-git-server.uri}
jobs:
- name: do-task
  plan:
  - get: config-files
  - task: the-task
    file: config-files/task.yml
```
and the contents of `config-files/task.yml` are:
```yaml
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.25'
run: {path: echo, args: ["hello", "world"]}
```

What you could do instead is have this pipeline:
```yaml
resources:
- name: config-files
  type: git
  source: {uri: http://your-git-server.uri}
- name: garden-ci
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.25' # you can make this 'latest' or whatever tag is suitable if you use the dynamic pinning option
jobs:
- name: do-task
  plan:
  - get: config-files
  - get: garden-ci
  - task: the-task
    file: config-files/task.yml
    image: garden-ci
```

and a simpler `config-files/task.yml` like

```yaml
platform: linux
run: {path: echo, args: ["hello", "world"]}
```

I'm less sure about the last part, I haven't actually tested it. But you could put any "default" image in the task config, since the `image:` field on a task step overrides it.

Does this make sense? I haven't talked as much about dynamic pinning here, so I can go into more detail about that if you'd like.
