### ISSUE TITLE
How to publish my resource to Kubernetes?

### ISSUE THREAD

**Issue by DenisIzmaylov** [concourse/concourse#501]
Dear,
Thank you for this great solution but I did not found clear solution or example how to publish my `output` to Kubernetes cluster?

**Comment by vito** [comment]
Not sure what you mean by this. By resource do you mean build artifact? What kind of build artifact?

**Comment by DenisIzmaylov** [comment]
@vito So I have the simple pipeline config:

```yaml
resources:
  - name: web-source
    type: git
    source:
      uri: git@github.com:DenisIzmaylov/private-one.git
      branch: release

  - name: web-image
    type: docker-image
    source:
      repository: localhost:5000/private-one-release

jobs:
  - name: build
    serial: true
    plan:
      - get: web-source
        trigger: true
      - put: web-image
        params:
          build: web-source
```

When Docker image (`web-image`) will be built how I can publish it as pods to Kubernetes?
