### ISSUE TITLE
get step params missing in custom resource

### ISSUE THREAD

**Issue by HoffiMuc** [concourse/concourse#5042]
## Bug Report

I'm implementing a custom resource (put/get values to a custom credhub server)

on implementing the `assets/in` script I realize that the `params` of the (second job's) get step are not passed via stdin json. There just is no `"params":{"KEY":"somekey","PREFIX": ... }` section in the stdin json.

## Steps to Reproduce

my (test)pipeline looks like this:

```
resource_types:
- name: concourse-credhub-store-resource-type
  type: docker-image
  source:
    repository: dhoffi/concourse-credhub-store-resource
    tag: latest

resources:
- name: concourse-credhub-store-resource
  type: concourse-credhub-store-resource-type
  source:
    credhub_client: ((jumpbox-credhub-client-name))
    credhub_secret: ((jumpbox-credhub-client-secret))
    credhub_server: ((jumpbox-credhub-server))
    credhub_ca_cert: ((jumpbox-credhub-ca-cert.certificate))
    prefix: /concourse/main/jobstate/testConcourseCredhubStoreResource


jobs:
- name: testConcourseCredhubStoreResource-Set
  serial: true
  serial_groups: [sync]
  plan:
  - put: concourse-credhub-store-resource
    resource: concourse-credhub-store-resource
    params:
      KEY: somekey
      VALUE: 
        somekey: somevalue
      # optional: overrides given prefix from resource
      PREFIX: /concourse/main/jobstate/testConcourseCredhubStoreResource
- name:  testConcourseCredhubStoreResource-Get
  serial: true
  serial_groups: [sync]
  plan:
  - get: concourse-credhub-store-resource
    passed: [testConcourseCredhubStoreResource-Set]
    # trigger: true
    resource: concourse-credhub-store-resource
    params:
      KEY: somekey
      # optional
      SKIP_MISSING: false
      # optional: overrides given prefix from resource
      PREFIX: /concourse/main/jobstate/testConcourseCredhubStoreResource
```

but the stdin json of my assets/in just looks like this:

```
{
  "source": {
    "credhub_ca_cert": "-----BEGIN CERTIFICATE-----<redacted>-----END CERTIFICATE-----",
    "credhub_client": "credhub-admin",
    "credhub_secret": "<redacted>",
    "credhub_server": "https://<redacted>:8844",
    "prefix": "/concourse/main/jobstate/testConcourseCredhubStoreResource"
  },
  "version": {
    "key": "/concourse/main/jobstate/testConcourseCredhubStoreResource/somekey"
  }
}
```

## Expected Results

I'd expect the json passed to assets/in also to contain a `"params": { ... }` entry beside the `"source": { ... }` and `"version": { ... }` entries

## Actual Results

no `"params": { ... }` entry in assets/in STDIN json

## Version Info

concourse is part of a (latest) BUCC setup

* Concourse version: v5.7.2
* Deployment type (BOSH/Docker/binary): BUCC bosh
* Infrastructure/IaaS: vSphere without NSX-T
* Browser (if applicable): chrome
* Did this used to work? no

**Comment by xtreme-sameer-vohra** [comment]
Hey @HoffiMuc

**Comment by xtreme-sameer-vohra** [comment]
Hey @HoffiMuc 
What you're observing is due to the implicit get step that occurs after the put step. 
See [this](https://concourse-ci.org/put-step.html) for more details

You can specify the params to be used in this case with `get_params`
```
plan:
- put: docker-build
  params: {build: git-resource}
  get_params: {skip_download: true}
```
