### ISSUE TITLE
Put step fails

### ISSUE THREAD

**Issue by pivotal-izabela-gomes** [concourse/concourse#5053]
##  Bug Report

While trying to use git-resource put step, we observed it was failing every time.

## Steps to Reproduce

Deploying this pipeline and staring a build, it will result in an errored build.
```
---
resources:
  - name: resource-gist
    type: git
    source:
      branch: master
      uri: ((publishing-outputs-gist-uri))
      private_key: ((publishing-outputs-private-key))
  - name: resource-gist-put
    type: git
    source:
      branch: master
      uri: ((publishing-outputs-gist-uri))
      private_key: ((publishing-outputs-private-key))

jobs:
  - name: job-bump-date
    serial: true
    plan:
      - get: resource-gist
      - put: resource-gist-put
        params:
          repository: resource-gist
```

## Expected Results

Expected to pass.

## Actual Results

Build fails with following error:
``
usage: /opt/resource/out <path/to/source>
``

## Additional Context

Tested on v5.8.0 and it worked.

## Version Info

* Concourse version: master branch 4bde6a2d8c77c9cb512c0ec641183112b3019603
* Did this used to work? Yes
