### ISSUE TITLE
`fly execute` does not fully redact secrets.

### ISSUE THREAD

**Issue by tvon** [concourse/concourse#5064]
## Bug Report

Given `fly execute` outputs the entire `run` config, any secret echo'd there will be displayed.

## Steps to Reproduce

Providing a secret named `some_secret_value`:

```yaml
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine}

run:
  path: sh
  args:
    - -exc
    - |
      echo ((some_secret_value)) > some-file.txt
```
The output is printed with "running ...":
```console
$ fly -t concourse execute -c scratch-task.yml
uploading scratch done
executing build 245 at https://concourse-testing.cmmint.net/builds/245
initializing
running sh -exc
echo SECRET_VALUE_DISPLAYED_HERE > some-file.txt

+ echo ((redacted))
((redacted))
+ echo '((redacted))'
succeeded
```

## Expected Results

Value redacted in the final output is also redacted in the "initializing/running ..." output.

## Actual Results

The value is initially displayed in the output but redacted in the final output.

## Additional Context

I realize that if you are going to provide people with access to a secret and a way to run arbitrary commands then they have a million different options for extracting those secrets.  That said, something like this could lead an otherwise well-meaning person to expose secrets to anyone who can view their screen.

## Version Info

* Concourse version: 5.8.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Azure VMs
* Browser (if applicable): n/a
* Did this used to work? nah
