### ISSUE TITLE
Expose RESOURCE_NAME to `put` step

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#5089]
## What challenge are you facing?

Concourse exposes a set of build metadata, `BUILD_ID`, `BUILD_NAME`, etc. to `get` and `put`, but without current resource name.

When a resource is `putting`, it doesn't know who itself is, which leads to a weird situation, for example:

```yaml
resources:
- name: mr
   type: gitlab-merge-request
   ...

jobs:
- name: job1
  plan:
  - get: mr # get the merge-request metadata, and stores in files.

  - put: mr
     params:
        dir: mr
        status: running
```

The `put` on `mr` doesn't know where `mr` is, so user has to define a param `dir: mr` to tell the `put` where the resource is, which sounds and looks really weird.

## What would make this better?

If current resource name is exposed to `put`, then `put` can by default look for `/tmp/put/<current resource name>` for itself, so the above weird param `dir: mr` can be avoided.

## Are you interested in implementing this yourself?

Yes
