### ISSUE TITLE
Passing worker environment variables to resources & tasks

### ISSUE THREAD

**Issue by holstvoogd** [concourse/concourse#510]
I would like to be able to pass environment variables from the worker's environment into the resource commands, specifically to be able to use Vault from within custom resource types by using the UserID provided as an env var to the worker.

I've started work on a PR to this end that uses the following approach: in both the params and source config passed to the resource commands I substitute values with a prefix (I've used 'ENV!!') with the env var with the name of the rest of the value. It is not a very pretty solution, but it should work for my use case.

An example:
```yaml
- name: my-vault-resource
  type: my-custom-resource-type
  source:
    vault_user_id: ENV!!VAULT_USER_ID
    app_id: 12345-asdfg-09876
```

In which the vault_user_id would be substituted with what ever the value of VAULT_USER_ID is for the worker, right before it is encoded as json and passed to the resource commands.

I still have to look at what is possible for tasks, but I think it would be handy to be able to do the same there too.

Furthermore this could be extended to incorporate values from other sources (lets say a secrets store such as vault ;)) on run time such as described in #291 with different prefix schemes etc.

Any feedback on this approach? Bit to hacky maybe?
