### ISSUE TITLE
Add patch number to worker version

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#5106]
## What challenge are you facing?

When upgrade a Concourse cluster to a new version, ATC part is easy, but rolling upgrading workers takes a lot of time. But for many versions, workers don't have to be upgraded at all.

Current worker version contains only major and minor version, like `2.2`, where automatic upgrade process has no way to determine if there is built-in resource type changes, so that it has to always upgrade workers. 

## What would make this better?

I'd suggest add a patch number to indicate if there are built-in resource type changes, which will benefit worker upgrade process very much.

## Are you interested in implementing this yourself?

This is not a code change, so I cannot make it.

**Comment by vito** [comment]
I think this is mixing up some concerns. Seems like you want to tell what *Concourse* version the workers are running, whereas the current worker version is solely to capture API/protocol compatibility.

For figuring out compatibility, we really only need major and minor numbers, and it's already kind of confusing to know when and how to bump them, so IMO adding a patch segment would make that more confusing.

If your end goal is to see which ones have and have not upgraded resource types, you could check their resource type versions in `fly workers --json`:

```yaml
[
  {
    "addr": "10.11.16.15:39765",
    "baggageclaim_url": "http://10.11.16.15:36179",
    "active_containers": 38,
    "active_volumes": 285,
    "active_tasks": 0,
    "resource_types": [
      {
        "type": "bosh-io-release",
        "image": "/usr/local/concourse/resource-types/bosh-io-release/rootfs.tgz",
        "version": "1.0.2",
        "privileged": false,
        "unique_version_history": false
      },

# ...
```
