### ISSUE TITLE
concourse freezes if a job has a dependency on itself

### ISSUE THREAD

**Issue by dsabeti** [concourse/concourse#511]
Hey there. I made the mistake of putting the following in my pipeline:
```yaml
- name: my-job
  plan:
  - get: some-resource
    passed: [ my-job ]
```
Instead of getting an error during `fly set-pipeline`, the CLI just says "configuration updated". But the Concourse UI completely freezes without any indication to the error. Maybe this could be detected in the CLI and give a meaningful error?
