### ISSUE TITLE
Outputs are not returned by the ListJobs endpoint

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5129]
## Bug Report

Outputs are no longer shown in the web UI. This is because they are no longer returned by DashboardJobs from the ListJobs endpoint that is used by the dashboard and to render the pipeline view. They were removed with the refactor of the return values of the dashboard. Whoops.

## Steps to Reproduce

Set a pipeline with outputs

## Expected Results

Yes outputs

## Actual Results

No outputs

## Version Info

* Concourse version: 6.0
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? Yes

**Comment by pivotal-jamie-klassen** [comment]
To be super explicit, let's take this pipeline:
```yaml
jobs:
- name: build
  plan:
  - aggregate:
    - get: repository
      trigger: true
    - get: version
      trigger: true
  - aggregate:
    - file: repository/ci/tasks/build.yml
      privileged: true
      task: build-image
  - get_params:
      format: oci
    inputs:
    - image
    - version
    params:
      additional_tags: version/version
      image: image/image.tar
    put: container-image
  public: true
resource_types:
- name: semver
  source:
    repository: concourse/semver-resource
  type: registry-image
resources:
- name: container-image
  source:
    password: ((docker-password))
    repository: cirocosta/flight_recorder
    username: ((docker-user))
  type: registry-image
- name: repository
  source:
    ignore_paths:
    - ./VERSION
    uri: https://((github-token))@github.com/cirocosta/flight_recorder
  type: git
- name: version
  source:
    branch: master
    driver: git
    file: ./VERSION
    git_user: Ciro S. Costa <cscosta@pivotal.io>
    uri: https://((github-token))@github.com/cirocosta/flight_recorder
  type: semver
```
If I set this pipeline locally running v5.8.0, I see
![Screen Shot 2020-02-07 at 9 50 05 AM](https://user-images.githubusercontent.com/22056320/74039068-3d8ca580-498f-11ea-80bd-97f285956251.png)
This is expected.

However, if I set this pipeline on hush-house running v6.0.0 and view the pipeline page, I see
![Screen Shot 2020-02-07 at 9 47 09 AM](https://user-images.githubusercontent.com/22056320/74038928-fa323700-498e-11ea-9b74-a0169fcd8f7d.png)
This is not.
