### ISSUE TITLE
Problem parsing payload from pipeline.yml

### ISSUE THREAD

**Issue by farahfa** [concourse/concourse#515]
Hello,

I'm creating a resource that creates AWS EC2 instances from specific AMIs and has the capability to use the docker remote API on those instances to pull and run images pulled from Amazon ECR.. But I'm having an issue parsing the payload from the pipeline yaml file.. I keep on getting the following error:

```
/opt/resource/out: line 21: can't open {"source":{"access_key_id":"AKIAXXXXXXXXXXX","ami_id":"ami-d62099c1","aws_region":"us-east-1","repository":"2xxxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/nexus-pro","secret_access_key":"DazXXXXXXXXXXXXXXXXXXXXXXX","tag":"2.13.0-np-1.0"},"params":{"container_name":"nexus","instance_type":"t2.medium","key_name":"pemkey","port_bindings":["80:8081","8081:8081"],"public_ip":false,"security_group_ids":"sg-3e85035a","subnet_id":"subnet-7c18bf57","vm_count":1}}: no such file
```

I don't understand what the `no such file` means..

This is how I'm fetching the values (which works if I try to do it manually):

```
payload=`cat`
repository="$(jq -r '.source.repository // ""' < $payload)"
tag_source=$(jq -r '.source.tag // ""' < $payload)
container_name=$(jq -r '.params.container_name // ""' < $payload)
port_bindings=$(echo "$payload" | jq -r '.source.port_bindings // [] | join(" ")')
ami_id=$(echo "$payload" | jq -r '.source.ami_id')
count=$(echo "$payload" | jq -r '.params.vm_count')
instance_type=$(echo "$payload" | jq -r '.params.instance_type')
subnet_id=$(echo "$payload" | jq -r '.params.subnet_id')
public_ip=$(echo "$payload" | jq -r '.params.public_ip // "false"')
security_group_ids=$(echo "$payload" | jq -r '.params.security_group_ids')
key_name=$(echo "$payload" | jq -r '.params.key_name')
```

And my pipeline.yml:

```
---
jobs:
- name: build-nexus-docker-image
  public: false
  plan:
  - put: nexus-test-resource
    params:
      vm_count: 1
      instance_type: t2.medium
      subnet_id: subnet-7c18bf57
      public_ip: false
      security_group_ids: sg-3e85035a
      key_name: covrnd1
      container_name: nexus
      port_bindings:
        - 80:8081
        - 8081:8081
    get_params:
      skip_download: true

resource_types:
- name: fadi-test-resource
  type: docker-image
  source:
    repository: covisintrnd/test-aws-ecr-nexus-resource
    tag: test

resources:
- name: nexus-test-resource
  type: fadi-test-resource
  source:
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    aws_region: {{ecr_region}}
    repository: {{ecr-nexus-repo}}
    tag: {{ecr-nexus-tag}}
    ami_id: ami-d62099c1
```

Any help is very much appreciated.

EDIT: My dockerfile for the resource looks like this:

```
FROM python:3.5-alpine

RUN apk add --update jq
RUN apk add --update curl

RUN pip install --upgrade pip
RUN pip install --upgrade awscli

ADD assets/ /opt/resource/
```
