### ISSUE TITLE
Make `zstd` compression opt-in; default to `gzip`

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5195]
Supporting `zstd` has proven to be a little tricky. It's more performant, but the `cgo` package we use appears to not work with certain payloads (#4621), and switching to a pure Go implementation caused more problems which need to be looked into (#5183).

In hindsight we probably should have made this feature-flagged, so let's go back to `gzip` as the default for now and make `zstd` opt-in.

In making `zstd` opt-in let's un-revert the pure Go changes; I think that's what we want in the long run, but we need to investigate why it's not working.

**Comment by kcmannem** [comment]
myabe use gzip as the fallback when zstd fails 🤷‍♂

**Comment by xtremerui** [comment]
With going by making zstd opt-in, `fly` now needs a way to tell which one of gzip/zstd that concourse server is running with.

One option is making the compression info available by `/api/v1/info`. Or fly could just try using `gzip` first and fallback to zstd.

@vito wdyt?

**Comment by vito** [comment]
@xtremerui I think we can have `fly` just use `gzip` by default. My understanding is that the biggest win with `zstd` is for when we have to stream between workers, i.e. in production pipelines - I don't think we really care as much about `fly execute`. 🤔 If it's "free" we could add a `--compression=gzip|zstd` flag?

**Comment by cirocosta** [comment]
Hey,

I was trying to compare zstd (the datadog one, cgo-based) vs gozstd (from klauspost), here are some interesting stats from the cgroup where those baggageclaim servers ran:

![Screenshot from 2020-04-09 18-11-51](https://user-images.githubusercontent.com/3574444/78945240-d2924480-7a8d-11ea-939f-dff62e11226b.png)

first three (<<) are `zstd`, and last three (>>) are gozstd.

The test is essentially getting a baggageclaim server streaming stuff to another baggageclaim server, with that traffic going through a "streamer" (something that connects `stream-out` from one to `stream-in` from another, just how `atc` does). In this case, the setup is:

- 24GB of "random" data (a bunch of different concourse release tarballs and the PAS tile)
- each baggageclaim server limitted at 2cpus and 1GB mem through cgroups (`docker-compose` setup

```yaml
services:
  bc-provider:
    image: baggageclaim
    privileged: true
    volumes:
      - ./testdata/volumes:/volumes
    command:
      - baggageclaim
      - --volumes=/volumes
      - --bind-ip=0.0.0.0
      - --driver=naive
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB

  bc-consumer:
    image: baggageclaim
    privileged: true
    command:
      - baggageclaim
      - --volumes=/tmp
      - --bind-ip=0.0.0.0
      - --driver=naive
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
```

The graph doesn't make that too explicit, but we can tell that there's a lot more throughput in gozstd, and a higher (better for the purpose of going faster) cpu utilization in the provider.

in numbers, the times are:

zstd:
- 1m36.14961094s
- 1m39.22672816s
- 1m39.582921997s

gozstd
- 51.897764859s
- 49.224558693s
- 48.912892542s
 
I'll update this comment with a comparison of gzip and pure tar with no compression too :+1:
