### ISSUE TITLE
"additional_resource_types" resource seems not working anymore.

### ISSUE THREAD

**Issue by shinji62** [concourse/concourse#521]
Hi,

Custom resource are working thought the declaration in the pipeline. 

But actually we want to use the `additional_resource_types` with bosh.
Additional resource are declared in `worker.json`, so that's mean my bosh deployment is ok.
I try with many of them, like email, pull-request and it seems that baggageclaim is complaining.

Concourse 1.4.0
Garden-Runc 0.4.0

Example
```yaml
properties:
     additional_resource_types:
     - image: docker:///pcfseceng/email-resource
       type: email
```

```json
{"timestamp":"1467955746.320254564","source":"baggageclaim","message":"baggageclaim.repository.create-volume.failed-to-materialize-strategy","log_level":2,"data":{"error":"exit status 1","handle":"965b756b-ed6b-42df-4020-fbe7f6b0d993","session":"3.2553"}}
```
