### ISSUE TITLE
Extensible var sources

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5229]
Just as `resource_types:` extends the supported types under `resources:`, we should provide a way to extend the supported types under `var_sources:` so that credential managers and other types of var sources may be implemented externally.

## Current proposal

Prerequisites:

* [x] concourse/rfcs#37

Come up with an interface that [prototypes](https://github.com/concourse/rfcs/pull/37) can implement so that they can be used as a var source:

```yaml
prototypes:
- name: vault-var-source
  type: registry-image
  source: {repository: concourse/vault-var-source-type}

var_sources:
- name: my-vault
  type: vault-var-source
  source: {...}

# ...
```

We must also ensure that the use of prototypes is secure and doesn't compromise the intent of using a credential manager in the first place.
