### ISSUE TITLE
CONCOURSE_VAULT_SHARED_PATH has no effect for secrets lookup

### ISSUE THREAD

**Issue by fftorres** [concourse/concourse#5253]
## Bug Report

After enabling CONCOURSE_VAULT_SHARED_PATH variable, Concourse keeps with the previous behavior as if this variable was not been seeing.

I have the following variables set:

```
CONCOURSE_VAULT_SHARED_PATH=defaults
CONCOURSE_VAULT_PATH_PREFIX=concourse
```
In Vault, I have the following structure:

```
concourse/main/defaults
concourse/defaults
```

I have the key `shared_secret` only in `concourse/defaults`.

My pipeline (test-shared-secrets) makes reference to `((defaults.shared_secret))` and fails when try to get this variable. When I create `shared_secret` in `/concourse/main/defaults` it works.

Checking API calls to Vault, I see concourse trying to fetch from `/concourse/main/test-shared-secrets/defaults` and also `/concourse/main/defaults` but never `/concourse/defaults` (as I was expecting).

## Steps to Reproduce

- Create a secret in `/concourse/defaults`, like shared_secret=geronimo
- Set a pipeline that refers to `((defaults.shared_secret))`
- Enable Vault and set the following variables:
-- CONCOURSE_VAULT_SHARED_PATH=defaults
-- CONCOURSE_VAULT_PATH_PREFIX=concourse
- Trigger the pipeline and you will see the failure

### Sample pipeline

```
---
resources:
- name: every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: Echo
  plan:
  - get: every-1m
    trigger: true
  - task: testing-shared-secrets
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: bash
        args:
          - -ec
          - |
            echo "my shared secret ((defaults.shared_secret))"
```

## Expected Results

I was expecting Concourse to find ((defaults.shared_secret)) in `/concourse/defaults/`

## Actual Results

Failed to interpolate task config: Finding variable 'defaults.shared_secret': missing field 'shared_secret' in var: defaults.shared_secret

## Additional Context

Now we use defaults per team but we want to use /concourse/defaults globally, taking precedence over /concourse/team/defaults.

## Version Info

* Concourse version: 5.8.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable):
* Did this used to work? No
