### ISSUE TITLE
fly yaml interpolation produces different outputs depending on the value source 

### ISSUE THREAD

**Issue by combor** [concourse/concourse#5285]
## Bug Report

While interpolating variables, when the variable is empty, fly produces different output depending on the source of value of the variable. 

## Steps to Reproduce

For instance if the value is specified as an empty string by using -v then config.params.test value is set to `""`
```
fly validate-pipeline -o -c /tmp/x.yml -v test=
jobs:
- name: test
  plan:
  - config:
      params:
        test: ""
      platform: linux
      run:
        path: sh
    task: test
```

However, when a YAML file with variables is used and the variable is empty:
```
test:
```
then the config.params.test value is set to `null`
```
fly validate-pipeline -o -c /tmp/x.yml -l /tmp/test.yml 
jobs:
- name: test
  plan:
  - config:
      params:
        test: null
      platform: linux
      run:
        path: sh
    task: test
```
If the YAML file with variables has quotes than we are back to `""` as the value. 

## Expected Results

The output is always same. 

## Version Info

fly --version 
5.7.0

**Comment by combor** [comment]
Pipeline file:
```
jobs:
- name: test
  plan:
  - task: test
    config:
      platform: linux
      params:
        test: ((test))
      run:
        path: sh
```
