### ISSUE TITLE
No resource type out-of-the-box with windows worker

### ISSUE THREAD

**Issue by iar-wain** [concourse/concourse#533]
Hi,

According to http://concourse.ci/resource-types.html, Concourse workers should support resource types such as `git` out of the box.

I probably missed something obvious somewhere but it looks like it might not the case for the Windows worker (everything went fine on Linux).

Both server and worker were started on a single Win7 SP1 64 machine with the following command lines:

Server:
`D:\>concourse web --development-mode --external-url http://127.0.0.1:8080 --session-signing-key session_signing_key --tsa-host-key host_key --tsa-authorized-keys authorized_worker_keys`

Worker:
`D:\>concourse worker --work-dir worker --tsa-host 127.0.0.1 --tsa-public-key host_key.pub --tsa-worker-private-key worker_key --peer-ip 127.0.0.1`

And the following pipeline was used:

``` yaml

---
resources:
- name: git-res
  type: git
  source:
    uri: https://github.com/concourse/concourse.git

jobs:
- name: hello-world
  plan:
  - get: git-res
  - task: hello-world
    config:
      platform: windows
      run:
        path: echo
        args: [hello world]
```

When executing the `hello-world` job, an error message was obtained:

```
error
no workers satisfying: resource type 'git'

available workers: 
  - platform 'windows'
```

What did I miss?

Additionally I couldn't find any documentation on how to add custom resource types for Windows workers. Where should I look for that?

Thanks in advance.
