### ISSUE TITLE
CONCOURSE_LIDAR_CHECKER_INTERVAL not being respected

### ISSUE THREAD

**Issue by tjhiggins** [concourse/concourse#5333]
## Bug Report

Setting `CONCOURSE_LIDAR_CHECKER_INTERVAL=1s` appears to still use the default of 10s on resource checks. I have a resource trigger defined with a check_every of 1s:

## Steps to Reproduce

Deploy concourse via docker compose using 6.0.0-rc and set a pipeline like the following. 
env: `CONCOURSE_LIDAR_CHECKER_INTERVAL=1s`

Note that the resource waits for 10s before performing a check.

```yaml
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
      tag: v0.5.1

resources:
  - name: gcs-deployment
    type: gcs-resource
    check_every: 1s

jobs:
  - name: example
    plan:
      - get: gcs-deployment
        trigger: true
        version: every
```

## Expected Results

Resource check would trigger every 1s.

## Actual Results

Resource check triggers every 10s.

## Additional Context

Upgraded to 6.0.0-rc because we wanted build retries and it included a important garden fix. Haven't noticed any other regressions besides this one so far. Loving concourse btw!

## Version Info

* Concourse version: 6.0.0-rc
* Deployment type (BOSH/Docker/binary): docker
* Did this used to work?
Worked on 5.8, but I don't think that used lidar?
