### ISSUE TITLE
v6.0 feedback

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5360]
v6.0 was a big release with significant changes to pipeline semantics - something we rarely do. We'll be taking a bit of time after the release to refactor code and listen to feedback left on this issue before moving on to the next "big thing."

If your workflow was affected by v6.0, whether it's in a good way or a bad way, please leave a comment here! If this issue is closed before then, please just open a new issue or perhaps open a thread in the [forums](https://discuss.concourse-ci.org).

Thanks!

**Comment by analytically** [comment]
Upgrading (from 5.8.0) went flawlessly, with one minor caveat: the order of build steps changed on the dashboard. While the pipeline still displays the correct order, the dashboard turns this around (sorting alphabetically?). Eg:

![image](https://user-images.githubusercontent.com/254434/77576187-8226be80-6eb3-11ea-958c-43bbfd0e47e6.png)

vs 

![image](https://user-images.githubusercontent.com/254434/77576258-ad111280-6eb3-11ea-9286-7955e1feb753.png)

**Comment by vito** [comment]
@analytically FWIW, the dashboard pipeline grid and the pipeline UI have always been out-of-sync, and probably will remain that way until we [re-write the pipeline UI in Elm](https://project.concourse-ci.org/projects/MDc6UHJvamVjdDI5OTk4MjA=).

**Comment by scuba10steve** [comment]
> ... We never got around to it because most of the motivation for it came from PR flows, which was (and still is) a pretty broken usage pattern which we were trying to address directly rather than have it act as a primary motivator for design decisions like this one.

I'm pretty curious if someone would be able to elaborate on this a little bit.  The reason I'm asking is we've began looking into potentially using concourse as an additional CI resource, but also have the capability of building pull requests through it to automatically run unit tests, compile code, etc.

I'm just trying to distinguish where the 'usage' part comes into play.

**Comment by drahnr** [comment]
Upgrade from 5.8.0 to 6.0.0 went flawlessly :+1: , CPU usage dropped significantly (yay!), :zap: https://github.com/concourse/concourse/issues/5334 is still causing issues.

**Comment by vito** [comment]
@scuba10steve Today most folks use the [`telia-oss/github-pr` resource](https://github.com/telia-oss/github-pr-resource), which kind of works but has a bunch of subtle problems in practice. Not the fault of the resource type at all - it's just a square peg trying to fit into a round hole.

The [v10 roadmap](https://blog.concourse-ci.org/core-roadmap-towards-v10/) is all about trying to provide better abstractions in Concourse in support of these types of workflows, which are "spatial" in that the set of things you want to test against grows and shrinks as PRs are opened/closed, which is very different from what resources represent today (they represent change of a *single object* over time).

The [Re-inventing resource types](https://blog.concourse-ci.org/reinventing-resource-types/) blog post digs into this with more detail - in particular the "When is a resource type not a resource type?" section.

So the tl;dr is: if you're considering Concourse primarily for pull requests, now is probably not a great time, though some people *are* doing it (including us). Other tools simply have a better model for pull requests at the moment. It's IMO the biggest feature gap in Concourse, and it's the main thing the v10 roadmap addresses.

@drahnr Awesome, good to hear! I've left a comment on your linked issue. :+1:

**Comment by scuba10steve** [comment]
@vito, Thanks, that really clears that up for me!  I appreciate the response.

**Comment by drahnr** [comment]
I was really happy seeing the `--team` introduced, but my main use-case would be around `set-pipeline` - which is sadly not covered just yet (nitpick).

**Comment by gowrisankar22** [comment]
We are running concourse deployment on top of k8s on GKE.  After upgrading from version 5.8.0 to 6.0.0 our task scheduling became very slow. The earlier job will run and finish within 35s but now it takes up to 4m

**Comment by drahnr** [comment]
@gowrisankar22 I see the same, very simplistic jobs take significantly longer (`fly execute` is still fast though, @vito this is a different issue, likely unrelated to #5334)

**Comment by vito** [comment]
@gowrisankar22 Gonna need more info and/or steps to reproduce in order to really dig into that further. :confused: Maybe open an issue once you have'em? Also you may want to enable [global resources](https://concourse-ci.org/global-resources.html) if you haven't - perhaps this is the same issue as https://github.com/concourse/concourse/issues/4940?

**Comment by coffee-squirrel** [comment]
We've moved from `v5.8.0` to `v6.0.0` (`concourse-bosh-deployment`; relatively small... platform ops) and things seem to be working fine.  It was a nice boring upgrade.

**Comment by cirocosta** [comment]
It *seems* like Safari (Version 13.1 (15609.1.20.111.8)) is having trouble rendering the dashboard 🤔  

v6.0.0

<img width="1599" alt="Screen Shot 2020-03-30 at 9 30 15 AM" src="https://user-images.githubusercontent.com/3574444/77918103-6b90b680-7269-11ea-918b-bca426236b25.png">

v5.8.0

<img width="1599" alt="Screen Shot 2020-03-30 at 9 30 18 AM" src="https://user-images.githubusercontent.com/3574444/77918122-71869780-7269-11ea-85f5-7ad90d11dd5f.png">

**Comment by gowrisankar22** [comment]
@vito created a bug #5378 to reproduce the issue. btw, I have enabled global resource check already.

**Comment by vito** [comment]
@cirocosta Looks like that's fixed by #5375

**Comment by mxplusb** [comment]
@vito Since the surprise 6.0 upgrade yesterday (relative to this comment), I have been seeing very strange CPU behaviour. I know the upgrade helped lower overall usage, but it feels like the high CPU usage times are much higher, and the low CPU usage times are much lower, so overall the differences are much higher. The impact of this is that Prometheus has been throwing high CPU warning for what are essentially glorified shell scripts, so since the upgrade Concourse is causing alarms that have really never triggered before to start triggering. These alarms are specifically on the workers, which are the exact same as they were before the upgrade.

I think something needs to be spread out a bit more, because it's very drastic changes right now and the alarms are unhelpful.

![image](https://user-images.githubusercontent.com/7537841/78065893-39f31a80-7351-11ea-9636-5f20e339c17b.png)

**Comment by cirocosta** [comment]
thanks for sharing, @mxplusb! 

would you mind sharing which version did you upgrade from? also, just to clarify: the panel above is only for *workers*, right?

thanks!

**Comment by jgriff** [comment]
Similar to @cirocosta's dashboard weirdness on Safari (desktop) [above](https://github.com/concourse/concourse/issues/5360#issuecomment-606001836), I get similar weirdness on mobile browsers.

Both Chrome (mobile) and Safari (mobile) now produce:
![IMG_8511](https://user-images.githubusercontent.com/1635227/78150919-f4dcf000-7405-11ea-907c-22d96f7b5648.PNG)


Perhaps mobile could be fixed by #5375 as well?

**Other than that, our upgrade to 6.0 has been flawless!** 🎉 🍾

**Comment by cirocosta** [comment]
@jgriff it seems like it did! just tested here against chrome and safari on my phone:

- https://user-images.githubusercontent.com/3574444/78151968-315d1b80-7407-11ea-91ac-b0193870ab01.png
- https://user-images.githubusercontent.com/3574444/78151976-34f0a280-7407-11ea-8917-910a31579a53.png

**Comment by mxplusb** [comment]
@cirocosta 

> would you mind sharing which version did you upgrade from? also, just to clarify: the panel above is only for workers, right?

We upgraded from 5.8.1, and that panel is exclusively the workers, yes. We're using the bosh release and the ATC resources seem about the same for us. We have 44 pipelines and each pipeline is fairly large. I can't show the dashboard but I can link to some of the public pipeline files if you want to see them.

**Comment by gowrisankar22** [comment]
@vito @cirocosta 
Facing issue still so weirdly ..Any suggestions, how to fix the issue? #5378 

I recreated all the workers and web nodes as well but no luck.

Every 4-5 builds one build is working as expected with less time(35s) rest all the builds takes (3-6)mins now..

**Comment by Rukenshia** [comment]
We have just upgraded our Concourse Deployment from 5.8.0 to 6.0.0, first some info about our cluster and then some initial feedback, if anything changes over the course of the following days, I'll add more info.

Cluster Info
---

* Deployment via: bosh
* Deployed on: AWS
* Sizing
  * Web nodes: 2x `c5.4xlarge`
  * Worker nodes: 35x `c5.4xlarge`
* Teams: ~180 (due to how our tenancy model works internally)
* Pipelines: ~1400
* Active Users: ~400

Upgrade Feedback
---

* Massive kudos for the DB utilization reduction. We went from close to 100% in 5.7.0, down to 50-60% in 5.8.0, and now... this 
![image](https://user-images.githubusercontent.com/1899599/78422283-821a8180-765e-11ea-829c-70e1c11cca60.png)
* We were getting used to running a very expensive database for concourse, but now we will finally be able to downsize it quite a lot! Thanks!
* The web node CPU utilization looks like it's taken load off one instance, but not the other. Not sure how to interpret this. Might also be too early to judge
![image](https://user-images.githubusercontent.com/1899599/78422513-1507eb80-7660-11ea-86b1-95fc76f00447.png)
* Our teams are heavy users of the [`git-multibranch-resource`](https://github.com/cloudfoundry-community/git-multibranch-resource) and it looks like the version history was reset for those during the upgrade... this caught us off-guard and we are still running scripts that cancel all builds right now (over 400 builds that needed to be aborted so far). It's probably the fault of the resource, but sad to see 👎 
* Upgrading the bosh release was one of the easiest yet for a major version, no config changes 👍 
* We will have to redo our dashboards, but I hope the new/modified metrics will give us more observability into our cluster
* We can use the `main` team user(s) again, because the dashboard is blazingly fast 👍

**Comment by jjoneson** [comment]
We see spikes similar to what @mxplusb is showing.

In our case, we host our own Gitlab instance, and these spikes directly coincide with Gitlab getting hammered with resource checks, causing the Gitlab instance to throw 502's.

Our Concourse deployment has 20 workers, 300+ pipelines with about 10 jobs, 3-5 tasks per job, and 5-10 resources per pipeline.

Current theory is resource check staggering not working anymore, but I haven't had a chance to do a deeper review.

**Comment by vito** [comment]
@pivotal-jwinters FYI It sounds like there may have been some merit to #4624 after all based on feedback from @jjoneson and @mxplusb - I'm going to re-open and put it in the post-6.0 project to at least re-investigate. 🤔

**Comment by pivotal-jwinters** [comment]
@vito we could probably add a `max-in-flight` similar to what the new scheduler does.

**Comment by vito** [comment]
@pivotal-jwinters Yeah. Finding the right number will be tricky though. 🤔 You could do max-in-flight-globally (since only one `web` node is working through the queue at a time) as you're suggesting but arriving at a reasonable number may be difficult and introduce a pretty sensitive knob that is kind of complicated to adjust.

If the number is raised because you have a lot of users and you want their resources checked in a timely manner, you will likely end up seeing load spikes for different resources which all point to the same server.

If the number is too low, it'll become hard to get through the whole queue within one minute if you have a ton of resources.

This kind of reminds me of our problem with the `time` resource, where everyone ends up with the same interval. One solution I mapped out in the [var steps RFC](https://github.com/vito/rfcs/blob/trigger-resources/027-var-steps/proposal.md) was to "hash" the interval based on the job/pipeline name so that they all end up with a unique interval. I wonder if we could take a similar approach to ensure resource configs end up with a unique interval?

It'd be nice to do some sort of simulation. A max-in-flight might be good enough. Ideally we end up with a relatively constant workload instead of going through a massive backlog and still having periods of idle time, but I may be over-complicating things since the checking interval is already so low (1 minute). Flattening the spikes and slowly working through a queue might be good enough in practice.

The argument could also be very easily made that checking every minute is way too ambitious in the first place though, and we should do some sort of back-off (or webhooks obviously) so that we aren't over-checking things that don't update often enough.

**Comment by vito** [comment]
Also @Rukenshia that's awesome, thanks for the feedback!

re: `git-multibranch-resource`, sounds like more motivation for the v10 roadmap. Glad we got the ball rolling on that recently!

**Comment by christophermancini** [comment]
> @vito, Thanks, that really clears that up for me! I appreciate the response.

We rewrote the PR resource to fix many of its holes and add new features: https://github.com/digitalocean/github-pr-resource

**Comment by gowrisankar22** [comment]
@vito @cirocosta 
another issue which I am running is time-resource is not checking the new time due to which auto-trigger. is not working.
we are using slirunner and auto-trigger job is not at all triggering.

https://github.com/cirocosta/slirunner/issues/5

```
checking pipeline is not paused
checking job is not paused
discovering any new versions of time-trigger
waiting for a suitable set of input versions
time-trigger - latest version of resource not found
checking max-in-flight is not reached
```

**Comment by cirocosta** [comment]
for those not familiar with `slirunner`, that's something I created a while ago
to provide through Prometheus, some SLIs around how well a given concourse
installation is working/not.

e.g., one of the things it tests is the ability to create a pipeline and have
that pipeline automatically running til completion within a minute.

```bash
fly -t {{ .Target }} destroy-pipeline -n -p {{ .Pipeline }} || true
fly -t {{ .Target }} set-pipeline -n -p {{ .Pipeline }} -c <(echo '`+pipelineContents+`')
fly -t {{ .Target }} unpause-pipeline -p {{ .Pipeline }}

wait_for_build () {
        fly -t {{ .Target }} builds -j {{ .Pipeline }}/auto-triggering | \
                grep -v pending | \
                wc -l
}

until [ "$(wait_for_build)" -gt 0 ]; do
        echo 'waiting for job to automatically trigger...'
        sleep 1
done

fly -t {{ .Target }} watch -j {{ .Pipeline }}/auto-triggering
fly -t {{ .Target }} destroy-pipeline -n -p {{ .Pipeline }}
```


where `pipelineContents` is pretty much


```yaml
resources:
- name: time-trigger
  type: time
  source: {interval: 24h}

jobs:
- name: auto-triggering
  build_logs_to_retain: 20
  public: true
  plan:
  - get: time-trigger
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: echo
        args: ["Hello, world!"]
```

and as @gowrisankar22 yeah, it seems like we indeed have failures in 6.0.x w/
regards to the "create and run pipeline should work in <1m", here are some stats
that I got from leaving it running for a little while here in a fresh install
from 5e315c6ccfe2fdb087ecb40a7a5339b5dc31feb5 (master - what will become 6.1? as of now):


```
19.562706381s
19.702385842s
19.715432663s
19.848655724s
20.181099662s
30.327641228s
31.29447348s
34.046901567s
38.691222651s
39.486083775s
39.590951906s
39.926586455s
40.007893257s
40.015529123s
40.375027532s
40.672262795s
49.33672843s
49.40895535s
49.583428512s
49.743940842s
49.797198204s
49.802862184s
49.949491182s
59.617249934s
59.714726906s
59.856086026s
59.884030924s
1m0.023290922s
1m0.132681344s
1m0.235779465s
1m0.462664124s
1m10.279202166s
```

(^ naturally, that's after sorting)

@vito does anything come to mind w/ regards to what could be getting us above
the 1m threshold? would the new runner intervals / some form of misnotification
when setting/unpausing be interfering with it?

**Comment by gowrisankar22** [comment]
@cirocosta so we should wait for 6.1? I even changed the time to 5mins but time resource not able to pin the time inorder auto-trigger to work. But time resource is working for all other pipelines but only via sli runner it is not working.

last 6 hours my sli for "create and run pipeline" is just 7% :(

**Comment by rhoughton-pivot** [comment]
We are seeing our max-containers reached over a 6 hour time period from a bosh redeploy from 5.8.1 to 6.1. Did a recreate on the workers last night, maxed out again this morning.

**Comment by lrstanley** [comment]
Noticing some potential issues with the time resource myself, in our sandbox environment where we're testing v6.1.0. Our standard environments have between 600-1600 pipelines (~130ish teams), totalling around 2700 pipelines, so wanted to stretch the sandbox environment as much as possible to see how resource checking performance is, because that's been one of the larger issues we've faced with prior versions (we run 5.7.x on all other clusters). By stretch I mean try and make the cluster fail due to resource usage, concurrency limitations, container counts, etc.

My initial testing involved:
- 100 pipelines in one team.
- one job and one task.
  - bash script that just echos out something.
- 10 git resources for each pipeline.
  - these all were the exact same `source` within each pipeline, as well as for all pipelines, in order to test global resources, just with slightly varying names.
- one time resource, set to 30s check interval to auto-trigger (also tried 5min).
  - default resource check interval is 1min, not sure if this had any affect. we did try changing it to 2min, to see if this would work but not much of a change.
- one custom docker image, that's pulled from our internal Artifactory cluster.

Of the 100 pipelines, after a certain amount of hours, resource checks for the time resource just stop or are significantly delayed:
![image](https://user-images.githubusercontent.com/1847365/83300180-84fca300-a1c5-11ea-84f0-3bf6dee515e0.png)

Some of them simply don't ever even make a single check. It seems as though the checks stopped right around 8h after we did the upgrade, then pushed the pipelines. This is a graph of containers for each worker:
![image](https://user-images.githubusercontent.com/1847365/83300573-40253c00-a1c6-11ea-94c1-2ac69afe94e2.png)

Just after 16:00, is when we upgraded from 5.7.x to 6.1.0. ~00:20 is when all checks/workers/etc seemed to have issues.

Seems as though resource check metrics no longer exist.

None of the nodes (web, db, workers) are under load or disk constraints.

Last thing, is that according to the prometheus metrics, the pipelines were still running.. even though the container metrics don't match:
![image](https://user-images.githubusercontent.com/1847365/83302332-21747480-a1c9-11ea-8123-d7a16d41dbc9.png)

I will be continuing to test to see if I can track down the cause. Will be testing adjusting check interval, time resource time, as well as toggling global resources, increasing pipeline count, etc. If I can find more info, will update. Don't have definitive enough info at the moment to know if it's a config issue on our end, v6, etc.


Cluster footprint:
- 1 db node
- 2 web nodes
- 2 workers

```
- cloud_properties:
    cpu: 2
    disk: 8192
    ram: 2048
  name: cc-app-web
- cloud_properties:
    cpu: 2
    disk: 32768
    ram: 6144
  name: cc-app-db
- cloud_properties:
    cpu: 2
    disk: 131072
    ram: 8192
  name: cc-app-worker
```

aaand:
```
---
name: concourse
releases:
- name: concourse
  version: 6.1.0
- name: bpm
  version: 1.1.8
- name: postgres
  version: '41'
- name: nginx
  version: 1.17.0
- name: os-conf
  version: 22.0.0

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 3
  serial: false
  update_watch_time: 1000-60000

instance_groups:
- azs:
  - AZ1
  instances: 2
  jobs:
  - name: limits
    properties:
      nofile:
        hard: 16384
        soft: 16384
    release: os-conf
  - name: sysctl
    properties:
      sysctl:
      - vm.swappiness=10
      - net.core.somaxconn=1024
    release: os-conf
  - name: bpm
    release: bpm
  - name: nginx
    properties:
      nginx_conf: TRUNCATED
      ssl_chained_cert: TRUNCATED
      ssl_key: TRUNCATED
    release: nginx
  - name: web
    properties:
      add_local_users:
      - TRUNCATED:TRUNCATED
      audit:
        build: true
        job: true
        pipeline: true
        system: true
        team: true
      bind_ip: 127.0.0.1
      bind_port: 8080
      build_log_retention:
        default_builds: 50
        default_days: 120
        maximum_builds: 100
        maximum_days: 365
      build_tracker_interval: 10s
      capture_error_metrics: true
      container_placement_strategy: fewest-build-containers
      default_check_interval: 1m
      default_resource_type_check_interval: 1m
      default_task_cpu_limit: 256
      default_task_memory_limit: 4096mb
      enable_global_resources: true
      external_url: TRUNCATED
      ldap_auth:
        [...TRUNCATED...]
      main_team:
        auth:
          ldap:
            groups:
            - TRUNCATED
            users: []
          local:
            users:
            - TRUNCATED
      postgresql:
        database: atc
        role:
          name: concourse
          password: TRUNCATED
      prometheus:
        bind_ip: 0.0.0.0
        bind_port: TRUNCATED
      token_signing_key:
        private_key: TRUNCATED
        public_key: TRUNCATED
      vault:
        auth:
          client_token: TRUNCATED
        path_prefix: "/concourse"
        shared_path: "/concourse-template"
        url: TRUNCATED
      worker_gateway:
        authorized_keys: TRUNCATED
        host_key:
          private_key: TRUNCATED
          public_key: TRUNCATED
    release: concourse
  name: web
  networks:
  - default:
    - dns
    - gateway
    name: default
    static_ips: TRUNCATED
  stemcell: xenial
  vm_type: cc-app-web
- azs:
  - AZ1
  instances: 1
  jobs:
  - name: limits
    properties:
      nofile:
        hard: 16384
        soft: 16384
    release: os-conf
  - name: sysctl
    properties:
      sysctl:
      - vm.swappiness=10
      - net.core.somaxconn=1024
    release: os-conf
  - name: postgres
    properties:
      databases:
        databases:
        - name: TRUNCATED
        port: TRUNCATED
        roles:
        - name: TRUNCATED
          password: TRUNCATED
    release: postgres
  name: db
  networks:
  - default:
    - dns
    - gateway
    name: default
    static_ips: TRUNCATED
  persistent_disk_type: cc-app-db-disk
  stemcell: xenial
  vm_type: cc-app-db
- azs:
  - AZ1
  env:
    bosh:
      swap_size: 0
  instances: 2
  jobs:
  - name: limits
    properties:
      nofile:
        hard: 16384
        soft: 16384
    release: os-conf
  - name: sysctl
    properties:
      sysctl:
      - vm.swappiness=10
      - net.core.somaxconn=1024
    release: os-conf
  - name: worker
    properties:
      ephemeral: true
      garden:
        max_containers: 350
        network_pool: 10.254.0.0/22
      worker_gateway:
        worker_key:
          private_key: TRUNCATED
          public_key: TRUNCATED
    release: concourse
  name: worker
  networks:
  - default:
    - dns
    - gateway
    name: default
    static_ips: TRUNCATED
  stemcell: xenial
  vm_type: cc-app-worker
```
