### ISSUE TITLE
After upgrade from v5.8.2 to v6.0 makes scheduling very slow

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse#5378]
Hello Colleagues,

We are using the helm/k8s based concourse setup. Recently, we have upgraded our test environment to evaluate v6.0. Deployments everything went absolutely fine. After upgrading our job scheduling became very very slow. 

v5.8.2 - same job took 35s
v6.0- same job took: ~3-4min

pipeline.yml
```
resources:
- name: iacbox
  type: registry-image
  source:
    repository: weberstephanhd/iacbox2
    tag: v293.02
    username: ""
    password: ""
- icon: av-timer
  name: 5-min
  source:
    interval: 5m
  type: time
jobs:
- name: test-concourse-v6.0
  serial: true
  build_log_retention:
    days: 3
  plan:
  - get: 5-min
    trigger: true
  - get: iacbox
  - task: test-concourse-v6.0
    image: iacbox
    timeout: 10m
    config:
      platform: linux
      run:
        path: sh
        args:
        - -c
        - "echo Test concourse v6.0"
```
our resource consumption:
```
k top po
NAME                             CPU(cores)   MEMORY(bytes)
concourse-web-6cc5d66847-z5dr8   188m         47Mi
concourse-worker-0               375m         529Mi
concourse-worker-1               665m         619Mi
concourse-worker-2               35m          714Mi
```

CPU/MEM requests set:

```
web: 1cpu/3gbmem
worker: 1cpu/1gbmem
```
@vito

**Comment by vito** [comment]
By "scheduling" do you mean build duration?

**Comment by gowrisankar22** [comment]
@vito yes right

**Comment by vito** [comment]
What does the build look like it's doing during this time? That image is quite large, are you sure it's not just being downloaded for the first time after the deploy and having to be streamed to the task? How many times has the job been run?

For me, on a brand new local `docker-compose` installation, the first build fetches the image and completes in 2m 51s. The next builds don't have to fetch the image and completes in 30s-42s.

**Comment by gowrisankar22** [comment]
@I have 3 workers, until all three workers gets the image once to cache it up, it downloads the image. We run the job every 5 mins .. there are 5 jobs runs quite often. 

Seems like if the jobs is running in one specific worker is fast as before .. other two workers are taking time upto 3-4 mins .. 

Any suggestions?

**Comment by gowrisankar22** [comment]
@vito @cirocosta Facing issue still. Any suggestions, how to fix the issue?
I recreated all the workers and web nodes as well but no luck.

out of 4-5 builds one build is work as expected with less time(35s) rest all the builds takes (3-6)mins now.

**Comment by vito** [comment]
Sorry but without being able to observe this directly there's not a whole lot to go on here. If you can replicate the scenario in a controlled environment like Docker Compose that would help narrow things down. Right now all I can do is guess.

Here are some shots in the dark:

* Can you show the output of `fly workers -d`?
* Can you provide the timing breakdown for each step in the build plan, and/or a trace of one that was normal and one that was slow? (Is it possible to send an 'export'? Not sure if that's a thing.)

**Comment by gowrisankar22** [comment]
@vito 
Our setup currently running on GKE.
Recently with concourse version `5.8.2`, we ran into the resource cache problem. This point we were using image_resource in the task config. After discussing in the `discord`  we moved image_resource in the task image in the build plan.  [1]
[1]https://discordapp.com/channels/219899946617274369/413770960089382922/689179388431826982
with concourse version `5.8.2` this change worked like a charm and performance was quite good.

After concourse `6.0.0` release, we tried updating to the latest version that's where the problem started.  

**pipeline1.yaml : -  moved image_resource in the task image in the build plan ** 
```
resources:
- name: iacbox
  type: registry-image
  source:
    repository: weberstephanhd/iacbox2
    tag: v305
- icon: av-timer
  name: 5-min
  source:
    interval: 5m
  type: time
jobs:
- name: test-concourse-v6.0
  serial: true
  build_log_retention:
    days: 3
  plan:
  - get: iacbox
  - get: 5-min
    trigger: true
  - task: test-concourse-v6.0
    image: iacbox
    timeout: 10m
    config:
      platform: linux
      run:
        path: sh
        args:
        - -c
        - "echo Test concourse v6.0"

````
**pipeline1 trace : issue**
<img width="1226" alt="Pipeline-1 issue" src="https://user-images.githubusercontent.com/20590107/78224510-4f4d7d80-74e6-11ea-86f4-657c55d4c8fa.png">

**pipeline1 trace: working**
<img width="1226" alt="pipeline-1-working" src="https://user-images.githubusercontent.com/20590107/78224573-6a1ff200-74e6-11ea-9f2e-035b71d9dbaa.png">


**pipeline2.yaml : image_resource in the task config rather than image in the build plan**
```
resources:
- icon: av-timer
  name: 5-min
  source:
    interval: 5m
  type: time
jobs:
- name: test-concourse-v6.0-test
  serial: true
  build_log_retention:
    days: 3
  plan:
  - get: 5-min
    trigger: true
  - task: test-concourse-v6.0
    timeout: 10m
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: weberstephanhd/iacbox2
          tag: v305
          username: ""
          password: ""
      run:
        path: sh
        args:
        - -c
        - "echo Test concourse v6.0"
```
with this pipeline definition it works always with few secs as expected. 
<img width="1225" alt="pipeline-2-working" src="https://user-images.githubusercontent.com/20590107/78224986-0f3aca80-74e7-11ea-8538-a616df3862f8.png">

Hopefully, this information helps to narrow down the problem?
