### ISSUE TITLE
'oci' material design icon not showing

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#5379]
The resource documentation (https://concourse-ci.org/resources.html#schema.resource.icon) lists https://materialdesignicons.com/ as the resource to find mdi icons.

But if I pick any of them (by means of search or via https://cdn.materialdesignicons.com/5.0.45/ ) they only show up as white question mark in a white circle.

Example:
```
- name: env-musl
  type: registry-image
  icon: mdi-oci
  source:
    repository: quay.io/drahnr/rust-musl-builder
```

Other items not working `mdi-git`, `mdi-github`, `mdi-oci` but despite not being part of this list `circle-github`,`git`,`docker` work, but `oci` does not.

What is the pattern or where can a viable translation resources be found?
