### ISSUE TITLE
Named var sources conflict with k8s secret manager

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5413]
## Bug Report

It looks like `var_sources` straight up doesn't work if you have k8s configured as a global credential manager.

## Steps to Reproduce

1. Configure k8s as a global credential manager.
2. Configure the following pipeline (thanks @allandegnan!):

```yaml
var_sources:
- name: dumb
  type: dummy
  config:
    vars:
      simple: hello!
      user:
        username: big
        password: sekrit

jobs:
- name: do bad thing
  plan:
    - task: expose secret
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: debian
            tag: latest
        params:
          FOO: yoyo
        run:
          path: /bin/sh
          args:
            - -c
            - |
                echo  ((dumb:user.username))
                env
```

## Expected Results

This should resolve `((dumb:user.username))` to `big` and the build should succeed.

## Actual Results

The build errors with the following message:

```
failed to interpolate task config: var lookup 'dumb:user.username': unable to split kubernetes secret path into [namespace]:[secret]: hush-house-main:k8s-var-sources.dumb:user
```

## Additional Context

Error comes from here:

https://github.com/concourse/concourse/blob/37d4934c510355ba429abdd09599013ed3cfb2b9/atc/creds/kubernetes/secrets.go#L40-L42

There's a question of how/why we're even getting to this code path, since I would have expected us to try a named var source first, since it's using the named syntax.

There's another problem here too: if we're using `:` as the named var syntax, we can't expect to also use it for k8s namespace syntax. 🤔 How can we resolve that ambiguity?

## Version Info

* Concourse version: 6.0
* Deployment type (BOSH/Docker/binary): any
* Infrastructure/IaaS: any
* Browser (if applicable): n/a
* Did this used to work? probably not
