### ISSUE TITLE
Document the default when no image is specified (neither in pipeline nor task yml)

### ISSUE THREAD

**Issue by bhuvnesh2703** [concourse/concourse#543]
Concourse allows you to have a task running a command like:

```
      run:
          path: cat
          args:
          - ami-id/ami-id.txt
```

when no image is specified, neither in the pipeline nor in the task configuration. It seems to give a default container of some kind -- can we document this behavior?
