### ISSUE TITLE
fly validate-pipeline is not validating missing resource in task configuration

### ISSUE THREAD

**Issue by tupti** [concourse/concourse#5464]
## Summary

> A brief summary of the problem.
validate-pipeline is returning 'looks good' for pipeline where you miss resource declaration and getting it by input, but you only use it as image in task configuration.
## Steps to reproduce

resources:

- name: repo
  type: git
  source:
    uri: https://github.com/concourse/bin.git

jobs:
- name: test
  plan:
    - in_parallel:
      - get: repo
      - task: hello-world
        **image: python.image**
        config:
          platform: linux
          inputs:
          - name: repo
          run:
            path: /bin/bash
            args:
            - -c
            - |
              echo "hello-world"

> Starting from `docker-compose up`, what steps can be followed to reproduce
> the problem?
>
> Please use https://gist.github.com for large snippets!

## Expected results

It should state that you are missing resource or something like this.

## Actual results

'looks good', even if you use --strict

## Triaging info

* Concourse version: 5.7.0
* Browser (if applicable):
* Did this used to work?
I don't think so

**Comment by pivotal-jamie-klassen** [comment]
@tupti in general I don't believe such a validation is possible. Let's imagine the following pipeline:
```yaml
resources:
- name: config-repo
  type: git
jobs:
- name: build-image-and-run
  plan:
  - get: config-repo
  - task: build-image
    file: config-repo/build-image.yml
  - task: run-in-image
    image: new-image # <-- look here!
    file: config-repo/task-to-run.yml
```
Now as long as the file `build-image.yml` in my `config-repo` has an output named `new-image` declared, this pipeline is valid. But if I change that file there's no way to statically tell, since the actual task config is dynamically resolved.

Perhaps the key thing to understand is that `image:` does _not_ have to be the name of a resource, but it can be an arbitrary _artifact source_ (which includes caches and task inputs/outputs), as mentioned in [the docs](https://concourse-ci.org/jobs.html#schema.step.task-step.image). This concept is not very heavily documented, I think.
