### ISSUE TITLE
Concourse (or runc) leaves an every-growing collection of pipes open, eventually exhausting FD limits.

### ISSUE THREAD

**Issue by colstrom** [concourse/concourse#547]
Can be reproduced with the following pipeline (tested on Ubuntu 16.04).

```

---
resources:
  - name: regularly
    type: time
    source:
      interval: 60s
jobs:
  - name: leak-file-descriptors
    plan:
      - get: regularly
        trigger: true
      - task: test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          run:
            path: /bin/echo
```

Deploy, and watch the open pipes on the worker

```
watch "lsof 2>/dev/null | grep -E '^(concourse|runc).*pipe\$' | wc -l"
```

The count will grow, and eventually the job will being failing, or the resource will stop delivering new versions.

This can be accelerated with a more complex pipeline. Rate of growth is proportional to steps in pipeline.
