### ISSUE TITLE
Image and Input Volumes provided by a resource maybe streamed redundantly for a Task

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#5485]
## Summary

If a Task references a previous step (eg. Get step fetching an image ) for its image and ends up being scheduled on worker `ABC`, while the previous step was scheduled on worker `123`, the volume for the image will be streamed from `123` to `ABC` even if the image cache exists on `ABC`.

This also impacted streaming of inputs that were backed by a resource.

## Steps to reproduce
- Setup Concourse with multiple workers ( was able to reproduce with docker compose )
- Fly a pipeline with a Task whose image references the output of a previous step
```
resources:
- name: apl
  type: registry-image
  source:
      repository: concourse/git-resource
      tag: dev-ubuntu
jobs:
- name: test-image-as-resource
  plan:
  - get: apl
    trigger: true
  - task: echo
    image: apl
    config:
        platform: linux
        run:
            path: sh
            args:
            - -c
            - |
                echo "foo"
```
- Execute builds until the resource cache volume exists on all workers
For example, with 3 workers
```
$ fly -t dev volumes
handle                                worker        type           identifier
2cbe1c52-4db0-4194-6ff6-9bcaeb18335c  31a442213347  resource       digest:sha256:cd47ec95bd17cd15382e4894c9a4be0e22cb2d3a7a60ea71aad9ace005fd1826
c7782d3c-cbb2-4320-77d0-3aa81416e63e  6ff99779506a  resource       digest:sha256:cd47ec95bd17cd15382e4894c9a4be0e22cb2d3a7a60ea71aad9ace005fd1826
26b6b62c-59bc-4be9-70da-abc3304a6743  9db63a79bb32  resource       digest:sha256:cd47ec95bd17cd15382e4894c9a4be0e22cb2d3a7a60ea71aad9ace005fd1826

```
- As the cache exists on all 3 workers, subsequent builds shouldn't require the `Task`'s image to be streamed. However, we observed via log statements and observing the initialization time for the `Task` step that it was indeed streaming the volume from the `123` that was chosen for the `Get` step to `ABC` chosen for the Task.

Relevant source code
- [client uses image referenced via previous step](https://github.com/concourse/concourse/blob/master/atc/worker/client.go#L250-L255)

[Original Discussion](https://github.com/concourse/concourse/discussions/5378)

## Expected results
When the Task's worker has the image volume required by the task, the volume is not streamed from the previous step's worker.

## Actual results
Concourse may redundantly stream volumes when
- Task's image is referencing the output of a previous Get step 
- For a given build, the Task and Get steps end up on different workers.

## Triaging info

* Concourse version: v6.0.0
* Did this used to work? Yes
