### ISSUE TITLE
unhelpful error message

### ISSUE THREAD

**Issue by hemna** [concourse/concourse#5499]
## Summary

running fly to execute a pipeline that's been validated, and the error message is
"error: resource not found"

What resource? which one?

My pipeline.yml
```
---
resources:
  - name: goestools-src
    type: git
    source:
      uri: https://github.com/hemna/docker-goestools
      branch: master

  - name: goestools-docker-image
    type: docker-image
    source:
        repository: https://192.168.1.3:5000/hemna/goestools
        tag: latest

jobs:
  - name: build-and-publish-goestools
    public: true
    serial: true
    plan:
      - get: goestools-src
      - put: goestools-docker-image
        params:
            build: docker-goestools
```

My script that runs it.

```
#!/bin/bash

set -eu

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export fly_target=${fly_target:-hemna}
echo "Concourse API target ${fly_target}"
echo "Hemna $(basename $DIR)"

pushd $DIR
  fly  -t ${fly_target} set-pipeline -p goes -c try.yml -n
  fly  -t ${fly_target} unpause-pipeline -p goes
  fly --verbose -t ${fly_target} trigger-job -w -j goes/publish-goestools
popd
```

The output:

```
waboring@dl360-1:~/docker/concourse/mine/goestools:(git::master) $  ./try.sh
Concourse API target hemna
Hemna goestools
~/docker/concourse/mine/goestools ~/docker/concourse/mine/goestools
no changes to apply
unpaused 'goes'
2020/04/24 14:42:30 GET /api/v1/info HTTP/1.1
Host: 192.168.1.3:8080
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2020/04/24 14:42:30 HTTP/1.1 200 OK
Content-Length: 84
Content-Type: application/json
Date: Fri, 24 Apr 2020 18:42:30 GMT
Vary: Accept-Encoding
X-Concourse-Version: 6.0.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

{"version":"6.0.0","worker_version":"2.2","external_url":"http://192.168.1.3:8080"}

2020/04/24 14:42:30 POST /api/v1/teams/main/pipelines/goes/jobs/publish-goestools/builds HTTP/1.1
Host: 192.168.1.3:8080
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept-Encoding: gzip


2020/04/24 14:42:30 HTTP/1.1 404 Not Found
Content-Length: 0
Content-Type: application/json
Date: Fri, 24 Apr 2020 18:42:30 GMT
Vary: Accept-Encoding
X-Concourse-Version: 6.0.0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block


error: resource not found
```
