### ISSUE TITLE
Terraform Vault configuration

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5560]
Unfortunately, we can't cleanly automate everything in a single terraform project, since we need to run `vault operator init` after creating Vault, but before configuring it (since we need to get the root token) - see #5559.

The process can still be completely automated, by having the following pipeline:

```
- put: terraform-production
  ...
- task: ensure-vault-initialized
  ...
  outputs:
  - name: vault_token
- put: terraform-production-vault
  ...
  params:
    vars:
      tokenFile: vault_token/token
```

This terraform will need to automate a few things:

- [x] Enable cert auth backend
- [x] Apply policy granting read access to `concourse/*`
- [x] Configure Vault CA cert as valid for auth (the creation of the cert should probably be done in the main TF, but storing the cert in Vault's trusted certs should be here)
- [x] Configure KV store at `concourse`
- [x] Write `gcp_credentials_json` secret

**A/C**
Given an empty environment
When I run the Greenpeace pipeline
And I add a secret to the vault server
Then jobs on the newly deployed concourse deployment should be able to access that secret
