### ISSUE TITLE
Terraform Datadog Helm release

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5561]
I'm not sure what exactly is entailed here and beyond for configuring datadog.

**Comment by cirocosta** [comment]
### desired outcome

What we intend here is to have metrics from both Concourse and the infrastructure (being on top of k8s, mostly container-related statistics) being sent to Datadog so that our Datadog dashboards work properly.

The way that we've been going about doing that so far has been by leveraging Datadog's Helm Chart (see https://github.com/helm/charts/blob/master/stable/datadog/README.md), which creates a DaemonSet that deploys its agent across all hosts in the cluster, thus, gathering container statistics from all of machines, as well as providing a unix socket that those wanting to submit custom metrics to it can do so via that socket.



```

machine1-----------------------------------
        datadog pod------------------------
                container------------------
                        dd agent
                                listens for conns on /var/run/datadog/dsd.socket
                                captures metrics about container in the machine
                                        (mounts /sys/fs/cgroup, /proc/ and docker.sock)

        concourse pod ---------------------
                container------------------
                        concourse web
                                writes metrics to /var/run/datadog/dsd.socket

```

ps.: this desired outcome is *different* from https://github.com/concourse/concourse/issues/5528 - all we want here is to be able to gather the metrics and forward them to datadog. In #5528, the asumption is that the data already exists in datadog, and then there we want to be able to have the dashboards that consume that data be described as code.


### extra context

In today's setup, `requirements.yaml` references the datadog chart:

```yaml
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.39.5
```

which is what gives us the ability to submit to Kubernetes the definition of the daemonset that will materialize the pods across all machines.

As the agents need to be able to send the metrics they collect & receive to our account, we provide to the datadog chart the apiKey, which turns into a secret, which is then consumed by the agents:

```
## .values.yaml
datadog:
  datadog:
    apiKey: 08d215b0f1bf8f39b338349d63a2ba5d
```

Given that we want to submit Concourse metrics to it, we tell it to listen for `dogstatsd` metrics on a unix socket at a known location:

```yaml
datadog:
  datadog:
    useDogStatsDSocketVolume: true
```

Knowing the location where the unix socket lives in the host, in `concourse` we can have it mounted (so that they both point at the same socket):

```yaml
    additionalVolumes:
      - name: dsdsocket
        hostPath:
          path: /var/run/datadog
    additionalVolumeMounts:
      - name: dsdsocket
        mountPath: /var/run/datadog
```

with the `web` container having the socket accessible as a file in the `/var/run/datadog` directory, all that we need to do to finish the setup is to have Concourse enabling the datadog emitter, pointing it to the socket:

```
      datadog:
        enabled: true
        # horrible hack; we need a proper way to configure unix sockets
        agentHost: unix
        agentPort: ///var/run/datadog/dsd.socket
```
