### ISSUE TITLE
`ci skip` ignored when global resources is enabled

### ISSUE THREAD

**Issue by sfunkhouser** [concourse/concourse#5601]
## Summary

After turning on global resources we noticed that pipelines that depend on `ci skip` for some automated updates ended up going in infinite loops. These pipelines had a separate defined resource for the `get` vs the `put`. However, the `resource.config` end up being the same so they pointed back to the same global resource. 

Workaround is to make the `resource.config` different between the two. We added `disable_ci_skip: false` to the `get` resource. This is a no-op because its the default but makes the `resource.config` different between the two resources. 

From discord: 
```
Previously, version history was tied to pipeline resources, so that 'hack' of repeating the same resource definition worked, but now that they're fully equivalent it doesn't help to just split it out. so it actually is because of global resources, and adding the config worked because it made their config different
```

## Steps to reproduce

Create a simple pipeline that has two resources defined, one for `get` and one for `put`:

```
resources:
  - name: master
    type: git
    source:
      uri: url-to-git-repo
      branch: master
      private_key: REDACTED

  - name: master-bumped
    type: git
    source:
      uri: url-to-git-repo
      branch: master
      private_key: REDACTED

jobs: 
  - name: master-bump
    plan:
      - get: master
        trigger: true
      - task: bump-version
        config:
          platform: linux
          ....
          .... config things
          ....
          run:
            path: sh
            args:
              - -exc
              - |
                # DO SOME THINGS HERE, but not really important .... #
                git config --global user.email "someone@someone.com"
                git config --global user.name "someone"

                # COMMIT using ci skip
                git commit -m "[ci skip] bump version to ${VERSION}"

      - put: master-bumped
         params:
          action: push
          repository: master
```

## Expected results

When global resources is off, this works fine and the commits showing up for the `get` resource do not include the `ci skip` commits.

When global resources is on all commits, including those from the `put` with `ci skip`, show up in the `get` resource, causing an infinite loop. 

## Actual results

The behavior should be consistent if global resources is on or off. A commit with `ci skip` should be ignored by the `get` step. 

## Additional context

https://github.com/concourse/concourse/issues/3463 should fix this issue

## Triaging info

* Concourse version: 6.0.0
* Browser (if applicable): n/a
* Did this used to work? Yes, prior to enabling global resources
