### ISSUE TITLE
Rename job with old_name = name cause web node panic

### ISSUE THREAD

**Issue by xtremerui** [concourse/concourse#5606]
## Summary
When use `old_name` with same value of `name` for a job the atc will crash with stack over flow error
```
web_1     | runtime: goroutine stack exceeds 1000000000-byte limit
web_1     | runtime: sp=0xc020d44498 stack=[0xc020d44000, 0xc040d44000]
web_1     | fatal error: stack overflow
web_1     |
web_1     | runtime stack:
web_1     | runtime.throw(0x379ed6f, 0xe)
web_1     | 	/usr/local/go/src/runtime/panic.go:1116 +0x72
web_1     | runtime.newstack()
web_1     | 	/usr/local/go/src/runtime/stack.go:1034 +0x70e
web_1     | runtime.morestack()
web_1     | 	/usr/local/go/src/runtime/asm_amd64.s:449 +0x8f
web_1     |
web_1     | goroutine 1001 [running]:
web_1     | github.com/concourse/concourse/atc/db.sortUpdateNames(0xc00000f6c0, 0x1, 0x1, 0x4, 0xc020d44668, 0x0)
web_1     | 	/src/atc/db/team.go:922 +0x4f8 fp=0xc020d444a8 sp=0xc020d444a0 pc=0x1992c18
web_1     | github.com/concourse/concourse/atc/db.sortUpdateNames(0xc00000f6c0, 0x1, 0x1, 0x0, 0x0, 0x0)
web_1     | 	/src/atc/db/team.go:934 +0x3f5 fp=0xc020d446c0 sp=0xc020d444a8 pc=0x1992b15
web_1     | github.com/concourse/concourse/atc/db.sortUpdateNames(0xc00000f6c0, 0x1, 0x1, 0x0, 0x0, 0x0)
web_1     | 	/src/atc/db/team.go:934 +0x3f5 fp=0xc020d448d8 sp=0xc020d446c0 pc=0x1992b15
web_1     | github.com/concourse/concourse/atc/db.sortUpdateNames(0xc00000f6c0, 0x1, 0x1, 0x0, 0x0, 0x0)
```

## Steps to reproduce
1. set a pipeline 
```
resources:
- name: booklit
  type: git
  source: {uri: "https://github.com/vito/booklit"}

jobs:
- name: unit
  serial: true
  plan:
  - get: booklit
    trigger: true
  - task: test
    file: booklit/ci/test.yml
```
2. set the pipeline again with `old_name`
```
resources:
- name: booklit
  type: git
  source: {uri: "https://github.com/vito/booklit"}

jobs:
- name: unit
  old_name: unit
  serial: true
  plan:
  - get: booklit
    trigger: true
  - task: test
    file: booklit/ci/test.yml
```

## Expected results
Nothing should change and fly exit with 0

## Actual results
fly hang a bit and then web node crashed

* Concourse version: 6.1
* Did this used to work? No
