### ISSUE TITLE
Task step `vars:` field should support interpolation

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5609]
## Summary

e.g.:

```yaml
- name: do-something-with-image-digest
  serial: true
  plan:
  - get: image-name
  - load_var: image
    file: image-name/digest
  - task: write-image-digest-somewhere
    file: task.yml
    vars:
      image: ((.:image))
```

This currently does not expand `((.:image))` - it passes it verbatim to the task. It should!

## Context

* Prior discussion: #5607
