### ISSUE TITLE
Why couldn't the `minor` job bump the version with a single `put` step?

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5629]
The [`minor` job](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/minor) is configured like so:

```yaml
- name: minor
  public: true
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: minor, pre: rc}
```

These builds were triggered yesterday:

* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/minor/builds/2
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/minor/builds/3
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/minor/builds/4

The first build successfully bumped to `6.1.0-rc.1`. However the next build was not able to bump from `6.1.0-rc.1` to `6.2.0-rc.1` - they just left the version as-is.

Once the build was changed to a `get` (with locally bumped version) -> `put` (with version from file), it worked.

Why didn't the single `put` with inline bump params work?

(@clarafu and @xtremerui have context)
