### ISSUE TITLE
fly execute fails when all workers are tagged

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5672]
## Summary

`fly execute` fails with a 500 status code when all of the workers have tags. The following error shows up on the atc:

```
web_1                | {"timestamp":"2020-05-27T15:12:26.638508447Z","level":"error","source":"atc","message":"atc.create-artifact.failed-to-create-volume","data":{"error":"no workers satisfying: platform 'linux'","session":"4652"}}
```

## Steps to reproduce

Use the following override file with `docker-compose`:

```
version: '3'

services:
  worker:
    environment:
      CONCOURSE_TAG: "some_tag"
```

Run `fly execute`:
`fly -t dev execute -c task.yml --tag some_tag`

## Expected results
Task runs successfully.

## Actual results
```
uploading concourse ⠋ (2.0MiB/s)
error: 'uploading concourse' failed: Unexpected Response
Status: 500 Internal Server Error
Body:
```

## Additional context
If a non-tagged worker is added to the deployment the task runs correctly on the specified worker.

## Triaging info

* Concourse version: 36cbf5ecf628dba92b6b4c08cfa536820638f313
* Did this used to work? 🤷

**Comment by aliculPix4D** [comment]
Hi,

Thanks to @aoldershaw for reporting this issue. I would just like to add that we are experiencing the same bug with `fly execute` when all of the platform workers are tagged. 
For example:
running `fly -t target sp -p test-tags -c test-tags.yml` where `test-tags.ym` is given as:
```
---
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        tags: ["catalina"]
        config:
          platform: darwin
          run:
            path: /bin/echo
            args: ["Hello, world!"]
```
runs successfully, while running `fly -t target execute -c test-task.yml --tag="catalina"` returns `status: 500 Internal Server Error` with the following error message:
```
{"timestamp":"2020-06-01T13:48:00.783858733Z","level":"error","source":"atc","message":"atc.create-artifact.failed-to-create-volume","data":{"error":"no workers satisfying: platform 'darwin'","session":"17838646"}}
```
`test-task.yml` looks like:
```
---
platform: darwin

run:
  path: /bin/echo
  args:
    - "Hello, world!"
```
