### ISSUE TITLE
Set Pipeline step `vars:` field should support interpolation

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5709]
## Summary

e.g.:

```yml
- name: reconfigure-promote
  plan:
  - get: pipelines-and-tasks
    trigger: true
    passed: [reconfigure-self]
  - get: latest-concourse
    trigger: true
  - load_var: release-version
    file: latest-concourse/version
  - set_pipeline: promote
    file: pipelines-and-tasks/pipelines/promote.yml
    vars: {release_version: ((.:release-version))}
```

Right now this configures the pipeline with the literal value `((.:release-version))` set in the pipeline, rather than being interpolated first.

## Context

* Very similar to #5609
