### ISSUE TITLE
After update to 6.2.0: failed to retrieve kernel parameter

### ISSUE THREAD

**Issue by kramerul** [concourse/concourse#5711]
## Summary

After updating concourse from 6.1.0 to 6.2.0, we get the error message

```
failed to retrieve kernel parameter "net.ipv4.tcp_keepalive_time": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory
```
In the worker logs, we can find:

```
{"timestamp":"2020-06-03T08:22:15.787525864Z","level":"error","source":"guardian","message":"guardian.create.containerizer-create.bundle-generate-failed","data":{"error":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.3"}}
{"timestamp":"2020-06-03T08:22:15.787634290Z","level":"info","source":"guardian","message":"guardian.create.containerizer-create.finished","data":{"handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.3"}}
{"timestamp":"2020-06-03T08:22:15.787655597Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.start","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4"}}
{"timestamp":"2020-06-03T08:22:15.787670221Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.started","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4.1"}}
{"timestamp":"2020-06-03T08:22:15.787682661Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.delete.started","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4.1.1"}}
{"timestamp":"2020-06-03T08:22:15.809938776Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.delete.state-failed-skipping-delete","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","error":"runc state: runc: exit status 1: container \"da525953-d55c-4b88-643a-9ab36070049c\" does not exist","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4.1.1"}}
{"timestamp":"2020-06-03T08:22:15.809978760Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.delete.finished","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4.1.1"}}
{"timestamp":"2020-06-03T08:22:15.809990217Z","level":"info","source":"guardian","message":"guardian.create.create-failed-cleaningup.destroy.finished","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4.1"}}
{"timestamp":"2020-06-03T08:22:15.810004624Z","level":"error","source":"guardian","message":"guardian.create.create-failed-cleaningup.no-properties-for-container-skipping-destroy-network","data":{"cause":"failed to retrieve kernel parameter \"net.ipv4.tcp_keepalive_time\": open /proc/sys/net/ipv4/tcp_keepalive_time: no such file or directory","error":"property not found: kawasaki.host-interface","handle":"da525953-d55c-4b88-643a-9ab36070049c","session":"36.4"}}

```
when starting a task

## Steps to reproduce

* Update to 6.2.0
* Run a task

## Expected results

Task runs without errors.

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by kramerul** [comment]
After switching back to version 6.1.0, the problem still occurs.

**Comment by kramerul** [comment]
See also https://github.com/concourse/concourse-docker/issues/61

**Comment by jamieklassen** [comment]
Can you give some more details about your system -- what kind of packaging are you using to deploy concourse (binary/systemd/bosh/helm/docker/etc)? What is the underlying OS/distribution? Any kernel configuration could be useful too.

While we're at it, can you provide the task you were using as well? You never know what details might be helpful.

**Comment by kramerul** [comment]
We are using docker-compose to run this concourse instance. It's running on AWS.
The docker node was set up using docker-machine (ubuntu 16.04, docker version 19.03.11)

```
docker-machine create -d amazonec2 \
    --amazonec2-region <redacted> --amazonec2-zone <redacted> --amazonec2-instance-type t3.xlarge \
    --amazonec2-root-size 500 \
    --amazonec2-security-group <redacted> \
    concourse
```

We used the following docker-compose file

```
version: '3'

services:
  nginx:
    image: linuxserver/letsencrypt
    ports: ["443:443","80:80"]
    environment:
      URL:   <redacted>
      EMAIL: <redacted>
      VALIDATION: http

  db:
    image: postgres:11
    environment:
      POSTGRES_DB: <redacted>
      POSTGRES_USER: <redacted>
      POSTGRES_PASSWORD: <redacted>
    volumes: ["pgdata:/var/lib/postgresql/data"]

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    volumes:
      - "concourse-keys-web:/concourse-keys"
      - "users:/users"
    environment:
      CONCOURSE_EXTERNAL_URL: <redacted>
      CONCOURSE_POSTGRES_HOST: <redacted>
      CONCOURSE_POSTGRES_USER: <redacted>
      CONCOURSE_POSTGRES_PASSWORD: <redacted>
      CONCOURSE_POSTGRES_DATABASE: <redacted>
      CONCOURSE_ADD_LOCAL_USER: <redacted>
      CONCOURSE_MAIN_TEAM_CONFIG: /users/users.yml
      CONCOURSE_AWS_SECRETSMANAGER_ACCESS_KEY: <redacted>
      CONCOURSE_AWS_SECRETSMANAGER_SECRET_KEY: <redacted>
      CONCOURSE_AWS_SECRETSMANAGER_REGION: <redacted>
      CONCOURSE_GITHUB_CLIENT_ID: <redacted>
      CONCOURSE_GITHUB_CLIENT_SECRET: <redacted>
      CONCOURSE_GITHUB_HOST: <redacted>

  worker_1:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["concourse-keys-worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222

volumes:
  concourse-keys-worker:
    external: true
  concourse-keys-web:
    external: true
  pgdata:
  users:

```
