### ISSUE TITLE
fatal: cannot chdir to 'E:/jobs/concourse/data/volumes/live/423d1736-5b6a-462f-6e2a-34a92d6ff3b8/volume': No such file or directory

### ISSUE THREAD

**Issue by hdhog** [concourse/concourse#5722]
## Summary

worker on windows server core 2016 6.2.0

Error on put to git resource

![image](https://user-images.githubusercontent.com/386666/84029801-0ca39800-a9a4-11ea-8581-b4d0f2057ea2.png)

Volume folder on disk is exists

![image](https://user-images.githubusercontent.com/386666/84030226-ba16ab80-a9a4-11ea-90d5-119bbaf1e5d2.png)

## Steps to reproduce

- get repo with 4k+ files
- update some files
- put chages to repo

## Additional context
task.yml
```
---
platform: windows

inputs:
- name: app_code
- name: code_docs
- name: pipeline

outputs:
- name: builds

run:
  path: C:\Program Files\PowerShell\7\pwsh.exe
  args:
  - -NoProfile
  - -NonInteractive
  - -ExecutionPolicy
  - Bypass
  - -File
  - '.\pipeline\scripts\build_docs.ps1'

```

build script

```powershell
$ErrorActionPreference = "Stop"
trap { $host.SetShouldExit(1) }
$cmake = "C:\Program Files\CMake\bin\cmake.exe"
if (!(Test-Path $cmake)) {
    Write-Error "cmake not found"
    exit 1;
}

$build_dir = "_build"
if (!(Test-Path $build_dir)) {
    New-Item -ItemType Directory $build_dir | Out-Null
    Write-Output "Creating build dir '$build_dir'"
}

git clone code_docs builds

Push-Location $build_dir

"##################### Generating build ####################"

"##### Removing items"
Remove-Item -Recurse ..\builds\code\html\*.* -force

& $cmake -DLAPS_SOURCE_DIR="..\app_code\src" ..\builds
if ($LASTEXITCODE -ne 0) {
    "##### configure fail"
    exit 1
}

Pop-Location

& $cmake --build $build_dir --target doc_doxygen

if ($LASTEXITCODE -ne 0) {
    "##### Build faile"
    exit 1
}
Push-Location code_docs

git config --global user.email "user@example.com"
git config --global user.name "Concourse"
git config core.autocrlf true
git add code
git commit -m "$(get-date)"
Pop-Location

```

## Triaging info

* Concourse version: 6.2.0
