### ISSUE TITLE
Task vars causing concourse to ignore the credential manager resolution

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#5753]
## Summary

When a task specifies `vars` concourse seems to not even attempt to resolve task vars via the configured credential manager. 

If one doesn't specify `vars` all of the tasks vars are resolved via the credential manager as expected.

## Steps to reproduce

1) Setup concourse with a credential manager (in our case vault but not sure if specific to vault).

2) Create a task definition with vars defined (making sure they exist in vault), e.g.:
```
params:
  MY_VAR: ((some-var))
```

3) invoke the task with:
```
- task: run-task
  file: resource/task.yml
```

4) invoke the task with:
```
- task: run-task-with-var
  file: resource/task.yml
  vars:
    blah: hello
```

## Expected results

Both tasks invocations should run

## Actual results

Invoking the task with `vars` (step 4) fails with:
```
failed to interpolate task config: undefined vars: some-var
```

## Additional context

This was discovered after we upgraded from 6.0 to 6.2 (possible cause: https://github.com/concourse/concourse/pull/5620)

## Triaging info

* Concourse version: 6.2
* Browser (if applicable):
* Did this used to work? Yes (up to 6.0 at least)

**Comment by evanchaoli** [comment]
I just tried to reproduce the issue, and confirmed the bug is introduced by #5620. The root cause is that, I used `InterpolateTemplateConfigSource` to interpolate task vars first: https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L163-L166, but I didn't notice that `InterpolateTemplateConfigSource` expects all keys: https://github.com/concourse/concourse/blob/master/atc/exec/task_config_source.go#L179.

I'll submit a fix soon.

**Comment by Jaypinto** [comment]
Hi,

I seem to be encountering the same problem on 6.4. I've configured my task like this:

- task: Extract 
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        run:
          path: sh
          args:
          - -c
          - |
            env
            echo ((nexus))
      params:
        CONCOURSE_VAULT_URL: <url>
        CONCOURSE_VAULT_CLIENT_TOKEN: <token>
        CONCOURSE_VAULT_AUTH_BACKEND: <app role>
        CONCOURSE_VAULT_AUTH_PARAM: <auth param>
        CONCOURSE_VAULT_PATH_PREFIX: <prefix>

I see the following error: 

failed to interpolate task config: undefined vars: nexus

This task is running on a concourse worker and the environment variables are passed from a parameters.yaml file. I tried hardcoding the parameter values and then omitting the parameters.yaml file but that did not make a difference. Am I missing something?

Thans,

Jason

**Comment by aoldershaw** [comment]
Hey @Jaypinto, it looks like the issue you're running into is how you're configuring vault.

The `CONCOURSE_VAULT_*` environment variables are meant to be passed into the `concourse web` process, not tasks themselves. Defining those variables sets up a global credential manager that you can use across all pipelines.

For more details on configuring vault as a global credential manager, see https://concourse-ci.org/vault-credential-manager.html (though I'm guessing you already saw this, but it wasn't obvious that it had to be set on the `web` process rather than the task)

---

Alternatively, if you don't operate your own Concourse instance or don't want to setup a global credential manager, you can define pipeline-local credential managers using `var_sources`. For instance, your pipeline might look like:

```yaml
var_sources:
- name: vault
  config:
    url: url
    client_token: token
    auth_backend: approle
    auth_params: {role_id: abc}
    path_prefix: prefix

jobs:
- name: some-job
  plan:
  - task: extract
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sh
        args:
        - -c
        - |
          env
          echo ((vault:nexus))
```

Note that the variable is now referenced as `((vault:nexus))`.

For more details on configuring `var_sources`, take a look at https://concourse-ci.org/vars.html#schema.var_source.

---

Hope this helps! Let me know if you're having any trouble getting it setup
