### ISSUE TITLE
Non-root container users - usability suboptimal

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#5759]
## Summary

Non-default container users have quite a few usability issues.

* caching is owned by root
* all mapped/mounted resources are owned by root

## Steps to reproduce

![image](https://user-images.githubusercontent.com/667047/84507102-9911cb80-acc0-11ea-8e3d-f61cd1a121b2.png)

```yaml
      - task: validate-meta
        timeout: 15m
        image: env-glibc
        config:
          platform: linux
          inputs:
          - name: git-repo
          run:
            # user: root
            path: sh
            args:
            - -exc
            - |
              export CARGO_HOME="$(pwd)/../cargo"
              rustc +stable --version --verbose
              cargo +stable fmt --check
              #cargo spellcheck --check
            dir: git-repo
          caches:
          - path: cargo
```

## Expected results

All resources are available to the current user, either bei mounting them with `ugo+rw` or changing ownership.

## Actual results

![image](https://user-images.githubusercontent.com/667047/84507261-d2e2d200-acc0-11ea-91c3-afd4b8f601bf.png)

Failure to access.

## Triaging info

* Concourse version: 6.2
* Browser (if applicable): firefox
* Did this used to work? No
