### ISSUE TITLE
Task file vars interpolation does not work for container_limits element

### ISSUE THREAD

**Issue by holgerstolzenberg** [concourse/concourse#5765]
## Summary
Having a pipeline with a task file whose `container_limits` are hard coded is working for us.
When we try to make the container limits configurable, the build breaks with an unparseble task file.

Working:
```yaml
---
platform: linux

container_limits:
  cpu: 32696
  memory: "5gb"

image_resource:
  type: docker-image
  source:
    repository: adoptopenjdk14-dind
    tag: latest
    insecure_registries: ['any.registry.com']
    username: ((concourse_user))
    password: ((concourse_password))

[…]
```

Not working:
```yaml
---
platform: linux

container_limits:
  cpu: 32696
  # configured via vars: in the pipeline
  memory: ((container_mem_limit)) 

image_resource:
  type: docker-image
  source:
    repository: adoptopenjdk14-dind
    tag: latest
    insecure_registries: ['any.registry.com']
    username: ((concourse_user))
    password: ((concourse_password))

[…]
```

## Expected results
The container limits in a task file should work from configured `vars:` in the pipeline.

## Actual results
Concourse cannot launch the task complaining that for example the memory limit cannot be parsed for the task file.
<img width="1364" alt="Screenshot 2020-06-15 at 12 55 09" src="https://user-images.githubusercontent.com/282736/84649810-77565580-af07-11ea-8797-876e1082cb18.png">

## Additional context
Might be related to #5753 

## Triaging info
* Concourse version: 6.2
* Did this used to work? => Unsure, tested it the first time with 6.2
