### ISSUE TITLE
Upgrade to v5.8.0 failed with 'panic: runtime error: invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by skreddy6673** [concourse/concourse#5788]
## Summary
Upgrade from v5.7.1 to v5.8.0 and the web nodes started to error with following message.

## Steps to reproduce

> Deploy the helm chart with v5.8.0 and newrelic emitter enabled.
```
newrelic:
      enabled: true

      ## New Relic Account ID
      ##
      accountId: "XXXXXXX"

      ## New Relic Insights API Key
      ##
      apiKey:

      ## An optional prefix for emitted New Relic events
      ##
      servicePrefix: concourse_dev_

      ## Number of events to batch together before emitting
      ##
      batchSize:

      ## Length of time to wait between emitting until all currently batched events are emitted
      ## Example: 60s
      ##
      batchDuration:

      ## Disables compression of the batch before sending it
      ##
      disableCompression:
```

## Expected results

Web nodes start and metrics sent to new relic.

## Actual results
Web nodes failed to start with below logs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x191a9d1]

goroutine 12 [running]:
github.com/concourse/concourse/atc/metric/emitter.(*NewRelicEmitter).Emit(0xc0006cad20, 0x37277e0, 0xc00113a540, 0x2d50cf0, 0xe, 0x2953d60, 0x49ec6a0, 0x2d3d0ff, 0x2, 0xc000717650, ...)
        /tmp/build/1c3187db/concourse/atc/metric/emitter/newrelic.go:109 +0x891
github.com/concourse/concourse/atc/metric.emitLoop()
        /tmp/build/1c3187db/concourse/atc/metric/emit.go:148 +0x133
created by github.com/concourse/concourse/atc/metric.Initialize
        /tmp/build/1c3187db/concourse/atc/metric/emit.go:108 +0x3c8
```

## Additional context

If i deploy the same helm chart with newrelic disabled, it's running good.

## Triaging info

* Concourse version: v5.8.0
* Browser (if applicable): N/A
* Did this used to work? YES, i have another concourse instance v5.7.1 running with newrelic enabled.
