### ISSUE TITLE
Volumes can only be reused twice

### ISSUE THREAD

**Issue by philandstuff** [concourse/concourse#5799]
## Summary

If you input and output the same volume in 3 or more tasks in the same job, the third task will fail with `failed to create volume`.

## Steps to reproduce

Set the following pipeline:

```yaml
resources:
- name: some-resource
  type: mock
  source:
    create_files:
      some_file: |
        hello you

jobs:
- name: reuse-volumes
  plan:
  - get: some-resource
  - task: step1
    config: &modify_some_file
      platform: linux

      inputs:
      - name: some-resource

      outputs:
      - name: some-resource

      image_resource:
        type: mock
        source: {mirror_self: true}

      run:
        path: sh
        args:
        - '-ec'
        - |
          echo "and you" >> some-resource/some_file
  - task: step2
    config: *modify_some_file
  - task: step3
    config: *modify_some_file
  - task: show-results
    config:
      platform: linux

      inputs:
      - name: some-resource

      image_resource:
        type: mock
        source: {mirror_self: true}

      run:
        path: sh
        args:
        - '-ec'
        - |
          cat some-resource/some_file
```

Trigger the `reuse-volumes` job.  The job will fail at task `step3`.  (I can PR this as a `testflight` case if there is interest.)

## Expected results

The job should complete successfully, and the `show-results` task should output

```
hello you
and you
and you
and you
```

## Actual results

Task `step3` fails with `failed to create volume`.

## Additional context

We observed this in a bigger pipeline.  Looking at the systemd journal on the box, we found the line:

    Jun 19 15:40:59 ip-10-1-22-245 kernel: [  625.625135] overlayfs: maximum fs stacking depth exceeded

It is not possible to stack overlayfs mounts indefinitely; there is a [hardcoded limit of 2](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/fs.h#n251) in the linux kernel.

I suspect (but have been unable as yet to positively confirm) that concourse/baggageclaim#35 is the cause of this issue.

## Triaging info

* Concourse version: 6.3.0
* Browser (if applicable): N/A
* Did this used to work?  Yes, we upgraded from 6.0.0 where we did not observe this problem.

**Comment by philandstuff** [comment]
To add a bit more context: overlayfs supports multiple layers, but the way you are supposed to do it is by specifying each layer in a list in the mount command.  So you would do something like:

    mount -t overlay overlay -o lowerdir=/lower1:/lower2:/lower3,upperdir=/upper,workdir=/work /merged

which produces a layered filesystem containing layers (from bottom to top): `/lower3`, `/lower2`, `/lower1`, `/upper`.  This is okay because it's still a single overlayfs mount, with multiple layers in the same mount.

What concourse/baggageclaim seem to be doing is the equivalent of this:

    mount -t overlay overlay -o lowerdir=/lower3,upperdir=/lower2,workdir=/worka /mergeda
    mount -t overlay overlay -o lowerdir=/mergeda,upperdir=/lower1,workdir=/workb /mergedb
    mount -t overlay overlay -o lowerdir=/mergedb,upperdir=/upper,workdir=/workc /mergedc

this breaks because it's multiple overlayfs mounts built on top of one another.  I'm unsure but I think that concourse/baggageclaim#35 switched from the top (working, but complicated) strategy to the bottom (simpler, but broken in this case) strategy.

**Comment by vito** [comment]
Dang, good catch, and thanks for digging into the kernel to find the root cause.

We originally did https://github.com/concourse/baggageclaim/pull/35 because we started getting kernel errors with the prior approach: https://github.com/concourse/concourse/issues/4964

I guess we could re-consider the second option from this comment: https://github.com/concourse/concourse/issues/4964#issuecomment-571413851 - unfortunately it would mean copying data around, but it feels like we're running out of alternatives. 😕

**Comment by vito** [comment]
@philandstuff If it's OK with you, I plan to leave this open and see how many people run into this issue before deciding on the next step - it looks like you found a workaround.

**Comment by philandstuff** [comment]
It's also worth recording here that the documentation doesn't help come up with a workaround. 
 In particular, it's not clear when volumes get COWed (leading to this problem) and when they're created afresh (avoiding this problem).  For example, if I change `step1` to:

```
  - task: step1
    config:
      platform: linux

      inputs:
      - name: some-resource

      outputs:
      - name: some-other-resource
        path: some-resource

      # ...
```

and if I change `step2` and `step3` similarly, I actually still hit this problem, because even though each task is creating a new volume with a new name, it's the fact that they share a path that causes them to be COW volumes.

The only way I can see to work around this is:

 1. collapse separate tasks into the same task (where possible),
 2. don't use the same path for input and output volumes (copying (or hard linking?)) where necessary

I think this is work-around-able, but it's a bit of a speed bump.
