### ISSUE TITLE
Git: fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by space55** [concourse/concourse#5823]
## Summary

When cloning a repo through the Git resource (that the SSH key has access to, I checked by cloning using the same SSH key), I receive:

```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 128

stderr:
Identity added: /tmp/git-resource-private-key (ubuntu@ip-172-31-36-103)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Steps to reproduce

1. Run a fresh Concourse instance, with docker-compose
2. Create a sample pipeline, f.ex, one that clones the Concourse repo, then echo's "Hello" to the console
3. The concourse instance will fail

## Expected results

Should not receive that error

## Actual results

Fails to clone pipeline

## Additional context

Sample pipeline:

```yaml
resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:concourse/concourse.git
      branch: master
      private_key: ((git-key))

  - name: Run tests
    plan:
      - get: repo
        trigger: true
      - task: run the test suite
        file: repo/ci/tasks/run-tests.yml
```

## Triaging info

* Concourse version: Fresh 6.3.0 install on AWS EC2
* Browser (if applicable): Chrome, but I don't think that applies
* Did this used to work? Never worked on this fresh install, works on my other clusters, some running the same version

Minor additional discussion going on in https://discuss.concourse-ci.org/t/resource-script-opt-resource-check-failed-exit-status-128/2310
