### ISSUE TITLE
dynamic var interpolation in task_step file does not work

### ISSUE THREAD

**Issue by HannesHasselbring** [concourse/concourse#5868]
## Summary
dynamic var interpolation in task_step file does not work in 6.3.0 but it works in 6.1.0

## Steps to reproduce
Use the following config set the secrets in secrets manger (AWS Secret Manager in our case)
ci.yml
```yaml
resources:
- name: src
  type: git
  source:
    uri: git@github.com:org/secret-interpolation-example.git
    branch: master
    private_key: ((example_interp_git_key))

jobs:
- name: secret-interpolation-example
  plan:
  - get: src
  - task: integration
    file: src/task.yml
    vars:
      text: "Hello World!"
```

task.yml
```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

run:
  path: echo
  args: ["((text))", "((myuser))"]
```

## Expected results
With 6.1.0 you get the following expected output
`Hello World! my_user_form_secrets_manager`

## Actual results
with 6.3.0 you get
`failed to interpolate task config: undefined vars: myuser`

## Additional context
According to the documentation: https://github.com/concourse/docs/blob/1b3dafd937dda235813d81f1e7d3dc72c56c1cb1/lit/docs/jobs/steps.lit#L453 this should work as in 6.1.0

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?
