### ISSUE TITLE
"harmlessly" invalid job configs cause errors on upgrading to 6.4.0-rc.1

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#5875]
## Summary

Since #5504, some JSON parsing for job plans got more strict. However it's possible that pre-6.4.0 you had stored invalid configs, so that after the upgrade, the JSON unmarshalling will refuse to parse stuff that's already there!

## Steps to reproduce

with the following files on hand:
* **docker-compose.6.3.0.yml**:
    ```yaml
    version: '3'
    
    services:
      concourse-db:
        image: postgres
        environment:
          POSTGRES_DB: concourse
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_USER: concourse_user
          PGDATA: /database
    
      concourse:
        image: concourse/concourse:6.3.0
        command: quickstart
        privileged: true
        depends_on: [concourse-db]
        ports: ["8080:8080"]
        environment:
          CONCOURSE_POSTGRES_HOST: concourse-db
          CONCOURSE_POSTGRES_USER: concourse_user
          CONCOURSE_POSTGRES_PASSWORD: concourse_pass
          CONCOURSE_POSTGRES_DATABASE: concourse
          CONCOURSE_EXTERNAL_URL: http://localhost:8080
          CONCOURSE_ADD_LOCAL_USER: test:test
          CONCOURSE_MAIN_TEAM_LOCAL_USER: test
          CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
    ```
* **docker-compose.6.4.0-rc.1.yml**:
    ```yaml
    version: '3'
    
    services:
      concourse-db:
        image: postgres
        environment:
          POSTGRES_DB: concourse
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_USER: concourse_user
          PGDATA: /database
    
      concourse:
        image: concourse/concourse-rc:6.4.0-rc.1
        command: quickstart
        privileged: true
        depends_on: [concourse-db]
        ports: ["8080:8080"]
        environment:
          CONCOURSE_POSTGRES_HOST: concourse-db
          CONCOURSE_POSTGRES_USER: concourse_user
          CONCOURSE_POSTGRES_PASSWORD: concourse_pass
          CONCOURSE_POSTGRES_DATABASE: concourse
          CONCOURSE_EXTERNAL_URL: http://localhost:8080
          CONCOURSE_ADD_LOCAL_USER: test:test
          CONCOURSE_MAIN_TEAM_LOCAL_USER: test
          CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
    ```
* **pipeline.yml**:
    ```yaml
    jobs:
    - name: hello-world
      plan:
      - task: hello-world
        inputs: [foo] # this is invalid but doesn't do anything
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}
          run:
            path: echo
            args: ["hello", "world"]
    ```

do the following:

1. `docker-compose -f docker-compose.6.3.0.yml up -d`
1. wait for web node to listen
1. download fly v6.3.0
1. `fly -t dev login -c http://localhost:8080 -u test -p test`
1. `fly -t dev set-pipeline -n -p pipeline -c pipeline.yml`
1. `docker-compose -f docker-compose.6.4.0-rc.1.yml up -d`
1. wait for web node to listen
1. `fly -t dev sync`
1. `fly -t dev get-pipeline -p pipeline`

## Expected results

```
jobs:
- name: hello-world
  plan:
  - config:
      image_resource:
        source:
          repository: busybox
        type: registry-image
      platform: linux
      run:
        args:
        - hello
        - world
        path: echo
    task: hello-world
```

## Actual results

```
error: Unexpected Response
Status: 500 Internal Server Error
Body:
```

## Additional context

reconfiguring these tainted pipelines fails too, so it's a pretty sticky problem: https://ci.concourse-ci.org/teams/main/pipelines/reconfigure-pipelines/jobs/reconfigure-pipelines/builds/233

maybe we could make the unmarshalling from the database a bit more permissive about extraneous fields? I think the `inputs:` field may be significant in this case, since it _is_ valid for step types other than `task:`.

## Triaging info

* Concourse version: 6.4.0-rc.1
* Browser (if applicable): n/a
* Did this used to work? yes
