### ISSUE TITLE
Scroll build numbers does not work on firefox: add scrollbar on hover

### ISSUE THREAD

**Issue by keymon** [concourse/concourse#588]
In the job view, when you got a lot of builds that overflow the screen, you can use the scroll wheel of the mouse to be able to scroll right to old builds.

This works on Chrome, but fails on Firefox (at least Firefox 43).  Also it can be problematic if you don't have a wheel.

I propose we add a scrollbar when hovering on the builds:

``` css
#builds:hover {          
     overflow-x: scroll;  
}                        
```

I would do a PR, but I think this is being refactor now. 

I created a greasemonkey user script to add the scrollbar bar: https://gist.github.com/keymon/c1e9232da6de12f36b22fd1ada28ff1b, simply click on "raw" to install.
