### ISSUE TITLE
fly execute is not working any longer with 6.4

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse#5888]
## Summary

with `v6.4` unable to run `fly -t ci execute` command and it fails with 

```
fly -t ci execute -c sample.yaml
uploading cencon ⠸ (128.3KiB/s)
error: 'uploading cencon' failed: Unexpected Response
Status: 413 Request Entity Too Large
Body:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
```

## Steps to reproduce

1. sample.yaml
```
---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

params:
  test: test
run:
  path: sh
  args:
  - -exc
  - |
    echo $test
```
2. fly -t ci execute -c sample.yaml and it throws an above-mentioned error

3. fly -t ci execute -c sample.yaml  --verbose even more weird it just streaming the binary file and not stopping at all.

like below,

````
�� wȌ㌀LU(�݋���IZ#e�eȴ1��F9�"���aF�o�e���
�f� q� �AB
e�L�N[�9��Ӆ�����%wR���q��9�UN��V4�CB�\�W0a�ٴ�2�~V-XB

````

## Expected results

```
executing build 5392 at https://concourse.com/builds/5392
initializing
running sh -exc echo $test

+ echo test
test
```

## Actual results

```
fly -t ci execute -c sample.yaml
uploading cencon ⠸ (128.3KiB/s)
error: 'uploading cencon' failed: Unexpected Response
Status: 413 Request Entity Too Large
Body:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
```

## Triaging info

* Concourse version: 6.4
* Browser (if applicable): All
* Did this used to work? yes
