### ISSUE TITLE
set-pipeline step allows names with slashes

### ISSUE THREAD

**Issue by abetaev** [concourse/concourse#5907]
## Summary

I was (occasionally) able to create pipeline with slash in its name when used parameter substitution for name of pipeline in `set-pipeline` step.

## Steps to reproduce

1. Define pipeline to create pipeline with parameterized name
```
    resources:

      - name: src
        type: git
        source:
          uri: <repo with pipelines>

    jobs:
      - name: set-test-pipeline
        public: true
        plan:
          - get: src
          - set_pipeline: ((parameter-with-slash))
            file: src/pipelines/test.pipeline.yml
```
2. Run `fly set-pipeline -c {filename} -p test-pipeline ... -v parameter-with-slash="this/is/ok"`

## Expected results

After running `test-pipeline` it should fail.

## Actual results

`test-pipeline` creates `this/is/ok` pipeline which does not work from UI.

## Triaging info

* Concourse version: 6.4.0
* Did this used to work? I have no idea.
