### ISSUE TITLE
SaveConfig policy check is not enforced when using set_pipeline step

### ISSUE THREAD

**Issue by cludden** [concourse/concourse#5931]
## Summary

`SaveConfig` policy check is not enforced when using `set_pipeline` step, which allows any policy enforcement of pipeline configuration to be circumvented

## Steps to reproduce

1. run OPA with policy that restricts which third-party/custom resource types can be used, for example:
  ```rego
  package concourse
  
  default allow = false
  
  # allow all actions without explicit rule mapping
  allow {
    actions != "SaveConfig"
    not actions[input.action]
  }
  
  # verify set-pipeline 
  allow {
    input.action == "SaveConfig"
    count(resource_violations) == 0
  }
  
  # extract list of custom & third party
  resource_violations[image] {
    image := input.data.resource_types[_].source.repository
    not allowed_resources[image]
  }
  
  # define list of approved custom & third-party resource images
  allowed_resources := {
    "teliaoss/github-pr-resource"
  }
  ```
2. run concourse web node with policy enforcement enabled, and using OPA backend
3. apply malicious pipeline, for example
  ```yaml
  jobs:
    - name: sync-pipeline
      plan:
        # generate new pipeline config that uses an unsupported resource type
        - task: gen-pipeline
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: ubuntu
                tag: bionic
            outputs:
              - name: pipeline
            run:
              path: /bin/bash
              args:
                - -c
                - |
                  cat <<PIPELINE > pipeline/pipeline.yml
                  jobs:
                    - name: sync-pipeline
                      plan:
                        - task: test
                          config:
                            platform: linux
                            image_resource:
                              type: docker-image
                              source:
                                repository: ubuntu
                                tag: bionic
                            outputs:
                              - name: pipeline
                            run:
                              path: /bin/bash
                              args:
                                - -c
                                - |
                                  echo "hello world"
                  resource_types:
                    - name: malicious-resource
                      type: registry-image
                      source:
                        repository: hacky/malicious-resource
                  PIPELINE
        # apply malicious pipeline
        - set_pipeline: self
          file: pipeline/pipeline.yml

  resource_types:
    # use allowed resource type when first applying pipeline
    - name: pull-request-resource
      type: registry-image
      source:
        repository: teliaoss/github-pr-resource

  ```
4. execute job that runs `set_pipeline` using a pipeline definition that includes unsupported resource_types 

## Expected results

`set_pipeline` should fail

## Actual results

`set_pipeline` succeeds and pipeline is updated with unsupported resource_type

## Triaging info

* Concourse version: 6.4.0
* Browser (if applicable): n/a
* Did this used to work? n/a
