### ISSUE TITLE
Support for modules

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#595]
We are using concourse to build and deploy about 50 microservices (the number is growing) and have found that we really need a way to compose pipelines so that each project can own it's pipelines, but make use of shared patterns. Rather than implement our own wrapper around fly for this, I want to try to create something that would be useful outside our project and that could be integrated with concourse.  

My hope is that this leads to a discussion that concludes with a practical design that can be implemented.  I have used templating syntax as proposed in #545. See also #417, this is really a concrete proposal for that issue.

So here is my proposal:
1. Modules are partial templates with an additional `vars` block, e.g.:
   
   ``` yaml
   # modules/build.yml
   vars:
     resources:
       source: git-source
       image: built-image
     job:
       name: build
     git_repo: null
     passed: []
   
   resources:
     - name: (( resources.source ))
       type: git
       source:
         repo: (( git.repo ))
   
     - name: (( resources.compiled ))
       type: s3
       ...
   
     - name: (( resources.image ))
       type: docker-image
       ...
   
   jobs:
     - name: (( job.name ))
       plan:
         - get:  git-source
           passed: (( passed ))
   
         - task: build
           file: (( resource.source ))/.ci/build.yml
   
         - put: (( resources.image ))
   ```
2. Pipelines use and configure modules by loading them in a new `modules` block:
   
   ``` yaml
   # pipeline.yml
   modules:
     - name: build
       file: ./modules/build.yml
       vars:
         passed: [ pre-check ]
         git:
           repo: git@github.com:example/example.git
   
   jobs:
     - name: pre-check
       plan:
         - get: (( build.resources.source ))
   
         - task: check
           file: (( build.resources.source ))/.ci/check.yml
   ```

Things to note:
- The `vars` block in a module defines defaults, and can be overridden in the pipeline `modules/vars` block.
- Variables can be used in the module, or in the pipeline namespaced by the name of the module (e.g.  `(( build.resources.source ))`)
- If two modules define identical jobs or resources, only one is created in the pipeline. If modules define different jobs or resources with the same name an error is raised.

As far as implementation is concerned, there are two options.
1.  Modules are an extension of the templating syntax and are resolved by fly before sending the pipeline to the ATC. In this case the syntax for importing a module should probably match the rest of the templating, e.g. something like
   
   ``` yaml
   # pipeline.yml
   (( module build 
       vars:
         ....
   ))
   ```
   
   This is not as pretty as pure yaml but would be fairly simple to implement I think.
2. Modules are a first class citizen and implemented in the ATC along with resources and jobs.  The biggest complexity with this is how the modules would be discovered. Since they sit outside the `jobs` tree and affect the structure of the pipeline, this would suggest that the ATC needs the ability to fetch resources and rebuild pipelines on the fly which doesn't sound like a good idea to me.
