### ISSUE TITLE
Rerunning a build after aliasing a `get` causes errored build page

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6010]
## Summary

Running a build whose `get` step identifier has been changed since the initial run causes an errored build page that loads forever.

## Steps to reproduce

1. Set a pipeline with a `get` step, e.g.:

```yaml
resources:
- name: asdf
  type: mock
  source:
    initial_version: abc

jobs:
- name: job
  plan:
  - get: asdf
```

2. Trigger a build
3. Re-set the pipeline, aliasing the `get`

```yaml
...
jobs:
- name: job
  plan:
  - get: asdf1234
    resource: asdf
```

4. Rerun the first build

## Expected results

Build reruns successfully

## Actual results

Build page never loads

![Screen Shot 2020-08-21 at 4 27 38 PM](https://user-images.githubusercontent.com/26583442/90931741-42fd8a80-e3cb-11ea-9ced-3c36921e1d48.png)

## Additional context

HTTP error: Failed to load resource: the server responded with a status of 404 (Not Found)

On CI, I saw the following error message:

```
{"timestamp":"2020-08-21T20:23:09.062770747Z","level":"error","source":"atc","message":"atc.scheduler.run.schedule-job.try-start-next-pending-build.failed-to-create-build-plan","data":{"build-id":2339612,"build-name":"1.1","error":"version for input postgres-image-latest not provided","job":"testflight","session":"22.28.10.1"}}
```

But for whatever reason I'm not seeing something like that locally?

## Triaging info

* Concourse version: 6.5
* Browser (if applicable):
* Did this used to work? Probably not
