### ISSUE TITLE
`fly validate-pipeline` does not allow `across` steps

### ISSUE THREAD

**Issue by flavorjones** [concourse/concourse#6026]
## Summary

#5887 introduces experimental support for an `across` step, which ATC allows when the `--enable-across-step` flag is set.

Fly's `validate-pipeline` command does not have an analogous flag, and so will always fail validation on pipelines that contain an `across` step.

## Steps to reproduce

Given this pipeline:

```yaml
resource_types:
- name: foo
  type: registry-image
  source:
    repository: foo/foo
- name: bar
  type: registry-image
  source:
    repository: bar/bar
jobs:
- name: hello-world
  plan:
  - task: say-hello
    across:
    - var: foo_version
      values: ["2.4", "2.5"]
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: ubuntu, tag: "foo-((foo))"}
      run:
        path: echo
        args: ["Hello, world!"]
```

Running `fly validate-pipeline -c path/to/pipeline.yml` will display the following error:

```
Error loading existing config:
  - invalid jobs:
	jobs.hello-world.plan.do[0].across: the across step must be explicitly opted-in to using the `--enable-across-step` flag
```

as expected!

I expect to then be able to run `fly validate-pipeline -c path/to/pipeline.yml --enable-across-step`, but this is the result:

```
error: unknown flag `enable-across-step'
```

When running `fly validate-pipeline -c path/to/pipeline.yml --enable-across-step` I expect a valid pipeline using an `across` step to be allowed.

## Additional context

I'll be submitting a PR to fix this shortly.

## Triaging info

* Concourse version: ~> 6.5.0
