### ISSUE TITLE
Unexpected group name when "n" is used as name

### ISSUE THREAD

**Issue by o-orand** [concourse/concourse#6049]
## Summary
When a group name is called "n", I expect to have "n" display as group name, not "false". 
On the screenshot below, I should have 'n' and 'ok' as group name
![image](https://user-images.githubusercontent.com/976115/92605600-36759f00-f2b2-11ea-8214-687c198c02cc.png)

## Steps to reproduce

Load the following pipeline:
```yaml
jobs:
  - name: my-job-1
groups:
  - name: n
    jobs:
      - my-job-1
  - name: ok
    jobs:
      - my-job-1
```

Here is the output when this pipeline is loaded by fly:
```
fly -t my-target set-pipeline -p group-name-display-issue -c group-name-display-issue.yml
groups:
  group false has been added:
+ jobs:
+ - my-job-1
+ name: "false"     <== This is WRONG ! It should be 'n'
  
  group ok has been added:
+ jobs:
+ - my-job-1
+ name: ok
  
jobs:
  job my-job-1 has been added:
+ name: my-job-1
+ plan: null 
```

## Triaging info

* Concourse version: 6.5.1

**Comment by chenbh** [comment]
That is a very unfortunate quirk of YAML: `n`, `false`, `No`, and `off` are all treated as Boolean false values (https://yaml.org/refcard.html).

You'll have to quote it if you want it to be treated as a string:
```
jobs:
  - name: my-job-1
groups:
  - name: "n"
    jobs:
      - my-job-1
  - name: ok
    jobs:
      - my-job-1
```
Results in the proper behaviour:
```
groups:
  group n has been added:
+ jobs:
+ - my-job-1
+ name: "n"

  group ok has been added:
+ jobs:
+ - my-job-1
+ name: ok

jobs:
  job my-job-1 has been added:
+ name: my-job-1
+ plan: null
```
