### ISSUE TITLE
Allow underscore as part of identifier schema; forbidding it is too restrictive and breaks workflows

### ISSUE THREAD

**Issue by issmirnov** [concourse/concourse#6070]
## Summary

The current [identifier schema](https://concourse-ci.org/config-basics.html#schema.identifier) is more restrictive than the prior allowed naming schemes. This breaks workflows that require folders with underscores.

## Steps to reproduce

Create any workflow that requires a folder with an underscore. At this time, it seems impossible to use such a name as an identifier.

Note that even with the `get.resource` param set to an underscore, the validation still fails due to an invalid schema.

## Expected results

Schema names should not be this restrictive. My use case is testing ansible roles, where the universal syntax is `$username.role_name`. As such, there's no easy way to test these roles without adding tons of fluff where directories are renamed.

## Actual results

```
  - jobs.ansible-role-ubuntu-desktop.plan.do[0].in_parallel.steps[3].get(issmirnov.compile_zsh): 'issmirnov.compile_zsh' is not a valid identifier: illegal character '_'
```

## Additional context

Ansible role names are incompatible with concourse naming schemas. This breaks existing workflows.

## Triaging info

* Concourse version: 6.5
* Did this used to work? Yes, in all versions prior to 6.0

## Full pipeline definition

<details><summary>pipeline.yml</summary>
<p>

```yaml
---
ansible_role_tester: &ansible_role_tester
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: issmirnov/dcind
  run:
    path: sh
    args:
      - -exc
      - |
        source /docker-lib.sh > /dev/null 2>&1
        # https://github.com/meAmidos/dcind/blob/master/docker-lib.sh#L56 # Inject registry.
        start_docker "http://docker-registry.puma" "http://docker-registry.puma" > /dev/null 2>&1

        # docker debug for caches.
        ls /var/lib/docker

        mkdir -p report # output
        export ROOT=$PWD
        cp art_bin/ansible-role-tester $ROLE
        [ -d cfssl_bin ] && cp -r cfssl_bin $ROLE/tests/
        cd $ROLE

        # iterate over all available playbooks
        for f in tests/*.yml; do
          if [ "$f" = "tests/requirements.yml" ] ;then continue; fi
          ./ansible-role-tester full -t ubuntu1804 --extra-roles $ROOT --library "$(pwd)/tests/library" --report --report-output ../report/report.json --playbook $f
          # check results
          if [[ "$(jq '.Ansible.Run.Result' ../report/report.json)" != "true" ]]; then
              echo "Run failed";
              exit 1;
          fi
          if [[ "$(jq '.Ansible.Idempotence.Result' ../report/report.json)" != "true" ]]; then
              echo "Idempotence failed";
              exit 2;
          fi
          # reset report file
          rm ../report/report.json # cleanup
        done
compile_art: &compile_art
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: golang
      tag:  1.12.1
  outputs:
    - name: art_bin
  run:
    path: sh
    args:
      - -exc
      - |
        export ROOT=$PWD
        export GOPATH=$PWD
        go get github.com/fubarhouse/ansible-role-tester
        cd src/github.com/fubarhouse/ansible-role-tester
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -ldflags '-w -extldflags "-static"'
        cp ansible-role-tester $ROOT/art_bin/
  caches:
    - path: art_bin
compile_cfssl: &compile_cfssl
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: golang
      tag:  1.12.1
  caches:
    - path: cfssl_bin
  outputs:
    - name: cfssl_bin
  run:
    path: sh
    args:
      - -exc
      - |
        export GOPATH=$PWD
        # Download and install.
        go get -u github.com/cloudflare/cfssl/cmd/...
        cp bin/cfssl* cfssl_bin/

        # sanity check.
        ./cfssl_bin/cfssl version
fail_email: &fail_email
  put: send-an-email
  params:
    subject_text: "[❌ FAILED] CI: build #${BUILD_NAME} on ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}!"
    body_text: |
      Oh no! Build #${BUILD_NAME} on ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME} failed!
      Build ID: ${BUILD_ID}
      Build Name: ${BUILD_NAME}
      Build Job Name: ${BUILD_JOB_NAME}
      Build Pipeline Name: ${BUILD_PIPELINE_NAME}
      ATC External URL: ${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}

success_email: &success_email
  put: send-an-email
  params:
    subject_text: "[✔️ PASSED] CI: build #${BUILD_NAME} on ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}."
    body_text: |
      Congrats, your commit worked.
      Build ID: ${BUILD_ID}
      Build Name: ${BUILD_NAME}
      Build Job Name: ${BUILD_JOB_NAME}
      Build Pipeline Name: ${BUILD_PIPELINE_NAME}
      ATC External URL: ${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
gitea_private_key: &gitea_private_key |
  -----BEGIN RSA PRIVATE KEY-----
  REDACTED
  -----END RSA PRIVATE KEY-----
resource_types:
  - name: email
    type: registry-image
    source:
      repository: pcfseceng/email-resource
      tag: latest

resources:
  - name: daily-timer
    type: time
    source:
      interval: 24h

# === ANSIBLE ===
  - name: ansible-role-cfssl
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: issmirnov.goss
    type: git
    source:
      uri: REDACTED
      branch: master

  - name: ansible-role-provision
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: ansible-role-server
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: ansible-role-ubuntu-desktop
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: issmirnov.zap
    type: git
    source:
      uri: https://github.com/issmirnov/ansible-role-zap.git
      branch: master


  - name: issmirnov.compile-zsh
    type: git
    source:
      uri: https://github.com/issmirnov/ansible-role-compile-zsh.git
      branch: master

  - name: issmirnov.dotfiles
    type: git
    source:
      uri: https://github.com/issmirnov/ansible-role-dotfiles.git
      branch: master

  # Explicitly define requirments, since reusing similar config for running the roles.
  # We can always go back to passing the --requirments flag to ansible-role-tester
  # FWIW, this is nice since i'll pick up breaking changes sooner.
  - name: oefenweb.swapfile
    type: git
    source:
      uri: https://github.com/Oefenweb/ansible-swapfile.git
      branch: master

  - name: jnv.unattended-upgrades
    type: git
    source:
      uri: https://github.com/jnv/ansible-role-unattended-upgrades.git
      branch: master

# === EMAIL ===
  - name: send-an-email
    type: email
    source:
      smtp:
        host: smtp.mailgun.org
        port: "587"
        username: ((username))
        password: ((password))
      from: ((from_email))
      to: [ ((my_email))]
########
# JOBS #
########
jobs:
  - name: issmirnov.compile-zsh
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-compile-zsh
          resource: issmirnov.compile-zsh
          params: {depth: 1}
          trigger: true
        - get: issmirnov.goss
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-art
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-compile-zsh
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-compile-zsh
            - name: issmirnov.goss
          outputs:
            - name: report


  - name: ansible-role-provision
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-provision
          params: {depth: 1}
          trigger: true
        - get: issmirnov.compile-zsh
          resource: issmirnov.compile_zsh
          params: {depth: 1}
          trigger: false
          passed: [issmirnov.compile-zsh]
        - get: issmirnov.goss
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-art
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-provision
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: issmirnov.compile-zsh
            - name: ansible-role-provision
            - name: issmirnov.goss

  - name: ansible-role-ubuntu-desktop
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-provision
          params: {depth: 1}
          trigger: true
          passed: [ansible-role-provision]
        - get: ansible-role-ubuntu-desktop
          params: {depth: 1}
          trigger: true
        - get: issmirnov.dotfiles
          params: {depth: 1}
          trigger: true
        - get: issmirnov.compile-zsh
          resource: issmirnov.compile-zsh
          params: {depth: 1}
          trigger: false
          passed: [ansible-role-provision]
        - get: issmirnov.goss
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-art
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-ubuntu-desktop
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: issmirnov.compile-zsh
            - name: issmirnov.dotfiles
            - name: ansible-role-provision
            - name: ansible-role-ubuntu-desktop
            - name: issmirnov.goss

  - name: ansible-role-server
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-server
          params: {depth: 1}
          trigger: true
        - get: oefenweb.swapfile
          params: {depth: 1}
          trigger: true
        - get: jnv.unattended-upgrades
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-server
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-server
            - name: oefenweb.swapfile
            - name: jnv.unattended-upgrades

  - name: issmirnov.dotfiles
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-dotfiles
          resource: issmirnov.dotfiles
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-dotfiles
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-dotfiles

  - name: issmirnov.zap
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-zap
          resource: issmirnov.zap
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-zap
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-zap

  - name: ansible-role-cfssl
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-cfssl
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: compile-cfssl-binaries
        config:
          <<: *compile_cfssl
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-cfssl
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-cfssl
            - name: cfssl_bin

```

</p>
</details>
