### ISSUE TITLE
Load test ListAllJobs watch endpoint

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6084]
## Summary

I've had #5802 sitting around for a while, but I haven't actually validated its impact on performance. Prior to merging that PR, we should run a load-test experiment with that feature enabled.

To load test, we need to simulate a lot of job activity - this could include running builds, setting/destroying pipelines, hiding/exposing pipelines, etc. (anything that could change the state of the dashboard). So, it's probably a good idea to build upon the existing drills environment setup, which already sets up a bunch of pipelines and runs builds.

One difference with the setup is that we need clients watching the `ListAllJobs` endpoint - we could start e.g. 100 open connections and measure the performance implications compared to polling every 5 seconds (as the dashboard does)

We should measure:

* Web node memory/CPU
* DB memory/CPU
* DB connections
* Network I/O between the DB/web
* Network I/O between web/clients
* Transaction time stats
  * I suspect this change will slow down fast transactions, but shouldn't have too much of an impact on already slow ones
  * I expect a "constant" (as in not scaling with the magnitude of data, but probably correlated with DB and/or ATC load) cost added to write operations - how significant that constant is has yet to be determined
  * Maybe just measure overall number of transactions per unit time?

## Context

* RFC: concourse/rfcs#61
* PR: concourse/concourse#5802

**Comment by aoldershaw** [comment]
I put in some work on this today. I set up a deployment with 3 ATCs and 10 workers (actually, I repurposed the greenpeace deployment that wasn't getting any use and scaled it up). I then set 100 pipelines using the https://github.com/concourse/drills/tree/master/longevity/algorithm-stress-tests drills setup script.

I put together an unpolished/untested [load testing tool](https://github.com/aoldershaw/loadtest) (with the incredibly creative name of `loadtest`) that is meant to simulate the dashboard by hitting the list all jobs endpoint every 5 seconds (skipping over 5s intervals if the previous request is still in flight). The load testing was run as a k8s job with concurrency 4, with each pod simulating 25 "dashboards" (for a total of 100 active "dashboards"):

<details>
<summary>Job YAML</summary>

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest
spec:
  completions: 4
  parallelism: 4
  template:
    spec:
      containers:
        - name: loadtest
          image: aoldershaw/loadtest
          args:
          - -n
          - '25'
          - -duration
          - 30m
          # uncomment for watch endpoints
          # - -headers
          # - Accept:text/event-stream
          env:
          - name: LOADTEST_ATC_URL
            value: https://ci-test.concourse-ci.org
          - name: LOADTEST_ADMIN_USERNAME
            value: admin
          - name: LOADTEST_ADMIN_PASSWORD
            value: redacted
      restartPolicy: Never
```

</details>

First, lets look at the performance with watch endpoints disabled.

Here's a quick table of approximate stats from prior to running the load test (Baseline) and during the load test (Stress):

```
		Baseline	Stress
Builds		15.8K/15min	8K/15min
Web CPU		80%		100%
Web Mem		20%		25%
Web Data RX	30MiB/s		12MiB/s
Web Data TX	7MiB/s		8MiB/s
DB Conn		120-150		120-150
DB CPU		75%		30%-60%
DB Mem		45-50%		45-50%
DB Transactions	375K/min	60K-190K/min
DB Data RX	100MiB/min	60MiB/min
DB Data TX	215MiB/min	550MiB/min
```

Notably, the web CPU for all 3 ATCs was pegged at 100%, and became a bottleneck (leading to a reduced rate of builds running, so the DB CPU decreased during the stress test). In case it's not totally obvious in these graphs 😁, the load testing started at 15:40, and lasted for 30 minutes.

Web CPU:
<img width="397" alt="web-cpu" src="https://user-images.githubusercontent.com/26583442/96309243-ec7b8980-0fd2-11eb-826d-ab05f2dc667d.png">

Build Scheduling:
<img width="801" alt="web-scheduling" src="https://user-images.githubusercontent.com/26583442/96309280-fef5c300-0fd2-11eb-9149-3d807b97d3d9.png">

DB CPU/Memory:
<img width="1185" alt="db-usage" src="https://user-images.githubusercontent.com/26583442/96309321-0fa63900-0fd3-11eb-8953-1afeeb6e1c90.png">

The DB saw a significant reduction if transaction rate, and a significant increase in network data transmitted/received:
<img width="1167" alt="db-tx-network" src="https://user-images.githubusercontent.com/26583442/96309421-382e3300-0fd3-11eb-8d8a-feac59d8d386.png">

In terms of data transmitted to the client, the `loadtest` tool monitors how much traffic each connection received. In total, 1.26GB of data was transmitted across a total of 24997 completed requests. This isn't a huge amount, but one thing to keep in mind is that the data was gzipped over the wire, and because all 100 pipelines/jobs are completely uniform (except for things like build times), it can get gzipped pretty effectively. Each response was just over 50KB - compare that to hush-house, which has a gzipped payload of just over 250KB.
