### ISSUE TITLE
Can't use quoted subkeys in var interpolation

### ISSUE THREAD

**Issue by vixus0** [concourse/concourse#6107]
## Summary

References to var subkeys that are quoted because they contain special characters are not properly unquoted, which causes lookups in var sources and secrets to fail.

## Steps to reproduce

`pipeline.yaml`:

```yaml
var_sources:
- name: dumb
  type: dummy
  config:
    vars:
      simple: hello!
      dot.pie: indeed
      wot:
        fish.egg: yup

jobs:
- name: print-creds
  plan:
  - task: print
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: alpine}

      run:
        path: ash
        args:
        - -c
        - |
          echo simple: ((dumb:simple))
          echo dot.pie: ((dumb:"dot.pie"))
          echo fish.egg: ((dumb:wot."fish.egg"))
```

```
fly sp -p test -c pipeline.yaml
fly tj -j test/print-creds -w
```

## Expected results

```
simple: hello!
dot.pie: indeed
fish.egg: yup
succeeded
```

## Actual results

```
failed to interpolate task config: missing field '"fish.egg"' in var: dumb:wot."fish.egg"
errored
```

## Additional context

Nope.

## Triaging info

* Concourse version: 6.5.1
* Did this used to work? No idea
