### ISSUE TITLE
check_every param is not working in concourse version 6.6.0. 

### ISSUE THREAD

**Issue by giva01121** [concourse/concourse#6154]
## Summary

it seems that the `check_every` param is not working in concourse version 6.6.0. I’ve just updated my concourse version and the builds are started on each minute as it is by default, but the check_every parameter is set to 30sec.

## Steps to reproduce

```
---
resources:
  - name: every-30s
    type: time
    icon: clock-outline
    source:
      interval: 30s

jobs:
  - name: job
    public: true
    plan:
      - get: every-30s
        trigger: true
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello, world!"]
```

## Expected results

The check to happen on each 30 seconds

## Actual results
![image](https://user-images.githubusercontent.com/58251102/95953162-234e7580-0e02-11eb-8dd8-29c31acdc695.png)

## Triaging info

* Concourse version: 6.6.0
* Browser (if applicable): Chrome
* Did this used to work?
yes in the previous version 5.7.0 the check was happening on each 30 seconds and a new build was started on each 30 seconds

**Comment by gid0** [comment]
Hey @giva01121, how did you define the check_every default value?
Does it work if you define the check_every at the resource level?
Like:

```
resources:
  - name: every-30s
    type: time
    icon: clock-outline
    source:
      interval: 30s
    check_every: 30s
```
