### ISSUE TITLE
'set_pipeline' and 'fly set-pipeline' produce inconsistent output when a pipeline config produces no changes

### ISSUE THREAD

**Issue by mdb** [concourse/concourse#6162]
## Summary

`set_pipeline` and `fly set-pipeline` produce inconsistent output when a pipeline config produces no changes. While `set_pipeline` prints "no diff found," `fly set-pipeline` prints "no changes to apply."

## Steps to reproduce

1. Start Concourse on http://localhost:8080:

    ```
    docker-compose up --build
    ```

2. Create a basic `pipeline.yml` file:

    ```
    ---
    resources:

    - name: gist
      type: git
      source:
        uri: https://gist.github.com/mdb/d493d79e8b10d02bb1a33f657497d3fb

    jobs:

    - name: set-pipeline
      plan:
      - get: gist
      - set_pipeline: pipeline
        file: gist/pipeline.yml
    ```

3. Download `fly` from your localhost Concourse:

    ```
    wget \
      -O fly \
      "http://localhost:8080/api/v1/cli?arch=amd64&platform=darwin"

    chmod +x fly
    ```

4. Use your downloaded `fly` to configure and unpause a `pipeline` pipeline:

    ```
    ./fly \
      --target local \
      login \
        --concourse-url http://localhost:8080 \
        --username test \
        --password test

    ./fly \
      --target local \
      set-pipeline \
        --pipeline pipeline \
        --config pipeline.yml

    ./fly \
      --target local \
      unpause-pipeline \
        --pipeline test
    ```

5. Trigger the pipeline's `set-pipeline` job; note its output reads "no diff found:"

    ```
    ./fly \
      --target local \
      trigger-job \
        --job pipeline/set-pipeline
    ```

6. Attempt to `fly set-pipeline`; note its output reads "no changes to apply:"

    ```
    ./fly \
      --target local \
      set-pipeline \
        --pipeline pipeline \
        --config pipeline.yml
    ```

## Expected results

I would expect `set_pipeline` to print "no changes to apply."

## Actual results

`set_pipeline` prints "no diff found."

## Additional context

There is some surrounding conversation between @vito and myself here:
https://github.com/concourse/concourse/pull/6116#issuecomment-709299616

## Triaging info

* Concourse version: `master` & all in which `set_pipeline` is supported
* Browser (if applicable): N/A
* Did this used to work? I don't believe so
