### ISSUE TITLE
Mishandled Resource Check API Errors Result in Builds Stuck in Pending State

### ISSUE THREAD

**Issue by benschmaus** [concourse/concourse#6210]
## Summary

After a successful resource check, a git resource configured with incorrect vault secrets can result in a resource check error that is not surfaced in the user interface.

Inspection into network traffic shows the `resources/<resource-name>/check` endpoint returning a 500 error while the UI displays a "checked successfully" message.

<img width="837" alt="success-in-ui-500-on-check-api" src="https://user-images.githubusercontent.com/102717/97029611-a8850900-152b-11eb-8bd1-b9faabba582e.png">

Checking the resource via fly shows the underlying error.  For example:

```
fly -t ci-bschmaus cr -r concourse-hacking/source-code
error: var lookup 'ghe.ccess-token': missing field 'ccess-token' in var: ghe.ccess-token
```

The same error response returned by `fly` is returned via the resource check endpoint (but it is not surfaced in the UI):

<img width="757" alt="check-api-error-message" src="https://user-images.githubusercontent.com/102717/97029883-044f9200-152c-11eb-8aeb-992aaaeb0e64.png">

Inspection into the DB shows the `check_error` column in the `resources` table is empty for the resource in question:

```
  id  |  id   |       name        |     name     | check_error
------+-------+-------------------+--------------+-------------
 3967 | 22431 | concourse-hacking | source-code  |
```

Note that when the `check_every` interval expires the error is correctly processed and displays in the UI and is captured in the `check_error` column of the `resources` table.  My team runs a large Concourse install and has a default `check_every` of 24+ hours to encourage use of webhooks.  So there appears to be some difference in how the resource checking API behaves compared with the check workflow that is used when the `check_every` interval elapses that is a factor in the error handling.

Lastly, when the resource is in this non-obvious error state, builds hang indefinitely in the pending state, which is confusing for users who manually check the resource in the UI and don't see any errors.

<img width="370" alt="build-stuck-in-pending" src="https://user-images.githubusercontent.com/102717/97030111-57294980-152c-11eb-89da-b1e54e2d4674.png">

## Steps to reproduce

The following pipeline can be used for testing:
```
jobs:
- name: a-job
  plan:
  - get: source-code
    trigger: true
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: ubuntu
        type: registry-image
      inputs:
      - name: source-code
      platform: linux
      run:
        args: [running]
        path: echo 
    task: the-task
resources:
- name: source-code
  check_every: 15m
  source:
    branch: master
    password: ((access-token))
    username: ((username))
    uri: <HTTPS_REPO_URL_GOES_HERE>
  type: git
```

1. Launch Concourse connected to a working vault credential manager
1. Set the test pipeline with `access_token` and `username` set correctly in vault
1. Navigate to `source-code` resource in UI and verify "checked successfully" message in UI
1. Typo one of the vault secrets and reset the pipeline
1. In UI, open developer tools and then click the resource check button: verify "checked successfully" message in UI, `resources/source-code/check` API call returns an HTTP 500 status with an error message that is not processed by UI and is not recorded in the `resources` table
1. Running `fly check-resource` will show the underlying error but does not result in resources table being updated with error state
1. When `check_every` expires resource will be correctly marked with the error

## Expected results

Any errors encountered when checking a resource are indicated to the user via UI and fly, and errors are properly recorded in the resources DB table.

## Actual results

An HTTP 500 response from the resource `check` API is not displayed by the UI and the `resources` table is not updated to reflect the resource error state.

## Additional context

As mentioned previously, this is likely not a significant issue for systems using the default `check_every` interval of 1 minute since the error is quickly detected via the short `check_every` setting. For larger systems with multi-hour `check_every` defaults, this issue can make resource config errors harder to identify and leads to builds not starting for non-obvious reasons. 

## Triaging info

* Concourse version: 6.4.0
* Browser (if applicable): Chrome
* Did this used to work? Not sure
