### ISSUE TITLE
Tabs not rendered correctly in web console

### ISSUE THREAD

**Issue by kurtmc** [concourse/concourse#6213]
## Summary

Many of our pipelines are not rendering indentation correctly in the log output. I think it's due to the tab characters not being rendered correctly. I believe this started happening since v6.6.0

## Steps to reproduce

Setup a pipeline that prints out tab separated characters and see that the tabs are incorrectly rendered when the job has run.
```
---
jobs:
  - name: job
    public: true
    plan:
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: ubuntu}
          run:
            path: bash
            args:
              - -c
              - |
                #!/bin/bash
                echo 1	1
                echo 2		2
                echo 3			3
                echo 4				4
                echo 5					5
```

## Expected results
```
1  1
2          2
3                  3
4                          4
5                                  5

```

## Actual results
```
1 1
2 2
3 3
4 4
5 5
```
![DeepinScreenshot_select-area_20201027105646](https://user-images.githubusercontent.com/2661907/97233058-2d7d6480-1843-11eb-9f88-9cafb77e5689.png)

## Triaging info

* Concourse version: 6.6.0
* Browser (if applicable): Firefox
* Did this used to work? Yes
