### ISSUE TITLE
upgrading in-place means garden assets fail to update

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#6236]
## Summary

The "standalone" `gdn` binary is not very good at being upgraded -- if there is a `/var/gdn/assets` folder it will simply use the binaries inside (instead of extracting its own bundled binaries), which can cause problems when the bundled `runc` has a breaking change.

### Setup

Clone https://github.com/concourse/concourse-docker and this repo in sibling folders.

Download https://github.com/concourse/concourse/releases/download/v6.5.1/concourse-6.5.1-linux-amd64.tgz and whatever the latest dev tarball is, from the `concourse-artifacts` bucket on GCP (at the time I ran these steps, it was https://storage.googleapis.com/concourse-artifacts/dev/concourse-6.6.0%2Bdev.370.e2831b5.linux-ubuntu.amd64.tgz) and place them in the `concourse-docker` folder.

Also place these two files in the `concourse-docker` folder:
**docker-compose.yml**
```yaml
version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse:6.5.1
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: jrei/systemd-ubuntu
    privileged: true
    depends_on: [web]
    volumes:
    - ./keys/worker:/concourse-keys
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - ./concourse:/usr/local/concourse
    - ./concourse-worker.service:/etc/systemd/system/concourse-worker.service
    links: [web]
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
```
**concourse-worker.service**
```systemd
[Unit]
Description=Concourse Worker

[Service]
ExecStart=/usr/local/concourse/bin/concourse worker
Type=exec
Delegate=yes
KillMode=process
Environment=CONCOURSE_WORK_DIR=/etc/work-dir
Environment=CONCOURSE_TSA_HOST=web:2222
Environment=CONCOURSE_TSA_PUBLIC_KEY=/concourse-keys/tsa_host_key.pub
Environment=CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse-keys/worker_key
Environment=CONCOURSE_BAGGAGECLAIM_DRIVER=naive
```

### Procedure
1. `tar -xzvf concourse-6.5.1-linux-amd64.tgz`
1. `docker-compose up -d`
1. `docker-compose exec worker bash -c 'apt update && apt install -y iproute2 && systemctl start concourse-worker.service'`
1. wait for the web node to be running on localhost port 8080
1. `fly -t dev login -u test -p test -c http://localhost:8080`
1. wait for the worker to appear in the output of `fly -t dev workers`
1. `rm concourse/*`
1. `tar -xzvf concourse-6.6.0+dev.370.e2831b5.linux-ubuntu.amd64.tgz` (or whatever your latest dev tarball is)
1. `docker-compose exec worker systemctl restart concourse-worker.service`
1. `fly -t dev sp -p pipeline -c ../concourse/web/wats/fixtures/smoke-pipeline.yml -n`
1. `fly -t dev up -p pipeline`
1. `fly -t dev cr -r pipeline/mockery`

## Expected results

check succeeds.

## Actual results

the dreaded `/dev/console` device cgroup error:
```
id  name     status   check_error
2   mockery  errored  run check step: run check step: find or create container: runc run: exit status 1: container_linux.go:349: starting container process caused "process_linux.go:439: container init caused \"process_linux.go:405: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"c 5:1 rwm\\\\\\\" to \\\\\\\"/sys/fs/cgroup/devices/docker/6e4a9856f98ddc409dd8f4b615d0f7f7431c0dfbf47e836cf75b231ac5f1b1d2/system.slice/concourse-worker.service/garden/303ae24e-737c-4f91-5089-4faa3a2b0d01/devices.allow\\\\\\\": write /sys/fs/cgroup/devices/docker/6e4a9856f98ddc409dd8f4b615d0f7f7431c0dfbf47e836cf75b231ac5f1b1d2/system.slice/concourse-worker.service/garden/303ae24e-737c-4f91-5089-4faa3a2b0d01/devices.allow: operation not permitted\\\"\""
```

## Additional context

This is a pretty complicated reproducible -- it's trying to be faithful to "typical" systemd deployments while still running in docker-compose for portability. It should also act as a reasonable simulation of what happens in bosh deployments. The fix _should_ be straightforward -- the concourse worker would clear the `/var/gdn/assets` folder whenever it starts, before starting the garden runner itself, so that `gdn` is forced to repopulate this directory on every startup.

Anyway I thought it was worth it to have a consistent reproduction case so we can be confident the problem has been solved.

Also - I've shown a really disastrous scenario where this failure to update assets neuters the whole worker, but a more typical scenario would be that CVE patches to runc don't actually end up getting applied (because the old `/var/gdn/assets/linux/bin/runc` gets used for the lifetime of the worker VM) and even after an upgrade, the worker is left vulnerable. 

## Triaging info

* Concourse version: all of them since we started shipping a tarball that bundled `gdn` instead of relying on operators to provide their own garden server. Maybe since v5.0.0?
* Browser (if applicable): N/A
* Did this used to work? not really, although bosh upgrades were probably smoother in the days when concourse deployments simply depended on garden-runc-release being present on the instance instead of bundling their own binary.
