### ISSUE TITLE
Cluster source defaults do not apply to fetching resource_types

### ISSUE THREAD

**Issue by daviddob** [concourse/concourse#6240]
## Summary

It looks like in https://github.com/concourse/concourse/pull/6079 when the ability was introduced to allow cluster defaults for resource types these dont apply getting custom resource types. For instance

```yaml
resource_types:
  - name: test
    type: docker-image
    source:
      repository: test/test-resource
      tag: dev
```
With the following default cluster configs
```yaml
      base_resource_type_defaults: |
        registry-image:
          registry_mirror:
            host: internal.registry.example.com
        docker-image:
          registry_mirror: https://internal.registry.example.com
```
Is ignoring the default cluster configs altogether. Its working out great for the other uses of docker-image and registry-image, however this appears to be an edge case.

## Steps to reproduce

Create an example pipeline that uses an external resource (stubbed out below - will need to be updated with a real external resource) as well as configuring some base_resource_type defaults (example for registry mirror above). Configure default parameters for the docker-image resource type - check that they are not applied when getting the custom resource type `test` 

```yaml
resource_types:
  - name: test
    type: docker-image
    source:
      repository: test/test-resource
      tag: dev

resources:
  - name: test-resource
    type: test
    source:
      example-param: example-value

jobs:
- name: test-performance
  plan:
  - get: test-resource
  - task: print-vars
    config:
      image_resource:
        source:
          repository: busybox
          tag: "latest"
        type: docker-image
      platform: linux
      run:
        path: sh
        args:
        - "-c"
        - |
          env
          ls -la
```

## Expected results

`base_resource_type_defaults` should apply to the resources regardless of where they are used (resource_types, within a task, etc) and the `test` resource type image should be pulled using the registry specified via defaults

## Actual results

`base_resource_type_defaults` appear to be ignored when pulling `resource_types`. In the example above, the registry_mirror is not used when pulling the resource_type `test` from the `test/test-resource` repo. However the image `busybox` will be pulled using the registry_mirror for the task. 

## Triaging info

* Concourse version: 6.7.1
* Browser (if applicable): Chrome/Firefox
* Did this used to work? This is related to new functionality introduced in 6.7.x

**Comment by vito** [comment]
A guess: maybe we need to update the worker image fetching code ([somewhere in here](https://github.com/concourse/concourse/blob/v6.7.1/atc/worker/image/image_resource_fetcher.go)) to apply defaults? This whole code path was removed in `master` so that might explain why this was missed when backporting the defaults.

If that is the case, it would mean we also currently don't apply defaults for task `image_resource`s either. Which would be less than ideal.

**Comment by evanchaoli** [comment]
I am pretty sure that I verified image fetching went through mirror before #6079 was merged. I'll verify it again based on current master branch.

**Comment by aoldershaw** [comment]
Tried to reproduce quickly but was unable to. Set my defaults as:

```yaml
registry-image:
  debug: true
```

and set the following pipeline:

```yaml
resource_types:
- name: type
  type: registry-image
  source:
    repository: cftoolsmiths/cron-resource

resources:
- name: resource
  type: type
  source:
    expression: "* * * * *"

jobs:
- name: job
  plan:
  - get: resource
```

I then paused the `tracker` component and triggered a build. I inspected the private build plan, and saw the following:

```json
{
  "id": "5fa0d6b1",
  "do": [
    {
      "id": "5fa0d6b0",
      "get": {
        "name": "resource",
        "type": "type",
        "resource": "resource",
        "source": {
          "expression": "* * * * *"
        },
        "version": {
          "time": "2020-11-03T04:45:40.44891399Z"
        },
        "resource_types": [
          {
            "name": "type",
            "type": "registry-image",
            "source": {
              "debug": true,
              "repository": "cftoolsmiths/cron-resource"
            },
            "version": {
              "digest": "sha256:b5dbc5d52893bc93b9adc8d01ef2bc3d6db749c8faf8b7af9faea3e3598fb6b2"
            }
          }
        ]
      }
    }
  ]
}
```

Notably, the `debug: true` is being applied to the `source`.

Not too familiar with the image fetching code, but it seems like it should use this `source` directly for fetching the image: https://github.com/concourse/concourse/blob/248606d42c177df7da97c65addd3e5955ce03bc4/atc/worker/image/image_factory.go#L62-L77

---

I also tried using the following `defaults`:

```yaml
registry-image:
  username: bogus
  password: bogus
```

...and saw resource checks failing with:

```
run check step: run check step: find or create container: fetching the image did not produce a volume
```

which I'm presuming is because the defaults were properly being applied, but since the credentials are bogus, it fails to fetch the image.

---

Let me know if you think I messed something up in my repro attempt

**Comment by evanchaoli** [comment]
I just verified on branch`master` and tag `v6.7.1`, both worked well for fetching images from mirror.

I started a local mirror, and configured the defaults as:

```yaml
registry-image:
  debug: true
  registry_mirror:
    host: 192.168.1.12:6000

docker-image:
  registry_mirror: http://192.168.1.12:6000
  insecure_registries: # declare the mirror as insecure
  - 192.168.1.12:6000
```

The pipeline code:

```yaml
- name: test
  type: docker-image
  source:
    repository: test/test-resource
    tag: dev

resources:
- name: test-resource
  type: test
  source:
    example-param: example-value

jobs:
- name: test
  public: true
  plan:
  - put: test-resource
```
As the image `test/test-resource` doesn't exist, `put` should fail:

![no-image-version](https://user-images.githubusercontent.com/18585861/97962276-c2f29880-1def-11eb-8a35-dc0a42b2f345.png)

And from my local mirror registry's log:

```
172.17.0.1 - - [03/Nov/2020:08:06:53 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "Go-http-client/1.1"
172.17.0.1 - - [03/Nov/2020:08:06:53 +0000] "GET /v2/test/test-resource/manifests/dev HTTP/1.1" 404 93 "" "Go-http-client/1.1"
time="2020-11-03T08:06:56.4954742Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="unknown tag=dev" err.message="manifest unknown" go.version=go1.11.2 http.request.host="192.168.1.12:6000" http.request.id=90eade8a-695c-4565-95ed-6aa6f37964a7 http.request.method=GET http.request.remoteaddr="172.17.0.1:46364" http.request.uri="/v2/test/test-resource/manifests/dev" http.request.useragent="Go-http-client/1.1" http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.9107208s http.response.status=404 http.response.written=93 vars.name="test/test-resource" vars.reference=dev
```

which proves that the pull went through the mirror.
