### ISSUE TITLE
Volumes can't be reused multiple times

### ISSUE THREAD

**Issue by qvistgaard** [concourse/concourse#6283]
## Summary
To sum up the problem, I believe that the issue #5799 is still haunting a bit.

## Steps to reproduce
I'm using Concourse 6.7.1 using docker-compose, with this configuration:
```yaml
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_LOG_LEVEL: debug
```

Using the following pipeline: https://gist.github.com/qvistgaard/906ee68e3d51a24b1e783d4fec54ddcf

## Expected results
Pipeline to finish without errors

## Actual results
Task `add-file-to-previous-output-5` fails with the message `failed to create volume`. 

## Additional context
Upon further investigation the host dmesg show the message ` overlayfs: maximum fs stacking depth exceeded`
Possible workaround is to change `CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER` to `naive`

## Triaging info
* Concourse version: 6.7.1
