### ISSUE TITLE
[6.4.1] Global resources - issue with tags for resource_type docker image

### ISSUE THREAD

**Issue by xeivieni** [concourse/concourse#6284]
## Summary

When using global resources it seems that my custom resource types are shared using a wrong tag

## Steps to reproduce
1. Enable global resources
2. Set multiple pipelines using the same resource type : 
```
  - name: kubernetes
    type: docker-image
    source:
      repository: <some repository url>
      check_every: 60m
      tag: 1.0.0
      username: ((docker.username))
      password: ((docker.password))
```
3. Get the digest of the resource 
`fly -t target curl /api/v1/teams/target/pipelines/my-pipeline/resource-types | jq -c '.[] | select(.name == "kubernetes") | .version.digest'`
You shall see the digest of the image configured
4. Update the resource type image tag:
```
  - name: kubernetes
    type: docker-image
    source:
      repository: <some repository url>
      check_every: 60m
      tag: 1.0.1
      username: ((docker.username))
      password: ((docker.password))
```
5. Repeat step 3

## Expected results
The digest returned shall match the updated tag. 

## Actual results

Digest is unchanged, pointing to the old docker image tag, even if the pipeline has since been triggerred.
I tried to force a check-resource-type on a specific pipeline, which did work for this pipeline but did not change the digest on the other resource

## Additional context

We never had this issue before enabling global resources. 

If I misunderstood the feature, forgive me for my mistake.

## Triaging info

* Concourse version: 6.4.1
* Browser (if applicable): All
* Did this used to work? don't know

**Comment by taylorsilva** [comment]
Clarifying the global resources feature: if multiple resources share the exact same `source` config then instead of creating a container per pipeline concourse will create one container that is shared across pipelines and teams.

Global resource OFF: two pipelines with the same resource definition results in two containers
Global resource ON: two pipelines with the same resource definition results in one container

---

I wasn't able to reproduce this with the latest code on `master`.

I made a pipeline:
```yaml
resource_types:
- name: newgit
  type: registry-image
  check_every: 30s
  source:
    repository: concourse/git-resource
    tag: latest

resources:
- name: git-repo
  type: newgit
  check_every: 60m
  source:
    uri: https://github.com/concourse/git-resource.git

jobs:
- name: job1
  plan:
    - get: git-repo
```
and set it twice on a concourse with global resources enabled (`CONCOURSE_ENABLE_GLOBAL_RESOURCES`).
```
fly -t dev sp -p test -c pipe.yml
fly -t dev sp -p test2 -c pipe.yml
fly -t dev up -p test
fly -t dev up -p test2
```
I curled the endpoint you specified and got the same digest for both:
```
$ fly -t dev curl /api/v1/teams/main/pipelines/test/resource-types | jq -c '.[] | select(.name == "newgit") | .version.digest'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   232  100   232    0     0  12210      0 --:--:-- --:--:-- --:--:-- 12210
"sha256:c25ef432d9dbbf1a81f01678b8ad1686130fffc62e54aadbd854616069457636"

$ fly -t dev curl /api/v1/teams/main/pipelines/test2/resource-types | jq -c '.[] | select(.name == "newgit") | .version.digest'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   232  100   232    0     0  12210      0 --:--:-- --:--:-- --:--:-- 12210
"sha256:c25ef432d9dbbf1a81f01678b8ad1686130fffc62e54aadbd854616069457636"
```

I then changed the tag for the `test` pipeline to `latest`. I left `test2` unchanged.
```
$ fly -t dev sp -p test -c pipe.yml
resource types:
  resource type newgit has changed:
  check_every: 60m
  name: newgit
  source:
    repository: concourse/git-resource
-   tag: dev
+   tag: latest
  type: registry-image

apply configuration? [yN]: y
configuration updated
```

I had to wait a while but eventually the new digest was returned for the pipeline I changed:
```
fly -t dev curl /api/v1/teams/main/pipelines/test/resource-types | jq -c '.[] | select(.name == "newgit") | .version.digest'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   238  100   238    0     0  18307      0 --:--:-- --:--:-- --:--:-- 18307
"sha256:1b9991aaf501daf4ccdd76cd09e872e5ecff68e50b3b973c94b4dcb716136d13"
```

test2 continued to return the digest for `dev`.
