### ISSUE TITLE
Windows workers on CI unreachable

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6301]
## Summary

_Note: This is blocking the release pipeline and is a blocker on `6.7.2`._

BOSH windows workers are currently unreachable - https://ci.concourse-ci.org/teams/main/pipelines/release-6.7.x/jobs/unit/builds/33

On the worker logs we see the following:
```
{"timestamp":"2020-11-18T17:11:01.260343600Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.failed-to-connect-to-tsa","data":{"error":"dial tcp 34.69.51.78:2222: i/o timeout","session":"4.1"}}
{"timestamp":"2020-11-18T17:11:01.260343600Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.dial.failed-to-connect-to-any-tsa","data":{"error":"all worker SSH gateways unreachable","session":"4.1.5"}}
{"timestamp":"2020-11-18T17:11:01.260343600Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.failed-to-dial","data":{"error":"all worker SSH gateways unreachable","session":"4.1"}}
{"timestamp":"2020-11-18T17:11:01.260343600Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.exited-with-error","data":{"error":"all worker SSH gateways unreachable","session":"4.1"}}
{"timestamp":"2020-11-18T17:11:01.260343600Z","level":"error","source":"worker","message":"worker.beacon-runner.failed","data":{"error":"all worker SSH gateways unreachable","session":"4"}}
```

We have checked that the authorized worker keys on the atc match those on the worker, and that the correct tsa_host_key is being used.

Deploying a Linux worker also gives the same error logs as above. This likely means it's a BOSH networking issue.

Connections timeout when we try to ping any outside network, e.g. `google.ca` from the worker.

## Steps to reproduce

Deploy Concourse 6.7.1 regularly on the team's BOSH director.

```
bosh -e prod deploy -d concourse-hsbc-debug concourse.yml \
      -l ../versions.yml \
        --vars-store cluster-creds.yml \
        -o operations/basic-auth.yml \
        --var local_user.username=admin \
        --var local_user.password=admin \
        --var external_url=http://127.0.0.1:8080 \
    --var network_name=web \
        --var web_vm_type=web \
        --var db_vm_type=database \
        --var db_persistent_disk_type=small \
        --var worker_vm_type=worker \
        --var deployment_name=concourse-hsbc-debug \
        --var azs=[z1]
```

Setup SSH port forwarding to access the web node.

```
bosh -e prod -d concourse-network-debug ssh web/0 --opts ' -L 8080:localhost:8080'
```

 Set up a pipeline with a git resource.
https://github.com/concourse/examples/blob/master/pipelines/git-triggered.yml

```
---
resources:
  - name: concourse-docs-git
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/docs

jobs:
  - name: job
    public: true
    plan:
      - get: concourse-docs-git
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: concourse-docs-git
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
            args: ["-la", "./concourse-docs-git"]
```

Unpause the pipeline and run the job.

## Expected results

Pipeline should succeed.

## Actual results

Resource checking fails with the following:
```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/concourse/docs/': Failed to connect to github.com port 443: Connection timed out
```

## Additional context

The BOSH director certificates had expired a day before this issue started happening. The certificates have been rotated but the issue persists.
