### ISSUE TITLE
Cannot use group authentication for BitBucket Cloud

### ISSUE THREAD

**Issue by cyberox** [concourse/concourse#6419]
## Summary

We can no longer login using group based authentication. The user authentication is working.

## Steps to reproduce

```
roles:
- name: owner
  local:
    users: ["admin"]
- name: member
  bitbucket-cloud:
    users: ["cyberox"]
    teams: ["developers"]
```

## Expected results

I can login, and see the pipelines, using a member in the developers group.

## Actual results

The user cyberox can see the correct pipelines, the users in the developers group cannot.

## Additional context

The `/teams` endopoint has been deprecated, and is fixed upstreamm by: https://github.com/dexidp/dex/pull/1812
According to the documentation, it requires a new config parameter `includeTeamGroups: true` (https://dexidp.io/docs/connectors/bitbucketcloud/)

## Triaging info

* Concourse version: 6.7.3
* Did this used to work? Yes
