### ISSUE TITLE
check for docker_image resource fails when using k8s secrets

### ISSUE THREAD

**Issue by Anonymous-Coward** [concourse/concourse#6452]
## Summary

This happens with concourse running on kubernetes, deployed using the newest helm chart for concourse. Therefore it cannot be reproduced easily locally.

When a pipeline uses a docker_image resource from a private repository that requires authentication, and the username and password are hard-coded into the pipeline, the check for the resource succeeds. When the username and password are replaced by secrets, using ((...)), the check fails - an error message about incorrect authentication is received from the docker repository.

## Steps to reproduce

In order for this to work you must have an image in a private docker repository which requires authentication and accepts username + password authentication.

1. Create a k8s secret in the team's k8s namespace, with two keys: `username` and `password`, corresponding to the credentials for your repository
1. Create a pipeline containing a resource of type docker_image and a job to fetch it:
```
resources:
  - name: some-image
    type: docker-image
    source:
      password: ((k8s-secret.repository-password))
      repository: repo.host/path/image-name
      username: ((k8s-secret.repository-username))
jobs:
  - name: fetch-resource
    plan:
    - get: some-image
```
 
## Expected results
The pipeline succeeds

## Actual results
The pipeline fails with an error message from the docker repository - the particular contents of the message are specific to the repository.

## Additional context
If the pipeline above is re-applied without secret references, i.e. by replacing the secret references with the actual values, the pipeline starts working.

## Triaging info

* Concourse version: v6.5.1
* Browser (if applicable): n.a.
* Did this used to work? yes
