### ISSUE TITLE
ATC crash caused by in parallel load_var

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#6454]
## Summary

Just found a few crashes on our prod cluster:

```
fatal error: concurrent map writes

goroutine 553279287 [running]:
runtime.throw(0x2e19692, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc003ba1988 sp=0xc003ba1958 pc=0xecdef2
runtime.mapassign_faststr(0x2bcb5a0, 0xc016427710, 0xc01b13f4d0, 0xe, 0xc003ba1ac8)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc003ba19f0 sp=0xc003ba1988 pc=0xeaae71
github.com/concourse/concourse/vars.(*BuildVariables).AddLocalVar(...)
	/tmp/build/8cf986d9/concourse/vars/build_vars.go:61
github.com/concourse/concourse/atc/exec.(*LoadVarStep).run(0xc00308c800, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0x0, 0x0)
	/tmp/build/8cf986d9/concourse/atc/exec/load_var_step.go:108 +0x666 fp=0xc003ba1b20 sp=0xc003ba19f0 pc=0x1857586
github.com/concourse/concourse/atc/exec.(*LoadVarStep).Run(0xc00308c800, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0x1, 0xc00ce64d68)
	/tmp/build/8cf986d9/concourse/atc/exec/load_var_step.go:78 +0x438 fp=0xc003ba1d00 sp=0xc003ba1b20 pc=0x1856e38
github.com/concourse/concourse/atc/exec.LogErrorStep.Run(0x3848940, 0xc00308c800, 0x7f769c342790, 0xc01a98cd80, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0x2c88601, 0x38a9780)
	/tmp/build/8cf986d9/concourse/atc/exec/log_error_step.go:34 +0xe4 fp=0xc003ba1d88 sp=0xc003ba1d00 pc=0x1858784
github.com/concourse/concourse/atc/exec.(*LogErrorStep).Run(0xc0183ff440, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0xc00ce64e01, 0xea4050)
	<autogenerated>:1 +0x8a fp=0xc003ba1de8 sp=0xc003ba1d88 pc=0x18675ea
github.com/concourse/concourse/atc/exec.RetryErrorStep.Run(0x3852340, 0xc0183ff440, 0x7f769c3427b0, 0xc01a98cd80, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0xc00fbaa301, 0xc00fbaa480)
	/tmp/build/8cf986d9/concourse/atc/exec/retry_error_step.go:43 +0xf3 fp=0xc003ba1e90 sp=0xc003ba1de8 pc=0x185baf3
github.com/concourse/concourse/atc/exec.(*RetryErrorStep).Run(0xc0183ff460, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0x280447a, 0x3893a00)
	<autogenerated>:1 +0x8a fp=0xc003ba1ef0 sp=0xc003ba1e90 pc=0x1867aca
github.com/concourse/concourse/atc/exec.InParallelStep.Run.func1(0xc01444acc0, 0xc0055965b0, 0x3852480, 0xc0183ff460, 0x3893940, 0xc0058451c0, 0x3876f00, 0xc004bfd220, 0xc00740f800, 0x6, ...)
	/tmp/build/8cf986d9/concourse/atc/exec/in_parallel.go:73 +0xbd fp=0xc003ba1f70 sp=0xc003ba1ef0 pc=0x1866cbd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc003ba1f78 sp=0xc003ba1f70 pc=0xf072e1
created by github.com/concourse/concourse/atc/exec.InParallelStep.Run
	/tmp/build/8cf986d9/concourse/atc/exec/in_parallel.go:60 +0x266
```

## Steps to reproduce

I can reproduce the crash with the following pipeline:

```yaml
resources:
- name: resource
  type: mock
  source:
    create_files:
      task.yml:
        a: b

jobs:
- name: test
  max_in_flight: 100
  plan:
  - get: resource
  - in_parallel:
    - load_var: v1
      file: resource/task.yml
    - load_var: v2
      file: resource/task.yml
    - load_var: v3
      file: resource/task.yml
    - load_var: v4
      file: resource/task.yml
    - load_var: v5
      file: resource/task.yml
    - load_var: v6
      file: resource/task.yml
    - load_var: v7
      file: resource/task.yml
    - load_var: v8
      file: resource/task.yml
    - load_var: v9
      file: resource/task.yml
    - load_var: v10
      file: resource/task.yml
    - load_var: v11
      file: resource/task.yml
    - load_var: v12
      file: resource/task.yml
    - load_var: v13
      file: resource/task.yml
    - load_var: v14
      file: resource/task.yml
    - load_var: v15
      file: resource/task.yml
    - load_var: v16
      file: resource/task.yml
    - load_var: v17
      file: resource/task.yml
    - load_var: v18
      file: resource/task.yml
    - load_var: v19
      file: resource/task.yml
    - load_var: v20
      file: resource/task.yml
    - load_var: v21
      file: resource/task.yml
    - load_var: v22
      file: resource/task.yml
    - load_var: v23
      file: resource/task.yml
    - load_var: v24
      file: resource/task.yml
    - load_var: v25
      file: resource/task.yml
    - load_var: v26
      file: resource/task.yml
    - load_var: v27
      file: resource/task.yml
    - load_var: v28
      file: resource/task.yml
    - load_var: v29
      file: resource/task.yml
    - load_var: v30
      file: resource/task.yml
    - load_var: v31
      file: resource/task.yml
    - load_var: v32
      file: resource/task.yml
    - load_var: v33
      file: resource/task.yml
    - load_var: v34
      file: resource/task.yml
    - load_var: v35
      file: resource/task.yml
    - load_var: v36
      file: resource/task.yml
    - load_var: v37
      file: resource/task.yml
    - load_var: v38
      file: resource/task.yml
    - load_var: v39
      file: resource/task.yml
    - load_var: v40
      file: resource/task.yml
    - load_var: v41
      file: resource/task.yml
    - load_var: v42
      file: resource/task.yml
    - load_var: v43
      file: resource/task.yml
    - load_var: v44
      file: resource/task.yml
    - load_var: v45
      file: resource/task.yml
    - load_var: v46
      file: resource/task.yml
    - load_var: v47
      file: resource/task.yml
    - load_var: v48
      file: resource/task.yml
    - load_var: v49
      file: resource/task.yml
    - load_var: v50
      file: resource/task.yml
```

After I manually quickly created hundreds builds, let a lot of builds run in parallel, ATC crashed.

## Expected results

ATC should never crash.

## Actual results

Crashed a few times.

## Triaging info

* Concourse version: 6.7.3 (maybe previous versions also have the bug)
* Browser (if applicable): NA
* Did this used to work? NA
