### ISSUE TITLE
Getting the same resource twice with different passed constraints never finds satisfactory inputs

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#652]
If I have a pipeline with one build at the beginning (stage 1), ten builds at stage 2, and one build at stage 3, where a resource must pass stage 1 before getting to stage 2, and must pass all of stage 2 before getting to stage 3, the stage 3 build will never start due to waiting for a suitable set of inputs if I have misconfigured stage 3 to request the resource twice, once for passing stage 1 and once for passing all of stage 2:

```
- name: build-step-3
  plan:
  - aggregate:
    - get: my-resource
      passed: [build-step-1]
      tags: [my-architecture]
    - get: my-resource
      passed:
      - build-step-2a
      - build-step-2b
      - build-step-2c
      - build-step-2d
      - build-step-2e
      - build-step-2f
      - build-step-2g
      - build-step-2h
      - build-step-2i
      - build-step-2j
      tags: [my-architecture]
```

I would expect this to either be rejected (or is it acceptable to get the same resource twice?), or to actually begin the build.
