### ISSUE TITLE
Escaping ((vars)) syntax

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#6530]
## Summary

Concourse will always attempt to evaluate any `((vars))` it sees in a pipeline, sometimes I actually want to keep the literal value instead.

This is particularly useful in the `set_pipeline` step where I might want to remap secret names.

## Steps to reproduce

```yaml
resources:
- name: mock
  type: mock
  source:
    create_files:
      pipeline.yml:
        jobs:
        - name: foo
          plan:
          - task: foo
            config:
              platform: linux
              image_resource:
                type: mock
                source: { mirror_self: true }
              run:
                path: echo
                args: [ ((foo)) ]

jobs:
- name: foo
  plan:
    - get: mock
    - set_pipeline: p2
      file: foo/pipeline.yml
      vars:
        foo: ((((bar))))
```

## Expected results

The `set_pipeline` step template results in `args: [ ((bar)) ]` and when I trigger `p2/foo`, it fetches the `bar` secret from my cred manager.

## Actual results

The `set_pipeline` step template results in `args: [ ((secret-value)) ]`
