### ISSUE TITLE
No way to add tagged worker to the default worker pool

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6565]
## Summary

Currently there is no way to add workers to the default pool from the worker cli.

The issue at hand:

I have quite a few containers and resources which are both being used on tagged workers and un-tagged workers as well.

The tasks either have a `tag: framework:cuda` or are untagged.

The result is that the containers are unavailable to the the tagged task on the tagged worker.

In the images `lemonaid` is a tagged worker with `framework:cuda`, `framework:opencl`, `lemonaid`.
`orangecestswirl` is a untagged worker.

![image](https://user-images.githubusercontent.com/667047/108822300-2da62a80-75bf-11eb-83c6-ec891d3c163c.png)
![image](https://user-images.githubusercontent.com/667047/108822337-3ac31980-75bf-11eb-97c4-99ece01b9387.png)

For my case, the tagged workers are rather boring instances, which just have a couple of special futures, but should also be considered for regular, untagged tasks.

## Steps to reproduce

```
- name: container-fedora-cuda
  type: registry-image

  tags: [framework:cuda]
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-cuda
    username: ((username))
    password: ((password))
- name: container-fedora-default
  type: registry-image

  tags: [framework:opencl,framework:cuda]
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-default
    username: ((username))
    password: ((password))

- name: container-fedora-native
  type: registry-image

  tags: []
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-native
    username: ((username))
    password: ((password))

  - name: pr-test-juice
    build_logs_to_retain: 4
    public: true
    serial: true
    plan:
    - get: pr-juice
      trigger: true
      version: every
    - get: container-fedora-cuda
      trigger: true

    - get: container-fedora-default
      trigger: true

    - get: container-fedora-native
      trigger: true

jobs:
    - put: pr-juice-stat
      resource: pr-juice
      get_params:
        skip_download: true
      params:
        path: pr-juice
        base_context: sirmergealot
        context: greenlit
        status: pending
    - in_parallel:

        limit: 1
        fail_fast: false
        steps:
        - task: pr-coaster-test-fedora-cuda
          image: container-fedora-cuda

          tags: [framework:cuda]

          config:
            platform: linux
            inputs:
            - name: pr-juice
            caches:
            - path: cargo_home
            - path: pr-juice/coaster/target
            run:
              path: sh
              args:
              - -exc
              - |
                # two levels up is the cache
                export CARGO_HOME=$(realpath "$(pwd)/../../cargo_home")
                echo "Sweet (cached) home is \"$CARGO_HOME\""
                # export RUST_LOG=coaster=warn,rcublas=debug,rcublas-sys=debug
                mkdir -p $CARGO_HOME
                prepare
                cargo-override-injection
                export RUST_LOG=juice=debug
                export RUST_BACKTRACE=1
                cargo test --no-default-features --features=native,cuda -- --nocapture
              dir: pr-juice/coaster
          on_failure:
            put: pr-juice-stat
            resource: pr-juice
            get_params:
              skip_download: true
            params:
              path: pr-juice
              base_context: sirmergealot
              context: coaster-test-fedora-cuda
              status: failure
          on_success:
            put: pr-juice-stat
            resource: pr-juice
            get_params:
              skip_download: true
            params:
              path: pr-juice
              base_context: sirmergealot
              context: coaster-test-fedora-cuda
              status: success

```
https://ci.spearow.io/teams/spearow/pipelines/juice/resources/container-fedora-cuda

## Expected results

Resources are available.

## Actual results

Resource is not available on the tagged worker.

## Additional context

The whole situation could be solved by adding a cli flag, that allows adding the worker to the default pool as well, since the machine really has special features, but should be used for normal tasks as well.

## Triaging info

* Concourse version: 6.7.2
* Browser (if applicable): firefox 85.0.1 (64-bit)
* Did this used to work? Yes
