### ISSUE TITLE
Streaming behaviour and work selection do not conform to the document behaviour

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6581]
## Summary

It is unclear and not consistent with what - to my best understanding of `tags` [1](https://concourse-ci.org/jobs.html#schema.step.tags) [2](https://concourse-ci.org/resources.html#schema.resource.tags) - should be happening.

In the following image you can see that the large~ish (3-5gb) containers are polled on worker `orangecestswirl`, which is a _untagged_ worker.
`lemonaid` is tagged with `framework:cuda` and `framework:opencl`.

Now in the image below one can see, that the checking is not done on `lemonaid`, but on other workers.

Currently the container _creation_ task runs on an _untagged_ worker  / `lemonaid`.

This has a couple of side effects:

* I assume the volumes are now streamed between workers, this is not a good behaviour since creation frequency is commonly a lot lower than consumption frequency.
*  Delayed builds, with no information #6575 

![image](https://user-images.githubusercontent.com/667047/109035083-9200e100-76c8-11eb-9a95-cad8d7128b59.png)

## Steps to reproduce

Reduced yaml:
```yaml
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource


resources:
- name: pr-juice
  type: pull-request
  check_every: 10m
  source:
    repository: spearow/juice
    access_token: ((sirmergealot-github-token))
- name: juice
  type: git
  source:
    branch: master
    uri: https://github.com/spearow/juice.git



- name: container-fedora-cuda
  type: registry-image

  tags: [framework:cuda]
  # privileged: true # FIXME this must be replaced with some proper selinux rules
  source:
    repository: quay.io/spearow/machine-learning-container-fedora-cuda

jobs:
    - in_parallel:

        limit: 1
        fail_fast: false
        steps:
        - task: pr-coaster-test-fedora-cuda
          image: container-fedora-cuda

          tags: [framework:cuda]
          # privileged: true # FIXME this must be replaced with some proper selinux rules

          config:
            platform: linux
            inputs:
            - name: pr-juice
            caches:
            - path: cargo_home
            - path: pr-juice/coaster/target
            run:
              path: sh
              args:
              - -exc
              - |
                # two levels up is the cache
                export CARGO_HOME=$(realpath "$(pwd)/../../cargo_home")
                echo "Sweet (cached) home is \"$CARGO_HOME\""
                # export RUST_LOG=coaster=warn,rcublas=debug,rcublas-sys=debug
                mkdir -p $CARGO_HOME
                prepare
                cargo-override-injection
                export RUST_LOG=juice=debug
                export RUST_BACKTRACE=1
                cargo test --no-default-features --features=native,cuda -- --nocapture
              dir: pr-juice/coaster
          on_failure:
            put: pr-juice-stat
            resource: pr-juice
            get_params:
              skip_download: true
            params:
              path: pr-juice
              base_context: sirmergealot
              context: coaster-test-fedora-cuda
              status: failure
          on_success:
            put: pr-juice-stat
            resource: pr-juice
            get_params:
              skip_download: true
            params:
              path: pr-juice
              base_context: sirmergealot
              context: coaster-test-fedora-cuda
              status: success

        - task: pr-coaster-blas-test-fedora-cuda
          image: container-fedora-cuda

          tags: [framework:cuda]
          # privileged: true # FIXME this must be replaced with some proper selinux rules

          config:
            platform: linux
            inputs:
            - name: pr-juice
            caches:
            - path: cargo_home
            - path: pr-juice/coaster-blas/target
            run:
              path: sh
              args:
              - -exc
              - |
                # two levels up is the cache
                export CARGO_HOME=$(realpath "$(pwd)/../../cargo_home")
                echo "Sweet (cached) home is \"$CARGO_HOME\""
                # export RUST_LOG=coaster=warn,rcublas=debug,rcublas-sys=debug
                mkdir -p $CARGO_HOME
                prepare
                cargo-override-injection
                export RUST_LOG=juice=debug
                export RUST_BACKTRACE=1
                cargo test --no-default-features --features=native,cuda -- --nocapture
              dir: pr-juice/coaster-blas
          on_failure:
            put: pr-juice-stat
            resource: pr-juice
            get_params:
              skip_download: true
            params:
              path: pr-juice
              base_context: sirmergealot
              context: coaster-blas-test-fedora-cuda
              status: failure
          on_success:
            put: pr-juice-stat
            resource: pr-juice
            get_params:
              skip_download: true
            params:
              path: pr-juice
              base_context: sirmergealot
              context: coaster-blas-test-fedora-cuda
              status: success
```

More complete example as currently running at https://ci.spearow.io/teams/spearow/pipelines/juice/jobs/test-juice/builds/197

https://gist.github.com/drahnr/aafa988ebe7e8c839de0d5f8f6715144

## Expected results

Instant error or execution of the task.

## Actual results

6 hour stalling

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): firefox
* Did this used to work? not sure, I used tags on and off
