### ISSUE TITLE
"check_every: never" breaks checking for custom resource_type resources

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#6582]
## Summary

When setting `check_every: never` on a resource who's type is defined in the `resource_types` section of the pipeline, checking will fail with the following on the web:
```json
{
  "level": "error",
  "source": "atc",
  "message": "atc.check-resource.failed-to-create-check",
  "data": {
    "error": "resource type 'static' has no version",
    "resource": "static-custom-resource-type",
    "session": "331"
  }
}
```

## Steps to reproduce

Set this pipeline and try to check the `static-custom-resource-type` resource. No error will appear in the web UI.
```yaml
resource_types:
- name: static
  type: registry-image
  source: { repository: ktchen14/static-resource }

resources:
- name: static-custom-resource-type
  check_every: never
  type: static
  source:
    foo: bar
- name: time-default-resource
  check_every: never
  type: time
  source:
    interval: 5s

jobs:
- name: job
  plan:
  - in_parallel:
    - get: static-custom-resource-type
    - get: time-default-resource
```
## Expected results

Check is successful.

## Actual results

Check is not successful. No error is shown in the web UI.

## Additional context

Triggering the job does not get around the issue either. The same error is found in the web logs:
```json
{
  "timestamp": "2021-02-24T19:37:13.380332800Z",
  "level": "error",
  "source": "atc",
  "message": "atc.create-job-build.failed-to-create-check",
  "data": {
    "error": "resource type 'static' has no version",
    "session": "1113"
  }
}
```

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): n/a
* Did this used to work? Probably not since it's a new feature
