### ISSUE TITLE
Switching to containerd results in TLS handshake timeout

### ISSUE THREAD

**Issue by Aqualie** [concourse/concourse#6599]
## Summary

Switching from guardian to containerd results in get registry-image-resource requests showing an error
`ERRO[0010] download failed: initialize transport: Get "https://replaced.com/v2/": net/http: TLS handshake timeout 
`

## Steps to reproduce

- name: node-image
  type: registry-image-git
  icon: docker
  source:
    repository: replaced.com/node/node
    username: {{user}}
    password: {{pw}}

jobs:
- name: build-and-push
  plan:
  - get: node-image
    trigger: true
    params:
      format: oci

## Triaging info

* Concourse version: 7.0.0 
* Browser (if applicable):
* Did this used to work? When using guardian runtime yes

**Comment by mkocus** [comment]
It seems that we've got essentaily the same issues with using containerd. Some examples:
```
run check: image fetching failed
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:47914->[::1]:53: read: connection refused
```
also for some reasons bitbucket also denies connection (works on garden runtime):
```
selected worker: b39cc50dd4e7
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
```
We are running worker with latest containerd and concourse 7.0.0

Right now we cannot use containerd for production.

**Comment by jghiloni** [comment]
Can confirm this is also occuring with Concourse 7.0 as deployed with helm chart 14.6.1, and can further confirm that reverting to garden solves the problem.

**Comment by vito** [comment]
Hmm, could this be explained by Guardian config not being converted to the containerd equivalent? Would y'all mind sharing what settings you have for your workers?

**Comment by jghiloni** [comment]
env vars:

```
CONCOURSE_BAGGAGECLAIM_BIND_IP=127.0.0.1
CONCOURSE_BAGGAGECLAIM_BIND_PORT=7788
CONCOURSE_BAGGAGECLAIM_BTRFS_BIN=btrfs
CONCOURSE_BAGGAGECLAIM_DEBUG_BIND_IP=127.0.0.1
CONCOURSE_BAGGAGECLAIM_DEBUG_BIND_PORT=7787
CONCOURSE_BAGGAGECLAIM_DRIVER=overlay
CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=info
CONCOURSE_BAGGAGECLAIM_MKFS_BIN=mkfs.btrfs
CONCOURSE_BAGGAGECLAIM_OVERLAYS_DIR=/concourse-work-dir
CONCOURSE_BIND_IP=127.0.0.1
CONCOURSE_BIND_PORT=7777
CONCOURSE_CONNECTION_DRAIN_TIMEOUT=1h
CONCOURSE_CONTAINER_SWEEPER_MAX_IN_FLIGHT=5
CONCOURSE_DEBUG_BIND_IP=127.0.0.1
CONCOURSE_DEBUG_BIND_PORT=7776
CONCOURSE_GARDEN_DNS_PROXY_ENABLE=true
CONCOURSE_HEALTHCHECK_BIND_IP=0.0.0.0
CONCOURSE_HEALTHCHECK_BIND_PORT=8888
CONCOURSE_HEALTHCHECK_TIMEOUT=5s
CONCOURSE_LOG_LEVEL=info
CONCOURSE_RUNTIME=containerd
CONCOURSE_SWEEP_INTERVAL=30s
CONCOURSE_TSA_HOST=concourse-web-worker-gateway:2222
CONCOURSE_TSA_PUBLIC_KEY=/concourse-keys/host_key.pub
CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse-keys/worker_key
CONCOURSE_VOLUME_SWEEPER_MAX_IN_FLIGHT=5
CONCOURSE_WEB_PORT=tcp://10.99.184.97:8080
CONCOURSE_WEB_PORT_8080_TCP=tcp://10.99.184.97:8080
CONCOURSE_WEB_PORT_8080_TCP_ADDR=10.99.184.97
CONCOURSE_WEB_PORT_8080_TCP_PORT=8080
CONCOURSE_WEB_PORT_8080_TCP_PROTO=tcp
CONCOURSE_WEB_PROMETHEUS_PORT=tcp://10.107.179.195:9391
CONCOURSE_WEB_PROMETHEUS_PORT_9391_TCP=tcp://10.107.179.195:9391
CONCOURSE_WEB_PROMETHEUS_PORT_9391_TCP_ADDR=10.107.179.195
CONCOURSE_WEB_PROMETHEUS_PORT_9391_TCP_PORT=9391
CONCOURSE_WEB_PROMETHEUS_PORT_9391_TCP_PROTO=tcp
CONCOURSE_WEB_PROMETHEUS_SERVICE_HOST=10.107.179.195
CONCOURSE_WEB_PROMETHEUS_SERVICE_PORT=9391
CONCOURSE_WEB_PROMETHEUS_SERVICE_PORT_PROMETHEUS=9391
CONCOURSE_WEB_SERVICE_HOST=10.99.184.97
CONCOURSE_WEB_SERVICE_PORT=8080
CONCOURSE_WEB_SERVICE_PORT_ATC=8080
CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE=true
CONCOURSE_WORKER_WORK_DIR=/worker-state
CONCOURSE_WORK_DIR=/concourse-work-dir
```

helm settings:
```
concourse:
  ...
  worker:
    shutdownSignal: SIGUSR2
    connectionDrainTimeout: 1h
    healthcheckBindIp: 0.0.0.0
    healthcheckBindPort: 8888
    healthcheckTimeout: 5s
    debugBindIp: 127.0.0.1
    debugBindPort: 7776
    workDir: /concourse-work-dir
    bindIp: 127.0.0.1
    bindPort: 7777
    sweepInterval: 30s
    logLevel: info
    containerSweeperMaxInFlight: 5
    volumeSweeperMaxInFlight: 5
    runtime: containerd

    baggageclaim:
      logLevel: info
      bindIp: 127.0.0.1
      bindPort: 7788
      debugBindIp: 127.0.0.1
      debugBindPort: 7787
      driver: overlay
      overlaysDir: /concourse-work-dir
      reapInterval: 10s
```

**Comment by vito** [comment]
Hmm, this part jumps out:

```sh
CONCOURSE_GARDEN_DNS_PROXY_ENABLE=true
```

I don't see that being set in your helm values though. It looks like it's actually set in our `Dockerfile`, but we don't set the containerd equivalent:

https://github.com/concourse/concourse-docker/blob/f658ed7523e7faaffff8e81422f19ca6038cd490/Dockerfile#L10-L12

You can try setting `concourse.worker.garden.dnsProxyEnable` to `true` in your helm settings. The env var to look for is this one:

```sh
CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE=true
```

If that fixes it we should consider setting the containerd value in the `Dockerfile` too just so the transition is easier. /cc @muntac

**Comment by jghiloni** [comment]
Already tried that, no go :(

**Comment by vito** [comment]
Oops, sorry, I said the wrong helm value: it's `concourse.worker.containerd.dnsProxyEnable`. But maybe that's what you actually tried. :)

**Comment by jghiloni** [comment]
yeah, definitely tried that one and not the garden one 😬

**Comment by mkocus** [comment]
Well, I've tried with absolutely minimal docker-compose config that works with garden:
```
version: '3'
services:
  concourse-worker:
    restart: always
    image: concourse/concourse:7.0.0
    command: worker
    privileged: true                            # needed to be able to create docker in docker
    volumes:
      - /opt/concourse/:/opt/concourse/
    environment:
      CONCOURSE_TSA_HOST: somehost.com:2222
      CONCOURSE_TSA_PUBLIC_KEY: /opt/concourse/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /opt/concourse/worker_key
      CONCOURSE_RUNTIME: containerd
```
But it don't work with containerd. Our test worker is behind firewall, so it may be some issue with that there - but I didn't have enough time to check on which level connections to dockerhub/bb fails.
