### ISSUE TITLE
mysql daemon fails to start when using containerd

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6609]
## Summary

A particular workload on Hush House [fails](https://hush-house.pivotal.io/teams/cf-uaa-pivotal-only/pipelines/v74-5-x-lts/jobs/unit-tests-mysql/builds/45 ) with:

```
Could not create unix socket lock file /var/run/mysqld/mysqld.sock.lock
```

The user noted that `/var/run/mysqld` does not exist on the container before the task script runs, and that the failure is probably due to the missing directory.

The image being used for the task is https://hub.docker.com/r/cfidentity/uaa-mysql. When they run the image using Docker or on an external worker (that presumably isn't using containerd) the task runs fine.

This possibly has something to do with the way we're setting up mounts in containerd.

## Triaging info

* Concourse version: 7.0
* Runtime: containerd
* Browser (if applicable):
* Did this used to work? Yes

**Comment by muntac** [comment]
@chenbh noted:
```
here’s a use case for getting rid of that /run mount. In this image, /var/run is symlinked to /run, which happened to be overwritten by our mount. Got it working by recompiling the worker
```

**Comment by taylorsilva** [comment]
We validated that this was fixed after https://github.com/concourse/concourse/pull/6592 was merged in.

Our test pipeline. We had to look through the logs for the socket error.
```yaml
jobs:
- name: test
  plan:
  - task: mysql
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: cfidentity/uaa-mysql
      params:
        MYSQL_DATABASE: uaa
        MYSQL_ROOT_HOST: 127.0.0.1
        MYSQL_ROOT_PASSWORD: changeme
      run:
        path: bash
        args: ["/entrypoint.sh","mysqld"]
```
