### ISSUE TITLE
long periods of no output + worker rebalancing causes containerd containers to exit

### ISSUE THREAD

**Issue by gaigaslab-operations** [concourse/concourse#6632]
## Summary

We are running tanzu bbr and om processes in concourse that take a long time with no output.  Specifically, when the bbr validate process runs on a 500+GB blobstore OR a stemcell upgrade in an environment with many instances of on-demand redsi/rabbitmq.  The errand 'upgrade-all-service-instances' in the redis/rabbitmq update does not provide any output until all the service instances are updated.

When we migrated from 6.7.2 to 7.0.0 and enabled our workers to use runtime containerd instead of garden, we experienced the task being killed after 1 hour of output inactivity with the following message:

```
Backend error: Exit status: 500, message: {"Type":"","Message":"load proc: process does not exist task: not found: unknown","Handle":"","ProcessID":"","Binary":""}
```

When we switch back to garden, these problems go away

We could not find any settings to control this behavior, although we did try:
containerd.request_timeout: 24h
(this is a BOSH deployment of Concourse)

## Steps to reproduce

Run bbr or om on a process that goes over 1h without output

## Expected results
Task completes if the command completes

## Actual results
Task is terminated with:
```
Backend error: Exit status: 500, message: {"Type":"","Message":"load proc: process does not exist task: not found: unknown","Handle":"","ProcessID":"","Binary":""}
```

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): N/A
* Did this used to work? Yes - using garden runtime and it still does with garden runtime

**Comment by gaigaslab-operations** [comment]
I was able to reproduce this behavior - but it took longer than 1 hour - almost 2 hours:

```
jobs:
- name: sleeptest
  plan:
  - task: sleeptest
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bash
          tag: latest
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo Starting
          touch inputfile
          date
          yes > /dev/null
          date

```
