### ISSUE TITLE
load_var/var_source variable interpolation is not respected by --check-creds

### ISSUE THREAD

**Issue by andy-paine** [concourse/concourse#6636]
## Summary
When trying to set a pipeline with variables interpolated from `load_var` variables using the `--check-creds` flag, it complains about `undefined vars` even though those vars will be known at runtime.

## Steps to reproduce
Try setting the following pipeline with `--check-creds`
```yaml
jobs:
- name: check-creds-sad-panda
  plan:
  - task: write_var
    config: &config
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      outputs:
      - name: var
      run:
        path: ash
        args:
        - -c
        - |
          echo "bar" > var/foo
  - load_var: foo
    file: var/foo
    format: trim
  - task: use_var
    config:
      <<: *config
      run:
        path: echo
        args:
        - ((.:foo))
```

## Expected results
`fly set-pipeline --check-creds` succeeds

## Actual results
`fly set-pipeline --check-creds` fails with
> `failed to interpolate task config: undefined vars: .:foo`

## Additional context
I guess this is probably because `--check-creds` is just looking for all placeholders and making sure either the global secrets manager or `fly set-pipeline --var/--load-vars-from` provide them.

This also happens with `var_source`:
```yaml
var_sources:
- name: my-dummy
  type: dummy
  config:
    vars:
      foo: bar

jobs:
- name: check-creds-sad-panda
  plan:
  - task: write_var
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      outputs:
      - name: var
      run:
        path: echo
        args:
        - ((my-dummy:foo))
```
> `failed to interpolate task config: undefined vars: my-dummy:foo`

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): N/A
* Did this used to work? Probably not but haven't tested
