### ISSUE TITLE
All workers busy when using container placement strategy limit-active-tasks in 7.0.0

### ISSUE THREAD

**Issue by mkocus** [concourse/concourse#6648]
## Summary
We are running a concourse environment with 1 web node and 3 workers using a web docker-compose config, which limits max running task per container to 1. One of the workers is using a tag to limit tasks that can be run on it.
```
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: limit-active-tasks
      CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER: 1
```
We are experiencing an issue that didn't appear before updating to version 7.0.0 - workers can randomly become busy with some unknown tasks (nothing visible on a web UI), and no other job can be started:
```
All workers are busy at the moment, please stand-by.
```
This can happen on any worker. In particular, when it does happen on the one that uses a tag, it causes all jobs that require that tag to starve on the message shown above.
We have checked that required workers are indeed online (state: running).
```
fly -t ci workers
name                 containers  platform  tags  team  state    version  age
26a773549c67         46          linux     none  none  running  2.3      9d
Jans-Mac-mini.local  0           darwin    jan   none  running  2.3      7d
f0e17b5530aa         39          linux     none  none  running  2.3      10d
```
We have also checked using `fly -t ci builds` that there are no other blocking jobs. Only a single item, which is not a "check" resource is being shown:
```
1379786  some-project/some-step/114  started    2021-03-08@17:24:57+0100  n/a                       7m27s+    main  user
```
## Steps to reproduce
Run 1 web node, 1 worker node, use the limit-active-tasks and 1 task per worker. After some time the worker becomes locked, and nothing can be runned on it. Restarting the web node and/or the worker node does not help.
## Expected results
When there is no job running on the given worker, it should be possible to run a job on it, using limit-active-tasks and 1 task per worker.
## Actual results
Web node says that `All workers are busy at the moment, please stand-by.`, and no job can be run on the given worker.
## Additional context
We are using garden, because containerd caused issues described in https://github.com/concourse/concourse/issues/6613.
## Triaging info
* Concourse version: 7.0.0
* Browser (if applicable): N/A
* Did this used to work? Yes, has been working on all previous 6.x.x versions

**Comment by mkocus** [comment]
Also, it is worth adding that changing a name of the problematic worker node clears the busy status and allows running task on them (at least, temporary).

**Comment by taylorsilva** [comment]
Hard to see how this could happen randomly since there's only one place where this code path is called; when a task is running:
https://github.com/concourse/concourse/blob/16dce5d776dc04f9d8af8cfc8a972ebce7cf51af/atc/engine/task_delegate.go#L141-L148

In the web logs, do you see the error `failed-to-increase-active-tasks` after this behaviour starts occurring? Maybe it's writing to the db successfully but failing on `RowsAffected()`?
https://github.com/concourse/concourse/blob/16dce5d776dc04f9d8af8cfc8a972ebce7cf51af/atc/db/worker.go#L388-L408

If you run `fly containers` and filter for the worker that you think has zero tasks, do you see any tasks containers on there? That may help you debug where this random task is coming from.

**Comment by mkocus** [comment]
Thanks for the investigation lead - we had to change the worker name as a workaround, because it had blocked our production work. I have turned on the logging and will check that when in occurs again.

**Comment by cwsatpolymath** [comment]
I've experienced the issue as well.  `fly containers` shows that the workers are saturated with `check` containers.  I think this is a side effect of checks running as builds in 7.0 and the scheduler treating them the same as task containers.   We currently are using a different (less efficient for our use case) container placement strategy.  I'll see if I can reproduce and check the logs for `failed-to-increase-active-tasks` events.

**Comment by x3nb63** [comment]
can confirm this: just upgraded to 7 yesterday and here it is. Its also set up with placement stratefy of `limit-active-tasks` and a limit of 1.

in a cluster of 5 linux nodes + 2 windows nodes, two jobs block on above message while NO other job is visibly running.

inspecting with `fly builds` and `fly containers` show lots of checks present and in started state,

cluster was working for a day, however.

may it come from the ratio if checks to nodes?

there are 123 containers right now, of which 105 are checks - only the 5 linux nodes appear doing the checks.

**Comment by x3nb63** [comment]
> may it come from the ratio of checks to nodes?

yep, bumped up the workers to 7 and removed/paused some pipelines and jobs start running again.

that's a workaround, however, for us its essential to run exactly 1 job per node for testing kernel drivers. I also cant tell people: no you cant add your pipeline right now, cause we lack nodes ...

**Comment by x3nb63** [comment]
one more thing:

my 2 windows workers do not take on any job. Both sit idle and `fly workers` lists them with 0 containers and running state.

however, all windows jobs say _"All workers are busy at the moment, please stand-by."_

don't know how to get them building again.

**Comment by odormond** [comment]
The issue is still present in 7.1.0.
I've experimented a bit and having a task error instead of fail prevent any further execution on the corresponding worker (tested with both Linux with containerd  and Windows).
I tried shortening the `--gc-failed-grace-period` to `10m` instead of the default of `120h` but that didn't make any difference.

**Comment by odormond** [comment]
I confirm it can be reproduced at will with a simple task that error.
My test setup has an single atc, one Linux worker and one Windows worker with `--container-placement-strategy limit-active-tasks --max-active-tasks-per-worker 1`. And here's my test pipeline:
```yaml
---
resources:
- name: tmux.git
  type: git
  source:
    uri: https://github.com/tmux/tmux.git
    branch: master

jobs:
- name: build
  plan:
  - get: tmux.git
    trigger: false

  - in_parallel:
    - task: build-linux
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: {repository: ubuntu}
        inputs:
          - name: tmux.git
        run:
          path: baboush
          args:
            - "-c"
            - |
              sleep $(($RANDOM / 500 + 30))
              exit 1
    - task: build-windows
      tags: [vs2019]
      config:
        platform: windows
        inputs:
          - name: tmux.git
        run:
          path: powershell
          args:
            - "-command"
            - |
              Start-Sleep -Seconds (Get-Random -Minimum 30 -Maximum 90);
              exit 1
```

The `build-linux` task will error due to a "typo" in the `task.config.run.path`: `baboush` instead of `bash`.

Here is the worker's log where you can see the task error at 08:14:39: [worker.log](https://github.com/concourse/concourse/files/6162071/worker.log)

And the web/atc logs: [web.log](https://github.com/concourse/concourse/files/6162048/web.log)

At 08:16:22, another job is started (from another pipeline but retriggering the same job gives the same result).
At 08:16:37, you can see the atc complain the worker is busy.

Note that the worker can still do check and get operations but tasks are blocked.

I will try to reproduce it with debug logs enabled during the day.
