### ISSUE TITLE
Resources that are trigger: true and version: every still miss versions

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse#666]
We're still seeing this problem from issue #563 on v2.1.0.

Multiple copies of a job finish close together, the following job in the sequence is skipping over one of the resource versions.

Does not happen all the time and we don't have a reproduction case.

Pipeline config is pretty straight forward, something like this:

```
- name: first-job
  plan:
  - get: resource1
    passed: [something-previous]
    trigger: true
    version: every
- name: second-job
  plan:
  - get: resource1
    passed: [first-job]
    trigger: true
    version: every
```

We'll see multiple copies of first-job finish, but then only a single second-job start using the latest version of resource1 and skipping over the previous version.
