### ISSUE TITLE
Using cache_tag: latest with a dynamic image tag causes builds to fail

### ISSUE THREAD

**Issue by imsky** [concourse/concourse#679]
Given this build plan:

``` yaml
- name: build-backend
  plan:
  - get: git
    trigger: true
  - put: docker-backend
    params:
      build: git
      tag: git/commit
      cache: true
      cache_tag: latest
```

where `git/commit` contains the SHA of the current Git commit, builds start failing due to trying to look up a "phantom" digest (seems related to buildcache). This means dynamically-tagged images are impossible to build from cache.

**Comment by imsky** [comment]
@macb it is the official docker image resource's git repo (master), but i believe it breaks with the default one as well (caching doesn't work there anyway)

**Comment by databus23** [comment]
Have you tried setting `tag_as_latest: true`. I think the caching only works if you publishing to the value of `cache_tag’ as well.

**Comment by imsky** [comment]
it works with the latest tag _only_. when i want to build tag `xyz` using `latest` as the cache source, it fails.

**Comment by databus23** [comment]
@imsky: The caching needs a fixed tag (`cache_tag`) it pulls to fill the cache. That means every build also has to publish your new image to that `cache_tag`. This is what `tag_as_latest: true` achieves (if you are using `cache_tag: latest`). By adding `tag_as_latest: true` to your above resource definition it should  work.

This is how we are using it (with `build/` being an output of a previous task):
```yaml
- put: our.image
  params:
    tag_as_latest: true
    cache: true
    cache_tag: latest
    build: build
    tag: build/tag
```

Using other tags then `latest` as the `cache_tag` is a but cumbersome atm as the resource does not provide a way to publish to another fixed tag then `latest`.
