### ISSUE TITLE
Unclear generic "file not found" error when passing in invalid task image formats

### ISSUE THREAD

**Issue by Krenair** [concourse/concourse#6803]
## Summary

As mentioned in https://github.com/vito/oci-build-task/pull/59 we were trying to use oci-build-task without UNPACK_ROOTFS (oops) and then use the image immediately in the next step.
This resulted in a generic "file not found" error. This was especially confusing as our task had a `file` attribute to get its config, which definitely existed.

## Steps to reproduce

* Make a job with a single step to use oci-build-task to produce an image
* For the next step try to run a task using that image

## Expected results

A more helpful error message, maybe saying what file precisely was missing, or complaining about image format, or something.

## Actual results

<img width="1171" alt="Screenshot 2021-04-01 at 10 52 43" src="https://user-images.githubusercontent.com/826662/113277231-69c45d80-92d8-11eb-8d1c-962d65d434c4.png">

## Triaging info

* Concourse version: 6.7.4
* Browser (if applicable): n/a
* Did this used to work? unknown

**Comment by taylorsilva** [comment]
Simple pipeline to reproduce the issue:
```yaml
resources:
- name: alpine
  type: registry-image
  source:
    repository: alpine

jobs:
  - name: simple-job
    plan:
      - get: alpine
        params:
          format: oci
      - task: simple-task
        image: alpine
        config:
          platform: linux
          run:
            path: echo
            args: ['Hello, world!']
```

Results in: 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/4583837/123829147-30e45680-d8d0-11eb-857c-0e2b4a372e93.png">
