### ISSUE TITLE
containerd: Images with nonexistent UID fail to run

### ISSUE THREAD

**Issue by vixus0** [concourse/concourse#6836]
## Summary

Images with nonexistent UIDs don't run with the containerd runtime, and result in errors like the following:
```
backend error: Exit status: 500, message: {"Type":"","Message":"user '65532' not found: no matching entries in /etc/passwd","Handle":"","ProcessID":"","Binary":""}
```

## Steps to reproduce

Using the following task config, run `fly execute`:
```
platform: linux
image_resource:
  type: registry-image
  source:
    repository: bitnami/kubectl
    tag: 1.20.4
run:
  path: kubectl
  args:
    - version
```

## Expected results

Concourse runs the task.

## Actual results

Task errors with:
```
backend error: Exit status: 500, message: {"Type":"","Message":"user '1001' not found: no matching entries in /etc/passwd","Handle":"","ProcessID":"","Binary":""}
```

## Additional context

Certain images set a UID, for example with the `USER` Dockerfile directive to a value that isn't present in `/etc/passwd`. Other images don't have an `/etc/passwd` at all (the [distroless](https://github.com/GoogleContainerTools/distroless) images for example).

I believe this commit is relevant: concourse/concourse@ac548408ddf8f7f0777eed85b78bca75f2875aab

## Triaging info

* Concourse version: 7.1.0 (containerd runtime)
* Browser (if applicable):
* Did this used to work? Under the guardian runtime, yes.
