### ISSUE TITLE
set_pipeline step does not unarchive pipelines where there is no diff

### ISSUE THREAD

**Issue by PFacheris** [concourse/concourse#6843]
## Summary

My team makes use of the set_pipeline step within a "manager" pipeline to set release and PR pipelines based on the result of a templating process. There was recently a case where the release pipeline was accidentally archived and we expected the job that sets it to unarchive it.

The result looked fine:
![image](https://user-images.githubusercontent.com/1783057/114083043-859da580-987c-11eb-9195-1572501d593e.png)

But the target pipeline was still archived, we expected it to not be archived as this would be consistent with the fly behavior.

## Steps to reproduce

Create the following pipeline and manually trigger it to set the booklit pipeline:
manager.yaml
```
resources:
- name: booklit
  type: git
  source: {uri: https://github.com/vito/booklit}
jobs:
- name: reconfigure
  plan:
  - get: booklit
  - set_pipeline: booklit
    file: booklit/ci/pipeline.yml
```

Run:
```
fly archive-pipeline -p booklit
```

Manually trigger the manager pipeline.

## Expected results
I would expect the booklit pipeline to no longer be archived to be consistent with fly.

## Actual results
The booklit pipeline is still archived.

## Triaging info

* Concourse version: 6.7.4
* Browser (if applicable):
* Did this used to work? Not sure, first time trying it.
