### ISSUE TITLE
Not enough docs on overlapping input/outputs, expand the documentation with an example.

### ISSUE THREAD

**Issue by jamie-pate** [concourse/concourse#6881]
## Summary

While getting started with concourse I had difficulty getting a pipeline which shared artifacts with multiple tasks. I eventually found the PR for `Permit overlapping inputs, outputs, and task caches #1799` which added only a small callout to document the feature.

## Steps to reproduce

Start over as a new user, and try to integrate caches and overlapping task input/output artifacts without understanding the internal details! ;)

Everything seems to work as I expect in this simple example, I guess it could be added as an example with a link to/from https://concourse-ci.org/tasks.html#task-environment callout about same input/output dir. (and a warning about caches :D)
```yaml
# Explore this:
# https://concourse-ci.org/tasks.html#task-environment
# you can configure an input and output with the same path.
# The directory will be populated by the input,
# and any changes made to the directory will propagate downstream as an output.
---
x: &platform-image
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: alpine }
jobs:
- name: job
  public: true
  plan:
  - task: init
    # generate an artifact from thin air!
    output_mapping:
      src: src-content
    config:
      # be careful with caches since their contents will not be there in the next task!
      caches:
      - path: src/cache
      outputs:
      - name: src
      <<: *platform-image
      run:
        path: sh
        args:
          - -c
          - |
            echo "---
            platform: linux
            image_resource:
                type: registry-image
                source: { repository: alpine }
            # input and output with the same name/path works just fine.
            inputs:
            - name: src
            outputs:
            - name: src
            run:
                path: sh
                args: [-c, 'echo contents > src/file2.txt']
            " > src/task.yml;
            chmod +x src/task.yml;
            cat src/task.yml
            set -x
            cat src/cache/cachedfile.txt || true
            date > src/cache/cachedfile.txt
            cat src/cache/cachedfile.txt
  - task: prep
    # input and output mapping can refer to the same name, but you probably don't want to
    # replace your initial e.g pr resource if you need to report status back to it later...
    input_mapping:
      src: src-content
    output_mapping:
      src: src-content
    file:
      src-content/task.yml
  - task: test
    # test the results of this pipeline, here we just print out the contents as an example.
    # note that anything in the cache dir from the 'prep' step has *not* been added to the src-content artifact
    input_mapping:
      src: src-content
    config:
      inputs:
      - name: src
      <<: *platform-image
      run:
        # cache will be empty here, but everything else should be present.
        path: find
```
## Expected results

This feature should be more thoroughly documented

## Actual results

Documentation is limited to a single callout with limited info.

## Additional context

https://github.com/concourse/concourse/issues/1799

## Triaging info

* Concourse version: v7.1.0
* Browser (if applicable): Chromium Version 89.0.4389.114
* Did this used to work?
