### ISSUE TITLE
Vault credential search hard-fails if the first attempted location is not a kv store

### ISSUE THREAD

**Issue by kberzinch** [concourse/concourse#6896]
## Summary

I use a few different non-kv secrets engines with Vault + Concourse, and it seems that the changes to support kv v2 secrets engines prevents usage with anything but kv secrets engines that are mounted at _each_ location that Concourse would search.

## Steps to reproduce

Start up a Vault server, and mount a `kv` secrets engine only at a team-specific path.

```sh
$ vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=roottoken
# in a different terminal
$ vault secrets enable -version=2 -path=concourse/main/ kv
```

Start up Concourse, and configure it to check a shared location first.

```sh
$ wget https://concourse-ci.org/docker-compose.yml

$ cat << "EOF" >> docker-compose.yml

      CONCOURSE_VAULT_URL: http://youriphere:8200
      CONCOURSE_VAULT_SHARED_PATH: shared
      CONCOURSE_VAULT_CLIENT_TOKEN: roottoken
EOF

$ docker-compose up
```

Run some task that needs a secret.

```yaml
# task.yml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu

params:
  SOME_PARAM: ((some-value))

run:
  path: irrelevant
```

## Expected results

Task fails because the secret does not exist.

## Actual results

Concourse does not check the actual configured `kv` store because `concourse/shared` is not a `kv` store.

```
$ fly execute --target local --config task.yml 
executing build 2 at http://localhost:8080/builds/2
failed to interpolate task config: Error making API request.

URL: GET http://192.168.1.179:8200/v1/sys/internal/ui/mounts/concourse/shared/some-value
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "concourse/shared/some-value/"
errored
```

## Additional context

If I put nginx in front of Vault and configure it to return a 404 for that endpoint instead of a 403 then Concourse will search other paths.

This is a super simple example but hopefully it shows my problem. My real deployment has three different engines mounted at five different locations and I have the lookup templates configured to check all of the engines in locations that make sense for each one.

## Triaging info

* Concourse version: 7.2.0
* Vault version: 1.7.0
* Browser (if applicable): Not applicable
* Did this used to work? Yes, in 6.7.5 at the oldest

**Comment by xtremerui** [comment]
Hi, I think the logic related to your issue is in here
https://github.com/concourse/concourse/blob/34474b0f0cd5b6a46639b517e4b38d3d4250f6e7/atc/creds/vault/vault_kvhelpers.go#L15-L29

As you can see, it indeed depends on if the response is a 404 to decide if it gonna try next path. The preflight intends to decide if the path a v2 path. So in your case, if you config the client plicies grant access as the error described, concourse would be able to read concourse/shared/ and find out the secret `some-value` doesn't exist. Then the response would be a 404.

**Comment by kberzinch** [comment]
It is not a client policy issue. The reproduction steps I posted in the original issue use a root token, which has permission to do everything.

I do think it is a little odd that Vault returns a 403 in this case, not sure if it makes more sense to file as a bug on their end instead.

**Comment by xtremerui** [comment]
This function is a direct copy from a vault helper function 
https://github.com/hashicorp/vault/blob/4b790d2c42f406a980230c196eeeb5b9b52a7cf1/command/kv_helpers.go#L44

So I'd assume returning 403 is not expected. I am not very familiar with vault about the root token access grant, if it is suppose to be able to read that secret then yes seeking help from vault is a better option.

**Comment by kberzinch** [comment]
There is a similar issue open regarding the Vault agent (first party client), I'll go poke there https://github.com/hashicorp/vault/issues/11156

**Comment by kberzinch** [comment]
This is intended behavior on the Vault side: https://github.com/hashicorp/vault/issues/11434#issuecomment-825872984

It seems that Concourse should treat a 403 from that endpoint in the same way as a 404. I'm a little fuzzy on the intricacies of the Vault integration but from working with it as a user for a little while now I don't _think_ that should break anything. The `sys/internal/ui/mounts/` endpoint will return a proper response if the token has access to the real mount endpoint, and otherwise falling back to kv v1 behavior should be fine.

**Comment by dmytro-zhernosiekov-rft** [comment]
hi @xtremerui @scottietremendous @vito @kberzinch  I have the same issue. Could you please advice is it exactly this one or I need to open another ticket. 

On 6.7.2 I had GitHub shared engine. We have Teams, defined in Concourse, for example let's take 123456. So engine is created in Vault as: `https://vault/ui/vault/secrets/concourse/shared/github/` 

In pipeline named **regression** and configured as:
```
var_sources:
- name: vault
  type: vault
  config:
    url: https://vault
    path_prefix: /concourse
    shared_path: shared
    client_token: ((auth-token))

resources:
- name: docs
  type: git
  source:
    uri: https://github.com/docs.git
    branch: master
    username: x-access-token
    password: ((vault:github/token/access.token)) # shared github token

jobs:
- name: build-docs
  plan:
  - get: docs-git
    trigger: true
  - task: build-docs-container
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      caches:
      - path: cache
      inputs:
      - name: docs-git
      outputs:
      - name: image
      params:
        CONTEXT: docs-git
      run:
        path: build
```
On 6.7.2 version there were no issues with this code and image were built as expected. 
But after upgrade to 7.2 I see next error:

```
resource config creds evaluation: Error making API request.

URL: GET https://vault/v1/sys/internal/ui/mounts/concourse/123456/regression/github/token/access
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "concourse/123456/regression/github/token/access/"
```
This happened just after upgrade on our test env.

Also according to Vault lookup policies (/concourse/(team name)/(pipeline name)/foo) should it try this path `/concourse/123456/github` or only `/concourse/123456/regression/foo` ? 

Is this same issue described in this ticket?
