### ISSUE TITLE
containerd: Runtime tries to mount/switch to invalid directory after upgrading to 7.2

### ISSUE THREAD

**Issue by holgerstolzenberg** [concourse/concourse#6900]
## Summary
We upgraded to Concourse 7.2.0 last wednesday. Initially everything looked good and the beginning.
On the first run after the update, ALL of our deploy jobs suddenly failed without any change to it.
The tasks that failed all use the same image below, which is also unchanged.

```
backend error: Exit status: 500, message: {"Type":"","Message":"proc start: OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: chdir to cwd (\"/tmp/build/13257d10/pull-request\") set in config.json failed: no such file or directory: unknown","Handle":"","ProcessID":"","Binary":""}
```

<img width="2540" alt="Screenshot 2021-04-16 at 12 21 59" src="https://user-images.githubusercontent.com/282736/115223364-0033b400-a10c-11eb-969d-43abfc2f381d.png">

I initially though it might be related to our pipelines, but could not find anything special.
Then I thought that it might be related to the Docker Engine version, but verified that the last update of Docker had been done in February.

So I tried it on a fresh pipeline and it also failed. If you look at the offending error message you can see that Concourse tries to 
somehow mount `/tmp/build/13257d10/pull-request` but the offending directory is not part the given jobs at all.

So as a last line of defense I tried to switch back to `guardian` runtime et voila, things worked again. Please note that containerd runtime worked like a charm for us with 7.1.

## Steps to reproduce
Run the given job from a Concourse installation:

**Builder image**
```Dockerfile
FROM python:3.9.0-slim

ARG yq_version="v4.6.2"

# Labels ommitted

RUN apt-get update && \
    apt-get install --yes wget jq ssh && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    pip install awxkit && \
    wget "https://github.com/mikefarah/yq/releases/download/$yq_version/yq_linux_amd64" -O /usr/bin/yq && \
    chmod +x /usr/bin/yq

ENTRYPOINT ["/bin/bash"]
```

**Pipeline job**
```yaml
- name: "deploy-latest-cs"
  build_log_retention:
    <<: *log_retention
  serial: true
  plan:
    - in_parallel:
      - get: artifactory-docker-image
        trigger: true
        passed: [master-build]
      - get: build-meta-data
      - get: pipeline
    - task: awx-trigger-deploy-latest
      file: "pipeline/ci/tasks/deploy-latest.yml"
      vars:
        artifact_id: ((artifact_id))
        artifactory_user: ((concourse_user))
        artifactory_password: ((concourse_password))
        awx_cli_version: ((awx_cli_version))
        awx_host: ((awx_host))
        awx_worklow_job_template_name: ((awx_worklow_job_template_name))
        concourse_application_client_id: ((concourse_application_client_id))
        concourse_application_client_secret: ((concourse_application_client_secret))
        concourse_ci_lab_user: ((concourse_ci_lab_user))
        concourse_ci_lab_user_private_key: ((concourse_ci_lab_user_private_key))
        concourse_ci_lab_password: ((concourse_ci_lab_password))
        docker_registry: ((docker_registry))
        okd_cluster: ((okd_cluster))
        rollout_environment: latest
        rollout_side: client
  on_failure: *email-notification
```

**Task file**
```yaml
platform: linux

inputs:
  - name: build-meta-data

image_resource:
  type: docker-image
  source:
    repository: ((docker_registry))/awx-cli
    tag: ((awx_cli_version))
    username: ((artifactory_user))
    password: ((artifactory_password))

# we use the AWX CLI default env variable names to have to specify them with each cli command
params:
  ARTIFACT: ((artifact_id))
  CLIENT_ID: ((concourse_application_client_id))
  CLIENT_SECRET: ((concourse_application_client_secret))
  CLUSTER: ((okd_cluster))
  ENVIRONMENT: ((rollout_environment))
  JOB_NAME: ((awx_worklow_job_template_name))
  PRIVATE_KEY: ((concourse_ci_lab_user_private_key))
  SIDE: ((rollout_side))
  TOWER_HOST: ((awx_host))
  TOWER_USERNAME: ((concourse_ci_lab_user))
  TOWER_PASSWORD: ((concourse_ci_lab_password))
  TOWER_VERIFY_SSL: f

run:
  path: bash
  dir: pull-request
  args:
    - -ec
    - |
      echo "AWX host: ${TOWER_HOST}"
      echo "AWX login user: ${TOWER_USERNAME}"
      echo "AWX verify SSL: ${TOWER_VERIFY_SSL}"
      BUILD_ID=$(cat ../build-meta-data/build-id)
      BUILD_NAME=$(cat ../build-meta-data/build-name)
      echo "Build ID: ${BUILD_ID}"
      DATE=$(date)
      TOWER_VERSION=$(awx -k ping | jq -r ".version")
      echo "AWX version: ${TOWER_VERSION}"
      export TOWER_TOKEN=$(awx login --conf.description "Concourse job deploy-latest:${BUILD_NAME} on ${DATE}" --conf.client_id "${CLIENT_ID}" --conf.client_secret "${CLIENT_SECRET}"|jq -r .token)
```

## Expected results
The task should run with `containerd` runtime configured.

## Actual results
The task fails as it cannot be started at all by Concourse. The error message is provided above.
The offending folder that fails to mount is not even part of the offending job.
Everything works under `7.1/containerd` or `7.2/guardian`.

## Additional context
There were no changes to the deploy jobs or the builder image behind it.

### Concourse version
7.2.0

### Did this used to work? 
Yes

### Docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-14-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 47.12GiB
 Name: concourse-wrk-01.xyz.com
 ID: BZJV:YSZ2:FAC3:LOAY:NVDS:YKNJ:BOMP:ADLO:HOIR:3QR3:PI2H:ZKDW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://webproxy.xyz.com:3128/
 No Proxy: localhost,127.0.0.1/8,lab.ewerk.com
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://docker-hub-mirror.xyz.com:80/
 Live Restore Enabled: false
```
