### ISSUE TITLE
Serialization of execution

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#698]
There are three different features for serialization of the execution and none of them seems to be useful in the cases I am having. I would like to propose a different serialization feature that will make the current three obsolete - because they are a subset of it - but will offer way much.

If we have a new object - lets call it semaphore. Semaphore have these properties:
1. Name/id - an arbitrary unique name.
2. Scope:
   2.1. System - the whole system
   2.2 Team - for jobs part of this team
   2.3 Pipeline - for jobs in the pipeline
   2.4 Job - for particular job
   2.5 Worker - for jobs running on particular worker
3. Permits - how many job permits

Now when this semaphore is used in the job you specify the name and the permits you exhaust.

```
Semaphore:
- Name: Serial
  Scope: Job
  Permits: 1

Semaphore:
- Name: Max-inflight
  Scope: Job
  Permits: (n)

Semaphore:
- Name: SerialGroup
  Scope: Pipeline
  Permits: 1
```

These do define all concourse currently provide, but we can also have the two other scenarios that I already found impossible to do: 

Limiting memory consuming jobs per worker. For this all I will need is:

```
 Semaphore:
 - Name: Memory
   Scope: Worker
   Permits: 15
```

And then specify how much every job consumes.

Cleanup an external resource. 

```
Semaphore:
- Name: Cleaner
  Scope: System
  Permits: 1000
```

And then use 1 permit for all the regular jobs and 1000 permits for the cleaning job.

As of implementation all you need is to extend the semaphore id with the current scope object, say: semaphore_is = <name>_<scope>_<scope_obj_name>

And support for adding removing an arbitrary number instead 1.
