### ISSUE TITLE
Figure out best approach for providing inputs/outputs to prototypes

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6980]
## Summary

The core team has discussed several alternatives for configuring inputs/outputs when running prototypes (primarily considering the use of the `run` step, but also considering prototype "interfaces" e.g. resource prototypes).

Since Prototypes are intended to support any arbitrary generic task, they should be flexible in how they accept inputs and produce outputs.
* Should support taking a non-fixed list of inputs and producing a non-fixed list of outputs
* e.g. license scanning across a list of repositories should produce a list of results
* e.g. cross compiling a binary across a matrix of platforms/architectures may produce many outputs for a single input

We should draft a follow-up RFC to the original prototypes RFC (concourse/rfcs#37) that outlines the approaches.

**Comment by aoldershaw** [comment]
### Option 1a - dynamic input/output config

The prototype's `info` response will include the required inputs/outputs(/caches?) based on the request object (i.e. `run.params`).

For instance, with the following `run` step:

```yaml
run: some-message
type: some-prototype
params:
  files: [some-artifact-1/some-file, some-artifact-2/some-other-file]
  other_config: here
  output_as: some-output
```

...the prototype may emit the following config:

```yaml
inputs:
- name: some-artifact-1
- name: some-artifact-2

outputs:
- name: some-output
```

...and Concourse will know to mount these artifacts appropriately.

#### Pros

* Simple to implement (within Concourse)
* No new concepts
  * If you're familiar with `task` configs, this is effectively the same - just more flexible
  * No new pipeline syntax/semantics
  * Feels like `put.inputs: detect`, but is more explicit (from the prototype author's PoV)
* Prototype details can be encapsulated behind config
  * e.g. with the oci-build-task, if you want to persist the build cache, you need to specify: `caches: [{path: cache}]`
  * With an approach like this, you could just specify: `cache: true` (i.e. you don't need to know where the cache is)

#### Cons

* Has performance implications - ignoring caching, `run` steps will need to spin up two containers (one for getting the `info` response, and one for running the prototype message)
  * Caching is easy for fixed configuration, but with variable interpolation it may not work so well
* More burden on prototype authors

**Comment by aoldershaw** [comment]
### Option 1b - JSON schema based dynamic input/output config

Similar to 1a in that we rely on the prototype to instruct Concourse on what the inputs/outputs should be are. However, rather than the `info` response providing the inputs/outputs config, it instead gives a JSON schema for each message, with some special semantics for defining inputs/outputs:

e.g. for a `build` message on an `oci-image` prototype:

```json
{
  "type": "object",
  "properties": {
    "files": {
      "type": "array",
      "items": {
        "type": "string",
        "concourse:input": {
          "name": "((name))"
        }
      }
    },
    "other_config": {
      "type": "string"
    },
    "output_as": {
      "type": "string",
      "concourse:output": {
        "name": "((name))"
      }
    }
  },
  "required": ["context"]
}
```

This isn't fully fleshed out, but the key concept is these `concourse:*` keywords, which allow you to say: this element in the object is an input/output/whatever.

#### Pros

* Performance implications from 1a disappear - much easier to cache
* All inputs/outputs need to be mentioned in the config, so nothing is implicit
  * Can also be viewed as a con - more verbose
* Gives a way for Concourse to easily validate input to a prototype, and for IDE's to provide more useful suggestions - https://github.com/concourse/concourse/issues/481
  * The IDE part may not be practical as getting the JSON schema requires running a docker image

#### Cons

* Makes it much more of a burden to write prototypes
* May be too restrictive - requires Concourse to support specific custom keywords in the JSON schema

**Comment by aoldershaw** [comment]
### Option 2a - emit outputs in response objects

This option implies two things:

1. A way for pipelines to explicitly specify what inputs should be provided to a prototype (whereas options 1a/b had the prototypes telling Concourse what inputs should be provided)
2. A way for prototypes to provide output artifacts as part of its message response (whereas option 1a included in the info response, i.e. not at "runtime" w.r.t. running the message)

The response objects could look something like:

```json
{
  "object": {
    "some_data": 123,
    "some_output": {"artifact": "./path/to/output"}
  }
}
```

Concourse will interpret `{"artifact": "./path"}` as an output, where `./path` is relative to some path that's mounted by default to all prototypes. *This means that multiple outputs may share an output volume, and differ only by the path within that volume.*

Since prototypes can emit multiple response objects, this also means you can have *streams* of outputs sharing a name that are identified by some other field(s). e.g. the above artifact could be identified as `some_output{some_data: 123}`, or something like that. That gives you the option of aggregating/filtering the stream of outputs by a subset of the fields that identify them - a similar idea has been fleshed out for the `across` step in https://github.com/concourse/rfcs/pull/29#discussion_r619863020.

w.r.t. passing inputs, we can use an approach similar to `put.inputs: detect`, but more explicit (from the pipeline's PoV), e.g.

```yaml
run: some-message
type: some-prototype
params:
  files: [@some-artifact-1/some-file, @some-artifact-2/some-other-file]
  other_config: here
```

Here, `@` is a special syntax that points to an artifact name and both *mounts it to the container* and *resolves to an absolute path to the artifact*. In this example, the prototype would receive something like:

```json
{
  "object": {
    "files": ["/tmp/build/some-artifact-1/some-file", "/tmp/build/some-artifact-2/some-file"],
    "other_config": "here"
  },
  "response_path": "..."
}
```

Interestingly, data and artifacts are all collocated, which raises a question - do we need a separate namespace for artifacts like we have now, or can they be treated as "just vars" and share the local vars namespace?

In order to use emitted artifacts within the pipeline, you can "set" them to the local namespace:

```yaml
run: some-message
type: some-prototype
params:
  files: [@some-artifact-1/some-file, @some-artifact-2/some-other-file]
  other_config: here
set_artifacts: # or, if we do collapse the namespaces, this could be `set_vars`
  some_output: my-output # some awkwardness around _ vs - here
```
