### ISSUE TITLE
Jobs with both "passed" and "version:every" constraints fails to auto trigger build on a special case

### ISSUE THREAD

**Issue by kirthiprakash** [concourse/concourse#6988]
## Summary
When a job is configured with `passed: [dependent-job]` and `version:every`, it fails to auto trigger if the `dependent-job` has duplicate builds i.e. two consecutive builds but with same input version.

## Steps to reproduce
Install Concourse V 7.1.0 using docker-compose file here [https://github.com/kirthiprakash/pipeline-example/blob/master/concourse_installation/docker-compose.yml](https://github.com/kirthiprakash/pipeline-example/blob/master/concourse_installation/docker-compose.yml)
Setup a two jobs with one job with `passed` constraint and `version:every` constraint
```
jobs:
  - name: stage-job
    plan:
      - get: pipeline-example-repo
        version: every
        trigger: true
      - task: display-file
        .
        .
        .
  - name: prod-job
    plan:
      - get: pipeline-example-repo
        trigger: true
        version: every
        passed: [stage-job]
      - task: display-file
```
Full configuration is available at [https://github.com/kirthiprakash/pipeline-example/blob/master/pipeline.yaml](https://github.com/kirthiprakash/pipeline-example/blob/master/pipeline.yaml)

Let the two jobs synchronise at the same input versions.

Assume the current state to be like this.
```
Resource v2 —> stage job build 2 ————> Resource v2 —> prod job build 2
Resource v1 —> stage job build 1 ————> Resource v1 —> prod job build 1
```

Now manually trigger a build on stage job from the Concourse UI which will result in
```
Resource v2 —> stage job build 3 ————> Scheduling Algorithm finds resource v2 is already built and doesn’t trigger new build
Resource v2 —> stage job build 2 ————> Resource v2 —> prod job build 2
Resource v1 —> stage job build 1 ————> Resource v1 —> prod job build 1
```
From now on, for any new resource versions, only stage job gets built and the prod job is never triggered.

Suppose there is new resource version v3.
```
Resource v3—> stage job build 4  ————> 
Resource v2 —> stage job build 3 ————> Algorithm finds resource v2 is already built and doesn’t trigger new build
Resource v2 —> stage job build 2 ————> Resource v2 —> prod job build 2
Resource v1 —> stage job build 1 ————> Resource v1 —> prod job build 1
```

The scheduling algorithm for prod job always resolves `stage-job/build3` and `resource v2`. Since `resource v2` is already built on `prod job` it never auto triggers the build. This was confirmed by enabling traces.

## Expected results

After two consecutive builds on upstream job with same inputs, the downstream job should trigger a new build when there is a new successful build on upstream job with a new input version.

## Actual results

After two consecutive builds on upstream job with same inputs, the downstream job never triggers even a single build even though there are new input versions and new successful builds on the upstream job.

## Additional context
The issue was not reproducible when `version:every` was removed from `prod job`

A note on traces: Traces really helped identified the issue, but it would be great if it had more details. For example, a span from the `Algorithm.compute` contains information about the version candidates but it was in md5 format. I did try a md5 hash of the commit id, but it wasn't matching. it took some time to figure out the input to the md5 should be `{"ref":"<commit id>"}` without any space. It would have been a lot easier if the version was displayed was from the resource type format.

## Triaging info

* Concourse version: V 7.1.0
* Browser (if applicable):
* Did this used to work? I never saw this issue on V.5.5.7

**Comment by kirthiprakash** [comment]
Found one more use case which results in the same issue.
`stage job` has two inputs `resource 1` and `resource 2` but `prod job` has only one input `resource 1`.
```
jobs:
  - name: stage-job
    plan:
      - get: resource 1
        version: every
        trigger: true
     - get: resource 2
        version: every
        trigger: true
      - task: display-file
        .
        .
        .
  - name: prod-job
    plan:
      - get: resource 1
        trigger: true
        version: every
        passed: [stage-job]
      - task: display-file
```
For every new version of `resource 2`, `stage-job` gets built. After sometime if there is a new version for `resource 1`, the scheduling algorithm for `prod job` resolves to a build after the last previously build `stage job` when `resource 1` had a new version.

Let me know if this is not clear, I can write up a detailed example for the same.

**Comment by vito** [comment]
Thanks for the detailed report! It's great to see the tracing efforts have helped out with this stuff. Thanks for the feedback about the md5s; it would be nice to show more user-friendly data there, though I'm not sure if the scheduler has access to it. It's a performance-critical component so we'd have to weigh the impact of fetching that data if it's not available, plus emitting it to the trace (versions can be large with some awkward resource types). Or maybe there's some way we can make the md5 <-> version correspondance easier to access (e.g. `fly resource-versions --md5`?).

Unfortunately I have 5 words you might not enjoy hearing: this is the intended behavior. `version: every` with `passed` doesn't mean it runs every time the upstream job runs; it just means it'll run with every version that came out of the upstream job instead of fast-forwarding to the latest version available. If the downstream job has already run with a version, it has no need to trigger again from the scheduler's perspective.

To fix this you could explicitly create a new version as an output of `stage-job` and pass it to `prod-job`. That way there will always be a new version for it to consume. From Concourse's perspective there must be some way to express what has changed as a resource relationship between the jobs - so did some external state change? Can that be expressed through a resource `put` and `get`?

FYI, `version: every` with `passed` constraints also has a hairy gotcha that allows it to skip versions (https://github.com/concourse/concourse/issues/736). This scenario is not likely to be fixed; it's kind of a fundamental difficulty with interpreting "give me all versions but oh wait only ones that passed the upstream jobs."

In general I would advise against using `version: every` + `passed`. We might turn it into a warning in the future, or even an error. `version: every` in general is pretty burdensome to support, and it's even more complicated with `passed`. We're trying to reduce at least some of the need for `version: every` with the [v10 roadmap](https://github.com/concourse/concourse#the-road-to-concourse-v10) - primarily the 'run across all things' use case, which can be done with an `across` step in the future.

Hope this helps!

**Comment by kirthiprakash** [comment]
Hi @vito. Thanks for you explanation. I will try and see if I can create different outputs on the `stage job` (even though the inputs remain the same) and pass it to the `prod job`. 

Regarding the `version: every` constraint, I do understand that it can get really complex when used with `passed` constraint and do not expect the downstream job to be built on every input version. I opened this issue because, the scheduling algorithm is reaching an inconsistent state and it not automatically recovering from that state. If there are two consecutive builds on `stage job` with same input versions, the `prod job` will be struck in that version indefinitely unless someone manually pins a different input version. I am sure this is not an intended behaviour. I guess I was not precise in wording the "Expected Results" and "Actual Results" and I will update the same.

If this was an intended behaviour then we should never allow the `version: every` + `passed` constraints to the configured together and bail out with an error.

**Comment by vito** [comment]
> If there are two consecutive builds on `stage job` with same input versions, the `prod job` will be struck in that version indefinitely unless someone manually pins a different input version. I am sure this is not an intended behaviour. I guess I was not precise in wording the "Expected Results" and "Actual Results" and I will update the same.

Ahhh, sorry, I didn't notice that part! That definitely sounds broken - we'll take a look.

**Comment by taylorsilva** [comment]
Explanation is great, adding some visuals to help understand the problem and a simpler pipeline:
Pipeline looks like this:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/4583837/120219060-a0e7ba00-c208-11eb-8aed-43c052b09e3d.png">

Version and job history looks like this:
1. first resource version triggers both jobs
2. job1 is manually triggered using the "re-run with same input" button to avoid a check being issued for a new version of the resource
3. Manually issue checks for the resource, creating new versions. job1 will trigger but job2 will never trigger.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4583837/120219381-29665a80-c209-11eb-917d-884fb59cb53d.png">

```yaml
resources:
- name: onesec
  type: time
  check_every: never
  source:
    interval: 1s

jobs:
- name: job1
  plan:
    - get: onesec
      version: every
      trigger: true
- name: job2
  plan:
    - get: onesec
      trigger: true
      version: every
      passed: [job1]
```
