### ISSUE TITLE
No error message on resource_types source.repository

### ISSUE THREAD

**Issue by tinygrasshopper** [concourse/concourse#7047]
## Summary

If an invalid image reference is provided when declaring a new resource_type in a pipeline. The pipeline is stuck and no descriptive error message is surfaced to the user.

## Steps to reproduce

1. Create a pipeline definition which defines and uses a resource_type, but the repository specified is not valid, for eg:
```
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-invalid
```
2.  Apply the pipeline
3. attempt to trigger the resource 

## Expected results
An error message that the image could not be pulled down, or any other message informing the user configuration might be wrong

## Actual results
The resource does not update

## Triaging info

* Concourse version: 7.1.0
* Browser (if applicable):
* Did this used to work?: Dont know
