### ISSUE TITLE
Implement Prototype support in pipeline config

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#7060]
## Summary

Allow users to configure `prototypes` in the pipeline config, much like how `resource_types` are configured, e.g.:

```yaml
prototypes:
- name: some-prototype
  type: registry-image
  source: {repository: aoldershaw/some-prototype}

...
```

Prototypes should be able to be checked for new versions, but needn't be checked periodically - they can instead be checked as needed (i.e. prior to a `run:` step executing, just like how we will be checking `resource_types` prior to a `get:` or `put:` step executing. note that we *currently* periodically check `resource_types`, but that is subject to change as part of #6274).

Implementation of the `run` to actually use prototypes in builds will be a part of another issue.

## Context

* RFC: concourse/rfcs#37
* Part of #6905
