### ISSUE TITLE
Resource Type does not pick up the new docker image

### ISSUE THREAD

**Issue by datianshi** [concourse/concourse#7062]
## Summary

Resource Type does not pickup the new docker image
## Steps to reproduce

```yaml
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.13.3
```

Change Tag 0.15.2. It still uses the old image.

I have to change the resource type name to make the put use the new image

## Expected results

Put should use the new resource type image

## Actual results

Put does not use the new resource type image. Got to change resource type name. 

## Triaging info

* Concourse version: 7.2.0
* Browser (if applicable):
* Did this used to work?

**Comment by taylorsilva** [comment]
This should be fixed by #6923, looks to be the exact problem described in the PR:
> This covers the edge case where a put-only resource's parent-type would not be check because we were only looping over everything except put-only resources

This will be fixed in 7.3.0 which we expect to come out this week. Closing this issue now. Leave a comment if your think that PR does not fix your problem.

Also, instead of `docker-image` you should use `registry-image` as the resource type, it's faster!

**Comment by jamie-pate** [comment]
I'm running into this in 7.3.0, I have a similar resource type on my internal registry, but it continues to only run the old image, even after running `check-resource-type` or `destroy-pipeline`

```
resource_types:
  - name: rsync-resource
    type: registry-image
    source:
      #mrsixw/concourse-rsync-resource
      repository: ((my_registry))/concourse-rsync-resource
      username: ((registry.username))
      password: ((registry.password))
```
