### ISSUE TITLE
Metric "concourse_workers_tasks" incongruous with limit-active-tasks

### ISSUE THREAD

**Issue by funkypenguin** [concourse/concourse#7085]
## Summary
Hey guys! In relation to #7084, we're trying to use `limitActiveTasks: 1` to limit how many jobs can run in our concourse instance at once. I mentioned in #7084 that the `concourse_tasks_waiting` metric mentioned in the docs doesn't exist, but I did find the `concourse_workers_tasks` metric, which I took to be a suitable stand-in.

This issue covers the fact that while `LimitActiveTasks: 1` seems to be working (see evidence below), the `concourse_workers_tasks` metric shows values way higher than 1 (also below)

![image](https://user-images.githubusercontent.com/1524686/119810190-eb7fe280-bf39-11eb-8e97-2ca0aa9bf8e0.png)

But prometheus says:

![image](https://user-images.githubusercontent.com/1524686/119810086-d1460480-bf39-11eb-9914-3633a2dc46fd.png)

So why aren't the tasks-per-worker in Prometheus limited to 1?

## Steps to reproduce
1. Deploy using helm chart, setting `concourse.web.containerPlacementStrategy=limit-active-tasks` and `concourse.web.limitActiveTasks=1`
2. Trigger multiple pipelines / tasks
3. Observe that tasks are delayed, with `no suitable workers found, waiting for worker...`
4. Examine the `concourse_workers_tasks` metric, observe total tasks > 1

## Expected results

Since tasks-per-worker are limited to 1, we expected `concourse_workers_tasks` to reach as high as 1, and no higher

## Actual results

`concourse_workers_tasks` reaches as high as 4.5 (see screenshot above)

## Triaging info

* Concourse version: 7.3.0
* Browser (if applicable):
* Did this used to work? N/A

**Comment by taylorsilva** [comment]
We tried to reproduce this locally using a docker-composed concourse, which gives us a similar setup to what the helm chart would give us (one web node, one worker node).

We didn't set multiple pipelines, but we did trigger the same small job multiple times, starting up to 20 builds at once.
These are the two pipelines we used:
```yaml
jobs:
- name: simple-job
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: mock
        source: {mirror_self: true}
      run:
        path: sh
        args:
        - -c
        - |
          until test -f /tmp/stop-waiting; do
            echo 'waiting for /tmp/stop-waiting to exist'
            sleep 10
          done

          echo done
```
and
```yaml
resources:
- name: some-resource
  type: mock
  source: {initial_version: first-version}

jobs:
- name: simple-job
  plan:
  - get: some-resource
```

We watched the `concourse_workers_tasks` metric and never saw it go past one. We also watched the `active_tasks` column in the `workers` table in the database and never saw it go past one either.

Were you able to reproduce the issue with the steps you wrote?
How large is your production cluster where you are seeing this issue? How many web and worker nodes does it have?
