### ISSUE TITLE
Resource logical names with `/` in them [Deprecate it or Support it?]

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#715]
# Feature Verification
## Current (undocumented?) behavior

I can declare logical names for `get`s of resources that include `/` in them, which can help me if I want a certain arrangement when the volumes are mounted in.

However, we're not sure about the consequences of this. Is the behavior for overlapping mounts defined, or expected in a certain way?

One specific use case where we'd find this really enabling, if it were actually supported, would be arranging files that we are building into Docker images. Example:

```
  - get: centos72-resource
    trigger: true
  - get: docker-root/toolsmiths-images
    resource: toolsmiths-images
  - put: centos72-with-extras-resource #a docker-image-resource
    params:
      build: "docker-root"
      dockerfile: docker-root/toolsmiths-images/gpdb/centos72/Dockerfile
```
## Bug/Error(?) it helps us avoid

If we have a put that looks like:

```
  - get: centos72-resource
    trigger: true
  - get: toolsmiths-images
  - put: centos72-with-extras-resource #a docker-image-resource
    params:
      build: "."
      dockerfile: toolsmiths-images/gpdb/centos72/Dockerfile
```

We get `Error checking context: 'no permission to read from '/tmp/build/put/centos72-resource/rootfs/dev/tty0''.`
## Going forward
- Is this formally supported? -OR-
- Will this be deprecated?
