### ISSUE TITLE
Upgrading concourse to v7.3.1 caused windows task to consistently hang

### ISSUE THREAD

**Issue by mnitchev** [concourse/concourse#7155]
## Summary

After upgrading our concourse (BOSH deployed) from 7.2.0 to 7.3.1 a job that runs tests on windows started to hang. It looks like the job cannot create a container at all for the task step and the job stays running forever. Attempts to abort a build are unsuccessful - the http request returns 204, but it does nothing. However after we restart the web vm the build finally gets aborted and produces an error different error messages about failing to create a container, some of specifically mentioning that `stream-in` has failed, for example:

```
find or create container on worker d91bec0e-packer-5d82fe93-b032-9b01-87e1-d597f0819862: Put "/volumes/1b2f682e-50c6-4530-5fbb-2bf0b29f721a/stream-in?path=.": write tcp 10.0.1.100:40374->10.0.1.100:39229: write: broken pipe
...
find or create container on worker d91bec0e-packer-5d82fe93-b032-9b01-87e1-d597f0819862: failed to stream in to volume
```

It looks like the specific git resource - [garden-runc-release](https://github.com/cloudfoundry/garden-runc-release) - is causing the failure. When we try to replace the resource with some of our other github repositories, the job succeeds. 
This may be because the repository is rather large with it's many submodules (around 500MB), but we did try creating a test repostiroy with dummy files (around 1GB) and the job was able to run.

Additionally we have also tried to recreate the `worker-windows` (a few times) and the `web` vms, but this did not help. We have also tried to downgrade back to 7.2.0, but this causes issues with the database - `pq: there is no unique or exclusion constraint matching the ON CONFLICT specification`.

## Steps to reproduce

1. deploy concourse with a windows worker
1. create the pipeline with the below yaml
1. unpause and run the `windows-test` job
1. see it hang forever

Pipeline yaml that reproduces the issue:
```yaml
groups:
  - name: main
    jobs:
    - windows-test

jobs:
  - name: windows-test
    public: true
    serial: true
    plan:
    - do:
      - get: grr-test
        trigger: true
      - task: build
        config:
          inputs:
            - name: grr-test
          platform: windows
          run:
            path: powershell
            args:
            - "-ExecutionPolicy"
            - "Bypass"
            - "echo"
            - "never gonna happen"

resources:
  - name: grr-test
    type: git
    source:
      uri: https://github.com/cloudfoundry/garden-runc-release
      branch: grr-test

```

## Expected results

The job passes.

## Actual results

The job stays running forever

## Additional context

We went through the `web` and `worker-windows` vms' logs, didn't find much useful information. Grepping for `job.*windows-test` in the web logs yielded these lines:
```log
web.stdout.log:{"timestamp":"2021-06-10T11:37:30.170875429Z","level":"info","source":"atc","message":"atc.create-job-build.created-build","data":{"build":"check","build_id":2295815,"pipeline":"windows-test","resource":"grr-test","session":"386421","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:37:34.000310390Z","level":"info","source":"atc","message":"atc.tracker.notify.run.running","data":{"build":"1","build_id":2295814,"job":"windows-test","pipeline":"windows-test","session":"23.10825.2","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:37:34.004544434Z","level":"info","source":"atc","message":"atc.tracker.notify.run.get-step.initializing","data":{"build":"1","build_id":2295814,"job":"windows-test","pipeline":"windows-test","session":"23.10825.2.3","step-name":"grr-test","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:37:34.018473189Z","level":"info","source":"atc","message":"atc.tracker.notify.run.get-step.starting","data":{"build":"1","build_id":2295814,"job":"windows-test","pipeline":"windows-test","session":"23.10825.2.3","step-name":"grr-test","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:38:18.413709483Z","level":"info","source":"atc","message":"atc.tracker.notify.run.get-step.finished","data":{"build":"1","build_id":2295814,"exit-status":0,"job":"windows-test","pipeline":"windows-test","session":"23.10825.2.3","step-name":"grr-test","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:38:18.417698611Z","level":"info","source":"atc","message":"atc.tracker.notify.run.task-step.initializing","data":{"build":"1","build_id":2295814,"job":"windows-test","job-id":4267,"pipeline":"windows-test","session":"23.10825.2.4","step-name":"build","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:38:19.966010213Z","level":"info","source":"atc","message":"atc.tracker.notify.run.task-step.stream-to.start","data":{"build":"1","build_id":2295814,"job":"windows-test","job-id":4267,"pipeline":"windows-test","session":"23.10825.2.4.10","step-name":"build","team":"main"}}
web.stdout.log:{"timestamp":"2021-06-10T11:38:40.703730766Z","level":"info","source":"atc","message":"atc.tracker.notify.run.task-step.stream-to.end","data":{"build":"1","build_id":2295814,"job":"windows-test","job-id":4267,"pipeline":"windows-test","session":"23.10825.2.4.10","step-name":"build","team":"main"}}
```

The worker-windows logs had this error that looked related:
```log
job-service-wrapper.out.log:1412:{"timestamp":"2021-06-10T11:07:50.252089300Z","level":"error","source":"worker","message":"work
er.garden.garden-server.attach.failed","data":{"error":"unknown process: task","handle":"55c954b0-4866-4c7d-6421-b2fcf573fdc9","
session":"1.1.5097"}}
```

Related issue in our backlog: cloudfoundry/garden-runc-release#192

## Triaging info

* Concourse version: **v7.3.1** (upgraded from v7.2.0)
* Browser (if applicable): **N/A**
* Did this used to work? - **Yes**
