### ISSUE TITLE
Diagnosis of slow step Inititialization. (btrfs, dcind)

### ISSUE THREAD

**Issue by jamie-pate** [concourse/concourse#7160]
## Summary
I recently added a pipeline that uses dcind (docker compose in docker, https://github.com/jamie-pate/concourse-dcind ) and it has run progressively slower at each step. There don't seem to be any steps to diagnose the cause of this slow initialization.

Unable to use dcind because the initialization times (even for the `get` step which previously ran immediately) become catastrophically long.

Did this used to work?
It seems like there are some previous issues about step initialization, but they were all closed assuming that they were caused by the overlay driver. I'm using btrfs but still have this issue. It would be nice to:
  
  1. Diagnose this issue. (I only vaguely understand it's likely somehow related to volumes at this point, not sure how to read the logs to further diagnose)
  2. If the issue is due to my specific setup and not a bug that can be fixed:
      * Have some diagnosis steps to determine the root cause
      * Show some extra warnings in the UI that point to the root cause of this issue and docs on how to fix it

## Steps to reproduce

Deploy a pipeline similar to this one:
```Yaml
resource_types:
- name: gerrit
  type: registry-image
  source:
    # image built from https://github.com/jamie-pate/concourse-resources/tree/master/gerrit
    repository: your-registry.local/gerrit-resource
resources:
- name: project1
  type: gerrit
  source:
    url: https://your-gerrit.local/g/
    query: status:open project:project1 branch:concourse-pipeline
    username: ((gerrit.username))
    password: ((gerrit.password))

    private_key: ((gerrit.private_key))
    private_key_user: ((gerrit.username))
    private_key_passphrase: ((gerrit.private_key_passphrase))
    fetch_url: ssh://your-gerrit.local/fos-gui-light

- name: project1-connector
  type: git
  source:
    uri: ssh://your-git.local/project1-connector
    # ...

jobs:
- name: integration_test
  plan:
  # Trigger this job for every new commit
  - get: project1
    version: every
    trigger: true
  - get: project1-connector
    version: latest
  - task: run
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          username: ((registry.username))
          password: ((registry.password))
          repository: your-registry.local/concourse-dcind
          tag: latest
      inputs:
      - name: project1
      - name: project1-connector
      outputs:
      # made up output, not used (yet)
      - name: test-results
        path: project1-connector/test-results
      run:
        path: entrypoint.sh
        args:
        - bash
        - -ceux
        - |
          # start containers
          docker-compose -f ./docker-compose.e2e.yaml --env-file ./.env up --build --force-recreate --exit-code-from test-cypress
          docker-compose -f docker-compose.e2e.yaml down
          docker volume rm $(docker volume ls -q)
          # 1.1G    /scratch/docker/btrfs/subvolumes/94ff554a5387163dd3030dce6d81caf3cf8ce60ce5baf6f2eb20f6bd03a0ad33
          # 3.8G    /scratch/docker/btrfs/subvolumes
```

## Expected results

Initialization should not be > 30 seconds without a good reason.

Initialization of `get` steps should not be affected by the volume size of task steps?

If there is a good reason:

      * Have some diagnosis steps to determine the root cause
      * Show some extra warnings in the UI that point to the root cause of this issue and docs on how to fix it

## Actual results

Initialization of all steps of the related pipeline takes an excessive amount of time, and I've got no idea why or how to fix it.

## Additional context
![concourse](https://user-images.githubusercontent.com/682658/121724652-08212c00-ca9d-11eb-8c27-ec999c8e2a80.png)
![cpu](https://user-images.githubusercontent.com/682658/121724656-08b9c280-ca9d-11eb-8095-d6643888bcd0.png)
![disk](https://user-images.githubusercontent.com/682658/121724660-08b9c280-ca9d-11eb-84bf-0a428df9b853.png)
![network](https://user-images.githubusercontent.com/682658/121724663-09525900-ca9d-11eb-9eeb-5e97c1304e3a.png)

concourse-web.env

```Bash
CONCOURSE_POSTGRES_HOST=localhost
CONCOURSE_POSTGRES_USER=concourse
CONCOURSE_POSTGRES_PASSWORD='${concourse_postgres_password}'
CONCOURSE_POSTGRES_DATABASE=concourse
CONCOURSE_EXTERNAL_URL=${concourse_external_url}
CONCOURSE_BIND_PORT=80
CONCOURSE_TLS_BIND_PORT=443
CONCOURSE_TLS_CERT=/etc/concourse.d/server.crt
CONCOURSE_TLS_KEY=/etc/concourse.d/server.key

CONCOURSE_ADD_LOCAL_USER=test:test
CONCOURSE_MAIN_TEAM_LOCAL_USER=test

CONCOURSE_SESSION_SIGNING_KEY=/mnt/concourse-web/keys/session_signing_key
CONCOURSE_TSA_AUTHORIZED_KEYS=/mnt/concourse-web/keys/authorized_worker_keys
CONCOURSE_TSA_HOST_KEY=/mnt/concourse-web/keys/tsa_host_key
CONCOURSE_TSA_PUBLIC_KEY=/mnt/concourse-web/keys/tsa_host_key.pub
CONCOURSE_TSA_WORKER_PRIVATE_KEY=/mnt/concourse-web/keys/worker_key

CONCOURSE_CLIENT_SECRET=${concourse_client_secret}
CONCOURSE_TSA_CLIENT_SECRET=${concourse_client_secret}

CONCOURSE_VAULT_URL=${concourse_vault_url}
CONCOURSE_VAULT_CA_CERT=/mnt/concourse-web/keys/vault_ca_cert.crt

#? didn't work, using  --vault-insecure-skip-verify instead #CONCOURSE_VAULT_INSECURE_SKIP_VERIFY="true"
CONCOURSE_VAULT_AUTH_BACKEND=approle
CONCOURSE_VAULT_AUTH_BACKEND_MAX_TTL=1h
CONCOURSE_VAULT_AUTH_PARAM=${concourse_vault_auth_param}
# TODO: # CONCOURSE_VAULT_CA_CERT: /vault/config/server.crt
# (didn't work using --vault-insecure-skip-verify instead)

CONCOURSE_VAULT_PATH_PREFIX=concourse

# limit number of containers started on each worker
CONCOURSE_CONTAINER_PLACEMENT_STRATEGY=limit-active-tasks,volume-locality
CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER=12
CONCOURSE_MAX_ACTIVE_CONTAINERS_PER_WORKER=24

# NOTE: btrfs works best if we create a btrfs filesystem on the worker
# TODO: test performance vs overlay
CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER=btrfs
```

Concourse-worker.env

```Bash
CONCOURSE_WORK_DIR=/mnt/concourse-worker/worker
CONCOURSE_LOG_LEVEL=error
CONCOURSE_TSA_HOST=${concourse_tsa_host}:2222
CONCOURSE_TSA_PUBLIC_KEY=/mnt/concourse-worker/keys/tsa_host_key.pub
CONCOURSE_TSA_WORKER_PRIVATE_KEY=/mnt/concourse-worker/keys/worker_key
CONCOURSE_GARDEN_BIND_IP=0.0.0.0
CONCOURSE_GARDEN_DNS_SERVER=${dns}
CONCOURSE_GARDEN_DESTROY_CONTAINERS_ON_STARTUP=
CONCOURSE_GARDEN_LOG_LEVEL=error
CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=debug
#error
CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0
CONCOURSE_BAGGAGECLAIM_DRIVER=btrfs
# concourse-worker/worker/volumes/ automatically?
# CONCOURSE_BAGGAGECLAIM_VOLUMES=/mnt/concourse-worker/volumes
#
# CONCOURSE_BAGGAGECLAIM_OVERLAYS_DIR=/mnt/concourse-worker/overlays

```

## Triaging info

Concourse version: 7.3.0
Deployment type (BOSH/Docker/binary): binary
Infrastructure/IaaS: Terraform -> OneNebula ( (concourse-web+postgresql) , concourse-worker x 2 )
