### ISSUE TITLE
Jobs with no get/put steps are rendered in the resources column

### ISSUE THREAD

**Issue by chenbh** [concourse/concourse#7207]
## Summary

Reported by @khng

The most visible issue is that the job overlaps the resource, but I think the fundamental problem is that the job node is rendered in the resources column (or maybe it's the first column which happens to be for resources)

## Steps to reproduce

Using the following pipeline config:

```yaml
resources:
- name: a
  type: mock
- name: b
  type: mock

jobs:
- name: a
  plan:
  - get: a
- name: b
  plan:
  - get: a
  - get: b
- name: overlapping
```

## Expected results

UI is rendered normally

## Actual results

![Screen Shot 2021-06-23 at 3 50 46 PM](https://user-images.githubusercontent.com/17577073/123159246-cb5d1980-d43a-11eb-9705-faccb3b3734b.png)

## Additional context

I think the jobs are sorted at some point, just changing the names can result in a different graph

```yaml
jobs:
- name: c
  plan:
  - get: a
- name: b
  plan:
  - get: a
  - get: b
- name: overlapping
```

![Screen Shot 2021-06-23 at 3 54 48 PM](https://user-images.githubusercontent.com/17577073/123159741-5ccc8b80-d43b-11eb-8c6c-e52866e515e9.png)

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?
