### ISSUE TITLE
check_every param is not working

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#7222]
### Discussed in https://github.com/concourse/concourse/discussions/6154

We expect the following resource to be checked multiple times within one minute. Instead we see it checked once per minute.

```yaml
resources:
- name: some-resource
  type: mock
  check_every: 15s
  source: {initial_version: first-version}

jobs:
- name: simple-job
  plan:
  - get: some-resource
```

Verified by watching the output of `fly builds`.

```
$ fly -t l builds
id  name                      status     start                     end                       duration  team  created by
91  test/some-resource/check  started    2021-06-28@16:32:42-0400  n/a                       5s+       main  system
90  test/some-resource/check  succeeded  2021-06-28@16:31:42-0400  2021-06-28@16:32:13-0400  31s       main  system
89  test/some-resource/check  succeeded  2021-06-28@16:30:42-0400  2021-06-28@16:31:12-0400  30s       main  system
88  test/some-resource/check  succeeded  2021-06-28@16:29:42-0400  2021-06-28@16:30:13-0400  31s       main  system
87  test/some-resource/check  succeeded  2021-06-28@16:28:42-0400  2021-06-28@16:29:13-0400  31s       main  system
```

Easier to reproduce after #7221

Initially reported in 6.6.0 and still happening on master
