### ISSUE TITLE
Still seeing resources with version: every getting skipped

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse#736]
# Bug Report

Follow up to #666 and #563

We're running 2.4.0.

What I saw this morning, Job starts multiple copies of itself; A, B, C, and D. In that order.

The jobs finished in A, C, D, B order. The next job that depends on that resource (which is `version: every`) did not run with resource version B.

**Comment by joonas** [comment]
I'm also seeing this behavior on my end on the [pullrequest-resource](https://github.com/jtarchie/pullrequest-resource/), currently running Concourse 2.4.0

**Comment by vito** [comment]
So this is a tricky one. The semantics for `version: every` coming from a job whose builds run in parallel are complicated by how the `passed` constraints work with `version: every`. See https://github.com/concourse/concourse/issues/358#issuecomment-207827612

tl;dr: `passed` constraints allow it to skip versions, otherwise when a bad version enters the mix, all downstream jobs can no longer run.

The scheduling for the second job would have to know that a build is in-flight for the ideal next version, and know to wait for it to finish before determining the inputs.

**Comment by oppegard** [comment]
Our team also makes heavy use of the [pullrequest-resource](https://github.com/jtarchie/pullrequest-resource/), and reliably running all `passed` versions of a PR in downstream jobs is important. As I currently understand it, we need to set `serial: true` or `max_in_flight: 1` to ensure all PRs make it through a pipeline?

**Comment by vito** [comment]
Possible workaround:

Have each job do a `put` to an otherwise-unused `time` resource. Then thread that through the subsequent jobs with `trigger: true` and a `passed` constraint. Do this for each job. This would make it so there's always a newer version once the build completes.

e.g.:

```yaml
resources:
- name: my-pr
  type: pr
  source: {...}

- name: dummy-time
  type: time
  source: {interval: 24h} # doesn't matter, but something has to be there

jobs:
- name: job-1
  plan:
  - get: my-pr
    trigger: true
  - task: test-pr
    # ...
  - put: dummy-time

- name: job-2
  plan:
  - get: my-pr
    trigger: true
    passed: [job-1]
  - get: dummy-time
    trigger: true
    passed: [job-1]
  - # ...
  - put: dummy-time

- name: job-3
  plan:
  - get: my-pr
    trigger: true
    passed: [job-2]
  - get: dummy-time
    trigger: true
    passed: [job-2]
  - # ...
  - put: dummy-time
```

**Comment by thewoolleyman** [comment]
Hi @vito,

Is still an issue (and whether the above workaround is still required) when using the [pullrequest-resource](https://github.com/jtarchie/pullrequest-resource/), even though the mentioned problems with using `passed` and `every` together have been (I believe?) resolved by https://github.com/concourse/concourse/issues/358#issuecomment-207827612 ?

If so, could you please explain the details, and why the problem seems to be specific to [pullrequest-resource](https://github.com/jtarchie/pullrequest-resource/)?

My guess is that it is because the pullrequest-resource conflates two independent "versions" (PR numbers and SHAs) into a single "version", which breaks some of the concourse assumptions about how resources and versioning work.  It would be great to have you confirm or deny that, and if so, possibly explain why from your perspective.

Thanks!
-- Chad

**Comment by vito** [comment]
The problem is not specific to the PR resource. This issue is still open. The linked comment explains why this issue exists; it's a fundamental issue with `passed` and `every` together, where it's either broken this way or broken in the way that comment mentioned, and I think this way is the less broken of the two (as the alternative is a deadlocked pipeline).

**Comment by thewoolleyman** [comment]
@vito OK, thanks.  I think understand now.  Here is your statement from above, but with my clarifications in brackets - please let me know if it is correct (and hopefully it helps others understand the crux of this complex issue.

> tl;dr: passed constraints allow it to skip versions, otherwise when a bad version enters the mix, all downstream jobs can no longer run.
>
> The scheduling for the second *[downstream]* job would have to know that a build *[for an upstream job, on which it has a `passed` constraint]* is in-flight for ~~the ideal next version~~ *[the downstream job's sequentially next unbuilt version, based on its `every` constraint]*, and know to wait for ~~it~~ *[the upstream job's build for the version]* to finish *[with a pass/fail]* before determining ~~the inputs~~ *[whether or not it should trigger the downstream job for the version]*.

But, with respect to the pullrequest-resource specifically:

* The only reason we need to use "every" is because the pullrequest-resource conflates two independent "versions" (PR# and SHA) into one emitted "version".  If we want the *latest* (**not** every) SHA to be built for *every* PR#.
* If we only used the standard concourse git resource, which only emits one "version" (a SHA), in conjunction with a pipeline-per-pr# (i.e. pipeline-per-branch) approach as you discuss [here](https://github.com/concourse/concourse/issues/534#issuecomment-235650894), we would not need to use "every", because the separate pipeline-per-pr# (each with separate standard git resources defined for the PRs' branches) would ensure the *latest* SHA for the per-branch git resource would always be run (**not** every SHA, which is fine because we only care about running the latest commit on the PR's branch).
* Thus, since we wouldn't need to use "every", we would not be exposed to this issue.

Correct?  

If not, then please explain in more detail, because I'm still confused :)

Thanks,
-- Chad

**Comment by thewoolleyman** [comment]
@vito Also, I tried out the workaround above.

It doesn't appear to work if you ever have more than one entry in a `passed:` array.

E.g., if you try this, `job-3` hang and never start with the message **"waiting for a suitable set of input versions\n dummy-time - no versions satisfy passed constraints"**

```
resources:
- name: my-pr
  type: pr
  source: {...}

- name: dummy-time
  type: time
  source: {interval: 24h} # doesn't matter, but something has to be there

jobs:
- name: job-1
  plan:
  - get: my-pr
    version: every
    trigger: true
  - task: test-pr
    # ...
  - put: dummy-time

- name: job-2a
  plan:
  - get: my-pr
    trigger: true
    passed: [job-1]
  - get: dummy-time
    version: every
    trigger: true
    passed: [job-1]
  - # ...
  - put: dummy-time

- name: job-2b
  plan:
  - get: my-pr
    trigger: true
    passed: [job-1]
  - get: dummy-time
    version: every
    trigger: true
    passed: [job-1]
  - # ...
  - put: dummy-time

- name: job-3
  plan:
  - get: my-pr
    trigger: true
    passed: [job-2a, job-2b]
  - get: dummy-time
    version: every
    trigger: true
    passed: [job-2a, job-2b]
  - # ...
  - put: dummy-time
```

Is this expected (and thus the workaround doesn't work in this situation), or do I have something wrong?

Thanks,
-- Chad

**Comment by tushar-dadlani** [comment]
+1 We are also seeing this issue at our end. We are going to try the workaround now.

**Comment by vito** [comment]
@nazrhom (and, well, everyone) To be honest we're starting to see `version: every` + `passed:` as a bit of a mis-feature. By saying "run with every version" but also "oh wait but only the ones that made it through this job" it can be seen as kind of an oxymoron, and from that perspective the the (mis)behavior described in this issue is somewhat unsurprising. It's also not super surprising that the workaround has led to other things that need working-around. :slightly_smiling_face: I don't see why having multiple entries in `passed` would break it any more or any less than with a single entry, fwiw.

It seems like what y'all area really trying to do is have a full pipeline run for every version. I think that's actually a challenge that can be met by a concept similar to spaces (#1707). We've got a new plan laid out in https://github.com/concourse/rfcs/pull/1#issuecomment-477749314 that should make this kind of thing possible. At that point we might deprecate configuring both `version: every` and `passed:` at the same time and encourage users to adopt the new pattern.

**Comment by nazrhom** [comment]
@vito thanks, will look into the rfcs. I did some more digging and the issue I am experiencing does not seem to be related to fan-in/out as I can reproduce the issue even with a setup like:

```
jobs:
- name: job-1
  plan:
  - get: my-pr
    version: every
    trigger: true
  - task: test-pr
    # ...
  - put: dummy-time

- name: job-2
  plan:
  - get: my-pr
    trigger: true
    passed: [job-1]
  - get: dummy-time
    version: every
    trigger: true
    passed: [job-1]
  - # ...
  - put: dummy-time

- name: job-3
  plan:
  - get: my-pr
    trigger: true
    passed: [job-2]
  - get: dummy-time
    version: every
    trigger: true
    passed: [job-2]
  - # ...
  - put: dummy-time
```

I have a question on the (current) expected semantics here: `job-2` will `get` a certain version of `dummy-time` that was `put` by `job-1`; after it does its thing it will `put` a new version of `dummy-time`. Doesn't this create 2 versions of `dummy-time` that have passed `job-2` (the one that `job-2` `get`s and the one it `put`s?) that can potentially both trigger `job-3`?
