### ISSUE TITLE
Fly cli - error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by wardourdigital** [concourse/concourse#7366]
## Summary

This may be more of a help request, so apologies in advance.

In my local Mac I have pulled the concourse tutorial repo.

When I attempt to set a pipeline from my local environment to my target. I get the error:

```
error: invalid character '<' looking for beginning of value
```

## Current Setup

**Target: **
Linux CentOS7
Concourse 7.4.0
Fly Cli 7.4.0

**Local**
Mac mini M1
OS X 11.4
Fly Cli 7.4.0

## Steps to reproduce

Attempt to set the pipeline for the config `pipeline.yml`:

```yml
---
jobs:
  - name: job-hello-world
    plan:
    - config:
        image_resource:
          name: ""
          source:
            repository: busybox
          type: docker-image
        platform: linux
        run:
          args:
          - eat my hell o world
          path: echo
      task: hello-world
    public: true
```

Running:

```
fly -t {target-name} set-pipeline -c pipeline.yml -p basic-pipeline
```

## Expected results

Confirmation that the pipeline is set

## Actual results

```shell
pipeline2
jobs:
  job job-hello-world has been added:
+ name: job-hello-world
+ plan:
+ - config:
+     image_resource:
+       name: ""
+       source:
+         repository: busybox
+       type: docker-image
+     platform: linux
+     run:
+       args:
+       - eat my hell o world
+       path: echo
+   task: hello-world
+ public: true
  
pipeline name: basic-pipeline2

apply configuration? [yN]: y
```

And results in:

```
error: invalid character '<' looking for beginning of value
```

## Additional context

I have copied the same config file directly in the the target environment and ran:

```
fly -t {target-name} set-pipeline -c pipeline.yml -p basic-pipeline
```

It successfully sets the pipeline and I can execute the build from within the web ui.

There are no clues as to why or what is causing the error on my Mac. Google searches have not been very helpful.

I have also run

```
fly validate-pipeline --config pipeline.yml
```

Result is: `look good`

## Triaging info

* Concourse version: 7.4.0
* Did this used to work? This is a first time setup
