### ISSUE TITLE
Pipeline with across step interpolating the value from load_var does not work

### ISSUE THREAD

**Issue by deepakmohanakrishnan1984** [concourse/concourse#7387]
## Summary

When a pipeline job contains an `across` step configured to interpolate its value from a `load_var` is failing during `set-pipeline` step.

## Steps to reproduce

1. Configure `pipeline.yml` containing across step interpolating iterable value from `load_var` step from a file.

 ```
resources:
- name: hosts
   type: mock
   source:
    create_files:
     hosts.json: |
       ["github.com", "concourse-ci.org"]

jobs:
- name: bulk-nc-connectivity-test
   plan:
   - get: hosts
   - load_var: hostnames
     file: hosts/hosts.json
   - across:
     - var: host
       values: ((.:hostnames))
     task: connectivity-tests
     config:
       platform: linux
       image_resource:
         type: docker-image
         source: {repository: alpine}
       run:
         path: nc
         args: [-zvw2, ((.:host)), "443"]
```

2. Create pipeline using `fly set-pipeline` (reports a marshalling error)

```
> fly -t ci sp -p bulk-connectivity-test -c pipeline.yml

error: error unmarshaling JSON: while decoding JSON: malformed across step: json: cannot unmarshal string into Go struct field AcrossStep.across of type []interface {}
```

3. `across` step with a static iterable value.

```
jobs:
- name: bulk-nc-connectivity-test
  plan:
  - across:
    - var: host
      values: ["github.com", "concourse-ci.org"]
    task: connectivity-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: nc
        args: [-zvw2, ((.:host)), "443"]
```

## Expected results

The `fly set-pipeline` for the pipeline definition mentioned in the step 1 should create and apply the configuration successfully.

## Actual results

```
error: error unmarshaling JSON: while decoding JSON: malformed across step: json: cannot unmarshal string into Go struct field AcrossStep.across of type []interface {}
```

## Additional context

Using mock resource to show the resource generating the file containing the list of values to be interpolated by across step. I have been referring this documentation https://concourse-ci.org/jobs.html#schema.step.across and also seems like my sample pipeline looks similar to the example provided in the documentation.

## Triaging info

* Concourse version: v6.7.6
* Browser (if applicable): NA
* Did this used to work? first time trying this feature.
