### ISSUE TITLE
/etc/resolv.conf not correctly configured in containerd containers after upgrading to 7.4 from 7.3

### ISSUE THREAD

**Issue by waweber** [concourse/concourse#7411]
## Summary

Image check for git fails with

```
fetching concourse/git-resource@sha256:14542abafcbe5de4faa403fb472a3dae2a0d6e4d3ac735c580a3957cdc162c85

ERRO[0000] download failed: initialize transport: Get "https://index.docker.io/v2/": dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:49105->[::1]:53: read: connection refused 
```

after upgrading to 7.4 from 7.3, on CentOS 7.

## Steps to reproduce

1. Be on CentOS 7 running Docker daemon 20.10.8 with kernel 5.4.125-1.el7.elrepo.x86_64
2. Install Concourse 7.3 with the following worker env vars:

```
      CONCOURSE_RUNTIME: containerd
      CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE: "true"
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
```

3. Upload a test pipeline and see if it can fetch the git resource image
4. Update to Concourse 7.4
5. See that the pipeline fails with the given error message.

## Expected results

The worker should be able to fetch the image for the resource.

## Actual results

The image fetch fails with the given dns-related error.

## Additional context

IPv6 is not enabled on the host I tested on, but I did put concourse in a network with an IPv6 subnet assigned and it still attempts to connect to [::1]:53. I also tried with both the ubuntu and alpine base images.

## Triaging info

* Concourse version:
* Browser (if applicable): N/A
* Did this used to work? Yes, there appear to be no issues running 7.4 on a different host running CentOS 8.

**Comment by fgerling** [comment]
I have similar issues. 
It seems that the resource checker containers can't resolve anymore. 

I run concourse via docker-compose on docker:
* `Docker version 19.03.13, build 4484c46d9d`
* concourse image: `concourse/concourse:7.4`

On 7.3 and 7.4 the resolv.conf looks the same:
```
$ docker-compose exec concourse bash
root@e0cc25f9f699:/# cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
```
and both versions can resolve `github.com` for example:
```
root@e0cc25f9f699:/# getent hosts github.com
140.82.121.4    github.com
```

Despite the web container being able to resolve correctly on 7.4, the resources aren't:
![image](https://user-images.githubusercontent.com/22368040/129867521-17c5ecfe-6232-432c-860d-165ae1c77a8d.png)


@waweber could you enter your 7.4 container and check if you can resolve something: 
`getent hosts github.com` ? You could also install iputils-ping and ping a host from inside the container. 
I would like to be check if the problem is the resolf.con file or something else.

**Comment by waweber** [comment]
@fgerling I'll have to spin it up again when I get the time. But, the resolv.conf were definitely different between versions for me. Names failed to resolve in a 7.4 worker container, until I manually added a nameserver directive to the resolv.conf. I think our issues might be different, since the error message I see seem to suggest it can't connect to a name server at all

**Comment by fgerling** [comment]
@waweber another option you could try is to change the names of your env variables to:
```
CONCOURSE_WORKER_RUNTIME: containerd
CONCOURSE_WORKER_CONTAINERD_DNS_PROXY_ENABLE: "true"
```
Notice `WORKER` after `CONCOURSE_`.

I was not able to found documentation about it. I greped my way thru the sources and found some [docker-compose](https://concourse-ci.org/docker-compose.yml) files using this environment variable format.

**Comment by maestrow** [comment]
As a workaround I can offer this config settings, that fix this DNS issue:
```
CONCOURSE_RUNTIME=containerd
CONCOURSE_CONTAINERD_EXTERNAL_IP=192.168.1.106
CONCOURSE_CONTAINERD_DNS_SERVER=192.168.1.1
CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS=true
CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE=true
```

192.168.1.106 (worker IP) and 192.168.1.1 (DNS IP) is just an example of addresses in local network.

**Comment by taylorsilva** [comment]
For everyone that's commented so far, are you all on centos 7, kernel 5+?

I tried to reproduce with @waweber's steps but was unsuccessful. I followed this page to install kernel 5.x: https://computingforgeeks.com/install-linux-kernel-5-on-centos-7/
I ended up with `5.14.0-1.el7.elrepo.x86_64`. I was using a vagrant box to create the vm:

```
Vagrant.configure(2) do |config|
  config.vm.disk :disk, name: "main", size: '20GB'
  config.ssh.forward_agent = true
  config.vm.box = 'generic/centos7'
  config.vm.boot_timeout = 420

  config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 6
  end
end
```

I used this pipeline to try and recreate the issue:
```yaml
---
resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/docs

jobs:
- name: job
  public: true
  plan:
  - get: repo
  - task: list-files
    config:
      inputs:
        - name: repo
      platform: linux
      image_resource:
        type: mock
        source: { mirror_self: true }
      run:
        path: ls
        args: ["-la", "./repo"]
```

but triggering the job or checking the resource were successful, on both 7.3 and 7.4 of concourse.

I used the quickstart command to bring up concourse, adding the DNS_ENABLE flag:
```yaml
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:7.4
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: tutorial
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_WORKER_CONTAINERD_DNS_PROXY_ENABLE: "true"
      CONCOURSE_WORKER_RUNTIME: "containerd"
```

I'm looking for any new info or suggestions on how I can reproduce this.
