### ISSUE TITLE
"waiting for worker" output when resource type not defined

### ISSUE THREAD

**Issue by jimbo459** [concourse/concourse#7467]
## Summary

When a resource has been defined, using a type which has not been defined there is no clear error output. Instead, the job hangs endlessly with the following output: 
```
no suitable workers found, waiting for worker...
```

## Steps to reproduce

With the below example a custom resource of `slack-notification` has been used, but the `resource_type` not defined. This will result in the job outputting `waiting for worker`

```
resources:
- name: slack-notification
  type: slack-notification
  icon: bell-ring
  source:
    url: ((slack.webhook))

jobs:
- name: slack-test
  put: slack-cryo-notification
  params:
    text: |
      Test Output
```

## Expected results

Error output to state that the resource_type of `slack-notification` has not been defined. This ideally would be shown as an error when attempting to set the pipeline.

## Actual results

No error setting pipeline, and task hangs with message `no suitable workers found, waiting for worker...`

## Triaging info

* Concourse version: v7.4.0
* Browser (if applicable): Chrome
* Did this used to work?: Not encountered this before.
