### ISSUE TITLE
Wrong image tag (registry-image) used after being updated

### ISSUE THREAD

**Issue by rjinskidepop** [concourse/concourse#7468]
## Summary

In production we were experiencing situations where our pipelines would fail after we updated the relevant tags on a registry-image resource. We were deleting and re-creating the pipeline to resolve the issue but started to investigate why. 

## Steps to reproduce

We have tested these steps in our cluster, but also on a local, fresh docker-compose (concourse-docker) cluster. The commit SHA's are correct at time of writing, but, may not be the latest (version_depth=10) when this is used. The purpose of the commit SHA's it to trigger the pipeline when we update it.

- Set pipeline with the below configuration
```
resources:
  - name: image
    type: registry-image
    source: { repository: golang, tag: "1.16" }

  - name: git
    type: git
    source:
      uri: https://github.com/concourse/concourse
      branch: master
      version_depth: 10

jobs:
  - name: use-image
    plan:
      - in_parallel:
          - get: image
          - get: git
            trigger: true
            version: { ref: 1e24cfceeefd388d8c993ab9b26c71d05642579a}
      - task: task
        image: image
        config:
          platform: linux
          run:
            path: go
            args: ["version"]
``` 

- unpause and await build 1 to run
- update the pipeline, with a new golang image (1.13) and a new commit ref to cause the job to run
```
resources:
  - name: image
    type: registry-image
    source: { repository: golang, tag: "1.13" }

  - name: git
    type: git
    source:
      uri: https://github.com/concourse/concourse
      branch: master
      version_depth: 10

jobs:
  - name: use-image
    plan:
      - in_parallel:
          - get: image
          - get: git
            trigger: true
            version: { ref: 212509f7c8fd705f9dd7a26b41638ddfd8f744ba}
      - task: task
        image: image
        config:
          platform: linux
          run:
            path: go
            args: ["version"]

```

## Expected results

Build 2 is run with golang image 1.13

## Actual results

Build 2 is run with golang image 1.16

## Additional context

![image](https://user-images.githubusercontent.com/77615995/130987877-f6ae96da-54d0-419d-9005-7479fc7e871e.png)

![image](https://user-images.githubusercontent.com/77615995/130988011-0659ad9d-dcde-4a37-98fd-7ab5a3d13334.png)

## Triaging info

* Concourse version: v7.4.0 (concourse-docker)
* Concourse version: v7.3.2 (production)

We have tried this with pr-resources instead of git and AWS ECR images instead of GoLang in docker hub and experienced the same behaviour.
