### ISSUE TITLE
Changing the repository of a resource_type tries to download the same hash

### ISSUE THREAD

**Issue by Mike-Dax** [concourse/concourse#7488]
## Summary

Using a resource type, in our case `pix4d/cogito` we found a bug, and created a fork to fix it. During testing I switched the repository to our fork. I expected concourse to refetch, but it seems to be caching the 'latest' hash of the wrong repository.

Old resource type:
![image](https://user-images.githubusercontent.com/13504878/131450160-ae4ef173-e849-4864-9aad-a4de97945c4f.png)

New resource type:
![image](https://user-images.githubusercontent.com/13504878/131450188-78e3c3c3-4c39-4458-9dbf-8c282c7d15c5.png)

```
selected worker: worker-ubuntu-vm

fetching electricui/cogito@sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852

ERRO[0002] download failed: get image: GET https://index.docker.io/v2/electricui/cogito/manifests/sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852: MANIFEST_UNKNOWN: manifest unknown; map[Name:electricui/cogito Revision:sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852] 
```

## Steps to reproduce

Download concourse, setup a pipeline with 

```
resource_types:
- name: cogito
  type: registry-image
  check_every: 12h
  source:
    repository: pix4d/cogito

resources:
- name: gh-status
  type: cogito
  check_every: 1h
  source:
    owner: xxx
    repo: xxx
    access_token: xxx
```

Run the pipeline, then swap out the repository to 

```
resource_types:
- name: cogito
  type: registry-image
  check_every: 12h
  source:
    repository: electricui/cogito

resources:
- name: gh-status
  type: cogito
  check_every: 1h
  source:
    owner: xxx
    repo: xxx
    access_token: xxx
```

It will try to grab the same hash at the wrong repository.

## Expected results

```
selected worker: worker-ubuntu-vm

fetching electricui/cogito@sha256:395a3bf790f4a63dbf30204d04ce92b379bb7585fb5ef89b7d48de544ff80a81

```

## Actual results

```
selected worker: worker-ubuntu-vm

fetching electricui/cogito@sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852

ERRO[0002] download failed: get image: GET https://index.docker.io/v2/electricui/cogito/manifests/sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852: MANIFEST_UNKNOWN: manifest unknown; map[Name:electricui/cogito Revision:sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852] 
```

## Additional context

I've tried `clear-resource-cache`, but it says `0 caches removed` on my Mac, and `_ caches removed` on Linux, which seems like an additional bug?

## Triaging info

* Concourse version: v7.4.0
* Browser (if applicable): Firefox
* Did this used to work? No idea.

**Comment by taylorsilva** [comment]
Some assumptions I made since you didn't provide a complete pipeline:

- `cogito` is a resource type
- `gh-status`, based on `cogito`, is a resource
- Unsure what your job looks like, but I assume it has at least one `put` step for the `gh-status` resource.

With those assumptions in mind, I made this pipeline to try and reproduce the issue locally since I didn't feel like setting up auth stuff:

```yaml
resource_types:
- name: mock
  type: registry-image
  check_every: 12h
  source:
    repository: concourse/mock-resource
    # repository: cirocosta/mock-resource

resources:
- name: gh-status
  type: mock
  check_every: 1h
  source:
    force_version: hello

jobs:
- name: status
  plan:
  - put: gh-status
    params:
      version: hi
```

I failed to reproduce the issue based on `master`. I then tried reproducing on 7.4.0 and got the same error as you!

I think #7176 may have fixed this. That PR will be out soon in 7.5.0 (#7493).
