### ISSUE TITLE
Failed auto triggers for downstream jobs

### ISSUE THREAD

**Issue by kirederik** [concourse/concourse#7518]
Issue created based on the discussion in https://github.com/concourse/concourse/discussions/7012

We are seeing a similar issue as #6988 with builds not triggering with new versions of the resource (specifically the telia-oss/git-pr-resource), unless the version is pinned to a particular version -- which automatically triggers the pending jobs. What is particularly interesting is that it does trigger _some_ jobs, but not all of them.

[This is our pipeline yaml](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/blob/a79c9a267aa4ae4756bf729c1e1b007512cf7998/ci/pipelines/backup-and-restore-sdk-release/pipeline.yml#L271-L274). The resulting pipeline can be seen [here](https://ci.cryo.cf-app.com/teams/bosh-backup-restore/pipelines/backup-and-restore-sdk-release).

https://user-images.githubusercontent.com/201163/132332331-c9bffa8e-f79c-4b76-b3ab-35ad6166dcb4.mov

**Comment by taylorsilva** [comment]
We tried to reproduce this using the [mock resource](https://github.com/concourse/mock-resource) with three different pipeline layouts.

The first was a simple job-one to job-two pipeline. We assume the issue may be if the resource emits multiple versions close together, so we had the mock resource emit 3 versions in quick succession:
```
fly -t l cr -r test/some-release -a -f version:mock-1
fly -t l cr -r test/some-release -a -f version:mock-2
fly -t l cr -r test/some-release -a -f version:mock-3
```
We saw all versions pass through the two jobs though. Here's the pipeline we used:
```yaml
--- # attempt 1
resources:
- name: some-release
  type: mock

jobs:
- name: job-one
  plan:
  - get: some-release
    trigger: true
    version: every

- name: job-two
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
```

---

Our second attempt kinda copied part of your pipeline, where you have five jobs fanning into one job. We did the same thing of having the mock resource create multiple versions in quick succession. The result was the same as the first pipeline though; all versions passed through all jobs, including the downstream job-two.

```yaml
--- # attempt 2
resources:
- name: some-release
  type: mock

jobs:
- name: job-a
  plan:
  - get: some-release
    trigger: true
    version: every
- name: job-b
  plan:
  - get: some-release
    trigger: true
    version: every
- name: job-c
  plan:
  - get: some-release
    trigger: true
    version: every
- name: job-d
  plan:
  - get: some-release
    trigger: true
    version: every
- name: job-e
  plan:
  - get: some-release
    trigger: true
    version: every

- name: job-two
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-a,job-b,job-c,job-d,job-e]
```
---

Our third attempt we added a job before the a-e jobs. So the resource would fan in then fan out:

```yaml
--- # attempt 3
resources:
- name: some-release
  type: mock

jobs:
- name: job-one
  plan:
  - get: some-release
    trigger: true
    version: every

- name: job-a
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-b
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-c
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-d
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-e
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]

- name: job-two
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-a,job-b,job-c,job-d,job-e]
```

Same process as the other two, we created multiple versions in quick succession. They passed through all jobs as expected though, no version was skipped by any of the jobs.

---

At this point we're not too sure what else to try here. Are there any other behaviours or patterns around this issue that you've noticed?

**Comment by fejnartal** [comment]
Hi @taylorsilva
I work with @kirederik

I wanted to highlight that we use set_pipeline: self in many of these pipelines.
We usually require any other job to wait until the self setting job has finished (using a passed: [] condition)

Also, many of our jobs are long-running processes which means that it is very frequent for the teliaoss resource to detect several new versions before an old one has finished.

I hope these clarifications help you reproduce this issue.
Thanks! :)

**Comment by taylorsilva** [comment]
One thing we noticed was that all your "heavy" jobs have `serial: true` set. We updated our third attempt to include that. We also slowed down one of the jobs in the middle to see if it's slowness would cause a version to not make it to the final `job-two`. This did not happen, every version got through all jobs of the pipeline.

```yaml
--- # attempt 4
resources:
- name: some-release
  type: mock
  source:
    no_initial_version: true

jobs:
- name: job-one
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every

- name: job-a
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-b
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-c
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-d
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
- name: job-e
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-one]
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: mock
        source: {mirror_self: true}
      run:
        path: sh
        args:
        - -c
        - |
          sleep 2m

- name: job-two
  serial: true
  plan:
  - get: some-release
    trigger: true
    version: every
    passed: [job-a,job-b,job-c,job-d,job-e]
```
