### ISSUE TITLE
on_error hook executes even when all steps/tasks in the job are successful

### ISSUE THREAD

**Issue by mathiasjoella** [concourse/concourse#7532]
See screenshot below:
<img width="1680" alt="Screen Shot 2021-09-09 at 2 33 43 PM" src="https://user-images.githubusercontent.com/15704681/132766002-078d03af-ee44-46f3-ad7d-98429495359b.png">

The job `fetch-next-pipeline-version` has 3 hooks: `on_abort`, `on_failure` and `on_error`. The `on_error` hook gets executed even when the overall job succeeds. This happens only when there are some implicit retries in one or more of the steps in the job. 
For example: see the `get: pipeline-config-semver-next` step, it has 2 retries:
```
selected worker: worker-sc1-01-vc26-10.78.228.124-RxwCG2Tbb
selected worker: worker-sc1-01-vc26-10.78.228.124-RxwCG2Tbb
```
The expected behavior would be to not call `on_error` when any implicit retries have succeeded.
Concourse version: 6.7.7

**Comment by taylorsilva** [comment]
Do you have `CONCOURSE_ENABLE_RERUN_WHEN_WORKER_DISAPPEARS` enabled?

**Comment by taylorsilva** [comment]
Can you share the pipeline definition or at least the job plan for this build? Looking at the code I don't see any way that the `on_error` could ever know about an error occurring in another step:

https://github.com/concourse/concourse/blob/fbf4729be0b2d8e508e0eccef3ed98372ef4e25f/atc/exec/on_error.go#L25-L41

**Comment by taylorsilva** [comment]
We have some other theories as to how this may be happening after looking at more code. When you open the `set_pipeline` step that the `on_error` is for, what's the output for that show for the specific build you screenshotted?

**Comment by mathiasjoella** [comment]
@evanchaoli could you please respond to the question about `CONCOURSE_ENABLE_RERUN_WHEN_WORKER_DISAPPEARS`?

@taylorsilva the `on_error` is actually for the entire job, not just for the `set_pipeline` step. This is the job plan:

```
- name: fetch-next-pipeline-version
  public: true
  plan:
  - in_parallel:
    - get: pipeline-config-semver-next
      trigger: true
    - get: vmc-dp-git
      trigger: true
    - get: service-metadata-git

  - load_var: new-version
    reveal: true
    file: pipeline-config-semver-next/version

    # Walks a directory recursively and renders all Jinja2 templates. Rendered
    # templates are created in the same directory as the original template without
    # the .j2 extension.
  - task: render-all-jinja2-templates
    file: vmc-dp-git/devops/concourse/templates/common-tasks/render/task-render-jinja2-template.yml
    input_mapping:
      vmc-dp-git: vmc-dp-git
      vmc-service-metadata: service-metadata-git
    output_mapping:
      vmc-dp-git: vmc-dp-git
    params:
      template_dir_path: vmc-dp-git/devops/concourse/templates/atlas/atlas-service-starter/pipelines/tf
      var_files:
        - vmc-dp-git/devops/concourse/templates/atlas/common-template-vars.yml
        - vmc-dp-git/devops/concourse/templates/atlas/atlas-service-starter/template-vars.yml
        - vmc-service-metadata/metadata/((gitlab-path))/((service-name))/service-vars.yml

  - in_parallel:
    - set_pipeline: tf-pipeline-manager # name of the pipeline
      # pipeline config file
      file: vmc-dp-git/devops/concourse/templates/atlas/atlas-service-starter/pipelines/tf/tf-pipeline-manager.yml
      vars:
        version: ((.:new-version))
        gitlab-path: ((gitlab-path))
        service-name: ((service-name))
        project-group: ((project-group))
      var_files:
        # service specific variables
        - service-metadata-git/metadata/((gitlab-path))/((service-name))/service-vars.yml
        # common template variables
        - vmc-dp-git/devops/concourse/templates/atlas/atlas-service-starter/template-vars.yml
        - vmc-dp-git/devops/concourse/templates/atlas/common-template-vars.yml

  <<: *send-notification
  ```
  
  `send-notification` is defined as follows:
  
  ```
  definitions:
    notification: &send-notification
      on_abort:
        put: oncall-slack-channel
        inputs: detect
        params:
          text: |
            <@((oncall-user))> *The <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_TEAM_NAME-$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME - $BUILD_ID> job aborted!*
      on_error:
        put: oncall-slack-channel
        inputs: detect
        params:
          text: |
            <@((oncall-user))> *The <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_TEAM_NAME-$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME - $BUILD_ID> job errored!*
      on_failure:
        put: oncall-slack-channel
        inputs: detect
        params:
          text: |
            <@((oncall-user))> *The <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_TEAM_NAME-$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME - $BUILD_ID> job failed!*
```
