### ISSUE TITLE
nested across step display bug

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#7564]
## Summary

When nesting across steps inside across steps, the steps inside the nested across step do not get rendered in the UI, and their output cannot be seen. Based on my testing, the nested steps are still running, and properly report error/success statuses up to the overall build, so it seems like this is just a display issue.

Worked around this by using an additional variable in the across matrix, since that was probably more appropriate for my case, but maybe there's a use case that makes sense for this?

## Steps to reproduce

1. Fly a pipeline that has a job with a nested across step. Here's a pretty contrived example, when I found the issue, the pipeline was a little less apparent that there was an across inside an across:

```
groups:
- name: main
  jobs:
  - unit-tests

jobs:
- name: unit-tests
  plan:
  - across:
    - var: release
      values:
      - {name: cf-networking, db-types: [mysql, postgres]}
      - {name: silk,          db-types: [postgres]}
      max_in_flight: all
    do:
    - task: echo-release
      config:
        image_resource:
          type: registry-image
          source: { repository: alpine }
        platform: linux
        run:
          path: echo
          args:
          - ((.:release.name))
    - across:
      - var: db-type
        values: ((.:release.db-types))
        max_in_flight: all
      do:
      - task: echo-release-and-db-type
        config:
          image_resource:
            type: registry-image
            source: { repository: alpine }
          platform: linux
          run:
            path: echo
            args:
            - ((.:release.name)) on ((.:db-type))

resources: []
```

2. Run the pipeline
3. View the build and verify that the steps inside the nested across do not display in the UI

## Expected results

Either nested across steps should have their steps displayed.

## Actual results

The nested across step itself is displayed, but none of its variables, or sub-steps.

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by taylorsilva** [comment]
Can you explain why you needed to nest the across step inside another across step instead of declaring a second set of vars?

For example, in our pipeline we have this across step:
```yaml
 - across:
    - var: runtime
      values:
      - guardian
      - containerd
      max_in_flight: all
    - var: postgres-image
      values:
      - postgres-image
      - postgres-image-legacy
      max_in_flight: all
```
https://github.com/concourse/ci/blob/86a962a5e8a367502d66f19bbe036aee3028651d/pipelines/concourse.yml#L342-L352

Which then results in this across step:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/4583837/134071818-a32ca63f-1975-416d-a3e6-e7ff2501e6db.png">

Are you not able to achieve the same results with one across step? Why do you need to nest them?
