### ISSUE TITLE
across step retry-status bug

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#7565]
## Summary

When an across's nested step has attempts on it, the across gets marked as failed, if any of the attempts fail, rather than if all of them fail.

## Steps to reproduce

1. Fly this pipeline:
```
groups:
- name: main
  jobs:
  - across-with-retries

jobs:
- name: across-with-retries
  plan:
  - across:
    - var: i
      values: [1]
      max_in_flight: all
    do:
    - task: echo-release
      attempts: 3
      config:
        image_resource:
          type: registry-image
          source: { repository: bash }
        platform: linux
        run:
          path: bash
          args:
          - -c
          - |
            echo "Seeing if we're on an even second or odd"
            exit $(expr $(date +%s) % 2)
resources: []
```
2. Run the across-with-retries job a bunch of times
3. Look through the results until you see a job that had multiple attempts.

## Expected results

The `across` step should be marked as green/successful

## Actual results

The across step is incorrectly marked as red, while at the same time the pipeline is marked as green, and the nested step is marked as green (correctly).

## Triaging info

* Concourse version: 7.4.0
* Browser (if applicable):
* Did this used to work?
![Screen Shot 2021-09-17 at 2 43 50 PM](https://user-images.githubusercontent.com/7180882/133839129-7ad475ae-3f50-46fa-b4d8-254b49228667.png)
