### ISSUE TITLE
Outputs inside across task not working

### ISSUE THREAD

**Issue by rgroemmer** [concourse/concourse#7577]
## Summary

Currently i facing an issue with a task inside an across step, the task creates some files which i want to consume afterwards in another step.
But the output specified in the task config is getting ignored if it runs inside an across step.

## Steps to reproduce
Set outputs in a task inside of an across: 
```
  - across:
    - var: name
      values:
      - file1
      - file2
      - file3
    task: create-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: touch
        args: 
        - manifests/((.:name))
      outputs: 
      - name: manifests

  - task: list-file
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      inputs:
      - name: manifests
      run:
        path: ls
        args: 
        - manifests
```

## Expected results
`list-file` task should have access to the manifests directory as input.

## Actual results
concourse error: `input not found: manifests`

## Triaging info

* Concourse version: 
 - AppVersion: 7.2.0  
 - ChartVersion: concourse-15.1.0

**Comment by rgroemmer** [comment]
Short update from my side, i have a workaround for this with the use of `do` and across: 
```yaml
  - across:
    - var: name
      values:
      - file1
      - file2
      - file3
    do: 
    - task: create-file
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: {repository: busybox}
        run:
          path: touch
          args: 
          - manifests/((.:name))
        outputs: 
        - name: manifests
      on_success:
        put: kubectl-apply
        inputs:
        - manifests
        params:
          file: ./
```

**Comment by taylorsilva** [comment]
Adding some context. This is currently working as it was coded to: https://github.com/concourse/concourse/blob/21c25554757f69e26da17301f75e07616d1083bc/atc/exec/across_step.go#L125

Each across var has a local scope, where it inherits all the outputs from previous steps. None of the outputs made within an across step are passed back to the parent scope though. So any steps that run after an `across` step will not have any outputs from the `across` step available to them.

This question about outputs was never raised in the RFC: https://github.com/concourse/rfcs/pull/29

I think I've seen this same "bug" raised three times or so now. It seems like a thing people really want to do with the across step and it makes sense to me. It would make it more powerful to use if artifacts can be passed out of the across step. It might just be complicated to code up or something 🤷

**Comment by maxknee** [comment]
So we ran into this today.
We upgraded from 6.7 to 7.6 (i know, i know)
but given `put` step's inability to be `put: ((.:var-name))` we had put steps AFTER the completion of the across step and was wondering why it wasn't working properly

**Comment by suhlig** [comment]
I am having the same issue. `across`' usefulness is quite limited for tasks ("fan-out") if we cannot access the outputs afterwards ("fan-in"); at least per my current understanding.

I tried `put`ting the outputs as part of each task, but with `git` this creates a lot of unnecessary churn and with `S3` this is not practical (you'd have to have a separate resource for each file produced, unless I misunderstand).

**Comment by alenapetraki** [comment]
Also as far as I understand you cannot add any files into the existing artifacts
I guess all the inputs are kind of "readonly" within the 'across' step

I believe an ability to make changed in existing artifacts could be very useful as well

**Comment by alenapetraki** [comment]
any updates here? maybe someone could tell if this will be implemented at all?
thanks:)

**Comment by DJAlPee** [comment]
I have built a workaround for this, which seems to work (at least for our case):
```yml
jobs:
- name: build
  plan:
  - load_var: configs
    file: src/configs.json
    format: json
  - task: prepare-build
    file: src/tasks/prepare-build.yml
  - in_parallel:
    - across:
      - var: config
        values: ((.configs))
        max_in_flight: all
      do:
      - task: build-config
        file: src/tasks/build-config.yml
  - task: bundle-results
    file: src/tasks/bundle-results.yml
```
The folder for `outputs` (one per `build-config` execution) are "declared" in the `prepare-build` task (this job just executes a simple `echo`) outside of the `across` scope. Within the `build-config` task, the results of the build is copied into one of the proviously "declared" output folders. Within the `bundle-results` tasks, I can collect the content of all `output` folders and do whatever neccessary...

Only drawback:
The `prepare-build` task wastes time and resources just for creating folders for `ouputs` in a "global scope". It would be great to have a step, which just creates these output folders without any big overhead.
@taylorsilva This could be an approach for a "sustainable" solution, which adresses the use cases mentioned above.

**Comment by taylorsilva** [comment]
Interesting idea @DJAlPee! If this is working as you described then a way to save more time could be to use the `mock` resource to generate the output folders for you.

So your example could become:

```yaml
resources:
- name: output-folder
  type: mock

jobs:
- name: build
  plan:
  - get: output
    resource: output-folder
  # Can even use the resource to create multiple output folders
  - get: more-outputs
    resource: output-folder
  - load_var: configs
    file: src/configs.json
    format: json
  - in_parallel:
    - across:
      - var: config
        values: ((.configs))
        max_in_flight: all
      do:
      - task: build-config
        file: src/tasks/build-config.yml
  - task: bundle-results
    file: src/tasks/bundle-results.yml
```

This should be a lot faster than spinning up a `task` step since every worker will have the `mock` resource on it. I still want to try this myself to see if this works. There's a part in my brain that says this _shouldn't_ work, but maybe I'm wrong since you claim it does!

**Comment by DJAlPee** [comment]
Maybe worth to mention, that we are still on concourse v6
From a logical perspective, it makes sense to me, because all (most?) common programming languages are working in the same way... From an "inner" scope, I can access (and write) to variables of an "outer" scope, as long, as they declared as "writable".

Also important: In the `build-config` task, the folder is  declared in `inputs` AND `outputs`, so that updates in that folder are handed over to the next task

**Comment by DJAlPee** [comment]
It definitely works in our environment and I hope it's not because of concourse v6...

Maybe I should be more precise here regarding my config (I have simplified and "censored" it). I hope the following snippets are more helpful

pipeline.yml:
```yml
jobs:
- name: build
  plan:
  - get: src
  - get: execution-image
  - task: prepare-app
    image: execution-image
    config:
      platform: linux
       inputs:
      - name: src
      outputs:
      - name: src
      run:
        path: /bin/sh
        args:
        - '-ecl'
        - |+

          # Generate config.json and task yml files
  # Currently useless, because ((.configs)) is not used anywhere
  - load_var: configs
    file: src/configs.json
    format: json
  - task: prepare-build
     image: execution-image
     file: src/tasks/prepare-build.yml
  - in_parallel:
    - across:
      - var: config
        # values: ((.configs)) # Works only on concourse v7
        values: 
        - name: config1
        - name: config2
        - name: config3
        max_in_flight: all
      do:
      - task: build-config
        image: execution-image
        file: src/tasks/build-config.yml
  - task: bundle-results
    image: execution-image
    file: src/tasks/bundle-results.yml
```

prepare-build.yml:
```yml
platform: linux
inputs:
- name: src
outputs:
- name: build-config1-output
- name: build-config2-output
- name: build-config3-output
run:
  path: /bin/sh
  args:
  - '-ecl'
  - |

     echo "Provide output folders for build"
```

build-config.yml
```yml
platform: linux
inputs:
- name: src
- name: build-((.:config.name))-output
outputs:
- name: build-((.:config.name))-output
params:
  CONFIG: ((.:config.name))
run:
  path: /bin/sh
  args:
  - '-ecl'
  - |

    # Do the build
    rsync -qa "build/" "../build-((.:config.name))-output/((.:config.name))"
```

bundle-results.yml:
```yml
platform: linux
inputs:
- name: src
- name: build-config1-output
- name: build-config2-output
- name: build-config3-output
run:
  path: /bin/sh
  args:
  - '-ecl'
  - |

     src/tasks/scripts/bundle-dist.sh build-config1-output build-config2-output build-config3-output
```
