### ISSUE TITLE
Resources with dots `.` in their name don't render correctly in the UI

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#7608]
### Discussed in https://github.com/concourse/concourse/discussions/7607

<div type='discussions-op-text'>

<sup>Originally posted by **HemangLavana** September 28, 2021</sup>
![image](https://user-images.githubusercontent.com/516502/135144271-5e761597-84f8-4502-ab7d-4291c5cfb41e.png)

After upgrading to concourse 7.5.0 version, the UI seems messed up in chrome and firefox. I tried clearing the cookies and reloading but it didn't help. Any idea if something is not setup correctly on my end.</div>

## Reproduce
Set this pipeline then view it in the UI
```yaml
resources:
- name: a.resource.with.dots
  type: mock
- name: a-resource-with-dashes
  type: mock

jobs:
- name: job-with-dash
  plan:
  - get: a.resource.with.dots
  - get: a-resource-with-dashes
- name: job.with.dot
  plan:
  - get: a.resource.with.dots
  - get: a-resource-with-dashes
```
<img width="1864" alt="image" src="https://user-images.githubusercontent.com/4583837/135159052-90d0e400-f4b8-4ab3-85f6-4a1a6b8ca1ef.png">

Confirmed with `git bisect` that this is caused by #7438
