### ISSUE TITLE
variables from var_sources and load_var not being interpolated in load-var-step file: argument

### ISSUE THREAD

**Issue by tspotts** [concourse/concourse#7625]
## Summary

Neither vars using `((vars:var_name))` or `((.:var_name))` syntax get interpolated when specified to: 

```yaml
load_var: 
  file: <substitution not happening!>
```

## Steps to reproduce

$ fly set-pipeline...  --load-vars-from `var_creds.yml` 
```yaml
---

base_username1: bob
```

vars_pipeline.yml
```yaml
---

var_sources:
- name: vars
  type: dummy
  config:
    vars:
      base_username2: alice



jobs:

- name: vars-bug
  plan:

  - task: secrets-mock
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      run:
        path: sh
        args:
        - -xce
        - |
          echo '001' > secrets/bob
          echo '12345' > secrets/bob-001
          echo '002' > secrets/alice
          echo 'password' > secrets/alice-002
      outputs:
      - name: secrets

  - load_var: username1
    file: secrets/((base_username1))
    format: trim
  
  # # fails => file 'bob-((.:username1))' not found within artifact 'secrets'
  # # not getting substituted properly :(
  # - load_var: password1
  #   file: secrets/((base_username1))-((.:username1))
  #   format: trim

  # # fails => file '((vars:base_username2))' not found within artifact 'secrets'
  # # not getting substituted properly either :(
  # - load_var: username2
  #   file: secrets/((vars:base_username2))
  #   format: trim

  - task: debug-creds
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      inputs:
      - name: secrets
      run:
        path: sh
        args:
        - -xce
        - |
          echo ((base_username1)) # should be bob, OK
          echo ((.:username1)) # should be 001, OK
          cat secrets/((base_username1))-((.:username1))  # should be 12345, OK
          echo ((vars:base_username2))  # should be alice, OK - this is the correct syntax and its getting interpolated here
```

## Triaging info

* Concourse version: 7.5.0
* Browser (if applicable):
* Did this used to work? Unknown
