### ISSUE TITLE
Don't check identifiers for across step if they contain a var 

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#7660]
## Summary

This only applies to the identifier for the `task` and `set_pipeline` steps.

Given `set_pipeline`/`task` is used with the `across` step and its identifier contains a var from the `across` step: 
```yaml
resources:
- name: ci
  type: git
  source:
    uri: https://github.com/concourse/examples.git

jobs:
- name: job
  plan:
  - get: ci
  - across:
    - var: name
      values: ["hello-world", "time-triggered"]
    set_pipeline: ((.:name))    # uses var as identifier
    file: ci/pipelines/((.:name)).yml
```
```yaml
jobs:
- name: job
  plan:
  - across:
    - var: name
      values: ["hello-world", "hello-concourse"]
    task: running-((.:name))    # uses var as identifier
    config:
      platform: linux
      image_resource:
        type: mock
        source:
          mirror_self: true
      inputs:
        - name: ci
      run:
        path: echo
        args: ["((.:name))"]
```

I should not receive a warning about the identifier being invalid.
```
'((.:name))' is not a valid identifier
```

You can run the above pipelines, they will work as expected.

## Context

* RFC: concourse/rfcs#29
* Prior discussion: #7560
