### ISSUE TITLE
Resource type image tag update is not propagated correctly to existing resources

### ISSUE THREAD

**Issue by stepanstipl** [concourse/concourse#773]
Hi there!

# Bug Report

If tag is changed for resource_type, this is not propagated correctly to already existing resources and these will keep using old version for check step.

let's take for example:
```
resource_types:
- name: test-resource
  type: docker-image
  source:
    repository: xxx/yyy
    tag: 1.0
```

and you update the pipeline to:
```
resource_types:
- name: test-resource
  type: docker-image
  source:
    repository: xxx/yyy
    tag: 2.0
```

Existing resources with this resource_type will still keep using the 1.0 image for check step. Workaround that seems to fix this is to remove the resource from the pipeline definition and then add it again.

* Concourse version: 2.4.0
* Deployment type (BOSH/Docker/binary): Docker
