### ISSUE TITLE
With 'version: every' build for every version is scheduled in order one by one (not in parallel)

### ISSUE THREAD

**Issue by alenapetraki** [concourse/concourse#7799]
## Summary

I have a pretty simple pipeline with option `version: every` in `get` step
So If I have many new versions builds are scheduled one at a time after previous build is finished, which takes a lot of time to process all the versions

```yaml
resource_types:
  - name: custom_resource
    type: registry-image
    source:
      repository: docker.some.ru/custom_resource
      tag: master

resources:
  - name: task
    type: custom_resource
    check_every: 30s
    source:
      content_url: content:8020
      type: simple

jobs:
  - name: main
    plan:
      - get: task
        trigger: true
        version: every 
      - task: t1
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
          run:
            path: echo
            args: ["hello, world"]
```

## Steps to reproduce

I use [docker-compose](https://concourse-ci.org/docker-compose.yml) file from docs with image `concourse/concourse:7.6.0` (tried 7.4.1 as well)
I also have a custom resource which may produce multiple versions at a time. Versions are produced in correct order: [ previous_latest_version, other_versions... ]

## Expected results

Builds for every produced version are scheduled right after check and run in parallel 

## Actual results
For every received version one build at a time is scheduled and running
![image](https://user-images.githubusercontent.com/41673458/141767274-1a3e33cd-bc3a-4d8d-b51e-0c24d2d22fcc.png)
![image](https://user-images.githubusercontent.com/41673458/141767314-65ffa5ad-5399-4a7f-b36a-b63f74087b58.png)

## Triaging info

* Concourse version: concourse/concourse:7.6.0, 7.4.1
* Browser (if applicable): -
* Did this used to work? I am not sure, maybe this is not a bug but an intended  behaviour

-----

I am not really sure if it's a bug at all, maybe intended behaviour? Will be a huge help for me to clarify this as there is no info in docs. Thanks
