### ISSUE TITLE
Strange styles after upgrading from 7.5 to 7.6

### ISSUE THREAD

**Issue by chriseaton** [concourse/concourse#7823]
## Summary

For some reason the styles look a bit off when viewing a job. This occurred after switching out the docker container tag from `7.5.0` to `7.6.0`.

![image](https://user-images.githubusercontent.com/5247568/142670667-a16b9134-5f5b-4984-91da-d776bfd40a76.png)

## Steps to reproduce
Using docker-compose:
```
version: "3.8"
networks:
    apps:
        external:
            name: apps
services: 
    host:
        image: concourse/concourse:7.6.0
        command: web
        restart: always
        user: ":6901"
        expose:
            - 8080
            - 2222
        volumes: 
            - ./data/keys/concourse:/concourse-keys:ro
            - /etc/append/ca.pem:/certs/ca.pem:ro
        env_file: [./config/concourse.conf]
        networks:
            apps:
                aliases: [concourse.apps]
```

## Expected results
Text colors that are readable.

## Actual results
White text on yellow background.

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): Firefox 91.3.0, Chrome 96.0.4664.45
* Did this used to work? Yes, text was readable before.
