### ISSUE TITLE
set_pipeline step does not preserve variables

### ISSUE THREAD

**Issue by hstenzel** [concourse/concourse#7832]
## Summary

If I use a variable `((foo))` in a `set_pipeline` step, I can successfully deploy the pipeline with `fly set-pipeline` but not with the `set_pipeline` step.

## Steps to reproduce

Consider:

```yaml
- name: set-pipeline
  plan:
  - get: src
    trigger: true
  - set_pipeline: self
    file: src/.concourse/pipeline.yml
    vars:
      foo: ((foo))
```

When I deploy with `fly set-pipeline --var foo=bar` it works as expected. However it errors out when run because of the src trigger.

## Expected results

I'd expect the pipeline variables from `fly set-pipeline` to be persisted and reused by the `set_pipeline` step.

## Actual results

It works correctly when deployed with `fly set-pipeline` but fails when deployed with the `set_pipeline` step.

## Additional context

There is a workaround, it's just a bit clunky. The trick is to have the set_pipeline's vars.foo not use a Concourse variable. However, since it still has to be a variable of some kind, I used `gomplate` to have a concrete value. 

```yaml
- name: set-pipeline
  plan:
  - get: src
    trigger: true
  - task: pipeline-genesis # builds the pipeline by processing generating all concourse yaml with the gomplate template engine
    file: src/.concourse/genesis-task.yml # the pipeline template source
    params:
      FOO: {{ .Env.FOO }} # rendered concrete at build time
  - set_pipeline: self
    file: src/build/concourse/pipeline.yml # the gomplate processed pipelines
    vars:
      foo: {{ .Env.FOO }} # rendered concrete at build time
```

## Triaging info

* Concourse version: 7.5
* Browser (if applicable): n/a
* Did this used to work?: Unknown

**Comment by taylorsilva** [comment]
I don't think this is a bug, I think this is confusion about how vars work in a pipeline vs on your terminal with fly.

When you're doing `fly set-pipeline` you're passing in static vars where you're providing the var **name** and **value**.

In your pipeline you've provided the var **name** and set the value to `((foo))`. This does NOT refer to the value of the var `foo` that you passed in via fly.

Going back to your terminal, you did `fly sp` and passed in the var `foo`. Your Concourse server never got that var because fly locally interpolates that var into your pipeline. You can see that in the code here:
https://github.com/concourse/concourse/blob/da6b3b68bc56884498cce9be31f6231b1d384ef2/fly/commands/set_pipeline.go#L106

And you can do a `fly get-pipeline` and see in the returned yaml that there's no evidence of the var `foo` ever being in your pipeline. It was locally interpolated on your computer by fly, so the Concourse server never knew about it.

Back to your pipeline with `set_pipeline`, that is technically a valid pipeline but you're probably missing a few pieces to get it working. Concourse will look up vars in any credential managers that it's connected to. You can read more about how that happens here: https://concourse-ci.org/vars.html#var-syntax

You can see where we use vars from a credential manager in our `set_pipeline` steps here: 
https://github.com/concourse/ci/blob/798a442475958d58f845c6f8fc4240ed068ff335/pipelines/reconfigure.yml#L175-L178

The general idea behind `set_pipeline` is that you never need to use `fly set-pipeline` to instantiate your pipelines. You can check out how this idea fully works with this post: https://blog.concourse-ci.org/gitops-for-pipelines/

Hope that helps clear up your confusion. Please ask any other questions you have if it's still not clear what's happening with `set_pipeline`.

**Comment by hstenzel** [comment]
Thanks, it does make sense asto why. It matches with what I inferred based on observed behavior.

However, it does mean that there is no way to truly use variables with the `set_pipeline` step since the variables are dereferenced at `fly sp` time. In turn this makes it more difficult to construct reusable pipelines -- it's harder to have a single pipeline definition and instantiate it multiple times with with the only difference being the variables.

I understand the proposed workaround of using a credential manager and can see how that would work. As a first-class solution it is lacking because it means that to change a pipeline variable one must have the ability to update the backend credential store.

**Comment by taylorsilva** [comment]
I'm having trouble with "...there is no way to truly use variables with the set_pipeline..." because I think that is very possible since we do use vars to set up a few of our pipelines.

You can see our release pipelines here: https://ci.concourse-ci.org/?search=team%3A%22main%22%20group%3A%22release%22
and they get set with `set_pipeline` steps here (in our `reconfigure` pipeline): https://github.com/concourse/ci/blob/798a442475958d58f845c6f8fc4240ed068ff335/pipelines/reconfigure.yml#L299-L348

The release pipeline is full of variables: https://github.com/concourse/ci/blob/master/pipelines/release.yml
I would consider this a single pipeline definition that's instantiated multiple times with with the only difference being the variables because it's literally that.

Maybe the part you're hung up on is that you don't want the var values saved in ANY of your pipelines? Not even the ones that contain the `set_pipeline` steps? Are you worried about secrets leaking? In general we don't encourage trying to keep secrets stored in the Concourse db (though you can enable encryption to be "safer" https://concourse-ci.org/encryption.html)

**Comment by hstenzel** [comment]
I think we're talking about two different scenarios.

Looking at https://github.com/concourse/ci/blob/798a442475958d58f845c6f8fc4240ed068ff335/pipelines/reconfigure.yml#L308, there is  `vars.slack_hook` set to `((slack_hooks.concourse-private))`, where the value comes from an external secret store.

This is different from what I am trying to do, where I want to use a non-secret concourse variable to dereference the actual secret. I have the same pipeline.yml that I want to deploy into multiple different Concourse instances. When they are deployed, they each get their secrets from Hashicorp Vault. However they use a different key to access vault. Therefore it is the key name that is the variable.

```yaml
# set-pipeline job in pipeline.yml
- name: set-pipeline
  plan:
  - get: src
    trigger: true
  - set_pipeline: self
    file: src/.concourse/pipeline.yml
    vars:
      cluster: ((cluster))
```

Then, the pipeline passes the cluster variable (and some others) into the task

```yaml
  - task: executor-create
    file: src/.concourse/executor-task.yml
    vars:
      # ...
      cluster: ((cluster))
```

The task itself then uses the cluster to figure out the correct vault key for the build secret
```yaml
# ...
params:
  BUILD_TOKEN: (("build/((cluster))".BUILD_TOKEN))
# ...
```

What I would like to do is to have the cluster variable be sticky from `fly sp` forward. I understand that we can pass in concrete variables with `set_pipeline`, however what we cannot do is use Concourse native variables such as `((cluster))` in the `set_pipeline` step.

**Comment by hcastrofactored** [comment]
Hi @hstenzel I am facing the same issue, did you manage to come up with a way to accomplish this?

**Comment by hstenzel** [comment]
@hcastrofactored I ended up sticking with (and doubling down) on the workaround.

For set-pipeline, we had: 
```yaml
- name: set-pipeline
  plan:
  - get: src
    trigger: true
  - task: pipeline-genesis # builds the pipeline by processing generating all concourse yaml with the gomplate template engine
    file: src/.concourse/genesis-task.yml # the pipeline template source
    params:
      FOO: {{ .Env.FOO }} # rendered concrete at build time
  - set_pipeline: self
    file: src/build/concourse/pipeline.yml # the gomplate processed pipelines
    vars:
      foo: {{ .Env.FOO }} # rendered concrete at build time
```

Which broadly speaking adds a build task between the get-source and the set-pipeline. That build step uses gomplate ( https://github.com/hairyhenderson/gomplate ) to render the pipeline instead of using Concourse variables. By doing this, the pipeline template can use either Concourse variables in the `(( ... ))` format, which is especially helpful for `params` and secrets. As an added bonus, It enables a bunch of other templating techniques.

Now, it turns out that if you want to reuse pipeline definitions for a bunch of different projects, you have to make much broader use of templating or other techniques to automatically generate pipelines. So this is a technique that is needed anyway for such scenarios (and is also an opportunity for better support in base Concourse)
