### ISSUE TITLE
Resource Not Updated Between Across Tasks

### ISSUE THREAD

**Issue by jprelph** [concourse/concourse#7848]
## Summary

When running multiple tasks with across, if the first run of the task updates the resource, the second run still uses an older version of the resource and not the updated version.

## Steps to reproduce

Resources are all git repositories.

```
jobs:
- name: add-components
  plan:
    - get: cpt-mock-manifest
      trigger: true
    - load_var: manifest
      file: cpt-mock-manifest/manifest.yaml
    - across: 
      - var: component
        values: ((.:manifest.components))
      do:
      - get: cpt-mock
        trigger: false
      - get: cpt-demo
        trigger: false
      - set_pipeline: cpt-mock-watcher
        file: cpt-demo/watcher.yaml
        vars:
          private_key: ((private_key))
        instance_vars:
          component: "((.:component.name))"
      - task: structure
        privileged: false
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: jprelph/yq
          inputs:
            - name: cpt-mock
            - name: cpt-demo
          outputs:
            - name: cpt-mock
          run:
            user: root
            path: sh
            args:
              -  -ecx
              - |-
                if  [ ! -d cpt-mock/((.:component.name)) ]; then
                  cp -R cpt-demo/archetypes/component cpt-mock/((.:component.name))
                  cd cpt-mock
                  git commit -m "Add folder structure"
                else
                  echo "Folders already exist"
                fi
      - put: cpt-mock
        params: 
          repository: cpt-mock
```

## Expected results

The first iteration of the task runs and updates (and puts) the cps-mock resource, which is then successfully used for the second task run. 

## Actual results

The first iteration of the task succeeds, and the "put" is successful, however the second task still "gets" the previous version of the resource (ie. the same one that the first iteration started with). The second "put" then fails as "Updates were rejected because the remote contains work that you do not have locally".

## Additional context

This can be worked around (eg. using a rebase) but it seems counterintuitive.

## Triaging info

* Concourse version: 7.4.2
