### ISSUE TITLE
Passed constraint on current job blocks its group to be displayed in the UI

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [concourse/concourse#7903]
## Summary

If you put a `passed` constraint on a GET resource and this constraint specify the current job, the group/tab in which the job is will not be displayed in the UI.

## Steps to reproduce

```yaml
resources:
  - name: a-git-resource
    type: git
    source:
      uri: ssh://git@my-repository/my-repository.git
  - name: another-git-resource
    type: git
    source:
      uri: ssh://git@my-repository/my-repository.git

groups:
- name: first-group
  jobs:
    - zero-job
    - ko-job
- name: second-group
  jobs:
    - ok-job

jobs:
  - name: zero-job
    plan:
      - get: another-git-resource
  - name: ko-job
    plan:
      - get: another-git-resource
        passed: [zero-job]
      - get: a-git-resource
        passed: [ko-job]

  - name: ok-job
    plan:
      - get: another-git-resource
        passed: [zero-job]
      - get: a-git-resource
```

## Expected results

It should be impossible to deploy such a pipeline!

## Actual results

The `first-group` tab is empty

![first-group](https://user-images.githubusercontent.com/79525444/147224828-da763b34-2f83-4307-9d9a-35f2462fb8aa.png)

... while the `second-group` is not

![second-group](https://user-images.githubusercontent.com/79525444/147224844-3fc42f6f-2071-4e11-843d-0fb7cd708fe3.png)

## Triaging info

* Concourse version: `7.4.0`
* Browser (if applicable): `any`
* Did this used to work? `no`

**Comment by taylorsilva** [comment]
# Issue Bankruptcy

This issue is being closed as part of 2025's **Issue Bankruptcy** declaration. [See here for details](https://blog.concourse-ci.org/posts/2025-01-06-concourse-2024-review/)

If you think this issue still has merit then feel free to open a new issue and reference this one.

---

Funny edge case! Setting a passed constraint on yourself doesn't make any sense. Would probably make sense for the pipeline validator to not allow this.

**Comment by Petahhh** [comment]
I'll take a look

**Comment by Petahhh** [comment]
I think this bug can be closed. When I deployed the above sample pipeline (with a real repo), I get the following error:

```
fly -t dev set-pipeline -p test-7903 -c pipeline.yml -n
.
.
.
error: invalid pipeline config:
invalid jobs:
	pipeline contains a cycle that starts at Job 'ko-job'
```

where `pipeline.yml`:
```
resources:
  - name: a-git-resource
    type: git
    source:
      uri: https://github.com/petahhh/concourse
  - name: another-git-resource
    type: git
    source:
      uri: https://github.com/petahhh/concourse

groups:
- name: first-group
  jobs:
    - zero-job
    - ko-job
- name: second-group
  jobs:
    - ok-job

jobs:
  - name: zero-job
    plan:
      - get: another-git-resource
  - name: ko-job
    plan:
      - get: another-git-resource
        passed: [zero-job]
      - get: a-git-resource
        passed: [ko-job]

  - name: ok-job
    plan:
      - get: another-git-resource
        passed: [zero-job]
      - get: a-git-resource
```
