### ISSUE TITLE
No way to override `default-get-timeout` for `image_resource`

### ISSUE THREAD

**Issue by kberzinch** [concourse/concourse#7907]
## Summary

If there is a global `default-get-timeout` set on the web node, it is not possible to override that timeout for the implicit `get` step that is used to pull the `image_resource` configured on a task.

## Steps to reproduce

Start up Concourse with `default-get-timeout` set very low

```sh
$ wget https://concourse-ci.org/docker-compose.yml

$ echo "      CONCOURSE_DEFAULT_GET_TIMEOUT: 1s" >> docker-compose.yml

$ docker-compose up
```

Task config:

```yaml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: mingc/android-build-box # some random very large image

run:
  path: sh
  args:
  - -e
  - -x
  - -c
  - >-
      echo hello world

```

## Expected results

Some field is available in the task config to override the default `get` timeout.

## Actual results

Image `get` step errors with `timeout exceeded`.

## Additional context

It is possible to work around this issue by running an explicit `get` step and referencing that image in the `task.image` field as described [here](https://concourse-ci.org/building-an-image-and-using-it-in-a-task.html).

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): N/A
* Did this used to work? Global default timeouts were added in 7.6.0
