### ISSUE TITLE
Peer-to-peer streaming large volume across workers reliably fails

### ISSUE THREAD

**Issue by kberzinch** [concourse/concourse#7910]
## Summary

I am trying to use the `mingc/android-build-box` Docker image to build an Android app, which is relatively large compared to the other images used in this cluster. The volume on disk is about ~10 GB:

```
[root@ip-172-31-38-220 062713c7-3d9a-4a76-5a65-8cf52b8ea200]# du -sh .
9.5G	.
```

Streaming this volume across workers (even if both have lots of disk/RAM) reliably fails.

## Steps to reproduce

Set up two workers with different tags, `a` and `b`.

Configure and run the following pipeline:

```yaml
---
resources:
- name: android-build-box
  type: registry-image
  public: true
  icon: android
  source:
    repository: mingc/android-build-box
    tag: 1.24.0

jobs:
- name: build-main
  public: true
  plan:
  - get: android-build-box
    tags:
    - a
  - task: print-gradle-version
    image: android-build-box
    config:
      platform: linux
      run:
        args:
        - -exc
        - echo hello world
        path: sh
    tags:
    - b
```

## Expected results

The volume is copied from worker `a` to worker `b` and the command executes.

## Actual results

Eventually the build errors with

```
find or create container on worker i-0555389473b7a1848: failed to stream p2p out from volume
```

Looking at the source worker `a` during the copy, there are several `tar` commands running concurrently started about a minute apart:

```
[root@ip-172-31-38-220 ~]# ps aux | grep -i tar
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
4294967+  4806  1.4  0.0  20240  2884 ?        S    19:42   0:08 tar -C /dev/fd/3 -cz .
4294967+  4825  1.4  0.0  20240  2844 ?        S    19:43   0:07 tar -C /dev/fd/3 -cz .
4294967+  4866  1.2  0.0  20240  2816 ?        S    19:44   0:05 tar -C /dev/fd/3 -cz .
4294967+  4871  1.1  0.0  20240  2888 ?        S    19:45   0:04 tar -C /dev/fd/3 -cz .
4294967+  4891  1.1  0.0  20240  2872 ?        S    19:46   0:03 tar -C /dev/fd/3 -cz .
4294967+  4948  1.1  0.0  20276  2744 ?        S    19:47   0:03 tar -C /dev/fd/3 -cz .
4294967+  4970  1.2  0.0  20272  2652 ?        S    19:48   0:02 tar -C /dev/fd/3 -cz .
4294967+  5031  1.1  0.0  20272  2812 ?        S    19:49   0:01 tar -C /dev/fd/3 -cz .
4294967+  5051  1.2  0.0  20272  2732 ?        S    19:50   0:01 tar -C /dev/fd/3 -cz .
4294967+  5074  1.0  0.0  19948  2536 ?        S    19:51   0:00 tar -C /dev/fd/3 -cz .
```

It appears that each of these is copying the volume into RAM, so the worker eventually runs out of memory.

![image](https://user-images.githubusercontent.com/10482109/147838008-d840a04b-26ec-4233-a601-e86a78c2e13b.png)

## Additional context

Source worker logs

```
Dec 31 19:59:55 ip-172-31-38-220.ec2.internal concourse[2850]: {"timestamp":"2021-12-31T19:59:55.638531288Z","level":"error","source":"baggageclaim","message":"baggageclaim.api.volume-server.stream-p2p-out.stream-p2p-out.failed-to-compress-volume","data":{"encoding":"gzip","error":"fork/exec /usr/bin/tar: cannot allocate memory","full-path":"/mnt/concourse/volumes/live/062713c7-3d9a-4a76-5a65-8cf52b8ea200/volume","session":"4.1.359.1","sub-path":".","volume":"062713c7-3d9a-4a76-5a65-8cf52b8ea200"}}
```

Source worker is a `r5dn.2xlarge` in AWS running only the Concourse worker under systemd and no other workloads inside Concourse. Memory usage is normal when it's not streaming the volume. The Concourse working directory is on a dedicated ~200 GB SSD (AWS instance store.)

Destination worker does not appear to affect anything.

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): N/A
* Did this used to work? Not sure
