### ISSUE TITLE
Worker cannot complete retirement if it was involved in the setup of a task it is not running

### ISSUE THREAD

**Issue by odormond** [concourse/concourse#7946]
## Summary

When a task start, the image to use for it is looked up by running the check operation of the image_resource followed by the get operation for the version found. When multiple workers are involved, it can happen that the check runs on a worker, the get on another worker and the task on a third worker. if any of the worker that took care of the check or get operation for the image is different from the one actually running the task, then retiring the worker that run the check or get will not complete until the task is finished.

This should not be the case, because:
- The worker taking care of running the task does not need anything from the check operation output. The get operation needs the version produced by the check but that's all.
- The worker taking care of running the task needed the volume produced by the get operation until it was copied to the worker running the task. When the task start execution, it already has a copy of the volume and so the original is not needed any more.

## Steps to reproduce

1. Start the ATC.
2. Start two workers.
3. Set the following pipeline under the name "abort-me":
    ```yaml
    jobs:
    - name: must-be-aborted
      plan:
      - task: abort
        config:
          platform: linux
          image_resource:
            type: mock
            source: {mirror_self: true}
          run:
            path: sh
            args: ["-c", "echo abort me; sleep 86400"]
    ```
4. Trigger the job "must-be-aborted" from the "abort-me" pipeline and wait for it's task "abort" to run start and print `abort me`
5. Check which worker was used to execute the check and get operations for the image as well as the one used to run the task itself.
6. If they're all the same, abort the task and try again.
7. If they're not all the same, tell the worker that is not running the task to retire (by sending a SIGUSR2).
8. Check with `fly workers` that the worker's state is indeed `retiring`.
9. Watch it stay like this for as long as you which. It will not go away until the task is finished (the `sleep 86400` in there) or it's aborted.
10. Abort the job and you'll see the worker go away a few seconds later.

Note that the worker involved in the setup but not the execution of the task is blocked from retiring in all cases. It could have taken care of just the check, just the get or both, that does not make any difference.

## Expected results

The concourse worker told to retire goes away after a few seconds.

## Actual results

The concours worker told to retire stays in retiring state for as along as the task is running.

## Triaging info

* Concourse version: 7.6.0 (I've seen it before too)
* Browser (if applicable): N/A
* Did this used to work? I don't know
