### ISSUE TITLE
Having resources sharing the same config but with different names makes them get triggered as if they were one resource

### ISSUE THREAD

**Issue by AndoniLarz** [concourse/concourse#7950]
## Summary

I have two git-resource resources 1 & 2 that share the same config, pointing to the same git repo.
They share the same content under the `source` key.
They have different names and the `webhook_token`s' values are different.
When I trigger a webhook on resource 1, both of resource 1 and 2 get checked.

Pipeline example :
```yaml
resources:
    -   name: git-resource-1
        type: git
        source:
            uri: ssh://git@my-gitlab-server.com:22/my-group/my-project.git
            branch: master
            private_key: ((gitlab_private_key))
        check_every: 24h
        webhook_token: webhook-my-project-git-resource-1
    -   name: git-resource-2
        type: git
        source:
            uri: ssh://git@my-gitlab-server.com:22/my-group/my-project.git
            branch: master
            private_key: ((gitlab_private_key))
        check_every: 24h
        webhook_token: webhook-my-project-git-resource-2

jobs:
  - name: echo-hello-resource-1
    public: true
    plan:
    -   get: git-resource-1
        trigger: true
    -   task: echo-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker_registry))/library/busybox
          run:
            path: echo
            args:
              - hello

  - name: echo-hello-resource-2
    public: true
    plan:
    -   get: git-resource-2
        trigger: true
    -   task: echo-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker_registry))/library/busybox
          run:
            path: echo
            args:
              - hello
```

## Steps to reproduce

Have a pipeline like the one above with two resources having the same config but different names and different webhook tokens.
Have a webhook setup on only one of the resources, trigger it and watch both of resources getting checked.
Make a change on the git-repo targeted by both resources and trigger the webhook. Then watch both resources get checked and both jobs get triggered.

## Expected results

When I trigger the webhook of resource 1, resource 1 is checked and resource 2 isn't.
If a change is made on the git-repo, a webhook is sent to resource 1 and Concourse triggers a check only on resource 1, hence having it checked and triggering the related job.
Resource 2 doesn't get checked and the related job doesn't get triggered.

## Actual results

When I trigger the webhook of resource 1, both resource 1 and 2 get checked.
If a change is made on the git-repo, a webhook is sent to resource 1, Concourse triggers a check on both resource 1 and resource 2, hence having them both checked and both triggering their related job.

## Additional context

This use case is a little bit special since we have two resources being almost the same.
Webhooks are sent from Gitlab to a webhook-distributor. The webhook-distributor checks which files on the git repo have been modified and pushes a webhook both to specific Concourse resources and to specific Jenkins jobs.

This post seems to be related and explain some aspects of this behaviour : https://medium.com/concourse-ci/concourse-resource-volume-caching-7f4eb73be1a6

This behaviour affects resources accross pipelines (we encountered this case) and may affect resources across teams (we did not encounter this case).

## Triaging info

* Concourse version: 7.4.0
* Browser (if applicable): Not applicable
* Did this used to work ? I never tried doing that before, so I don't really know if it's new
