### ISSUE TITLE
Outputs of in_parallel steps lost if resource used concurrently

### ISSUE THREAD

**Issue by Anonymous-Coward** [concourse/concourse#8022]
## Summary

If two steps running in parallel write to different places but in the same input directory, the writes of the one that finishes first are lost.

## Steps to reproduce

Configure and run the following pipeline (no additional setup or resources needed - but you might want to pull the docker image used by the pipeline into a local repo and change the pipeline to use it from there, given that docker hub restricts frequent pulling of images):
```
resources:
- name: alpine-bash
  type: docker-image
  source:
    repository: frolvlad/alpine-bash
jobs:
  - name: build-test
    plan:
    - get: alpine-bash
    - task: create-file-0
      image: alpine-bash
      config:
        platform: linux
        outputs:
        - name: some-volume
        run:
          path: bash
          args: ["-c", "set -x; mkdir -p some-volume; cd some-volume; touch test0.txt;"]
    - in_parallel:
        steps:
        - task: create-file-a
          image: alpine-bash
          config:
            platform: linux
            inputs:
            - name: some-volume
            outputs:
            - name: some-volume
            run:
              dir: some-volume
              path: bash
              args: ["-c", "set -x; sleep 30; touch testA.txt;"]
        - task: create-file-b
          image: alpine-bash
          config:
            platform: linux
            inputs:
            - name: some-volume
            outputs:
            - name: some-volume
            run:
              dir: some-volume
              path: bash
              args: ["-c", "set -x; sleep 60; touch testB.txt;"]
    - task: check-files
      image: alpine-bash
      config:
        platform: linux
        inputs:
        - name: some-volume
        run:
          dir: some-volume
          path: sh
          args: ["-c", "ls;"]
```

## Expected results
The last step in the pipeline above lists three files: test0.txt, testA.txt and testB.txt.

## Actual results
The last step in the pipeline above only lists two files: test0.txt and testB.txt.

## Additional context
This is a simplified version. The bug also occurs when different tasks write to different sub-directories inside the same input.

Probably related: using sub-directories of an input as outputs also doesn't work - whatever is in the sub-directories before the first task which uses them as input is lost.

## Triaging info

* Concourse version: 7.4.0
* Browser (if applicable):
* Did this used to work? Never tried it before, since in_parallel is a relatively recent addition.
