### ISSUE TITLE
Resource scope will not be recalculated after enabling global resources

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#8059]
## Summary

I happened to find this bug when run tests on master branch. Then I verified a few more branches, and confirmed this bug should be introduced in 7.5.0.

## Steps to reproduce

This is very easy to reproduce. Just use a pipeline with two resources and they are defined with the same source. My test pipeline is like:

```yaml
resources:
- name: mygit1
  type: git
  source:
    uri: <my git repo>
    branch: master
    private_key: ((chaol-gitlab-private-key))

- name: mygit2
  type: git
  source:
    uri: git@gitlab.eng.vmware.com:chaol/fortest.git
    branch: master
    private_key: ((chaol-gitlab-private-key))

jobs:
- name: job
  public: true
  plan:
  - get: mygit1
  - get: mygit2
```

Steps:
- Start Concourse with disabling global resources
- Set and unpause the pipeline
- Wait a check interval, then `select * from resources`. The two resources will have the same config id but different scope id.
- Restart Concourse with enabling global resources
- Wait a check interval, then run the query again

## Expected results

The two resources' scope id should be recalculated, and they should have the same scope id.

## Actual results

With branch `release/7.4.x`, I got the expected result.

But with branch `release/7.5.x` and `master`, scope ids are not recalculated. If destroy the pipeline and reset it, the two resources will get the same scope id.

I didn't verify 7.6, but I assume 7.6 should have the same bug as the bug still exists on `master`.

## Additional context

Looking at release content of 7.5.0, I guess the bug is introduced by #7176. I'm not sure, just guessed that.

## Triaging info

* Concourse version: since 7.5.0
* Browser (if applicable): NA
* Did this used to work? yes, 7.4.0 works.
