### ISSUE TITLE
set-pipeline add unnecessary quote with template variable 

### ISSUE THREAD

**Issue by aminotsukasa** [concourse/concourse#806]
# Bug Report

I create a minimum pipeline and asset file.

```
jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      params:
        foo: prefix-{{environment_name}}
      run:
        path: echo
        args: ["hello"]
```
```
---
environment_name: development
```

and set-pipeline executing..

```
$ fly -t lite set-pipeline -p hello-world -c hello.yml -l manifest.yml

jobs:
  job hello-world has changed:
    name: hello-world
    plan:
    - task: say-hello
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        params:
          foo: prefix-"development"
        run:
          path: echo
          args:
          - Hello
          - hello
          dir: ""
```

This has expanded template block with unnecessary quote character
Expected Result.
```
        params:
          foo: prefix-development
```

Actual Result.
```
        params:
          foo: prefix-"development"
```

* Concourse version: 2.5
* Deployment type (BOSH/Docker/binary): docker
* Infrastructure/IaaS: AWS EC2
* Browser (if applicable): Firefox 50
* Did this used to work? yes
