### ISSUE TITLE
run as user does not work for darwin worker

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#807]
Hi there!

# Bug Report

Setting user for a task does not work for darwin worker.
It is expected to make id -un ----> server, since I explicitly tell the task to run as **user:server**, it returns root. 👎 

---
platform: darwin
inputs:
- name: mex-ios-repo
- name: mex-mock-server-repo
run:
  **user: server**
  path: sh
  args:
  - -exc
  - |
    **id -un**

The following can also be handy:

* Concourse version: 2.50

**Comment by databus23** [comment]
I think this might be a duplicate of https://github.com/vito/houdini/pull/4

**Comment by devdavidkarlsson** [comment]
This is a workaround to running my ui tests through fastlane when the task is run as root,  "chown -r myuser:staff .." and then "sudo -H -u myuser -c 'cd ios-repo && pod install && bundle exec fastlane test'"

**Comment by ratkins** [comment]
Noting we can reproduced this on 2.7.0—and it prevents iOS builds from working at all as `xcodebuild` can't find any provisioning profiles when run as root.

**Comment by eedwards-sk** [comment]
@vito 

👍 

This is biting me when trying to build homebrew bottles on OS X, as homebrew does not support running as root.

**Comment by eedwards-sk** [comment]
Note how user is still `root` and all the files and folders are still owned by `root`.

```
platform: darwin

inputs:
- name: source
- name: source-dist
- name: source-dist-checksum
- name: homebrew
- name: homebrew-core

run:
  path: source/ci/concourse/task-scripts/build-bottle.1
  user: eedwards
```

```
whoami

ls

ls -la
```

```
+ whoami
root
+ ls
homebrew		homebrew-core		source			source-dist		source-dist-checksum
+ ls -la
total 0
drwxr-xr-x  7 root  staff  224 Aug  9 14:07 .
drwxr-xr-x  6 root  staff  192 Aug  9 14:07 ..
lrwxr-xr-x  1 root  staff   84 Aug  9 14:07 homebrew -> /opt/concourse/local/worker/volumes/live/a0c9368e-fece-4c73-799f-24e0ef21dc23/volume
lrwxr-xr-x  1 root  staff   84 Aug  9 14:07 homebrew-core -> /opt/concourse/local/worker/volumes/live/389ab207-b747-496f-713c-3b52d950fa05/volume
lrwxr-xr-x  1 root  staff   84 Aug  9 14:07 source -> /opt/concourse/local/worker/volumes/live/0982d409-2335-4055-7858-4070e0b7807b/volume
lrwxr-xr-x  1 root  staff   84 Aug  9 14:07 source-dist -> /opt/concourse/local/worker/volumes/live/c6ecd72c-3617-4a0e-52ee-ac4e4a93732c/volume
lrwxr-xr-x  1 root  staff   84 Aug  9 14:07 source-dist-checksum -> /opt/concourse/local/worker/volumes/live/ede8b853-ed56-4e0e-62c5-ebed08eb4470/volume
```

**Comment by eedwards-sk** [comment]
For posterity, here's a workaround I implemented, but I don't like having to use it :(

This allows me to execute a task as a specified user/group by applying a recursive `chown` to the volume, its contents (symlinks), and the contents of its symlinks, and then executing the target script as the specified user.

This actually has the benefit OVER the build in `user` command as I can pass the username to take on dynamically from `fly execute` by using an environment variable (something I can't do with the `user` command since we can't parameterize tasks... grumble grumble...)

```
platform: darwin

inputs:
- name: source
- name: source-dist
- name: source-dist-checksum
- name: homebrew
- name: homebrew-core

PARAMS:
  HOMEBREW_USER_NAME:
  HOMEBREW_USER_GROUP:

run:
  path: bash
  args:
  - -c
  - |
    : "${HOMEBREW_USER_NAME:?"must provide user name to build homebrew as"}"
    : "${HOMEBREW_USER_GROUP:?"must provide user group to build homebrew as"}"
    chown -R "${HOMEBREW_USER_NAME}:${HOMEBREW_USER_GROUP}" ../volume &&
    chown -R "${HOMEBREW_USER_NAME}:${HOMEBREW_USER_GROUP}" ./*/ &&
    sudo -H -u "${HOMEBREW_USER_NAME}" source/ci/concourse/task-scripts/build-bottle.1
```
