### ISSUE TITLE
Additional Certificates don't work in Helm-Deployment

### ISSUE THREAD

**Issue by MarkusPoh** [concourse/concourse#8112]
## Summary

In our enterprise enviroment I have to use self-signed certificates for our image-repository. 
Without this additional certificates I am unable to use the registry.  For example:
```
--
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: harbor.mycompany.com/docker-hub-proxy/library/busybox
          tag: "latest"
          user: ****
          password: *****
      run:
        path: echo
        args: ["Hello world!"]
```
results in
```
* ping https: Get "https://harbor.mycompany.com/v2/": x509: certificate signed by unknown authority
* ping http: Get "https://harbor.mycompany.com/:443/v2/": x509: certificate signed by unknown authority
```
Adding CA, server-certificate and intermediate to `workerAdditionalCerts` in `value.yaml` won't fix.

As I can see the certificates are mounted as 
```
tmpfs on /etc/ssl/certs/worker-additional-certs.pem type tmpfs (ro,relatime,seclabel,size=31772584k)
```
in the workers. But they are not used. The Error-Message still remains:
```
* ping https: Get "https://harbor.mycompany.com/v2/": x509: certificate signed by unknown authority
* ping http: Get "https://harbor.mycompany.com/:443/v2/": x509: certificate signed by unknown authority
```
## Steps to reproduce

* set up a  local image registry with a self signed certificate.
* add this certificates to the section  to `workerAdditionalCerts` in `value.yaml` (from concourse-helm)
* Deploy Concourse CI on kubernetes with helm
* Add a hello-world-pipeline as 
```
--
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: YOURREGISTRY/busybox
          tag: "latest"
          user: YOURUSER
          password: YOURPASSWD
      run:
        path: echo
        args: ["Hello world!"]
```
* Run the pipeline

## Expected results

Display `hello world!` in task `simple-task` in the concourse dashboard.

## Actual results

```
* ping https: Get "https://harbor.mycompany.com/v2/": x509: certificate signed by unknown authority
* ping http: Get "https://harbor.mycompany.com/:443/v2/": x509: certificate signed by unknown authority
```
## Additional context

--

## Triaging info

* Concourse version: 7.6.0
* Browser (if applicable): -
* Did this used to work? No
