### ISSUE TITLE
Pipeline check list resource history which already been deleted

### ISSUE THREAD

**Issue by 50wu** [concourse/concourse#8122]
## Summary

We find that the pipeline will show the resource history even though that resource has already been deleted. It will trigger the pipeline by mistake and cause the pipeline to fail. We are using version v7.6.0, the older version v5.7.1 doesn't have this issue. 

## Steps to reproduce

We are using the private image, it's hard to reproduce on your side, attach the pipeline yaml file for your reference:

```
resource_types:
- name: tanzunet
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/tanzunet-concourse-resource

resources:
- name: pivotal-gpdb-all-user
  type: tanzunet
  source:
    api_token: xxx
    endpoint: tanzunet-website-url
    product_slug: test-slug
    version: ^6\..*
    since_version: 6.2.0
    availability: "All Users"

jobs:
- name: get-pivotal-gpdb-all-users
  plan:
  - get: pivotal-gpdb-all-user
    params:
      globs: []
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: bash }
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          echo 1
```

## Expected results

Pipeline resource only lists the latest release version:

![Screen Shot 2022-02-23 at 5 54 04 PM](https://user-images.githubusercontent.com/16753994/155307566-848442ce-7e9c-4bda-b1b8-941133e7c265.png)

## Actual results

It lists all versions triggered the pipeline before, also they are not exist anymore

![Screen Shot 2022-02-23 at 5 55 34 PM](https://user-images.githubusercontent.com/16753994/155307577-f1b183a4-b650-460b-9039-511638ef0422.png)

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?
