### ISSUE TITLE
Wrong warning message for set_pipeline with var as name inside across

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#8134]
## Summary

The Concourse Doc (https://concourse-ci.org/across-step.html#schema.across) provides an example that run `set_pipeline` inside `across` and use a var as pipeline name.

I used the following pipeline to test that:

```yaml
resources:
- name: data
  type: mock
  source:
    create_files:
      data.json: |
        [{"key": "a"}, {"key": "b"}]
      p.yml: |
        resources:
        - name: data
          type: mock
        jobs:
        - name: job-1
          public: true
          plan:
          - get: data


jobs:
- name: something
  public: true
  plan:
    - get: data
    - load_var: d
      file: data/data.json
    - across:
      - var: obj
        values: ((.:d))
      set_pipeline: ((.:obj.key))
      file: data/p.yml
```

But when I set the pipeline, it badly raised an error message:

```
$  fly760 -t target sp -c test-across.yml -p test-across

apply configuration? [yN]: y

DEPRECATION WARNING:
  - jobs.something.plan.do[2].across.set_pipeline(((.:obj.key))): '((.:obj.key))' is not a valid identifier: must start with a lowercase letter

identifier schema documentation: https://concourse-ci.org/config-basics.html#schema.identifier

configuration updated
```

## Steps to reproduce

As above.

## Expected results

The warning should not be there.

## Actual results

It's there.

## Triaging info

* Concourse version: 7.6.0 (maybe previous versions as well)
* Browser (if applicable):
* Did this used to work?
