### ISSUE TITLE
Stuck in discovering new version forever

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#815]
Hi there!

# Bug Report

Resource_type(npm-cache-resource) resource stuck forever in

"discovering any new versions of node_modules"

No logs no output, Task is not starting

**The following appears to works successfully:**
fly -t dev_refactor check-resource -r oasis/node_modules
checked 'node_modules'

Have tried fetching it from a private docker-registry resource,
I have tried fetching it from docker hub

I have destroyed my virtual box running docker-compose and recreated it.

* Concourse version: 2.5.0

```

resource_types:
# https://github.com/ymedlop-sandbox/npm-cache-resource
- name: node_modules-type
  type: docker-image
  source: {repository: devdavid/npm-cache-resource, tag: latest}
  # source:
  #   repository: {{docker-registry-npm-cache}}
  #   tag: latest
  #   insecure_registries:
  #     - {{docker-registry}}

......

# a resource caching the dependencies listed in the source repository
- name: node_modules
  type: node_modules-type # as defined above
  source:
    <<: *client-repo-source # the source is the same as the corresponding git resource ...
    paths: # ... except that it's only interested in files listing dependencies
      - package.json

.......

#Git repo containing the client source:
- name: client-repo
  type: git
  source: &client-repo-source #YAML-Anchor for npm cache
    uri: git@bitbucket.org:my_repo/client-devops.git
    branch: frontend
    private_key: {{private-key}}

.......

#Cache client NPM packages:
- name: cache
  plan:
    - get: client-repo
      trigger: true
    - get: node_modules
```

**Comment by vito** [comment]
Have you tried hijacking the container (`fly hijack -c pipeline-name/resource-name`) and seeing if a `check` process is running?

**Comment by kurtmc** [comment]
I have experienced a similar problem. All the checks seems to have finished but it is still stuck. I noticed that the s3 resource container still had the check process running. hijacking the container and killing the process allowed my build plan to start.

Is the bug in concourse or the s3 resource? Should checks have some sort of timeout enforced by concourse?

**Comment by mkb** [comment]
I've seen this behavior on both 2.5.0 and 2.5.1. I've attached logs from the `web` and `worker` bosh jobs.

[concourse-logs.zip](https://github.com/concourse/concourse/files/656140/concourse-logs.zip)

It doesn't look like a `check` process is running in the container:

    ± % fly -t tut-ci hijack -c main/resource-deployment-manifest-stub-in
    bash-4.3# ps augxww
    PID   USER     COMMAND
        1 root     {exe} /var/vcap/packages/runc/bin/runc init
      534 root     bash
      538 root     ps augxww

Give a shout if I can provide any other diagnostic info. Thanks!

**Comment by holstvoogd** [comment]
I've seen this behaviour too. It happend in concurrence with loosing a worker. See #796 for details

**Comment by mkb** [comment]
Ah, I forgot to mention I've seen the behavior both with Concourse in a local Vagrant/VirtualBox VM and deployed via BOSH.

**Comment by ahelal** [comment]
this happens very often now with 1.5.1

**Comment by devdavidkarlsson** [comment]
Was away for five days and when I got back all resources appear to be stuck and orange…
Tried updating to 2.5.1 and now… Most of the resources are spinning in discovery....
Hard to know the status since nothing is logged to the UI (It really should log something)....

But should’nt discovery be a <10 min thing?
It appears mine are spinning forever again ;(

**Comment by vito** [comment]
We've seen quite a few reports of this but still haven't found a smoking gun. :/ We haven't forgotten about it, but we're also not running into it ourselves, so we don't have much to work with.

Valuable information to report would be:

* Are all your workers present? Could be #750 if not.
* Can you reach the workers from your ATC? Could be an ARP caching issue if you're on AWS and recently modified your cluster.
* Please collect a stack dump from the ATC - this can be done via `curl http://127.0.0.1:8079/debug/pprof/goroutine?debug=2`. Please throw it in a gist since it can be quite long. It will *not* include any sensitive information.
* Also collect a stack dump from the TSA. If you're running binaries, this will be part of the above stack dump, as they're the same process. If not, you'll have to send `SIGQUIT` to the TSA process, and then look in stderr.
* After collecting that stack dump, try bouncing the ATC and TSA.

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/844 as there are a few related issues and I'd like to highlight the above diagnostics collection.

Thanks for the information provided thus far! But if you could, going through the linked issue would be a great help.

**Comment by Murryy79** [comment]
I am stuck with this same issue "discovering any new versions of <resourcename>" and little below "waiting for a suitable set of input versions"

![image](https://user-images.githubusercontent.com/19574664/28345291-e62a943a-6bee-11e7-9676-f3684f27b261.png)


My concourse version: 2.7.4

deleted and re-created pipeline
restarted concourse workers
upgrade stemcells to newer version

all of the above didn't fix "discovering any new versions" forever issue
anyone found resolution ?

**Comment by daggerok** [comment]
i have a similar issue using docker-compose environment for concourse:

decomposed-pipeline.yml:

```yml
resources:
- name: pipeline-resources
  type: git
  source:
    url: https://github.com/daggerok/concourse-examples.git
jobs:
- name: pipeline
  public: true
  plan:
  - get: pipeline-resources
  - task: hola
    file: pipeline-resources/04-tasks-extracted-into-resources/decomposed-resource.yml
```

decomposed-resource.yml:

```yml
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

run:
  path: echo
  args: [who-hoo!]
```

<img width="412" alt="screen shot 2017-09-19 at 01 29 13" src="https://user-images.githubusercontent.com/2445604/30567707-4a5a6e78-9cda-11e7-9e4f-ec6f3057db58.png">

anybody knows how fix that?

Thanks

---
Regards,
Maksim

**Comment by daggerok** [comment]
No actual
I found an issue in my decomposed-pipeline.yml: url -> uri

wrong:
```
resources:
- name: pipeline-resources
  type: git
  source:
    url: ....
```

correct:
```
resources:
- name: pipeline-resources
  type: git
  source:
    uri: ....
```

maybe, this will helps someone.

---
/br Max
