### ISSUE TITLE
Paused job locks serial group

### ISSUE THREAD

**Issue by iredelmeier** [concourse/concourse#817]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Bug Report

Not entirely sure if this is a bug, but it frequently causes problems for us.  We have several jobs in a serial group, and whenever we pause one, it blocks the unpaused jobs from running such that we need to manually abort the paused job's build whenever it gets triggered.  The "error" message explaining why the unpaused job isn't running is misleading and references `max-in-flight`:

```
checking pipeline is not paused
checking job is not paused
discovering any new versions of task-repo
waiting for a suitable set of input versions
checking max-in-flight is not reached
```

Minimal steps to reproduce:

1. Pipeline:

```
resources:
  - name: task-repo
    type: git
    source:
      uri: https://github.com/stevemao/left-pad
      branch: master

jobs:
  - name: unit-tests2
    serial_groups: ["hi"]
    plan:
      - get: task-repo
        trigger: true # this part may not be needed
  - name: unit-tests
    serial_groups: ["hi"]
    plan:
      - get: task-repo
        trigger: true # this part may not be needed
```

2. Unpause the pipeline and let both jobs run once, cause...
3. Pause one job, and then manually trigger it; it will enter the pending state.
4. Then, manually trigger the unpaused job.  See that the unpaused job doesn't run and the error message references `max-in-flight`.

We would expect that unpaused jobs would just run, i.e., that the paused-but-pending job would not block the rest of the serial group.

Environment details:

* Concourse version: 2.5.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): N/A
* Did this used to work? Don't think so

Thanks!
