### ISSUE TITLE
Baggage claim failing when deployed with 5gb ephemeral disk

### ISSUE THREAD

**Issue by evanfarrar** [concourse/concourse#818]
Steps to reproduce: 
Given the cloud-config
```
vm_extensions:
- name: 5GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 5
    root_disk_type: pd-ssd
- name: 50GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
```

And a manifest based on the example for clustered deploy with this in the worker section: 
```
- name: worker
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # sufficient ephemeral storage to VMs in this instance group.
  - 5GB_ephemeral_disk
```
Then worker/0 job fails with this message in ```/var/vcap/data/sys/log/baggageclaim/fs_mounter.stderr.log```:

```
expected argument for flag `--size-in-megabytes', but got option `-9194'
expected argument for flag `--size-in-megabytes', but got option `-9194'
expected argument for flag `--size-in-megabytes', but got option `-9194'
expected argument for flag `--size-in-megabytes', but got option `-9194'
```
However, if I increase to the 50GB_ephemeral_disk then the error goes away. This could be considered a math bug or just a documentation bug. Perhaps we could modify that comment ```sufficient ephemeral storage``` to explain what sufficient entails.

* Concourse version: garden-runc/1.0.4 + concourse/2.5.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): N/A
* Did this used to work?: First version that I have ever attempted this on.
