### ISSUE TITLE
var_sources not accessible when inside an across task

### ISSUE THREAD

**Issue by farhank3389** [concourse/concourse#8191]
## Summary

I have 2 dummy var_sources defined. I am using across to iterate over one of the dummy vars but I get the following error when trying to also access the other dummy var inside the task. The same thing happens with accessing vault var_sources inside across.

```
failed to interpolate template: missing source 'dummyvar2' in var: dummyvar2:testkey
```

## Steps to reproduce

Create and run the following pipeline:

```
var_sources:
- name: dummyvar
  type: dummy
  config:
    vars:
      testkey: ["test1", "test2"]
- name: dummyvar2
  type: dummy
  config:
    vars:
      testkey: "test3"

jobs:
- name: placeholder
  plan:
  - across:
    - var: testiter
      values: ((dummyvar:testkey))
    task: use-vars
    config:
      platform: linux

      image_resource:
        type: mock
        source: {mirror_self: true}

      run:
        path: sh
        args:
        - -exc
        - |
          echo ((.:testiter))
          echo ((dummyvar2:testkey))
```

Running this without ` echo ((dummyvar2:testkey))` works fine - it iterates over `testkey` and echoes `test1` and `test2`.

## Expected results

The task should be able to access the other variable.

## Actual results

This error is produced when running the pipeline

```
failed to interpolate template: missing source 'dummyvar2' in var: dummyvar2:testkey
```

## Triaging info

* Concourse version:  v7.7.0
* Browser (if applicable): Chromium
* Did this used to work? No
