### ISSUE TITLE
Error when running task registry-image "proc start: OCI runtime exec failed"

### ISSUE THREAD

**Issue by jessielaf** [concourse/concourse#8199]
## Summary

I am trying to build on my concourse instance but every task throws an error. It does not matter what I am doing with the task. This is my first time using concourse.

## Steps to reproduce

Concourse is running with docker-compose on debian with this config:

```  
CONCOURSE_POSTGRES_HOST: db
CONCOURSE_POSTGRES_USER: concourse_user
CONCOURSE_POSTGRES_PASSWORD: "secret"
CONCOURSE_POSTGRES_DATABASE: concourse
CONCOURSE_ADD_LOCAL_USER: "admin:secret"
CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
CONCOURSE_WORKER_RUNTIME: "containerd"
CONCOURSE_EXTERNAL_URL: https://concourse.jcbdevelopment.com
CONCOURSE_VAULT_URL: https://vault.jcbdevelopment.com
CONCOURSE_VAULT_LOOKUP_TEMPLATES: "{{ '{{.Secret}}' }}"
CONCOURSE_VAULT_PATH_PREFIX: kv
CONCOURSE_VAULT_CLIENT_TOKEN: "{{ secrets['VAULT_TOKEN'] }}"
```

I used quickstart instead of a separate `worker` and `web` because I could not get the worker to connect to the web instance.

Using this example concourse config I found:
```
resources:
  - name: larvel-websockets-git
    type: git
    icon: github
    source:
      uri: https://github.com/beyondcode/laravel-websockets.git

jobs:
  - name: test
    public: true
    plan:
      - get: larvel-websockets-git
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: composer }
          inputs:
            - name: larvel-websockets-git
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd larvel-websockets-git

                composer install
                vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
```

Than run the pipeline.

## Expected results

Build runs smoothly

## Actual results

Getting this error in the ui:
`start process: backend error: Exit status: 500, message: {"Type":"","Message":"proc start: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec format error: unknown","Handle":"","ProcessID":"","Binary":""}`

Looking further into the logs:

It starts with this error:
`time="2022-03-25T09:21:22.904340967Z" level=error msg="failed to enable controllers ([cpuset cpu io pids])" error="failed to write subtree controllers [cpuset cpu io pids] to \"/sys/fs/cgroup/garden/cgroup.subtree_control\": write /sys/fs/cgroup/garden/cgroup.subtree_control: no such file or directory"
`

Which is the same error I got in the workers. There is an open discussion about it: https://github.com/concourse/concourse/discussions/7953

The next errors:

```
{"timestamp":"2022-03-25T09:21:25.832004100Z","level":"error","source":"worker","message":"worker.garden.garden-server.destroy.failed","data":{"error":"gracefully killing task: graceful kill: kill task execed processes: task execed processes: pid listing: runc did not terminate successfully: exit status 1: container_linux.go:187: getting all container pids from cgroups caused: read /sys/fs/cgroup/garden/6f39cce8-cc8a-4f81-7ca5-d0b77b7c6593/cgroup.procs: operation not supported\n: unknown","handle":"6f39cce8-cc8a-4f81-7ca5-d0b77b7c6593","session":"1.2.82067"}}
{"timestamp":"2022-03-25T09:21:25.832687001Z","level":"error","source":"worker","message":"worker.container-sweeper.tick.failed-to-destroy-container","data":{"error":"gracefully killing task: graceful kill: kill task execed processes: task execed processes: pid listing: runc did not terminate successfully: exit status 1: container_linux.go:187: getting all container pids from cgroups caused: read /sys/fs/cgroup/garden/6f39cce8-cc8a-4f81-7ca5-d0b77b7c6593/cgroup.procs: operation not supported\n: unknown","handle":"6f39cce8-cc8a-4f81-7ca5-d0b77b7c6593","session":"6.2024"}}

```

These keep on repeating and repeating.

## Triaging info

* Concourse version: 7.7.0
* Browser (if applicable): Chrome
* Did this used to work? No
