### ISSUE TITLE
Cannot have a pipeline with a put as its (only) first step

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#82]
example pipeline (from https://github.com/cloudfoundry-community/slack-notification-resource-boshrelease):

```
---
jobs:
- name: alert
  public: true
  plan:
  - put: alert
    params:
      text: Hi everybody!
      channel: "#general"
      username: concourse
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png

resources:
- name: alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/XXXX/XXX/XXXX
```

fails, with build log:

```
/opt/resource/out: line 5: cd: /tmp/build/put: No such file or directory
```
