### ISSUE TITLE
Container cannot access internet during building from a Dockerfile

### ISSUE THREAD

**Issue by janaurka** [concourse/concourse#821]
Hi there!

We experience a weird problem.
Our setup:

1. We sit behind a proxy
1. We have set the `http_proxy` and `https_proxy` for `groundcrew` 
4. We like to build a `docker` container using concourse:
1. Concourse is able to download the `docker` containers from the official repository
1. The `Dockerfile` we use to build a new container on top of this repository tries to access the internet. This _fails_. 
1. When trying to debug this: We can reach the resource from the `worker`. Also when intercepting the container and running `wget` locally. So this is only a problem during the `build` phase (?!?).

The `pipeline` basically looks like this:

```
---

resources:
- name: from-github
  type: git
  source:
    uri: https://github.com/janaurka/terraform.git
    branch: master

- name: docker-image-to-create
  type: docker-image
  source:
    <private repo details>


jobs:

- name: get-code
  plan:
  - get: from-github
  - put: to-private-repo
    params:
      build: from-github

```

The `Dockerfile` is:

```
FROM golang:alpine
MAINTAINER "XX"

ENV TERRAFORM_VERSION=0.8.1

RUN apk add --update git bash 

ENV TF_DEV=true

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/mevansam/terraform.git ./ && \
    /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["terraform"]

```

The `RUN apk` thingy tries to connect to the server using `http` and fails. 

We’ve tested this `wget` another `http` resource and it fails as well.

The following can also be handy:

* Concourse version: 
```
concourse       | concourse/2.5.1       | bosh-vsphere-esxi-ubuntu-trusty-go_agent/3312.8 | latest
```

* Deployment type (BOSH/Docker/binary):

```
Version    258.0.0 (00000000)
```

* Infrastructure/IaaS: `vSphere`

Honestly I’ve no clue how to debug this. 

Downloading the image seems to hit the proxy settings just fine. And after the buildphase (well which fails) everything fails as well. Any ideas?
