### ISSUE TITLE
acrossStep with multiple vars/values isn't creating a full matrix

### ISSUE THREAD

**Issue by nexeck** [concourse/concourse#8268]
## Summary

We want to use the acrossStep with 6 vars each with 1 to 4 values. Concourse isn't creating a full matrix, its just using the last values of some of our vars.

## Steps to reproduce

```yaml
- across:
    - var: a
      values: ["a1"]
    - var: b
      values: ["b1", "b2"]
    - var: c
      values:
        ["c1", "c2", "c3", "c4"]
      max_in_flight: all
    - var: d
      values: ["d1", "d2"]
    - var: e
      values: ["e1", "e2"]
    - var: f
      values: ["f1", "f2"]
  do:
    - task: test
```

```go
package main

import (
	"fmt"
)

func cartesianProduct(varValues [][]interface{}) [][]interface{} {
	if len(varValues) == 0 {
		return make([][]interface{}, 1)
	}
	var product [][]interface{}
	subProduct := cartesianProduct(varValues[:len(varValues)-1])
	for _, vec := range subProduct {
		for _, val := range varValues[len(varValues)-1] {
			product = append(product, append(vec, val))
		}
	}
	return product
}

func main() {
	var matrix [][]interface{}
	matrix = append(matrix,
		append(make([]interface{}, 0), "a1"),
		append(make([]interface{}, 0), "b1", "b2"),
		append(make([]interface{}, 0), "c1", "c2", "c3", "c4"),
		append(make([]interface{}, 0), "d1", "d2"),
		append(make([]interface{}, 0), "e1", "e2"),
		append(make([]interface{}, 0), "f1", "f2"),
	)
	fmt.Printf("Underlying Value: %v\n", cartesianProduct(matrix))
}

```

## Expected results
To have a full matrix from a combination of all values

## Actual results
d1 and f1 are never used, but we have the correct count of items.
```
[[a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e1 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c1 d2 e2 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e1 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c2 d2 e2 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e1 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c3 d2 e2 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e2 f2] [a1 b1 c4 d2 e2 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e1 f2] [a1 b1 c4 d2 e2 f2] [a1 b1 c4 d2 e2 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e1 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c1 d2 e2 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e1 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c2 d2 e2 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e1 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c3 d2 e2 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e2 f2] [a1 b2 c4 d2 e2 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e1 f2] [a1 b2 c4 d2 e2 f2] [a1 b2 c4 d2 e2 f2]]
```

## Additional context

- https://stackoverflow.com/questions/16248241/concatenate-two-slices-in-go
- https://yourbasic.org/golang/gotcha-append/

## Triaging info

* Concourse version: 7.7.1
* Browser (if applicable):
* Did this used to work?
