### ISSUE TITLE
Impossible to trigger manual check of resource from the WebUI

### ISSUE THREAD

**Issue by aliculPix4D** [concourse/concourse#8350]
## Summary

When user sets the pipeline but forgets to configure the ((branch)) variable, it is not possible to trigger the resource check manually from the WebUI. Forcing the resource check with the fly cli correctly informs the user about the issue: `resource config creds evaluation: undefined vars: branch`

## Steps to reproduce

Create a new pipeline from the template:

```
resources:
- name: repo.git
  source:
    branch: ((branch))
    uri: git@github.com:Pix4D/git@github.com:concourse/concourse.git
  type: git
jobs:
- max_in_flight: 1
  name: test
  plan:
  - get: repo.git
    trigger: true
```

```
$ fly --target devs set-pipeline --pipeline bug-example --config template.yml
```

## Expected results

- clicking on trigger manual check for the repo.git resource should start a check and return an error like in older Concourse versions
i.e `resource config creds evaluation: undefined vars: branch`

## Actual results

It is not possible to trigger a resource check. The message is only: `not checked yet` and it is impossible for the user to understand what is wrong. i.e user forgot to set the branch variable.

Forcing the resource check with the fly cli correctly informs the user about the issue, but the check is not seen in the WebUI.

```
fly --target devs check-resource --resource=bug-example/repo.git
initializing check: repo.git
resource config creds evaluation: undefined vars: branch
errored
```

## Triaging info

* Concourse version: v7.7.1
* Did this used to work? Yes, at least up to v7.6.0
