### ISSUE TITLE
Cannot use variable within task YML?

### ISSUE THREAD

**Issue by petemounce** [concourse/concourse#839]
# Bug Report

## Summary
It does not look like it is possible to use variables within tasks. They work fine in pipelines.

## Detail

I tried to define a task like:
```yml
---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: {{docker_repo_host_port}}/system_test
    tag: "latest"
    insecure_registries: [ "{{docker_repo_host_port}}" ]

inputs:
  - name: my_input

run:
  path: my_input/build.sh
```

Where `docker_repo_host_port` is configured when I `set-pipeline`, using `--load-vars-from my_vars.yml` which contains

```yml
---
docker_repo_host_port: 1.2.3.4:5000
```

If I then `fly --target target login && fly --target target execute --config path/to/task.yml` I get an error

```shell
target saved
error: yaml: line 5: did not find expected key
```

If I quote the value of `repository` then the output is

```shell
target saved
executing build 7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1640M    0 1640M    0     0  16.2M      0 --:--:--  0:01:40 --:--:-- 11.5M
initializing
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to construct named reference: invalid reference format

errored
```

... but this progresses further through the task before failing, which means feedback cycle is a git clone away each time.

## Desired behaviour

* I get a better error message - mention the filename containing the error, and that variables cannot be used in task definitions
* I get an error _sooner_ if the value is invalid - I assume it's resolving to `/system_test`, which will not be a valid docker repository URI (I would have thought)
* I am able to use variables within task definitions as well as pipelines

## Environment

The following can also be handy:

* Concourse version: **2.5.1**
* Deployment type (BOSH/Docker/binary): **vagrant/lite**
* Infrastructure/IaaS: **n/a**
* Browser (if applicable): **Chrome**
* Did this used to work? **Don't know**
