### ISSUE TITLE
Concourse web UI freezes when job requires resource that has passed itself

### ISSUE THREAD

**Issue by evanshort73** [concourse/concourse#84]
If your pipeline contains

```
jobs:
  - name: my-job
  plan:
  - get: my-resource
    passed: my-job
    trigger: true
```

then when you try to look at that pipeline in the web UI, the display area is black and Chrome eventually says that the page has frozen.
