### ISSUE TITLE
Automatically triggered builds use the old/wrong version of the resource even though resource (and pipeline) configuration changed

### ISSUE THREAD

**Issue by aliculPix4D** [concourse/concourse#8404]
## Summary

When resource source configuration is changed (in this example for image.docker resource) one should force a check of the resource to ensure that the automatically triggered built runs with versions that corresponds to the current pipeline configuration.

Currently this is not the case, after the merge of the commit that updates the resource source configuration, the next build will in majority of cases (race between check of two resources) still run using the old version of the resouce.

## Steps to reproduce

Set up a github repository containing the `pipeline-config.yml` configuration file. Set your pipeline and let it finish the first build.
Update the tag for `alpine/git` from `v2.32.0` to `v2.34.2`, commit your change and push it to remote.
Wait for the `repo.git` resource check to detect the new version (commit). The first job (`sync-pipeline`) will reset the pipeline correctly, updating the source configuration. But as it can be seen from the logs in WebUI, the second job (`use-resources`) will still use the the old version `v2.32.0` for its second build.

```
resources:
- name: repo.git
  check_every: 1m
  type: git
  source:
    uri: git@github.com:repo.git
    branch: some-branch

- name: image.docker
  # increased on purpose to ensure bug is triggered, but 1m is also enough. 
  # In production we have 7m as default for both  resources,
  # and its actually enough to trigger the bug in majority of cases.
  check_every: 1h 
  type: registry-image
  source:
    repository: alpine/git
    tag: v2.32.0 # from v2.32.0 update to v2.34.2

jobs:
- name: sync-pipeline
  plan:
  - get: repo.git
    trigger: true
  - set_pipeline: self
    file: repo.git/pipeline-config.yml

- name: use-resources
  plan:
  - get: repo.git
    trigger: true
    passed: 
    - sync-pipeline
  - get: image.docker
  - task: check-versions
    image: image.docker
    config:
      platform: linux
      inputs:
      - name: repo.git
      - name: image.docker
      run:
        path: /bin/sh
        args:
        - -c
        - |
          cd repo.git
          echo "git info"
          cat .git/refs/heads/tag-bug-concourse
          echo "docker image info"
          cat ../image.docker/repository
          echo
          cat ../image.docker/tag
          echo
          cat ../image.docker/digest
```

## Expected results

The second job (`use-resources`) should always use the up-to-date resource `image.docker` if the resource source configuration changed (and with that the pipeline configuration)

In the above example, that means that we expected that the second build run with `v2.34.2` version for `image.docker` resource

## Actual results

The second job (`use-resources`)  uses the old version of the resource `image.docker`, even though the pipeline configuration does not contain this version anymore.

In the above example, that means that the second build runs with `v2.32.0` version for `image.docker` resource instead of `v2.34.2`.

## Triaging info

Concourse version: v7.7.1
Did this used to work? I don't think so.
