### ISSUE TITLE
Support for read/write locking around jobs

### ISSUE THREAD

**Issue by vito** [concourse/concourse#842]
# Feature Request

## What challenge are you facing?

#698 showed a use case for having "read" jobs not block each other, but "write" jobs block other write jobs and also other "read" jobs. A simplified example would be a "write" job that modifies a cluster and many "read" jobs that can run tests against it in parallel.

## A Modest Proposal

Dumb mockup:

```yaml
jobs:
- name: test-a
  read_lock: [my-env]
- name: test-b
  read_lock: [my-env]
- name: deploy-env
  write_lock: [my-env]
```

...but I think it's worth thinking a bit more about it. And maybe consolidate with `serial_groups`?
