### ISSUE TITLE
Step "set-pipeline" exposes sensitive information

### ISSUE THREAD

**Issue by holgerstolzenberg** [concourse/concourse#8474]
## Summary
The diff output when using the `set-pipeline` step exposes sensitive data in the web UI.

## Steps to reproduce
Use the `set-pipeline` step in one of your builds and have a look at the diff log that is printed out.
If you have sensitive data (coming from the secrets store), they will be printed to the Web UIs log output fully readable.

## Expected results
Sensitive data (like secrets) should be masked/hidden within the output.

## Triaging info
* Concourse version: `7.8.1`
* Browser (if applicable): `Chrome 03.0.5060.114 (Official Build) (x86_64)` (Mac)
* Did this used to work?: Not yet I guess

**Comment by will-gant** [comment]
Yep, here's a pipeline that will reproduce this issue if you set credentials named `cred1` and `cred2` in your secrets manager:

```
jobs:
- name: test
  plan:
  - task: test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      params:
        SECRET: ((cred1))
      outputs:
        - name: pipeline
      run:
        path: /bin/sh
        args:
          - -cx
          - |
            cat <<EOF >> pipeline/test.yml
            jobs:
            - name: test
              plan:
              - task: test
                config:
                  platform: linux
                  image_resource:
                    type: registry-image
                    source: {repository: alpine}
                  params:
                    SECRET: ((cred2))
                  outputs:
                    - name: pipeline
                  run:
                    path: /bin/sh
                    args:
                      - -cx
                      - |
                        cat <<EOF >> pipeline/test.yml
                        jobs:
                        - name: test
                          plan:
                          - task: test
                            config:
                              platform: linux
                              image_resource:
                                type: registry-image
                                source: {repository: alpine}
                              params:
                                SECRET: ((cred1))
                              outputs:
                                - name: pipeline
                              run:
                                path: /bin/sh
                                args:
                                  - -cx
                                  - |
                                    echo $SECRET
                          - set_pipeline: self
                            file: pipeline/test.yml
            EOF
  - set_pipeline: self
    file: pipeline/test.yml
```

Output:

<img width="686" alt="Screenshot 2022-07-23 at 08 17 47" src="https://user-images.githubusercontent.com/20523607/180594880-e55b16b9-d684-4b59-aba6-739307e09e30.png">

**Comment by lrstanley** [comment]
> Yep, here's a pipeline that will reproduce this issue if you set credentials named `cred1` and `cred2` in your secrets manager:
> [...]

So I don't actually think that is a good example -- if you reference vars inline, it will write the file with bash using the variable in question, not the `((var))` reference itself. In that instance, it is working correctly, because you're replacing that field with an actual static value.

**Comment by lrstanley** [comment]
Tested this 7.8.1 and unable to replicate without using inline variable references:
![](https://ls-screen.s3.us-west-004.backblazeb2.com/2022/07/chrome_iievzXekQH.png)

@holgerstolzenberg is your usecase similar to that of @will-gant's? If so, this is expected behavior. Similar to when you do something like:

```yaml
params:
    SECRET: ((cred1))
```

Concourse renders that reference as it at execution time and passes it to the underlying task. This also works when using the `run` section, for example:

```yaml
run: { path: /bin/sh, args: ["-cx", "echo some secret here: ((cred1))"] }
```

The above would execute the following:

```console
$ sh -cx "echo some secret here: my-resolved-secret"
```

As such, writing the pipeline yaml inline, inside of the pipeline like @will-gant is, would inline the secret. When using set-pipeline, the ideal scenario is it references a file that was pulled from something like git, and doesn't get written inline (FWIW, writing inline is beneficial for various other scenarios, though).

**Comment by will-gant** [comment]
Yep, I'm an absolute numpty. Profuse apologies for the false alarm! Put it all in-line just so I could test out the issue reported here without pushing files to git, and yeah, obviously had a brain fart as that method meant the secret wasn't being rendered in the set_pipeline step at all. Whoops.

**Comment by holgerstolzenberg** [comment]
I stumbled upon this one using the new instanced pipeline feature. I have a job that creates instanced pipelines. During execution of the job a `set-pipeline` step creates the instanced pipeline and the diff is shown in the ui. There sensitive information is exposed. 

Please see screenshot attached:

<img width="939" alt="Screenshot 2022-08-01 at 12 54 31" src="https://user-images.githubusercontent.com/282736/182133596-d4ed95f7-1531-4886-b05b-36f17cba2f34.png">

**Comment by lrstanley** [comment]
@holgerstolzenberg could you provide a yaml example that can be used to replicate the issue?

**Comment by holgerstolzenberg** [comment]
```yaml
- name: hotfix-prepare
    build_log_retention:
      <<: *log_retention
    serial: true
    plan:
      - in_parallel:
        - get: hotfix-branches
          trigger: true
        - get: pipeline
          passed: [update-pipeline]
      - load_var: branches
        file: hotfix-branches/branches.json
      - across:
        - var: branch
          values: ((.:branches))
          max_in_flight: all
        do:
          - task: "prepare-hotfix-version"
            file: "pipeline/tasks/prepare-hotfix-version.yml"
            vars:
              bash_version: ((bash_version))
              branch: ((.:branch.name))
              docker_hub_mirror: ((docker_hub_mirror))
          - load_var: hotfix-version
            file: versions/hotfix
          - set_pipeline: ((artifact_id))-hotfixes # try to use slash in here, e.g. ((artifact_id))/((hotfix-version))
            file: pipeline/hotfix.yml
            instance_vars:
              branch: ((.:branch.name))
            vars:
              artifact_id: ((artifact_id))
              # all other vars
    on_failure: *email-notification
```

**Comment by xtremerui** [comment]
@holgerstolzenberg could you please verify that https://github.com/concourse/concourse/blob/master/atc/atccmd/command.go#L249 is enabled?

**Comment by holgerstolzenberg** [comment]
@xtremerui
Nope the secrets are coming from the `vars` section of the `set_pipeline` step.

I wasn't aware of the `EnableRedactSecrets` configuration flag. I activated it and tested it - and yes - now the vars are obfuscated. A small downside is, that there are also variables obfuscated, that are not secrets.

How does Concourse decide if a given value is a secret?

**Comment by xtremerui** [comment]
it is by a regex to looking for patterns like `((...))`. A build tracker will store those matching patterns in a map. When in build log, it will iterate through line by line and replace the interpolated secrect value with ((redacted)) if there is match in the map.

**Comment by zagr0** [comment]
hi, we have very similar issue with secret exposing
In our scenario we are trying to keep our pipeline code DRY, utilizing single template file and we are passing to `set_pipeline` step vars values that should be referencing to secrets in vault, like this:
```
jobs:
- name: pipeline1
  plan:
  - set_pipeline: my-pipeline-1
    file: repo/my-pipeline.yml
    vars:
      secret: ((secret_name_1_in_vault))
- name: pipeline2
  plan:
  - set_pipeline: my-pipeline-2
    file: repo/my-pipeline.yml
    vars:
      secret: ((secret_name_2_in_vault))
```
Variable `secret` is used inside pipeline template `my-pipeline.yml` and should be passes as value `'((secret_name_1_in_vault))'`
Even if we enable `EnableRedactSecrets` flag it's still cause that secrets are stored as values in the pipeline code as rendered / interpolated on `set_pipeline` step (Secrets can be got with `fly get-pipeline`)

Can we pass somehow string value `((secret_name_1_in_vault))` as reference to external secret variable from `set_pipeline` step to avoid be rendered? so we can use single template pipeline file and don't expose / store secret values in concourse

Tried to escape `((`  `))` with multiple ways, but with no luck...

**Comment by zagr0** [comment]
as an update we've found some kind of workaround to avoid interpolation of secrets
with vars of set_pipeline we pass string, the name of variable, like this
```
jobs:
- name: pipeline1
  plan:
  - set_pipeline: my-pipeline-1
    file: repo/my-pipeline.yml
    vars:
      secret: secret_var_name_1_in_vault
```
but inside of pipeline template file we use notation like `((((secret))))`, `((secret_var_name_1_in_vault))` will be interpolated when target pipeline is built

**Comment by achille1789** [comment]
Hi, I faced a similar issue. When set-pipeline sets the secret, on the UI it shows the value as ((redacted)), but when set-pipeline removes the secret, it shows its value in clear.
Here is the snippet:
```
    - set_pipeline: my-child-pipeline
      file: my_pipeline_file.yml
      vars:
        my_secret: ((super-secret))
```
When I run the above, on the web UI correctly it shows the change as `+ my_secret: ((redacted))`
but after that I set the secret, if I remove it, on the UI it shows `- my_secret: secret_value_in_clear`

Thanks
