### ISSUE TITLE
fly commands do not fully redact secrets from build logs

### ISSUE THREAD

**Issue by aliculPix4D** [concourse/concourse#8477]
## Summary

fly commands do not fully redact secrets, even though secrets are correctly redacted in the WebUI. 
The issue was encountered with following commands:
- `fly watch`
- `fly execute`
- `fly trigger-job --watch`

Similar, but stale and closed issue: https://github.com/concourse/concourse/issues/5064

## Steps to reproduce
Example 1:  `task.yml` used with fly execute
```
---
platform: linux

image_resource:
  type: registry-image
  source: {repository: busybox}

run:
  path: sh
  args: 
  - -c
  - |
   env # GOOD
   echo $SECRET # GOOD
   echo ((test_parameter)) # BAD
params:
  SECRET: ((test_parameter))
```
Example 2:  `pipeline.yml` used in combination with `fly watch` and `fly trigger-job --watch`
```
---
jobs:
- name: redact-secrets
  plan:
  - task: secrets
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: sh
        args: 
        - -c
        - |
        env # GOOD
        echo $SECRET # GOOD
        echo ((test_parameter)) # BAD
    params:
      SECRET: ((test_parameter))
```

Both examples will result in leaked secret in your terminal:
```
selected worker: wrk-lin-0
running sh -c env # GOOD
echo $SECRET # GOOD
echo **LEAKED_SECRET_VALUE** # BAD
....
SECRET=((redacted))
....
((redacted))
((redacted))
succeeded
```

## Expected results
- all secrets are redacted from build logs, even when using fly commands

## Actual results
Secrets from credential manager are leaking in build logs when using some fly commands

## Triaging info

* Concourse version: v7.8.1
* Browser (if applicable): N/A
* Did this used to work? No.
