### ISSUE TITLE
Concourse stops jobs with error ProcessNotFoundError

### ISSUE THREAD

**Issue by Kifah** [concourse/concourse#8483]
On many concourse pipelines, which run a docker build task, we get the error:

`backend error: Exit status: 404, message: {"Type":"ProcessNotFoundError","Message":"unknown process: task","Handle":"","ProcessID":"task","Binary":""}`

The snippet from the yml job responsible is the following:

```
      - task: build-task-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: jprelph/oci-build-task
          inputs:
            - name: src-docker-repo
          outputs:
            # The oci-build-task outputs the built container image in a directory called image
            - name: image

          run:
            path: build

```

Has anyone faced a similar error? and if yes, what is the best workaround or better: solution for it?
