### ISSUE TITLE
Time resource not getting new versions since the new year

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse#849]
* Concourse version: 2.5.1

Resource config:
```
- name: morning-timer
  type: time
  source:
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    start: 13:05 -0000
    stop: 13:10 -0000
```

The last version that was generated was `2016-12-30T13:05:09.7024715Z`

From the check container:
```
bash-4.3# echo '{"source":{"days":["Wednesday"],"start":"00:00","stop":"23:59"}}' | /opt/resource/check
[{"time":"2017-01-04T17:26:12.939598502Z"}]

bash-4.3# echo '{"source":{"days":["Wednesday"],"start":"00:00","stop":"23:59"},"version":{"time":"2016-12-30T13:05:09.7024715Z"}}' | /opt/resource/check
[{"time":"2016-12-30T13:05:09.7024715Z"}]
```

We have 5 pipelines with similar time resources, none of them are triggering. The above one has been untouched. The others were paused over the holiday, so their last version is ~2017-12-23, and unpausing the pipelines has left them in a similar non-triggering state.
