### ISSUE TITLE
Over-scheduling worker node when using volume-locality strategy in 7.8.2

### ISSUE THREAD

**Issue by robbadler** [concourse/concourse#8503]
## Summary

Concourse 7.8.2 deployed on GKE via Concourse helm chart.
Seeing workers get scheduled above the 230 (and even the 250 hard limit) containers, resulting in `max-containers-reached` errors in concourse jobs.

## Steps to reproduce
helm deploy, with values.yaml:
```
concourse:
  web:
    containerPlacementStrategies:
    - limit-active-containers
    - volume-locality
    - fewest-build-containers
    limitActiveContainers: 230
```

## Expected results

That concourse respects the `limitActiveContainers` value of 230, or at least not over-schedule past 250, which is causing CI errors.

## Actual results

![Screen Shot 2022-07-27 at 4 04 57 PM](https://user-images.githubusercontent.com/643334/181387341-dab3cd0e-5ace-412f-b474-35a2e1c98a3d.png)

## Triaging info

* Concourse version: 7.8.2
* Browser (if applicable):
* Did this used to work? Previous deployment was with 7.6.0, and we did not see this issue.
