### ISSUE TITLE
Failed to create volume 

### ISSUE THREAD

**Issue by JoHaHu** [concourse/concourse#8517]
## Summary

I installed concourse via the provided Helmchart on Kubernetes.
But i cant run pipelines.

## Steps  to reproduce

install with Helm chart
```
persistence:
    enabled: true
    worker:
      storageClass: nfs
```

`fly -t target check-resource -r root-pipeline/pipelines`

## Actual results

run check: find or create container on worker concourse-worker-0: failed to create volume errored

## Additional context
I've tried running it with different runtimes and baggageclaim drivers with no success

## Triaging info

* Concourse version: 7.8.1
