### ISSUE TITLE
"Permission Denied" running any task in RHEL8

### ISSUE THREAD

**Issue by c4lliope** [concourse/concourse#8607]
## Summary

Running any pipeline step produces an error on RHEL8:

## Steps to reproduce

Run `fly set-pipeline ...` on:

```yml
jobs:
- name: hello
  plan:
  - task: say-hello
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, concourse!"]
```

## Expected results

Pipeline should run.

## Actual results

```
run check: find or create container on worker lcsdevops01.us.house.gov: starting task: new task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error preparing rootfs: mount /concourse/memory/volumes/live/daceb497-c533-458b-41c4-675e69454d92/volume:/concourse/memory/volumes/live/daceb497-c533-458b-41c4-675e69454d92/volume, flags: 0x5000: permission denied: unknown
```

## Additional context

```bash
[gyoung@lcsdevops01 concourse.2]$ runc --version
runc version 1.1.3
spec: 1.0.2-dev
go: go1.17.12
libseccomp: 2.5.2
```

```bash
[gyoung@lcsdevops01 concourse.2]$ uname -a
Linux lcsdevops01.domain.com 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
[gyoung@lcsdevops01 concourse.2]$ x="/concourse/memory/volumes/live/daceb497-c533-458b-41c4-675e69454d92/volume"
[gyoung@lcsdevops01 concourse.2]$ (while [ $x != "/" ]; do sudo ls -ld $x; x=$(dirname $x); done)
ls: cannot access '/concourse/memory/volumes/live/daceb497-c533-458b-41c4-675e69454d92/volume': No such file or directory
ls: cannot access '/concourse/memory/volumes/live/daceb497-c533-458b-41c4-675e69454d92': No such file or directory
drwxr-x---. 4 root root 94 Oct 27 14:11 /concourse/memory/volumes/live
drwxr-xr-x. 5 root root 42 Oct  7 19:32 /concourse/memory/volumes
drwxr-xr-x 7 root root 142 Oct  7 19:56 /concourse/memory
drwxr-xr-x. 3 root root 20 Oct  7 11:22 /concourse
```
