### ISSUE TITLE
Across step no longer reporting results on UI

### ISSUE THREAD

**Issue by cole-abramson** [concourse/concourse#8610]
## Steps to reproduce
Given the following pipeline:
```
jobs:
  - name: test
    plan:
      - across:
          - var: iteration
            values: ['1', '2', '3', '4', '5', '6']
            max_in_flight: 3
        do:
          - task: deploy-((.:iteration))
            config:
              image_resource:
                type: registry-image
                source: { repository: alpine }
              platform: linux
              params:
                ITERATION: ((.:iteration))
              run:
                path: /bin/sh
                args:
                  - -ec
                  - |
                    echo $ITERATION
                    if [ $ITERATION == "2" ]; then
                      exit 1
                    fi
                    
                    sleep 10
```

## Expected results
On `v7.7.1`, UI would report like this:
<img width="1185" alt="Screen Shot 2022-11-01 at 12 29 31 PM" src="https://user-images.githubusercontent.com/8454489/199285956-a1c14afe-1b47-4d3e-b468-e890f0d506ea.png">

## Actual results
After `v7.7.1`, it reports like this:
<img width="1186" alt="Screen Shot 2022-11-01 at 12 30 54 PM" src="https://user-images.githubusercontent.com/8454489/199286073-20937681-43dc-4f41-bd6f-6099d5fdc5e9.png">

The steps appear as if they were not executed even though they were.

## Triaging info

* Concourse version: >`v7.7.1`
* Did this used to work? yes
