### ISSUE TITLE
Bundled registry-image version doesn't support authenticating with GAR (Google artifact registry)

### ISSUE THREAD

**Issue by stigtermichiel** [concourse/concourse#8635]
## Summary

The latest concourse version (7.8.3) is bundled with registry-image-resource version v1.5.1. This version of the registry-image breaks when performing a `check`  trying to authenticate to a GAR-repo.

When running the same check with the registry-image-resource on the master-branch, this seems to be fixed.

## Steps to reproduce

Try running a check on a GAR-repo with concourse version 7.8.3. Possible resource_type config:

```
- check_every: 24h0m0s
  name: halfpipe-slack-resource
  source:
    password: ((a.private_key))
    repository: eu.gcr.io/repo/halfpipe-slack-resource //a GCR-repo that has been switched to GAR
    tag: latest
    username: _json_key
  type: registry-image
```

## Expected results
A working check step. 

## Actual results

```
selected worker: 1848c69c-dc81-4d72-bff1-7b19bf96a3d2

2022/11/29 20:41:54 No matching credentials were found for "eu.gcr.io"

ERRO[0000] checking origin eu.gcr.io/halfpipe-test2/cf-resource-v2 failed: list repository tags: GET https://eu.gcr.io/v2/token?scope=repository%3Arepo%2Fhalfpipe-slack-resource%3Apull&service=eu.gcr.io: UNAUTHORIZED: failed authentication 
```

## Additional context

This has been fixed on the master-branch of the registry-image-resource. So I think releasing a new version of the resource and bundling it in a new version of concourse would do the trick. 

I think the fix was to update this: `github.com/google/go-containerregistry v0.9.0` to `github.com/google/go-containerregistry v0.12.1`

## Triaging info

* Concourse version: 7.8.2
