### ISSUE TITLE
Pipeline freezes when managing resource trough set_pipeline

### ISSUE THREAD

**Issue by Kump3r** [concourse/concourse#8641]
## Summary

When managing the resource trough set_pipeline in concourse pipeline itself, the version history for that resource is wiped since the whole resource changes. After set_pipeline the input, of this resource, for the following job, doesn't trigger the job itself. The resource gets the latest version of the resource (by design I guess). In order for the pipeline to resume, you can trigger the next job manually or pause/unpause pipeline and the next job starts.

## Steps to reproduce
```
resources:
- name: repo
  type: git
  source: 
    branch: main
    password: <password-for-git>
    skip_ssl_verification: true
    submodule_credentials:
    - host: <some-host>
      password: <some-password>
      username: <some-user>
    uri: <uri>

jobs:
  - name: configure-self
    plan:
    - get: repo
      trigger: true
    - set_pipeline: self
      file: <some/path/to/pipeline>

  - name: hello
    plan:
      - get: repo
        trigger: true
        passed: [configure-self]
      - task: echo-hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello world!"]
```
If you for example change the branch of the resource. The pipeline starts as expected it reconfigures itself and then it freezes before getting the repo in the second task. After set_pipeline, the resource cleans the version history and fetches the latest resource. This seems by design looking at last sentence of version [here](https://concourse-ci.org/get-step.html#schema.get.version)
As I said above even a simple pause/unpause after it triggers the get step, otherwise it remains stuck.

## Expected results

Concourse pipeline continues with get step, even with a short delay for fetching the latest version.

## Actual results

Concourse pipeline freezes before get step, although the get step is looking at the previous commit and the resource to the latest

## Additional context

N/A

## Triaging info

* Concourse version: 7.8.2
* Browser (if applicable): N/A
* Did this used to work? I am not sure, I guess not.
