### ISSUE TITLE
on_failure not taken into account on in_parallel step with steps:

### ISSUE THREAD

**Issue by bnoorduin** [concourse/concourse#8643]
## Summary

When I use an in_parallel step with the parallel steps defined under 'steps:', the on_failure modifier is not taken into account.

## Steps to reproduce

Config like this:

```yaml
      - in_parallel:
          fast_fail: true
          steps:
            - task: execute-tu-and-sonar
              file: repo-common-code/sldng/execute-sonar.yml
            - task: analyze-enf-tester
              file: repo-common-code/sldng/execute-enf-tester.yml
              ensure:
                try:
                  task: sync-test-report-to-s3
                  file: repo-common-code/s3/s3_copy.yml
            - put: image-docker
          on_failure:
            try:
              task: delete-temporary-image
              file: repo-common-code/tools/artifactory-delete-image.yml
```

## Expected results

```console
$ alias fsp='fly -t $CONCOURSE_TARGET sp -c ci/pipeline.yml -p $(basename "$(printf "%q\n" $(pwd))") $CONCOURSE_VARS'
$ f sp -p test -c ci/pipeline.yml
$ f gp -p test | yq .jobs.[1].plan.[2]
in_parallel:
  steps:
    - file: repo-common-code/sldng/execute-sonar.yml
      task: execute-tu-and-sonar
    - ensure:
        try:
          file: repo-common-code/s3/s3_copy.yml
          task: sync-test-report-to-s3
      file: repo-common-code/sldng/execute-enf-tester.yml
      task: analyze-enf-tester
    - put: image-docker
on_failure:
  try:
    file: repo-common-code/tools/artifactory-delete-image.yml
    task: delete-temporary-image
```

## Actual results

```console
$ f gp -p test | yq .jobs.[1].plan.[2]
in_parallel:
  steps:
    - file: repo-common-code/sldng/execute-sonar.yml
      task: execute-tu-and-sonar
    - ensure:
        try:
          file: repo-common-code/s3/s3_copy.yml
          task: sync-test-report-to-s3
      file: repo-common-code/sldng/execute-enf-tester.yml
      task: analyze-enf-tester
    - put: image-docker
```

## Triaging info

* Concourse version: 7.8.3
* Browser (if applicable):
* Did this used to work? never tried

**Comment by felsta** [comment]
Are you sure about your indentation? Try
```yaml
      - in_parallel:
          fast_fail: true
          steps:
            - task: execute-tu-and-sonar
              file: repo-common-code/sldng/execute-sonar.yml
            - task: analyze-enf-tester
              file: repo-common-code/sldng/execute-enf-tester.yml
              ensure:
                try:
                  task: sync-test-report-to-s3
                  file: repo-common-code/s3/s3_copy.yml
            - put: image-docker
        on_failure:
          try:
            task: delete-temporary-image
            file: repo-common-code/tools/artifactory-delete-image.yml
```
