### ISSUE TITLE
Cannot read credentials from Vault

### ISSUE THREAD

**Issue by seifertdan** [concourse/concourse#8663]
## Summary

Using Vault: 1.11.6+

Reading credentials from Vault is failing:

Web UI:
```
resource config creds evaluation: missing field 'docker_password_field_name' in var: "/common/secrets".docker_password_field_name
```

Log:
```
{"timestamp":"2023-01-10T17:02:13.337358613Z","level":"info","source":"atc","message":"atc.tracker-imb.run.finish.errored","data":{"build":"check","error":"resource config creds evaluation: missing field 'docker_password_field_name' in var: \"/common/secrets\".docker_password_field_name","pipeline":"my_test_pipeline","pre_build_id":989,"resource":"docker_image_name","session":"23.989.4","team":"main"}}
```

## Steps to reproduce

**Concourse pipeline manifest**:
```
resources:
- name: docker_image_name
  type: docker-image
  source:
    repository: docker_repo_name
    tag: docker_tag_name
    username: docker_username
    password: ((/common/secrets.docker_password_field_name))
...
```

**Concourse Vault config**:
```
CONCOURSE_VAULT_NAMESPACE: "ns1"
CONCOURSE_VAULT_PATH_PREFIX: "/ns2/kv/data"
CONCOURSE_VAULT_LOOKUP_TEMPLATES: "/{{.Secret}}" 
CONCOURSE_VAULT_AUTH_BACKEND: "approle"
...
```

**Vault structure**:
Using `kv2` for `common/secrets`. Pseudo path:
```
/ns1/ns2/common/secrets
```
`secrets` is a JSON object:
```
{
  "docker_password_field_name": "very_secret_pw",
  "more_key": "value_pairs",
  ...
}
```

## Expected results
Get the password for docker

## Actual results
See error message above. Why is the error message formatted odd (quotes around the path)?

## Additional context
We are using Vault across multiple applications and do not want to change the structure. This means we had to eliminate `/concourse`, team and pipeline names via Concourse configuration from the queries (see `CONCOURSE_VAULT_PATH_PREFIX` and `CONCOURSE_VAULT_LOOKUP_TEMPLATES`.

It is possible to query the credentials via Vault HTTP API:
```
curl -H "X-Vault-Token: <approle_vault_token>" -X GET https://<url>/v1/ns1/ns2/kv/data/common/secrets

{
  "request_id":"XXXX",
  ...
  "data":{"data":{
    "docker_password_field_name":"very_secret_pw",
    "more_key":"value_pairs",
    ...
    }
  ...
}
```

## Triaging info

* Concourse version: 7.8.2
* Browser (if applicable): Firefox
* Did this used to work?

**Comment by seifertdan** [comment]
Completely removing Vault as primary credential store and using Credhub again + Vault via `var_sources` yields this:

- Reading credentials with `client_token` **directly works:**

```
var_sources:
- config:
    client_token: ((client_token))
    lookup_templates:
    - /{{.Secret}}
    namespace: ns1/ns2
    path_prefix: kv
    server_name: vault_server_name
    url: https://url
  name: vault
  type: vault


resources:
- name: docker-image
  type: docker-image
  source:
    repository: ${docker_repo}
    tag: ${tag}
    username: ${docker_user}
    password: ((vault:/mypath/secrets.foo))
```

- Using the same configuration but `role_id` and `secret_id` instead of `client_token` is **not working**:

```
var_sources:
- config:
    auth_backend: approle
    auth_params:
      role_id: ((role_id))
      secret_id: ((secret_id))
    lookup_templates:
    - /{{.Secret}}
    namespace: ns1/ns2
    path_prefix: kv
    server_name: vault_server_name
    url: https://url
  name: vault
  type: vault

resources:
- name: docker-image
  type: docker-image
  ... same
```
