### ISSUE TITLE
cf authentication fails on 7.9.1

### ISSUE THREAD

**Issue by gaigaslab-operations** [concourse/concourse#8696]
BOSH deployment
We upgraded from 7.8.3 -> 7.9.1
We use integrated authentication for admin and cf authentication for developers, and one team uses github auth.

web nodes were in error after upgrade completed.
Failed with:
`error: server: Failed to open connector cf: failed to open connector: unknown connector type "cf"`

Pertinent config:
```
      cf_auth:
        api_url: https://<redacted>
        ca_cert: |
        <redacted>
        certificate: |
        <redacted>
        client_id: concourse-platform-1.<redacted>
        client_secret: <redacted>
        skip_ssl_validation: true       
      displayer_user_id_per_connector:
      - cf:email
      - github:username
```

Reverting to 7.8.3 versions restored web node functionality.

**Comment by blyles** [comment]
This was mentioned here as well - https://github.com/concourse/concourse-bosh-release/issues/172

**Comment by jhohiii** [comment]
I'm sorry, @xtremerui, I don't understand what I need to do to use the cloudfoundry connector.

The BOSH SPEC file still references 'cf' as the authentication specification for cloudfoundry.

How do I get concourse to authenticate via cloudfoundry?

**Comment by xtremerui** [comment]
@jhohiii the fix is done in a way that doesn't require change of the flag, and thus bosh spec and helm values ref to the connector remains the same. You will need to wait for next release of them though.

**Comment by xtremerui** [comment]
@jhohiii next release of Concourse i.e. v7.9.2

**Comment by blyles** [comment]
This is unfortunately still broken for us, we're debugging but it doesn't seem to work from everything that we've tried.

**Comment by xtremerui** [comment]
@Kump3r could you share how do you specify the --cf-xx config?

**Comment by Kump3r** [comment]
@xtremerui 
We have a bosh deployment. Using OPS and VARS files we configure the properties in the web spec.
Example web properties from a generated manifest
```
      cf_auth:
        api_url: https://some_url/
        client_id: some_id
        client_secret: ((!some_secret))
```
Thanks for looking into it!
