### ISSUE TITLE
7.9.1 - pipeline job to "bosh recreate" the Concourse db fails often and continues on to the next job

### ISSUE THREAD

**Issue by burgerjeffrey** [concourse/concourse#8711]
## Summary

I upgraded from 7.4.1 to 7.9.1 and was running pipeline tests against the new Concourse.  I am using a pipeline that uses bosh to recreate the Concourse database.  It fails 1/3 of the time and it continues to the next job to repave the workers.  I have been running this Concourse repave pipeline for over two years without this issue until 7.9.1.

Note: this pipeline is repaving Concourse itself.  First the database, then the workers.  The use of the tags are to redirect the work to a set of workers with the tag repave.

## Steps to reproduce

Job # 1

```
- name: repave-db
  plan:
  - in_parallel:
      steps:
      - get: platform-automation-image
        params:
          unpack: true
        tags:
        - repave
      - get: configuration
        tags:
        - repave
        trigger: true
      - get: concourse-timer
        passed:
        - repave-webs
        tags:
        - repave
        trigger: true
  - file: configuration/tasks/prepare-tasks-with-secrets-custom.yml
    image: platform-automation-image
    input_mapping:
      config: configuration
      custom-tasks: configuration
      tasks: configuration
      vars: configuration
    on_abort:
      params:
        alert_type: aborted
      put: slack-notification
    on_error:
      params:
        alert_type: errored
      put: slack-notification
    on_failure:
      params:
        alert_type: failed
      put: slack-notification
    output_mapping:
      tasks: custom-tasks
    params:
      CONFIG_PATHS: |
        config/config/opsman/2.10/opsman.yml config/config/opsman/2.10/director-concourse.yml config/config/pivotal-telemetry-om/1.2.4/pivotal-telemetry-om.yml config/env
      TASKS_PATH: tasks/tasks
      VARS_PATHS: vars/environments/pcf1-dg-com-ss-itdev-01/vars
    task: prepare-tasks-with-secrets-custom
  - file: custom-tasks/tasks/bosh-recreate.yml
    image: platform-automation-image
    input_mapping:
      env: configuration
    on_abort:
      params:
        alert_type: aborted
      put: slack-notification
    on_error:
      params:
        alert_type: errored
      put: slack-notification
    on_failure:
      params:
        alert_type: failed
      put: slack-notification
    params:
      CONCOURSE_DEPLOYMENT: pcf1-dg-com-ss-itdev-01-controlplane
      ENV_FILE: env/env.yml
      INSTANCE_GROUP: db
    tags:
    - repave
    task: recreate-db
  serial: true
```

Job # 2
```
  - name: repave-workers
  plan:
  - in_parallel:
      steps:
      - get: platform-automation-image
        params:
          unpack: true
        tags:
        - repave
      - get: configuration
        tags:
        - repave
      - get: platform-trigger
        passed:
        - repave-db
        tags:
        - repave
        trigger: true
      - get: concourse-timer
        passed:
        - repave-db
        tags:
        - repave
        trigger: true
  - file: configuration/tasks/prepare-tasks-with-secrets-custom.yml
    image: platform-automation-image
    input_mapping:
      config: configuration
      custom-tasks: configuration
      tasks: configuration
      vars: configuration
    on_abort:
      params:
        alert_type: aborted
      put: slack-notification
    on_error:
      params:
        alert_type: errored
      put: slack-notification
    on_failure:
      params:
        alert_type: failed
      put: slack-notification
    output_mapping:
      tasks: custom-tasks
    params:
      CONFIG_PATHS: |
        config/config/opsman/2.10/opsman.yml config/config/opsman/2.10/director-concourse.yml config/config/pivotal-telemetry-om/1.2.4/pivotal-telemetry-om.yml config/env
      TASKS_PATH: tasks/tasks
      VARS_PATHS: vars/environments/pcf1-dg-com-ss-itdev-01/vars
    task: prepare-tasks-with-secrets-custom
  - file: custom-tasks/tasks/bosh-recreate.yml
    image: platform-automation-image
    input_mapping:
      env: configuration
    on_abort:
      params:
        alert_type: aborted
      put: slack-notification
    on_error:
      params:
        alert_type: errored
      put: slack-notification
    on_failure:
      params:
        alert_type: failed
      put: slack-notification
    params:
      CONCOURSE_DEPLOYMENT: pcf1-dg-com-ss-itdev-01-controlplane
      ENV_FILE: env/env.yml
      INSTANCE_GROUP: worker
    tags:
    - repave
    task: recreate-workers
  serial: true
```

## Expected results

Expected that if  job # 1 failed, job # 2 wouldn't run.

## Actual results

Job # 2 runs regardless if job # 1 fails or not.

## Triaging info

* Concourse version: 7.9.1
* Did this used to work? Yes, in 7.4.1 & 6.X
