### ISSUE TITLE
AWS EKS IRSA Integration For Worker Containers

### ISSUE THREAD

**Issue by ChrisJBurns** [concourse/concourse#8716]
## Summary
Currently if you deploy Concourse to EKS Kubernetes, the permissions that the pipeline jobs that occur on the workers will be controlled via the IAM policies that are attached to the EKS worker nodes. These are then propagated into the container workloads that exist within pipelines. If however you have IRSA setup, and attach it via the ServiceAccount Annotations:

```yaml
    rbac:
      webServiceAccountAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-NUM:role/tooling-concourse-worker
      workerServiceAccountAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-NUM:role/tooling-concourse-worker
```

The pipeline jobs on the Concourse workers do not assume these roles, they still take their permissions from the IAM Role that is attached to the underlying Kubernetes EC2 Node.

Can we please have a feature that allows us to use IRSA with the underlying pipeline containers, this then removes us having wide ranging permissions attached to the nodes and to move towards a more fine grained principle of least privilege approach.
