### ISSUE TITLE
"Quickstart" Guide doesn't work on M1 Mac due to docker compose issue

### ISSUE THREAD

**Issue by tedivm** [concourse/concourse#8719]
## Summary

[The quickstart page](https://concourse-ci.org/quick-start.html) recommends using a supplied docker compose file to start.

Running this docker compose file on an M1 fails.

## Steps to reproduce

```
$ curl -O https://concourse-ci.org/docker-compose.yml
$ docker-compose up -d
```

## Expected results

Concourse launches.

## Actual results

1. Attempting it directly-

```
 ⠋ concourse The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                            0.0s
...
concourse-concourse-1     | {"timestamp":"2023-03-29T18:05:21.330364719Z","level":"error","source":"worker","message":"worker.garden-runner.logging-runner-exited","data":{"error":"Exit trace for group:\ncontainerd-garden-backend exited with error: setup host network failed: create chain or flush if exists failed: running [/usr/sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait]: exit status 3: iptables v1.8.7 (legacy): can't initialize iptables table `filter': iptables who? (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n\ncontainerd exited with nil\n","session":"8"}}
...
concourse-concourse-1     | containerd-garden-backend exited with error: setup host network failed: create chain or flush if exists failed: running [/usr/sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait]: exit status 3: iptables v1.8.7 (legacy): can't initialize iptables table `filter': iptables who? (do you need to insmod?)
```

2. Attempting it with the "dev" image, [from this issue](https://github.com/concourse/concourse/issues/8558#issuecomment-1487766343).

```
concourse-concourse-1     | error: the required flag `--worker-work-dir' was not specified
concourse-concourse-1 exited with code 1
```

Note that this does resolve the "wrong architecture" problem but otherwise seems like a broken image.

## Additional context

This is with a fresh docker desktop install.

## Triaging info

* Concourse version: latest
* Browser (if applicable):
* Did this used to work? No idea, I'm new to concourse. I assume it did due to the documentation recommending it.

**Comment by ajs95** [comment]
Try with below change in docker-compose.yml
      CONCOURSE_WORKER_RUNTIME: "houdini"

**Comment by tedivm** [comment]
I've tried with the "alpine" and "python" containers as well, just in case, but end up with the same error-

> find or create container on worker 06630b9c1782: stream image metadata file: failed to stream out from volume

**Comment by danlsgiga** [comment]
Here's a working docker-compose.yml file I got working on my Mac M1. The key is to use the `concourse/concourse:7.9.1-ubuntu` image and change / add the following env vars:

```
CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: naive
CONCOURSE_WORKER_BAGGAGECLAIM_DISABLE_USER_NAMESPACES: true
```

### Full docker-compose.yml file

```
version: '3.9'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:7.9.1-ubuntu
    platform: linux/amd64
    command: quickstart
    privileged: true
    depends_on:
      - concourse-db
    ports:
      - "8080:8080"
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_SWEEP_INTERVAL: 24h
      # If running on a non M1/M2 MacOS, optionally change this to overlay
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: naive
      CONCOURSE_WORKER_BAGGAGECLAIM_DISABLE_USER_NAMESPACES: true
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: test
      CONCOURSE_WORKER_WORK_DIR: /worker-state
      # If running on a non M1/M2 MacOS, optionally change this to guardian (default) or containerd (if cgroupsv2 is supported by the host)
      CONCOURSE_WORKER_RUNTIME: "houdini"
```

**Comment by tedivm** [comment]
That worked! Thank you!

**Comment by gsaslis** [comment]
I am also struggling getting concourse to run jobs on an `arm64` mac. 

With the options:
```yaml
CONCOURSE_WORKER_RUNTIME: "houdini"
CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: naive
CONCOURSE_WORKER_BAGGAGECLAIM_DISABLE_USER_NAMESPACES: true
```

and image: 
```yaml
image: concourse/concourse:7.9.1-ubuntu
platform: linux/amd64
```

I am getting: 

```
selected worker: 5ab99a3c2614
running build
mount: permission denied (are you root?)
FATA[0000] failed to start buildkitd: setup cgroups: exit status 1
FATA[0000] failed to run task: exit status 1
failed
```

(I _am_ on a `rootful=true` podman machine, and `privileged: true` is also declared in the docker-compose.yaml)

**Comment by gsaslis** [comment]
For additional context: 

```yaml
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_WORKER_RUNTIME: "containerd"
```

and: 

```yaml
    platform: linux/amd64
    image: concourse/concourse:7.9-ubuntu
```

failed with: 
```bash
concourse-concourse-1     | containerd-garden-backend exited with error: setup host network failed: create chain or flush if exists failed: running [/usr/sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait]: exit status 3: iptables v1.8.7 (legacy): can't initialize iptables table `filter': iptables who? (do you need to insmod?)
concourse-concourse-1     | Perhaps iptables or your kernel needs to be upgraded.
```

i.e. concourse itself couldn't start.

**Comment by gsaslis** [comment]
On the other hand, I was able to get this going with: 

```yaml
      CONCOURSE_WORKER_RUNTIME: "containerd"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
```

and the `arm64` image for concourse: 

```yaml
    image: rdclda/concourse:7.9.1
    platform: linux/arm64
```

where no errors were reported during startup of concourse, and the above `mount: permission denied (are you root?)` went away! 🎉

**Comment by Sky-Syed** [comment]
> platform: linux/amd64

thank it worked for me on Mac M1 without using
platform: linux/amd64

**Comment by dove-young** [comment]
I got similar error on RHEL 8.9 when follow the quick start https://concourse-ci.org/quick-start.html.  `docker compose up` exits with these error msg

```
concourse-1     | {"timestamp":"2024-03-22T03:11:07.986970373Z","level":"info","source":"quickstart","message":"quickstart.web-runner.logging-runner-exited","data":{"session":"1"}}
concourse-1     | error: Exit trace for group:
concourse-1     | worker exited with error: Exit trace for group:
concourse-1     | garden exited with error: Exit trace for group:
concourse-1     | containerd-garden-backend exited with error: setup host network failed: create chain or flush if exists failed: running [/usr/sbin/iptables -t filter -N CONCOURSE-OPERATOR --wait]: exit status 3: iptables v1.8.7 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
concourse-1     | Perhaps iptables or your kernel needs to be upgraded.
```

here is my compose file

```yaml
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: tutorial
      CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
      # For ARM-based machine, change the Concourse runtime to "houdini"
      CONCOURSE_WORKER_RUNTIME: "containerd"
```
