### ISSUE TITLE
Cron resource issue

### ISSUE THREAD

**Issue by sikateweiqi** [concourse/concourse#8731]
**Error description:**

error creating input file: open /tmp/build/get/input: permission denied

**Configuration:**
```
---
resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource

resources:
  - name: 10-min-trigger
    type: cron-resource
    source:
      expression: "*/10 * * * *"
      location: "America/New_York"
      fire_immediately: true
```

**Comment by insobi** [comment]
It seems that latest update of the cron-resource has caused a problem. To fix it, try reverting to a prior version of the cron-resource like below.

```
---
resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
    tag: v0.3
```
