### ISSUE TITLE
`7.9.2` Regression? Max Containers Reached Regression?

### ISSUE THREAD

**Issue by ChrisJBurns** [concourse/concourse#8775]
## Summary
Before we were on `7.8.1` and we upgraded to `7.9.2` and we've noticed that we're getting "max containers reached" now when we never got them before. We 

Concourse installation with Helm Chart with the following container replacement strategy:
` checkContainerPlacementStrategy: limit-active-containers,fewest-build-containers`

We also noticed that `volume-locality` wasn't a valid value anymore, so we had to remove it due to failures when starting Concourse after upgrade.

## Steps to reproduce

Install concourse with a helm chart version `17.1.1`, install concourse version `7.9.2` for web and worker images. Create some pipelines and see it favour one worker specifically when scheduling workloads.

![image](https://github.com/concourse/concourse/assets/29541485/28301f1b-5020-41ee-980c-e2bbbd6db052)
![image](https://github.com/concourse/concourse/assets/29541485/96f968e2-82ac-46e5-a649-817cdd1da520)
![image](https://github.com/concourse/concourse/assets/29541485/5c4ae520-2657-4765-a623-07af96df3a10)
![image](https://github.com/concourse/concourse/assets/29541485/a080b62e-e6e5-46eb-af73-43096a451824)

It's worth adding that this is a serious problem for us as concourse is not using the other workers at all. When we restart builds it is just scheduling containers to the same worker consistently

**Comment by ChrisJBurns** [comment]
Closing as it seems we only configured one of the strategies, although not sure how this never caused issues before:

```yaml
        checkContainerPlacementStrategies:
          - limit-active-containers
          - fewest-build-containers
        containerPlacementStrategies: 
          - limit-active-containers
          - fewest-build-containers
        noInputContainerPlacementStrategies:
          - limit-active-containers
          - fewest-build-containers
```
