### ISSUE TITLE
Passing an Object Variable to `Across` does not allow child attributes to be accessed

### ISSUE THREAD

**Issue by reskin89** [concourse/concourse#8808]
## Summary

When using the `across` step to create instanced pipelines, it seems its not possible to pass an object variable with multiple values such as:

```yaml
- object:
     key1: value1
     key2: value2
- object:
     key1: valueA
     key2: valueB
```

and then calling the across step for set-pipeline such as:

```yaml
- load_var: object
     file: pipeline-account-vars/_ci/accounts.yml
  across:
   - var: object
     values: ((.:object))
  instance_vars:
    key1: ((.:object.key1))
    key2: ((.:object.key2))
```

Is met with an error.

I'm not sure if this is a limitation or a bug, as being able to load multiple instance vars this way seems like it would be very useful.

## Expected results

An instanced pipeline referencing the proper values passed from the top level pipeline that creates it

## Actual results

An error that no value for X (object.key) exists.

## Triaging info

* Concourse version: v7
* Browser (if applicable): 
* Did this used to work? As it is a new feature in v7, there is no reference for this question.
