### ISSUE TITLE
Add Ownership to Inputs and Outputs

### ISSUE THREAD

**Issue by reskin89** [concourse/concourse#8814]
## Summary

Some containers set a specific user for operations, this can cause an issue when attempting to use a container such as this, and then creating an output for it to put data in for a new task.

The issue here is that `output` directories are created with `root:root` ownership.

The suggestion here is to add `owner` and `group` optional attributes to an `output` directive such that:

```yaml
outputs:
  - name: data
     owner: ubuntu
     group: wheel
```

This would allow a container that's bound to the `ubuntu` user to copy data into this output folder.
