### ISSUE TITLE
When a new pipeline gets a resource that has been pinned in the pipeline config to a "very old" version, my pipeline won't run until I `fly check-resource --from foo`

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#882]
# Feature Request

## What challenge are you facing?

When we are pinning a resource to a specific version (e.g. a git resource to a specific SHA), it is likely that this version has become too old for the default check behavior to find it. My pipeline will not run (and, worse, won't provide very good visual feedback about why it's refusing to run) until I `fly check-resource --from ref:super-old-ref`. This is a problem for pipelines that are distributed to multiple teams as sample pipelines, since we need to provide additional instructions to consumers regarding how to "kick start" their pipeline.

## A Modest Proposal

When a `get` has a pinned version using the `version` key, if that version does not exist, perform an additional check with a `from` of the requested version. That way the pipeline will be able to "kick start" itself.

If there are concerns that this might cause performance problems (for example, if the request version is very, very, very old) or have other issues, I would like a flag that allows me to force-on this new back-checking behavior. For example:

```
- get: bosh-deployment
  version:
    ref: ccca4c9f7bcdd0f217c8c3adf186648c52b3b137
  check_from_version: true
```

or

```
- name: bosh-deployment
  type: git
  seed_version:
    ref: ccca4c9f7bcdd0f217c8c3adf186648c52b3b137
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master
```

...where the first time the resource is checked, rather than passing in an empty version, pass in the "seed" version.

/cc @drich10
