### ISSUE TITLE
Container Placement Strategies not working

### ISSUE THREAD

**Issue by ChrisJBurns** [concourse/concourse#8836]
## Summary
We have set our container replacement strategies to the following:

```yaml
concourse:
    web:
        checkContainerPlacementStrategies:
        - limit-active-containers
        - fewest-build-containers
        containerPlacementStrategies:
        - limit-active-containers
        - fewest-build-containers
        noInputContainerPlacementStrategies:
        - limit-active-containers
        - fewest-build-containers
```

## Expected results

We expect containers to be spread across the workers.

## Actual results

We get workers with an disproportionate amount of containers. Often resulting in our builds failing because they've hit the container limit even if there are other workers that have plenty of room.

![image](https://github.com/concourse/concourse/assets/29541485/bcbaf006-4cc4-400c-8add-5646b602f481)

## Additional context

The default max limit is 250.

## Triaging info

* Concourse version: `7.10.0`
* Browser (if applicable): Chrome
