### ISSUE TITLE
archive pipeline leaks containers

### ISSUE THREAD

**Issue by fredwangwang** [concourse/concourse#8867]
## Summary

Hi, I am using [set-pipeline step](https://concourse-ci.org/set-pipeline-step.html) to dynamically create/tear down pipelines for feature branches.

After using the feature for a while noticing new pipelines hitting issues with worker no longer able to create new containers due to the workers has reached max number of containers.

using `fly containers` reveals a bunch dangling containers for the instance pipelines that has already archived.

below shows one such container after the instance has been archived 
![image](https://github.com/concourse/concourse/assets/21690857/597bfbc0-547f-4442-a250-9bf11ec806cd)

## Steps to reproduce

setting up multi branch workflow per: https://concourse-ci.org/multi-branch-workflows.html#multi-branch-tracking-branches,
then remove a branch.

**OR** I think manually set-pipeline and archive-pipeline could also trigger, but havent tested myself.

## Expected results

Containers associated with archived pipeline are **destroyed**

## Actual results

Containers associated with archived pipeline are **leaked**

## Triaging info

* Concourse version: 7.10.0
* Did this used to work? Dont think so

**Comment by 8R0WNI3** [comment]
Hi, I have the same problem with dangling containers of already archived pipelines. Is there any update on this?

**Comment by taylorsilva** [comment]
This should be easy enough to validate. Thanks for reporting. No ETA on when this will be fixed besides "eventually" :)

**Comment by taylorsilva** [comment]
Finally getting around to verifying this issue.

Archived pipelines are also marked as paused in the database. This was by design, we figured we'd leverage the existing GC logic for paused pipelines. Therefore I should expect:
- containers tied to failed builds get GC'd after the "failed builds grace period", which is 5 days by default
- Containers that were part of running builds that eventually succeed, get GC'd as usual during the next GC interval

My test pipeline:
```yaml
resources:
  - name: image
    type: mock
    source:
      mirror_self: true

jobs:
  - name: failed
    plan:
      - get: image
      - task: build
        image: image
        config:
          platform: linux
          run:
            path: exit
            args: ["1"]

  - name: sleep
    plan:
      - get: image
      - task: build
        image: image
        config:
          platform: linux
          run:
            path: sleep
            args: ["15s"]

```

I set the pipeline, triggered the jobs, and then archived the pipeline with fly while the `sleep` job was running. Immediately after archiving I had these containers:
```
handle                                worker        pipeline  job     build #  build id  type   name   attempt
5bdeb716-b53b-4c85-abb4-c39f78b2d6ce  2f72b7067b49  test      none    check    none      check  image  n/a
5d02dc34-cd7a-49b3-8761-9aa9df18acff  2f72b7067b49  test      failed  2        4         task   build  n/a
caa40abd-981c-471a-bcdf-ec4cc759b487  2f72b7067b49  test      sleep   2        6         task   build  n/a
```

On my test cluster I've set the following on my web node, just so I don't wait too long while testing things here:
```
CONCOURSE_GC_FAILED_GRACE_PERIOD: 30s
CONCOURSE_GC_INTERVAL: 10s
```

After waiting 30s, I ran `fly containers` again and saw all the containers were GC'd as expected.

I don't think there are any containers being leaked by archived pipelines. I'm going to close this issue. If someone has more information or can reproduce the issue please share and I'll re-open the issue.
