### ISSUE TITLE
Output not passed to next task when the next task is in "ensure, do..."

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#894]
# Bug Report

output from task is not available as input for next task in "ensure, do task" step.
The pipeline runs but the output folder "test-reports" of UI-tests does not appear in the container of the upload-reports task. even though i is added as an input.

I would expect the test-reports folder to be passed to the upload-reports task.

**pipeline:** 

```
- name: UI-tests
  public: true
  #  max_in_flight: 1
  plan:
  - aggregate:
    - get: repo
    - get: mock-server-repo
    - get: devops-repo
    - get: nightly
      trigger: true
  - task: run-test
    timeout: 3h # Time limit on running the tests, if exceded: tests will fail.
    file: devops-repo/ios-pipeline/tasks/run-UI-tests.yml
    **// Generates an output "test-reports"** 
    params:
      PRODUCT: "BBL"
      KEYCHAINPASS: {{keychain-pass}}
    ensure:
      do:
      - task: upload-reports
        file: devops-repo/mex-ios-pipeline/tasks/upload-test-reports.yml
        **// References the "test-reports" output from the task above as an input**
        params:
          REPORTS_SERVER: {{reports-server}}
```

**Task:  run-UI-tests.yml**
```
---
platform: darwin
inputs:
- name: ios-repo
- name: mock-server-repo
- name: devops-repo
outputs:
- name: test-reports
params:
  PRODUCT:
  KEYCHAINPASS:
run:
  user: server
  path: sh
  args:
  - -exc
  - |
    id -un
   ...

```
**Task:  upload-test-reports.yml**
```
---
platform: darwin
inputs:
- name: devops-repo
- name: test-reports
params:
  REPORTS_SERVER:
run:
  user: server
  path: bash
  args:
  - -exc
  - |
    id -un
    ls -lah  **//only devops-repo is shown**
    pwd
    touch ./test-reports/test132.txt  
 **// touch: ./test-reports/test132.txt: No such file or directory**

```

The following can also be handy:

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): Docker + binary OSX worker
