### ISSUE TITLE
Error unexpected Response

### ISSUE THREAD

**Issue by ianatarewe** [concourse/concourse#8958]
## Summary

When following this: https://concourse-ci.org/tutorial-hello-world.html I get to the part where I create the hello-world pipeline and execute:

fly -t my-target -p hello-world -c hello-world.yml

it responds with:

```
  job hello-world-job has been added:
+ name: hello-world-job
+ plan:
+ - config:
+     image_resource:
+       name: ""
+       source:
+         repository: busybox
+       type: registry-image
+     platform: linux
+     run:
+       args:
+       - Hello world!
+       path: echo
+   task: hello-world-task

pipeline name: hello-world

apply configuration? [yN]: y
error: Unexpected Response
Status: 404 Not Found
Body:
```

## Steps to reproduce

execute set-pipeline

## Expected results

pipeline is created

## Actual results

config was read and asked for confirmation, but upon confirmation a 404 occurs.

## Additional context

Tried syncing: `version 7.11.2 already matches; skipping`

The server is running with SSL behind nginx, and you can log into it both with fly and with the web UI. 

nginx logs show this:

```
192.168.1.1 - - [06/May/2024:17:17:51 +0000] "GET /api/v1/jobs HTTP/1.1" 200 3 "https://my.server.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/pipelines HTTP/1.1" 200 3 "https://my.server.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/teams HTTP/1.1" 200 80 "https://my.server.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/resources HTTP/1.1" 200 3 "https://my.server.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/jobs HTTP/1.1" 200 3 "https://my.server.duckdns.org/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/info HTTP/1.1" 200 326 "http://my.server.duckdns.org/api/v1/info" "Go-http-client/1.1" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/teams/main/pipelines/hello-world/config HTTP/1.1" 404 0 "http://my.server.duckdns.org/api/v1/teams/main/pipelines/hello-world/config" "Go-http-client/1.1" "-"
192.168.1.1 - - [06/May/2024:17:17:56 +0000] "GET /api/v1/teams/main/pipelines/hello-world HTTP/1.1" 404 0 "http://my.server.duckdns.org/api/v1/teams/main/pipelines/hello-world" "Go-http-client/1.1" "-"
192.168.1.1 - - [06/May/2024:17:17:57 +0000] "GET /api/v1/teams/main/pipelines/hello-world/config HTTP/1.1" 404 0 "http://my.server.duckdns.org/api/v1/teams/main/pipelines/hello-world/config" "Go-http-client/1.1" "-"
```

The config is based on the basic docker-compose:

```
  concourse-db:
    image: postgres
    env_file: /mnt/storage/appdata/concourse/.env
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      PGDATA: /database
  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    expose:
      - 8080
    env_file: /mnt/storage/appdata/concourse/.env
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: https://my.server.duckdns.org
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: my-target
      CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
      # For ARM-based machine, change the Concourse runtime to "houdini"
      CONCOURSE_WORKER_RUNTIME: "containerd"
```

Target and server address redacted.

## Triaging info

* Concourse version: 7.11.2
* Browser (if applicable): n/a
* Did this used to work? no
