### ISSUE TITLE
Version created by resource type's `out` should be `check`ed

### ISSUE THREAD

**Issue by KoltesDigital** [concourse/concourse#8990]
## Summary

I want to release a new version of my project whenever there's a commit on the main branch (should be a merge from a PR). I store the current version number in a versioned file. A Concourse pipeline detects new commits, launches a task (which increments the version number, adds stuff the to the changelog, commits with a message _M_, tags, whatever), and pushes back to the repo.

This new commit then triggers the pipeline again! This would make an infinite loop, so I store the dist hash to bail out when new commits don't change last release.

The `git` resource has a `commit_filter` parameter, whereby _M_ is excluded. So if I manually push a new commit with message _M_, Concourse won't launch a build. However, if Concourse pushes this commit in a `put` step, it does launch a build.

I believe `out` has to declare a version, and this version goes directly into the resource's version list. Concourse does not wait to see whether `check` provides it.

I think it's a global issue, because a lot of resource types filter versions during `check`.

## Steps to reproduce

```yaml
resources:
- name: git-repository
  type: git
  source:
    ...
    commit_filter:
      exclude:
      - bump versions
jobs:
- name: infinite-loop
  plan:
  - get: git-repository
    trigger: true
  - task: commit
    config:
      inputs:
      - git-repository
      outputs:
      - git-repository
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine/git
      run:
        path: sh
        cwd: git-repository
        args:
          - exc
          - git -c "user.email=concourse@example.com" -c "user.name=Concourse" commit --allow-empty -m "bump versions"
  - put: git-repository
    no_get: true
    params:
      repository: git-repository
```
(out of my head, not tested)

## Expected results

Version should not be detected because its commit message is filtered out. A single build should be launched, that's all.

## Actual results

A new version is detected after each build, starting a new build, in an infinite loop.

## Additional context

I guess it may be possible to work around using two resources, one for reading and one for writing. But that's less elegant.

## Triaging info

* Concourse version: 7.11.2 (latest)
* Did this used to work? I don't know. I think it always has been like that.
