### ISSUE TITLE
CONCOURSE_GARDEN_DENY_NETWORK is not working as expected in v 7.11.0

### ISSUE THREAD

**Issue by Kump3r** [concourse/concourse#8993]
## Summary
The iptables rules, that should restrict connections to certain endpoints are not working as designed

## Steps to reproduce

We run a bosh deployment, with guardian garden runtime. We don't have any custom garden configurations and decided to evaluate the deny_networks option, as to block access to the metadata endpoint as in [this example](https://github.com/concourse/hush-house/blob/290f5fdecc0c160147e6fef7c00349c6690f0a56/deployments/with-creds/ci/values.yaml#L76). 

We can see that the gdn server starts as expected:
```
gdn server --bind-ip 127.0.0.1 --bind-port 7777 --depot /var/vcap/data/worker/work/depot --properties-path /var/vcap/data/worker/work/garden-properties.json --time-format rfc3339 --no-image-plugin --deny-network 169.254.169.254/32 --max-containers 250 --network-pool 10.80.0.0/16
```
Also in the `iptables-legacy`  of a PID, or the general worker `iptables-legacy` we see:
```
iptables-legacy -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N w--default
-N w--forward
-N w--input
-A INPUT -i w+ -j w--input
-A FORWARD -i w+ -j w--forward
-A w--default -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A w--default -d 169.254.169.254/32 -j REJECT --reject-with icmp-port-unreachable
-A w--forward -i eth0 -j ACCEPT
-A w--forward -j DROP
-A w--input -i eth0 -j ACCEPT
-A w--input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A w--input -j REJECT --reject-with icmp-host-prohibited
```
the rule `-A w--default -d 169.254.169.254/32 -j REJECT --reject-with icmp-port-unreachable` is present, but scheduling a dummy pipeline for example:

```
jobs:
  - name: curl-aws-metadata
    public: true
    plan:
      - task: curl-metadata-endpoint
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
              tag: "20.04"
          run:
            path: bash
            args:
              - -c
              - |
                apt-get update
                apt-get install -y curl
                echo "Curling AWS Metadata Endpoint..."
                curl -v http://169.254.169.254 || true
                curl -vvv google.com || true
                curl -vvv neopets.com || true
                curl -vvv github.com || true
```
results in all connections succeeding. I also tried adding the CIDR's from [this PR discussion](https://github.com/concourse/concourse/pull/5829)

## Expected results
Something of the sort:
```
Curling AWS Metadata Endpoint...
*   Trying 169.254.169.254:80...
* connect to 169.254.169.254 port 80 failed: No route to host
* Failed to connect to 169.254.169.254 port 80 after 0 ms: No route to host
* Closing connection 0
curl: (7) Failed to connect to 169.254.169.254 port 80 after 0 ms: No route to host
```

## Actual results
```
Curling AWS Metadata Endpoint...
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET / HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Date: Tue, 27 Aug 2024 10:35:32 GMT
< Server: EC2ws
< Connection: close
< Content-Type: text/plain
< 
* Closing connection 0
*   Trying 172.253.115.100:80...
* Connected to google.com (172.253.115.100) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-Loor0sNZCcNAKPXn5TZzsQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< Date: Tue, 27 Aug 2024 10:35:32 GMT
< Expires: Thu, 26 Sep 2024 10:35:32 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="gfe-default_product_name"
< Report-To: {"group":"gfe-default_product_name","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/default_product_name"}]}
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact
*   Trying 23.96.35.235:80...
* Connected to neopets.com (23.96.35.235) port 80 (#0)
> GET / HTTP/1.1
> Host: neopets.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 27 Aug 2024 10:35:32 GMT
< Server: Apache/2.2.15 (CentOS)
< Location: http://www.neopets.com/
< Content-Length: 308
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.neopets.com/">here</a>.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at neopets.com Port 80</address>
</body></html>
* Closing connection 0
*   Trying 140.82.112.3:80...
* Connected to github.com (140.82.112.3) port 80 (#0)
> GET / HTTP/1.1
> Host: github.com
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Location: https://github.com/
< 
* Connection #0 to host github.com left intact
```

## Additional context
I am more than happy to try suggestions. Also I understand it could be an issue with guardian upstream, just wondering if you detected similar problems, or do I need to add something additional to my env.

As a side note using gardner-config.ini from [this example](cluster/operations/add-garden-config-ini.yml), brought the same unexpected result, so I don't believe it is a problem with the options.

I see this as a potential security issue, if applicable for other people as well. 

## Triaging info

* Concourse version: 7.11.0
* Browser (if applicable): N/A
* Did this used to work? I assume based on the discussion in the PR.
