### ISSUE TITLE
fly set-pipeline does not fail on duplicate keys in pipeline yaml

### ISSUE THREAD

**Issue by Knappek** [concourse/concourse#9026]
## Summary

Any duplicate key in a pipeline yaml overwrites the previous occurence when executing `fly set-pipeline ...`.

## Steps to reproduce

Consider the pipeline:

```yaml
jobs:
- name: test-job
  plan:
  - task: display-cred
    config:
      platform: linux
      platform: windows
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      run:
        path: bash
        args: [-c, "echo Hello world"]
```

This pipeline has a duplicate key in the config, `platform: linux` and `platform: windows`. That usually happens by coincidence.

When executing `fly set-pipeline ...` it sets

```yaml
jobs:
- name: test-job
  plan:
  - task: display-cred
    config:
      platform: windows
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      run:
        path: bash
        args: [-c, "echo Hello world"]
```

so taking `platform: windows` and simply ignoring the duplicate key `platform`.

## Expected results

I expect `fly set-pipeline` to throw an error because of the duplicate key. This would improve error handling and make it easier to find misconfigurations.

## Triaging info

* Concourse version: v7.4.0
* fly version: 7.4.0

**Comment by taylorsilva** [comment]
I forget what we use to validate the pipeline, but I wonder if that library has a built-in way to warn about duplicate keys. This could potentially be a very easy fix.

**Comment by Knappek** [comment]
I have looked into this if it can be realized and implemented, but it can't (yet). 

A pipeline config simply gets unmarshalled using [yaml.Unmarshal()](https://github.com/concourse/concourse/blob/master/fly/commands/internal/setpipelinehelpers/atc_config.go#L61) and the `encoding/json` [accepts duplicate keys](https://github.com/golang/go/issues/24415) and you experience exactly the behaviour as described in the issue description. There is an [accepted but still open proposal to add a feature to disallow duplicate keys](https://github.com/golang/go/issues/48298) so I assume we just have to wait until this proposal gets implemented, then we can also implement it for `fly set-pipeline`. 

Until then, I think it's best to keep this issue on hold.

**Comment by ae-govau** [comment]
Back in 2018 at least, `fly` used a library that could validate this, and this was in fact added, with some discussion as to whether it should also be run on `set-pipeline`:
https://github.com/vmware-archive/fly/pull/201#issuecomment-357081778

**Comment by ae-govau** [comment]
And still does, according to the tests:

https://github.com/concourse/concourse/blob/cd71788dc4e7338197f9679f13e9ac221d2bd088/fly/commands/internal/validatepipelinehelpers/validate_test.go#L146-L153

**Comment by ae-govau** [comment]
And also (from 8 years ago):

https://github.com/concourse/concourse/blob/cd71788dc4e7338197f9679f13e9ac221d2bd088/fly/commands/internal/validatepipelinehelpers/validate.go#L23-L29

Perhaps this is the time? :)

**Comment by Knappek** [comment]
Thanks @ae-govau , I researched about UnmarshalStrict and [this comment](https://github.com/go-yaml/yaml/issues/602#issuecomment-623485602) explains that yaml.v3 replaced "strict" unmarshaling, as it is an open-ended term, and it has been replaced by more specific terms like KnownFields(true/false) in the decoder. Unfortunately the decoder does not have a function "DuplicateKeys(true/false)" as mentioned in my previous comment.

BUT, I learned that fly uses the library [sigs.k8s.io/yaml](https://github.com/concourse/concourse/blob/master/fly/commands/internal/setpipelinehelpers/atc_config.go#L12C2-L12C20) to unmarshal the config which uses [sigs.k8s.io/yaml/goyaml.v2](https://pkg.go.dev/sigs.k8s.io/yaml@v1.4.0/goyaml.v2) which indeed still supports [UnmarshalStrict](https://pkg.go.dev/sigs.k8s.io/yaml@v1.4.0/goyaml.v2#UnmarshalStrict). 

Question is: Can we just use UnmarshalStrict instead of Unmarshal and solve this issue?

I thought about that question and first thought it might not be a good idea to rely on a "old" version of the yaml library. But there are some reasons that would still the answer with "yes that's fine":

1. the latest version of [sigs.k8s.io/yaml](https://pkg.go.dev/sigs.k8s.io/yaml@v1.4.0) uses UnmarshalStrict and there is a reason why this library has been introduced as a fork for kubernetes projects
2. the official [go-yaml library](https://github.com/go-yaml/yaml) seems to be at the end of development and there's not much happening: the last commit for v3 (latest release) is 3 years ago.

IMO, it is fine to replace Unmarshal with UnmarshalStrict. I am also happy to implement it, but I would first like to have some maintainers to agree.

**Comment by taylorsilva** [comment]
So the only problem I see with using this strict setting is that it blocks people from adding unknown fields to their pipeline config. I know this is a thing people take advantage of to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) up their pipelines a bit by using [YAML anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/).

I did this quick test to confirm this behaviour happens.

I have this pipeline yaml:
```yaml
resources:
- name: every-30s
  type: time
  source:
    interval: 5s

jobs:
- name: job
  public: true
  plan:
  - get: every-30s
    trigger: true
```

I ran `fly validate-pipeline` on it with the `--strict` flag and I get `looks good`.

If I add a second `type` key:
```yaml
resources:
- name: every-30s
  type: time
  type: time
  source:
    interval: 5s

jobs:
- name: job
  public: true
  plan:
  - get: every-30s
    trigger: true
```
I get:
```
error: error parsing yaml before applying templates: error converting YAML to JSON: yaml: unmarshal errors:
  line 5: key "type" already set in map
```

Yay, that's what we want! What happens if I add an unknown key to the config though?

```yaml
somekey: hello

resources:
- name: every-30s
  type: time
  source:
    interval: 5s

jobs:
- name: job
  public: true
  plan:
  - get: every-30s
    trigger: true
```

I get
```
error: error unmarshaling JSON: while decoding JSON: json: unknown field "somekey"
```

It's this behaviour we don't want to break. So I don't think switching over to use `UnmarshalStrict` everywhere is going to be viable.

If we had some way to allow unknown top-level keys in the pipeline config then we could be strict about the keys everywhere else. I know this is a pattern that some people use though and I don't want to take that behaviour away from them.
