### ISSUE TITLE
stdout/stderr output to the console is lost when jobs have a long duration

### ISSUE THREAD

**Issue by jrobison-sb** [concourse/concourse#9050]
## Summary

I have found that if a job runs for a long duration (2 days, for example) with no output to the console, the console will lose the ability to output stdout/stderr. This is problematic because if your job runs for a long duration and then fails, you need the output of stdout/stderr to know why it failed, and currently you cannot see that output.

## Steps to reproduce

```
jobs:
- name: dev-2648-just-testing
  plan:
  - task: dev-2648-just-testing
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: 22.04

      run:
        path: /bin/bash
        args:
        - -exc
        - |
          echo 1
          echo 2
          echo 3
          sleep 172800 # 2 days
          echo 4
          grep foo /does/not/exist # this will cause an error
```

## Expected results

I expect to see 4 numbers echo'ed to the console, and I expect a `No such file or directory` error for that grep command.

## Actual results

I see 3 numbers echo'ed to the console. I see no output at all after the period of sleep.

<img width="713" alt="Screenshot 2023-05-15 at 10 14 48 AM" src="https://github.com/concourse/concourse/assets/39737211/4dd92c39-8f03-4324-9c4c-ae8cb68a3677">

## Triaging info

* Concourse version: v7.8.2
