### ISSUE TITLE
Resource parameters are not validated when setting a pipeline

### ISSUE THREAD

**Issue by robtaylorsky** [concourse/concourse#9067]
## Summary
Resource parameters are not validated when setting a pipeline

## Steps to reproduce
1. Define a resource in your pipeline with a non-existent parameter:
```yaml
resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/example/example.git
    branch: main
    foo: bar # this should get validated when you run fly set-pipeline
```
2. Run fly set-pipeline
3. Your pipeline will get set, and everything will seem ok

The problem with not validating parameters is that it can lead to behaviour like this: https://github.com/concourse/concourse/issues/2487.

In the example of https://github.com/concourse/concourse/issues/2487 it would be good if Concourse output an error when this pipeline was being originally set. That would have alerted the user to their misconfiguration and saved them time when debugging.

## Expected results

Concourse should output an error when either required parameters for a resource are omitted, or when unsupported parameters are used.

Perhaps each resource type could include a simple schema definition that could be used by Concourse for validation.

## Actual results

See example above. Also see the issue described here: https://github.com/concourse/concourse/issues/2487

## Additional context
n/a

## Triaging info

* Concourse version: 7.11.2
* Browser (if applicable):
* Did this used to work? No
