### ISSUE TITLE
`OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown`

### ISSUE THREAD

**Issue by 9numbernine9** [concourse/concourse#9088]
## Summary

(This is a re-opening of #8792 which was closed during the _Issue Bankruptcy_ on 2025-01-07 but is still a problem that occurs.)

Creating a new task (or performing a resource check) returns an error: `OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown`. This happens when deploying Concourse `7.12.1` on a Talos Linux Kubernetes cluster running Talos `1.9.4` and Kubernetes `1.32.1`.

Worker logs:
```
time="2025-02-28T02:35:37.179592863Z" level=info msg="connecting to shim 523efe36-629d-4145-58a2-fab052affa07" address="unix:///run/containerd/s/b7a96f65be9df4fe2b93ac55c9b0ae2981d146b20b77c1bf8180d267010b227d" namespace=concourse protocol=ttrpc version=3
time="2025-02-28T02:35:37.284903003Z" level=info msg="shim disconnected" id=523efe36-629d-4145-58a2-fab052affa07 namespace=concourse
time="2025-02-28T02:35:37.284938177Z" level=warning msg="cleaning up after shim disconnected" id=523efe36-629d-4145-58a2-fab052affa07 namespace=concourse
time="2025-02-28T02:35:37.284948846Z" level=info msg="cleaning up dead shim" namespace=concourse
time="2025-02-28T02:35:37.293064244Z" level=warning msg="cleanup warnings time=\"2025-02-28T02:35:37Z\" level=warning msg=\"failed to read init pid file\" error=\"open /run/containerd/io.containerd.runtime.v2.task/concourse/523efe36-629d-4145-58a2-fab052affa07/init.pid: no such file or directory\" runtime=io.containerd.runc.v2\n" namespace=concourse
time="2025-02-28T02:35:37.302946396Z" level=error msg="copy shim log" error="read /proc/self/fd/10: file already closed" namespace=concourse
{"timestamp":"2025-02-28T02:35:37.303405956Z","level":"error","source":"worker","message":"worker.garden.garden-server.create.failed","data":{"error":"starting task: new task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown","request":{"Handle":"523efe36-629d-4145-58a2-fab052affa07","GraceTime":0,"RootFSPath":"raw:///concourse-work-dir/volumes/live/21d545a4-dbd5-4c2b-46ec-73693152933b/volume","BindMounts":[{"src_path":"/concourse-work-dir/volumes/live/d1340232-cdd0-485e-6e9d-e65152a14731/volume","dst_path":"/scratch","mode":1}],"Network":"","Privileged":false,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{},"pid_limits":{}}},"session":"1.2.7"}}
```

## Steps to reproduce

- Deploy a Concourse `7.12.1` deployment to a Talos Linux cluster.
- Create a simple pipeline -the [Hello World](https://concourse-ci.org/hello-world-example.html#configuration) pipeline in the documentation is sufficient.
- Attempt to start the job and observe the error.

Concourse was deployed using the most recent Helm chart and with the following values:
```yaml
concourse:
  web:
    auth:
      mainTeam:
        localUser: admin
    externalUrl: https://concourse.example.com
    kubernetes:
      createTeamNamespaces: false
    postgres:
      database: concourse
      host: concourse-database-rw.concourse.svc.cluster.local
      port: "5432"
      sslmode: require
  worker:
    baggageclaim:
      driver: naive
    runtime: containerd
persistence:
  worker:
    storageClass: ceph-csi-cephfs-persistent
postgresql:
  enabled: false
secrets:
  localUsers: admin:admin
  postgresPassword: postgrespassword
  postgresUser: user
web:
  replicas: 1
worker:
  replicas: 1
```

## Expected results

- Job completes successfully.

## Actual results

Task fails with `OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown` error.

## Additional context

- Talos Linux `1.9.4`
- Kubernetes `1.32.1`

## Triaging info

* Concourse version: `7.12.1`
* Browser (if applicable): N/A
* Did this used to work? No
