### ISSUE TITLE
Resource caching not clearing on changes to pipeline resource_type

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#913]
# Bug Report

I have had some issues when trying to POC stuff in concourse and the resource_type has been misconfigured. It appears that it becomes cached in concourse, doing a set pipeline with changes to the same resource/resource-type does not seem to flush the cache... This can result in pending resources...

**Example:**

```
resource_types:
- name: nm_cache
  type: docker-image
  source: 
    repository: {{docker-registry-npm-cache-non-working}}
    insecure_registries:
       - {{my-docker-registry}}
```

update the pipeline to the working repository, set pipeline using fly:

```
resource_types:
- name: nm_cache
  type: docker-image
  source: {repository: devdavid/npm-cache-resource, tag: latest}
```

**Result**
Pipeline is still pending and cannot start even though cancelled, retriggered manually....

**Expected:**
The new resource type is used by the resources utilizing the resource_type named: nm_cache (in this case)...

* Concourse version: 2.60
