### ISSUE TITLE
Unable to deploy on Bosh.  Failed to reserve IP for web  for manual network 'private': no more available

### ISSUE THREAD

**Issue by StBurcher** [concourse/concourse#928]
Hi there!

I'm facing the challenge to deploy concourse, but the system will not reserve an IP for the instances.
Here are my system information:
* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Openstack (Liberty=

If I start the deployment, I get the following error.
```
Director task 605
  Started preparing deployment > Preparing deployment. Failed: Failed to reserve                                                                                                              IP for 'worker/3e959050-77d8-47a0-93d5-59facb7f9380 (0)' for manual network 'pr                                                                                                             ivate': no more available (00:00:00)

Error 130011: Failed to reserve IP for 'worker/3e959050-77d8-47a0-93d5-59facb7f9                                                                                                             380 (0)' for manual network 'private': no more available
```
The project is using the network 10.0.0.0/24. For this installation the ip addresses 10.0.0.110 to 10.0.0.124 are reserved. This is the used cloud config.

```
azs:
- name: z1
  cloud_properties:
    availability_zone: nova

vm_types:
- name: default
  cloud_properties:
    instance_type: m1.medium
- name: small
  cloud_properties:
    instance_type: m1.small
- name: large
  cloud_properties:
    instance_type: m1.large

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    az: z1
    dns: [139.25.25.243]
    cloud_properties:
      net_id: 116355d4-c925-4c66-b49e-6ef8f64764cc
      security_groups: [bosh]
    static: 10.0.0.110 - 10.0.0.124

compilation:
  workers: 1
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: private
```

The Deployment manifest looks like this one.
```
---
name: concourse

director_uuid: 87c25ba6-be78-4c13-8c7a-3ca9017594c7

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: small
  stemcell: trusty
  azs: [z1]
  networks: 
  - name: private
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: concourse.de.cloudlab.com
      basic_auth_username: admin
      basic_auth_password: password

      # replace with your SSL cert and key
      tls_cert: |+
        -----BEGIN CERTIFICATE-----
       
        -----END CERTIFICATE-----
      tls_key: |+
        -----BEGIN RSA PRIVATE KEY-----
        
        -----END RSA PRIVATE KEY-----

      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: small
  stemcell: trusty
  persistent_disk_type: default
  azs: [z1]
  networks: 
  - name: private
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: admin
        password: password

- name: worker
  instances: 1
  vm_type: small
  vm_extensions: []
  stemcell: trusty
  azs: [z1]
  networks: 
  - name: private
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```

I have tried to assign static ips in the manifest, but then the worker instances has the same problems.

Any ideas?
