### ISSUE TITLE
Source params causing resource to fail with non-descriptive error

### ISSUE THREAD

**Issue by elementsweb** [concourse/concourse#929]
Hi there!

I'm having an issue configuring a new `resource_types` in my pipeline. If I attempt to pass `source` parameters to the resource_type I get an non-descriptive error.

My pipeline configuration is as follows:

```
resource_types:
- name: bitbucket-notifier
  type: docker-image
  source:
    repository: namespace/bitbucket-notifier
    tag: "1.0"

resources:
- name: project-x
  type: git
  source:
    uri: git@bitbucket.org:User/project-x.git
    branch: master
    private_key: {{bitbucket-private-key}}
- name: bitbucket-notifier
  type: bitbucket-notifier
  source:
    bitbucket_user: helloworld

jobs:
- name: unit-test
  plan:
  - get: project-x
    trigger: true
  - task: run-unit-tests
    file: project-x/concourse-dev.yml
    on_success:
      put: bitbucket-notifier
```

I've changed the names of some things in my pasted code to protect my deployment process.

The docker-image specified in the bitbucket_notifier `resource_types` is pulled down from Docker Hub correctly, but then I get an error:

```
invalid character 'h' looking for beginning of value
```

The character 'h' is replaced with whatever is the first character of the value for the `bitbucket` source parameter being passed to `bitbucket-notifier`.

My Docker image uses in the `bitbucket-notifier` resource is configured similarly to existing resource_types available on Github and is currently configured to simply echo the `bitbucket_user` parameter.

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: DigitalOcean
* Browser (if applicable): Chrome
* Did this used to work? Haven't attempted before
