### ISSUE TITLE
build setup fails but build runs anyway

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#93]
ATC running on localhost, garden running inside bosh-lite; ATC callback URL not set correctly results in the following:

```
fly -t local e -c .//task.yml
executing build 1625
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused
gunzip: invalid magic
tar: short read
exit status 1
initializing with docker:///ubuntu
running /bin/bash -c exit 0
succeeded
```

task.yml:

```yaml
---
platform: linux
image: docker:///ubuntu
run:
  path: /bin/bash
  args:  ["-c", "exit 0"]
```

Assume there is a missing `set -o pipefail` somewhere, perhaps the archive resource?
