### ISSUE TITLE
docker image is not pulling in helm chart under kubernetes

### ISSUE THREAD

**Issue by thaniyarasu** [concourse/concourse#937]
i installed concourse/stable in kubernetes cluster using helm charts.

when i try hello-world
i get this error

annoy
resource script '/opt/resource/check []' failed: exit status 1
stderr:
failed to ping registry: 2 error(s) occurred:

ping https: Get https://registry-1.docker.io/v2/: dial tcp 184.168.221.96:443: i/o timeout
ping http: Get http://registry-1.docker.io/v2/: dial tcp 184.168.221.96:80: i/o timeout

**Comment by databus23** [comment]
@thaniyarasu the concourse helm chart is not maintained by the concourse team so I think this error could also be reported to the chart maintainer.

That being sad the helm chart is doing no magic. Its just deploying some k8s specs. Looks like the network setup in your k8s cluster is not playing well with the garden containers created by the concourse worker.

There is way more information needed to give some meaningful help.
For starters:
* Where is your k8s cluster running? AWS? GCP? Baremetal?
* How is the networking setup for this cluster?
* Can you curl https://registry-1.docker.io/v2/ from inside the concourse worker docker container?

**Comment by thaniyarasu** [comment]
1. my kubernetes cluster  is running at AWS. this cluster is created by kops 
2. networking is private (topology:private)
3. i can't able curl  https://registry-1.docker.io/v2/ from inside the concourse worker.
 but i can able to curl inside kubernetes->basybox container

**Comment by thaniyarasu** [comment]
thanks @databus23 
may be you are correct, 
let me create another public networking cluster (topology: public) and try this and let you know the status.
anyway Concourse is rocking. i love it.

**Comment by thaniyarasu** [comment]
still same error, i have created another kops cluster with public . still i am facing same error.

**Comment by databus23** [comment]
That you are already having trouble reaching urls from inside the concourse docker images I think its indicative of something general with your k8s cluster outside the scope of concourse. The concourse docker image is nothing fancy: https://github.com/concourse/concourse-docker/blob/master/Dockerfile.

**Comment by thaniyarasu** [comment]
i have created concourse in docker-compose at my localhost by following this guide https://concourse.ci/docker-repository.html.
here i can able to pull images from docker hub. working fine.

**Comment by PavelPrischepa** [comment]
Concourse in docker compose working well, but not in Kubernetes. I've entered into a container (via fly intercept) and ping, wget external resources successfully. But docker push don't working as I described here https://github.com/concourse/docker-image-resource/issues/102

**Comment by rodcloutier** [comment]
@thaniyarasu I had the same issue at first and it was because I had misspelled one entry in the hello.yml file (`respository` instead of `repository`).

 I had
```
  name: hello-world
    plan:
    - task: say-hello
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            respository: ubuntu
        run:
          path: echo
          args:
          - hello, world!
```
instead of 

```
  name: hello-world
    plan:
    - task: say-hello
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: echo
          args:
          - hello, world!
```
