### ISSUE TITLE
Add ability to allow a job to run only when a new version of a resource is present

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#945]
I have a situation where I'd like to have a job only run when a new version of a resource is present. In other words, I want *non-reproducible* builds.

Use-cases for this: I don't want someone to push a button on a build that has no new artifacts, which increments a version resource and creates a new release. If there are no new changes, the job should not run. A job *could* be queued to run when a new version of the resource with the limitation is introduced.

Additionally, I'd like to be able to use the [time resource](https://github.com/concourse/time-resource) to have builds *only* run within a particular time window.

@mariash came up with a solution that does the latter:

```yaml
resources:
- name: after-midnight
  type: time
  source:
    interval: 30s
    start: 12:00 AM
    stop: 1:00 AM
    location: America/Bahia_Banderas
    
jobs:
- name: after-midnight-banana-check
  plan:
  - get: banana
  - get: after-midnight
    trigger: true
  
- name: banana-unit
   plan:
  - get: banana
    trigger: true
    passed: [after-midnight-banana-check]
  - task: run-unit
```

The *banana-unit* job will only run during the after-midnight time window, which is good. But it's not optimal, because as she notes, it's like using a job as a `check`, and that's gross. Additionally, it doesn't solve the first problem, of wanting to only run jobs when they have a unique set of resources available.

This feels to me like the inverse of the `passed` constraint, which leads me to this:

```
jobs:
- name: my-job
  plan:
    - get: a-resource
      not_passed: [my-job]
    - get: b-resource
```

Thoughts?
