### ISSUE TITLE
Error message on invalid docker-image repository

### ISSUE THREAD

**Issue by AustinBGibbons** [concourse/concourse#980]
# Feature Request

Hello! I had a docker-image resource-type with an incorrect repository. The resource that depended on this resource_type offered no output in the UI - it just showed "Checking successfully"

The check-resource command offered this output:

```
fly -t push check-resource -r init/git-pull-requests
error: check failed with exit status '1':
failed to fetch digest: 401 Unauthorized
```

Logging that it failed to get the docker image in the UI, or making a more clear error message, would be helpful, thanks!

**Comment by cc250080** [comment]
I completely agree, in general the error messages, even on the logs, are pretty useless, you always need to guess what is happening.

**Comment by simonjohansson** [comment]
Indeed, we had a user today very confused as to why his pipeline was not working.

```
- name: build
  serial: true
  plan:
  - get: git
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: IMAGE_THAT_DOESNT_EXIST_IN_DOCKER_HUB
          tag: latest
     .. ... ..
```

<img width="1436" alt="screen shot 2018-07-06 at 2 15 16 pm" src="https://user-images.githubusercontent.com/736248/42378278-0b1048c8-8127-11e8-9e1c-a53d0e5859cc.png">
