### ISSUE TITLE
Versioned S3 resource not able to PUT.

### ISSUE THREAD

**Issue by pms1969** [concourse/concourse#981]
* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): Binary to AWS EC2 instance
* Infrastructure/IaaS:  AWS EC2 Instance (t2.Medium - ATC and Worker)
* Browser (if applicable): N/A
* Did this used to work?  not sure.

Having issues using the s3 versioned resource type.  I've deployed to AWS EC2 instances, with a "concourse" role that has full s3 rights.

I've set up a test pipeline that looks like this.
```
jobs:
- name: test-stuff
  plan:
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      outputs:
        - name: tests
      run:
        path: /bin/ash
        args: 
        - -c
        - |
          apk update
          apk add bash
          echo this worked? >> tests/output-0.1.2.txt
  - put: test-copy-to-s3-original
    params:
      file: tests/output-*.txt
    skip-download: true

resources:
- name: test-copy-to-s3-original
  type: s3
  source:
    bucket: my-bucket
    regexp: output-(.*).txt
    region_name: eu-west-1
```

however when I kick off a run of this configuration, I get the following output from the `put`
```
13 B / 13 B [==============================================] 100.00 % 288 B/s 0serror running command: AccessDenied: Access Denied
	status code: 403, request id: 0CD819A727E90A89
```

Conversation in the Concourse slack channel was unable to shed light on the problem.

Any help welcome.
