### ISSUE TITLE
Question: Built-in resource versions

### ISSUE THREAD

**Issue by phillbaker** [concourse/concourse#984]
Hello and thanks for all the hard work on concourse! I wanted to double check my understanding of the versioning of built-in resources to clarify how we're building pipelines. 

* Concourse version: 2.6.0
* Deployment type: binary/ansible
* Infrastructure/IaaS: aws

### Background
We've recently started using [`docker-image`](https://github.com/concourse/docker-image-resource) resource to build and push images to ECR with the credential helper (:+1: for this!). The version of docker-image provided in the binary failed authentication with ECR, and what ended up working was creating an additional resource type:

```
resource_types:
  - name: updated-docker-image
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: latest
```

### Question

 It [looks like](https://github.com/concourse/concourse/blob/master/ci/pipelines/resources.yml#L267-L285) the binary versions of concourse include precompiled versions of these plugins, so does it make sense that we need the approach above? How else would webe able to get more recent versions of built-in resources?

This tripped us for a bit - would a PR to the docs to explain this be accepted?
