### ISSUE TITLE
Feature: Fly set-pipeline parameter injected with string replace

### ISSUE THREAD

**Issue by mbjelac** [concourse/concourse#985]
# Feature Request

## Fly `set-pipeline` parameter injection doesn't support prefixes and suffixes

This is clearly indicated in https://concourse.ci/fly-set-pipeline.html:

```
Note that only strings are supported for these values, so that interpolating them into the template is trivial. Other types of values, and features like concatenation, are not supported.
```

When I have several similar configuration values in my pipeline, I would like to replace *parts* of them with the same parameter placeholder so that the part that is equal for all the values can be injected with Fly's `--var` or `--load-vars-from`.

Example (doesn't work):

```
resources:
- name: artifact
  type: maven-resource
  source:
    artifact: my.group.id:dummy:jar
    url: {{artifactory-url}}/libs-snapshot-local
jobs:
...
  - task: build
        file: ci-tools/maven/build.yml
        params:
          ARTIF_URL: {{artifactory-url}}
...
```

Notice: `{{artifactory-url}}` is the same in more places, but some places require adding specific paths to the URL.

However, it seems that only "clean" placeholders are supported, i.e. a YAML value should be only a single placeholder without prefix or suffix, or entirely without placeholders. This means that I have to have a new placeholder (and a new variable in my Fly vars file) for each extension of the base value.

## Just do a string replace

Fly's `--var` or `--load-vars-from` should just do a string replace `{{placeholder}}` with the value of the `placeholder` variable. Possibly verify the placeholder is located within YAML values, and not property names.
