### ISSUE TITLE
Paused jobs can block unpaused jobs

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#994]
If there are two jobs in the same serial group, and the second job is paused, then a pending build on the second job blocks builds on the first job. Here's a simple example:

```yaml
jobs:
- name: one
  serial_groups: [ser]
  plan:
  - task: one
    config: &config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: echo
        args: ["hi"]
- name: two
  serial_groups: [ser]
  plan:
  - task: two
    config: *config
```

```bash
fly -t ci set-pipeline -p test-pausing -c pipeline.yml
fly -t ci unpause-pipeline -p test-pausing
fly -t ci pause-job -j test-pausing/two
fly -t ci trigger-job -j test-pausing/two
fly -t ci trigger-job -j test-pausing/one
```

From this situation, job `one` can never run until job `two` is unpaused, or until the pending build of job `two` is canceled. @LinuxBozo and I noticed this and found it to be counterintuitive--we would expect a paused job not to count against in-flight for a serial group.
