### ISSUE TITLE
Task output not passed to input between Windows tasks

### ISSUE THREAD

**Issue by jdeppe-pivotal** [concourse/concourse#998]
# Bug Report

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable):
* Did this used to work?

We are starting to use Concourse on Windows workers and have run into an issue. In a nutshell, the output from one windows task is not made visible as the input on a subsequent *windows* task. However, if the subsequent task is a *linux* task, then the output of the prior windows task *is* visible in the linux task.

Here is a sample of our pipeline:
```
    - task: configure-build
      config:
        platform: windows
        inputs:
          - name: nativeclient-version
            path: version
          - name: nativeclient-source
            path: source
        outputs:
          - name: build
        run:
          path: powershell
          args:
          - -command
          - |
            dir

    - task: build-all
      config:
        platform: windows
        inputs:
        - name: nativeclient-source
          path: source
        - name: build
        run:
          path: powershell
          args:
          - -command
          - |
            dir
```
The terminal output of the second task does not show the `build` directory.

If we insert an intermediate *linux* task that simply copies `build` to `build-copy` and then use 
 `build-copy` as an input in a subsequent windows task, everything works as expected.
